### ISSUE TITLE
`poetry build -f wheel` broken for C extensions

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#1332]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

## Issue
I'm trying to build a library that includes a C extension.
* `poetry build` works and creates both `.whl` and `.tar.gz`
* `poetry build -f sdist` works and creates `.tar.gz`
* `poetry build -f wheel` fails

### Error output
```
… ~/awaitwhat> poetry build -vvv --f wheel
Using virtualenv: /Users/xxx/Library/Caches/pypoetry/virtualenvs/awaitwhat-QZ4jZTXn-py3.7
Building awaitwhat (1.0)
 - Building wheel
 - Adding: /Users/xxx/awaitwhat/awaitwhat/__init__.py
 - Adding: /Users/xxx/awaitwhat/awaitwhat/what.c

[EnvCommandError]
Command ['/Users/xxx/Library/Caches/pypoetry/virtualenvs/awaitwhat-QZ4jZTXn-py3.7/bin/python', '/Users/xxx/awaitwhat/setup.py', 'build', '-b', '/Users/xxx/awaitwhat/build'] errored with the following return code 2, and output:
/Library/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/Users/xxx/awaitwhat/setup.py': [Errno 2] No such file or directory


Traceback (most recent call last):
  File "/Users/xxx/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 132, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/xxx/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 119, in handle
    status_code = self._do_handle(args, io)
  File "/Users/xxx/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 167, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/xxx/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/xxx/.poetry/lib/poetry/console/commands/build.py", line 30, in handle
    builder.build(fmt)
  File "/Users/xxx/.poetry/lib/poetry/masonry/builder.py", line 21, in build
    return builder.build()
  File "/Users/xxx/.poetry/lib/poetry/masonry/builders/wheel.py", line 81, in build
    self._build(zip_file)
  File "/Users/xxx/.poetry/lib/poetry/masonry/builders/wheel.py", line 104, in _build
    'python', str(setup), 'build', '-b', str(self._path / 'build')
  File "/Users/xxx/.poetry/lib/poetry/utils/env.py", line 875, in run
    return super(VirtualEnv, self).run(bin, *args, **kwargs)
  File "/Users/xxx/.poetry/lib/poetry/utils/env.py", line 708, in run
    raise EnvCommandError(e, input=input_)
```

### Environment

```
… ~/awaitwhat> uname
Darwin
… ~/awaitwhat> poetry --version
Poetry version 1.0.0b1
```

### Source code

https://github.com/dimaqq/awaitwhat/tree/poetry/issues/1332
(I've tagged my library `poetry/issues/1332` at the point where issue can be reproduced)

**Comment by dimaqq** [comment]
It's still broken:

```
… ~/awaitwhat> poetry build -f wheel
Building awaitwhat (19.1a5)
 - Building wheel

[EnvCommandError]
Command ['/Users/dima.tisnek/Library/Caches/pypoetry/virtualenvs/awaitwhat-QZ4jZTXn-py3.8/bin/python', '/Users/dima.tisnek/awaitwhat/setup.py', 'build', '-b', '/Users/dima.tisnek/awaitwhat/build'] errored with the following return code 2, and output:
/Users/dima.tisnek/Library/Caches/pypoetry/virtualenvs/awaitwhat-QZ4jZTXn-py3.8/bin/python: can't open file '/Users/dima.tisnek/awaitwhat/setup.py': [Errno 2] No such file or directory

… ~/awaitwhat> poetry build
Building awaitwhat (19.1a5)
 - Building sdist
 - Built awaitwhat-19.1a5.tar.gz

 - Building wheel
 - Built awaitwhat-19.1a5-cp38-cp38-macosx_10_9_x86_64.whl
… ~/awaitwhat> poetry --version
Poetry version 1.0.0b3
```

**Comment by dimaqq** [comment]
And it's still broken on newest poetry, 1.0.0b4:

```
… ~/awaitwhat> poetry --version
Poetry version 1.0.0b4
… ~/awaitwhat> poetry build
Building awaitwhat (19.1a5)
 - Building sdist
 - Built awaitwhat-19.1a5.tar.gz

 - Building wheel
 - Built awaitwhat-19.1a5-cp38-cp38-macosx_10_9_x86_64.whl
… ~/awaitwhat> poetry build -f wheel
Building awaitwhat (19.1a5)
 - Building wheel

[EnvCommandError]
Command ['/Users/dima.tisnek/Library/Caches/pypoetry/virtualenvs/awaitwhat-QZ4jZTXn-py3.8/bin/python', '/Users/dima.tisnek/awaitwhat/setup.py', 'build', '-b', '/Users/dima.tisnek/awaitwhat/build'] errored with the following return code 2, and output:
/Users/dima.tisnek/Library/Caches/pypoetry/virtualenvs/awaitwhat-QZ4jZTXn-py3.8/bin/python: can't open file '/Users/dima.tisnek/awaitwhat/setup.py': [Errno 2] No such file or directory

… ~/awaitwhat>
```

**Comment by jhrmnn** [comment]
Because of this bug, [pendulum](https://github.com/sdispater/pendulum) cannot be installed directly from a git repository:

```
19:44 ~/Downloads 🐟 venv/bin/pip install git+https://github.com/sdispater/pendulum
Collecting git+https://github.com/sdispater/pendulum
  Cloning https://github.com/sdispater/pendulum to /private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-req-build-iezlj1rb
  Running command git clone -q https://github.com/sdispater/pendulum /private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-req-build-iezlj1rb
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
    Preparing wheel metadata ... done
Collecting python-dateutil<3.0,>=2.6 (from pendulum==2.0.5)
  Using cached https://files.pythonhosted.org/packages/d4/70/d60450c3dd48ef87586924207ae8907090de0b306af2bce5d134d78615cb/python_dateutil-2.8.1-py2.py3-none-any.whl
Collecting pytzdata>=2018.3 (from pendulum==2.0.5)
  Using cached https://files.pythonhosted.org/packages/7f/f9/cdd39831b0465285c02ed90cfbf0db25bb951cb2a35ded0e69222375bea3/pytzdata-2019.3-py2.py3-none-any.whl
Collecting six>=1.5 (from python-dateutil<3.0,>=2.6->pendulum==2.0.5)
  Using cached https://files.pythonhosted.org/packages/65/26/32b8464df2a97e6dd1b656ed26b2c194606c16fe163c695a992b36c11cdf/six-1.13.0-py2.py3-none-any.whl
Building wheels for collected packages: pendulum
  Building wheel for pendulum (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/jhermann/Downloads/venv/bin/python3 /Users/jhermann/Downloads/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/tmp2aa389cj
       cwd: /private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-req-build-iezlj1rb
  Complete output (33 lines):
  Traceback (most recent call last):
    File "/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-build-env-ak3yf4h0/overlay/lib/python3.7/site-packages/poetry/utils/env.py", line 830, in _run
      cmd, stderr=subprocess.STDOUT, **kwargs
    File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/subprocess.py", line 411, in check_output
      **kwargs).stdout
    File "/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-build-env-ak3yf4h0/overlay/lib/python3.7/site-packages/poetry/utils/_compat.py", line 206, in run
      retcode, process.args, output=stdout, stderr=stderr
  poetry.utils._compat.CalledProcessError: Command '['/Users/jhermann/Downloads/venv/bin/python', 'setup.py', 'build', '-b', 'build']' returned non-zero exit status 2.

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/Users/jhermann/Downloads/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/Users/jhermann/Downloads/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/Users/jhermann/Downloads/venv/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 141, in build_wheel
      metadata_directory)
    File "/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-build-env-ak3yf4h0/overlay/lib/python3.7/site-packages/poetry/masonry/api.py", line 62, in build_wheel
      poetry, SystemEnv(Path(sys.prefix)), NullIO(), Path(wheel_directory)
    File "/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-build-env-ak3yf4h0/overlay/lib/python3.7/site-packages/poetry/masonry/builders/wheel.py", line 55,in make_in
      wb.build()
    File "/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-build-env-ak3yf4h0/overlay/lib/python3.7/site-packages/poetry/masonry/builders/wheel.py", line 81,in build
      self._build(zip_file)
    File "/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-build-env-ak3yf4h0/overlay/lib/python3.7/site-packages/poetry/masonry/builders/wheel.py", line 104, in _build
      "python", str(setup), "build", "-b", str(self._path / "build")
    File "/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-build-env-ak3yf4h0/overlay/lib/python3.7/site-packages/poetry/utils/env.py", line 796, in run
      return self._run(cmd, **kwargs)
    File "/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-build-env-ak3yf4h0/overlay/lib/python3.7/site-packages/poetry/utils/env.py", line 833, in _run
      raise EnvCommandError(e, input=input_)
  poetry.utils.env.EnvCommandError: Command ['/Users/jhermann/Downloads/venv/bin/python', 'setup.py', 'build', '-b', 'build'] errored with the following return code 2, and output:
  /usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/Resources/Python.app/Contents/MacOS/Python: can't open file 'setup.py': [Errno 2] No such file or directory

  ----------------------------------------
  ERROR: Failed building wheel for pendulum
  Running setup.py clean for pendulum
  ERROR: Command errored out with exit status 1:
   command: /Users/jhermann/Downloads/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-req-build-iezlj1rb/setup.py'"'"'; __file__='"'"'/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-req-build-iezlj1rb/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: /private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-req-build-iezlj1rb
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/tokenize.py", line 447, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: '/private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-req-build-iezlj1rb/setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for pendulum
Failed to build pendulum
ERROR: Could not build wheels for pendulum which use PEP 517 and cannot be installed directly
```

This is unlike, say, [cleo](https://github.com/sdispater/pendulum), which can be installed just fine:

```
19:49 ~/Downloads 🐟 venv/bin/pip install git+https://github.com/sdispater/cleo
Collecting git+https://github.com/sdispater/cleo
  Cloning https://github.com/sdispater/cleo to /private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-req-build-sqo5wk0b
  Running command git clone -q https://github.com/sdispater/cleo /private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-req-build-sqo5wk0b
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Collecting clikit<0.5.0,>=0.4.0 (from cleo==0.7.6)
  Using cached https://files.pythonhosted.org/packages/38/96/1fa492dcca7610640b29a4c417abe5a6237d27bd9b29d9641459ebe7f100/clikit-0.4.0-py2.py3-none-any.whl
Collecting pastel<0.2.0,>=0.1.0 (from clikit<0.5.0,>=0.4.0->cleo==0.7.6)
  Using cached https://files.pythonhosted.org/packages/09/b9/ca6434777928cc4e25cd17a8d2a913f3c2877ce54c5a7b7c18bf646ff257/pastel-0.1.1-py2.py3-none-any.whl
Collecting pylev<2.0,>=1.3 (from clikit<0.5.0,>=0.4.0->cleo==0.7.6)
  Using cached https://files.pythonhosted.org/packages/40/1c/7dff1d242bf1e19f9c6202f0ba4e6fd18cc7ecb8bc85b17b2d16c806e228/pylev-1.3.0-py2.py3-none-any.whl
Building wheels for collected packages: cleo
  Building wheel for cleo (PEP 517) ... done
  Created wheel for cleo: filename=cleo-0.7.6-cp37-none-any.whl size=21225 sha256=6fe65f58319597159305396e867a0bac05eeb9781f9ed61b7e8bef2828346ea8
  Stored in directory: /private/var/folders/z6/1mrv40ys089cm2mr70pg44r1wr6l3c/T/pip-ephem-wheel-cache-_o0f9xe2/wheels/aa/ea/09/71f6dbd07c2c95756f50d253ef1641f72590b708e41645a69a
Successfully built cleo
Installing collected packages: pastel, pylev, clikit, cleo
Successfully installed cleo-0.7.6 clikit-0.4.0 pastel-0.1.1 pylev-1.3.0
```

**Comment by jhrmnn** [comment]
Seems to persist with 1.0.0.

**Comment by jhrmnn** [comment]
If I understand the issue correctly, the problem is that for packages with a `build` option, `WheelBuilder` actually calls `python setup.py build` to build the C extensions. This works with `poetry build`, because that uses `CompleteBuilder`, which creates a source distribution first (which generates `setup.py`), and the creates the wheel from that distribution (so at that point `setup.py` already exists—the generated one). But with `poetry build -f wheel`, `setup.py` is not generated.

So I don't think this is a bug, it's just that this scenario (building a wheel from the source tree without building a source distribution first) has never been considered at all by the current code.

This also causes the PEP 517 build too fail, because Pip apparently attempts to create the wheel directly from the source tree, even though PEP 517 [says](https://www.python.org/dev/peps/pep-0517/#build-wheel):

> To ensure that wheels from different sources are built the same way, frontends may call build_sdist first, and then call build_wheel in the unpacked sdist. But if the backend indicates that it is missing some requirements for creating an sdist (see below), the frontend will fall back to calling build_wheel in the source directory.

@sdispater What would be the course of action here? Could we add a safe check that ensures that the wheel builder always uses a generated source distribution rather than the source tree if the package contains the `build` option?

**Comment by jhrmnn** [comment]
A hack that fixes the PEP 517 issue is to have this in `pyproject.toml`:
```toml
[build-system]
backend-path = ["."]
build-backend = "mocked_poetry_masonry_api"
```
and then this in `mocked_poetry_masonry_api.py`:
```python
import sys
import os
import tarfile
from contextlib import contextmanager
from pathlib import Path

from clikit.io import NullIO

from poetry.factory import Factory
from poetry.utils._compat import unicode
from poetry.utils.env import SystemEnv
from poetry.utils.helpers import temporary_directory

from poetry.masonry.builders.sdist import SdistBuilder
from poetry.masonry.builders.wheel import WheelBuilder
from poetry.masonry.api import *


@contextmanager
def _unpacked_tarball(path):
    tf = tarfile.open(str(path))

    with temporary_directory() as tmpdir:
        tf.extractall(tmpdir)
        files = os.listdir(tmpdir)

        assert len(files) == 1, files

        yield Path(tmpdir) / files[0]


def build_wheel(wheel_directory, config_settings=None, metadata_directory=None):
    """Builds a wheel, places it in wheel_directory"""

    poetry = Factory().create_poetry(Path('.'))
    env = SystemEnv(Path(sys.prefix))

    with temporary_directory() as tmpdir_sdist:
        sdist_file = SdistBuilder(poetry, env, NullIO()).build(
            Path(tmpdir_sdist)
        )
        with _unpacked_tarball(sdist_file) as tmpdir:
            return unicode(
                WheelBuilder.make_in(
                    Factory().create_poetry(tmpdir),
                    env,
                    NullIO(),
                    Path(wheel_directory),
                    original=poetry,
                )
            )
```

The latter is just a patch of `poetry.masonry.api.build_wheel()` that does what `CompleteBuilder` does, that is building the wheel from a temporary source distribution.
