### ISSUE TITLE
Keyring error on every command

### ISSUE THREAD

**Issue by lpfann** [python-poetry/poetry#1335]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 30 Gnome
- **Poetry version**: 1.0.0b1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/lpfann/d452508a400b15d63091e18d25e964f6

## Issue
On the latest beta release I encounter the following output when running any poetry command.
Poetry still works fine despite those messages.
It is probably related to #774 .

```
Error initializing plugin EntryPoint('Gnome', 'keyrings.alt.Gnome', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/Gnome.py", line 11, in <module>
    from keyring.py27compat import unicode_str
ModuleNotFoundError: No module named 'keyring.py27compat'
Error initializing plugin EntryPoint('Google', 'keyrings.alt.Google', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/Google.py", line 18, in <module>
    from keyring.py27compat import input, pickle
ModuleNotFoundError: No module named 'keyring.py27compat'
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/file_base.py", line 7, in <module>
    from keyring.py27compat import configparser
ModuleNotFoundError: No module named 'keyring.py27compat'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/file.py", line 9, in <module>
    from keyring.py27compat import configparser
ModuleNotFoundError: No module named 'keyring.py27compat'
Error initializing plugin EntryPoint('kwallet', 'keyrings.alt.kwallet', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/kwallet.py", line 6, in <module>
    from keyring.py27compat import unicode_str
ModuleNotFoundError: No module named 'keyring.py27compat'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '1.3')).
Traceback (most recent call last):
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/lpfannschmidt/.poetry/lib/poetry/_vendor/py3.7/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/lpfannschmidt/anaconda3/lib/python3.7/site-packages/keyrings/alt/pyfs.py", line 5, in <module>
    from keyring.py27compat import configparser
ModuleNotFoundError: No module named 'keyring.py27compat'
```

**Comment by pydolan** [comment]
I'm also getting this error using a Pyenv install of Python 3.7.5 and Poetry v1.0.0b6.  Reverting back to Poetry v0.12.17 removes the error.

**Comment by PsiPhire** [comment]
I'm also getting this error with Poetry v1.0.0a5 through Poetry v1.0.0b8 on Ubuntu 18.04.3 LTS. Reverting back to Poetry v0.12.17 fixes it. I'm not using anaconda. 

Full error:
```
Error initializing plugin EntryPoint('Windows (alt)', 'keyrings.alt.Windows', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/zander/.poetry/lib/poetry/_vendor/py3.6/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/zander/.poetry/lib/poetry/_vendor/py3.6/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/Windows.py", line 9, in <module>
    from . import file_base
  File "/usr/lib/python3/dist-packages/keyrings/alt/file_base.py", line 13, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('file', 'keyrings.alt.file', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/zander/.poetry/lib/poetry/_vendor/py3.6/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/zander/.poetry/lib/poetry/_vendor/py3.6/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/file.py", line 11, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
Error initializing plugin EntryPoint('pyfs', 'keyrings.alt.pyfs', None, Distribution('keyrings.alt', '3.0')).
Traceback (most recent call last):
  File "/home/zander/.poetry/lib/poetry/_vendor/py3.6/keyring/backend.py", line 188, in _load_plugins
    init_func = ep.load()
  File "/home/zander/.poetry/lib/poetry/_vendor/py3.6/entrypoints.py", line 82, in load
    mod = import_module(self.module_name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3/dist-packages/keyrings/alt/pyfs.py", line 8, in <module>
    from keyring.util.escape import escape as escape_for_ini
ModuleNotFoundError: No module named 'keyring.util.escape'
```

**Comment by danieleades** [comment]
i'm seeing this on poetry 1.0.3

**Comment by thoward27** [comment]
Same for me, version 1.0.3

**Comment by cbpygit** [comment]
Very similar issue on my end, which suddenly shows up on *every* poetry command although I didn't touch the poetry installation on my system:
```
>>> poetry debug

Poetry
Error initializing plugin EntryPoint(name='macOS', value='keyring.backends.macOS', group='keyring.backends').
Traceback (most recent call last):
  File "~/.poetry/lib/poetry/_vendor/py3.8/keyring/backend.py", line 198, in _load_plugins
    init_func = ep.load()
  File "~/.pyenv/versions/3.8.6/lib/python3.8/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "~/.pyenv/versions/3.8.6/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'keyring.backends.macOS'
Version: 1.1.4
Python:  3.8.6

Virtualenv
Python:         3.8.6
Implementation: CPython
Path:           ~/.cache/pypoetry/virtualenvs/shared-python-logging-Q4CTD019-py3.8
Valid:          True

System
Platform: linux
OS:       posix
Python:   ~/.pyenv/versions/3.8.6
```

Especially weird as I am running on Ubuntu, and the error mentions macOS.
