### ISSUE TITLE
Fresh install broken in Py 3.8 docker

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#1377]
Maybe related to #553

```
> docker run -it --rm python:3.8.0b4-buster /bin/sh
# curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile file located at:

$HOME/.profile

You can uninstall at any time with `poetry self:uninstall`,
or by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 0.12.17
  - Downloading poetry-0.12.17-linux.tar.gz (8.37MB)

Poetry (0.12.17) is installed now. Great!

To get started you need Poetry's bin directory ($HOME/.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run `source $HOME/.poetry/env`

# $HOME/.poetry/bin/poetry
Traceback (most recent call last):
  File "/root/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/root/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/root/.poetry/lib/poetry/console/application.py", line 6, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
#
```

**Comment by dimaqq** [comment]
Could it be that `3.8` is missing from this list?
```
# find / -name cleo
/root/.poetry/lib/poetry/_vendor/py3.4/cleo
/root/.poetry/lib/poetry/_vendor/py3.6/cleo
/root/.poetry/lib/poetry/_vendor/py3.7/cleo
/root/.poetry/lib/poetry/_vendor/py3.5/cleo
/root/.poetry/lib/poetry/_vendor/py2.7/cleo
```

**Comment by dmontagu** [comment]
I wonder if this section is related:
https://github.com/sdispater/poetry/blob/cb8dc0d94e68042f120441b4e30d89c92598b40e/sonnet#L30

**Comment by dmontagu** [comment]
> Could it be that 3.8 is missing from this list?

Indeed, running

```sh
cp -r /root/.poetry/lib/poetry/_vendor/py3.7 /root/.poetry/lib/poetry/_vendor/py3.8
```

right after the `curl` install command seems to work for me (in the python3.8 docker image you were using).

I don't know if there are any lurking incompatibilties between the 3.7 and 3.8 versions though.

**Comment by deepio** [comment]
This doesn't only happen in docker, **dimaqq** it seems anything except those versions mentioned by **dmontagu** will have this issue. Maybe when main python becomes 3.8 on October 14th this issue will get looked at?

```python
poetry install
Traceback (most recent call last):
  File "/home/travis/.poetry/bin/poetry", line 12, in <module>
    from poetry.console import main
  File "/home/travis/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/travis/.poetry/lib/poetry/console/application.py", line 6, in <module>
    from cleo import Application as BaseApplication
ModuleNotFoundError: No module named 'cleo'
The command "poetry install" failed and exited with 1 during .
```

**Comment by Gr1N** [comment]
Got the same issue.

Poetry version 0.12.17, installed into fresh `python:3.8.0-buster` container using `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python`.

@sdispater can you help us, please?

**Comment by sdispater** [comment]
The full `0.12.17` release  (with bundled dependencies) does not support Python 3.8 since the dependencies for it have not been bundled.

For Python 3.8, you might want to install Poetry with `pip` or try the latest `1.0.0b2` version.

I will see if I can make a `0.12.18` release, or even update the archives of the `0.12.17` with support for Python 3.8.

I will keep you updated.
