### ISSUE TITLE
impossible to install poetry on python 2.7

### ISSUE THREAD

**Issue by NargiT** [python-poetry/poetry#1467]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ubuntu 18.04.3 LTS
- **Poetry version**: poetry-1.0.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: not a issue running poetry
## Issue

```
virtualenv --python=python2.7 toto
source toto/bin/activate
pip install poetry
...
...
Collecting more-itertools
...
ERROR: Package 'more-itertools' requires a different Python: 2.7.16 not in '>=3.4'
```

What am I  doing wrong ? I though it's compatible with 2.7?

**Comment by NargiT** [comment]
The workaround I found is to install more-itertools==4.0.0

But when I try to run `poetry` i get another issue.

```
Traceback (most recent call last):
  File "/home/ttchougo/workspace/ttchougo/itconfig-reader/toto/bin/poetry", line 5, in <module>
    from poetry.console import main
  File "/home/ttchougo/workspace/ttchougo/itconfig-reader/toto/lib/python2.7/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/ttchougo/workspace/ttchougo/itconfig-reader/toto/lib/python2.7/site-packages/poetry/console/application.py", line 7, in <module>
    from .commands import AboutCommand
  File "/home/ttchougo/workspace/ttchougo/itconfig-reader/toto/lib/python2.7/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/ttchougo/workspace/ttchougo/itconfig-reader/toto/lib/python2.7/site-packages/poetry/console/commands/check.py", line 1, in <module>
    from poetry.factory import Factory
  File "/home/ttchougo/workspace/ttchougo/itconfig-reader/toto/lib/python2.7/site-packages/poetry/factory.py", line 21, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/home/ttchougo/workspace/ttchougo/itconfig-reader/toto/lib/python2.7/site-packages/poetry/repositories/pypi_repository.py", line 38, in <module>
    from poetry.utils.inspector import Inspector
  File "/home/ttchougo/workspace/ttchougo/itconfig-reader/toto/lib/python2.7/site-packages/poetry/utils/inspector.py", line 9, in <module>
    from bz2 import BZ2File
ImportError: No module named bz2
```

**Comment by NargiT** [comment]
installing `sudo apt-get install libbz2-dev` and rerunning the virtual env made it work.

but I do not understand why from a clean virtual env I get the wrong version of `more-itertools`

**Comment by lithammer** [comment]
We're running into the same issue. But because of the build isolation (PEP 517/518) it doesn't matter if I install an older version of more-itertools or not since it will still try to install the latest version of more-itertools into the isolated build environment.

One solution could be to publish more wheels using https://github.com/pypa/manylinux or https://github.com/joerick/cibuildwheel.

**Comment by lithammer** [comment]
A hacky workaround to install pendulum which requires poetry to build from source:

```sh
./env/bin/pip install 'more-itertools<6'
./env/bin/pip install poetry
./env/bin/pip install --no-build-isolation pendulum==2.0.4
```

**Comment by sdispater** [comment]
@NargiT Could you provide the complete output of `pip install poetry`?

**Comment by NargiT** [comment]
Sorry for the delay, I will post asap the output.

**Comment by dimbleby** [comment]
I bet that the root of the issue is: you are using a very old version of `pip`, which does not understand `python_requires`, and which therefore is willing to install a recent `more-itertools` even though that project has dropped python2 support.

Try upgrading `pip` before installing `poetry`.

**Comment by NargiT** [comment]
Here is the full output.

@dimbleby, pip version inside the virtual env is 19.3.1

```
$ virtualenv --python=python2.7 toto
Running virtualenv with interpreter /home/ttchougo/.pyenv/shims/python2.7
New python executable in /home/ttchougo/workspace/toto/bin/python2.7
Also creating executable in /home/ttchougo/workspace/toto/bin/python
Installing setuptools, pip, wheel...
done.
$ source toto/bin/activate
 toto > $ pip --version
pip 19.3.1 from /home/ttchougo/workspace/toto/local/lib/python2.7/site-packages/pip (python 2.7)
 toto > $ pip install poetry
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7. More details about Python 2 support in pip, can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support
Looking in indexes: https://internal.mirror.ch/repository/pypi/simple
Collecting poetry
  Using cached https://internal.mirror.ch/repository/pypi/packages/c9/76/214acc400055aa0045ed21ce25378225b1887c5c091f99476955bf9f6984/poetry-0.12.17-py2.py3-none-any.whl
Processing /home/ttchougo/.cache/pip/wheels/25/b3/fc/9353c534571416d2f9bdeb14666ad865a9b70b5fd5270e549e/glob2-0.6-py2.py3-none-any.whl
Collecting virtualenv<17.0,>=16.0; python_version >= "2.7" and python_version < "2.8"
  Using cached https://internal.mirror.ch/repository/pypi/packages/89/66/786e0d6f61bd0612f431e19b016d1ae46f1cb8d21a80352cc6774ec876e3/virtualenv-16.7.6-py2.py3-none-any.whl
Collecting pathlib2<3.0,>=2.3; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.4" and python_version < "3.5"
  Using cached https://internal.mirror.ch/repository/pypi/packages/e9/45/9c82d3666af4ef9f221cbb954e1d77ddbb513faf552aea6df5f37f1a4859/pathlib2-2.3.5-py2.py3-none-any.whl
Processing /home/ttchougo/.cache/pip/wheels/0a/61/2e/ca89d31e148ca2f867e411a6fa1c7fc8d41cebab1e8f66b0ad/pyrsistent-0.14.11-cp27-cp27mu-linux_x86_64.whl
Processing /home/ttchougo/.cache/pip/wheels/36/07/b1/92ca9e6c714d6fe126af8b6edff4d780a963cee492e90b00de/subprocess32-3.5.4-cp27-cp27mu-linux_x86_64.whl
Collecting pkginfo<2.0,>=1.4
  Using cached https://internal.mirror.ch/repository/pypi/packages/e6/d5/451b913307b478c49eb29084916639dc53a88489b993530fed0a66bab8b9/pkginfo-1.5.0.1-py2.py3-none-any.whl
Collecting html5lib<2.0,>=1.0
  Using cached https://internal.mirror.ch/repository/pypi/packages/a5/62/bbd2be0e7943ec8504b517e62bab011b4946e1258842bc159e5dfde15b96/html5lib-1.0.1-py2.py3-none-any.whl
Collecting jsonschema<4.0,>=3.0a3
  Using cached https://internal.mirror.ch/repository/pypi/packages/ce/6c/888d7c3c1fce3974c88a01a6bc553528c99d3586e098eee23e8383dd11c3/jsonschema-3.1.1-py2.py3-none-any.whl
Collecting pyparsing<3.0,>=2.2
  Using cached https://internal.mirror.ch/repository/pypi/packages/11/fa/0160cd525c62d7abd076a070ff02b2b94de589f1a9789774f17d7c54058e/pyparsing-2.4.2-py2.py3-none-any.whl
Collecting tomlkit<0.6.0,>=0.5.1
  Using cached https://internal.mirror.ch/repository/pypi/packages/3e/30/7c2693fc50bd466285ec22bf02ee344be1bde3e2e8267e302fdc82d11f2d/tomlkit-0.5.8-py2.py3-none-any.whl
Collecting cleo<0.7.0,>=0.6.7
  Using cached https://internal.mirror.ch/repository/pypi/packages/a7/b9/270301a3a87587f09bc3985973f2e362ffa45fa5fcd5128501516b2f5e31/cleo-0.6.8-py2.py3-none-any.whl
Processing /home/ttchougo/.cache/pip/wheels/20/18/db/972028182164c4fabe6c89083376eb6e82a31fa9d95d57b5d6/functools32-3.2.3.post2-cp27-none-any.whl
Collecting cachy<0.3,>=0.2
  Using cached https://internal.mirror.ch/repository/pypi/packages/26/37/8ce3e7b330078b6797a34e79a80a8ad6935e404a3b903765417182c9ce19/cachy-0.2.0-py2.py3-none-any.whl
Processing /home/ttchougo/.cache/pip/wheels/ee/16/11/c4ce1f2609643540df56b8340ec8bd5ff41b8d861c523d6699/CacheControl-0.12.5-cp27-none-any.whl
Collecting requests-toolbelt<0.9.0,>=0.8.0
  Using cached https://internal.mirror.ch/repository/pypi/packages/97/8a/d710f792d6f6ecc089c5e55b66e66c3f2f35516a1ede5a8f54c13350ffb0/requests_toolbelt-0.8.0-py2.py3-none-any.whl
Collecting shellingham<2.0,>=1.1
  Using cached https://internal.mirror.ch/repository/pypi/packages/2d/ac/e8a34d4b3d24bf554f40651b2aac549a3fc7223725bf10fbdfe2083b6372/shellingham-1.3.1-py2.py3-none-any.whl
Collecting typing<4.0,>=3.6; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.4" and python_version < "3.5"
  Using cached https://internal.mirror.ch/repository/pypi/packages/22/30/64ca29543375759dc589ade14a6cd36382abf2bec17d67de8481bc9814d7/typing-3.7.4.1-py2-none-any.whl
Collecting requests<3.0,>=2.18
  Using cached https://internal.mirror.ch/repository/pypi/packages/51/bd/23c926cd341ea6b7dd0b2a00aba99ae0f828be89d72b2190f27c11d4b7fb/requests-2.22.0-py2.py3-none-any.whl
Collecting six
  Using cached https://internal.mirror.ch/repository/pypi/packages/73/fb/00a976f728d0d1fecfe898238ce23f502a721c0ac0ecfedb80e0d88c64e9/six-1.12.0-py2.py3-none-any.whl
Processing /home/ttchougo/.cache/pip/wheels/f1/16/ab/d2796b6d507aa6a67b6669af0d7a45d48b36b38514cf30f818/scandir-1.10.0-cp27-cp27mu-linux_x86_64.whl
Collecting webencodings
  Using cached https://internal.mirror.ch/repository/pypi/packages/f4/24/2a3e3df732393fed8b3ebf2ec078f05546de641fe1b667ee316ec1dcf3b7/webencodings-0.5.1-py2.py3-none-any.whl
Requirement already satisfied: setuptools in ./toto/lib/python2.7/site-packages (from jsonschema<4.0,>=3.0a3->poetry) (41.4.0)
Collecting attrs>=17.4.0
  Using cached https://internal.mirror.ch/repository/pypi/packages/a2/db/4313ab3be961f7a763066401fb77f7748373b6094076ae2bda2806988af6/attrs-19.3.0-py2.py3-none-any.whl
Collecting importlib-metadata
  Using cached https://internal.mirror.ch/repository/pypi/packages/f6/d2/40b3fa882147719744e6aa50ac39cf7a22a913cbcba86a0371176c425a3b/importlib_metadata-0.23-py2.py3-none-any.whl
Collecting enum34<2.0,>=1.1; python_version >= "2.7" and python_version < "2.8"
  Using cached https://internal.mirror.ch/repository/pypi/packages/c5/db/e56e6b4bbac7c4a06de1c50de6fe1ef3810018ae11732a50f15f62c7d050/enum34-1.1.6-py2-none-any.whl
Collecting pastel<0.2.0,>=0.1.0
  Using cached https://internal.mirror.ch/repository/pypi/packages/09/b9/ca6434777928cc4e25cd17a8d2a913f3c2877ce54c5a7b7c18bf646ff257/pastel-0.1.1-py2.py3-none-any.whl
Collecting pylev<2.0,>=1.3
  Using cached https://internal.mirror.ch/repository/pypi/packages/40/1c/7dff1d242bf1e19f9c6202f0ba4e6fd18cc7ecb8bc85b17b2d16c806e228/pylev-1.3.0-py2.py3-none-any.whl
Collecting msgpack
  Using cached https://internal.mirror.ch/repository/pypi/packages/ea/31/3c12ea064e9ccf113082dcdb01b683a5540ca3a3e3dbf02c05e9d30ec73f/msgpack-0.6.2-cp27-cp27mu-manylinux1_x86_64.whl
Collecting lockfile>=0.9; extra == "filecache"
  Using cached https://internal.mirror.ch/repository/pypi/packages/c8/22/9460e311f340cb62d26a38c419b1381b8593b0bb6b5d1f056938b086d362/lockfile-0.12.2-py2.py3-none-any.whl
Collecting urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1
  Using cached https://internal.mirror.ch/repository/pypi/packages/e0/da/55f51ea951e1b7c63a579c09dd7db825bb730ec1fe9c0180fc77bfb31448/urllib3-1.25.6-py2.py3-none-any.whl
Collecting certifi>=2017.4.17
  Using cached https://internal.mirror.ch/repository/pypi/packages/18/b0/8146a4f8dd402f60744fa380bc73ca47303cccf8b9190fd16a827281eac2/certifi-2019.9.11-py2.py3-none-any.whl
Collecting chardet<3.1.0,>=3.0.2
  Using cached https://internal.mirror.ch/repository/pypi/packages/bc/a9/01ffebfb562e4274b6487b4bb1ddec7ca55ec7510b22e4c51f14098443b8/chardet-3.0.4-py2.py3-none-any.whl
Collecting idna<2.9,>=2.5
  Using cached https://internal.mirror.ch/repository/pypi/packages/14/2c/cd551d81dbe15200be1cf41cd03869a46fe7226e7450af7a6545bfc474c9/idna-2.8-py2.py3-none-any.whl
Collecting zipp>=0.5
  Using cached https://internal.mirror.ch/repository/pypi/packages/74/3d/1ee25a26411ba0401b43c6376d2316a71addcc72ef8690b101b4ea56d76a/zipp-0.6.0-py2.py3-none-any.whl
Collecting configparser>=3.5; python_version < "3"
  Using cached https://internal.mirror.ch/repository/pypi/packages/7a/2a/95ed0501cf5d8709490b1d3a3f9b5cf340da6c433f896bbe9ce08dbe6785/configparser-4.0.2-py2.py3-none-any.whl
Collecting contextlib2; python_version < "3"
  Using cached https://internal.mirror.ch/repository/pypi/packages/85/60/370352f7ef6aa96c52fb001831622f50f923c1d575427d021b8ab3311236/contextlib2-0.6.0.post1-py2.py3-none-any.whl
Collecting more-itertools
  Using cached https://internal.mirror.ch/repository/pypi/packages/c2/31/45f61c8927c9550109f1c4b99ba3ca66d328d889a9c9853a808bff1c9fa0/more-itertools-7.2.0.tar.gz
ERROR: Package 'more-itertools' requires a different Python: 2.7.15 not in '>=3.4'
```

**Comment by sgleske-ias** [comment]
https://github.com/sdispater/poetry/issues/1467#issuecomment-542853865 was a great comment but just to shortcut my pain for others... it does not work on CentOS 7.  According to https://github.com/sdispater/pendulum/issues/185#issuecomment-512136079 it requires a slight modification to downgrade pip to 18.1.

# Debian workaround

Basically I replicated https://github.com/sdispater/poetry/issues/1467#issuecomment-542853865 successfully in Debian.

```bash
virtualenv -p python2.7 /tmp/venv
source /tmp/venv/bin/activate

#now inside of a fresh virtualenv

pip install -U pip==19.3.1 setuptools==41.6.0
pip install more-itertools==5.0.0 poetry==0.12.17
pip install --no-build-isolation pendulum==2.0.5
```

# CentOS 7 workaround

From https://github.com/sdispater/pendulum/issues/185#issuecomment-512136079

CentOS 7 doesn't work with pip 19+ so you must install pip 18.1

```bash
virtualenv -p python2.7 /tmp/venv
source /tmp/venv/bin/activate

#now inside of a fresh virtualenv

pip install -U pip==18.1 setuptools==41.6.0
pip install more-itertools==5.0.0 poetry==0.12.17
pip install --no-build-isolation pendulum==2.0.5
```

Thanks to @lithammer and @cognifloyd from that other comment.
