### ISSUE TITLE
Could not parse version constraint: //github.com/pyinstaller/pyinstaller.git

### ISSUE THREAD

**Issue by mozesa** [python-poetry/poetry#1489]
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://poetry.eustace.io/docs/) and believe that my question is not covered.

## Issue
I would like to install the current _development_ version of PyInstaller.

What I tried was `poetry add git+https://github.com/pyinstaller/pyinstaller/archive/develop.tar`

But whenever I invoke the command, I get the following error message:
```python
[ValueError]
Could not parse version constraint: //github.com/pyinstaller/pyinstaller.git
```

What mistake did I make?

Thanks is advance.

P.S.: I go without any error when I try the link given on PyInstaller's website.
`pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz`

**Comment by mozesa** [comment]
```
(venv) C:\Users\Dia\PycharmProjects\new-git\EE>poetry add "https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz" -vvv
Using virtualenv: C:\Users\Dia\PycharmProjects\new-git\venv

Updating dependencies
Resolving dependencies...
   1: fact: ee is 0.1.0
   1: derived: ee
   1: fact: ee depends on unzipped-egg (*)
   1: fact: ee depends on pytest (^3.0)
   1: selecting ee (0.1.0)
   1: derived: pytest (^3.0)
   1: derived: unzipped-egg (*)
PyPI: 44 packages found for pytest >=3.0,<4.0
   1: fact: unzipped-egg (0.1) depends on altgraph (*)
   1: selecting unzipped-egg (0.1 https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz)
   1: derived: altgraph (*)
PyPI: 16 packages found for altgraph *
   1: selecting altgraph (0.16.1)
   1: fact: pytest (3.10.1) depends on py (>=1.5.0)
   1: fact: pytest (3.10.1) depends on six (>=1.10.0)
   1: fact: pytest (3.10.1) depends on attrs (>=17.4.0)
   1: fact: pytest (3.10.1) depends on more-itertools (>=4.0.0)
   1: fact: pytest (3.10.1) depends on atomicwrites (>=1.0)
   1: fact: pytest (3.10.1) depends on pluggy (>=0.7)
   1: fact: pytest (3.10.1) depends on colorama (*)
   1: selecting pytest (3.10.1)
   1: derived: colorama (*)
   1: derived: pluggy (>=0.7)
   1: derived: atomicwrites (>=1.0)
   1: derived: more-itertools (>=4.0.0)
   1: derived: attrs (>=17.4.0)
   1: derived: six (>=1.10.0)
   1: derived: py (>=1.5.0)
PyPI: 39 packages found for colorama *
PyPI: 8 packages found for pluggy >=0.7
PyPI: 6 packages found for atomicwrites >=1.0
PyPI: 10 packages found for more-itertools >=4.0.0
PyPI: 6 packages found for attrs >=17.4.0
PyPI: 3 packages found for six >=1.10.0
PyPI: No release information found for py-0.8.0-alpha2, skipping
PyPI: No release information found for py-0.9.0, skipping
PyPI: No release information found for py-1.4.32.dev1, skipping
PyPI: 7 packages found for py >=1.5.0
   1: selecting six (1.12.0)
   1: selecting atomicwrites (1.3.0)
   1: selecting attrs (19.3.0)
   1: selecting py (1.8.0)
   1: selecting pluggy (0.13.0)
   1: selecting more-itertools (7.2.0)
   1: selecting colorama (0.4.1)
   1: Version solving took 9.953 seconds.
   1: Tried 1 solutions.

Writing lock file


Package operations: 1 install, 0 updates, 0 removals

  - Installing unzipped-egg (0.1 https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz)

[EnvCommandError]
Command ['C:\\Users\\Dia\\PycharmProjects\\new-git\\venv\\Scripts\\python.exe', '-m', 'pip', 'install', '--no-deps', 'https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz#egg=unzipped-egg'] errored with the fol
lowing return code 1, and output:
Collecting unzipped-egg
  Downloading https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz (3.5MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'done'
  WARNING: Generating metadata for package unzipped-egg produced metadata for project name pyinstaller. Fix your #egg=unzipped-egg fragments.
Building wheels for collected packages: pyinstaller, pyinstaller
  Building wheel for pyinstaller (PEP 517): started
  Building wheel for pyinstaller (PEP 517): finished with status 'done'
  Created wheel for pyinstaller: filename=PyInstaller-4.0.dev0+a9b299995-cp38-none-any.whl size=2885626 sha256=07ea475e2892c7a82001528396ef86ac0b79c83dbadbd8336b32f44f4ed79e76
  Stored in directory: C:\Users\Dia\AppData\Local\Temp\pip-ephem-wheel-cache-36v9wdj2\wheels\8b\39\b1\344cfb87bb8f3413c66ff18d4065479af5f826949ebca3bf6c
  Building wheel for pyinstaller (PEP 517): started
  ERROR: Error [WinError 267] Érvénytelen a könyvtárnév while executing command 'C:\Users\Dia\PycharmProjects\new-git\venv\Scripts\python.exe' 'C:\Users\Dia\PycharmProjects\new-git\venv\lib\site-packages\pip\_vendor\pep517\
_in_process.py' build_wheel 'C:\Users\Dia\AppData\Local\Temp\tmprfr7_39n'
  Building wheel for pyinstaller (PEP 517): finished with status 'error'
  ERROR: Failed building wheel for pyinstaller
  Running setup.py clean for pyinstaller
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Dia\PycharmProjects\new-git\venv\Scripts\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Dia\\AppData\\Local\\Temp\\pip-install-tdjufbq1\\pyinstaller\\setup.py'"'"';
__file__='"'"'C:\\Users\\Dia\\AppData\\Local\\Temp\\pip-install-tdjufbq1\\pyinstaller\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(com
pile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\Dia\AppData\Local\Temp\pip-install-tdjufbq1\pyinstaller
  Complete output (5 lines):
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Python\Python38-32\lib\tokenize.py", line 392, in open
      buffer = _builtin_open(filename, 'rb')
  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dia\\AppData\\Local\\Temp\\pip-install-tdjufbq1\\pyinstaller\\setup.py'
  ----------------------------------------
  ERROR: Failed cleaning build dir for pyinstaller
Successfully built pyinstaller
Failed to build pyinstaller
ERROR: Could not build wheels for pyinstaller which use PEP 517 and cannot be installed directly


Traceback (most recent call last):
  File "C:\Users\Dia\.poetry\lib\poetry\_vendor\py3.8\clikit\console_application.py", line 132, in run
    status_code = command.handle(parsed_args, io)
  File "C:\Users\Dia\.poetry\lib\poetry\_vendor\py3.8\clikit\api\command\command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "C:\Users\Dia\.poetry\lib\poetry\_vendor\py3.8\clikit\api\command\command.py", line 173, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "C:\Users\Dia\.poetry\lib\poetry\_vendor\py3.8\cleo\commands\command.py", line 92, in wrap_handle
    return self.handle()
  File "C:\Users\Dia\.poetry\lib\poetry\console\commands\add.py", line 149, in handle
    status = installer.run()
  File "C:\Users\Dia\.poetry\lib\poetry\installation\installer.py", line 74, in run
    self._do_install(local_repo)
  File "C:\Users\Dia\.poetry\lib\poetry\installation\installer.py", line 286, in _do_install
    self._execute(op)
  File "C:\Users\Dia\.poetry\lib\poetry\installation\installer.py", line 302, in _execute
    getattr(self, "_execute_{}".format(method))(operation)
  File "C:\Users\Dia\.poetry\lib\poetry\installation\installer.py", line 327, in _execute_install
    self._installer.install(operation.package)
  File "C:\Users\Dia\.poetry\lib\poetry\installation\pip_installer.py", line 89, in install
    self.run(*args)
  File "C:\Users\Dia\.poetry\lib\poetry\installation\pip_installer.py", line 110, in run
    return self._env.run("python", "-m", "pip", *args, **kwargs)
  File "C:\Users\Dia\.poetry\lib\poetry\utils\env.py", line 884, in run
    return super(VirtualEnv, self).run(bin, *args, **kwargs)
  File "C:\Users\Dia\.poetry\lib\poetry\utils\env.py", line 708, in run
    raise EnvCommandError(e, input=input_)
```

**Comment by mozesa** [comment]
Any thoughts, how should I install the dev version of PyInstaller?


Thanks in advance.
