### ISSUE TITLE
backports.configparser not found

### ISSUE THREAD

**Issue by mthuurne** [python-poetry/poetry#1501]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- openSUSE Linux 15.1
- Poetry 1.0.0b3

## Issue

I updated from Poetry 0.12.17 to 1.0.0b3 using `poetry self:update --preview`. The update ran in a directory that selected Python 3.7 using pyenv and it completed without errors.

When I try to start Poetry in a directory that uses pyenv to select a Python 3.x as the default, Poetry runs. But if I start Poetry in a directory without a `.python-version` file, the system default Python 2.7.14 is used and I get the following error:

```
$ poetry --version
/home/mth/.poetry/lib/poetry/_vendor/py2.7/subprocess32.py:149: RuntimeWarning: The _posixsubprocess module is not being used. Child process reliability may suffer if your program uses threads.
  "program uses threads.", RuntimeWarning)
Traceback (most recent call last):
  File "/home/mth/.poetry/bin/poetry", line 11, in <module>
    from poetry.console import main
  File "/home/mth/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/mth/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands import AboutCommand
  File "/home/mth/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/mth/.poetry/lib/poetry/console/commands/check.py", line 1, in <module>
    from poetry.factory import Factory
  File "/home/mth/.poetry/lib/poetry/factory.py", line 15, in <module>
    from .json import validate_object
  File "/home/mth/.poetry/lib/poetry/json/__init__.py", line 4, in <module>
    import jsonschema
  File "/home/mth/.poetry/lib/poetry/_vendor/py2.7/jsonschema/__init__.py", line 31, in <module>
    import importlib_metadata
  File "/home/mth/.poetry/lib/poetry/_vendor/py2.7/importlib_metadata/__init__.py", line 15, in <module>
    from ._compat import (
  File "/home/mth/.poetry/lib/poetry/_vendor/py2.7/importlib_metadata/_compat.py", line 19, in <module>
    from backports.configparser import ConfigParser
ImportError: No module named configparser
```
The problem seems to be that there is an openSUSE package named `python-backports.functools_lru_cache` that defines a Python package named `backports`, which shadows the `backports` package from Poetry. After I uninstalled `python-backports.functools_lru_cache`, the problem was gone. However, some people might not be able to uninstall it without applications they rely upon breaking.

A possible way to avoid name conflicts like this would be to use a unique package name such as `poetry.backports` instead of just `backports`.

**Comment by finswimmer** [comment]
Because there were no more comments to this issue for a very long time, I assume it is solved. So I will close it.

Feel free to leave a comment if someone disagree.

fin swimmer

**Comment by mthuurne** [comment]
I cannot reproduce the problem anymore with Poetry 1.0.5, not even with the openSUSE package `python2-backports.functools_lru_cache` installed. So unless someone else can still reproduce it, I think it's fine to keep this issue closed.

**Comment by Michal-Szelag-Sonos** [comment]
I am seeing this issue consistently with `1.1.4` and python2.7 venv.  I used the recommended installer.

```
$ virtualenv -p python2.7 .venv
...
$ source .venv/bin/activate
$ poetry -V
Traceback (most recent call last):
  File "/home/mszelag/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
  File "/home/mszelag/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/mszelag/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/home/mszelag/.poetry/lib/poetry/console/commands/__init__.py", line 2, in <module>
    from .add import AddCommand
  File "/home/mszelag/.poetry/lib/poetry/console/commands/add.py", line 8, in <module>
    from .init import InitCommand
  File "/home/mszelag/.poetry/lib/poetry/console/commands/init.py", line 18, in <module>
    from poetry.utils._compat import OrderedDict
  File "/home/mszelag/.poetry/lib/poetry/utils/_compat.py", line 19, in <module>
    import importlib_metadata as metadata
  File "/home/mszelag/.poetry/lib/poetry/_vendor/py2.7/importlib_metadata/__init__.py", line 16, in <module>
    from ._compat import (
  File "/home/mszelag/.poetry/lib/poetry/_vendor/py2.7/importlib_metadata/_compat.py", line 20, in <module>
    from backports.configparser import ConfigParser
ImportError: No module named configparser
```
Obviously, I can work around this by installing configparser into my venv but I should not have to install a dependency into my project to make poetry work.
