### ISSUE TITLE
Poetry doesn't find package in devpi repository

### ISSUE THREAD

**Issue by Yanpas** [python-poetry/poetry#1524]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 19.10
- **Poetry version**: 1.0.0b3

## Issue
I have a private repository `https://pypi.g.mycompany/`:
```
devpi-server-5.1.0
devpi-web-3.5.2
```
and I want to install package foo from it, poetry doesn't find it:
```
[SolverProblemError]
Because project depends on foo (0.19.0) which doesn't match any versions, version solving failed.

Traceback (most recent call last):
Traceback (most recent call last):
  File "/home/yan/.poetry/bin/poetry", line 14, in <module>
    main()
  File "/home/yan/.poetry/lib/poetry/console/__init__.py", line 5, in main
    return Application().run()
  File "/home/yan/.poetry/lib/poetry/_vendor/py2.7/clikit/console_application.py", line 139, in run
    trace.render(io, simple=isinstance(e, CliKitException))
  File "/home/yan/.poetry/lib/poetry/_vendor/py2.7/clikit/ui/components/exception_trace.py", line 57, in render
    self._render_traceback(io, tb)
  File "/home/yan/.poetry/lib/poetry/_vendor/py2.7/clikit/ui/components/exception_trace.py", line 67, in _render_traceback
    io.write_line("".join(traceback.format_list(frames)))
  File "/usr/lib/python2.7/traceback.py", line 39, in format_list
    item = '  File "%s", line %d, in %s\n' % (filename,lineno,name)
```

pyproject.toml:
```toml
[tool.poetry]
name = "projects"
version = "0.1.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.7"
foo = {version = "0.19.0", source = "xxx"}

[tool.poetry.dev-dependencies]
pylint = "^2.4"

[[tool.poetry.source]]
name = "xxx"
url = "https://pypi.g.mycompany/root/pypi/+simple"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

**Comment by kyluca** [comment]
Hey @Yanpas, I'm not 100% sure but I believe you've accidentally misconfigured the URL to be the `root/pypi` passthrough index,
```
url = "https://pypi.g.mycompany/root/pypi/+simple"
```
instead of your company's top level index e.g.
```
url = "https://pypi.g.mycompany/myuser/myindex/+simple"
```

A devpi index e.g. `myuser/myindex` holds your private packages *and* inherits from `root/pypi`, however the URL you've got at the moment is completely skipping your custom packages because it's pointing to `root/pypi`.

**Comment by Yanpas** [comment]
:thinking: that did help, thank you. I've tried many different repo urls before posting an issue, seems like I've missed this one.

**Comment by Yanpas** [comment]
Oh, I cleared all the caches (Poetry used pipenv cache) and reproduce it with correct URL, same which I use in pipenv.:
```
[EnvCommandError]
Command ['/home/yan/.cache/pypoetry/virtualenvs/project-cJ-t_B_F-py3.7/bin/python', '-m', 'pip', 'install', '--no-deps', '--index-url', u'https://pypi.g.mycompany/go/prod', '--extra-index-url', 'https://pypi.org/', 'foo==0.19.0'] errored with the following return code 1, and output: 
Looking in indexes: https://pypi.g.mycompany/go/prod, https://pypi.org/
Collecting foo==0.19.0
Could not install packages due to an EnvironmentError: 404 Client Error: Not Found for url: https://pypi.org/pyinet/
```

**Comment by Yanpas** [comment]
I have only one file in ~/.cache/pypoetry/cache/repositories/xxx/4b/dd/fe/83/26/20/6b/d9/4bddfe8326206bd9bcf93b3117fd3cab597644ef3ab6168196372ee1aba1d789:
```
|9999999999{"file|
|s": [{"hash": "s|
|ha256:8bc85c88a2|
|f112452552bbf7a3|
|92d2d366884d9210|
|a408338009660841|
|80e2b0", "file":|
| "fooooo-0.19.0.|
|tar.gz"}, {"hash|
|": "sha256:eefb4|
|dd34ff3d6b0f6139|
|bc3f1293afa78f60|
|06bad5aa06e62632|
|1593f3e7bd7", "f|
|ile": "fooooo-0.|
|19.0-py3-none-an|
|y.whl"}], "name"|
|: "fooooo", "req|
|uires_python": "|
|>=3.6", "summary|
|": "fooooo - asy|
|ncio net library|
|", "_cache_versi|
|on": "1.0.0b2", |
|"requires_dist":|
| ["aiodns", "aio|
|http (<4.0,>=3.4|
|)", "cached-prop|
|erty", "cchardet|
|", "chardet", "m|
|ultidict", "pyca|
|res", "yarl", "s|
|etproctitle", "u|
|vloop", "attrs",|
| "async-timeout"|
|, "aiohttp-jinja|
|2", "jinja2", "a|
|iocontextvars", |
|"typing-extensio|
|ns", "raven-aioh|
|ttp (>=0.7.0) ; |
|extra == 'sentry|
|'"], "version": |
|"0.19.0"}|
```

**Comment by Yanpas** [comment]
Adding `default = true` to tool.poetry.source did help

**Comment by HacKanCuBa** [comment]
> Adding `default = true` to tool.poetry.source did help

You, sir, are awesome!
Came here for the same issue, this fixed it :D

So now I'm not sure if this is a bug or a feature :unamused:

**Comment by rs-garrick** [comment]
I'm having this problem now with a new devpi server.   pip and pipenv can install packages just fine, but poetry just keeps erroring with messages like `Because foo depends on requests (==2.25.1) which doesn't match any versions, version solving failed.`

```
[[tool.poetry.source]]
name = "resci"
url = "https://devpi.foo.co/foo/simple/"
default = true
[tool.poetry.dependencies]
python = "==3.9.1"
requests = "==2.25.1"

```
```
$ pip install requests==2.25.1 -i https://devpi.foo.co/resci/simple --no-cache-dir
Looking in indexes: https://devpi.foo.co/resci/simple
Collecting requests==2.25.1
  Downloading https://devpi.foo.co/root/pypi/%2Bf/c21/0084e36a42ae6/requests-2.25.1-py2.py3-none-any.whl (61 kB)
...
Installing collected packages: urllib3, idna, chardet, certifi, requests
Successfully installed certifi-2022.5.18.1 chardet-4.0.0 idna-2.10 requests-2.25.1 urllib3-1.26.9

$ poetry update -vvv
Using virtualenv: /home/garrick/git/bar/venv
Updating dependencies
Resolving dependencies...
   1: fact: bar is 0.1.0
   1: derived: bar
   1: fact: bar depends on requests (==2.25.1)
   1: selecting bar (0.1.0)
   1: derived: requests (==2.25.1)
foo: 0 packages found for requests 2.25.1
   1: fact: no versions of requests match 2.25.1
   1: conflict: no versions of requests match 2.25.1
   1: ! requests (==2.25.1) is satisfied by requests (==2.25.1)
   1: ! which is caused by "bar depends on requests (==2.25.1)"
   1: ! thus: version solving failed
   1: Version solving took 0.709 seconds.
   1: Tried 1 solutions.

[SolverProblemError]
Because bar depends on requests (==2.25.1) which doesn't match any versions, version solving failed.

```

**Comment by neersighted** [comment]
Closing as this is a configuration issue, and we already have asks in for better docs around source resolution order.
