### ISSUE TITLE
get the location of the virt. env. quickly

### ISSUE THREAD

**Issue by jabbalaci** [python-poetry/poetry#1533]
I'm using Poetry version 0.12.17. I'd like to get the location of the virtual environment in a simple and quick way.

**Motivation**
With virt. env.-s, I prefer to use two aliases, called "on" and "off" for activating and deactivating, respectively. With ZSH, I have the following definitions:

```
# activate the virt. env. if Pipfile exists
_activate_venv() {
  if [[ -n ${VIRTUAL_ENV} ]]; then
      # echo "# virt. env. is already activated"
      return
  fi
  # else
  if [[ -f Pipfile ]]; then
    # echo "# activating venv…"
    source $(pipenv --venv)/bin/activate
  fi
}

autoload -U add-zsh-hook
add-zsh-hook chpwd _activate_venv

_activate_venv

alias on=_activate_venv

alias off='deactivate'

alias out='off; cd ..'
```

I know about `poetry shell`, but I don't want to create a subshell, I prefer activating a virt. env. in the current shell. The key part is this:

```
if [[ -f Pipfile ]]; then
    # echo "# activating venv…"
    source $(pipenv --venv)/bin/activate
  fi
```

I want to move from pipenv to poetry, and this is the only thing that I still want to solve. How can I get the location of the virt. env.?

I know about `poetry show -v`, but 1) it returns other things too, and 2) it's very slow for this purpose. It also fetches the packages and their versions, which makes it slow. If I only want the venv location, then there's no need to fetch any other info. On my machine, `poetry show -v` takes about 1 second, which is too slow.

**Feature request**

Please provide an option that returns just the location of the virt. env. Example:

    poetry --venv

Thanks!

**Update:** currently, this is how I can extract the necessary information: `(poetry show -v | head -1) 2>/dev/null | cut -d" " -f3` .

**Comment by isstabb** [comment]
`poetry env info -p` is in the prerelease version of poetry.

**Comment by jabbalaci** [comment]
Thanks. Unfortunately the preview version got stuck (under Manjaro Linux). After Ctrl-C, it printed the following:

```
$ poetry    
^CTraceback (most recent call last):
  File "./poetry", line 12, in <module>
    from poetry.console import main
  File "/home/jabba/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/jabba/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands import AboutCommand
  File "/home/jabba/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/jabba/.poetry/lib/poetry/console/commands/check.py", line 1, in <module>
    from poetry.factory import Factory
  File "/home/jabba/.poetry/lib/poetry/factory.py", line 17, in <module>
    from .packages.dependency import Dependency
  File "/home/jabba/.poetry/lib/poetry/packages/__init__.py", line 7, in <module>
    from .dependency import Dependency
  File "/home/jabba/.poetry/lib/poetry/packages/dependency.py", line 10, in <module>
    from poetry.utils.helpers import canonicalize_name
  File "/home/jabba/.poetry/lib/poetry/utils/helpers.py", line 16, in <module>
    from keyring import delete_password, set_password, get_password
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/__init__.py", line 1, in <module>
    from .core import (
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/core.py", line 189, in <module>
    init_backend()
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/core.py", line 91, in init_backend
    keyrings = filter(limit, backend.get_all_keyring())
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/util/__init__.py", line 22, in wrapper
    func.always_returns = func(*args, **kwargs)
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 204, in get_all_keyring
    return list(rings)
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/util/__init__.py", line 33, in suppress_exceptions
    for callable in callables:
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/backend.py", line 64, in viable
    cls.priority
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/util/properties.py", line 26, in __get__
    return self.fget.__get__(None, owner)()
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/keyring/backends/SecretService.py", line 41, in priority
    list(secretstorage.get_all_collections(bus))
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/secretstorage/collection.py", line 153, in get_all_collections
    for collection_path in service.get_property('Collections'):
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/secretstorage/util.py", line 65, in get_property
    (signature, value), = self.send_and_get_reply(msg)
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/secretstorage/util.py", line 47, in send_and_get_reply
    return self._connection.send_and_get_reply(msg)
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/jeepney/integrate/blocking.py", line 67, in send_and_get_reply
    self.recv_messages()
  File "/home/jabba/.poetry/lib/poetry/_vendor/py3.7/jeepney/integrate/blocking.py", line 55, in recv_messages
    b = self.sock.recv(4096)
KeyboardInterrupt
```

**Comment by finswimmer** [comment]
Hello,

as @isstabb mentioned since poetry 1.0 the subcommands of `poetry env` can be used to retrieve information about the venv.

For more information have a look at `poetry env --help`.

fin swimmer
