### ISSUE TITLE
[1.0.0b7] ImportError: cannot import name 'argument'

### ISSUE THREAD

**Issue by kmmbvnr** [python-poetry/poetry#1628]
- [X] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **ubuntu 18.04**
- **1.0.0b7**

```
$ pip3 install poetry --user --pre
....
Installing collected packages: six, pyrsistent, msgpack, certifi, chardet, urllib3, idna, requests, lockfile, cachecontrol, entrypoints, jeepney, pycparser, cffi, cryptography, secretstorage, keyring, pyparsing, more-itertools, zipp, importlib-metadata, attrs, setuptools, jsonschema, tomlkit, webencodings, html5lib, pylev, pastel, clikit, cleo, ptyprocess, pexpect, pkginfo, cachy, shellingham, requests-toolbelt, poetry
Successfully installed attrs-19.3.0 cachecontrol-0.12.5 cachy-0.3.0 certifi-2019.9.11 cffi-1.13.2 chardet-3.0.4 cleo-0.7.6 clikit-0.4.0 cryptography-2.8 entrypoints-0.3 html5lib-1.0.1 idna-2.8 importlib-metadata-0.23 jeepney-0.4.1 jsonschema-3.2.0 keyring-19.2.0 lockfile-0.12.2 more-itertools-7.2.0 msgpack-0.6.2 pastel-0.1.1 pexpect-4.7.0 pkginfo-1.5.0.1 poetry-1.0.0b7 ptyprocess-0.6.0 pycparser-2.19 pylev-1.3.0 pyparsing-2.4.5 pyrsistent-0.14.11 requests-2.22.0 requests-toolbelt-0.8.0 secretstorage-3.1.1 setuptools-42.0.0 shellingham-1.3.1 six-1.13.0 tomlkit-0.5.8 urllib3-1.25.7 webencodings-0.5.1 zipp-0.6.0

$ poetry --version
Traceback (most recent call last):
  File "/home/kmmbvnr/.local/bin/poetry", line 7, in <module>
    from poetry.console import main
  File "/home/kmmbvnr/.local/lib/python3.6/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/kmmbvnr/.local/lib/python3.6/site-packages/poetry/console/application.py", line 1, in <module>
    from cleo import Application as BaseApplication
  File "/home/kmmbvnr/.local/lib/python3.6/site-packages/cleo/__init__.py", line 3, in <module>
    from .application import Application
  File "/home/kmmbvnr/.local/lib/python3.6/site-packages/cleo/application.py", line 7, in <module>
    from .commands.completions_command import CompletionsCommand
  File "/home/kmmbvnr/.local/lib/python3.6/site-packages/cleo/commands/completions_command.py", line 10, in <module>
    from ..helpers import argument
ImportError: cannot import name 'argument'
```

**Comment by duichwer** [comment]
I'm having the  same issue on ubuntu (wsl) on windows and don't know how i can tempory create a workaround, since I have to use a new prerelease to handle the `pip` not found isuue https://github.com/sdispater/poetry/issues/712 on ubuntu with python3.

Is this issue related to poetry or should we open another issue for [cleo](https://github.com/sdispater/cleo)?
Maybe using absolute package paths instead of relatives may help?

```python
from cleo.helpers import argument
```

**Comment by finswimmer** [comment]
Hello,

doesn't seem to be a problem anymore. So I will close this issue.

Thanks for reporting!

fin swimmer

**Comment by dyno** [comment]
i still see the problem on mac, and it turns out i have to uninstall cleo twice, one for 0.7.6 and one for 0.6.8. now sure how they can coexists.
