### ISSUE TITLE
deeper path dependencies are not working app1 -> pathlib1 -> pathlib2

### ISSUE THREAD

**Issue by mxab** [python-poetry/poetry#1636]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: in docker based container `python:3.7` (currently not able to reproduce this locally)
- **Poetry version**: 1.0.0b7
- **[Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/mxab/poetry-multiproject-demo

## Issue

I'm having a path dependency with another path dependency. When I try to install my application I get an error.

It seems that it actually has not problem resolving and installing the deeper dependency `  - Installing util (0.1.0 ../corelib/../util)` but fails when installing the actual dependency `  - Installing corelib (0.1.0 ../corelib)`

```
reating virtualenv server-9bWhMBql-py3.7 in /root/.cache/pypoetry/virtualenvs
Using virtualenv: /root/.cache/pypoetry/virtualenvs/server-9bWhMBql-py3.7
Installing dependencies from lock file


Package operations: 12 installs, 0 updates, 0 removals, 12 skipped

  - Installing six (1.13.0)
  - Installing markupsafe (1.1.1)
  - Installing python-dateutil (2.8.1)
  - Installing pytzdata (2019.3)
  - Installing click (7.0)
  - Installing itsdangerous (1.1.0)
  - Installing jinja2 (2.10.3)
  - Installing pendulum (2.0.5)
  - Installing util (0.1.0 ../corelib/../util)
  - Installing werkzeug (0.16.0)
  - Installing corelib (0.1.0 ../corelib)

[EnvCommandError]
Command ['/root/.cache/pypoetry/virtualenvs/server-9bWhMBql-py3.7/bin/pip', 'install', '--no-deps', '-U', '-e', '/app/server/../corelib'] errored with the following return code 1, and output: 
Obtaining file:///app/corelib
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /root/.cache/pypoetry/virtualenvs/server-9bWhMBql-py3.7/bin/python /root/.cache/pypoetry/virtualenvs/server-9bWhMBql-py3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-4m98ool7/normal --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'pendulum>=2.0.5,<3.0.0' util
       cwd: None
  Complete output (7 lines):
  Collecting pendulum<3.0.0,>=2.0.5
    Using cached https://files.pythonhosted.org/packages/0b/db/eadff08d7a50a5a28d13efba6a029868f72b662f7cb30079f4af56a8de02/pendulum-2.0.5-cp37-cp37m-manylinux1_x86_64.whl
  Collecting util
    ERROR: Could not find a version that satisfies the requirement util (from versions: none)
  ERROR: No matching distribution found for util
  WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
  You should consider upgrading via the 'pip install --upgrade pip' command.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /root/.cache/pypoetry/virtualenvs/server-9bWhMBql-py3.7/bin/python /root/.cache/pypoetry/virtualenvs/server-9bWhMBql-py3.7/lib/python3.7/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-4m98ool7/normal --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'pendulum>=2.0.5,<3.0.0' util Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 19.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Traceback (most recent call last):
  File "/root/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/root/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/root/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/root/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/root/.poetry/lib/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/root/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/root/.poetry/lib/poetry/installation/installer.py", line 286, in _do_install
    self._execute(op)
  File "/root/.poetry/lib/poetry/installation/installer.py", line 302, in _execute
    getattr(self, '_execute_{}'.format(method))(operation)
  File "/root/.poetry/lib/poetry/installation/installer.py", line 327, in _execute_install
    self._installer.install(operation.package)
  File "/root/.poetry/lib/poetry/installation/pip_installer.py", line 32, in install
    self.install_directory(package)
  File "/root/.poetry/lib/poetry/installation/pip_installer.py", line 221, in install_directory
    return self.run(*args)
  File "/root/.poetry/lib/poetry/installation/pip_installer.py", line 118, in run
    return self._env.run_pip(*args, **kwargs)
  File "/root/.poetry/lib/poetry/utils/env.py", line 801, in run_pip
    return self._run(cmd, **kwargs)
  File "/root/.poetry/lib/poetry/utils/env.py", line 1029, in _run
    return super(VirtualEnv, self)._run(cmd, **kwargs)
  File "/root/.poetry/lib/poetry/utils/env.py", line 833, in _run
    raise EnvCommandError(e, input=input_)

The command '/bin/sh -c poetry install -vvv --no-dev -n' returned a non-zero code: 1
``` 

Some follow up questions would be how is the setup with the lock files in such a case.
Should the path dependencies contain own lock files or are they ignored by the installation of the root app?
Should I do a install in the path dependencies first? 

Kind Regards

**Comment by finswimmer** [comment]
Hey @mxab,

even if you reported this earlier then #1689, I will close yours as a duplicate. Because in the other issue are already more information about the root cause of the problem. Feel free to add any information there.

Thanks a lot for reporting!

fin swimmer
