### ISSUE TITLE
Cannot install poetry on freebsd using get-poetry.sh

### ISSUE THREAD

**Issue by mhozza** [python-poetry/poetry#1647]
- [x] I am on the [latest](https://github.com/sdispater/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/sdispater/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: FreeBSD 11.1-RELEASE-p1
- **Poetry version**: master

## Issue

Running `curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python` ends with following error on FreeBSD:

`pip install poetry` works fine.

```
Installing version: 0.12.17
Traceback (most recent call last):
  File "<stdin>", line 533, in _make_lib
  File "/usr/local/lib/python3.5/urllib/request.py", line 163, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.5/urllib/request.py", line 472, in open
    response = meth(req, response)
  File "/usr/local/lib/python3.5/urllib/request.py", line 582, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/local/lib/python3.5/urllib/request.py", line 510, in error
    return self._call_chain(*args)
  File "/usr/local/lib/python3.5/urllib/request.py", line 444, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.5/urllib/request.py", line 590, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 959, in <module>
  File "<stdin>", line 955, in main
  File "<stdin>", line 356, in run
  File "<stdin>", line 489, in install
  File "<stdin>", line 509, in make_lib
  File "<stdin>", line 536, in _make_lib
RuntimeError: Could not find poetry-0.12.17-freebsd11.sha256sum file
```

**Comment by seasonedgeek** [comment]
I had the same issue (above: ../urllib/request.py) except that I was trying to uninstall poetry using the get-poetry.py script. If you have the time, you can save a [copy of the script](https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py), and modify the code slightly to achieve your quest.

For example, in my case, I had to first, install [certifi](https://pypi.python.org/pypi/certifi) using a script. And then, in get-poetry.py, I reassign the `lib` variable at line #207 to point to Homebrew's `../Frameworks/Python.framework/Versions/3.8/lib/python3.8/urllib`.
Oh happy day, it worked (get-poetry.py --uninstall )!

**Comment by finswimmer** [comment]
The get-poetry.py script is now deprecated. Please use `install-poetry.py` instead. Just leave a comment if the issue still exists.

fin swimmer
