### ISSUE TITLE
The specified Python version (3.8) is not supported by the project (^3.7).

### ISSUE THREAD

**Issue by jobevers** [python-poetry/poetry#1735]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.3 LTS
- **Poetry version**: `Poetry version 1.0.0`
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/jobevers/a3e674e4f316a6c0ea535ac818bf5f61

## Issue
I wanted to start using python 3.8 in a project:

```
» poetry env use -vvv 3.8.0 

[NoCompatiblePythonVersionFound]
The specified Python version (3.8) is not supported by the project (^3.7).
Please choose a compatible version or loosen the python constraint specified in the pyproject.toml file.

Traceback (most recent call last):
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/poetry/console/commands/env/use.py", line 23, in handle
    env = manager.activate(self.argument('python'), self._io)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/poetry/utils/env.py", line 259, in activate
    self.create_venv(io, executable=python, force=create)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/poetry/utils/env.py", line 520, in create_venv
    self._poetry.package.python_versions, python_minor
```

**Comment by sdispater** [comment]
You should use only the minor version with `env use`:

```bash
poetry env use 3.8
```

Basically, Poetry looks for a `python3.8.0` executable which it does not find leading to this error.

**Comment by finswimmer** [comment]
Hello @jobevers ,

I guess the error message is misleading. `poetry env use` expect the path to an python executable and not a version number.

So specify the complete path to the python 3.8 interpreter or, if you use pyenv for handling multiple python versions, activate the correct version first.

fin swimmer

**Comment by jobevers** [comment]
```
» poetry env use -vvv 3.8

[NoCompatiblePythonVersionFound]
The specified Python version (3.8) is not supported by the project (^3.7).
Please choose a compatible version or loosen the python constraint specified in the pyproject.toml file.

Traceback (most recent call last):
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/poetry/console/commands/env/use.py", line 23, in handle
    env = manager.activate(self.argument('python'), self._io)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/poetry/utils/env.py", line 259, in activate
    self.create_venv(io, executable=python, force=create)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/poetry/utils/env.py", line 520, in create_venv
    self._poetry.package.python_versions, python_minor
```

**Comment by sdispater** [comment]
@jobevers Do you actually have a `python3.8` executable in your `PATH`?

**Comment by jobevers** [comment]
```
poetry env use -vvv /home/jobevers/code/pyenv/versions/3.8.0/bin/python                                             

[NoCompatiblePythonVersionFound]
The specified Python version (3.8) is not supported by the project (^3.7).
Please choose a compatible version or loosen the python constraint specified in the pyproject.toml file.

Traceback (most recent call last):
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/poetry/console/commands/env/use.py", line 23, in handle
    env = manager.activate(self.argument('python'), self._io)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/poetry/utils/env.py", line 259, in activate
    self.create_venv(io, executable=python, force=create)
  File "/home/jobevers/.local/pipx/venvs/poetry/lib/python3.6/site-packages/poetry/utils/env.py", line 520, in create_venv
    self._poetry.package.python_versions, python_minor
```

**Comment by jobevers** [comment]
```
» which python3.8
/home/jobevers/code/pyenv/shims/python3.8
```

**Comment by sdispater** [comment]
Oh, I know what's going on, this is a bug in how Poetry gets the patch version of the executable. Basically, it uses the current Python for the patch version instead of the one of the passed executable.

This should be an easy fix.

**Comment by echernyavskiy** [comment]
@sdispater could you cut a patch release that includes this fix?

**Comment by kamyar** [comment]
+1 having this issue at the moment with python 3.8.2

**Comment by tinder-alexbohr** [comment]
> I guess initially set it too strictly without knowing


I'm getting mixed results - work for me but not the person next to me, not sure which is expected behaviour.  When saying:
```
[tool.poetry.dependencies]
python = "3.8"
```
which patch versions does that support?

**Comment by abraralali** [comment]
> +1 having this issue at the moment with python 3.8.2.
> 
> Edit:
> changing
> 
> ```
> [tool.poetry.dependencies]
> python = "3.8"
> ```
> 
> to
> 
> ```
> [tool.poetry.dependencies]
> python = "^3.8"
> ```
> 
> worked.
> 
>  I guess initially set it too strictly without knowing

Thank you kamyar
This solution worked for me also. Python 3.8.5

**Comment by himsgupta** [comment]
> +1 having this issue at the moment with python 3.8.2.
> 
> Edit: changing
> 
> ```
> [tool.poetry.dependencies]
> python = "3.8"
> ```
> 
> to
> 
> ```
> [tool.poetry.dependencies]
> python = "^3.8"
> ```
> 
> worked.
> 
> I guess initially set it too strictly without knowing
It didinot work in my case, somehow

**Comment by tinyweasel** [comment]
Fixed mine by adding this to ~/.zshrc (on advice from work documentation). Also needed to restart shell and rerun `poetry install`.

```
export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
export C_INCLUDE_PATH=/opt/homebrew/Cellar/librdkafka/1.8.2/include
export LIBRARY_PATH=/opt/homebrew/Cellar/librdkafka/1.8.2/lib
```

**Comment by neersighted** [comment]
> Fixed mine by adding this to ~/.zshrc (on advice from work documentation). Also needed to restart shell and rerun `poetry install`.
> 
> ```
> export LDFLAGS="-L/opt/homebrew/opt/openssl@3/lib"
> export CPPFLAGS="-I/opt/homebrew/opt/openssl@3/include"
> export C_INCLUDE_PATH=/opt/homebrew/Cellar/librdkafka/1.8.2/include
> export LIBRARY_PATH=/opt/homebrew/Cellar/librdkafka/1.8.2/lib
> ```

I think you may have gotten turned around and are discussing something totally different.

**Comment by allendred** [comment]
> +1 having this issue at the moment with python 3.8.2.
> 
> Edit: changing
> 
> ```
> [tool.poetry.dependencies]
> python = "3.8"
> ```
> 
> to
> 
> ```
> [tool.poetry.dependencies]
> python = "^3.8"
> ```
> 
> worked.
> 
> I guess initially set it too strictly without knowing

This does not work. After manually modifying toml, `python-versions = "^3.7"` executes `poetry add numpy` and still uses version 3.10 of numpy
