### ISSUE TITLE
`pip3 install poetry` doesn't work

### ISSUE THREAD

**Issue by nottrobin** [python-poetry/poetry#1748]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04.3 LTS
- **Poetry version**: 1.0.0

## Issue

I know that Pip is not [the recommended way](https://github.com/python-poetry/poetry#installation) to install Poetry, but until https://github.com/python-poetry/poetry/pull/1518 is released, I don't see another way to install Poetry for Python3.

Also, installing with Pip would just be so much more straightforward and easy to remember. I would suggest that now Poetry has in theory reached stability with v1.0.0, ensuring it's successfully installable with Pip would be a worthwhile goal.

Here's what happened when I tried:

``` bash
$ sudo pip3 install poetry
Keyring is skipped due to an exception: not all arguments converted during string formatting
WARNING: The directory '/home/robin/.cache/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
WARNING: The directory '/home/robin/.cache/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting poetry
  Downloading https://files.pythonhosted.org/packages/d9/ca/6db99ba6be273b13ba3747ccfcc357714dd60c887d1f2598119ee1909262/poetry-1.0.0-py2.py3-none-any.whl (217kB)
     |████████████████████████████████| 225kB 5.6MB/s 
Requirement already satisfied: jsonschema<4.0,>=3.1 in /home/robin/.local/lib/python3.6/site-packages (from poetry) (3.2.0)
Requirement already satisfied: cleo<0.8.0,>=0.7.6 in /usr/local/lib/python3.6/dist-packages (from poetry) (0.7.6)
Requirement already satisfied: pkginfo<2.0,>=1.4 in /home/robin/.local/lib/python3.6/site-packages (from poetry) (1.5.0.1)
Requirement already satisfied: pyparsing<3.0,>=2.2 in /home/robin/.local/lib/python3.6/site-packages (from poetry) (2.4.2)
Requirement already satisfied: requests<3.0,>=2.18 in /home/robin/.local/lib/python3.6/site-packages (from poetry) (2.22.0)
Requirement already satisfied: importlib-metadata<0.24,>=0.23; python_version < "3.8" in /usr/local/lib/python3.6/dist-packages (from poetry) (0.23)
Requirement already satisfied: requests-toolbelt<0.9.0,>=0.8.0 in /home/robin/.local/lib/python3.6/site-packages (from poetry) (0.8.0)
Requirement already satisfied: html5lib<2.0,>=1.0 in /home/robin/.local/lib/python3.6/site-packages (from poetry) (1.0.1)
Requirement already satisfied: cachy<0.4.0,>=0.3.0 in /usr/local/lib/python3.6/dist-packages (from poetry) (0.3.0)
Requirement already satisfied: shellingham<2.0,>=1.1 in /home/robin/.local/lib/python3.6/site-packages (from poetry) (1.3.1)
Requirement already satisfied: tomlkit<0.6.0,>=0.5.8 in /usr/local/lib/python3.6/dist-packages (from poetry) (0.5.8)
Requirement already satisfied: pyrsistent<0.15.0,>=0.14.2 in /home/robin/.local/lib/python3.6/site-packages (from poetry) (0.14.11)
Requirement already satisfied: pexpect<5.0.0,>=4.7.0 in /home/robin/.local/lib/python3.6/site-packages (from poetry) (4.7.0)
Requirement already satisfied: cachecontrol[filecache]<0.13.0,>=0.12.4 in /home/robin/.local/lib/python3.6/site-packages (from poetry) (0.12.5)
Requirement already satisfied: clikit<0.5.0,>=0.4.1 in /usr/local/lib/python3.6/dist-packages (from poetry) (0.4.1)
Requirement already satisfied: keyring<20.0,>=19.0; python_version >= "3.5" and python_version < "4.0" in /usr/local/lib/python3.6/dist-packages (from poetry) (19.3.0)
Requirement already satisfied: attrs>=17.4.0 in /home/robin/.local/lib/python3.6/site-packages (from jsonschema<4.0,>=3.1->poetry) (19.1.0)
Requirement already satisfied: six>=1.11.0 in /home/robin/.local/lib/python3.6/site-packages (from jsonschema<4.0,>=3.1->poetry) (1.12.0)
Requirement already satisfied: setuptools in /home/robin/.local/lib/python3.6/site-packages (from jsonschema<4.0,>=3.1->poetry) (41.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/robin/.local/lib/python3.6/site-packages (from requests<3.0,>=2.18->poetry) (2019.9.11)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /home/robin/.local/lib/python3.6/site-packages (from requests<3.0,>=2.18->poetry) (1.25.3)
Requirement already satisfied: idna<2.9,>=2.5 in /home/robin/.local/lib/python3.6/site-packages (from requests<3.0,>=2.18->poetry) (2.8)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /home/robin/.local/lib/python3.6/site-packages (from requests<3.0,>=2.18->poetry) (3.0.4)
Requirement already satisfied: zipp>=0.5 in /usr/local/lib/python3.6/dist-packages (from importlib-metadata<0.24,>=0.23; python_version < "3.8"->poetry) (0.6.0)
Requirement already satisfied: webencodings in /home/robin/.local/lib/python3.6/site-packages (from html5lib<2.0,>=1.0->poetry) (0.5.1)
Requirement already satisfied: ptyprocess>=0.5 in /home/robin/.local/lib/python3.6/site-packages (from pexpect<5.0.0,>=4.7.0->poetry) (0.6.0)
Requirement already satisfied: msgpack in /home/robin/.local/lib/python3.6/site-packages (from cachecontrol[filecache]<0.13.0,>=0.12.4->poetry) (0.6.1)
Requirement already satisfied: lockfile>=0.9; extra == "filecache" in /home/robin/.local/lib/python3.6/site-packages (from cachecontrol[filecache]<0.13.0,>=0.12.4->poetry) (0.12.2)
Requirement already satisfied: pastel<0.2.0,>=0.1.0 in /home/robin/.local/lib/python3.6/site-packages (from clikit<0.5.0,>=0.4.1->poetry) (0.1.1)
Requirement already satisfied: pylev<2.0,>=1.3 in /home/robin/.local/lib/python3.6/site-packages (from clikit<0.5.0,>=0.4.1->poetry) (1.3.0)
Requirement already satisfied: secretstorage; sys_platform == "linux" in /usr/lib/python3/dist-packages (from keyring<20.0,>=19.0; python_version >= "3.5" and python_version < "4.0"->poetry) (2.3.1)
Requirement already satisfied: more-itertools in /usr/local/lib/python3.6/dist-packages (from zipp>=0.5->importlib-metadata<0.24,>=0.23; python_version < "3.8"->poetry) (8.0.2)
Installing collected packages: poetry
Successfully installed poetry-1.0.0

$ poetry -vvv version
Traceback (most recent call last):
  File "/usr/local/bin/poetry", line 5, in <module>
    from poetry.console import main
  File "/usr/local/lib/python3.6/dist-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/local/lib/python3.6/dist-packages/poetry/console/application.py", line 1, in <module>
    from cleo import Application as BaseApplication
  File "/usr/local/lib/python3.6/dist-packages/cleo/__init__.py", line 3, in <module>
    from .application import Application
  File "/usr/local/lib/python3.6/dist-packages/cleo/application.py", line 7, in <module>
    from .commands.completions_command import CompletionsCommand
  File "/usr/local/lib/python3.6/dist-packages/cleo/commands/completions_command.py", line 10, in <module>
    from ..helpers import argument
ImportError: cannot import name 'argument'
```

**Comment by Ivoz** [comment]
or [pipx](https://pipxproject.github.io/pipx/) is a great meta-tool for these kinds of tools.

**Comment by thejohnfreeman** [comment]
With pipx, I finally have a tool to create an isolated environment to install Poetry so I can create isolated environments to install my projects. Perfect!

Joking aside, it would be nice if Poetry made it a mission to work after being installed with pip (just like pipx!).

**Comment by rvanlaar** [comment]
The issue seems to have been resolved.

I just installed Poetry 1.0.3 on a clean install of Ubuntu 18.04.4 LTS.
