### ISSUE TITLE
poetry can break if `six` is dev-dependency

### ISSUE THREAD

**Issue by nekokatt** [python-poetry/poetry#1780]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

If you execute poetry within a venv, make a new project, add six as a dev dependency, then run `poetry update`, `poetry update --no-dev`, `poetry update`, the installation of poetry becomes broken and has to be reinstalled manually to continue.

Reproduce with the following script:

```sh
#!/bin/sh
set -x

# Setup isolated environment
rm .venv pyproject.toml poetry.lock -Rf
python -m venv .venv
source .venv/bin/activate
pip install poetry

# Reproduce issue
poetry init -n --dev-dependency six 
poetry update
poetry update --no-dev
poetry update    # <-- *bang!*
```

Expect: `six` to be reinstalled in my project on the last command.
Actual:

```sh
+ poetry init -n --dev-dependency six

This command will guide you through creating your pyproject.toml config.


You can specify a package in the following forms:
  - A single name (requests)
  - A name and a constraint (requests ^2.23.0)
  - A git url (git+https://github.com/python-poetry/poetry.git)
  - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
  - A file path (../my-package/my-package.whl)
  - A directory (../my-package/)
  - An url (https://example.com/packages/my-package-0.1.0.tar.gz)


Using version ^1.13.0 for six

+ poetry update
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

No dependencies to install or update

+ poetry update --no-dev
Updating dependencies
Resolving dependencies... (0.1s)


Package operations: 0 installs, 0 updates, 1 removal

  - Removing six (1.13.0)
+ poetry update
Traceback (most recent call last):
  File "/home/.../code/poetry-issue/.venv/bin/poetry", line 6, in <module>
    from poetry.console import main
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/poetry/console/application.py", line 5, in <module>
    from .commands.about import AboutCommand
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/poetry/console/commands/check.py", line 1, in <module>
    from poetry.factory import Factory
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/poetry/factory.py", line 15, in <module>
    from .json import validate_object
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/poetry/json/__init__.py", line 7, in <module>
    import jsonschema
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/jsonschema/__init__.py", line 21, in <module>
    from jsonschema._types import TypeChecker
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/jsonschema/_types.py", line 3, in <module>
    from pyrsistent import pmap
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/pyrsistent/__init__.py", line 3, in <module>
    from pyrsistent._pmap import pmap, m, PMap
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/pyrsistent/_pmap.py", line 1, in <module>
    from ._compat import Mapping, Hashable
  File "/home/.../code/poetry-issue/.venv/lib/python3.8/site-packages/pyrsistent/_compat.py", line 1, in <module>
    from six import string_types
ModuleNotFoundError: No module named 'six'
```

Generated pyproject.toml

```toml
[tool.poetry]
name = "poetry-issue"
version = "0.1.0"
description = ""
authors = ["Nekokatt <3903853-nekokatt@users.noreply.gitlab.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
six = "^1.13.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

This occurs if six is a transitive dependency of any dev dependency, and you run `poetry update --no-dev`, which is somewhat of a nuisance to work with unfortunately

**Comment by sdispater** [comment]
Poetry is not supposed to be installed in the virtualenv it is managing otherwise you can have issues like the one you are experiencing. There is nothing we can do for that and you should follow the recommended ways of installing Poetry described in the documentation: https://python-poetry.org/docs/#installation
