### ISSUE TITLE
Unable to add djangorestframework-simplejwt 4.4.0

### ISSUE THREAD

**Issue by oliverandrich** [python-poetry/poetry#1793]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15
- **Poetry version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/oliverandrich/3d1f36e76ba0a7d3c086bc4f1ef39e1a

## Issue
When I try to add djangorestframework-simplejwt to my project, I get the following confusing error message. I am using 3.7.5 and so it fits within the range of >=3.6,<3.9. Installing it using pip works without problems.

```bash
❯ poetry add djangorestframework_simplejwt
Using version ^4.4.0 for djangorestframework_simplejwt

Updating dependencies
Resolving dependencies... (0.2s)

[SolverProblemError]
The current project's Python requirement (^3.7) is not compatible with some of the required packages Python requirement:
  - djangorestframework-simplejwt requires Python >=3.6,<3.9

Because djangorestframework-simplejwt (4.4.0) requires Python >=3.6,<3.9
 and no versions of djangorestframework-simplejwt match >4.4.0,<5.0.0, djangorestframework-simplejwt is forbidden.
So, because django-project-boilerplate depends on djangorestframework_simplejwt (^4.4.0), version solving failed.
```

Here is also the output from poetry add -vvv

```bash
❯ poetry add -vvv djangorestframework_simplejwt
Using virtualenv: /Users/oa/tmp/django-project-boilerplate/.venv
PyPI: No release information found for djangorestframework_simplejwt-1.5, skipping
PyPI: 31 packages found for djangorestframework_simplejwt *
Using version ^4.4.0 for djangorestframework_simplejwt

Updating dependencies
Resolving dependencies...
   1: fact: django-project-boilerplate is 0.1.0
   1: derived: django-project-boilerplate
   1: fact: django-project-boilerplate depends on bcrypt (^3.1.7)
   1: fact: django-project-boilerplate depends on django (^3.0.1)
   1: fact: django-project-boilerplate depends on django-cors-headers (^3.2.0)
   1: fact: django-project-boilerplate depends on django-environ (^0.4.5)
   1: fact: django-project-boilerplate depends on django-filter (^2.2.0)
   1: fact: django-project-boilerplate depends on django-health-check (^3.11.1)
   1: fact: django-project-boilerplate depends on django-lifecycle (^0.7.0)
   1: fact: django-project-boilerplate depends on django-memoize (^2.2.1)
   1: fact: django-project-boilerplate depends on django-model-utils (^4.0.0)
   1: fact: django-project-boilerplate depends on django-redis-cache (^2.1.0)
   1: fact: django-project-boilerplate depends on djangorestframework (^3.11.0)
   1: fact: django-project-boilerplate depends on gunicorn (^19.9.0)
   1: fact: django-project-boilerplate depends on markdown (^3.1.1)
   1: fact: django-project-boilerplate depends on psycopg2-binary (^2.8.4)
   1: fact: django-project-boilerplate depends on sentry-sdk (^0.13.5)
   1: fact: django-project-boilerplate depends on whitenoise (^5.0.0)
   1: fact: django-project-boilerplate depends on djoser (^2.0.3)
   1: fact: django-project-boilerplate depends on djangorestframework_simplejwt (^4.4.0)
   1: fact: django-project-boilerplate depends on black (^19.10b0)
   1: fact: django-project-boilerplate depends on django-debug-toolbar (^2.1)
   1: fact: django-project-boilerplate depends on flake8 (^3.7.9)
   1: fact: django-project-boilerplate depends on ipython (^7.10.2)
   1: fact: django-project-boilerplate depends on isort (^4.3.21)
   1: fact: django-project-boilerplate depends on pytest (^5.3.2)
   1: fact: django-project-boilerplate depends on pytest-cov (^2.8.1)
   1: fact: django-project-boilerplate depends on pytest-django (^3.7.0)
   1: fact: django-project-boilerplate depends on pytest-mock (^1.13.0)
   1: fact: django-project-boilerplate depends on pytest-factoryboy (^2.0.3)
   1: fact: django-project-boilerplate depends on pytest-xdist (^1.31.0)
   1: fact: django-project-boilerplate depends on pip-licenses (^1.18.0)
   1: fact: django-project-boilerplate depends on coverage (^5.0)
   1: fact: django-project-boilerplate depends on flake8-coding (^1.3.2)
   1: fact: django-project-boilerplate depends on black (^19.10b0)
   1: fact: django-project-boilerplate depends on django-debug-toolbar (^2.1)
   1: fact: django-project-boilerplate depends on flake8 (^3.7.9)
   1: fact: django-project-boilerplate depends on ipython (^7.10.2)
   1: fact: django-project-boilerplate depends on isort (^4.3.21)
   1: fact: django-project-boilerplate depends on pytest (^5.3.2)
   1: fact: django-project-boilerplate depends on pytest-cov (^2.8.1)
   1: fact: django-project-boilerplate depends on pytest-django (^3.7.0)
   1: fact: django-project-boilerplate depends on pytest-mock (^1.13.0)
   1: fact: django-project-boilerplate depends on pytest-factoryboy (^2.0.3)
   1: fact: django-project-boilerplate depends on pytest-xdist (^1.31.0)
   1: fact: django-project-boilerplate depends on pip-licenses (^1.18.0)
   1: fact: django-project-boilerplate depends on coverage (^5.0)
   1: fact: django-project-boilerplate depends on flake8-coding (^1.3.2)
   1: selecting django-project-boilerplate (0.1.0)
   1: derived: flake8-coding (^1.3.2)
   1: derived: coverage (^5.0)
   1: derived: pip-licenses (^1.18.0)
   1: derived: pytest-xdist (^1.31.0)
   1: derived: pytest-factoryboy (^2.0.3)
   1: derived: pytest-mock (^1.13.0)
   1: derived: pytest-django (^3.7.0)
   1: derived: pytest-cov (^2.8.1)
   1: derived: pytest (^5.3.2)
   1: derived: isort (^4.3.21)
   1: derived: ipython (^7.10.2)
   1: derived: flake8 (^3.7.9)
   1: derived: django-debug-toolbar (^2.1)
   1: derived: black (^19.10b0)
   1: derived: djangorestframework_simplejwt (^4.4.0)
   1: derived: djoser (^2.0.3)
   1: derived: whitenoise (^5.0.0)
   1: derived: sentry-sdk (^0.13.5)
   1: derived: psycopg2-binary (^2.8.4)
   1: derived: markdown (^3.1.1)
   1: derived: gunicorn (^19.9.0)
   1: derived: djangorestframework (^3.11.0)
   1: derived: django-redis-cache (^2.1.0)
   1: derived: django-model-utils (^4.0.0)
   1: derived: django-memoize (^2.2.1)
   1: derived: django-lifecycle (^0.7.0)
   1: derived: django-health-check (^3.11.1)
   1: derived: django-filter (^2.2.0)
   1: derived: django-environ (^0.4.5)
   1: derived: django-cors-headers (^3.2.0)
   1: derived: django (^3.0.1)
   1: derived: bcrypt (^3.1.7)
PyPI: 1 packages found for flake8-coding >=1.3.2,<2.0.0
PyPI: No release information found for coverage-2.5, skipping
PyPI: No release information found for coverage-2.6, skipping
PyPI: No release information found for coverage-2.75, skipping
PyPI: No release information found for coverage-2.76, skipping
PyPI: No release information found for coverage-2.77, skipping
PyPI: No release information found for coverage-2.78, skipping
PyPI: No release information found for coverage-2.8, skipping
PyPI: No release information found for coverage-2.80, skipping
PyPI: No release information found for coverage-2.85, skipping
PyPI: 2 packages found for coverage >=5.0,<6.0
PyPI: 1 packages found for pip-licenses >=1.18.0,<2.0.0
PyPI: 1 packages found for pytest-xdist >=1.31.0,<2.0.0
PyPI: 1 packages found for pytest-factoryboy >=2.0.3,<3.0.0
PyPI: 1 packages found for pytest-mock >=1.13.0,<2.0.0
PyPI: 1 packages found for pytest-django >=3.7.0,<4.0.0
PyPI: 1 packages found for pytest-cov >=2.8.1,<3.0.0
PyPI: 1 packages found for pytest >=5.3.2,<6.0.0
PyPI: 1 packages found for isort >=4.3.21,<5.0.0
PyPI: No release information found for ipython-0.6.10, skipping
PyPI: No release information found for ipython-0.6.11, skipping
PyPI: No release information found for ipython-0.6.12, skipping
PyPI: No release information found for ipython-0.6.13, skipping
PyPI: No release information found for ipython-0.6.14, skipping
PyPI: No release information found for ipython-0.6.15, skipping
PyPI: No release information found for ipython-0.6.4, skipping
PyPI: No release information found for ipython-0.6.5, skipping
PyPI: No release information found for ipython-0.6.6, skipping
PyPI: No release information found for ipython-0.6.7, skipping
PyPI: No release information found for ipython-0.6.8, skipping
PyPI: No release information found for ipython-0.6.9, skipping
PyPI: No release information found for ipython-0.7.0, skipping
PyPI: No release information found for ipython-0.7.1, skipping
PyPI: No release information found for ipython-0.7.1.fix1, skipping
PyPI: No release information found for ipython-0.7.2, skipping
PyPI: No release information found for ipython-0.7.4.svn.r2010, skipping
PyPI: No release information found for ipython-0.8.0, skipping
PyPI: No release information found for ipython-0.8.1, skipping
PyPI: No release information found for ipython-0.8.2, skipping
PyPI: No release information found for ipython-0.8.3, skipping
PyPI: No release information found for ipython-0.8.4, skipping
PyPI: No release information found for ipython-0.9, skipping
PyPI: No release information found for ipython-0.9.1, skipping
PyPI: No release information found for ipython-4.0.0-b1, skipping
PyPI: 1 packages found for ipython >=7.10.2,<8.0.0
PyPI: 1 packages found for flake8 >=3.7.9,<4.0.0
PyPI: No release information found for django-debug-toolbar-1.3.1, skipping
PyPI: 1 packages found for django-debug-toolbar >=2.1,<3.0
PyPI: 1 packages found for black >=19.10b0,<20.0
PyPI: 1 packages found for djoser >=2.0.3,<3.0.0
PyPI: 2 packages found for whitenoise >=5.0.0,<6.0.0
PyPI: 1 packages found for sentry-sdk >=0.13.5,<0.14.0
PyPI: 1 packages found for psycopg2-binary >=2.8.4,<3.0.0
PyPI: No release information found for markdown-1.6, skipping
PyPI: 1 packages found for markdown >=3.1.1,<4.0.0
PyPI: No release information found for gunicorn-20.0.1, skipping
PyPI: 2 packages found for gunicorn >=19.9.0,<20.0.0
PyPI: No release information found for djangorestframework-2.4.7, skipping
PyPI: 1 packages found for djangorestframework >=3.11.0,<4.0.0
PyPI: 1 packages found for django-redis-cache >=2.1.0,<3.0.0
PyPI: 1 packages found for django-model-utils >=4.0.0,<5.0.0
PyPI: 1 packages found for django-memoize >=2.2.1,<3.0.0
PyPI: 1 packages found for django-lifecycle >=0.7.0,<0.8.0
PyPI: 1 packages found for django-health-check >=3.11.1,<4.0.0
PyPI: 1 packages found for django-filter >=2.2.0,<3.0.0
PyPI: 1 packages found for django-environ >=0.4.5,<0.5.0
PyPI: 1 packages found for django-cors-headers >=3.2.0,<4.0.0
PyPI: No release information found for django-1.0.1, skipping
PyPI: No release information found for django-1.0.2, skipping
PyPI: No release information found for django-1.0.3, skipping
PyPI: No release information found for django-1.0.4, skipping
PyPI: No release information found for django-1.1, skipping
PyPI: No release information found for django-1.1.1, skipping
PyPI: No release information found for django-1.1.2, skipping
PyPI: 1 packages found for django >=3.0.1,<4.0.0
PyPI: 1 packages found for bcrypt >=3.1.7,<4.0.0
   1: fact: flake8-coding (1.3.2) depends on flake8 (*)
   1: selecting flake8-coding (1.3.2)
   1: fact: pip-licenses (1.18.0) depends on PTable (*)
   1: selecting pip-licenses (1.18.0)
   1: derived: PTable (*)
PyPI: No release information found for ptable-0.9.0, skipping
PyPI: No release information found for ptable-0.9.1, skipping
PyPI: 1 packages found for ptable *
   1: fact: pytest-xdist (1.31.0) depends on execnet (>=1.1)
   1: fact: pytest-xdist (1.31.0) depends on pytest (>=4.4.0)
   1: fact: pytest-xdist (1.31.0) depends on pytest-forked (*)
   1: fact: pytest-xdist (1.31.0) depends on six (*)
   1: selecting pytest-xdist (1.31.0)
   1: derived: six (*)
   1: derived: pytest-forked (*)
   1: derived: execnet (>=1.1)
PyPI: 24 packages found for six *
PyPI: 7 packages found for pytest-forked *
PyPI: 10 packages found for execnet >=1.1
   1: fact: pytest-factoryboy (2.0.3) depends on inflection (*)
   1: fact: pytest-factoryboy (2.0.3) depends on factory_boy (>=2.10.0)
   1: fact: pytest-factoryboy (2.0.3) depends on pytest (>=3.3.2)
   1: selecting pytest-factoryboy (2.0.3)
   1: derived: factory_boy (>=2.10.0)
   1: derived: inflection (*)
PyPI: 4 packages found for factory-boy >=2.10.0
PyPI: 6 packages found for inflection *
   1: fact: pytest-mock (1.13.0) depends on pytest (>=2.7)
   1: selecting pytest-mock (1.13.0)
   1: fact: pytest-django (3.7.0) depends on pytest (>=3.6)
   1: selecting pytest-django (3.7.0)
   1: fact: pytest-cov (2.8.1) depends on pytest (>=3.6)
   1: fact: pytest-cov (2.8.1) depends on coverage (>=4.4)
   1: selecting pytest-cov (2.8.1)
   1: fact: pytest (5.3.2) depends on py (>=1.5.0)
   1: fact: pytest (5.3.2) depends on packaging (*)
   1: fact: pytest (5.3.2) depends on attrs (>=17.4.0)
   1: fact: pytest (5.3.2) depends on more-itertools (>=4.0.0)
   1: fact: pytest (5.3.2) depends on pluggy (>=0.12,<1.0)
   1: fact: pytest (5.3.2) depends on wcwidth (*)
   1: fact: pytest (5.3.2) depends on importlib-metadata (>=0.12)
   1: fact: pytest (5.3.2) depends on atomicwrites (>=1.0)
   1: fact: pytest (5.3.2) depends on colorama (*)
   1: selecting pytest (5.3.2)
   1: derived: colorama (*)
   1: derived: atomicwrites (>=1.0)
   1: derived: importlib-metadata (>=0.12)
   1: derived: wcwidth (*)
   1: derived: pluggy (>=0.12,<1.0)
   1: derived: more-itertools (>=4.0.0)
   1: derived: attrs (>=17.4.0)
   1: derived: packaging (*)
   1: derived: py (>=1.5.0)
PyPI: 41 packages found for colorama *
PyPI: 6 packages found for atomicwrites >=1.0
PyPI: 19 packages found for importlib-metadata >=0.12
PyPI: 9 packages found for wcwidth *
PyPI: 3 packages found for pluggy >=0.12,<1.0
PyPI: 13 packages found for more-itertools >=4.0.0
PyPI: 6 packages found for attrs >=17.4.0
PyPI: 25 packages found for packaging *
PyPI: No release information found for py-0.8.0-alpha2, skipping
PyPI: No release information found for py-0.9.0, skipping
PyPI: No release information found for py-1.4.32.dev1, skipping
PyPI: 7 packages found for py >=1.5.0
   1: fact: isort (4.3.21) depends on toml (*)
   1: selecting isort (4.3.21)
   1: derived: toml (*)
PyPI: 14 packages found for toml *
   1: fact: ipython (7.10.2) depends on jedi (>=0.10)
   1: fact: ipython (7.10.2) depends on decorator (*)
   1: fact: ipython (7.10.2) depends on pickleshare (*)
   1: fact: ipython (7.10.2) depends on traitlets (>=4.2)
   1: fact: ipython (7.10.2) depends on prompt-toolkit (>=2.0.0,<3.0.0 || >3.0.0,<3.0.1 || >3.0.1,<3.1.0)
   1: fact: ipython (7.10.2) depends on pygments (*)
   1: fact: ipython (7.10.2) depends on backcall (*)
   1: fact: ipython (7.10.2) depends on pexpect (*)
   1: fact: ipython (7.10.2) depends on appnope (*)
   1: fact: ipython (7.10.2) depends on colorama (*)
   1: selecting ipython (7.10.2)
   1: derived: appnope (*)
   1: derived: pexpect (*)
   1: derived: backcall (*)
   1: derived: pygments (*)
   1: derived: prompt-toolkit (>=2.0.0,<3.0.0 || >3.0.0,<3.0.1 || >3.0.1,<3.1.0)
   1: derived: traitlets (>=4.2)
   1: derived: pickleshare (*)
   1: derived: decorator (*)
   1: derived: jedi (>=0.10)
PyPI: 8 packages found for appnope *
PyPI: No release information found for pexpect-0.97, skipping
PyPI: No release information found for pexpect-2.01, skipping
PyPI: 16 packages found for pexpect *
PyPI: 1 packages found for backcall *
PyPI: 37 packages found for pygments *
PyPI: 11 packages found for prompt-toolkit >=2.0.0,<3.0.0 || >3.0.0,<3.0.1 || >3.0.1,<3.1.0
PyPI: No release information found for traitlets-4.0.0.dev, skipping
PyPI: 7 packages found for traitlets >=4.2
PyPI: 12 packages found for pickleshare *
PyPI: No release information found for decorator-3.4.1, skipping
PyPI: No release information found for decorator-4.0.8, skipping
PyPI: 24 packages found for decorator *
PyPI: 16 packages found for jedi >=0.10
   1: fact: flake8 (3.7.9) depends on entrypoints (>=0.3.0,<0.4.0)
   1: fact: flake8 (3.7.9) depends on pyflakes (>=2.1.0,<2.2.0)
   1: fact: flake8 (3.7.9) depends on pycodestyle (>=2.5.0,<2.6.0)
   1: fact: flake8 (3.7.9) depends on mccabe (>=0.6.0,<0.7.0)
   1: selecting flake8 (3.7.9)
   1: derived: mccabe (>=0.6.0,<0.7.0)
   1: derived: pycodestyle (>=2.5.0,<2.6.0)
   1: derived: pyflakes (>=2.1.0,<2.2.0)
   1: derived: entrypoints (>=0.3.0,<0.4.0)
PyPI: No release information found for mccabe-0.0.0, skipping
PyPI: 2 packages found for mccabe >=0.6.0,<0.7.0
PyPI: No release information found for pycodestyle-0.0.0, skipping
PyPI: 1 packages found for pycodestyle >=2.5.0,<2.6.0
PyPI: No release information found for pyflakes-0.2.0, skipping
PyPI: No release information found for pyflakes-0.2.1, skipping
PyPI: 2 packages found for pyflakes >=2.1.0,<2.2.0
PyPI: 1 packages found for entrypoints >=0.3.0,<0.4.0
   1: fact: django-debug-toolbar (2.1) depends on Django (>=1.11)
   1: fact: django-debug-toolbar (2.1) depends on sqlparse (>=0.2.0)
   1: selecting django-debug-toolbar (2.1)
   1: derived: sqlparse (>=0.2.0)
PyPI: 6 packages found for sqlparse >=0.2.0
   1: fact: black (19.10b0) depends on click (>=6.5)
   1: fact: black (19.10b0) depends on attrs (>=18.1.0)
   1: fact: black (19.10b0) depends on appdirs (*)
   1: fact: black (19.10b0) depends on toml (>=0.9.4)
   1: fact: black (19.10b0) depends on typed-ast (>=1.4.0)
   1: fact: black (19.10b0) depends on regex (*)
   1: fact: black (19.10b0) depends on pathspec (>=0.6,<1)
   1: selecting black (19.10b0)
   1: derived: pathspec (>=0.6,<1)
   1: derived: regex (*)
   1: derived: typed-ast (>=1.4.0)
   1: derived: toml (>=0.9.4)
   1: derived: appdirs (*)
   1: derived: attrs (>=18.1.0)
   1: derived: click (>=6.5)
PyPI: 1 packages found for pathspec >=0.6,<1
PyPI: 273 packages found for regex *
PyPI: 1 packages found for typed-ast >=1.4.0
PyPI: 7 packages found for appdirs *
PyPI: 4 packages found for click >=6.5
PyPI: No release information found for djangorestframework-simplejwt-1.5, skipping
PyPI: 1 packages found for djangorestframework-simplejwt >=4.4.0,<5.0.0
   1: fact: djangorestframework-simplejwt (4.4.0) requires Python >=3.6,<3.9
   1: derived: not djangorestframework-simplejwt (4.4.0)
   1: fact: no versions of djangorestframework-simplejwt match >4.4.0,<5.0.0
   1: conflict: no versions of djangorestframework-simplejwt match >4.4.0,<5.0.0
   1: derived: not djangorestframework-simplejwt (>4.4.0,<5.0.0)
   1: conflict: djangorestframework-simplejwt (4.4.0) requires Python >=3.6,<3.9
   1: ! djangorestframework-simplejwt (4.4.0) is partially satisfied by not djangorestframework-simplejwt (>4.4.0,<5.0.0)
   1: ! which is caused by "no versions of djangorestframework-simplejwt match >4.4.0,<5.0.0"
   1: ! thus: djangorestframework-simplejwt is forbidden
   1: ! djangorestframework-simplejwt (>=4.4.0,<5.0.0) is satisfied by djangorestframework_simplejwt (^4.4.0)
   1: ! which is caused by "django-project-boilerplate depends on djangorestframework_simplejwt (^4.4.0)"
   1: ! thus: version solving failed
   1: Version solving took 0.818 seconds.
   1: Tried 1 solutions.

[SolverProblemError]
The current project's Python requirement (^3.7) is not compatible with some of the required packages Python requirement:
  - djangorestframework-simplejwt requires Python >=3.6,<3.9

Because djangorestframework-simplejwt (4.4.0) requires Python >=3.6,<3.9
 and no versions of djangorestframework-simplejwt match >4.4.0,<5.0.0, djangorestframework-simplejwt is forbidden.
So, because django-project-boilerplate depends on djangorestframework_simplejwt (^4.4.0), version solving failed.

Traceback (most recent call last):
  File "/Users/oa/.pyenv/versions/3.7.5/lib/python3.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/oa/.pyenv/versions/3.7.5/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/oa/.pyenv/versions/3.7.5/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/oa/.pyenv/versions/3.7.5/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/oa/.pyenv/versions/3.7.5/lib/python3.7/site-packages/poetry/console/commands/add.py", line 149, in handle
    status = installer.run()
  File "/Users/oa/.pyenv/versions/3.7.5/lib/python3.7/site-packages/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/Users/oa/.pyenv/versions/3.7.5/lib/python3.7/site-packages/poetry/installation/installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "/Users/oa/.pyenv/versions/3.7.5/lib/python3.7/site-packages/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/Users/oa/.pyenv/versions/3.7.5/lib/python3.7/site-packages/poetry/puzzle/solver.py", line 190, in _solve
    raise SolverProblemError(e)
```

**Comment by sneakypete81** [comment]
The error says:

`- djangorestframework-simplejwt requires Python >=3.6,<3.9`

but your `pyproject.toml' includes Python 3.9:

`python = "^3.7"`

Try changing that line to:

`python = "^3.7, <3.9"`

**Comment by oliverandrich** [comment]
Damn! Thanks a lot @sneakypete81. This solved indeed my problem. I am still learning the dependency resolution rules of poetry. Some things really differ compared to pip and pipenv. But they differ for good reasons.

**Comment by sneakypete81** [comment]
No worries :-). I came here with a similar problem, then it finally dawned on me.

**Comment by nffdiogosilva** [comment]
x3. I've also came here with the same problem. Thanks for creating the ticket @oliverandrich

**Comment by differentMonster** [comment]
i have the same problem but i even if i change to python = "^3.7, <3.9" it still wont work any idea guys ?

```
[tool.poetry]
name = "weddinghousedashboard"
version = "0.1.0"
description = ""
authors = ["differentmonster <differentcodemonster@gmail.com>"]

[tool.poetry.dependencies]
# python = "^3.8, <3.9"
python = ">=3.6, <3.9"
asgiref = "^3.2.10"
autopep8 = "^1.5.3"
django = "^3.0.7"
pycodestyle = "^2.6.0"
pytz = "^2020.1"
sqlparse = "^0.3.1"
Unipath = "^1.1"
dj-database-url = "^0.5.0"
gunicorn = "^20.0.4"
whitenoise = "^5.1.0"
django-rest-framework = "^0.1.0"
pillow = "^7.1.2"
django-pdb = "^0.6.2"
django-environ = "^0.4.5"
psycopg2 = "^2.8.5"
django-cors-headers = "^3.5.0"
django-countries = "^6.1.3"
djangorestframework-simplejwt = "^4.4.0"
pytest = "^6.2.1"
pytest-django = "^4.1.0"
pytest-cov = "^2.11.1"
djoser = "^2.1.0"

[tool.poetry.dev-dependencies]

[build-system]
# Should be the same as `$POETRY_VERSION`:
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

```
