### ISSUE TITLE
Sub-dependencies using `path` should not be installed before parent

### ISSUE THREAD

**Issue by daaain** [python-poetry/poetry#1812]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: `python:3.7` Docker image
- **Poetry version**: 1.0.0

## Issue

I have a legacy repo which has multiple Python packages, which used to work with `pipenv` by declaring multiple `git` dependencies with `subdirectory` set.

Since that's not supported by Poetry I created a master `pyproject.toml` in the root directory, trying to make all the libraries installable as a bundle – in my case it's not important to be able install them individually.

While it feels like a bit of a hack, using the `packages` config I was able to make all libraries import after a fair bit of trial and error and co-locating them in the same source folder (see related issue #1811).

```toml
[tool.poetry]
name = "basis-libraries"
# ...

packages = [
    { include = "basis_sqlalchemy_filters", from="basis_utils" },
    { include = "basis_utils", from="basis_utils" },
    { include = "basis_messaging", from="basis_utils" },
]

include = ["**/*"]

[tool.poetry.dependencies]
python = "^3.7"
basis-utils = { path = "./basis_utils/" }
basis-sqlalchemy-filters = { path = "./basis_utils/basis_sqlalchemy_filters/" }
```

The issue however is that each of these have their sub-dependencies, but while declaring them in `[tool.poetry.dependencies]` works when installing in the library repo itself, when it's a `git` dependency in another application the installation fails with the following error output (all other dependencies removed for brevity):

```
Step 29/32 : RUN poetry install -vvv
 ---> Running in 5bb1928c9684
Creating virtualenv bike-9TtSrW0h-py3.7 in /home/app/.cache/pypoetry/virtualenvs
Using virtualenv: /home/app/.cache/pypoetry/virtualenvs/bike-9TtSrW0h-py3.7
Updating dependencies
Resolving dependencies...
   1: fact: bike is 1.0.0
   1: derived: bike
   1: fact: bike depends on basis-libraries (*)
   1: selecting bike (1.0.0)
   1: derived: basis-libraries (*)
   1: fact: basis-libraries (1.0.0) depends on basis-utils (*)
   1: fact: basis-libraries (1.0.0) depends on basis-sqlalchemy-filters (*)
   1: selecting basis-libraries (1.0.0 0e62443)
   1: derived: basis-sqlalchemy-filters (*)
   1: derived: basis-utils (*)
   1: Version solving took 1.804 seconds.
   1: Tried 1 solutions.

[FileNotFoundError]
[Errno 2] No such file or directory: '/tmp/pypoetry-git-basis-librariesidc40fof/basis_utils/basis_sqlalchemy_filters'

Traceback (most recent call last):
  File "/home/app/.local/lib/python3.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/app/.local/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/app/.local/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/app/.local/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/app/.local/lib/python3.7/site-packages/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/home/app/.local/lib/python3.7/site-packages/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/home/app/.local/lib/python3.7/site-packages/poetry/installation/installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "/home/app/.local/lib/python3.7/site-packages/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/home/app/.local/lib/python3.7/site-packages/poetry/puzzle/solver.py", line 181, in _solve
    self._package, self._provider, locked=locked, use_latest=use_latest
  File "/home/app/.local/lib/python3.7/site-packages/poetry/mixology/__init__.py", line 7, in resolve_version
    return solver.solve()
  File "/home/app/.local/lib/python3.7/site-packages/poetry/mixology/version_solver.py", line 80, in solve
    next = self._choose_package_version()
  File "/home/app/.local/lib/python3.7/site-packages/poetry/mixology/version_solver.py", line 350, in _choose_package_version
    dependency = min(*unsatisfied, key=_get_min)
  File "/home/app/.local/lib/python3.7/site-packages/poetry/mixology/version_solver.py", line 343, in _get_min
    return len(self._provider.search_for(dependency))
  File "/home/app/.local/lib/python3.7/site-packages/poetry/puzzle/provider.py", line 134, in search_for
    packages = self.search_for_directory(dependency)
  File "/home/app/.local/lib/python3.7/site-packages/poetry/puzzle/provider.py", line 274, in search_for_directory
    dependency.full_path, name=dependency.name
  File "/home/app/.local/lib/python3.7/site-packages/poetry/puzzle/provider.py", line 326, in get_package_from_directory
    os.chdir(str(directory))
```

I might be wrong with my diagnosis, but I think Poetry is trying to install the sub-dependencies first, but because their parent is not fully cloned from `git` yet (I'm guessing the resolver only gets metadata?), the directories referenced in `path` are not there.

So while I completely understand why Poetry is installing leaf dependencies first in order to make sure branch dependencies have everything they need to build, I think for `path` dependencies the parent's files should be downloaded first. While this might only be a problem for source based `git` dependencies, it makes it completely impossible to resolve sub-dependencies, unless they are re-declared in the root `pyproject.toml`.

**Comment by finswimmer** [comment]
Hello @daaain,

could you please try if this issue is still there in the latest poetry version (1.0.3)?

fin swimmer

**Comment by finswimmer** [comment]
Closing this because we haven't received more information for a long time.

Feel free to leave a comment if you disagree.
