### ISSUE TITLE
Pip does not install package with git dependencies

### ISSUE THREAD

**Issue by matemax** [python-poetry/poetry#1825]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**:  Windows 10 
- **Poetry version**: 1.0.0 + changes from (https://github.com/python-poetry/poetry/issues/1697)
- **Link of a with the contents of your pyproject.toml file**:  [Gist](https://github.com/matemax/test_poetry_private_deps)
## Issue

Pip fails when installed from github or builded (tar.gz) package with pyproject.toml with git dependecies. I create a test  [repository](https://github.com/matemax/test_poetry_private_deps). And try install
package from githib

```bash
pip install git+https://github.com/matemax/test_poetry_private_deps.git
```

And got

```
Collecting git+https://github.com/matemax/test_poetry_private_deps.git
  Cloning https://github.com/matemax/test_poetry_private_deps.git to c:\users\matem\appdata\local\temp\pip-req-build-7krqjgwd
  Running command git clone -q https://github.com/matemax/test_poetry_private_deps.git 'C:\Users\matem\AppData\Local\Temp\pip-req-build-7krqjgwd'
  warning: unsupported ssl version tslv1.2: using default
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
ERROR: Exception:
Traceback (most recent call last):
  File "c:\python37\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3101, in __init__
    super(Requirement, self).__init__(requirement_string)
  File "c:\python37\lib\site-packages\pip\_vendor\packaging\requirements.py", line 110, in __init__
    raise InvalidRequirement("Invalid URL: {0}".format(req.url))
pip._vendor.packaging.requirements.InvalidRequirement: Invalid URL: git+git@github.com:matemax/poetry_private_module.git@master

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\python37\lib\site-packages\pip\_internal\cli\base_command.py", line 153, in _main
    status = self.run(options, args)
  File "c:\python37\lib\site-packages\pip\_internal\commands\install.py", line 382, in run
    resolver.resolve(requirement_set)
  File "c:\python37\lib\site-packages\pip\_internal\legacy_resolve.py", line 201, in resolve
    self._resolve_one(requirement_set, req)
  File "c:\python37\lib\site-packages\pip\_internal\legacy_resolve.py", line 365, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "c:\python37\lib\site-packages\pip\_internal\legacy_resolve.py", line 313, in _get_abstract_dist_for
    req, self.session, self.finder, self.require_hashes
  File "c:\python37\lib\site-packages\pip\_internal\operations\prepare.py", line 224, in prepare_linked_requirement
    req, self.req_tracker, finder, self.build_isolation,
  File "c:\python37\lib\site-packages\pip\_internal\operations\prepare.py", line 49, in _get_prepared_distribution
    abstract_dist.prepare_distribution_metadata(finder, build_isolation)
  File "c:\python37\lib\site-packages\pip\_internal\distributions\source\legacy.py", line 37, in prepare_distribution_metadata
    self._setup_isolation(finder)
  File "c:\python37\lib\site-packages\pip\_internal\distributions\source\legacy.py", line 92, in _setup_isolation
    conflicting, missing = self.req.build_env.check_requirements(reqs)
  File "c:\python37\lib\site-packages\pip\_internal\build_env.py", line 152, in check_requirements
    if ws.find(Requirement.parse(req)) is None:
  File "c:\python37\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3147, in parse
    req, = parse_requirements(s)
  File "c:\python37\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3094, in parse_requirements
    yield Requirement(line)
  File "c:\python37\lib\site-packages\pip\_vendor\pkg_resources\__init__.py", line 3103, in __init__
    raise RequirementParseError(str(e))
pip._vendor.pkg_resources.RequirementParseError: Invalid URL: git+git@github.com:matemax/poetry_private_module.git@master
```
pip version 19.3.1

same effect if clone repository and build package

``` bash
poetry build
pip install dist/test_poetry_private_deps-0.1.0.tar.gz
```

If remove  pyproject.toml from test_poetry_private_deps-0.1.0.tar.gz pip wiil install package.

**Comment by finswimmer** [comment]
Hello  @matemax,

the problem here is, that poetry creates invalid PEP508 strings for git dependencies if the source protocol is ssh. This was already reported in #1697 and should be fixed with #1799. 

I close this as a duplicate. Leave a comment if you disagree. Thanks for confirming this issue!

fin swimmer

**Comment by matemax** [comment]
I wrote that my poetry version is 1.0.0 + changes from (#1697). I don't sure that same bug because problem  with pip

**Comment by matemax** [comment]
https://github.com/python-poetry/poetry/pull/1799 does not solve my problem

**Comment by finswimmer** [comment]
Until a poetry version with this fix available via pip, it is not possible to test it. And that's the reason:

`poetry` tells `pip` what it has to install. In case of a git repository, pip tries to build the package, based on a `pyproject.toml` or (if no `pyproject.toml` is available) `setup.py`.

The `pyproject.toml` has defined this:

```
[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

That way, pip know that it needs poetry to build the package. pip will now create a new virtual environment, where the build process will take place, and install poetry there. This poetry is received via the PyPi repository and is not the local installed one! That's why the build still fails.

**Comment by matemax** [comment]
Thank you, @finswimmer. but what should doing if i want build package on my PC and install it on other PC without poetry and PyPi (use wheels )? I thought that i can build package to archive and install.

**Comment by matemax** [comment]
And what for seyup.py in archive?
