### ISSUE TITLE
Error when adding URL tar.gz

### ISSUE THREAD

**Issue by Yelinz** [python-poetry/poetry#1836]
- [ x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 19.10
- **Poetry version**: 1.0.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/Yelinz/8becde4047b05a33f353795e7136d762

## Issue
Poetry fails to add a URL tar.gz dependency.

```bash
$ poetry add -vvv https://github.com/projectcaluma/caluma/archive/v4.3.0.tar.gz
Using virtualenv: /home/yelin/.cache/pypoetry/virtualenvs/camac-UQggRNiR-py3.7

[RuntimeError]
Unable to determine the package name of /tmp/tmpfkl5pgzy/v4.3.0.tar.gz

Traceback (most recent call last):
  File "/home/yelin/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/yelin/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/yelin/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/yelin/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/yelin/.poetry/lib/poetry/console/commands/add.py", line 89, in handle
    packages, allow_prereleases=self.option('allow-prereleases')
  File "/home/yelin/.poetry/lib/poetry/console/commands/init.py", line 294, in _determine_requirements
    requires = self._parse_requirements(requires)
  File "/home/yelin/.poetry/lib/poetry/console/commands/init.py", line 389, in _parse_requirements
    package = Provider.get_package_from_url(requirement)
  File "/home/yelin/.poetry/lib/poetry/puzzle/provider.py", line 466, in get_package_from_url
    package = cls.get_package_from_file(temp_dir / file_name)
  File "/home/yelin/.poetry/lib/poetry/puzzle/provider.py", line 246, in get_package_from_file
    'Unable to determine the package name of {}'.format(file_path)
```

**Comment by finswimmer** [comment]
Hello @Yelinz,

AFAIK the `tar.gz` must be a valid sdist package. This is not the case here. It contains just the project folder.

fin swimmer

**Comment by Yelinz** [comment]
Thanks @finswimmer !
