### ISSUE TITLE
Poetry env using different python than specified?

### ISSUE THREAD

**Issue by StephenBrown2** [python-poetry/poetry#1869]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.14.6 (Mojave)
- **Poetry version**: Poetry version 1.0.2 (Installed via homebrew)
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  See below

## Issue

This has been discussed before in several related issues, the closest being #536, but I couldn't fine one that seemed to match my situation, since I'm using the proposed solution from #1477 in the stable release of 1.0.2. My apologies if I missed the answer elsewhere.

It seems that when I have python 3.7 installed and available via homebrew, poetry (also installed via homebrew), will only ever use that Python. I would like to keep poetry installed via homebrew so it's segregated from the rest of my pythons, but it seems that poetry is still not detecting the correct python, even when I specify it using `poetry env use`. See below for how I replicated this in a brand new dir after running through a `poetry init`

```
❯ poetry --version
Poetry version 1.0.2

❯ poetry init
...
❯ cat pyproject.toml
[tool.poetry]
name = "poetry_venv_test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

❯ pyenv version
system (set by /Users/step7212/.pyenv/version)

❯ python -V
Python 2.7.17

❯ python3 -V
Python 3.7.6

❯ pyenv versions
* system (set by /Users/step7212/.pyenv/version)
  2.7.17
  3.6.10
  3.7.6
  3.8.1

❯ pyenv local 3.6.10

❯ pyenv versions
  system
  2.7.17
* 3.6.10 (set by /Users/step7212/git/hub/poetry-venv/.python-version)
  3.7.6
  3.8.1

❯ python -V
Python 3.6.10

❯ python3 -V
Python 3.6.10

❯ poetry env info

Virtualenv
Python:         3.7.6
Implementation: CPython
Path:           NA

System
Platform: darwin
OS:       posix
Python:   /usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7

❯ poetry env use python3.6 -vvv
Creating virtualenv poetry-venv-test-g8VlvTaA-py3.6 in /Users/step7212/Library/Caches/pypoetry/virtualenvs
Using virtualenv: /Users/step7212/Library/Caches/pypoetry/virtualenvs/poetry-venv-test-g8VlvTaA-py3.6

❯ poetry env info

Virtualenv
Python:         3.7.6
Implementation: CPython
Path:           /Users/step7212/Library/Caches/pypoetry/virtualenvs/poetry-venv-test-g8VlvTaA-py3.6
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7

❯ poetry env remove /Users/step7212/Library/Caches/pypoetry/virtualenvs/poetry-venv-test-g8VlvTaA-py3.6/bin/python

[ValueError]
Environment "poetry-venv-test-g8VlvTaA-py3.7" does not exist.

❯ poetry env remove /Users/step7212/Library/Caches/pypoetry/virtualenvs/poetry-venv-test-g8VlvTaA-py3.6/bin/python -vvv

[ValueError]
Environment "poetry-venv-test-g8VlvTaA-py3.7" does not exist.

Traceback (most recent call last):
  File "/usr/local/Cellar/poetry/1.0.2/libexec/vendor/lib/python3.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/Cellar/poetry/1.0.2/libexec/vendor/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/Cellar/poetry/1.0.2/libexec/vendor/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/Cellar/poetry/1.0.2/libexec/vendor/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/Cellar/poetry/1.0.2/libexec/lib/python3.7/site-packages/poetry/console/commands/env/remove.py", line 19, in handle
    venv = manager.remove(self.argument('python'))
  File "/usr/local/Cellar/poetry/1.0.2/libexec/lib/python3.7/site-packages/poetry/utils/env.py", line 451, in remove
    'Environment "{}" does not exist.'.format(name)

❯ poetry env remove python3.6
Deleted virtualenv: /Users/step7212/Library/Caches/pypoetry/virtualenvs/poetry-venv-test-g8VlvTaA-py3.6
```
I also find it interesting that `poetry env remove` will not work if I specify the full path to the venv's python, but will work if I use the pyenv alias.

**Comment by StephenBrown2** [comment]
Adding some dependencies reveals that the python installed in the virtualenv is indeed _not_ `python3.6`:
```
❯ poetry add fastapi
Using version ^0.46.0 for fastapi

Updating dependencies
Resolving dependencies... (0.5s)

Writing lock file


Package operations: 3 installs, 0 updates, 0 removals

  - Installing pydantic (1.3)
  - Installing starlette (0.12.9)
  - Installing fastapi (0.46.0)

❯ poetry add uvicorn
Using version ^0.11.1 for uvicorn

Updating dependencies
Resolving dependencies... (3.4s)

Writing lock file


Package operations: 6 installs, 3 updates, 0 removals

  - Installing click (7.0)
  - Installing h11 (0.9.0)
  - Installing httptools (0.0.13)
  - Updating pydantic (1.3 /Users/step7212/Library/Caches/pypoetry/virtualenvs/poetry-venv-test-g8VlvTaA-py3.6/lib/python3.7/site-packages -> 1.3)
  - Updating starlette (0.12.9 /Users/step7212/Library/Caches/pypoetry/virtualenvs/poetry-venv-test-g8VlvTaA-py3.6/lib/python3.7/site-packages -> 0.12.9)
  - Installing uvloop (0.14.0)
  - Installing websockets (8.0.2)
  - Updating fastapi (0.46.0 /Users/step7212/Library/Caches/pypoetry/virtualenvs/poetry-venv-test-g8VlvTaA-py3.6/lib/python3.7/site-packages -> 0.46.0)
  - Installing uvicorn (0.11.1)
```

**Comment by finswimmer** [comment]
Hello,

changing the Python version used by Poetry for new venv's via pyenv only ever worked if Poetry was installed via the `get-poetry.py` install Script.

The current preview release (1.2.0b2)  has an experimental option `virtualenvs.prefer-active-python` to do this regardless of the installation method: https://python-poetry.org/docs/master/configuration/#virtualenvsprefer-active-python-experimental

fin swimmer
