### ISSUE TITLE
UnicodeEncodeError could be a little more informative.

### ISSUE THREAD

**Issue by kierun** [python-poetry/poetry#1936]
- [X ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: CenTOS 7.
- **Poetry version**: 1.0.2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Not applicable.

## Issue

When installing my own package, I get a 
```
[UnicodeEncodeError]
'ascii' codec can't encode character u'\u2502' in position 1885: ordinal not in
range(128)
```

with the stack:

```
Traceback (most recent call last):
  File "/home/usr/.poetry/lib/poetry/_vendor/py2.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/usr/.poetry/lib/poetry/_vendor/py2.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/usr/.poetry/lib/poetry/_vendor/py2.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/usr/.poetry/lib/poetry/_vendor/py2.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/usr/.poetry/lib/poetry/console/commands/install.py", line 88, in
handle
    builder.build()
  File "/home/usr/.poetry/lib/poetry/masonry/builders/editable.py", line 17, in build
    return self._setup_build()
  File "/home/usr/.poetry/lib/poetry/masonry/builders/editable.py", line 41, in _setup_build
    self._env.run_pip('install', '-e', str(self._path))
  File "/home/usr/.poetry/lib/poetry/utils/env.py", line 843, in run_pip
    return self._run(cmd, **kwargs)
  File "/home/usr/.poetry/lib/poetry/utils/env.py", line 1071, in _run
    return super(VirtualEnv, self)._run(cmd, **kwargs)
  File "/home/usr/.poetry/lib/poetry/utils/env.py", line 875, in _run
    raise EnvCommandError(e, input=input_)
  File "/home/usr/.poetry/lib/poetry/utils/env.py", line 131, in __init__
    e.cmd, e.returncode, decode(e.output)
```

There clearly is something not correct with my code, somewhere. A hint as to *where* would be useful as currently it is obfuscated. 

Note that the same code works fine on a different machine with the same set up -- well, clearly not the same since it's not working but…

**Comment by kierun** [comment]
I fixed it by removing some of the dependencies that were in `setup.py` which I actually did not need so they were not passed to `pyporject.yaml`. Still, that is really odd.

Maybe it's just my messed up system… If you think so, feel free to close this.

**Comment by finswimmer** [comment]
Hello @kierun ,

I guess you ran into the same problem as in #221 .

fin swimmer

**Comment by kierun** [comment]
@finswimmer Yup, that looks like the one. Thank you.
