### ISSUE TITLE
poetry lock: Invalid requirement, parse error at "'šf (==0.'"

### ISSUE THREAD

**Issue by timthelion** [python-poetry/poetry#1956]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian stretch
- **Poetry version**: 1.0.2 on python 3.7.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/timthelion/836998b7198f60b3951959bac92317c2

## Issue

````
$ poetry lock -vvv
Using virtualenv: /home/test/.cache/pypoetry/virtualenvs/fšf-P6ygHmuH-py3.7
Updating dependencies
Resolving dependencies...
   1: fact: fšf is 0.1.0
   1: derived: fšf
   1: Version solving took 0.004 seconds.
   1: Tried 1 solutions.

[InvalidRequirement]
Invalid requirement, parse error at "'šf (==0.'"

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/lib/python3.7/site-packages/poetry/console/commands/lock.py", line 28, in handle
    return installer.run()
  File "/usr/local/lib/python3.7/site-packages/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/usr/local/lib/python3.7/site-packages/poetry/installation/installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "/usr/local/lib/python3.7/site-packages/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/usr/local/lib/python3.7/site-packages/poetry/puzzle/solver.py", line 181, in _solve
    self._package, self._provider, locked=locked, use_latest=use_latest
  File "/usr/local/lib/python3.7/site-packages/poetry/mixology/__init__.py", line 7, in resolve_version
    return solver.solve()
  File "/usr/local/lib/python3.7/site-packages/poetry/mixology/version_solver.py", line 80, in solve
    next = self._choose_package_version()
  File "/usr/local/lib/python3.7/site-packages/poetry/mixology/version_solver.py", line 398, in _choose_package_version
    self._solution.decide(version)
  File "/usr/local/lib/python3.7/site-packages/poetry/mixology/partial_solution.py", line 87, in decide
    Assignment.decision(package, self.decision_level, len(self._assignments))
  File "/usr/local/lib/python3.7/site-packages/poetry/mixology/assignment.py", line 35, in decision
    return cls(package.to_dependency(), True, decision_level, index)
  File "/usr/local/lib/python3.7/site-packages/poetry/packages/project_package.py", line 26, in to_dependency
    dependency = super(ProjectPackage, self).to_dependency()
  File "/usr/local/lib/python3.7/site-packages/poetry/packages/package.py", line 395, in to_dependency
    return dependency_from_pep_508(name)
  File "/usr/local/lib/python3.7/site-packages/poetry/packages/__init__.py", line 38, in dependency_from_pep_508
    req = Requirement(name)
  File "/usr/local/lib/python3.7/site-packages/poetry/version/requirements.py", line 212, in __init__
    requirement_string[e.loc : e.loc + 8]
````

**Comment by timthelion** [comment]
Removing the `š` fixes the problem.

**Comment by timthelion** [comment]
Here is a case where no unicode chars are present:

````
[tool]
[tool.poetry]
name = "Do prace na kole"
version = "0.0.0"
description = "Do prace na kole bike to work competition dopracenakole.cz"
authors = ["Automat z.s."]

[tool.poetry.dependencies]
python = ">=3.6"
asgiref = "*"
boto = "*"
celery = "*"
coreapi = "*"
createsend = "*"
dj-anonymizer = "*"
dj-fiobank-payments = "<=0.3.0"
django = ">=2.2.6"
django-admin-charts = {git = "https://github.com/PetrDlouhy/django-admin-charts", rev = "develop"}
django-admin-sortable2 = "*"
django-admin-views = "*"
django-adminactions = {git = "https://github.com/saxix/django-adminactions.git", rev = "develop"}
django-adminfilters = "==1.0.0"
django-advanced-filters = "*"
django-appconf = "*"
django-author = "*"
django-autocomplete-light = {git = "https://github.com/auto-mat/django-autocomplete-light.git", rev = "jquery"}
django-avatar = "*"
django-betterforms = "*"
django-bleach = "*"
django-bootstrap4 = "==0.0.8"
django-braces = "*"
django-bulk-update = "*"
django-cachalot = {git = "https://github.com/federicobond/django-cachalot.git", rev = "django-2.2"}
django-celery-beat = "*"
django-celery-email = "*"
django-chart-tools = "*"
django-class-based-auth-views = "*"
django-colorfield = "*"
django-composite-field = "*"
django-cors-headers = "*"
django-crispy-forms = "==1.7.2"
django-datatables-view = "*"
django-daterange-filter = "*"
django-dbbackup = "*"
django-dbtemplates = "*"
django-denorm = "*"
django-extensions = "*"
django-extra-views = "*"
django-favicon = "*"
django-fieldsignals = "*"
django-fm = "*"
django-google-tag-manager = "*"
django-gpxpy = "*"
django-import-export = "*"
django-import-export-celery = {git = "https://github.com/auto-mat/django-import-export-celery.git", rev = "master"}
django-initial-field = "*"
django-inline-static = "*"
django-ipware = "*"
django-isnull-list-filter = "*"
django-leaflet = "*"
django-likes = {git = "https://github.com/PetrDlouhy/django-likes.git", rev = "develop"}
django-mass-edit = "*"
django-model-utils = "*"
django-modeltranslation = "*"
django-nested-admin = "*"
django-oauth-toolkit = "*"
django-photologue = {git = "https://github.com/auto-mat/django-photologue.git", rev = "s3links"}
django-polymorphic = "*"
django-price-level = "*"
django-rank-query = "*"
django-redis = "*"
django-registration-redux = "*"
django-related-admin = "*"
django-reversion = "*"
django-rosetta = "*"
"django-scribbler-django2.0" = "*"
django-selectable = "*"
django-ses = "*"
django-settings-context-processor = "*"
django-sitetree = "*"
django-smart-selects = {git = "https://github.com/Murakam1/django-smart-selects.git", rev = "patch-1"}
django-smmapdfs = "*"
django-softhyphen = "*"
django-stdnumfield = {git = "https://github.com/PetrDlouhy/django-stdnumfield.git", rev = "mergeup"}
django-storages = "*"
django-su = "*"
django-subdomains = {git = "https://github.com/PetrDlouhy/django-subdomains", rev = "django20"}
django-table-select-widget = {git = "https://github.com/willardmr/DjangoTableSelectMultipleWidget.git", rev = "master"}
django-wysiwyg-redactor = {git = "https://github.com/adilkhash/django-wysiwyg-redactor"}
djangorestframework = "*"
djangorestframework-gis = "*"
djcacheutils = "*"
easy-thumbnails = "*"
faker = "*"
fiobank = "*"
flower = "*"
geopy = "*"
gpxpy = "*"
gunicorn = "*"
html2text = "*"
invoicegenerator = "*"
lxml = "*"
newrelic = "*"
ordereddict = "*"
pillow = "==6.2.0"
polyline = "*"
psycopg2 = "*"
pypdf2 = "*"
python-memcached = "*"
raven = "*"
redis = "*"
reportlab = "*"
single-beat = "*"
six = "*"
slumber = "*"
social-auth-app-django = "*"
sqlalchemy = "*"
sqlparse = "*"
stravalib = {git = "https://github.com/hozn/stravalib", rev = "master"}
svg2rlg = {git = "https://github.com/aquavitae/svg2rlg.git"}
tornado = "<6"
unidecode = "*"
vokativ = "*"
whitenoise = "*"

[tool.poetry.dev-dependencies]
coverage = "*"
coveralls = "*"
ddt = "*"
django-admin-smoke-tests = "*"
django-coverage-plugin = "*"
django-debug-toolbar = "*"
django-debug-toolbar-line-profiler = "*"
django-debug-toolbar-request-history = "*"
django-debug-toolbar-template-timings = "*"
django-livereload-server = "*"
django-nose = "*"
flake8 = "*"
flake8-blind-except = "*"
flake8-builtins = "*"
flake8-comprehensions = "*"
flake8-import-order = "*"
flake8-strict = "*"
flake8-tidy-imports = "*"
freezegun = "*"
model-mommy = {git = "https://github.com/auto-mat/model_mommy.git", rev = "issue-377"}
nose-exclude = "*"
nose-parameterized = "*"
nose-timer = "*"
pudb = "*"
````

````
$ poetry lock
Updating dependencies
Resolving dependencies... (0.0s)

[InvalidRequirement]
Invalid requirement, parse error at "'prace na'"
````

**Comment by dimbleby** [comment]
Seems to be fixed on recent code

**Comment by abn** [comment]
Thanks @dimbleby. Closing for now. 

Please let us know if this is still an issue with the code on master.
