### ISSUE TITLE
`poetry new -h` results in TypeError

### ISSUE THREAD

**Issue by pscosta5** [python-poetry/poetry#1974]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.4
- **Poetry version**: 1.0.3

## Issue

```zsh
❯ poetry new -h

[TypeError]
catching classes that do not inherit from BaseException is not allowed

Traceback (most recent call last):
  File "/Users/pcosta/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 123, in run
    io = io_factory(
  File "/Users/pcosta/.poetry/lib/poetry/console/config/application_config.py", line 165, in create_io
    resolved_command = application.resolve_command(args)
  File "/Users/pcosta/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 104, in resolve_command
    self._dispatcher.dispatch(PRE_RESOLVE, event)
  File "/Users/pcosta/.poetry/lib/poetry/_vendor/py3.8/clikit/api/event/event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/Users/pcosta/.poetry/lib/poetry/_vendor/py3.8/clikit/api/event/event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "/Users/pcosta/.poetry/lib/poetry/console/config/application_config.py", line 107, in resolve_help_command
    except CliKitException:
```

**Comment by pscosta5** [comment]
Same for `poetry add -h`

**Comment by finswimmer** [comment]
Hello @pscosta5 ,

thanks a lot for reporting! 

The problem is on clikit's side and must be fixed there. I've opened an [issue](https://github.com/sdispater/clikit/issues/13).

fin swimmer

**Comment by pscosta5** [comment]
Thanks for moving the issue to its appropriate home!
