### ISSUE TITLE
Running `poetry add --help` raises exception

### ISSUE THREAD

**Issue by shangxiao** [python-poetry/poetry#1987]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.3 Catalina
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: Didn't have one yet…

## Issue

```
$ poetry add -vvv --help

[TypeError]
catching classes that do not inherit from BaseException is not allowed

Traceback (most recent call last):
  File "/Users/someuser/.poetry/lib/poetry/_vendor/py3.6/clikit/console_application.py", line 124, in run
    self, args, input_stream, output_stream, error_stream
  File "/Users/someuser/.poetry/lib/poetry/console/config/application_config.py", line 165, in create_io
    resolved_command = application.resolve_command(args)
  File "/Users/someuser/.poetry/lib/poetry/_vendor/py3.6/clikit/console_application.py", line 104, in resolve_command
    self._dispatcher.dispatch(PRE_RESOLVE, event)
  File "/Users/someuser/.poetry/lib/poetry/_vendor/py3.6/clikit/api/event/event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/Users/someuser/.poetry/lib/poetry/_vendor/py3.6/clikit/api/event/event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "/Users/someuser/.poetry/lib/poetry/console/config/application_config.py", line 107, in resolve_help_command
    except CliKitException:
```

**Comment by finswimmer** [comment]
Hello @shangxiao,

thanks for reporting. However, this was already reported in https://github.com/python-poetry/poetry/issues/1974 and must be fixed on CliKit's side.

fin swimmer
