### ISSUE TITLE
Unhandled ValueError thrown for very narrow terminals

### ISSUE THREAD

**Issue by dgilman** [python-poetry/poetry#2025]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

```
21:59.david@lappy:~$ poetry -vvv
Poetry version
1.0.3

USAGE
  poetry [-h] [-q]
         [-v [<...>]]
         [-V] [--ansi]
         [--no-ansi] [-n]
         <command>
         [<arg1>] ...
         [<argN>]

ARGUMENTS

[ValueError]
invalid width 0 (must be > 0)

Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/clikit/handler/help/help_text_handler.py", line 29, in handle
    usage.render(io)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/clikit/ui/help/abstract_help.py", line 31, in render
    layout.render(io, indentation)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/clikit/ui/layout/block_layout.py", line 42, in render
    element.render(io, self._indentations[i] + indentation)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/clikit/ui/components/labeled_paragraph.py", line 60, in render
    "\n".join(textwrap.wrap(self._text, text_width)),
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 379, in wrap
    return w.wrap(text)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 354, in wrap
    return self._wrap_chunks(chunks)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/textwrap.py", line 248, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
```

- **OS version and name**: MacOS 10.13
- **Poetry version**: 1.0.3

## Issue
A very minor issue, but I reproduced the issue in https://github.com/python-poetry/poetry/issues/1864 by running poetry in a terminal that's only 26 columns wide.  If you narrow it further the "invalid width 0" exception string becomes negative.

**Comment by dimbleby** [comment]
Does not reproduce on recent code. 

(Lots of change in CLI handling since this was raised eg most of the stack above is in clikit which isn't a dependency any more)
