### ISSUE TITLE
Empty requirement throws debug exception

### ISSUE THREAD

**Issue by willronchetti** [python-poetry/poetry#2071]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX Mojave 10.14.6
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/willronchetti/19e70f4d8a20b6e0f4fd5e9b16de6d1a

## Issue

If you specify an empty dependency, such as:
`flake8 = ""`

Multiple poetry commands (at least install, lock, update) run in debug mode (at least -vv) will throw an exception, example traceback is below. The issue is when there is a blank dependency 'm' in provider.py:debug is None, thus the exception when trying to access `m.group(1)`. AFAIK such a dependency specification is not disallowed. If I missed that feel free to close, but poetry seems to accept it.
```
(snovault) TecRef-LT-F9A480:snovault willronchetti$ poetry lock -vv
Using virtualenv: /Users/willronchetti/.virtualenvs/snovault
Updating dependencies
Resolving dependencies...
   1: fact: dcicsnovault is 2.0.0b3
   1: derived: dcicsnovault
   0: Duplicate dependencies for coverage
   0: Duplicate dependencies for flaky
   0: Merging requirements for flaky (3.6.1)
   0: Duplicate dependencies for pytest
   0: Duplicate dependencies for pytest-cov
   0: Merging requirements for pytest-cov (2.2.1)
   0: Duplicate dependencies for pytest-mock
   0: Duplicate dependencies for pytest-runner
   1: fact: dcicsnovault depends on aws-requests-auth (^0.4.1)
   1: fact: dcicsnovault depends on awscli (^1.15.42)
   1: fact: dcicsnovault depends on bcrypt (3.1.0)
   1: fact: dcicsnovault depends on beautifulsoup4 (4.4.1)
   1: fact: dcicsnovault depends on boto3 (^1.7.42)
   1: fact: dcicsnovault depends on botocore (^1.10.42)
   1: fact: dcicsnovault depends on certifi (2018.11.29)
   1: fact: dcicsnovault depends on cffi (1.7.0)
   1: fact: dcicsnovault depends on chardet (3.0.4)
   1: fact: dcicsnovault depends on colorama (0.3.7)
   1: fact: dcicsnovault depends on coverage (4.1)
   1: Version solving took 0.050 seconds.
   1: Tried 1 solutions.

[AttributeError]
'NoneType' object has no attribute 'group'

Traceback (most recent call last):
  File "/Users/willronchetti/.poetry/lib/poetry/_vendor/py3.6/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/willronchetti/.poetry/lib/poetry/_vendor/py3.6/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/willronchetti/.poetry/lib/poetry/_vendor/py3.6/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/willronchetti/.poetry/lib/poetry/_vendor/py3.6/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/willronchetti/.poetry/lib/poetry/console/commands/lock.py", line 28, in handle
    return installer.run()
  File "/Users/willronchetti/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/Users/willronchetti/.poetry/lib/poetry/installation/installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "/Users/willronchetti/.poetry/lib/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/Users/willronchetti/.poetry/lib/poetry/puzzle/solver.py", line 181, in _solve
    self._package, self._provider, locked=locked, use_latest=use_latest
  File "/Users/willronchetti/.poetry/lib/poetry/mixology/__init__.py", line 7, in resolve_version
    return solver.solve()
  File "/Users/willronchetti/.poetry/lib/poetry/mixology/version_solver.py", line 80, in solve
    next = self._choose_package_version()
  File "/Users/willronchetti/.poetry/lib/poetry/mixology/version_solver.py", line 382, in _choose_package_version
    self._add_incompatibility(incompatibility)
  File "/Users/willronchetti/.poetry/lib/poetry/mixology/version_solver.py", line 421, in _add_incompatibility
    self._log('fact: {}'.format(incompatibility))
  File "/Users/willronchetti/.poetry/lib/poetry/mixology/version_solver.py", line 446, in _log
    self._provider.debug(text, self._solution.attempted_solutions)
  File "/Users/willronchetti/.poetry/lib/poetry/puzzle/provider.py", line 707, in debug
    m2 = re.match('(.+?) \((.+?)\)'", m.group(1))
```

To reproduce:

1. Create clean virtualenv
2. Try running commands with at least -vv with the below `pyproject.toml` (or create one yourself)

```
[tool.poetry]
name = "poetry_test"
version = "0.1.0"
description = ""
authors = ["Someone <someone@someone.com>"]

[tool.poetry.dependencies]
python = "^3.6"
flake8 = ""

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

**Comment by gabegma** [comment]
I have the same traceback error, but I don't have any empty dependencies. I've been struggling with a bug, and I cannot debug because of this.

**Comment by dimbleby** [comment]
code today has a branch detecting the non-match - thanks to mypy - and raises an explicit error:
```
  ValueError

  Unable to parse fact: fact: test depends on flake8 ()
```
