### ISSUE TITLE
Could not find a matching version of package from private registry with traceback

### ISSUE THREAD

**Issue by bsitruk** [python-poetry/poetry#2084]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18
- **Poetry version**: 1.0.3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/bsitruk/e0fd90d239a5b231cfd90b42eac7f982

## Issue
Hi,
I've published a package on a private repository using poetry.
Everything went well, and I'm able to install it using pip like so:

`pip install my-package --index-url=https://pypi.python.org/simple --extra-index-url=http://artifactory-dev.com:8081/artifactory/api/pypi/Python/simple --trusted-host=artifactory-dev.com  --trusted-host=pypi.python.org --trusted-host=pypi.org --trusted-host=files.pythonhosted.org`

But when trying to install with poetry: `poetry add -vvv my-package`
I get the following error:

```
Using virtualenv: /home/user/.pyenv/versions/3.8.0/envs/test-env
PyPI: No packages found for my-package *
mypypi: 0 packages found for my-package *

[ValueError]
Could not find a matching version of package my-package

Traceback (most recent call last):
  File "/home/user/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/user/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/user/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/user/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/user/.poetry/lib/poetry/console/commands/add.py", line 88, in handle
    requirements = self._determine_requirements(
  File "/home/user/.poetry/lib/poetry/console/commands/init.py", line 302, in _determine_requirements
    name, version = self._find_best_version_for_package(
  File "/home/user/.poetry/lib/poetry/console/commands/init.py", line 338, in _find_best_version_for_package
    raise ValueError(
```

Any idea how to fix it ?

Thanks !

**Comment by bsitruk** [comment]
Sorry, it was just a sneaky typo in the repository name...
