### ISSUE TITLE
source repository broken in poetry 1.0.4

### ISSUE THREAD

**Issue by mbelang** [python-poetry/poetry#2110]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ArchLinux
- **Poetry version**: 1.0.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:

all you need to reproduce is to add this section
```
[[tool.poetry.source]]
name = "xxxxxx"
url = "https://xxxxxx.invalid"
```

## Issue
I just updated to poetry 1.0.4 and source repositories specified in pyproject.toml doesn't work anymore. It seems related to that issue: https://github.com/sdispater/tomlkit/issues/80

Reverting to 1.0.3 is working just fine.

here is the exception:

```  
- Installing blahblah (0.7.13)

[ValueError]
Repository "xxxxxx" does not exist.

Traceback (most recent call last):
  File "/home/mbelanger/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/mbelanger/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/mbelanger/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/mbelanger/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/mbelanger/.poetry/lib/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/home/mbelanger/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/home/mbelanger/.poetry/lib/poetry/installation/installer.py", line 286, in _do_install
    self._execute(op)
  File "/home/mbelanger/.poetry/lib/poetry/installation/installer.py", line 302, in _execute
    getattr(self, '_execute_{}'.format(method))(operation)
  File "/home/mbelanger/.poetry/lib/poetry/installation/installer.py", line 327, in _execute_install
    self._installer.install(operation.package)
  File "/home/mbelanger/.poetry/lib/poetry/installation/pip_installer.py", line 47, in install
    repository = self._pool.repository(package.source_reference)
  File "/home/mbelanger/.poetry/lib/poetry/repositories/pool.py", line 40, in repository
    raise ValueError('Repository "{}" does not exist.'.format(name))
```

**Comment by mbelang** [comment]
@sdispater this one is really blocking us as poetry is bundled in circleci images now and they way the install is preventing us revert to 1.0.3 :grimacing:

**Comment by timothyjlaurent** [comment]
This is related to #2109

**Comment by timothyjlaurent** [comment]
I see that if I use get_poetry.py to install, this problem can be fixed by installing 1.0.3, but if installing with pip then it is broken for 1.0.1, 1.0.2, 1.0.3, and 1.0.4.

**Comment by mbelang** [comment]
Yes I also noticed that. I can workaround by installing toolkit==0.5.8 with pip if poetry is installed with pip.

**Comment by mbelang** [comment]
So this issue is a duplicate of #2010. When I decided to open I totally missed yours.

**Comment by mbelang** [comment]
I just did a test. It is because pip and poetry doesn't manage dependencies the same way.

in a clean virtualenv I did `pip install poetry==1.0.3`

the result of `pip list` after:

```
Package            Version   
------------------ ----------
attrs              19.3.0    
CacheControl       0.12.6    
cachy              0.3.0     
certifi            2019.11.28
cffi               1.14.0    
chardet            3.0.4     
cleo               0.7.6     
clikit             0.4.2     
cryptography       2.8       
html5lib           1.0.1     
idna               2.9       
importlib-metadata 1.1.3     
jeepney            0.4.2     
jsonschema         3.2.0     
keyring            20.0.1    
lockfile           0.12.2    
msgpack            1.0.0     
pastel             0.2.0     
pexpect            4.8.0     
pip                20.0.2    
pkginfo            1.5.0.1   
poetry             1.0.3     
ptyprocess         0.6.0     
pycparser          2.19      
pylev              1.3.0     
pyparsing          2.4.6     
pyrsistent         0.14.11   
requests           2.23.0    
requests-toolbelt  0.8.0     
SecretStorage      3.1.2     
setuptools         45.2.0    
shellingham        1.3.2     
six                1.14.0    
tomlkit            0.5.10    
urllib3            1.25.8    
webencodings       0.5.1     
wheel              0.34.2    
zipp               3.0.0 
```

same with poetry 1.0.1 and 1.0.2.
The problem is tomlkit 0.5.10

**Comment by mbelang** [comment]
@timothyjlaurent and @sdispater implemented a fix here: https://github.com/sdispater/tomlkit/pull/81

Please take a look a it :)

**Comment by mbelang** [comment]
Thanks for the quick fix @sdispater :)
