### ISSUE TITLE
The "--requirements" option does not exist.

### ISSUE THREAD

**Issue by leileigong** [python-poetry/poetry#2135]
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## `poetry add --requirements requirements.txt`  rasise an error

comand ` poetry add --requirements requirements.txt` got an error:
```
PS E:\GisManager> poetry add --requirements requirements.txt

[NoSuchOptionException]
The "--requirements" option does not exist.

Traceback (most recent call last):
  File "c:\python36\lib\site-packages\clikit\console_application.py", line 124, in run
    self, args, input_stream, output_stream, error_stream
  File "c:\python36\lib\site-packages\poetry\console\config\application_config.py", line 165, in create_io
    resolved_command = application.resolve_command(args)
  File "c:\python36\lib\site-packages\clikit\console_application.py", line 110, in resolve_command
    return self._config.command_resolver.resolve(args, self)
  File "c:\python36\lib\site-packages\clikit\resolver\default_resolver.py", line 34, in resolve
    return self.create_resolved_command(result)
  File "c:\python36\lib\site-packages\clikit\resolver\default_resolver.py", line 166, in create_resolved_command
    if not result.is_parsable():
  File "c:\python36\lib\site-packages\clikit\resolver\resolve_result.py", line 43, in is_parsable
    self._parse()
  File "c:\python36\lib\site-packages\clikit\resolver\resolve_result.py", line 49, in _parse
    self._parsed_args = self._command.parse(self._raw_args)
  File "c:\python36\lib\site-packages\clikit\api\command\command.py", line 113, in parse
    return self._config.args_parser.parse(args, self._args_format, lenient)
  File "c:\python36\lib\site-packages\clikit\args\default_args_parser.py", line 53, in parse
    self._parse(args, _fmt, lenient)
  File "c:\python36\lib\site-packages\clikit\args\default_args_parser.py", line 101, in _parse
    self._parse_long_option(token, tokens, fmt, lenient)
  File "c:\python36\lib\site-packages\clikit\args\default_args_parser.py", line 247, in _parse_long_option
    self._add_long_option(name, None, tokens, fmt, lenient)
  File "c:\python36\lib\site-packages\clikit\args\default_args_parser.py", line 300, in _add_long_option
    raise NoSuchOptionException(name)

PS E:\GisManager>
```

**Comment by finswimmer** [comment]
Hello @leileigong,

as the output says:

> The "--requirements" option does not exist.

poetry doesn't support such an option.

fin swimmer

**Comment by leileigong** [comment]
the issue #663 show that, i can use this option.I just wanna  know how to import an `requirements.txt`

**Comment by finswimmer** [comment]
Hello again,

in #633 there was just a suggestion to add such an option. @absassi [mentioned](https://github.com/python-poetry/poetry/issues/663#issuecomment-508792730) why this doesn't make sense in most cases.

The thread includes some one-liner how one can achieve this if really needed. You can also give [dephell](https://github.com/dephell/dephell) a try.

fin swimmer
