### ISSUE TITLE
install poetry got an error on Raspberry.

### ISSUE THREAD

**Issue by leileigong** [python-poetry/poetry#2136]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 
- **Poetry version**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Raspberry install poetry got an error.

Here is my arch:
```sh
pi@raspberrypi:~$ uname -a
Linux raspberrypi 4.9.35-v7+ #1014 SMP Fri Jun 30 14:47:43 BST 2017 armv7l GNU/Linux
```

Here is my python version:
```sh
pi@raspberrypi:~$ python3
Python 3.5.3 (default, Jan 19 2017, 14:11:04) 
[GCC 6.3.0 20170124] on linux
```

```
pi@raspberrypi:~/FNTools$ pip3 install poetry
Downloading/unpacking poetry
  Downloading poetry-1.0.5-py2.py3-none-any.whl (220kB): 220kB downloaded
Downloading/unpacking pexpect<5.0.0,>=4.7.0 (from poetry)
  Downloading pexpect-4.8.0-py2.py3-none-any.whl (59kB): 59kB downloaded
Downloading/unpacking shellingham<2.0,>=1.1 (from poetry)
  Downloading shellingham-1.3.2-py2.py3-none-any.whl
Downloading/unpacking pyrsistent<0.15.0,>=0.14.2 (from poetry)
  Downloading pyrsistent-0.14.11.tar.gz (104kB): 104kB downloaded
  Running setup.py (path:/tmp/pip-build-c_0o1wtv/pyrsistent/setup.py) egg_info for package pyrsistent
Downloading/unpacking clikit<0.5.0,>=0.4.2 (from poetry)
  Downloading clikit-0.4.2-py2.py3-none-any.whl (88kB): 88kB downloaded
Downloading/unpacking tomlkit<0.6.0,>=0.5.11 (from poetry)
  Downloading tomlkit-0.5.11-py2.py3-none-any.whl
Downloading/unpacking jsonschema<4.0,>=3.1 (from poetry)
  Downloading jsonschema-3.2.0-py2.py3-none-any.whl (56kB): 56kB downloaded
Downloading/unpacking cachecontrol[filecache]<0.13.0,>=0.12.4 (from poetry)
  Downloading CacheControl-0.12.6-py2.py3-none-any.whl
Downloading/unpacking keyring<21.0.0,>=20.0.1; python_version >= "3.5" and python_version < "4.0" (from poetry)
  Downloading keyring-20.0.1-py2.py3-none-any.whl
Downloading/unpacking requests-toolbelt<0.9.0,>=0.8.0 (from poetry)
  Downloading requests_toolbelt-0.8.0-py2.py3-none-any.whl (54kB): 54kB downloaded
Downloading/unpacking pyparsing<3.0,>=2.2 (from poetry)
  Downloading pyparsing-2.4.6-py2.py3-none-any.whl (67kB): 67kB downloaded
Downloading/unpacking pkginfo<2.0,>=1.4 (from poetry)
  Downloading pkginfo-1.5.0.1-py2.py3-none-any.whl
Downloading/unpacking cachy<0.4.0,>=0.3.0 (from poetry)
  Downloading cachy-0.3.0-py2.py3-none-any.whl
Downloading/unpacking requests<3.0,>=2.18 (from poetry)
  Downloading requests-2.23.0-py2.py3-none-any.whl (58kB): 58kB downloaded
Downloading/unpacking html5lib<2.0,>=1.0 (from poetry)
  Downloading html5lib-1.0.1-py2.py3-none-any.whl (117kB): 117kB downloaded
Downloading/unpacking cleo<0.8.0,>=0.7.6 (from poetry)
  Downloading cleo-0.7.6-py2.py3-none-any.whl
Downloading/unpacking importlib-metadata<1.2.0,>=1.1.3; python_version < "3.8" (from poetry)
  Downloading importlib_metadata-1.1.3-py2.py3-none-any.whl
Downloading/unpacking ptyprocess>=0.5 (from pexpect<5.0.0,>=4.7.0->poetry)
  Downloading ptyprocess-0.6.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python3/dist-packages (from pyrsistent<0.15.0,>=0.14.2->poetry)
Downloading/unpacking typing-extensions<4.0,>=3.6; python_version >= "3.5.0" and python_version < "3.5.4" (from clikit<0.5.0,>=0.4.2->poetry)
  Downloading typing_extensions-3.7.4.1-py3-none-any.whl
Downloading/unpacking pylev<2.0,>=1.3 (from clikit<0.5.0,>=0.4.2->poetry)
  Downloading pylev-1.3.0-py2.py3-none-any.whl
Downloading/unpacking pastel<0.3.0,>=0.2.0 (from clikit<0.5.0,>=0.4.2->poetry)
  Downloading pastel-0.2.0-py2.py3-none-any.whl
Requirement already satisfied (use --upgrade to upgrade): setuptools in /usr/lib/python3/dist-packages (from jsonschema<4.0,>=3.1->poetry)
Downloading/unpacking attrs>=17.4.0 (from jsonschema<4.0,>=3.1->poetry)
  Downloading attrs-19.3.0-py2.py3-none-any.whl
Downloading/unpacking msgpack>=0.5.2 (from cachecontrol[filecache]<0.13.0,>=0.12.4->poetry)
  Downloading msgpack-1.0.0.tar.gz (232kB): 232kB downloaded
  Running setup.py (path:/tmp/pip-build-c_0o1wtv/msgpack/setup.py) egg_info for package msgpack
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python3/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python3/dist-packages/pip/req.py", line 1091, in prepare_files
    req_to_install.check_if_exists()
  File "/usr/lib/python3/dist-packages/pip/req.py", line 811, in check_if_exists
    self.satisfied_by = pkg_resources.get_distribution(self.req)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 553, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 427, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
IndexError: list index out of range

Storing debug log for failure in /home/pi/.pip/pip.log

```

**Comment by leileigong** [comment]
i try to install msgpack singly, installation success.
```sh
pi@raspberrypi:~$ sudo pip3 install msgpack
Downloading/unpacking msgpack
  Downloading msgpack-1.0.0.tar.gz (232kB): 232kB downloaded
  Running setup.py (path:/tmp/pip-build-gcqq8djf/msgpack/setup.py) egg_info for package msgpack
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
Installing collected packages: msgpack
  Running setup.py install for msgpack
    building 'msgpack._cmsgpack' extension
    arm-linux-gnueabihf-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fdebug-prefix-map=/build/python3.5-RUbMX3/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -D__LITTLE_ENDIAN__=1 -I. -I/usr/include/python3.5m -c msgpack/_cmsgpack.cpp -o build/temp.linux-armv7l-3.5/msgpack/_cmsgpack.o
    cc1plus: warning: command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
    In file included from msgpack/_cmsgpack.cpp:618:0:
    msgpack/unpack.h: In function ‘int unpack_callback_array(unpack_user*, unsigned int, PyObject**)’:
    msgpack/unpack.h:141:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (n > u->max_array_len) {
             ~~^~~~~~~~~~~~~~~~~~
    In file included from msgpack/_cmsgpack.cpp:618:0:
    msgpack/unpack.h: In function ‘int unpack_callback_map(unpack_user*, unsigned int, PyObject**)’:
    msgpack/unpack.h:176:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (n > u->max_map_len) {
             ~~^~~~~~~~~~~~~~~~
    msgpack/unpack.h: In function ‘int unpack_callback_raw(unpack_user*, const char*, const char*, unsigned int, PyObject**)’:
    msgpack/unpack.h:234:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (l > u->max_str_len) {
             ~~^~~~~~~~~~~~~~~~
    msgpack/unpack.h: In function ‘int unpack_callback_bin(unpack_user*, const char*, const char*, unsigned int, PyObject**)’:
    msgpack/unpack.h:254:11: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (l > u->max_bin_len) {
             ~~^~~~~~~~~~~~~~~~
    In file included from msgpack/_cmsgpack.cpp:618:0:
    msgpack/unpack.h: In function ‘int unpack_callback_ext(unpack_user*, const char*, const char*, unsigned int, PyObject**)’:
    msgpack/unpack.h:308:18: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
         if (length-1 > u->max_ext_len) {
             ~~~~~~~~~^~~~~~~~~~~~~~~~
    msgpack/_cmsgpack.cpp: In function ‘int __pyx_f_7msgpack_9_cmsgpack_6Packer__pack(__pyx_obj_7msgpack_9_cmsgpack_Packer*, PyObject*, __pyx_opt_args_7msgpack_9_cmsgpack_6Packer__pack*)’:
    msgpack/_cmsgpack.cpp:4461:10: warning: ‘__pyx_r’ may be used uninitialized in this function [-Wmaybe-uninitialized]
       return __pyx_r;
              ^~~~~~~
    arm-linux-gnueabihf-g++ -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,relro -g -fdebug-prefix-map=/build/python3.5-RUbMX3/python3.5-3.5.3=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 build/temp.linux-armv7l-3.5/msgpack/_cmsgpack.o -o build/lib.linux-armv7l-3.5/msgpack/_cmsgpack.cpython-35m-arm-linux-gnueabihf.so
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)
    /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'long_description_content_type'
      warnings.warn(msg)
  Could not find .egg-info directory in install record for msgpack
Successfully installed msgpack
Cleaning up...

```

**Comment by andreevdanil** [comment]
You can try to install poetry throw `curl`.

**Comment by mkniewallner** [comment]
I know this issue is quite old, but do you still have troubles installing Poetry?
Otherwise, should this issue be closed?

**Comment by mkniewallner** [comment]
Closing, since this issue is quite old and probably not relevant anymore. Feel free to reopen if you still encounter issues.
