### ISSUE TITLE
Poetry install does not work as expected

### ISSUE THREAD

**Issue by rgreinho** [python-poetry/poetry#2140]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

```
$ poetry debug info

Poetry
Version: 1.0.5
Python:  3.7.6

Virtualenv
Python:         3.7.6
Implementation: CPython
Path:           /private/tmp/bugreport/.venv
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7
```

## Issue

It looks like `poetry install` does not install the packages properly. For example if I install `black` with poetry I cannot use it from the venv, and I have to re-install it using pip. Bellow are the repro steps.

Create a new project:
```bash
cd /tmp
poetry new bugreport
cd bugreport
poetry config virtualenvs.in-project true --local
```
The install `black`:

```bash
$ poetry add black --dev
Creating virtualenv bugreport in /private/tmp/bugreport/.venv
Using version ^19.10b0 for black

Updating dependencies
Resolving dependencies... (1.0s)

Writing lock file


Package operations: 12 installs, 6 updates, 0 removals

  - Updating zipp (1.2.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 3.1.0)
  - Updating importlib-metadata (1.1.3 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 1.5.0)
  - Updating pyparsing (2.4.6 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 2.4.6)
  - Updating six (1.14.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 1.14.0)
  - Installing appdirs (1.4.3)
  - Updating attrs (19.3.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 19.3.0)
  - Installing click (7.0)
  - Updating more-itertools (8.2.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 8.2.0)
  - Installing packaging (20.3)
  - Installing pathspec (0.7.0)
  - Installing pluggy (0.13.1)
  - Installing py (1.8.1)
  - Installing regex (2020.2.20)
  - Installing toml (0.10.0)
  - Installing typed-ast (1.4.1)
  - Installing wcwidth (0.1.8)
  - Installing black (19.10b0)
  - Installing pytest (5.3.5)
```
This seems fine but if I activative the venv and run black it fails

```bash
source .venv/bin/activate
black bugreport
```
Output:

```python
Traceback (most recent call last):
  File "/private/tmp/bugreport/.venv/bin/black", line 6, in <module>
    from black import patched_main
  File "/private/tmp/bugreport/.venv/lib/python3.7/site-packages/black.py", line 42, in <module>
    from attr import dataclass, evolve, Factory
ModuleNotFoundError: No module named 'attr'
```

Workaround:
```bash
pip install -r <(poetry export -f requirements.txt --dev)
```

Then `black` works:
```bash
$ black bugreport
reformatted bugreport/__init__.py
All done! ✨ 🍰 ✨
1 file reformatted.
```

Also no matter how many times I run the `poetry install` command, it keeps on trying to update packages:

```bash
$ poetry install
Installing dependencies from lock file


Package operations: 0 installs, 18 updates, 0 removals

  - Updating zipp (1.2.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 3.1.0)
  - Updating importlib-metadata (1.1.3 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 1.5.0)
  - Updating pyparsing (2.4.6 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 2.4.6)
  - Updating six (1.14.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 1.14.0)
  - Updating appdirs (1.4.3 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 1.4.3)
  - Updating attrs (19.3.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 19.3.0)
  - Updating click (7.0 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 7.0)
  - Updating more-itertools (8.2.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 8.2.0)
  - Updating packaging (20.3 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 20.3)
  - Updating pathspec (0.7.0 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 0.7.0)
  - Updating pluggy (0.13.1 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 0.13.1)
  - Updating py (1.8.1 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 1.8.1)
  - Updating regex (2020.2.20 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 2020.2.20)
  - Updating toml (0.10.0 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 0.10.0)
  - Updating typed-ast (1.4.1 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 1.4.1)
  - Updating wcwidth (0.1.8 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 0.1.8)
  - Updating black (19.10b0 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 19.10b0)
  - Updating pytest (5.3.5 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 5.3.5)
  - Installing bugreport (0.1.0)
$ poetry install
Installing dependencies from lock file


Package operations: 0 installs, 18 updates, 0 removals

  - Updating zipp (1.2.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 3.1.0)
  - Updating importlib-metadata (1.1.3 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 1.5.0)
  - Updating pyparsing (2.4.6 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 2.4.6)
  - Updating six (1.14.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 1.14.0)
  - Updating appdirs (1.4.3 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 1.4.3)
  - Updating attrs (19.3.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 19.3.0)
  - Updating click (7.0 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 7.0)
  - Updating more-itertools (8.2.0 /usr/local/Cellar/poetry/1.0.5/libexec/vendor/lib/python3.7/site-packages -> 8.2.0)
  - Updating packaging (20.3 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 20.3)
  - Updating pathspec (0.7.0 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 0.7.0)
  - Updating pluggy (0.13.1 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 0.13.1)
  - Updating py (1.8.1 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 1.8.1)
  - Updating regex (2020.2.20 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 2020.2.20)
  - Updating toml (0.10.0 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 0.10.0)
  - Updating typed-ast (1.4.1 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 1.4.1)
  - Updating wcwidth (0.1.8 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 0.1.8)
  - Updating black (19.10b0 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 19.10b0)
  - Updating pytest (5.3.5 /private/tmp/bugreport/.venv/lib/python3.7/site-packages -> 5.3.5)
  - Installing bugreport (0.1.0)
```

To finish, it might be worth noting that if I run `poetry run black bugreport` if works fine.

**Comment by finswimmer** [comment]
Hello @rgreinho,

unfortunately I'm not able to reproduce your problem. But your output looks a bit strange. Some packages are installed/update in `/usr/local/Cellar/poetry` (those are the ones needed by poetry itself) and some get installed in the `.venv` folder.

How have you installed poetry?

fin swimmer

**Comment by rgreinho** [comment]
I installed it with `brew`.

```bash
$ brew info poetry
poetry: stable 1.0.5 (bottled)
Python package management tool
https://python-poetry.org/
/usr/local/Cellar/poetry/1.0.5_1 (1,162 files, 8.6MB) *
  Poured from bottle on 2020-03-06 at 10:23:52
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/poetry.rb
==> Dependencies
Required: python ✔
==> Analytics
install: 1,001 (30 days), 1,868 (90 days), 1,955 (365 days)
install-on-request: 998 (30 days), 1,864 (90 days), 1,951 (365 days)
build-error: 0 (30 days)
```

Re-installing the formula solved the problem though. Thank you for pointing the potential  installation problem.

**Comment by Mastermind-U** [comment]
I've met the same issue but with docker, googling over stackoverflow solved it:
```Dockerfile
RUN poetry config virtualenvs.create false && poetry install --no-interaction --no-ansi
```
