### ISSUE TITLE
No module named 'html5lib'

### ISSUE THREAD

**Issue by kakulukia** [python-poetry/poetry#2142]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: OSX 10.14
- **Poetry version**: 1.0.5

## Issue
I have `weasyprint` as a project requirement and happend to uninstall it with `poetry remove weasyprint` where poetry ended up deleting those dependencies:

```
Package operations: 0 installs, 0 updates, 8 removals

  - Removing cairocffi (1.1.0)
  - Removing cairosvg (2.4.2)
  - Removing cssselect2 (0.2.2)
  - Removing html5lib (1.0.1)
  - Removing pyphen (0.9.5)
  - Removing tinycss2 (1.0.2)
  - Removing weasyprint (51)
  - Removing webencodings (0.5.1)
```

I dont actually need `html5lib` so this seems fine, but after this step poetry is broken, because it actually needs that lib.

```
poetry --version
Traceback (most recent call last):
  File "/Users/andy/projects/schichtsalat/.venv/bin/poetry", line 6, in <module>
    from poetry.console import main
  File "/Users/andy/projects/schichtsalat/.venv/lib/python3.7/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/andy/projects/schichtsalat/.venv/lib/python3.7/site-packages/poetry/console/application.py", line 5, in <module>
    from .commands.about import AboutCommand
  File "/Users/andy/projects/schichtsalat/.venv/lib/python3.7/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/Users/andy/projects/schichtsalat/.venv/lib/python3.7/site-packages/poetry/console/commands/check.py", line 1, in <module>
    from poetry.factory import Factory
  File "/Users/andy/projects/schichtsalat/.venv/lib/python3.7/site-packages/poetry/factory.py", line 21, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/Users/andy/projects/schichtsalat/.venv/lib/python3.7/site-packages/poetry/repositories/pypi_repository.py", line 13, in <module>
    from html5lib.html5parser import parse
ModuleNotFoundError: No module named 'html5lib'
```

Poetry should not uninstall `html5lib` since it breaks itself.
Reinstalling that lib with pip helps fixing poetry, tho.

**Comment by finswimmer** [comment]
Hello @kakulukia,

I'm not sure if I would call this a bug. You have installed poetry in the same venv as your project. This is not recommended.

`poetry remove` removes all packages which are not used by any of the dependencies defined in the `pyproject.toml`. If you have installed any other package in the venv without poetry, poetry will not take care if a package, it tries to remove, is needed by these packages.

What you **should** do is to install poetry global as recommended in the [docs](https://python-poetry.org/docs/).

What you _can_ do as a work around is to add poetry itself to the dependency section of the `pyproject.toml`.

fin swimmer

**Comment by kakulukia** [comment]
OH, i actually have poetry installed globally, but you are right it somehow ended up also being installed in the venv. Removing the local version solved the issue.

Thx!
