### ISSUE TITLE
SolverProblem in Docker

### ISSUE THREAD

**Issue by thoward27** [python-poetry/poetry#2160]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Docker: python:3.8.0**: 
- **Poetry version: 1.0.5**: 
- **Link to [Github](https://github.com/thoward27/grade/blob/feature/pyproject/pyproject.toml) with the contents of your pyproject.toml file**: 

## Issue

Alright, I think I must be missing something here. I have a Dockerfile that starts from python:3.8.0, I install `poetry`, then try to run `poetry install` and get a `SovlerProblemError`

Traceback:
```
[SolverProblemError]
The current project's Python requirement (2.7.16) is not compatible with some of the required packages Python requirement:
  - black requires Python >=3.6

Because black (19.10b0) requires Python >=3.6
 and no versions of black match >19.10b0,<20.0, black is forbidden.
So, because grade depends on black (^19.10b0), version solving failed.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/lib/python3.8/site-packages/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/usr/local/lib/python3.8/site-packages/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/usr/local/lib/python3.8/site-packages/poetry/installation/installer.py", line 225, in _do_install
    ops = solver.solve(use_latest=whitelist)
  File "/usr/local/lib/python3.8/site-packages/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/usr/local/lib/python3.8/site-packages/poetry/puzzle/solver.py", line 190, in _solve
    raise SolverProblemError(e)
```

Dockerfile:
```
FROM python:3.8.0

# First let's just get things updated.
RUN apt-get -y update --fix-missing && apt-get -y upgrade

# Dependancies
RUN apt-get install -y \
    make \
    gcc \
    clang \
    valgrind \
    git \
    build-essential \
    software-properties-common \
    wget \
    curl

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

# Install grade
RUN mkdir /app/
COPY . /app/

# Defaults
WORKDIR /app/
RUN python -m pip install --upgrade pip \
    && python -m pip install poetry \
    && poetry config virtualenvs.create false \
    && poetry -V \
    && poetry install -vvv
```

pyproject.toml
```
[tool.poetry]
name = "grade"
version = "2.1.5"
description = "a package focused on autograding"
authors = ["Tom <info@tomhoward.codes>"]
license = "AGPL-3.0"
packages = [
    { include = "grade" }
]

[tool.poetry.dependencies]
python = "^3.6"
click = "^7.0"

[tool.poetry.dev-dependencies]
Sphinx = "^2.4.1"
coverage = "^5.0.3"
black = "^19.10b0"
python-semantic-release = "^4.10.0"
toml = "^0.10.0"

[tool.semantic_release]
version_variable = "pyproject.toml:version"
commit_message = "build: version bump to v${version}"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api
```

**Comment by andreevdanil** [comment]
Hi, can you attach `pyproject.toml`? Also you should try to add `poetry env use 3.8` in your Dockerfile.

**Comment by thoward27** [comment]
New Dockerfile:
```
FROM python:3.8.0

# First let's just get things updated.
RUN apt-get -y update --fix-missing && apt-get -y upgrade

# Dependancies
RUN apt-get install -y \
    make \
    gcc \
    clang \
    valgrind \
    git \
    build-essential \
    software-properties-common \
    wget \
    curl

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python

# Install grade
RUN mkdir /app/
COPY . /app/

# Defaults
WORKDIR /app/
RUN python -m pip install --upgrade --quiet pip 
RUN python -m pip install --quiet poetry
RUN poetry env use 3.8 
RUN poetry install -vvv
CMD ["python", "-m", "unittest", "discover"]
```

New output:
```
Step 10/12 : RUN poetry env use 3.8
 ---> Running in f950c039c19a
Creating virtualenv grade-9TtSrW0h-py3.8 in /root/.cache/pypoetry/virtualenvs
Using virtualenv: /app/.venv
Removing intermediate container f950c039c19a
 ---> 0764bbe156bf
Step 11/12 : RUN poetry install -vvv
 ---> Running in 6e43666b135c
Using virtualenv: /app/.venv
Installing dependencies from lock file

[SolverProblemError]
The current project's Python requirement (2.7.16) is not compatible with some of the required packages Python requirement:
  - black requires Python >=3.6

Because black (19.10b0) requires Python >=3.6
 and no versions of black match >19.10b0,<20.0, black is forbidden.
So, because grade depends on black (^19.10b0), version solving failed.

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/local/lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/local/lib/python3.8/site-packages/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/usr/local/lib/python3.8/site-packages/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/usr/local/lib/python3.8/site-packages/poetry/installation/installer.py", line 225, in _do_install
    ops = solver.solve(use_latest=whitelist)
  File "/usr/local/lib/python3.8/site-packages/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/usr/local/lib/python3.8/site-packages/poetry/puzzle/solver.py", line 190, in _solve
    raise SolverProblemError(e)
```

**Comment by jules-ch** [comment]
Couldn't reproduce, I've managed to build your Dockerfile.

You're installing poetry twice in your Dockerfile. 
If you want to install poetry using the curl command like in the documentation you need to add it to your PATH variable.

```dockerfile
FROM python:3.8.0

# First let's just get things updated.
RUN apt-get -y update --fix-missing && apt-get -y upgrade

# Dependancies
RUN apt-get install -y \
    make \
    gcc \
    clang \
    valgrind \
    git \
    build-essential \
    software-properties-common \
    wget \
    curl

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
# Adding poetry to PATH
ENV PATH="/root/.poetry/bin:$PATH"

# Install grade
RUN mkdir /app/
COPY . /app/

# Defaults
WORKDIR /app/
RUN python -m pip install --upgrade pip \
    && poetry install -vvv
``` 

Can you do your docker command again without cache : `docker build . --no-cache`

**Comment by thoward27** [comment]
Alright, so, still no progress.

```
docker system prune -a -f
docker build -t grade --no-cache .
...
Step 9/10 : RUN python -m pip install --upgrade pip     && poetry install -vvv
 ---> Running in 9438430d179f
Requirement already up-to-date: pip in /usr/local/lib/python3.8/site-packages (20.0.2)
Using virtualenv: /app/.venv
Installing dependencies from lock file

[SolverProblemError]
The current project's Python requirement (2.7.16) is not compatible with some of the required packages Python requirement:
  - black requires Python >=3.6

Because black (19.10b0) requires Python >=3.6
 and no versions of black match >19.10b0,<20.0, black is forbidden.
So, because grade depends on black (^19.10b0), version solving failed.

Traceback (most recent call last):
  File "/root/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/root/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/root/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/root/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/root/.poetry/lib/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/root/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/root/.poetry/lib/poetry/installation/installer.py", line 225, in _do_install
    ops = solver.solve(use_latest=whitelist)
  File "/root/.poetry/lib/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/root/.poetry/lib/poetry/puzzle/solver.py", line 190, in _solve
    raise SolverProblemError(e)

The command '/bin/sh -c python -m pip install --upgrade pip     && poetry install -vvv' returned a non-zero code: 1
```

Current dockerfile (attempted with `python:3.8.0` as well)
```
FROM python:3.8

# First let's just get things updated.
RUN apt-get -y update --fix-missing && apt-get -y upgrade

# Dependancies
RUN apt-get install -y \
    make \
    gcc \
    clang \
    valgrind \
    git \
    build-essential \
    software-properties-common \
    wget \
    curl

RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
# Adding poetry to PATH
ENV PATH="/root/.poetry/bin:$PATH"

# Install grade
RUN mkdir /app/
COPY . /app/

# Defaults
WORKDIR /app/
RUN python -m pip install --upgrade pip \
    && poetry install -vvv
CMD ["python", "-m", "unittest", "discover"]
```

Docker version `19.03.6-ce, build 369ce74a3c`
Operating System: Manjaro Linux (Arch-based)

**Comment by finswimmer** [comment]
```
Using virtualenv: /app/.venv
Installing dependencies from lock file
```

According to this, there is already a virtual environment and I guess in this there is python2 installed. So remove this before running `poetry install` or make sure that ths environment contain a python3.

fin swimmer

**Comment by jules-ch** [comment]
The error is weird, it seems your python version in your container is 2.7.16. Can you put a 

```dockerfile
RUN $(python --version)
```
in your dockerfile for debug.

Can you remove your poetry.lock and relock your dependencies aswell  with `poetry lock`

**Comment by jules-ch** [comment]
> ```
> Using virtualenv: /app/.venv
> Installing dependencies from lock file
> ```
> 
> 
> According to this, there is already a virtual environment and I guess in this there is python2 installed. So remove this before running `poetry install` or make sure that ths environment contain a python3.
> 
> 
> fin swimmer

Good catch

**Comment by thoward27** [comment]
@finswimmer that worked! I tried to recreate my bug for a while, it looks like something was broken in my `.venv`, which is super confusing as I cannot even find python2 on my system at all... either way, I'm good now, thanks for all the help!
