### ISSUE TITLE
poetry update: [AttributeError] 'Context' object has no attribute 'pattern'

### ISSUE THREAD

**Issue by QasimK** [python-poetry/poetry#2215]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.0.5
- **pyproject.toml file**: https://raw.githubusercontent.com/Fustra/vote4film/89beb976cfd5e9122e5ff3ca53100543667477f6/pyproject.toml

## Issue

I have a Poetry project that I started many months ago. Recently, I tried to execute `poetry update` so that I could check if all my dependencies were up-to-date, however I encountered the following error.

```
(vote4film-lFuj2EJI-py3.8) me@my-laptop ~/c/m/vote4film (master)> poetry update -vvv
Using virtualenv: /home/me/.cache/pypoetry/virtualenvs/vote4film-lFuj2EJI-py3.8

[AttributeError]
'Context' object has no attribute 'pattern'

Traceback (most recent call last):
  File "/home/me/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/me/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/me/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/me/.local/pipx/venvs/poetry/lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/me/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/console/commands/update.py", line 35, in handle
    installer = Installer(
  File "/home/me/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/installation/installer.py", line 55, in __init__
    installed = self._get_installed()
  File "/home/me/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/installation/installer.py", line 488, in _get_installed
    return InstalledRepository.load(self._env)
  File "/home/me/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/repositories/installed_repository.py", line 22, in load
    for distribution in sorted(
  File "/usr/lib/python3.8/importlib/metadata.py", line 194, in <genexpr>
    resolver(context)
  File "/home/me/.local/pipx/venvs/poetry/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 417, in find_distributions
    found = self._search_paths(context.pattern, context.path)
```

I get the same error if I try `poetry install`.

I installed & updated Poetry with pipx, this is the debug output:

```
(vote4film-lFuj2EJI-py3.8) me@my-laptop ~/c/m/vote4film (master)> poetry debug

Poetry
Version: 1.0.5
Python:  3.8.2

Virtualenv
Python:         3.8.2
Implementation: CPython
Path:           /home/me/.cache/pypoetry/virtualenvs/vote4film-lFuj2EJI-py3.8
Valid:          True

System
Platform: linux
OS:       posix
Python:   /usr
```

**Comment by tarcisioe** [comment]
@QasimK I have poetry installed with pipx as well and was having the same issue. I uninstalled poetry and reinstalled it (still with pipx) and it worked. Less than ideal, but thought I'd share.

**Comment by aeroaks** [comment]
Hi, 
Uninstall and install does not work for me.

**Comment by pcp1976** [comment]
@aeroaks try
`pip uninstall importlib_metadata` followed by `pip install poetry`.

**Comment by finswimmer** [comment]
Hello @QasimK,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
