### ISSUE TITLE
poetry fails to install if no white space is between author name and email adress

### ISSUE THREAD

**Issue by Selion05** [python-poetry/poetry#2263]
OS: Manjaro 19.0.2 Kyria
Kernel: x86_64 Linux 5.5.13-1-MANJARO
Python 3.8.2
Poetry version 1.0.5

> [AttributeError]
'NoneType' object has no attribute 'group'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/lib/python3.8/site-packages/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/usr/lib/python3.8/site-packages/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/usr/lib/python3.8/site-packages/poetry/installation/installer.py", line 286, in _do_install
    self._execute(op)
  File "/usr/lib/python3.8/site-packages/poetry/installation/installer.py", line 302, in _execute
    getattr(self, "_execute_{}".format(method))(operation)
  File "/usr/lib/python3.8/site-packages/poetry/installation/installer.py", line 327, in _execute_install
    self._installer.install(operation.package)
  File "/usr/lib/python3.8/site-packages/poetry/installation/pip_installer.py", line 32, in install
    self.install_directory(package)
  File "/usr/lib/python3.8/site-packages/poetry/installation/pip_installer.py", line 213, in install_directory
    builder = SdistBuilder(
  File "/usr/lib/python3.8/site-packages/poetry/masonry/builders/builder.py", line 71, in __init__
    self._meta = Metadata.from_package(self._package)
  File "/usr/lib/python3.8/site-packages/poetry/masonry/metadata.py", line 54, in from_package
    meta.author = package.author_name
  File "/usr/lib/python3.8/site-packages/poetry/packages/package.py", line 138, in author_name
    return self._get_author()["name"]
  File "/usr/lib/python3.8/site-packages/poetry/packages/package.py", line 166, in _get_author
    name = m.group("name")

## Issue

I have an project where I install dev dependencies by path e.g
`mylib = { path = "../../libs/mylib", develop = true }` if the authors field in `mylib` has no space between name and email  (`authors = ["name<mailgmail.com>"]`)  it fails. Adding a space  (`authors = ["name <mailgmail.com>"]`) fixes it.

**Comment by Selion05** [comment]
Sounds ok but then there should be a better error message than `'NoneType' object has no attribute 'group'`
