### ISSUE TITLE
Can not install vendored library in tox

### ISSUE THREAD

**Issue by lexicalunit** [python-poetry/poetry#2377]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.3
- **Poetry version**: 1.0.5
- **Link of the contents of your pyproject.toml file**: https://github.com/theastropath/turbot/blob/d3b610441ae02903d75a8c0523180d8f8bea1090/pyproject.toml

## Issue

I'm trying to install a vendored library using poetry and have that work with tox. Some context:

- My repository: https://github.com/theastropath/turbot
- The library I want to vendor: https://gitlab.com/nanoNago/turnips
- The WIP branch: https://github.com/theastropath/turbot/compare/vendor-turnips

You can see in the diffs for my `pyproject.toml` where I've moved from a `git` dependency to a vendored one. This is for multiple reasons:

1. I want to pin the version of the dependency instead of relying on `master`.
2. You can't publish to PyPI with a git dependency.

Basically, this is what I've done:

```shell
# change directory to the root of my repository
cd /path/to/turbot

# create a vendor directory to house the sdist
mkdir -p vendor/turnips

# clone the library I want to vendor and build sdist for it
git clone git@gitlab.com:nanoNago/turnips.git
cd turnips
python setup.py sdist

# move the sdist out and into the vendor directory
mv dist/turnips-*.tar.gz ../vendor/turnips

# blow away the clone, no longer needed
cd ..
rm -rf turnips
```

At this point, from the root of my repository, I have a directory `vendor` that has a directory `turnps` which contains the sdist I built from a clone of `nanoNago/turnips`. Cool.

So now I do:

```shell
poetry add vendor/turnips/turnips-0.6.4.dev6+gc6ce6a0.tar.gz
```

Obviously the actual name of the sdist file may vary over time, but at the time of this writing that is the name of the file. Then I try install my application:

```shell
$ poetry install
Installing dependencies from lock file


Package operations: 1 install, 1 update, 0 removals

  - Installing discord-py (1.3.3)
  - Updating turnips (0.6.4.dev6+gc6ce6a0 -> 0.6.4.dev6+gc6ce6a0 vendor/turnips/turnips-0.6.4.dev6+gc6ce6a0.tar.gz)
  - Installing turbot (3.2.3)
```

It works! Great! Ok now let's try with tox. I'll restrict it to a single environment for the sake of simplicity and add some verbosity.

```shell
± tox -e py37 -v
using tox.ini: /Users/me/source/turbot/tox.ini (pid 56992)
using tox-3.14.6 from /usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/tox/__init__.py (pid 56992)
.package reusing: /Users/me/source/turbot/.tox/.package
[57017] /Users/me/source/turbot$ /Users/me/source/turbot/.tox/.package/bin/python /usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/tox/helper/build_requires.py poetry.masonry.api '' >.tox/.package/log/.package-10.log
[57025] /Users/me/source/turbot$ /Users/me/source/turbot/.tox/.package/bin/python /usr/local/Caskroom/miniconda/base/lib/python3.7/site-packages/tox/helper/build_isolated.py .tox/dist poetry.masonry.api '' >.tox/.package/log/.package-11.log
package .tmp/package/1/turbot-3.2.3.tar.gz links to dist/turbot-3.2.3.tar.gz (/Users/me/source/turbot/.tox)
py37 reusing: /Users/me/source/turbot/.tox/py37
py37 inst-nodeps: /Users/me/source/turbot/.tox/.tmp/package/1/turbot-3.2.3.tar.gz
[57053] /Users/me/source/turbot$ /Users/me/source/turbot/.tox/py37/bin/python -m pip install --no-deps -U .tox/.tmp/package/1/turbot-3.2.3.tar.gz >.tox/py37/log/py37-5.log
ERROR: invocation failed (exit code 1), logfile: /Users/me/source/turbot/.tox/py37/log/py37-5.log
===================================================================================================================================================================================== log start =====================================================================================================================================================================================
Processing ./.tox/.tmp/package/1/turbot-3.2.3.tar.gz
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
    Preparing wheel metadata: started
    Preparing wheel metadata: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /Users/me/source/turbot/.tox/py37/bin/python /Users/me/source/turbot/.tox/py37/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/_y/st7mb4vn48575s_cp1bdshjw0000gn/T/tmppfch7nai
         cwd: /private/var/folders/_y/st7mb4vn48575s_cp1bdshjw0000gn/T/pip-req-build-pgx61xo4
    Complete output (16 lines):
    Traceback (most recent call last):
      File "/Users/me/source/turbot/.tox/py37/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
        main()
      File "/Users/me/source/turbot/.tox/py37/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/Users/me/source/turbot/.tox/py37/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py", line 110, in prepare_metadata_for_build_wheel
        return hook(metadata_directory, config_settings)
      File "/private/var/folders/_y/st7mb4vn48575s_cp1bdshjw0000gn/T/pip-build-env-_viob16p/overlay/lib/python3.7/site-packages/poetry/masonry/api.py", line 38, in prepare_metadata_for_build_wheel
        poetry = Factory().create_poetry(Path("."))
      File "/private/var/folders/_y/st7mb4vn48575s_cp1bdshjw0000gn/T/pip-build-env-_viob16p/overlay/lib/python3.7/site-packages/poetry/factory.py", line 99, in create_poetry
        package.add_dependency(name, constraint)
      File "/private/var/folders/_y/st7mb4vn48575s_cp1bdshjw0000gn/T/pip-build-env-_viob16p/overlay/lib/python3.7/site-packages/poetry/packages/package.py", line 333, in add_dependency
        develop=constraint.get("develop", True),
      File "/private/var/folders/_y/st7mb4vn48575s_cp1bdshjw0000gn/T/pip-build-env-_viob16p/overlay/lib/python3.7/site-packages/poetry/packages/directory_dependency.py", line 36, in __init__
        raise ValueError("Directory {} does not exist".format(self._path))
    ValueError: Directory vendor/turnips/turnips-0.6.4.dev6+gc6ce6a0.tar.gz does not exist
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/me/source/turbot/.tox/py37/bin/python /Users/me/source/turbot/.tox/py37/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/_y/st7mb4vn48575s_cp1bdshjw0000gn/T/tmppfch7nai Check the logs for full command output.
WARNING: You are using pip version 20.0.2; however, version 20.1 is available.
You should consider upgrading via the '/Users/me/source/turbot/.tox/py37/bin/python -m pip install --upgrade pip' command.

====================================================================================================================================================================================== log end ======================================================================================================================================================================================
______________________________________________________________________________________________________________________________________________________________________________________ summary ______________________________________________________________________________________________________________________________________________________________________________________
ERROR:   py37: InvocationError for command /Users/me/source/turbot/.tox/py37/bin/python -m pip install --no-deps -U .tox/.tmp/package/1/turbot-3.2.3.tar.gz (exited with code 1)
```

It's failing because `ValueError: Directory vendor/turnips/turnips-0.6.4.dev6+gc6ce6a0.tar.gz does not exist`. My thought is that somehow the sdist isn't being properly copied into the working space but I don't know how to configure poetry in such a way that it will build a `MANIFEST.in` (or whatever it does) that correctly indicates that my vendor directory needs to be copied into that working space.

I've looked over the documentation and I didn't see anything that helped.

**Comment by lexicalunit** [comment]
Haha I found the solution literally minutes after writing up that whole ticket. I just needed to add an `include` to my `pyproject.toml`:

```
include = ["vendor/turnips/turnips-0.6.4.dev6+gc6ce6a0.tar.gz"]
```
