### ISSUE TITLE
Cannot use special characters in poetry.name (cookiecutter incompatibility)

### ISSUE THREAD

**Issue by frafra** [python-poetry/poetry#2406]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 31
- **Poetry version**: 1.0.6
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/frafra/936b7fdc01e8547c4ea21a4d5e50f7c8#file-pyproject-toml

## Issue

Poetry is unable to handle projects with brackets in the name. This is a problem when using cookiecutter.

```
poetry update -vvv
Using virtualenv: /home/frafra/.cache/pypoetry/virtualenvs/{{_cookiecutter.project-name_}}-jJUQu13Q-py3.7
Updating dependencies
Resolving dependencies...
   1: fact: {{ cookiecutter.project-name }} is 0.1.0
   1: derived: {{ cookiecutter.project-name }}
   1: Version solving took 0.004 seconds.
   1: Tried 1 solutions.

[InvalidRequirement]
Invalid requirement, parse error at "'{{ cooki'"

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/lib/python3.7/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/lib/python3.7/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/lib/python3.7/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/lib/python3.7/site-packages/poetry/console/commands/update.py", line 49, in handle
    return installer.run()
  File "/usr/lib/python3.7/site-packages/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/usr/lib/python3.7/site-packages/poetry/installation/installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "/usr/lib/python3.7/site-packages/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/usr/lib/python3.7/site-packages/poetry/puzzle/solver.py", line 181, in _solve
    self._package, self._provider, locked=locked, use_latest=use_latest
  File "/usr/lib/python3.7/site-packages/poetry/mixology/__init__.py", line 7, in resolve_version
    return solver.solve()
  File "/usr/lib/python3.7/site-packages/poetry/mixology/version_solver.py", line 80, in solve
    next = self._choose_package_version()
  File "/usr/lib/python3.7/site-packages/poetry/mixology/version_solver.py", line 381, in _choose_package_version
    for incompatibility in self._provider.incompatibilities_for(version):
  File "/usr/lib/python3.7/site-packages/poetry/puzzle/provider.py", line 529, in incompatibilities_for
    for dep in dependencies
  File "/usr/lib/python3.7/site-packages/poetry/puzzle/provider.py", line 529, in <listcomp>
    for dep in dependencies
  File "/usr/lib/python3.7/site-packages/poetry/packages/project_package.py", line 26, in to_dependency
    dependency = super(ProjectPackage, self).to_dependency()
  File "/usr/lib/python3.7/site-packages/poetry/packages/package.py", line 396, in to_dependency
    return dependency_from_pep_508(name)
  File "/usr/lib/python3.7/site-packages/poetry/packages/__init__.py", line 39, in dependency_from_pep_508
    req = Requirement(name)
  File "/usr/lib/python3.7/site-packages/poetry/version/requirements.py", line 212, in __init__
    requirement_string[e.loc : e.loc + 8]
```

**Comment by timthelion** [comment]
Seems similar to, if not identical to https://github.com/python-poetry/poetry/issues/1956

**Comment by Secrus** [comment]
This package name contains characters that are not allowed by the PyPA specification. As Poetry is packaging tool it will follow the specification.
