### ISSUE TITLE
pkg_resources.DistributionNotFound distribution was not found and is required

### ISSUE THREAD

**Issue by lexicalunit** [python-poetry/poetry#2411]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.3
- **Poetry version**: 1.0.5
- **Link to project**: https://github.com/theastropath/turbot

### Poetry Config

```
$ poetry config --list
cache-dir = "/Users/me/Library/Caches/pypoetry"
virtualenvs.create = true
virtualenvs.in-project = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/me/Library/Caches/pypoetry/virtualenvs
```

### Steps to Reproduce

**Install:**
```
$ poetry install
Creating virtualenv turbot-hmkN_N5W-py3.7 in /Users/me/Library/Caches/pypoetry/virtualenvs
Installing dependencies from lock file


Package operations: 77 installs, 0 updates, 0 removals

  - Installing zipp (3.1.0)
  - Installing idna (2.9)
  - Installing importlib-metadata (1.6.0)
[...]
```

**Enter shell:**
```
$ poetry shell
Spawning shell within /Users/me/Library/Caches/pypoetry/virtualenvs/turbot-hmkN_N5W-py3.7
```

**Run application:**
```
$ turbot --version
Traceback (most recent call last):
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/turbot-hmkN_N5W-py3.7/bin/turbot", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/turbot-hmkN_N5W-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3250, in <module>
    @_call_aside
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/turbot-hmkN_N5W-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3234, in _call_aside
    f(*args, **kwargs)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/turbot-hmkN_N5W-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3263, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/turbot-hmkN_N5W-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/turbot-hmkN_N5W-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/Users/me/Library/Caches/pypoetry/virtualenvs/turbot-hmkN_N5W-py3.7/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'discord-py<2.0.0,>=1.3.3' distribution was not found and is required by turbot
```

However, this is a lie because `discord-py` is absolutely installed in the venv:

```
$ python -c "import discord; print(discord.__version__)"
1.3.3
```

I have no idea why this isn't working.

**Comment by lexicalunit** [comment]
In case it matters (though I have no idea why it should):

```
$ pip --version
pip 19.2.3 from /Users/me/Library/Caches/pypoetry/virtualenvs/turbot-hmkN_N5W-py3.7/lib/python3.7/site-packages/pip (python 3.7)

$ python --version
Python 3.7.6
```

**Comment by cmsax** [comment]
I've encountered the same issue.

**Comment by finswimmer** [comment]
Interesting. Running with `poetry run turbot --version` works. But not when manually activate the venv via `source ...` or `poetry shell` :thinking:

**Comment by lexicalunit** [comment]
Yep. It's very weird.

**Comment by cmsax** [comment]
To remove `turbot` related files in `venv` and retry may help.

**Comment by finswimmer** [comment]
Hello @lexicalunit ,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
