### ISSUE TITLE
extra deps of dependency installed from source are lost

### ISSUE THREAD

**Issue by gaetano-guerriero** [python-poetry/poetry#2428]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian 10
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/gaetano-guerriero/bb8365facb43b7e508b9d05c6cea96f4

## Issue

Updating a single dependency forgets the extras of another dependency
installed from source in the lock file.

Given pyproject.toml in the gist:
```
pendulum = "2.0.0"
requests = {git = "https://github.com/psf/requests.git", rev = "v2.23.0", extras = ["security"]}
```

```
$ poetry install
```

correctly installs cryptography and pyOpenSSL, the "security" extra dependency of requests

If I update pendulum:

```
$ poetry add pendulum==2.1.0
```

cryptography and pyOpenSSL are removed from poetry.lock file, after that poetry install fails:

```
$ poetry install -vvv
Using virtualenv: /tmp/foobar/.venv
Installing dependencies from lock file

[SolverProblemError]
Because no versions of requests match !=2.23.0
 and requests (2.23.0) depends on pyOpenSSL (>=0.14), every version of requests requires pyOpenSSL (>=0.14).
So, because no versions of pyopenssl match >=0.14
 and foobar depends on requests (*), version solving failed.

Traceback (most recent call last):
  File "/home/gaetano/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/gaetano/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/gaetano/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/gaetano/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/gaetano/.poetry/lib/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/home/gaetano/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/home/gaetano/.poetry/lib/poetry/installation/installer.py", line 225, in _do_install
    ops = solver.solve(use_latest=whitelist)
  File "/home/gaetano/.poetry/lib/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/home/gaetano/.poetry/lib/poetry/puzzle/solver.py", line 190, in _solve
    raise SolverProblemError(e)
```

**Comment by finswimmer** [comment]
Hello @gaetano-guerriero,

thanks a lot for reporting. However there is already in open issue for this: #1609

If you disagree, just leave a comment.

fin swimmer

**Comment by gaetano-guerriero** [comment]
They are surely deeply related.
Anyway the core of my bug report is that with from pypi resolution works fine, with a source dependency its extra deps are sometimes lost.
The reporter of the other issue mentions this in a comment anyway.
