### ISSUE TITLE
poetry export pre-commit hook

### ISSUE THREAD

**Issue by Diaoul** [python-poetry/poetry#2457]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Feature Request

Having both a requirements.txt file and pyproject.toml + poetry.lock file may seem like duplication but it is sometimes needed for example for installing dependencies in Docker without loosing the cache on version bump or other changes unrelated to dependencies.
Installing poetry on the docker image is also a bit of a pain, and slower than pip as mentioned on other issues.

For all those reasons I decided to maintain a requirements.txt in addition to poetry, I wanted this process to be smooth and never forget about it so I created [this simple pre-commit-hook](https://github.com/Diaoul/pre-commit-hooks-poetry) that takes care of running **poetry export** for me! :cake: 

This issue is a feature request for having poetry-related pre-commit hooks like this one maintained here rather than on 3rd party repositories.

**Comment by finswimmer** [comment]
Hey @Diaoul,

sounds like this is something for the [upcoming plugin system](https://github.com/python-poetry/poetry/issues/1856).

fin swimmer

**Comment by Diaoul** [comment]
My code is only rearranging arguments for improved pre-commit compatibility. I don't think a full blown plugin system is necessary for that to be delivered.
Pre-commit hooks could be officially supported with for example a `precommit {hook_name}`.

It's common for libraries with a CLI to ship pre-commit hooks officially ([black](https://github.com/psf/black) and [isort](https://github.com/timothycrosley/isort) for example).
The only difference is that here the current CLI doesn't allow for that to work perfectly.

So it would be an officially supported plugin? Is that a thing?

**Comment by finswimmer** [comment]
Hello @Diaoul,

I see now. I misunderstood your feature request. This is really nothing for the plugin system.

I cannot answer the question by my own, whether we will create and support such a pre-commit hook. So I let this request open for further discussion.

fin swimmer

**Comment by Diaoul** [comment]
Thanks @finswimmer, I'll wait for others to weight in.
This might not be a frequent feature request but I think keeping automatically a requirements.txt in sync with poetry would make the switch to poetry easier for existing projects!

**Comment by SanketDG** [comment]
Also relevant to add here https://pre-commit.com/hooks.html

**Comment by Cielquan** [comment]
I just also had the idea to add `.pre-commit-hooks.yaml` to poetry to enable usability with pre-commit.

In itself the setup is straightforward and pretty easy. You just need to add the file with the correct config and done. I did this on [my fork](https://github.com/Cielquan/poetry/blob/feature/pre-commit-hooks/.pre-commit-hooks.yaml) to prepare a PR.

Then I went to test it and a catastrophic error occurred: **check-egg-error** (as it seems)

When I clone the poetry repo I cannot install it via `pip install .` like pre-commit will do. For installing it it wants to build a wheel for poetry but fails so because for building it it wants to use itself but its dependencies are not there because its not installed - catch-22.

Is there a way to fix this? 
Else there are two other solutions or rather workarounds:
1. Change the hooks to `language: system`. Then they would depend on a global installation of poetry or poetry must be manually installed inside the virtual environment from which one calls pre-commit.
2. Open a second repo like `python-poetry/poetry-hooks` or whatever. There we need a dummy python package to be installed and add `additional_dependencies: ["poetry"]` to the hooks to let pre-commit install poetry from PyPI.

I personally don't like both workarounds because the first one is too specific and the second is just a hack to pre-commit and no clean solution.

Here the output from pre-commit. It looks almost the same when you do `pip install .` in the repo.
```
$ pre-commit run --all-files
[INFO] Initializing environment for https://github.com/Cielquan/poetry.
[INFO] Installing environment for https://github.com/Cielquan/poetry.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/home/user/.cache/pre-commit/reponzle4x2t/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /home/user/.cache/pre-commit/reponzle4x2t
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'error'
    
stderr:
      ERROR: Command errored out with exit status 1:
       command: /home/user/.cache/pre-commit/reponzle4x2t/py_env-python3/bin/python /home/user/.cache/pre-commit/reponzle4x2t/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp87f36717
           cwd: /tmp/pip-req-build-6rb54p9s
      Complete output (36 lines):
      Traceback (most recent call last):
        File "/home/user/.cache/pre-commit/reponzle4x2t/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/home/user/.cache/pre-commit/reponzle4x2t/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user/.cache/pre-commit/reponzle4x2t/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 114, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-6o4jcxh7/overlay/lib/python3.8/site-packages/intreehooks.py", line 53, in get_requires_for_build_wheel
          return self._backend.get_requires_for_build_sdist(config_settings)
        File "/tmp/pip-build-env-6o4jcxh7/overlay/lib/python3.8/site-packages/intreehooks.py", line 38, in _backend
          obj = self._module_from_dir(modname)
        File "/tmp/pip-build-env-6o4jcxh7/overlay/lib/python3.8/site-packages/intreehooks.py", line 25, in _module_from_dir
          mod = importlib.import_module(modname)
        File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
          return _bootstrap._gcd_import(name[level:], package, level)
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
        File "<frozen importlib._bootstrap_external>", line 783, in exec_module
        File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
        File "/tmp/pip-req-build-6rb54p9s/poetry/masonry/__init__.py", line 10, in <module>
          from .builder import Builder
        File "/tmp/pip-req-build-6rb54p9s/poetry/masonry/builder.py", line 1, in <module>
          from .builders.complete import CompleteBuilder
        File "/tmp/pip-req-build-6rb54p9s/poetry/masonry/builders/__init__.py", line 1, in <module>
          from .complete import CompleteBuilder
        File "/tmp/pip-req-build-6rb54p9s/poetry/masonry/builders/complete.py", line 6, in <module>
          from poetry.factory import Factory
        File "/tmp/pip-req-build-6rb54p9s/poetry/factory.py", line 10, in <module>
          from clikit.api.io.io import IO
      ModuleNotFoundError: No module named 'clikit'
      ----------------------------------------
    ERROR: Command errored out with exit status 1: /home/user/.cache/pre-commit/reponzle4x2t/py_env-python3/bin/python /home/user/.cache/pre-commit/reponzle4x2t/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp87f36717 Check the logs for full command output.
    
Check the log at /home/user/.cache/pre-commit/pre-commit.log
*** Exit Code: 1 ***
```

**Comment by Cielquan** [comment]
I took the check-egg-problem discussion into a new issue #2515 .

**Comment by ludaavics** [comment]
Stumbled on this looking for something else. 
FWIW, dephell already does this (and more) for you: https://dephell.readthedocs.io/use-git-hook.html
But agreed, having something like this directly with poetry would smooth transitions / learning curves

**Comment by redraw** [comment]
I took a simpler approach I guess? Supposing `poetry` is installed,

```
- repo: local
  hooks:
    - id: export-requirements
      name: Export requeriments.txt
      language: system
      pass_filenames: false
      entry: poetry export --without-hashes -o requirements.txt
      files: ^(pyproject.toml|poetry.lock)$
```

**Comment by Cielquan** [comment]
> I took a simpler approach I guess? Supposing `poetry` is installed,
> 
> ```
> - repo: local
>   hooks:
>     - id: export-requirements
>       name: Export requeriments.txt
>       language: system
>       pass_filenames: false
>       entry: poetry export --without-hashes -o requirements.txt
>       files: ^(pyproject.toml|poetry.lock)$
> ```

Well good point. I think for local development its fine, but when you want to run it in CI I think it gets eventually problematic.
I run `pre-commit` via `tox` (https://github.com/pre-commit/pre-commit/issues/1309) so in my case it would be fine, but for others they would have to eventually change setups.

When #2511 gets merged the issue will be nonexistent anymore.

**Comment by Cielquan** [comment]
I created a mirror of poetry for use with pre-commit.

I plan to support it as of now till #2511 gets merged. The current version 1.1.4 is the only one supported at the moment. As poetry releases new versions they will be added also.

If you need a specific earlier version for whatever reason leave me an issue so I will add the corresponding tag.
