### ISSUE TITLE
Poetry can't resolve dependencies when linux wheel not available on PyPI

### ISSUE THREAD

**Issue by alkamid** [python-poetry/poetry#2467]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 18.04
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/alkamid/0d6b0f7e6334fc1289b0b20f4b979dfe

## Issue
Recently, VTK 9.0 has been released, however on PyPI there are only Windows and MacOS wheels available at the moment. When running poetry on linux, I'd expect to check if a linux wheel is available, and pick a lower version if it's not. Poetry however raises an exception:
```
Installing dependencies from lock file


Package operations: 1 install, 0 updates, 0 removals, 13 skipped

  - Skipping zipp (3.1.0) Already installed
  - Skipping importlib-metadata (1.6.0) Already installed
  - Skipping pyparsing (2.4.7) Already installed
  - Skipping six (1.15.0) Already installed
  - Skipping atomicwrites (1.4.0) Not needed for the current environment
  - Skipping attrs (19.3.0) Already installed
  - Skipping colorama (0.4.3) Not needed for the current environment
  - Skipping more-itertools (8.3.0) Already installed
  - Skipping packaging (20.4) Already installed
  - Skipping pluggy (0.13.1) Already installed
  - Skipping py (1.8.1) Already installed
  - Skipping wcwidth (0.1.9) Already installed
  - Skipping pytest (5.4.2) Already installed
  - Installing vtk (9.0.0)

[EnvCommandError]
Command ['/home/user/.cache/pypoetry/virtualenvs/test-vtk-JNaWryI6-py3.7/bin/pip', 'install', '--no-deps', 'vtk==9.0.0'] errored with the following return code 1, and output: 
Collecting vtk==9.0.0
  ERROR: Could not find a version that satisfies the requirement vtk==9.0.0 (from versions: 8.1.2)
ERROR: No matching distribution found for vtk==9.0.0
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Traceback (most recent call last):
  File "/home/user/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/user/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/user/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/user/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/user/.poetry/lib/poetry/console/commands/install.py", line 63, in handle
    return_code = installer.run()
  File "/home/user/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/home/user/.poetry/lib/poetry/installation/installer.py", line 286, in _do_install
    self._execute(op)
  File "/home/user/.poetry/lib/poetry/installation/installer.py", line 302, in _execute
    getattr(self, '_execute_{}'.format(method))(operation)
  File "/home/user/.poetry/lib/poetry/installation/installer.py", line 327, in _execute_install
    self._installer.install(operation.package)
  File "/home/user/.poetry/lib/poetry/installation/pip_installer.py", line 97, in install
    self.run(*args)
  File "/home/user/.poetry/lib/poetry/installation/pip_installer.py", line 123, in run
    return self._env.run_pip(*args, **kwargs)
  File "/home/user/.poetry/lib/poetry/utils/env.py", line 861, in run_pip
    return self._run(cmd, **kwargs)
  File "/home/user/.poetry/lib/poetry/utils/env.py", line 1089, in _run
    return super(VirtualEnv, self)._run(cmd, **kwargs)
  File "/home/user/.poetry/lib/poetry/utils/env.py", line 893, in _run
    raise EnvCommandError(e, input=input_)

```

**Comment by fbeaudo** [comment]
Just to mention that my colleague and I are getting the same issue. I am also using Ubuntu 18.0.4, but my colleague uses MacOS.

**Comment by finswimmer** [comment]
Hello,

in this case you have to help poetry to resolves the correct version, by using [environment marker](https://python-poetry.org/docs/dependency-specification/#using-environment-markers) in the `pyproject.toml`.

fin swimmer

**Comment by 0xMRTT** [comment]
Hi, this issue is fixed in the latest version of Poetry.

**Comment by 0xMRTT** [comment]
Hi, this issue is fixed in the latest version of Poetry.

**Comment by dimbleby** [comment]
not really fixed, but also I don't expect that poetry wants to change here so closing it is fine anyway.

poetry's solver only pays attention to versions and marker constraints, if a project hasn't published packages that will work in enviroment X then the solver doesn't check that.

so it remains the case that the solver can select eg vtk 9.0, and only at install time discover that no suitable package is available on linux

per finswimmer, in such cases you can refine the vtk requirement eg with environment markers
