### ISSUE TITLE
Windows 10 (WSL - Windows Subsystem Linux) (Ubuntu 19.10) poetry install fails

### ISSUE THREAD

**Issue by fbenavides69** [python-poetry/poetry#2472]
- [x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 19.10
- **Poetry version**: 1.0.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/fbenavides69/41b4f717beb27bc52e0cf3d7278e7a46

## Issue
While migrating from an Ubuntu box to Windows 10 Professional and recreating my development environment in the Windows Subsystem Linux, I have managed to install and update accordingly all needed libraries and settings, up to point of now trying to install the poetry environment to continue working and it just breaks!
```
fbenavides@BOSFBENAVIDES-L2:~/iso-lib$ poetry install -vvv
Using virtualenv: /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8
Installing dependencies from lock file

No dependencies to install or update

  - Skipping pycparser (2.20) Already installed
  - Skipping certifi (2019.11.28) Already installed
  - Skipping cffi (1.14.0) Already installed
  - Skipping chardet (3.0.4) Already installed
  - Skipping idna (2.9) Already installed
  - Skipping six (1.14.0) Already installed
  - Skipping urllib3 (1.25.8) Already installed
  - Skipping cryptography (2.8) Already installed
  - Skipping oauthlib (3.1.0) Already installed
  - Skipping requests (2.23.0) Already installed
  - Skipping hpack (3.0.0) Already installed
  - Skipping hyperframe (5.2.0) Already installed
  - Skipping isodate (0.6.0) Already installed
  - Skipping pyjwt (1.7.1) Already installed
  - Skipping python-dateutil (2.8.1) Already installed
  - Skipping pywin32 (227) Not needed for the current environment
  - Skipping requests-oauthlib (1.3.0) Already installed
  - Skipping adal (1.2.2) Already installed
  - Skipping azure-common (1.1.24) Already installed
  - Skipping azure-core (1.2.2) Already installed
  - Skipping h11 (0.8.1) Already installed
  - Skipping h2 (3.2.0) Already installed
  - Skipping hstspreload (2020.3.4) Already installed
  - Skipping lxml (4.2.5) Already installed
  - Skipping msal (1.1.0) Already installed
  - Skipping msrest (0.6.11) Already installed
  - Skipping pkgconfig (1.5.1) Already installed
  - Skipping portalocker (1.5.2) Already installed
  - Skipping pyparsing (2.4.6) Already installed
  - Skipping rfc3986 (1.3.2) Already installed
  - Skipping sniffio (1.1.0) Already installed
  - Skipping aiofiles (0.4.0) Already installed
  - Skipping appdirs (1.4.3) Already installed
  - Skipping atomicwrites (1.3.0) Not needed for the current environment
  - Skipping attrs (19.3.0) Already installed
  - Skipping azure-keyvault-keys (4.0.1) Already installed
  - Skipping azure-keyvault-secrets (4.0.1) Already installed
  - Skipping cached-property (1.5.1) Already installed
  - Skipping colorama (0.4.3) Not needed for the current environment
  - Skipping defusedxml (0.6.0) Already installed
  - Skipping httptools (0.1.1) Already installed
  - Skipping httpx (0.9.3) Already installed
  - Skipping marshmallow (3.5.1) Already installed
  - Skipping more-itertools (8.2.0) Already installed
  - Skipping msal-extensions (0.1.3) Already installed
  - Skipping msrestazure (0.6.2) Already installed
  - Skipping multidict (4.7.5) Already installed
  - Skipping numpy (1.18.1) Already installed
  - Skipping packaging (20.3) Already installed
  - Skipping pluggy (0.13.1) Already installed
  - Skipping py (1.8.1) Already installed
  - Skipping python-dotenv (0.12.0) Already installed
  - Skipping pytz (2019.3) Already installed
  - Skipping requests-toolbelt (0.9.1) Already installed
  - Skipping uamqp (1.2.6) Already installed
  - Skipping ujson (1.35) Already installed
  - Skipping uvloop (0.14.0) Already installed
  - Skipping wcwidth (0.1.8) Already installed
  - Skipping websockets (8.1) Already installed
  - Skipping xmlsec (1.3.3) Already installed
  - Skipping azure-identity (1.3.0) Already installed
  - Skipping azure-keyvault (4.0.0) Already installed
  - Skipping azure-servicebus (0.50.2) Already installed
  - Skipping azure-storage-blob (12.2.0) Already installed
  - Skipping azure-storage-queue (12.1.0) Already installed
  - Skipping click (7.0) Already installed
  - Skipping environs (7.4.0) Already installed
  - Skipping frozendict (1.2) Already installed
  - Skipping pandas (1.0.1) Already installed
  - Skipping pyodbc (4.0.30) Already installed
  - Skipping pyopenssl (19.1.0) Already installed
  - Skipping pytest (5.3.5) Already installed
  - Skipping python-json-logger (0.1.11) Already installed
  - Skipping sanic (19.12.2) Already installed
  - Skipping xmltodict (0.12.0) Already installed
  - Skipping zeep (3.4.0) Already installed
  - Not removing importlib-metadata (1.5.0) Not currently installed
  - Not removing zipp (3.1.0) Not currently installed
  - Installing iso-lib (0.1.0)

[EnvCommandError]
Command ['/home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/bin/pip', 'install', '-e', '/mnt/c/Users/francisco.benavides/iso-lib'] errored with the following return code 1, and output:
Obtaining file:///mnt/c/Users/francisco.benavides/iso-lib
    ERROR: Command errored out with exit status 1:
     command: /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/francisco.benavides/iso-lib/setup.py'"'"'; __file__='"'"'/mnt/c/Users/francisco.benavides/iso-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-dq7ljm0b
         cwd: /mnt/c/Users/francisco.benavides/iso-lib/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/c/Users/francisco.benavides/iso-lib/setup.py", line 29, in <module>
        with open(path.join(__here__, 'pyproject.toml'), 'r') as fh:
      File "/home/fbenavides/.pyenv/versions/3.8.3/lib/python3.8/codecs.py", line 905, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/francisco.benavides/iso-lib/pyproject.toml'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


Traceback (most recent call last):
  File "/home/fbenavides/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/fbenavides/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/fbenavides/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/fbenavides/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/fbenavides/.poetry/lib/poetry/console/commands/install.py", line 88, in handle
    builder.build()
  File "/home/fbenavides/.poetry/lib/poetry/masonry/builders/editable.py", line 17, in build
    return self._setup_build()
  File "/home/fbenavides/.poetry/lib/poetry/masonry/builders/editable.py", line 41, in _setup_build
    self._env.run_pip("install", "-e", str(self._path))
  File "/home/fbenavides/.poetry/lib/poetry/utils/env.py", line 861, in run_pip
    return self._run(cmd, **kwargs)
  File "/home/fbenavides/.poetry/lib/poetry/utils/env.py", line 1089, in _run
    return super(VirtualEnv, self)._run(cmd, **kwargs)
  File "/home/fbenavides/.poetry/lib/poetry/utils/env.py", line 893, in _run
    raise EnvCommandError(e, input=input_)

fbenavides@BOSFBENAVIDES-L2:~/iso-lib$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 19.10
Release:        19.10
Codename:       eoan
fbenavides@BOSFBENAVIDES-L2:~/iso-lib$ poetry --version
Poetry version 1.0.5
fbenavides@BOSFBENAVIDES-L2:~/iso-lib$
```
I then re-run the given command that seems to be causing the error and get the following:
```
fbenavides@BOSFBENAVIDES-L2:~/iso-lib$ /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/bin/pip install -e /mnt/c/Users/francisco.benavides/iso-lib
Obtaining file:///mnt/c/Users/francisco.benavides/iso-lib
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: frozendict<2.0,>=1.2 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (1.2)
Requirement already satisfied: xmltodict<0.13.0,>=0.12.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (0.12.0)
Requirement already satisfied: azure-identity<2.0.0,>=1.3.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (1.3.0)
Requirement already satisfied: python-json-logger<0.2.0,>=0.1.11 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (0.1.11)
Requirement already satisfied: urllib3<2.0.0,>=1.25.8 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (1.25.8)
Requirement already satisfied: sanic<20.0.0,>=19.12.2 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (19.12.2)
Requirement already satisfied: pandas<2.0.0,>=1.0.1 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (1.0.1)
Requirement already satisfied: zeep[xmlsec]<4.0.0,>=3.4.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (3.4.0)
Requirement already satisfied: numpy<2.0.0,>=1.18.1 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (1.18.1)
Requirement already satisfied: pyopenssl<20.0.0,>=19.1.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (19.1.0)
Requirement already satisfied: click<8.0,>=7.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (7.0)
Requirement already satisfied: azure-servicebus<0.51.0,>=0.50.2 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (0.50.2)
Requirement already satisfied: environs<8.0.0,>=7.2.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (7.4.0)
Requirement already satisfied: azure-storage-queue<13.0.0,>=12.1.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (12.1.0)
Requirement already satisfied: azure-keyvault<5.0.0,>=4.0.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (4.0.0)
Requirement already satisfied: azure-storage-blob<13.0.0,>=12.2.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (12.2.0)
Requirement already satisfied: pyodbc<5.0.0,>=4.0.30 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (4.0.30)
Requirement already satisfied: lxml==4.2.5 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from iso-lib==0.1.0) (4.2.5)
Requirement already satisfied: cryptography>=2.1.4 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-identity<2.0.0,>=1.3.0->iso-lib==0.1.0) (2.8)
Requirement already satisfied: msal<2.0.0,>=1.0.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-identity<2.0.0,>=1.3.0->iso-lib==0.1.0) (1.1.0)
Requirement already satisfied: msal-extensions~=0.1.3 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-identity<2.0.0,>=1.3.0->iso-lib==0.1.0) (0.1.3)
Requirement already satisfied: azure-core<2.0.0,>=1.0.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-identity<2.0.0,>=1.3.0->iso-lib==0.1.0) (1.2.2)
Requirement already satisfied: six>=1.6 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-identity<2.0.0,>=1.3.0->iso-lib==0.1.0) (1.14.0)
Requirement already satisfied: websockets<9.0,>=7.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (8.1)
Requirement already satisfied: httpx==0.9.3 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (0.9.3)
Requirement already satisfied: httptools>=0.0.10 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (0.1.1)
Requirement already satisfied: uvloop>=0.5.3; sys_platform != "win32" and implementation_name == "cpython" in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (0.14.0)
Requirement already satisfied: multidict<5.0,>=4.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (4.7.5)
Requirement already satisfied: aiofiles>=0.3.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (0.4.0)
Requirement already satisfied: ujson>=1.35; sys_platform != "win32" and implementation_name == "cpython" in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (1.35)
Requirement already satisfied: python-dateutil>=2.6.1 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from pandas<2.0.0,>=1.0.1->iso-lib==0.1.0) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from pandas<2.0.0,>=1.0.1->iso-lib==0.1.0) (2019.3)
Requirement already satisfied: defusedxml>=0.4.1 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from zeep[xmlsec]<4.0.0,>=3.4.0->iso-lib==0.1.0) (0.6.0)
Requirement already satisfied: appdirs>=1.4.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from zeep[xmlsec]<4.0.0,>=3.4.0->iso-lib==0.1.0) (1.4.3)
Requirement already satisfied: attrs>=17.2.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from zeep[xmlsec]<4.0.0,>=3.4.0->iso-lib==0.1.0) (19.3.0)
Requirement already satisfied: cached-property>=1.3.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from zeep[xmlsec]<4.0.0,>=3.4.0->iso-lib==0.1.0) (1.5.1)
Requirement already satisfied: isodate>=0.5.4 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from zeep[xmlsec]<4.0.0,>=3.4.0->iso-lib==0.1.0) (0.6.0)
Requirement already satisfied: requests-toolbelt>=0.7.1 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from zeep[xmlsec]<4.0.0,>=3.4.0->iso-lib==0.1.0) (0.9.1)
Requirement already satisfied: requests>=2.7.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from zeep[xmlsec]<4.0.0,>=3.4.0->iso-lib==0.1.0) (2.23.0)
Requirement already satisfied: xmlsec>=0.6.1; extra == "xmlsec" in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from zeep[xmlsec]<4.0.0,>=3.4.0->iso-lib==0.1.0) (1.3.3)
Requirement already satisfied: uamqp<2.0.0,>=1.2.5 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-servicebus<0.51.0,>=0.50.2->iso-lib==0.1.0) (1.2.6)
Requirement already satisfied: msrestazure<2.0.0,>=0.4.32 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-servicebus<0.51.0,>=0.50.2->iso-lib==0.1.0) (0.6.2)
Requirement already satisfied: azure-common~=1.1 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-servicebus<0.51.0,>=0.50.2->iso-lib==0.1.0) (1.1.24)
Requirement already satisfied: python-dotenv in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from environs<8.0.0,>=7.2.0->iso-lib==0.1.0) (0.12.0)
Requirement already satisfied: marshmallow>=2.7.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from environs<8.0.0,>=7.2.0->iso-lib==0.1.0) (3.5.1)
Requirement already satisfied: msrest>=0.6.10 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-storage-queue<13.0.0,>=12.1.0->iso-lib==0.1.0) (0.6.11)
Requirement already satisfied: azure-keyvault-keys~=4.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-keyvault<5.0.0,>=4.0.0->iso-lib==0.1.0) (4.0.1)
Requirement already satisfied: azure-keyvault-secrets~=4.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from azure-keyvault<5.0.0,>=4.0.0->iso-lib==0.1.0) (4.0.1)
Requirement already satisfied: cffi!=1.11.3,>=1.8 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from cryptography>=2.1.4->azure-identity<2.0.0,>=1.3.0->iso-lib==0.1.0) (1.14.0)
Requirement already satisfied: PyJWT[crypto]<2,>=1.0.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from msal<2.0.0,>=1.0.0->azure-identity<2.0.0,>=1.3.0->iso-lib==0.1.0) (1.7.1)
Requirement already satisfied: portalocker~=1.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from msal-extensions~=0.1.3->azure-identity<2.0.0,>=1.3.0->iso-lib==0.1.0) (1.5.2)
Requirement already satisfied: rfc3986<2,>=1.3 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from httpx==0.9.3->sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (1.3.2)
Requirement already satisfied: h2==3.* in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from httpx==0.9.3->sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (3.2.0)
Requirement already satisfied: sniffio==1.* in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from httpx==0.9.3->sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (1.1.0)
Requirement already satisfied: idna==2.* in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from httpx==0.9.3->sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (2.9)
Requirement already satisfied: h11==0.8.* in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from httpx==0.9.3->sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (0.8.1)
Requirement already satisfied: certifi in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from httpx==0.9.3->sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (2019.11.28)
Requirement already satisfied: hstspreload in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from httpx==0.9.3->sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (2020.3.4)
Requirement already satisfied: chardet==3.* in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from httpx==0.9.3->sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (3.0.4)
Requirement already satisfied: pkgconfig in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from xmlsec>=0.6.1; extra == "xmlsec"->zeep[xmlsec]<4.0.0,>=3.4.0->iso-lib==0.1.0) (1.5.1)
Requirement already satisfied: adal<2.0.0,>=0.6.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from msrestazure<2.0.0,>=0.4.32->azure-servicebus<0.51.0,>=0.50.2->iso-lib==0.1.0) (1.2.2)
Requirement already satisfied: requests-oauthlib>=0.5.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from msrest>=0.6.10->azure-storage-queue<13.0.0,>=12.1.0->iso-lib==0.1.0) (1.3.0)
Requirement already satisfied: pycparser in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from cffi!=1.11.3,>=1.8->cryptography>=2.1.4->azure-identity<2.0.0,>=1.3.0->iso-lib==0.1.0) (2.20)
Requirement already satisfied: hpack<4,>=3.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from h2==3.*->httpx==0.9.3->sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (3.0.0)
Requirement already satisfied: hyperframe<6,>=5.2.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from h2==3.*->httpx==0.9.3->sanic<20.0.0,>=19.12.2->iso-lib==0.1.0) (5.2.0)
Requirement already satisfied: oauthlib>=3.0.0 in /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/lib/python3.8/site-packages (from requests-oauthlib>=0.5.0->msrest>=0.6.10->azure-storage-queue<13.0.0,>=12.1.0->iso-lib==0.1.0) (3.1.0)
Installing collected packages: iso-lib
  Running setup.py develop for iso-lib
    ERROR: Command errored out with exit status 1:
     command: /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/francisco.benavides/iso-lib/setup.py'"'"'; __file__='"'"'/mnt/c/Users/francisco.benavides/iso-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /mnt/c/Users/francisco.benavides/iso-lib/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/c/Users/francisco.benavides/iso-lib/setup.py", line 9, in <module>
        from config import __name__
      File "/mnt/c/Users/francisco.benavides/iso-lib/config/__init__.py", line 11, in <module>
        from .__main__ import env
      File "/mnt/c/Users/francisco.benavides/iso-lib/config/__main__.py", line 6, in <module>
        import environs
    ModuleNotFoundError: No module named 'environs'
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/francisco.benavides/iso-lib/setup.py'"'"'; __file__='"'"'/mnt/c/Users/francisco.benavides/iso-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps Check the logs for full command output.
fbenavides@BOSFBENAVIDES-L2:~/iso-lib$ 
```
The `environs` module is in deed installed, so I have no idea why it's complaining.

**Comment by abn** [comment]
```console
    FileNotFoundError: [Errno 2] No such file or directory: '/mnt/c/Users/francisco.benavides/iso-lib/pyproject.toml'
```

This indicates that this file was not available in the PEP 517 isolated build enviroment. Check your package's sdist. 

```console
Installing collected packages: iso-lib
  Running setup.py develop for iso-lib
    ERROR: Command errored out with exit status 1:
     command: /home/fbenavides/.cache/pypoetry/virtualenvs/iso-lib-3LeqttpQ-py3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/mnt/c/Users/francisco.benavides/iso-lib/setup.py'"'"'; __file__='"'"'/mnt/c/Users/francisco.benavides/iso-lib/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps
         cwd: /mnt/c/Users/francisco.benavides/iso-lib/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/mnt/c/Users/francisco.benavides/iso-lib/setup.py", line 9, in <module>
        from config import __name__
      File "/mnt/c/Users/francisco.benavides/iso-lib/config/__init__.py", line 11, in <module>
        from .__main__ import env
      File "/mnt/c/Users/francisco.benavides/iso-lib/config/__main__.py", line 6, in <module>
        import environs
    ModuleNotFoundError: No module named 'environs'
```

This bit indicates that your project `iso-lib` required `environs` as a `build-system` requirement. For example (assuming the `iso-lib` project is built using `setuptools`, it will need the following in its `pyproject.toml`.

```toml
[build-system]
requires = ["setuptools", "wheel", "environs"]
build-backend = "setuptools.build_meta:__legacy__"
```
