### ISSUE TITLE
Poetry errors fails with '--format wheel'

### ISSUE THREAD

**Issue by padix-key** [python-poetry/poetry#2493]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS**: Ubuntu 18.04
- **Poetry version**: 1.0.5
- **pyproject.toml**: https://github.com/padix-key/biotite/blob/poetry-build/pyproject.toml
- **build.py**: https://github.com/padix-key/biotite/blob/poetry-build/build.py

## Issue

When building my Python project with `poetry build -vvv -f wheel`it errors:
```
[EnvCommandError]
Command ['/home/kunzmann/bin/conda/envs/biotite-dev/bin/python', '/home/kunzmann/data/coding/biotite/setup.py', 'build', '-b', '/home/kunzmann/data/coding/biotite/build'] errored with the following return code 2, and output: 
/home/kunzmann/bin/conda/envs/biotite-dev/bin/python: can't open file '/home/kunzmann/data/coding/biotite/setup.py': [Errno 2] No such file or directory


Traceback (most recent call last):
  File "/home/kunzmann/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/kunzmann/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/kunzmann/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/kunzmann/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/kunzmann/.poetry/lib/poetry/console/commands/build.py", line 30, in handle
    builder.build(fmt)
  File "/home/kunzmann/.poetry/lib/poetry/masonry/builder.py", line 21, in build
    return builder.build()
  File "/home/kunzmann/.poetry/lib/poetry/masonry/builders/wheel.py", line 81, in build
    self._build(zip_file)
  File "/home/kunzmann/.poetry/lib/poetry/masonry/builders/wheel.py", line 103, in _build
    self._env.run(
  File "/home/kunzmann/.poetry/lib/poetry/utils/env.py", line 856, in run
    return self._run(cmd, **kwargs)
  File "/home/kunzmann/.poetry/lib/poetry/utils/env.py", line 1089, in _run
    return super(VirtualEnv, self)._run(cmd, **kwargs)
  File "/home/kunzmann/.poetry/lib/poetry/utils/env.py", line 893, in _run
    raise EnvCommandError(e, input=input_)
```

However, when running `poetry build` (without `--format`) it works fine.

I am using Poetry in a Conda environment.

**Comment by padix-key** [comment]
When I execute `pip install .` on the project directory, I get a similar error:
```
  ERROR: Command errored out with exit status 1:
   command: /home/kunzmann/bin/conda/envs/biotite-poetry/bin/python /home/kunzmann/bin/conda/envs/biotite-poetry/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpgreyr6mw
       cwd: /tmp/pip-req-build-583ux60a
  Complete output (33 lines):
  Traceback (most recent call last):
    File "/tmp/pip-build-env-pb40k1f5/overlay/lib/python3.8/site-packages/poetry/utils/env.py", line 889, in _run
      output = subprocess.check_output(
    File "/home/kunzmann/bin/conda/envs/biotite-poetry/lib/python3.8/subprocess.py", line 411, in check_output
      return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
    File "/tmp/pip-build-env-pb40k1f5/overlay/lib/python3.8/site-packages/poetry/utils/_compat.py", line 205, in run
      raise CalledProcessError(
  poetry.utils._compat.CalledProcessError: Command '['/home/kunzmann/bin/conda/envs/biotite-poetry/bin/python', 'setup.py', 'build', '-b', 'build']' returned non-zero exit status 2.
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "/home/kunzmann/bin/conda/envs/biotite-poetry/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 257, in <module>
      main()
    File "/home/kunzmann/bin/conda/envs/biotite-poetry/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 240, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/home/kunzmann/bin/conda/envs/biotite-poetry/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 181, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/pip-build-env-pb40k1f5/overlay/lib/python3.8/site-packages/poetry/masonry/api.py", line 62, in build_wheel
      WheelBuilder.make_in(
    File "/tmp/pip-build-env-pb40k1f5/overlay/lib/python3.8/site-packages/poetry/masonry/builders/wheel.py", line 55, in make_in
      wb.build()
    File "/tmp/pip-build-env-pb40k1f5/overlay/lib/python3.8/site-packages/poetry/masonry/builders/wheel.py", line 81, in build
      self._build(zip_file)
    File "/tmp/pip-build-env-pb40k1f5/overlay/lib/python3.8/site-packages/poetry/masonry/builders/wheel.py", line 103, in _build
      self._env.run(
    File "/tmp/pip-build-env-pb40k1f5/overlay/lib/python3.8/site-packages/poetry/utils/env.py", line 856, in run
      return self._run(cmd, **kwargs)
    File "/tmp/pip-build-env-pb40k1f5/overlay/lib/python3.8/site-packages/poetry/utils/env.py", line 893, in _run
      raise EnvCommandError(e, input=input_)
  poetry.utils.env.EnvCommandError: Command ['/home/kunzmann/bin/conda/envs/biotite-poetry/bin/python', 'setup.py', 'build', '-b', 'build'] errored with the following return code 2, and output:
  /home/kunzmann/bin/conda/envs/biotite-poetry/bin/python: can't open file 'setup.py': [Errno 2] No such file or directory
```

**Comment by padix-key** [comment]
The core of the issue seems to be the build script: If I remove `build = "build.py"` from the `pyproject.toml`, both errors disappear.
However, the problem is not within `build.py`, since these errors are stil raised, when `build.py` is empty.

**Comment by padix-key** [comment]
Just recognized, that this issue is a duplicate of #2214.
