### ISSUE TITLE
Installation after Deinstallation impossible

### ISSUE THREAD

**Issue by Cielquan** [python-poetry/poetry#2539]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: linux mint 19.3
- **Poetry version**: master / 1.0.9

## Issue

I installed poetry with the curl pipe command which resulted in an installation with python2.7. I got sick of the version message every time and wanted to reinstall with python3.

To safe some time I modified the install command for uninstallation:
`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - --uninstall`

The uninstallation went through without a problem. Then I wanted to install poetry again with py3 but it is not possible anymore regardless of the python version (I tried 2.7, 3.5, 3.6, 3.7, 3.8, 3.9).

Next I tried to recreate the problem on another machine which resulted in the same issue.
I first installed poetry, then uninstalled it and tried to install again. See below for the outputs of those three commands.

EDIT: I installed py3.9 after the uninstallation. System is up-to-date.

```
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile file located at:

$HOME/.profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.0.9
  - Downloading poetry-1.0.9-linux.tar.gz (25.37MB)

Poetry (1.0.9) is installed now. Great!

To get started you need Poetry's bin directory ($HOME/.poetry/bin) in your `PATH`
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run `source $HOME/.poetry/env`
```
```
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 - --uninstall
# We are sorry to see you go!

This will uninstall Poetry.

It will remove the `poetry` command from Poetry's bin directory, located at:

$HOME/.poetry/bin

This will also remove Poetry from your system's PATH.
```
```
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

$HOME/.poetry/bin

This path will then be added to your `PATH` environment variable by
modifying the profile file located at:

$HOME/.profile

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.0.9
Traceback (most recent call last):
  File "/usr/lib/python3.6/urllib/request.py", line 1325, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/lib/python3.6/http/client.py", line 1264, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1310, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1259, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.6/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/usr/lib/python3.6/http/client.py", line 976, in send
    self.connect()
  File "/usr/lib/python3.6/http/client.py", line 1417, in connect
    super().connect()
  File "/usr/lib/python3.6/http/client.py", line 948, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/usr/lib/python3.6/socket.py", line 704, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "/usr/lib/python3.6/socket.py", line 745, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -2] Name or service not known

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 999, in <module>
  File "<stdin>", line 995, in main
  File "<stdin>", line 358, in run
  File "<stdin>", line 491, in install
  File "<stdin>", line 511, in make_lib
  File "<stdin>", line 535, in _make_lib
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 564, in error
    result = self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 756, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 526, in open
    response = self._open(req, data)
  File "/usr/lib/python3.6/urllib/request.py", line 544, in _open
    '_open', req)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 1368, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "/usr/lib/python3.6/urllib/request.py", line 1327, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno -2] Name or service not known>
*** Exit Code: 1 ***
```

**Comment by abitrolly** [comment]
This looks like a problem with internet connection. Does that repeat the the latest version?

**Comment by Cielquan** [comment]
I have to test again.

**Comment by Cielquan** [comment]
So I tested it again on a VM that failed back then and now with `1.1.2` it works just fine. Dunno if the new version fixed it or some other circumstances.

**Comment by pkoch** [comment]
Got this, with Python `3.10.2`. I have no clue why it started happening, I had installed Poetry just fine before.

**Comment by Secrus** [comment]
> Got this, with Python `3.10.2`. I have no clue why it started happening, I had installed Poetry just fine before.

Are you using new script?

**Comment by pkoch** [comment]
Hmm, I was missing `libssl-dev libssl3 libssl3:i386`. I re-instally my Python with that, and things started working. Unsure why that lib went away, I suspect the upgrade to Ubuntu Jammy, but I can't tell for sure. :x

**Comment by pkoch** [comment]
I used `https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py`.
