### ISSUE TITLE
Can't use multiple constrains dependencies on `python`

### ISSUE THREAD

**Issue by FFY00** [python-poetry/poetry#2542]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Arch Linux
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/FFY00/d36c0e9899c07a7f2f14021629230dde

## Issue

I am trying to use multiple contains dependencies (https://python-poetry.org/docs/dependency-specification/#multiple-constraints-dependencies) on `python`.

```toml
[tool.poetry.dependencies]
python = [
    '2.7',
    '>=3.5',
]
```
Results in
```
[AttributeError]
'Array' object has no attribute 'strip'

Traceback (most recent call last):
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/command/command.py", line 163, in _do_handle
    self._dispatcher.dispatch(PRE_HANDLE, event)
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/event/event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/event/event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/console/config/application_config.py", line 86, in set_env
    poetry = command.poetry
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/console/commands/command.py", line 10, in poetry
    return self.application.poetry
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/console/application.py", line 49, in poetry
    self._poetry = Factory().create_poetry(Path.cwd())
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/factory.py", line 90, in create_poetry
    package.python_versions = constraint
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/packages/project_package.py", line 43, in python_versions
    self._python_constraint = parse_constraint(value)
  File "/home/anubis/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/semver/__init__.py", line 19, in parse_constraint
    or_constraints = re.split(r"\s*\|\|?\s*", constraints.strip())
```

**Comment by RootLUG** [comment]
I believe multiple version should be defined like this as I just used it in another project:
`python = "~2.7 || >=3.5"`

**Comment by FFY00** [comment]
Well, sure, I could do that, but as I understand it, it is not the poetry way (tm) :smile:.

**Comment by finswimmer** [comment]
The right site of the dependency definition expects either a string or an inline table. This is why one cannot provide a list and it must be written like @RootLUG explained.
