### ISSUE TITLE
setup.py --user not recognized

### ISSUE THREAD

**Issue by heitorlessa** [python-poetry/poetry#2550]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Ubuntu 20.04 
- **Poetry version**: 1.0.9 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**:  https://gist.github.com/heitorlessa/a7bea3acf7b50ea640bca804beb26a1f 

## Issue

When using poetry in [Gitpod.io](https://gitpod.io) to install a project in editable mode, `poetry install`, it fails with --user not recognized -- This does not happen locally in my laptop.

It seemed to be [related to an old version of pip that poetry might be using](https://github.com/python-poetry/poetry/issues/1661), so I've gone ahead and updated both pip and setuptools, sadly to no avail - `pip install -U pip setuptools; poetry run pip install -U pip setuptools`

Is there anything else I can possibly try?

Thank you!

### How to reproduce

1. [Launch a new IDE environment in the browser](https://gitpod.io/#https://github.com/awslabs/aws-lambda-powertools-python)
2. Install all dependencies by running `make dev`

### Logs

**Full error**

```python
[EnvCommandError]
Command ['/home/gitpod/.cache/pypoetry/virtualenvs/aws-lambda-powertools-YwoV7uxh-py3.8/bin/pip', 'install', '--no-deps', '-e', '/workspace/aws-lambda-powertools-python'] errored with the following return code 1, and output: 
Obtaining file:///workspace/aws-lambda-powertools-python
Installing collected packages: aws-lambda-powertools
  Running setup.py develop for aws-lambda-powertools
    ERROR: Command errored out with exit status 1:
     command: /home/gitpod/.cache/pypoetry/virtualenvs/aws-lambda-powertools-YwoV7uxh-py3.8/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/workspace/aws-lambda-powertools-python/setup.py'"'"'; __file__='"'"'/workspace/aws-lambda-powertools-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix=
         cwd: /workspace/aws-lambda-powertools-python/
    Complete output (6 lines):
    usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: setup.py --help [cmd1 cmd2 ...]
       or: setup.py --help-commands
       or: setup.py cmd --help
    
    error: option --user not recognized
    ----------------------------------------
ERROR: Command errored out with exit status 1: /home/gitpod/.cache/pypoetry/virtualenvs/aws-lambda-powertools-YwoV7uxh-py3.8/bin/python3 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/workspace/aws-lambda-powertools-python/setup.py'"'"'; __file__='"'"'/workspace/aws-lambda-powertools-python/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' develop --no-deps --user --prefix= Check the logs for full command output.
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Traceback (most recent call last):
  File "/workspace/.pip-modules/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/poetry/console/commands/install.py", line 94, in handle
    builder.build()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/poetry/masonry/builders/editable.py", line 17, in build
    return self._setup_build()
  File "/workspace/.pip-modules/lib/python3.8/site-packages/poetry/masonry/builders/editable.py", line 41, in _setup_build
    self._env.run_pip("install", "--no-deps", "-e", str(self._path))
  File "/workspace/.pip-modules/lib/python3.8/site-packages/poetry/utils/env.py", line 861, in run_pip
    return self._run(cmd, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/poetry/utils/env.py", line 1089, in _run
    return super(VirtualEnv, self)._run(cmd, **kwargs)
  File "/workspace/.pip-modules/lib/python3.8/site-packages/poetry/utils/env.py", line 893, in _run
    raise EnvCommandError(e, input=input_)

make: *** [Makefile:7: dev] Error 1
```

**Python site output**

```python
python -m site
sys.path = [
    '/workspace/aws-lambda-powertools-python',
    '/home/gitpod/.pyenv/versions/3.8.3/lib/python38.zip',
    '/home/gitpod/.pyenv/versions/3.8.3/lib/python3.8',
    '/home/gitpod/.pyenv/versions/3.8.3/lib/python3.8/lib-dynload',
    '/workspace/.pip-modules/lib/python3.8/site-packages',
    '/home/gitpod/.pyenv/versions/3.8.3/lib/python3.8/site-packages',
]
USER_BASE: '/workspace/.pip-modules' (exists)
USER_SITE: '/workspace/.pip-modules/lib/python3.8/site-packages' (exists)
ENABLE_USER_SITE: True
```

**Comment by heitorlessa** [comment]
Resolving - After lots of troubleshooting I can only reproduce this on Gitpod.io env
