### ISSUE TITLE
Poetry should crash when entry-point has invalid name

### ISSUE THREAD

**Issue by Conchylicultor** [python-poetry/poetry#2581]
Issue was also posted in https://github.com/pypa/setuptools/issues/2203 and https://github.com/pypa/pip/issues/8461.

**Environment**

* Poetry version: 1.0.9
* pip version: pip 20.1.1
* Python version: 3.6
* OS: MacOs

**Description**

I was experimenting with [entry_points](https://setuptools.readthedocs.io/en/latest/setuptools.html#dynamic-discovery-of-services-and-plugins) and released a test pip package with an invalid "entry-point" name: `epot-test` (the `-` is an invalid character):

```
[tool.poetry.plugins."epot-test.test"]
"abc" = "epot_poetry_test.sub.other:SomeClass"
```

I was able to successfully publish the package even if the "epot-test" is not a valid entry-point name.

However `pip install` fails as the entry-point is invalid.

**Expected behavior**

Poetry should have catch the invalid name and not publish the package in the first place. `poetry build` should have failed.

**How to Reproduce**

Create a package with an invalid entry-point name:
```
[tool.poetry.plugins."epot-test.invalid"]
"a" = "package:SomeClass"
```

```sh
poetry build & poetry publish  # Push the corrupted package << Should fail here!
pip install epot-poetry-test==0.2.0  # Fails (but still install the corrupted package)

# After the corrupted package is installed, it cannot be uninstalled or replaced:
pip uninstall epot-poetry-test  # Fail
pip epot-poetry-test --upgrade  # Fail
```

**Output**

```
epot-macbookpro% pip3 uninstall epot-poetry-test     
Found existing installation: epot-poetry-test 0.2.0
ERROR: Exception:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2857, in get_entry_map
    ep_map = self._ep_map
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2815, in __getattr__
    raise AttributeError(attr)
AttributeError: _ep_map

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 188, in _main
    status = self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/commands/uninstall.py", line 86, in run
    auto_confirm=options.yes, verbose=self.verbosity > 0,
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 675, in uninstall
    uninstalled_pathset = UninstallPathSet.from_dist(dist)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_internal/req/req_uninstall.py", line 571, in from_dist
    console_scripts = dist.get_entry_map(group='console_scripts')
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2860, in get_entry_map
    self._get_metadata('entry_points.txt'), self
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2535, in parse_map
    maps[group] = cls.parse_group(group, lines, dist)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/pip/_vendor/pkg_resources/__init__.py", line 2510, in parse_group
    raise ValueError("Invalid group name", group)
ValueError: ('Invalid group name', 'epot-test.test')
```

The only way I found was to manually found where the corrupted package was installed and remove the faulty entry point.

**Comment by mthuurne** [comment]
I ran into this same issue: a package with a dash in the entry point group name can be installed and used just fine, but it cannot be uninstalled.

The [entry points specification](https://packaging.python.org/en/latest/specifications/entry-points/#data-model) is explicit about what characters are allowed, but unfortunately I didn't see that until now. It would be nice if Poetry could catch this mistake early.

I'm using Poetry 1.2.2, pip 22.3 and Python 3.10.6 on Linux.

**Comment by neersighted** [comment]
I can reproduce this on 1.2.2; this would need to be fixed in core. PRs welcome.

**Comment by radoering** [comment]
I am going to close this as "won't fix" because [`tool.poetry.plugins` is deprecated](https://python-poetry.org/docs/pyproject/#plugins) since Poetry 2 and the replacement `project.entry-points` already has a stricter regex.
