### ISSUE TITLE
poetry-core: * character causes "[TypeError] quote_from_bytes() expected bytes"

### ISSUE THREAD

**Issue by fredrikaverpil** [python-poetry/poetry#2626]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux RHEL 7
- **Poetry version**: 1.0.9

## Issue

If a dependency is pinned with an asterisk, the **poetry-core 1.0.0a8** will fail installing the package, when installing with tox.

```toml
# pyproject.toml
[tool.poetry.dependencies]
dep = "0.*"

[build-system]
requires = ["poetry-core>=1.0.0a8"]
build-backend = "poetry.core.masonry.api"
```

```ini
# tox.ini

[tox]
isolated_build = true
envlist =
    py37

[testenv:format]
description = Format code.
skip_install = true
whitelist_externals = poetry
commands =
    poetry install -vvv --no-root --no-dev -E format
    poetry run black {posargs}
```

Running `tox -e format`, yields the following:

```
  - Updating dep (0.0.0 053051a -> 0.3.0)

[TypeError]
quote_from_bytes() expected bytes

Traceback (most recent call last):
  File "/home/fredrik/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/fredrik/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/fredrik/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/fredrik/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/fredrik/.poetry/lib/poetry/console/commands/install.py", line 69, in handle
    return_code = installer.run()
  File "/home/fredrik/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/home/fredrik/.poetry/lib/poetry/installation/installer.py", line 286, in _do_install
    self._execute(op)
  File "/home/fredrik/.poetry/lib/poetry/installation/installer.py", line 302, in _execute
    getattr(self, '_execute_{}'.format(method))(operation)
  File "/home/fredrik/.poetry/lib/poetry/installation/installer.py", line 357, in _execute_update
    self._installer.update(source, target)
  File "/home/fredrik/.poetry/lib/poetry/installation/pip_installer.py", line 104, in update
    self.install(target, update=True)
  File "/home/fredrik/.poetry/lib/poetry/installation/pip_installer.py", line 62, in install
    index_url = repository.authenticated_url
  File "/home/fredrik/.poetry/lib/poetry/repositories/legacy_repository.py", line 224, in authenticated_url
    password=quote(self._auth.auth.password, safe=''),
  File "/app/vbuild/RHEL7-x86_64/python/3.7.4/lib/python3.7/urllib/parse.py", line 834, in quote
    return quote_from_bytes(string, safe)
  File "/app/vbuild/RHEL7-x86_64/python/3.7.4/lib/python3.7/urllib/parse.py", line 859, in quote_from_bytes
    raise TypeError('quote_from_bytes() expected bytes')

ERROR: InvocationError for command /home/fredrik/.poetry/bin/poetry install -vvv --no-root --no-dev -E format (exited with code 1)
```

**Comment by dimbleby** [comment]
seems long since fixed, works fine on 1.1.13
