### ISSUE TITLE
Traceback displayed when using wrong option

### ISSUE THREAD

**Issue by M5oul** [python-poetry/poetry#2627]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora 32
- **Poetry version**: 1.0.9
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I used `-d` option which does not exists, and there is a traceback..
The traceback seems catched, but I suggest to hide it:
```bash
poetry add asynctest -d

[NoSuchOptionException]
The "-d" option does not exist.

Traceback (most recent call last):
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/console_application.py", line 123, in run
    io = io_factory(
  File "/home/moul/.local/lib/python3.8/site-packages/poetry/console/config/application_config.py", line 165, in create_io
    resolved_command = application.resolve_command(args)
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/console_application.py", line 110, in resolve_command
    return self._config.command_resolver.resolve(args, self)
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/resolver/default_resolver.py", line 34, in resolve
    return self.create_resolved_command(result)
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/resolver/default_resolver.py", line 166, in create_resolved_command
    if not result.is_parsable():
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/resolver/resolve_result.py", line 43, in is_parsable
    self._parse()
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/resolver/resolve_result.py", line 49, in _parse
    self._parsed_args = self._command.parse(self._raw_args)
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/api/command/command.py", line 113, in parse
    return self._config.args_parser.parse(args, self._args_format, lenient)
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/args/default_args_parser.py", line 53, in parse
    self._parse(args, _fmt, lenient)
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/args/default_args_parser.py", line 103, in _parse
    self._parse_short_option(token, tokens, fmt, lenient)
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/args/default_args_parser.py", line 272, in _parse_short_option
    self._add_short_option(name, None, tokens, fmt, lenient)
  File "/home/moul/.local/lib/python3.8/site-packages/clikit/args/default_args_parser.py", line 349, in _add_short_option
    raise NoSuchOptionException(name)
```

**Comment by dimbleby** [comment]
per recent cleo update, output now is
```
$ poetry add sadfadf -d

The option "-d" does not exist
```
much cleaner
