### ISSUE TITLE
Poetry installation on AIX7.2 failed with "ZIP does not support timestamps before 1980"

### ISSUE THREAD

**Issue by bergen288** [python-poetry/poetry#2644]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  AIX7.2 
- **Poetry version**:  1.0.9 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Below is my script to install Poetry package:
```
python setup.py install >install.log 2>&1 &
```
Below is the log:
```
running install
running bdist_egg
running egg_info
writing poetry.egg-info/PKG-INFO
writing dependency_links to poetry.egg-info/dependency_links.txt
writing entry points to poetry.egg-info/entry_points.txt
writing requirements to poetry.egg-info/requires.txt
writing top-level names to poetry.egg-info/top_level.txt
reading manifest file 'poetry.egg-info/SOURCES.txt'
writing manifest file 'poetry.egg-info/SOURCES.txt'
installing library code to build/bdist.aix-7.2/egg
running install_lib
running build_py
copying poetry.egg-info/PKG-INFO -> build/bdist.aix-7.2/egg/EGG-INFO
copying poetry.egg-info/SOURCES.txt -> build/bdist.aix-7.2/egg/EGG-INFO
copying poetry.egg-info/dependency_links.txt -> build/bdist.aix-7.2/egg/EGG-INFO
copying poetry.egg-info/entry_points.txt -> build/bdist.aix-7.2/egg/EGG-INFO
copying poetry.egg-info/requires.txt -> build/bdist.aix-7.2/egg/EGG-INFO
copying poetry.egg-info/top_level.txt -> build/bdist.aix-7.2/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/poetry-1.0.9-py3.7.egg' and adding 'build/bdist.aix-7.2/egg' to it
Traceback (most recent call last):
  File "setup.py", line 92, in <module>
    setup(**setup_kwargs)
  File "/opt/freeware/lib/python3.7/site-packages/setuptools-47.3.1.post20200626-py3.7.egg/setuptools/__init__.py", line 161, in setup
  File "/opt/freeware/lib64/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/opt/freeware/lib64/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/opt/freeware/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/freeware/lib/python3.7/site-packages/setuptools-47.3.1.post20200626-py3.7.egg/setuptools/command/install.py", line 67, in run
  File "/opt/freeware/lib/python3.7/site-packages/setuptools-47.3.1.post20200626-py3.7.egg/setuptools/command/install.py", line 109, in do_egg_install
  File "/opt/freeware/lib64/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/opt/freeware/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/opt/freeware/lib/python3.7/site-packages/setuptools-47.3.1.post20200626-py3.7.egg/setuptools/command/bdist_egg.py", line 236, in run
  File "/opt/freeware/lib/python3.7/site-packages/setuptools-47.3.1.post20200626-py3.7.egg/setuptools/command/bdist_egg.py", line 505, in make_zipfile
  File "/opt/freeware/lib/python3.7/site-packages/setuptools-47.3.1.post20200626-py3.7.egg/setuptools/command/bdist_egg.py", line 498, in visit
  File "/opt/freeware/lib64/python3.7/zipfile.py", line 1730, in write
    zinfo = ZipInfo.from_file(filename, arcname)
  File "/opt/freeware/lib64/python3.7/zipfile.py", line 530, in from_file
    zinfo = cls(arcname, date_time)
  File "/opt/freeware/lib64/python3.7/zipfile.py", line 357, in __init__
    raise ValueError('ZIP does not support timestamps before 1980')
ValueError: ZIP does not support timestamps before 1980
```
/opt/freeware/lib64/python3.7/zipfile.py has the following line.
```
   def __init__(self, filename="NoName", date_time=(1980,1,1,0,0,0)):
```
I also notice some files and directories in poetry subdirectory were last touched in 1969.  Not sure which one is the root cause.
```
-rw-r--r--    1 xzhang   xzhang          345 Dec 31 1969  __init__.py
-rw-r--r--    1 xzhang   xzhang           92 Dec 31 1969  __main__.py
-rw-r--r--    1 xzhang   xzhang           22 Dec 31 1969  __version__.py
-rw-r--r--    1 xzhang   xzhang           99 Dec 31 1969  exceptions.py
-rw-r--r--    1 xzhang   xzhang        11882 Dec 31 1969  factory.py
```

**Comment by finswimmer** [comment]
Hello @bergen288 ,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
