### ISSUE TITLE
Poetry add pack

### ISSUE THREAD

**Issue by peach-lasagna** [python-poetry/poetry#2735]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: 10 Windows
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://github.com/peach-lasagna/Idea-Manager/blob/master/pyproject.toml) with the contents of your pyproject.toml file**

## Issue

I tried to run file and catch error

```sh
$ py idea_manager
Traceback (most recent call last):
  File "C:\Users\kir\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kir\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "idea_manager\__main__.py", line 4, in <module>
    from dotenv import find_dotenv, load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```
then run install
```sh
$ poetry install
Creating virtualenv idea-manager in C:\Users\kir\Tools\Idea-manager\.venv
Updating dependencies
Resolving dependencies...

Writing lock file


Package operations: 32 installs, 0 updates, 0 removals

  - Installing smmap (3.0.4)
  - Installing gitdb (4.0.5)
  - Installing pbr (5.4.5)
  - Installing snowballstemmer (2.0.0)
  - Installing appdirs (1.4.4)
  - Installing attrs (19.3.0)
  - Installing click (7.1.2)
  - Installing colorama (0.4.3)
  - Installing gitpython (3.1.7)
  - Installing mccabe (0.6.1)
  - Installing mypy-extensions (0.4.3)
  - Installing pathspec (0.8.0)
  - Installing pycodestyle (2.6.0)
  - Installing pydocstyle (5.0.2)
  - Installing pyflakes (2.2.0)
  - Installing pyyaml (5.3.1)
  - Installing regex (2020.7.14)
  - Installing six (1.15.0)
  - Installing stevedore (3.2.0)
  - Installing toml (0.10.1)
  - Installing typed-ast (1.4.1)
  - Installing typing-extensions (3.7.4.2)
  - Installing autopep8 (1.5.3)
  - Installing bandit (1.6.2)
  - Installing black (19.10b0)
  - Installing flake8 (3.8.3)
  - Installing isort (4.3.21)
  - Installing keyboard (0.13.5)
  - Installing mypy (0.782)
  - Installing pylama (7.7.1)
  - Installing python-dotenv (0.14.0)
  - Installing vulture (1.6)
  - Installing Idea-manager (0.1.0)
```
run show
```sh
$ poetry show
appdirs           1.4.4     A small Python module for determining appropriate platform-specific dirs, e.g. a "user data dir".
attrs             19.3.0    Classes Without Boilerplate
autopep8          1.5.3     A tool that automatically formats Python code to conform to the PEP 8 style guide
bandit            1.6.2     Security oriented static analyser for python code.
black             19.10b0   The uncompromising code formatter.
click             7.1.2     Composable command line interface toolkit
colorama          0.4.3     Cross-platform colored terminal text.
flake8            3.8.3     the modular source code checker: pep8 pyflakes and co
gitdb             4.0.5     Git Object Database
gitpython         3.1.7     Python Git Library
isort             4.3.21    A Python utility / library to sort Python imports.
keyboard          0.13.5    Hook and simulate keyboard events on Windows and Linux
mccabe            0.6.1     McCabe checker, plugin for flake8
mypy              0.782     Optional static typing for Python
mypy-extensions   0.4.3     Experimental type system extensions for programs checked with the mypy typechecker.
pathspec          0.8.0     Utility library for gitignore style pattern matching of file paths.
pbr               5.4.5     Python Build Reasonableness
pycodestyle       2.6.0     Python style guide checker
pydocstyle        5.0.2     Python docstring style checker
pyflakes          2.2.0     passive checker of Python programs
pylama            7.7.1     pylama -- Code audit tool for python
python-dotenv     0.14.0    Add .env support to your django/flask apps in development and deployments
pyyaml            5.3.1     YAML parser and emitter for Python
regex             2020.7.14 Alternative regular expression module, to replace re.
six               1.15.0    Python 2 and 3 compatibility utilities
smmap             3.0.4     A pure Python implementation of a sliding window memory map manager
snowballstemmer   2.0.0     This package provides 26 stemmers for 25 languages generated from Snowball algorithms.
stevedore         3.2.0     Manage dynamic plugins for Python applications
toml              0.10.1    Python Library for Tom's Obvious, Minimal Language
typed-ast         1.4.1     a fork of Python 2 and 3 ast modules with type comment support
typing-extensions 3.7.4.2   Backported and Experimental Type Hints for Python 3.5+
vulture           1.6       Find dead code
```
then run my file
```sh
$ py idea_manager
Traceback (most recent call last):
  File "C:\Users\kir\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\kir\AppData\Local\Programs\Python\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "idea_manager\__main__.py", line 4, in <module>
    from dotenv import find_dotenv, load_dotenv
ModuleNotFoundError: No module named 'dotenv'
```
OOPS!
I tried add python-dotenv
```sh
$ poetry add python-dotenv

[ValueError]
Package python-dotenv is already present
```
OK!
I remove him!
```sh
$ poetry remove python-dotenv
Updating dependencies
Resolving dependencies...

Writing lock file

[RecursionError]
maximum recursion depth exceeded while calling a Python object
```
WHAT?

I want to show dependies
```sh
$ poetry show

[RecursionError]
maximum recursion depth exceeded
```

**WTF??**

**Comment by finswimmer** [comment]
Hello @peach-lasagna,

at the moment I cannot  tell you why there is an recursion error when you try to remove the package. But I can tell you something to your first point.

After running `poetry install` the packages get installed into a virtualenvironment. You have to run your program within that env.

This can be done in several ways:

1. Use `poetry run`

```
$ poetry run python idea_manager
````

`poetry` will create a new shell, activate the env there, runs the program and will close the shell when it's finished.

2. Use `poetry shell`

```
$ poetry shell
$ python idea_manager
```

Here `poetry` creates a new shell and activates the venv. Every command afterwards will be executed in the venv. To close the shell and the venv just type `exit`

3. Manually activate the venv

```
$ source .venv/bin/activate
$ python idea_manager
```

This uses the activation script by the venv to activate the venv. Every command afterwards will be executed in the venv. To deactivate the venv type `deactivate`.

fin swimmer

**Comment by peach-lasagna** [comment]
@finswimmer
Thanks so much!
```sh
$ poetry run python idea_manager
```
Helped me!.
