### ISSUE TITLE
[RecursionError] on first poetry install of tomlkit project

### ISSUE THREAD

**Issue by nat-n** [python-poetry/poetry#2763]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.14.6
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/sdispater/tomlkit/blob/1926311a71172b75fae1dea2cc6bccd103b32243/pyproject.toml

## Issue
I tried checking out [tomlkit](https://github.com/sdispater/tomlkit) (heard of it?) 

and then this happened:

```
poetry install -vvv
Using virtualenv: /Users/nat/Library/Caches/pypoetry/virtualenvs/tomlkit-xn8UEsS9-py3.6
The lock file might not be compatible with the current version of Poetry.
Upgrade Poetry to ensure the lock file is read properly or, alternatively, regenerate the lock file with the `poetry lock` command.
Installing dependencies from lock file

[RecursionError]
maximum recursion depth exceeded

Traceback (most recent call last):
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/nat/.poetry/lib/poetry/console/commands/install.py", line 69, in handle
    return_code = installer.run()
  File "/Users/nat/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/Users/nat/.poetry/lib/poetry/installation/installer.py", line 225, in _do_install
    ops = solver.solve(use_latest=whitelist)
  File "/Users/nat/.poetry/lib/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/Users/nat/.poetry/lib/poetry/puzzle/solver.py", line 187, in _solve
    e.constraints, use_latest=use_latest
  File "/Users/nat/.poetry/lib/poetry/puzzle/solver.py", line 154, in solve_in_compatibility_mode
    _packages, _depths = self._solve(use_latest=use_latest)

... several pages of the last same two lines repeating ...

  File "/Users/nat/.poetry/lib/poetry/puzzle/solver.py", line 181, in _solve
    self._package, self._provider, locked=locked, use_latest=use_latest
  File "/Users/nat/.poetry/lib/poetry/mixology/__init__.py", line 7, in resolve_version
    return solver.solve()
  File "/Users/nat/.poetry/lib/poetry/mixology/version_solver.py", line 80, in solve
    next = self._choose_package_version()
  File "/Users/nat/.poetry/lib/poetry/mixology/version_solver.py", line 388, in _choose_package_version
    version = self._provider.complete_package(version)
  File "/Users/nat/.poetry/lib/poetry/puzzle/provider.py", line 587, in complete_package
    repository=package.dependency.source_name,
  File "/Users/nat/.poetry/lib/poetry/repositories/pool.py", line 115, in package
    package = repo.package(name, version, extras=extras)
  File "/Users/nat/.poetry/lib/poetry/repositories/repository.py", line 40, in package
    return package.clone()
  File "/Users/nat/.poetry/lib/poetry/packages/package.py", line 427, in clone
    clone.python_versions = self.python_versions
  File "/Users/nat/.poetry/lib/poetry/packages/package.py", line 203, in python_versions
    create_nested_marker('python_version', self._python_constraint)
  File "/Users/nat/.poetry/lib/poetry/version/markers.py", line 725, in parse_marker
    markers = _coerce_parse_result(MARKER.parseString(marker))
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1943, in parseString
    loc, tokens = self._parse(instring, 0)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4069, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4052, in parseImpl
    loc, resultlist = self.exprs[0]._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4254, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4069, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4069, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4781, in parseImpl
    return super(ZeroOrMore, self).parseImpl(instring, loc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4697, in parseImpl
    loc, tokens = self_expr_parse(instring, loc, doActions, callPreParse=False)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4069, in parseImpl
    loc, exprtokens = e._parse(instring, loc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4052, in parseImpl
    loc, resultlist = self.exprs[0]._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4254, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4462, in parseImpl
    return self.expr._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4052, in parseImpl
    loc, resultlist = self.exprs[0]._parse(instring, loc, doActions, callPreParse=False)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4254, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1683, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 4254, in parseImpl
    ret = e._parse(instring, loc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 1687, in _parseNoCache
    loc, tokens = self.parseImpl(instring, preloc, doActions)
  File "/Users/nat/.poetry/lib/poetry/_vendor/py3.6/pyparsing.py", line 2893, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
```

I'm guess this indicates a bug to be fixed, but would also be interested in a work around if one is known.

**Comment by abn** [comment]
@nat-n `tomlkit` uses a lockfile generated by one of the `1.1.0` pre-releases of `poetry`. These are incompatible due to a change in the way the markers are read. Can you try using the latest pre-release?

**Comment by nat-n** [comment]
@abn Yes apparently it works with 1.1.0b2.
