### ISSUE TITLE
Circular dependencies / recursion depth (MVP example)

### ISSUE THREAD

**Issue by tony** [python-poetry/poetry#2781]
Potential duplicate of (search: ["maximum recursion"](https://github.com/python-poetry/poetry/issues?q=is%3Aissue+is%3Aopen+maximum+recursion)): #2555 #2376 #2329 #2138 #2138 #2008

If it is a duplicate, please feel free to close. Hopefully this gist example and debug log is helpful!

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.  - I am not 100% sure
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: WSL 2 + Ubuntu 20.04 + Python 2.7
- **Poetry version**: Poetry version 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/tony/439cfe08a9d36e90dac02a2f77296205

#### Config

```toml
[tool.poetry]
name = "test"
version = "0.0.1"
description = "test config"
authors = ["User <user@user.com>"]

[tool.poetry.dependencies]
python = "2.7 || ^3.5"
django-extensions = { version = "*", optional = true }

[tool.poetry.dev-dependencies]
django-extensions = [
  {version="<2.2.6", python="<3"},
  {version="*", python=">=3"}
]


[tool.poetry.extras]
test = ["django-extensions"]
```

Debug output: [bug.txt](https://github.com/python-poetry/poetry/files/5045719/bug.txt)

Debug snippet:

```
   0: Different requirements found for django-extensions (*) and django-extensions (<2.2.6).
   1: Version solving took 0.002 seconds.
   1: Tried 1 solutions.
   0: Retrying dependency resolution for Python (2.7 || >=3.5,<4.0).
   1: fact: test is 0.0.1
   1: derived: test
   0: Duplicate dependencies for django-extensions
   0: Different requirements found for django-extensions (*) and django-extensions (<2.2.6).
   1: Version solving took 0.002 seconds.
   1: Tried 1 solutions.
   0: Retrying dependency resolution for Python (2.7 || >=3.5,<4.0).
   1: fact: test is 0.0.1
   1: derived: test
   1: Version solving took 0.001 seconds.
   1: Tried 1 solutions.

[RecursionError]
maximum recursion depth exceeded

Traceback (most recent call last):
  File "/home/t/.poetry/lib/poetry/_vendor/py3.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/t/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/t/.poetry/lib/poetry/_vendor/py3.7/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/t/.poetry/lib/poetry/_vendor/py3.7/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/t/.poetry/lib/poetry/console/commands/install.py", line 69, in handle
    return_code = installer.run()
  File "/home/t/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/home/t/.poetry/lib/poetry/installation/installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "/home/t/.poetry/lib/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/home/t/.poetry/lib/poetry/puzzle/solver.py", line 187, in _solve
    e.constraints, use_latest=use_latest
  File "/home/t/.poetry/lib/poetry/puzzle/solver.py", line 154, in solve_in_compatibility_mode
    _packages, _depths = self._solve(use_latest=use_latest)
  File "/home/t/.poetry/lib/poetry/puzzle/solver.py", line 187, in _solve
    e.constraints, use_latest=use_latest
  File "/home/t/.poetry/lib/poetry/puzzle/solver.py", line 154, in solve_in_compatibility_mode
    _packages, _depths = self._solve(use_latest=use_latest)
  File "/home/t/.poetry/lib/poetry/puzzle/solver.py", line 187, in _solve
    e.constraints, use_latest=use_latest
  File "/home/t/.poetry/lib/poetry/puzzle/solver.py", line 154, in solve_in_compatibility_mode
    _packages, _depths = self._solve(use_latest=use_latest)
  File "/home/t/.poetry/lib/poetry/puzzle/solver.py", line 187, in _solve
    e.constraints, use_latest=use_latest
```

**Comment by abn** [comment]
@tony can you you try using the latest pre-release please? Once installed, I'd recommend regenerating the lock file. On an additional notes, lock files generated using `1.1.z` releases will not work with `1.0.z` releases due to changes in how environment markers are handled.

**Comment by tony** [comment]
@abn Thank you for your prompt reply!

This works correct with 1.1.0b2

```~/poetry-test ❯ poetry --version
Poetry version 1.1.0b2
~/poetry-test ❯ poetry install
Updating dependencies
Resolving dependencies... (0.9s)

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing django-extensions (3.0.5)
```

Works good:

```
~/poetry-test ❯ poetry install -vvv
Using virtualenv: /home/t/poetry-test/.venv
Updating dependencies
Resolving dependencies...
   1: fact: test is 0.0.1
   1: derived: test
   0: Duplicate dependencies for django-extensions
   0: Different requirements found for django-extensions (*) with markers * and django-extensions (<2.2.6) with markers python_version < "3".
   1: Version solving took 0.001 seconds.
   1: Tried 1 solutions.
   0: Retrying dependency resolution with the following overrides ({<Package test>: {'django-extensions': <Dependency django-extensions (*)>}}).
   1: fact: test is 0.0.1
   1: derived: test
   1: fact: test depends on django-extensions (*)
   1: selecting test (0.0.1)
   1: derived: django-extensions (*)
   1: fact: django-extensions (3.0.5) depends on typing (*)
   1: selecting django-extensions (3.0.5)
   1: derived: typing (*)
   1: selecting typing (3.7.4.3)
   1: Version solving took 0.010 seconds.
   1: Tried 1 solutions.
   0: Retrying dependency resolution with the following overrides ({<Package test>: {'django-extensions': <Dependency django-extensions (<2.2.6)>}}).
   1: fact: test is 0.0.1
   1: derived: test
   1: fact: test depends on django-extensions (<2.2.6)
   1: selecting test (0.0.1)
   1: derived: django-extensions (<2.2.6)
   1: fact: django-extensions (2.2.5) depends on six (>=1.2)
   1: fact: django-extensions (2.2.5) depends on typing (*)
   1: selecting django-extensions (2.2.5)
   1: derived: typing (*)
   1: derived: six (>=1.2)
   1: selecting typing (3.7.4.3)
   1: selecting six (1.15.0)
   1: Version solving took 0.007 seconds.
   1: Tried 1 solutions.
   0: Complete version solving took 0.019 seconds with 2 overrides
   0: Resolved with overrides: ({<Package test>: {'django-extensions': <Dependency django-extensions (*)>}}), ({<Package test>: {'django-extensions': <Dependency django-extensions (<2.2.6)>}})

Writing lock file

Finding the necessary packages for the current system

Package operations: 0 installs, 0 updates, 0 removals, 1 skipped

  • Installing django-extensions (3.0.5): Pending...
  • Installing django-extensions (3.0.5): Skipped for the following reason: Already installed
```

It looks like its solved in the next release, then.  I will close this issue for now

If you (or anyone else) would like to re-open please feel free!
