### ISSUE TITLE
poetry config: 'Keyring' object has no attribute 'name'

### ISSUE THREAD

**Issue by GvandeSteeg** [python-poetry/poetry#2790]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS Catalina 10.15.6
- **Poetry version**: 1.0.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/GvandeSteeg/9fdcd9691ea5dd0d9e4652b9ebf5547e

## Issue

I'm trying to set up poetry for my team's projects, having only learned about it a few weeks ago after always using venv, but when following the steps [here](https://python-poetry.org/docs/repositories/) to add a private pypi repository to our config I get the following error:
```python
poetry add entrypoint:v1.0.3_rc.1_2_g892939d_feature_fix_pypi_integration_2 -vvv

[AttributeError]
'Keyring' object has no attribute 'name'

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/command/command.py", line 163, in _do_handle
    self._dispatcher.dispatch(PRE_HANDLE, event)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/event/event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/usr/local/lib/python3.8/site-packages/clikit/api/event/event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "/usr/local/lib/python3.8/site-packages/poetry/console/config/application_config.py", line 89, in set_env
    poetry = command.poetry
  File "/usr/local/lib/python3.8/site-packages/poetry/console/commands/command.py", line 10, in poetry
    return self.application.poetry
  File "/usr/local/lib/python3.8/site-packages/poetry/console/application.py", line 49, in poetry
    self._poetry = Factory().create_poetry(Path.cwd())
  File "/usr/local/lib/python3.8/site-packages/poetry/factory.py", line 169, in create_poetry
    repository = self.create_legacy_repository(source, config)
  File "/usr/local/lib/python3.8/site-packages/poetry/factory.py", line 249, in create_legacy_repository
    credentials = password_manager.get_http_auth(name)
  File "/usr/local/lib/python3.8/site-packages/poetry/utils/password_manager.py", line 165, in get_http_auth
    password = self.keyring.get_password(name, username)
  File "/usr/local/lib/python3.8/site-packages/poetry/utils/password_manager.py", line 125, in keyring
    self._keyring = KeyRing("poetry-repository")
  File "/usr/local/lib/python3.8/site-packages/poetry/utils/password_manager.py", line 22, in __init__
    self._check()
  File "/usr/local/lib/python3.8/site-packages/poetry/utils/password_manager.py", line 90, in _check
    name = backend.name.split(" ")[0]
```

I added the repo with http-basic and it worked once, i.e. I was able to install packages from our pypi, but when I logged back in the next day it refuses to work.
The same error occurs when running `poetry config --list`

**Comment by abn** [comment]
@GvandeSteeg did the version of `keyring` channg in your python environment? Try `pip show keyring`.

**Comment by GvandeSteeg** [comment]
@abn 
```
pip show keyring
Name: keyring
Version: 9.3.1
Summary: Store and access your passwords safely.
Home-page: https://github.com/jaraco/keyring
Author: Jason R. Coombs
Author-email: jaraco@jaraco.com
License: UNKNOWN
Location: /Users/gvandestee/Library/Python/3.8/lib/python/site-packages
Requires:
Required-by: bonfire, poetry
```

**Comment by GvandeSteeg** [comment]
And that solves the issue! Sorry for wasting your time :rofl:

**Comment by abn** [comment]
No worries happy to help. :) You can use the installer `get-poetry.py` or use `pipx` to avoid this in the future.
