### ISSUE TITLE
Poetry on Windows 10 + pyenv-win is quickly corrupted

### ISSUE THREAD

**Issue by kiudee** [python-poetry/poetry#2795]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version (reason below).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10 (10.0.18362 Build 18362), German locale
- **Poetry version**: 1.1.0b2
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/kiudee/96f414e3564023b5576137ddf761675c

## Issue

I spent several days trying to install poetry on my Windows workstation (after already using it for months on my Linux PCs). After trying the following methods (which failed):
- Global python installation + PowerShell command
- pyenv-win + PowerShell command
- pyenv-win + pipx + poetry==1.0.10

I got poetry to work using:

0. Uninstalling global python and removing entries from PATH
1. Installing [pyenv-win 2.64.1](https://github.com/pyenv-win/pyenv-win/releases/tag/v2.64.2)
2. Installing python using `pyenv install 3.8.2` and `pyenv global 3.8.2`
3. Installing pipx using `pip install pipx`
4. Correctly adding all directories to PATH
5. Installing poetry using `pipx install poetry==1.1.0b2` (beta was required to get poetry to run - got the tip from another issue)

Running `poetry install` on a project worked once, but broke when trying again on another project.
So what already fails then is the following:

1. Create a new project using `poetry new blablub`
2. `poetry add tqdm` (or insert any other package here) fails with
```
  Command C:\Users\Karlson\AppData\Local\pypoetry\Cache\virtualenvs\blablub-HgamxXlr-py3.8\Scripts\pip.exe install --no-deps file://C:\Users\Karlson\AppData\Local\pypoetry\Cache\artifacts\be\98\c7\69fe6fea7a59659af1c6260899226129565330b1e07c9c5b3769be76bf\six-1.15.0-py2.py3-none-any.whl errored with the following return code 1, and output:
  Processing c:\users\karlson\appdata\local\pypoetry\cache\artifacts\be\98\c7\69fe6fea7a59659af1c6260899226129565330b1e07c9c5b3769be76bf\six-1.15.0-py2.py3-none-any.whl
      ERROR: Command errored out with exit status 1:
       command: 'C:\Users\Karlson\AppData\Local\pypoetry\Cache\virtualenvs\blablub-HgamxXlr-py3.8\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Karlson\\AppData\\Local\\Temp\\pip-req-build-mm0i0yyu\\setup.py'"'"'; __file__='"'"'C:\\Users\\Karlson\\AppData\\Local\\Temp\\pip-req-build-mm0i0yyu\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\Karlson\AppData\Local\Temp\pip-pip-egg-info-sly7kipr'
           cwd: C:\Users\Karlson\AppData\Local\Temp\pip-req-build-mm0i0yyu\
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "c:\users\karlson\.pyenv\pyenv-win\versions\3.8.2\lib\tokenize.py", line 392, in open
          buffer = _builtin_open(filename, 'rb')
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Karlson\\AppData\\Local\\Temp\\pip-req-build-mm0i0yyu\\setup.py'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```
Gist with the full debug output: https://gist.github.com/kiudee/70df85a30c7caed4156fc490d2569d02

Installing the same package in the pyenv environment using `pip install six` works perfectly fine.

Let me know if you need more information to debug the problem.

**Comment by sourkwhat** [comment]
I am experiencing the same issue. I'm not using pyenv or pipx though -- just a vanilla setup of python. Are there any workarounds?

**Comment by gwdekker** [comment]
I have a very similar experience when trying to let poetry work with multiple python versions on Windows
* In my experience, `pyenv-win` and `poetry` do not play nicely so I dropped that option - instead, having several pythons installed in Windows through the standard python.org Windows installers, added only one to PATH.
* Poetry 1.0.10 seems to work fine as long as you use the same python version poetry was installed with
* Poetry 1.0.10 crashes when trying `poetry env use`, as covered in issue #2698. This issue suggests using 1.1.0b2 instead. 
* Poetry 1.1.0b2 shows exactly the same instable behavior for me as experenced by OP.

**Comment by daddycocoaman** [comment]
Having the same issues with 1.1.0b2. Noticed the same stuff as @gwdekker . I've been able to deal with it by deleting the artifacts and cache folders in pypoetry cache folder but it's only good for one run so I end up deleting those folders anytime I want to `poetry add`.

**Comment by moochannel** [comment]
I think 1.1.0b2 have a problem that cannot use files under `cache-dir\artifacts` subfolders on installing packages.

```powershell
PS C:\Users\xxxxxxxx\tmp> poetry config --list
cache-dir = "C:\\Users\\xxxxxxxx\\AppData\\Local\\pypoetry\\Cache"
experimental.new-installer = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\xxxxxxxx\AppData\Local\pypoetry\Cache\virtualenvs


<<Delete all folders in cache-dir on Windows Explorer>>

PS C:\Users\xxxxxxxx\tmp> poetry init -n

This command will guide you through creating your pyproject.toml config.


You can specify a package in the following forms:
  - A single name (requests)
  - A name and a constraint (requests@^2.23.0)
  - A git url (git+https://github.com/python-poetry/poetry.git)
  - A git url with a revision (git+https://github.com/python-poetry/poetry.git#develop)
  - A file path (../my-package/my-package.whl)
  - A directory (../my-package/)
  - A url (https://example.com/packages/my-package-0.1.0.tar.gz)

PS C:\Users\xxxxxxxx\tmp> poetry add whitenoise
Creating virtualenv tmp in C:\Users\xxxxxxxx\tmp\.venv
Using version ^5.2.0 for whitenoise

Updating dependencies
Resolving dependencies...

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing whitenoise (5.2.0)


<<Delete .venv folder>>

PS C:\Users\xxxxxxxx\tmp> poetry install
Creating virtualenv tmp in C:\Users\xxxxxxxx\tmp\.venv
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing whitenoise (5.2.0)

  EnvCommandError

  Command C:\Users\xxxxxxxx\tmp\.venv\Scripts\pip.exe install --no-deps file://C:\Users\xxxxxxxx\AppData\Local\pypoetry\Cache\artifacts\85\9d\ae\96bb78abce27b6862969fd9e72817c63580afa169b43960b46f8819c6e\whitenoise-5.2.0-py2.py3-none-any.whl errored with the following return code 1, and output:
  Processing c:\users\xxxxxxxx\appdata\local\pypoetry\cache\artifacts\85\9d\ae\96bb78abce27b6862969fd9e72817c63580afa169b43960b46f8819c6e\whitenoise-5.2.0-py2.py3-none-any.whl
      ERROR: Command errored out with exit status 1:
       command: 'C:\Users\xxxxxxxx\tmp\.venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\pip-req-build-yurhhnob\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\pip-req-build-yurhhnob\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xxxxxxxx\AppData\Local\Temp\pip-pip-egg-info-6ytz8mwk'
           cwd: C:\Users\xxxxxxxx\AppData\Local\Temp\pip-req-build-yurhhnob\
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Program Files\Python38\lib\tokenize.py", line 392, in open
          buffer = _builtin_open(filename, 'rb')
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\pip-req-build-yurhhnob\\setup.py'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
  You should consider upgrading via the 'C:\Users\xxxxxxxx\tmp\.venv\Scripts\python.exe -m pip install --upgrade pip' command.


  at ~\.poetry\lib\poetry\utils\env.py:915 in _run
       911│                 output = subprocess.check_output(
       912│                     cmd, stderr=subprocess.STDOUT, **kwargs
       913│                 )
       914│         except CalledProcessError as e:
    →  915│             raise EnvCommandError(e, input=input_)
       916│
       917│         return decode(output)
       918│
       919│     def execute(self, bin, *args, **kwargs):


<<Delete whl file of whitenoise from cache-dir\artifacts (C:\Users\xxxxxxxx\AppData\Local\pypoetry\Cache\artifacts\85\9d\ae\96bb78abce27b6862969fd9e72817c63580afa169b43960b46f8819c6e\whitenoise-5.2.0-py2.py3-none-any.whl)>>
<<Delete .venv folder>>

PS C:\Users\xxxxxxxx\tmp> poetry install
Creating virtualenv tmp in C:\Users\xxxxxxxx\tmp\.venv
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing whitenoise (5.2.0)
```

```
pip.exe install --no-deps file://C:\Users\xxxxxx
                          ^^^^^^^
```

The protocol part on file path causes error. I think it should be removed.

```powershell
<<Delete .venv folder>>

PS C:\Users\xxxxxxxx\tmp> poetry env use 'C:\Program Files\Python38\python.exe'
Creating virtualenv tmp in C:\Users\xxxxxxxx\tmp\.venv
Using virtualenv: C:\Users\xxxxxxxx\tmp\.venv


PS C:\Users\xxxxxxxx\tmp> poetry run pip install --no-deps file://C:\Users\xxxxxxxx\AppData\Local\pypoetry\Cache\artifacts\85\9d\ae\96bb78abce27b6862969fd9e72817c63580afa169b43960b46f8819c6e\whitenoise-5.2.0-py2.py3-none-any.whl
Processing c:\users\xxxxxxxx\appdata\local\pypoetry\cache\artifacts\85\9d\ae\96bb78abce27b6862969fd9e72817c63580afa169b43960b46f8819c6e\whitenoise-5.2.0-py2.py3-none-any.whl
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\xxxxxxxx\tmp\.venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\pip-req-build-uxjv2y01\\setup.py'"'"'; __file__='"'"'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\pip-req-build-uxjv2y01\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\xxxxxxxx\AppData\Local\Temp\pip-pip-egg-info-yn8xqocx'
         cwd: C:\Users\xxxxxxxx\AppData\Local\Temp\pip-req-build-uxjv2y01\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Program Files\Python38\lib\tokenize.py", line 392, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\xxxxxxxx\\AppData\\Local\\Temp\\pip-req-build-uxjv2y01\\setup.py'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the 'C:\Users\xxxxxxxx\tmp\.venv\Scripts\python.exe -m pip install --upgrade pip' command.


PS C:\Users\xxxxxxxx\tmp> poetry run pip install --no-deps C:\Users\xxxxxxxx\AppData\Local\pypoetry\Cache\artifacts\85\9d\ae\96bb78abce27b6862969fd9e72817c63580afa169b43960b46f8819c6e\whitenoise-5.2.0-py2.py3-none-any.whl
Processing c:\users\xxxxxxxx\appdata\local\pypoetry\cache\artifacts\85\9d\ae\96bb78abce27b6862969fd9e72817c63580afa169b43960b46f8819c6e\whitenoise-5.2.0-py2.py3-none-any.whl
Installing collected packages: whitenoise
Successfully installed whitenoise-5.2.0
WARNING: You are using pip version 20.1.1; however, version 20.2.2 is available.
You should consider upgrading via the 'C:\Users\xxxxxxxx\tmp\.venv\Scripts\python.exe -m pip install --upgrade pip' command.
```

**Comment by tiaradwiputri** [comment]
Hi, wondering if there's any follow up on this issue? Had the same problem.

**Comment by jessekrubin** [comment]
@JayDoubleu is correct, that this is SUPER annoying.

**Comment by neersighted** [comment]
This does not reproduce for me with Python 3.10 + Poetry 1.2.x -- reproductions on a Python.org-sourced Python install would be very valuable. Until then I am closing this as there is no consistent reproduction.
