### ISSUE TITLE
UnexpectedCharError when executing poetry commands

### ISSUE THREAD

**Issue by andymcarter** [python-poetry/poetry#2838]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **MacOS 10.15.5, python 3.8.3**: 
- **1.0.10**: 
- **gist: https://gist.github.com/andymcarter/10bc0073468b1a4c13611b7b7523fdd1**: 

## Issue
Almost any `poetry` commands suddenly result in an UnexpectedCharError, so unable to add packages to existing environments or create new environments. Have installed latest poetry beta to try and solve the issue but no luck. Even a very basic pyproject.toml file causes this issue.

```python-traceback
[UnexpectedCharError]
Unexpected character: u'\n' at line 4 col 5

Traceback (most recent call last):
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/clikit/api/command/command.py", line 163, in _do_handle
    self._dispatcher.dispatch(PRE_HANDLE, event)
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/clikit/api/event/event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/clikit/api/event/event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "/Users/andycarter/.poetry/lib/poetry/console/config/application_config.py", line 92, in set_env
    env = env_manager.create_venv(io)
  File "/Users/andycarter/.poetry/lib/poetry/utils/env.py", line 490, in create_venv
    env = self.get(reload=True)
  File "/Users/andycarter/.poetry/lib/poetry/utils/env.py", line 314, in get
    envs = envs_file.read()
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/tomlkit/toml_file.py", line 20, in read
    return loads(f.read())
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/tomlkit/api.py", line 34, in loads
    return parse(string)
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/tomlkit/api.py", line 51, in parse
    return Parser(string).parse()
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/tomlkit/parser.py", line 153, in parse
    key, value = self._parse_table()
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/tomlkit/parser.py", line 1056, in _parse_table
    item = self._parse_item()
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/tomlkit/parser.py", line 302, in _parse_item
    return self._parse_key_value(True)
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/tomlkit/parser.py", line 387, in _parse_key_value
    val = self._parse_value()
  File "/Users/andycarter/.poetry/lib/poetry/_vendor/py2.7/tomlkit/parser.py", line 602, in _parse_value
    raise self.parse_error(UnexpectedCharError, c)
```

**Comment by finswimmer** [comment]
Hello @andymcarter,

I'm unable to reproduce this. Can you upload somewhere an original `pyproject.toml` with which it doesn't work? Or does this also happens with a new one created by `poetry init -n`?

fin swimmer

**Comment by andymcarter** [comment]
This was a new pyproject.toml, but I suspect it is something with my
installation as it seems to be affecting all my poetry managed envs.

Even with the verbose output I can't track down what might be the cause,
just wondered if that specific error rang any bells with anyone else.

**Comment by andymcarter** [comment]
I think I've found the solution, somehow `envs.toml` in my virtualenvs folder had been edited to look like this.

![image](https://user-images.githubusercontent.com/22293319/90867412-3fe3a980-e38d-11ea-868f-67551d0612b5.png)

Removing the offending line on 4 and the duplicate key got me back working.
