### ISSUE TITLE
Dependency is not installed before so install fails

### ISSUE THREAD

**Issue by Cilyan** [python-poetry/poetry#2890]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Linux 5.8.4-200.fc32.x86_64 (Fedora 32)**: 
- **Poetry version 1.0.10**: 
- **See project.toml file below**: 
- **Python 3.8.5**

## Issue

I want to use Poetry in my next simple project. This is a simple website based on Flask. But after a simple `poetry init` to configure the project and add Flask to the dependencies, the `poetry install` fails. It seems that the `setup.py` of requests requires `chardet`. This dependency is properly listed in the requests setup.py but poetry doesn't install it, or decides to install it later. As such, the install fails. This is quite surprising.

```sh
[***@*** myproject]$ poetry init

...

Generated file

[tool.poetry]
name = "myproject"
version = "0.1.0"
description = "******"
authors = ["*** *** <***.***@***.com>"]

[tool.poetry.dependencies]
python = "^3.6"
flask = "^1.1.2"
flask-googlelogin = "^0.3.1"
python-decouple = "^3.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"


Do you confirm generation? (yes/no) [yes] 
[***@*** myproject]$ poetry install
Creating virtualenv myproject-ZQvAPwMg-py3.8 in /home/***/.cache/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (3.2s)

Writing lock file


Package operations: 10 installs, 0 updates, 0 removals

  - Installing markupsafe (1.1.1)
  - Installing click (7.1.2)
  - Installing itsdangerous (1.1.0)
  - Installing jinja2 (2.11.2)
  - Installing werkzeug (1.0.1)
  - Installing flask (1.1.2)
  - Installing flask-login (0.2.11)
  - Installing requests (0.14.2)

[EnvCommandError]
Command ['/home/***/.cache/pypoetry/virtualenvs/myproject-ZQvAPwMg-py3.8/bin/pip', 'install', '--no-deps', 'requests==0.14.2'] errored with the following return code 1, and output: 
Collecting requests==0.14.2
  Downloading https://files.pythonhosted.org/packages/fa/d1/0dd60e1146e79e7b193e7b0189d8c13ef100d55cbfe65e1825ac5f03c397/requests-0.14.2.tar.gz (361kB)
    ERROR: Command errored out with exit status 1:
     command: /home/***/.cache/pypoetry/virtualenvs/myproject-ZQvAPwMg-py3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-w_2rqenq/requests/setup.py'"'"'; __file__='"'"'/tmp/pip-install-w_2rqenq/requests/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-w_2rqenq/requests/pip-egg-info
         cwd: /tmp/pip-install-w_2rqenq/requests/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-w_2rqenq/requests/setup.py", line 6, in <module>
        import requests
      File "/tmp/pip-install-w_2rqenq/requests/requests/__init__.py", line 52, in <module>
        from . import utils
      File "/tmp/pip-install-w_2rqenq/requests/requests/utils.py", line 22, in <module>
        from .compat import parse_http_list as _parse_list_header
      File "/tmp/pip-install-w_2rqenq/requests/requests/compat.py", line 112, in <module>
        from .packages import chardet2 as chardet
    ImportError: cannot import name 'chardet2' from 'requests.packages' (/tmp/pip-install-w_2rqenq/requests/requests/packages/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

[***@*** myproject]$ poetry install -vvv
Using virtualenv: /home/***/.cache/pypoetry/virtualenvs/myproject-ZQvAPwMg-py3.8
Installing dependencies from lock file


Package operations: 3 installs, 0 updates, 0 removals, 7 skipped

  - Skipping markupsafe (1.1.1) Already installed
  - Skipping click (7.1.2) Already installed
  - Skipping itsdangerous (1.1.0) Already installed
  - Skipping jinja2 (2.11.2) Already installed
  - Skipping werkzeug (1.0.1) Already installed
  - Skipping flask (1.1.2) Already installed
  - Skipping flask-login (0.2.11) Already installed
  - Installing requests (0.14.2)

[EnvCommandError]
Command ['/home/***/.cache/pypoetry/virtualenvs/myproject-ZQvAPwMg-py3.8/bin/pip', 'install', '--no-deps', 'requests==0.14.2'] errored with the following return code 1, and output: 
Collecting requests==0.14.2
  Using cached https://files.pythonhosted.org/packages/fa/d1/0dd60e1146e79e7b193e7b0189d8c13ef100d55cbfe65e1825ac5f03c397/requests-0.14.2.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /home/***/.cache/pypoetry/virtualenvs/myproject-ZQvAPwMg-py3.8/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-dp9kl0ho/requests/setup.py'"'"'; __file__='"'"'/tmp/pip-install-dp9kl0ho/requests/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-dp9kl0ho/requests/pip-egg-info
         cwd: /tmp/pip-install-dp9kl0ho/requests/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-dp9kl0ho/requests/setup.py", line 6, in <module>
        import requests
      File "/tmp/pip-install-dp9kl0ho/requests/requests/__init__.py", line 52, in <module>
        from . import utils
      File "/tmp/pip-install-dp9kl0ho/requests/requests/utils.py", line 22, in <module>
        from .compat import parse_http_list as _parse_list_header
      File "/tmp/pip-install-dp9kl0ho/requests/requests/compat.py", line 112, in <module>
        from .packages import chardet2 as chardet
    ImportError: cannot import name 'chardet2' from 'requests.packages' (/tmp/pip-install-dp9kl0ho/requests/requests/packages/__init__.py)
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
WARNING: You are using pip version 19.3.1; however, version 20.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.


Traceback (most recent call last):
  File "/home/***/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/***/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/***/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/***/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/***/.poetry/lib/poetry/console/commands/install.py", line 69, in handle
    return_code = installer.run()
  File "/home/***/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/home/***/.poetry/lib/poetry/installation/installer.py", line 286, in _do_install
    self._execute(op)
  File "/home/***/.poetry/lib/poetry/installation/installer.py", line 302, in _execute
    getattr(self, "_execute_{}".format(method))(operation)
  File "/home/***/.poetry/lib/poetry/installation/installer.py", line 327, in _execute_install
    self._installer.install(operation.package)
  File "/home/***/.poetry/lib/poetry/installation/pip_installer.py", line 96, in install
    self.run(*args)
  File "/home/***/.poetry/lib/poetry/installation/pip_installer.py", line 127, in run
    return self._env.run_pip(*args, **kwargs)
  File "/home/***/.poetry/lib/poetry/utils/env.py", line 884, in run_pip
    return self._run(cmd, **kwargs)
  File "/home/***/.poetry/lib/poetry/utils/env.py", line 1112, in _run
    return super(VirtualEnv, self)._run(cmd, **kwargs)
  File "/home/***/.poetry/lib/poetry/utils/env.py", line 916, in _run
    raise EnvCommandError(e, input=input_)

[***@*** myproject]$ 
```

**Comment by Cilyan** [comment]
My bad, this is an issue with GoogleLogin. I did not realize this project was that old... Silly me. Sorry !
