### ISSUE TITLE
poetry add python-dotenv => Invalid requirement, parse error at "'ids (==0'"

### ISSUE THREAD

**Issue by everetr** [python-poetry/poetry#2894]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Kubuntu 18.04.5
- **Poetry version**: 1.0.10
- **Contents of your pyproject.toml file**:

```
[tool.poetry]
name = "my_project"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Issue

When I try to add the [python-dotenv](https://pypi.org/project/python-dotenv/) package as a main dependency, I get error: `Invalid requirement, parse error at "'ids (==0'"`. Possibly related to #1772.

Here's the full output when I run `poetry add -vvv python-dotenv`:

```sh
Using virtualenv: /home/username/.cache/pypoetry/virtualenvs/my_project-stekY1tQ-py3.8
PyPI: 32 packages found for python-dotenv *
Using version ^0.14.0 for python-dotenv

Updating dependencies
Resolving dependencies...
   1: fact: my_project is 0.1.0
   1: derived: my_project
   1: Version solving took 0.003 seconds.
   1: Tried 1 solutions.

[InvalidRequirement]
Invalid requirement, parse error at "'ids (==0'"

Traceback (most recent call last):
  File "/home/username/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/username/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/username/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/username/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/username/.poetry/lib/poetry/console/commands/add.py", line 156, in handle
    status = installer.run()
  File "/home/username/.poetry/lib/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/home/username/.poetry/lib/poetry/installation/installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "/home/username/.poetry/lib/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/home/username/.poetry/lib/poetry/puzzle/solver.py", line 180, in _solve
    result = resolve_version(
  File "/home/username/.poetry/lib/poetry/mixology/__init__.py", line 7, in resolve_version
    return solver.solve()
  File "/home/username/.poetry/lib/poetry/mixology/version_solver.py", line 80, in solve
    next = self._choose_package_version()
  File "/home/username/.poetry/lib/poetry/mixology/version_solver.py", line 391, in _choose_package_version
    for incompatibility in self._provider.incompatibilities_for(version):
  File "/home/username/.poetry/lib/poetry/puzzle/provider.py", line 561, in incompatibilities_for
    return [
  File "/home/username/.poetry/lib/poetry/puzzle/provider.py", line 563, in <listcomp>
    [Term(package.to_dependency(), True), Term(dep, False)],
  File "/home/username/.poetry/lib/poetry/packages/project_package.py", line 26, in to_dependency
    dependency = super(ProjectPackage, self).to_dependency()
  File "/home/username/.poetry/lib/poetry/packages/package.py", line 410, in to_dependency
    return dependency_from_pep_508(name)
  File "/home/username/.poetry/lib/poetry/packages/__init__.py", line 39, in dependency_from_pep_508
    req = Requirement(name)
  File "/home/username/.poetry/lib/poetry/version/requirements.py", line 210, in __init__
    raise InvalidRequirement(

```

**Comment by finswimmer** [comment]
Hello @everetr,

can you try this with the latest prerelease (1.1.0b2) please. I'm not able to reproduce the issue there.

fin swimmer

**Comment by RixzZ** [comment]
I had this same problem. It seems it only happens when you have a whitespace in the value of 'name' in the pyproject.toml.
