### ISSUE TITLE
Poetry 1.1.0b2 fails to install zipp when trying to install poetry-core

### ISSUE THREAD

**Issue by Celeborn2BeAlive** [python-poetry/poetry#2911]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.0b2
- pyproject.toml file: https://github.com/python-poetry/poetry-core/blob/master/pyproject.toml

## Issue

I was trying to update a pull request of mine and required a dev version of poetry-core, so I tried installing it with poetry 1.1.0b2, got this error for zipp

```
  • Installing zipp (1.2.0): Pending...
  • Installing zipp (1.2.0): Installing...
  • Installing zipp (1.2.0): Failed

  EnvCommandError

  Command D:\projects\open_source_contrib\poetry-core\.venv\Scripts\pip.exe install --no-deps file://C:\Users\laure\AppData\Local\pypoetry\Cache\artifacts\96\15\17\6dc4596b5827e94647f
1e4e7362bec368fcdda2100141109ada8a1e3dd\zipp-1.2.0-py2.py3-none-any.whl errored with the following return code 1, and output:
  Processing c:\users\laure\appdata\local\pypoetry\cache\artifacts\96\15\17\6dc4596b5827e94647f1e4e7362bec368fcdda2100141109ada8a1e3dd\zipp-1.2.0-py2.py3-none-any.whl
      ERROR: Command errored out with exit status 1:
       command: 'D:\projects\open_source_contrib\poetry-core\.venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\laure\\scoop\\apps\\msys2\\current\\tmp\\pip-req-build-xyaj9k4t\\setup.py'"'"'; __file__='"'"'C:\\Users\\laure\\scoop\\apps\\msys2\\current\\tmp\\pip-req-build-xyaj9k4t\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\laure\scoop\apps\msys2\current\tmp\pip-pip-egg-info-tc7ro9mf'
           cwd: C:\Users\laure\scoop\apps\msys2\current\tmp\pip-req-build-xyaj9k4t\
      Complete output (5 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "C:\Users\laure\.pyenv\pyenv-win\versions\3.7.6-amd64\lib\tokenize.py", line 447, in open
          buffer = _builtin_open(filename, 'rb')
      FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\laure\\scoop\\apps\\msys2\\current\\tmp\\pip-req-build-xyaj9k4t\\setup.py'
      ----------------------------------------
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
  You should consider upgrading via the 'D:\projects\open_source_contrib\poetry-core\.venv\Scripts\python.exe -m pip install --upgrade pip' command.
  

  at c:\users\laure\.local\pipx\venvs\poetry-pre\lib\site-packages\poetry\utils\env.py:915 in _run
       911│                 output = subprocess.check_output(
       912│                     cmd, stderr=subprocess.STDOUT, **kwargs     
       913│                 )
       914│         except CalledProcessError as e:
    →  915│             raise EnvCommandError(e, input=input_
)
       916│
       917│         return decode(output)
       918│
       919│     def execute(self, bin, *args, **kwargs
):
```

**Comment by Celeborn2BeAlive** [comment]
It also fails with
- 1.1.0b1
- 1.1.0a3

But it works with 1.1.0a2 !

**Comment by abn** [comment]
@Celeborn2BeAlive I believe this might have to do with something related to #2666 (`1.1.0b1`) if anything.

The issue here does not seem to be poetry related. The curious part is this.
```console
Command D:\projects\open_source_contrib\poetry-core\.venv\Scripts\pip.exe install --no-deps file://C:\Users\laure\AppData\Local\pypoetry\Cache\artifacts\96\15\17\6dc4596b5827e94647f
1e4e7362bec368fcdda2100141109ada8a1e3dd\zipp-1.2.0-py2.py3-none-any.whl errored with the following return code 1, and output:
```

The above indicates poetry did its job, downloaded the wheel, passed it into pip for install. The command output, also indicates pip is failing.
```console
  Processing c:\users\laure\appdata\local\pypoetry\cache\artifacts\96\15\17\6dc4596b5827e94647f1e4e7362bec368fcdda2100141109ada8a1e3dd\zipp-1.2.0-py2.py3-none-any.whl
      ERROR: Command errored out with exit status 1:
       command: 'D:\projects\open_source_contrib\poetry-core\.venv\Scripts\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\laure\\scoop\\apps\\msys2\\current\\tmp\\pip-req-build-xyaj9k4t\\setup.py'"'"'; __file__='"'"'C:\\Users\\laure\\scoop\\apps\\msys2\\current\\tmp\\pip-req-build-xyaj9k4t\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\laure\scoop\apps\msys2\current\tmp\pip-pip-egg-info-tc7ro9mf'
           cwd: C:\Users\laure\scoop\apps\msys2\current\tmp\pip-req-build-xyaj9k4t\
```

I am curious what happens when you manually try the above command using the pip installed in your `.venv`.
