### ISSUE TITLE
ModuleNotFoundError: No module named 'cleo'

### ISSUE THREAD

**Issue by thoward27** [python-poetry/poetry#2991]
- Docker: python 3.8.5
- poetry 1.0.5

## Issue

All of a sudden I'm seeing failures while trying to use poetry. Dockerfiles have not changed, but they're suddenly unable to build.

Example Dockerfile: 

```
from python:3.8.5
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/1.0.5/get-poetry.py | python > /dev/null
ENV PATH="/root/.poetry/bin:$PATH"
RUN poetry config -vvv virtualenvs.create false
```

Resulting error:

```
 > [3/3] RUN poetry config -vvv virtualenvs.create false:                                                                                                                                
#6 0.261 Traceback (most recent call last):                                                                                                                                              
#6 0.261   File "/root/.poetry/bin/poetry", line 12, in <module>                                                                                                                         
#6 0.261     from poetry.console import main                                                                                                                                             
#6 0.261   File "/root/.poetry/lib/poetry/console/__init__.py", line 1, in <module>                                                                                                      
#6 0.261     from .application import Application
#6 0.261   File "/root/.poetry/lib/poetry/console/application.py", line 3, in <module>
#6 0.261     from cleo import Application as BaseApplication
#6 0.261 ModuleNotFoundError: No module named 'cleo'
```

I'm seeing this same error across repositories, versions of python, and even different computers.

**Comment by abn** [comment]
@thoward27 I do not think you command does what you intend it to do. I am assuming that you want to install poetry at `1.0.5`. For this you have to do.

```Dockefile
from python:3.8.5
RUN curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/1.0.5/get-poetry.py | python - --version 1.0.5 > /dev/null
ENV PATH="/root/.poetry/bin:$PATH"
RUN poetry config -vvv virtualenvs.create false
```

The snippet you provided will try to install `1.1.0rc1` using the `get-poetry.py` script at `1.0.5`. It is recommended that you always use the latest `get-poetry.py` script. Additionally, unless there is a pressing reason why you need `1.0.5`, I'd recommend using the latest stable version.
