### ISSUE TITLE
1.1.0 Does not resolve paths in dependencies correctly

### ISSUE THREAD

**Issue by ginty** [python-poetry/poetry#3062]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Ubuntu**: 
- **1.1.0**: 

## Issue

First off, thanks for all the work on Poetry, it's shaping up to be a great tool and the speed improvements to package installation
in 1.1.0 look great.

I do see the following regression though vs 1.0.10:

I have an application comprised of 3 packages which are organized like this in my workspace:

~~~
common_pkg/
  pyproject.toml
apps/
  parent_pkg/
    pyproject.toml
  child_pkg/
    pyproject.toml
~~~

The pyproject.tomls are setup like this:

~~~toml
# apps/parent_pkg/pyproject.toml
[tool.poetry.dependencies]
common_pkg = { path = "../../common_pkg" }
child_pkg = { path = "../child_pkg" }

# apps/child_pkg/pyproject.toml
[tool.poetry.dependencies]
common_pkg = { path = "../../common_pkg" }
~~~

When working in the `child_app` everything works fine, the path to the `common_pkg` is correctly resolved.

However, when working in the `parent_app`, the path to the `common_pkg` within the `child_app` is not resolved correctly and the installation fails.
I'm not sure what's going on because the error message only prints out the relative path argument that I've supplied and not the full absolute path that it has resolved.

Here is the complete error message:

~~~
...
  • Installing child_pkg (0.1.0 /home/stephen/Code/github/o2/apps/child_pkg): Failed

  EnvCommandError

  Command ['/home/stephen/.cache/pypoetry/virtualenvs/example-SlMy6f3g-py3.6/bin/pip', 'install', '--no-deps', '-U', '/home/stephen/Code/github/o2/apps/child_pkg'] errored with the following return code 1, and output:
  Processing /home/stephen/Code/github/o2/apps/child_pkg
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /home/stephen/.cache/pypoetry/virtualenvs/example-SlMy6f3g-py3.6/bin/python /home/stephen/.cache/pypoetry/virtualenvs/example-SlMy6f3g-py3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpc3v5v8xh
           cwd: /tmp/pip-req-build-ep07tmh3
      Complete output (16 lines):
      Traceback (most recent call last):
        File "/home/stephen/.cache/pypoetry/virtualenvs/example-SlMy6f3g-py3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/home/stephen/.cache/pypoetry/virtualenvs/example-SlMy6f3g-py3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/stephen/.cache/pypoetry/virtualenvs/example-SlMy6f3g-py3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-ifd1r9rs/overlay/lib/python3.6/site-packages/poetry/core/masonry/api.py", line 34, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve())
        File "/tmp/pip-build-env-ifd1r9rs/overlay/lib/python3.6/site-packages/poetry/core/factory.py", line 91, in create_poetry
          self.create_dependency(name, constraint, root_dir=package.root_dir)
        File "/tmp/pip-build-env-ifd1r9rs/overlay/lib/python3.6/site-packages/poetry/core/factory.py", line 249, in create_dependency
          extras=constraint.get("extras", []),
        File "/tmp/pip-build-env-ifd1r9rs/overlay/lib/python3.6/site-packages/poetry/core/packages/directory_dependency.py", line 36, in __init__
          raise ValueError("Directory {} does not exist".format(self._path))
      ValueError: Directory ../../common_pkg does not exist
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /home/stephen/.cache/pypoetry/virtualenvs/example-SlMy6f3g-py3.6/bin/python /home/stephen/.cache/pypoetry/virtualenvs/example-SlMy6f3g-py3.6/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpc3v5v8xh Check the logs for full command output.
~~~

**Comment by abn** [comment]
With `1.1.0` Poetry no longer defaults to `develop = true` for path dependencies.

Please refer to https://python-poetry.org/blog/announcing-poetry-1-1-0.html#directory-dependencies-are-now-non-editable-by-default

In your case poetry attempts a PEP 517 build of your dependency, but since thats are relative files required for the build are not correctly copied, causing the error.

**Comment by ginty** [comment]
Thanks a lot @abn, works perfect now!
