### ISSUE TITLE
Using path dependency on a package that also uses path dependency breaks

### ISSUE THREAD

**Issue by mr-bjerre** [python-poetry/poetry#3082]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Catalina 10.15.7
- **Poetry version**: 1.0.0

## Issue

Imagine a folder structure like this

```
├── libs
│   ├── BaseLib
│   │   ├── README.rst
│   │   ├── baselib
│   │   │   └── __init__.py
│   │   ├── poetry.lock
│   │   ├── pyproject.toml
│   │   └── tests
│   │       ├── __init__.py
│   │       └── test_baselib.py
│   └── DependentLib
│       ├── README.rst
│       ├── dependentlib
│       │   └── __init__.py
│       ├── poetry.lock
│       ├── pyproject.toml
│       └── tests
│           ├── __init__.py
│           └── test_dependentlib.py
└── services
    └── DependentService
        ├── README.rst
        ├── dependentservice
        │   └── __init__.py
        ├── poetry.lock
        ├── pyproject.toml
        └── tests
            ├── __init__.py
            └── test_dependentservice.py
```

The `libs/BaseLib/pyproject.toml` is just plain

```toml
[tool.poetry]
name = "BaseLib"
version = "0.1.0"
description = ""
authors = ["John Doe <john@doe.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

The `libs/DependentLib/pyproject.toml` have a path dependency (depends on BaseLib). Running `poetry install` works just fine.

```toml
[tool.poetry]
name = "DependentLib"
version = "0.1.0"
description = ""
authors = ["John Doe <john@doe.com>"]

[tool.poetry.dependencies]
python = "^3.8"
baselib = {path = "../BaseLib"}

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

But now to the issue. Lets say `services/DependentService/pyproject.toml` is plain as well and now I `cd` into `services/DependentService`. Then I can run `poetry add ../../libs/BaseLib` just fine BUT I get an error when I run the following

```
poetry add ../../libs/DependentLib -vvv
```

#### Output

```
Creating virtualenv dependentservice-OpJeHZVV-py3.8 in /Users/nixd/Library/Caches/pypoetry/virtualenvs
Using virtualenv: /Users/nixd/Library/Caches/pypoetry/virtualenvs/dependentservice-OpJeHZVV-py3.8

Updating dependencies
Resolving dependencies...
   1: fact: dependentservice is 0.1.0
   1: derived: dependentservice
   1: fact: dependentservice depends on baselib (0.1.0 ../../libs/BaseLib)
   1: fact: dependentservice depends on dependentlib (0.1.0 ../../libs/DependentLib)
   1: fact: dependentservice depends on pytest (^5.2)
   1: fact: dependentservice depends on pytest (^5.2)
   1: selecting dependentservice (0.1.0)
   1: derived: pytest (^5.2)
   1: derived: dependentlib (0.1.0 ../../libs/DependentLib)
   1: derived: baselib (0.1.0 ../../libs/BaseLib)
   1: fact: pytest (5.4.3) depends on py (>=1.5.0)
   1: fact: pytest (5.4.3) depends on packaging (*)
   1: fact: pytest (5.4.3) depends on attrs (>=17.4.0)
   1: fact: pytest (5.4.3) depends on more-itertools (>=4.0.0)
   1: fact: pytest (5.4.3) depends on pluggy (>=0.12,<1.0)
   1: fact: pytest (5.4.3) depends on wcwidth (*)
   1: fact: pytest (5.4.3) depends on atomicwrites (>=1.0)
   1: fact: pytest (5.4.3) depends on colorama (*)
   1: selecting pytest (5.4.3)
   1: derived: colorama (*)
   1: derived: atomicwrites (>=1.0)
   1: derived: wcwidth (*)
   1: derived: pluggy (>=0.12,<1.0)
   1: derived: more-itertools (>=4.0.0)
   1: derived: attrs (>=17.4.0)
   1: derived: packaging (*)
   1: derived: py (>=1.5.0)
   1: fact: dependentlib (0.1.0 /Users/nixd/Projects/MiniExamples/root/libs/DependentLib) depends on baselib (0.1.0 ../BaseLib)
   1: selecting dependentlib (0.1.0 /Users/nixd/Projects/MiniExamples/root/libs/DependentLib)
   1: selecting baselib (0.1.0 /Users/nixd/Projects/MiniExamples/root/libs/BaseLib)
   1: selecting colorama (0.4.3)
   1: selecting atomicwrites (1.4.0)
   1: selecting wcwidth (0.2.5)
   1: selecting pluggy (0.13.1)
   1: selecting more-itertools (8.5.0)
   1: selecting attrs (20.2.0)
   1: fact: packaging (20.4) depends on pyparsing (>=2.0.2)
   1: fact: packaging (20.4) depends on six (*)
   1: selecting packaging (20.4)
   1: derived: six (*)
   1: derived: pyparsing (>=2.0.2)
   1: selecting py (1.9.0)
   1: selecting six (1.15.0)
   1: selecting pyparsing (2.4.7)
   1: Version solving took 0.087 seconds.
   1: Tried 1 solutions.

Finding the necessary packages for the current system

Package operations: 11 installs, 0 updates, 0 removals, 2 skipped

  • Removing atomicwrites (1.4.0): Pending...
  • Removing atomicwrites (1.4.0): Skipped for the following reason: Not currently installed
  • Removing colorama (0.4.3): Pending...
  • Removing colorama (0.4.3): Skipped for the following reason: Not currently installed
  • Installing pyparsing (2.4.7): Pending...
  • Installing pyparsing (2.4.7): Installing...
  • Installing pyparsing (2.4.7)
  • Installing six (1.15.0): Pending...
  • Installing six (1.15.0): Installing...
  • Installing six (1.15.0)
  • Installing attrs (20.2.0): Pending...
  • Installing attrs (20.2.0): Installing...
  • Installing attrs (20.2.0)
  • Installing baselib (0.1.0 /Users/nixd/Projects/MiniExamples/root/libs/BaseLib): Pending...
  • Installing baselib (0.1.0 /Users/nixd/Projects/MiniExamples/root/libs/BaseLib): Building...
  • Installing baselib (0.1.0 /Users/nixd/Projects/MiniExamples/root/libs/BaseLib)
  • Installing more-itertools (8.5.0): Pending...
  • Installing more-itertools (8.5.0): Installing...
  • Installing more-itertools (8.5.0)
  • Installing packaging (20.4): Pending...
  • Installing packaging (20.4): Installing...
  • Installing packaging (20.4)
  • Installing pluggy (0.13.1): Pending...
  • Installing pluggy (0.13.1): Installing...
  • Installing pluggy (0.13.1)
  • Installing py (1.9.0): Pending...
  • Installing py (1.9.0): Installing...
  • Installing py (1.9.0)
  • Installing wcwidth (0.2.5): Pending...
  • Installing wcwidth (0.2.5): Installing...
  • Installing wcwidth (0.2.5)
  • Installing dependentlib (0.1.0 /Users/nixd/Projects/MiniExamples/root/libs/DependentLib): Pending...
  • Installing dependentlib (0.1.0 /Users/nixd/Projects/MiniExamples/root/libs/DependentLib): Building...
  • Installing dependentlib (0.1.0 /Users/nixd/Projects/MiniExamples/root/libs/DependentLib): Failed

  EnvCommandError

  Command ['/Users/nixd/Library/Caches/pypoetry/virtualenvs/dependentservice-OpJeHZVV-py3.8/bin/pip', 'install', '--no-deps', '-U', '/Users/nixd/Projects/MiniExamples/root/libs/
DependentLib'] errored with the following return code 1, and output: 
  Processing /Users/nixd/Projects/MiniExamples/root/libs/DependentLib
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/nixd/Library/Caches/pypoetry/virtualenvs/dependentservice-OpJeHZVV-py3.8/bin/python /Users/nixd/Library/Caches/pypoetry/virtualenvs/dependentservice-OpJeHZVV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/ll/wnbx0pk51vs_cq7ls9gy6s5h0000gn/T/tmpeewo9dee
           cwd: /private/var/folders/ll/wnbx0pk51vs_cq7ls9gy6s5h0000gn/T/pip-req-build-_8xmh0nj
      Complete output (16 lines):
      Traceback (most recent call last):
        File "/Users/nixd/Library/Caches/pypoetry/virtualenvs/dependentservice-OpJeHZVV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/Users/nixd/Library/Caches/pypoetry/virtualenvs/dependentservice-OpJeHZVV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/nixd/Library/Caches/pypoetry/virtualenvs/dependentservice-OpJeHZVV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/private/var/folders/ll/wnbx0pk51vs_cq7ls9gy6s5h0000gn/T/pip-build-env-3i6ebd_8/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 34, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve())
        File "/private/var/folders/ll/wnbx0pk51vs_cq7ls9gy6s5h0000gn/T/pip-build-env-3i6ebd_8/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 91, in create_poetry
          self.create_dependency(name, constraint, root_dir=package.root_dir)
        File "/private/var/folders/ll/wnbx0pk51vs_cq7ls9gy6s5h0000gn/T/pip-build-env-3i6ebd_8/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 242, in create_dependency
          dependency = DirectoryDependency(
        File "/private/var/folders/ll/wnbx0pk51vs_cq7ls9gy6s5h0000gn/T/pip-build-env-3i6ebd_8/overlay/lib/python3.8/site-packages/poetry/core/packages/directory_dependency.py", line 36, in __init__
          raise ValueError("Directory {} does not exist".format(self._path))
      ValueError: Directory ../BaseLib does not exist
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /Users/nixd/Library/Caches/pypoetry/virtualenvs/dependentservice-OpJeHZVV-py3.8/bin/python /Users/nixd/Library/Caches/pypoetry/virtualenvs/dependentservice-OpJeHZVV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /var/folders/ll/wnbx0pk51vs_cq7ls9gy6s5h0000gn/T/tmpeewo9dee Check the logs for full command output.
  WARNING: You are using pip version 20.2.2; however, version 20.2.3 is available.
  You should consider upgrading via the '/Users/nixd/Library/Caches/pypoetry/virtualenvs/dependentservice-OpJeHZVV-py3.8/bin/python -m pip install --upgrade pip' command.
  

  at ~/.poetry/lib/poetry/utils/env.py:948 in _run
       944│                 output = subprocess.check_output(
       945│                     cmd, stderr=subprocess.STDOUT, **kwargs
       946│                 )
       947│         except CalledProcessError as e:
    →  948│             raise EnvCommandError(e, input=input_)
       949│ 
       950│         return decode(output)
       951│ 
       952│     def execute(self, bin, *args, **kwargs):

  • Installing pytest (5.4.3): Pending...
  • Installing pytest (5.4.3): Installing...
  • Installing pytest (5.4.3)

Failed to add packages, reverting the pyproject.toml file to its original content.
```

**Comment by abn** [comment]
With `1.1.0` Poetry no longer defaults to `develop = true` for path dependencies.

Please refer to https://python-poetry.org/blog/announcing-poetry-1-1-0.html#directory-dependencies-are-now-non-editable-by-default

In your case poetry attempts a PEP 517 build of your dependency, but since thats are relative files required for the build are not correctly copied, causing the error.

**Comment by mr-bjerre** [comment]
Thanks for the answer @abn . But shouldn't I be able to install the packages in non-development mode as well? I might be wrong about this of course.

**Comment by abn** [comment]
Well, you should be yes. However, this will depend on your project specification and the dependencies you include. 

For example, if `a (/path/to/a)` depends on `b (/path/to/a/b)`, and `b` in turn depends on, `c (../c)`. With `c` being located at `/path/to/a/c`.

When you install `a`, poetry detects `b` as a dependency. And since, the dependency is now `develop = false`, a PEP 517 isolated build is used. This means all packages as included by the `sdist` of `b` will be copied over to a temporary location (eg: `/tmp/some-tmp-name/b`). Then within this context a build is initiated. At this point, poetry will identify that `b` depends on `c (../c)`. However, the resolution of the path is now `/tmp/some-tmp-name/c`, which, obviously does not exist. Hence why you see the following error.

```
ValueError: Directory ../BaseLib does not exist
```

**Comment by mr-bjerre** [comment]
That makes sense. Thanks for the insights !
