### ISSUE TITLE
Dependency install issue with 1.1.0 on Windows CI, fixed by experimental.new-installer=false

### ISSUE THREAD

**Issue by ginty** [python-poetry/poetry#3090]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Windows (Travis CI)**: 
- **1.1.0**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I don't really understand what the problem is, but below is a stack trace from Poetry failing to install my app's dependencies on a Travis Windows system.

The problem can be fixed by rolling back to `1.0.10` or by setting `experimental.new-installer=false`, so I believe it to be a Poetry issue (even though it's not clear from the stack trace).

Full Travis log is here if it helps - https://travis-ci.org/github/Origen-SDK/o2/jobs/732477284

~~~
  � Installing shellingham (1.3.2)
  � Installing sphinx (3.0.2)
  � Installing tomlkit (0.7.0)
  � Installing virtualenv (20.0.32)
  � Installing autoapi (2.0.1 79d07bc)
  � Installing bs4 (0.0.1)
  � Installing lxml (4.4.2)
  � Installing mako (1.1.0)
  � Installing poetry (1.1.0)
  � Installing pyreadline (2.1)
  EnvCommandError
  Command C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\Scripts\pip.exe install --no-deps C:\Users\travis\AppData\Local\pypoetry\Cache\artifacts\40\b7\a1\08d80a4ee91ede614be15e9ad0add0d8f7c093a6d2f75c2b1e5239c365\pyreadline-2.1.win32.exe errored with the following return code 2, and output: 
  ERROR: Exception:
  Traceback (most recent call last):
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_vendor\packaging\requirements.py", line 98, in __init__
      req = REQUIREMENT.parseString(requirement_string)
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_vendor\pyparsing.py", line 1955, in parseString
      raise exc
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_vendor\pyparsing.py", line 3814, in parseImpl
      raise ParseException(instring, loc, self.errmsg, self)
  pip._vendor.pyparsing.ParseException: Expected stringEnd, found ':'  (at char 1), (line:1, col:2)
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_internal\req\constructors.py", line 359, in parse_req_from_line
      req = Requirement(req_as_string)
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_vendor\packaging\requirements.py", line 102, in __init__
      requirement_string[e.loc : e.loc + 8], e.msg
  pip._vendor.packaging.requirements.InvalidRequirement: Parse error at "':\\Users\\'": Expected stringEnd
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
      status = self.run(options, args)
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
      return func(self, options, args)
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_internal\commands\install.py", line 294, in run
      reqs = self.get_requirements(args, options, finder, session)
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_internal\cli\req_command.py", line 319, in get_requirements
      user_supplied=True,
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_internal\req\constructors.py", line 409, in install_req_from_line
      parts = parse_req_from_line(name, line_source)
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_internal\req\constructors.py", line 363, in parse_req_from_line
      add_msg += deduce_helpful_msg(req_as_string)
    File "C:\Users\travis\AppData\Local\pypoetry\Cache\virtualenvs\example-aQyiZWLB-py3.7\lib\site-packages\pip\_internal\req\constructors.py", line 167, in deduce_helpful_msg
      next(parse_requirements(fp.read()))
    File "C:\PythonForO2\lib\encodings\cp1252.py", line 23, in decode
      return codecs.charmap_decode(input,self.errors,decoding_table)[0]
  UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 2: character maps to <undefined>
~~~

**Comment by abn** [comment]
@ginty think this is a duplicate of #3045. Can you try Poetry `1.1.1` please?

**Comment by ginty** [comment]
@abn, I confirm that 1.1.1 fixes this, thanks!

**Comment by Yajo** [comment]
I'm having the same issue [here](https://github.com/copier-org/copier/runs/1229756173?check_suite_focus=true) , but I use Poetry 1.1.2. However my logs aren't so detailed. You can see the complete logs there and navigate to the pyproject.toml file. The summary:

```
Installing dependencies from lock file 

98 

99 UnicodeDecodeError 

100 

101 'charmap' codec can't decode byte 0x90 in position 356: character maps to <undefined> 

102 

103 at c:\hostedtoolcache\windows\python\3.8.6\x64\lib\encodings\cp1252.py:23 in decode 

104 19│ return codecs.charmap_encode(input,self.errors,encoding_table)[0] 

105 20│ 

106 21│ class IncrementalDecoder(codecs.IncrementalDecoder): 

107 22│ def decode(self, input, final=False): 

108 → 23│ return codecs.charmap_decode(input,self.errors,decoding_table)[0] 

109 24│ 

110 25│ class StreamWriter(Codec,codecs.StreamWriter): 

111 26│ pass 

112 27│ 

113Error: Process completed with exit code 1.


```
