### ISSUE TITLE
poetry install with python3 but still use python2?

### ISSUE THREAD

**Issue by linhnvhicts** [python-poetry/poetry#3391]
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

OS: **macOS**
Version: **10.14.6**
python version: **3.7.0**

I had installed poetry with `curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3 -`

After that i activated with `source $HOME/.poetry/env`

But when i try to create new environment with `poetry shell` with `poetry.lock` file

it still return error notify that i'm using python2...
```
Python 2.7 will no longer be supported in the next feature release of Poetry (1.2).
You should consider updating your Python version to a supported one.

Note that you will still be able to manage Python 2.7 projects by using the env command.
See https://python-poetry.org/docs/managing-environments/ for more information.

The currently activated Python version 2.7.10 is not supported by the project (^3.7).
Trying to find and use a compatible version. 
Using python3.7 (3.7.0)
Creating virtualenv base.django-AnqsdXoZ-py3.7 in /Users/admin/Library/Caches/pypoetry/virtualenvs

ImportError

No module named via_app_data.via_app_data
```

here the full stacktrace:
```
Python 2.7 will no longer be supported in the next feature release of Poetry (1.2).
You should consider updating your Python version to a supported one.

Note that you will still be able to manage Python 2.7 projects by using the env command.
See https://python-poetry.org/docs/managing-environments/ for more information.

The currently activated Python version 2.7.10 is not supported by the project (^3.7).
Trying to find and use a compatible version. 
Trying python3
Trying python3.9
Trying python3.8
Using python3.7 (3.7.2)
Creating virtualenv base.django-AnqsdXoZ-py3.7 in /Users/admin/Library/Caches/pypoetry/virtualenvs

ImportError

No module named via_app_data.via_app_data

Traceback (most recent call last):
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/clikit/api/command/command.py", line 163, in _do_handle
    self._dispatcher.dispatch(PRE_HANDLE, event)
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/clikit/api/event/event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/clikit/api/event/event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "/Users/admin/.poetry/lib/poetry/console/config/application_config.py", line 119, in set_env
    env = env_manager.create_venv(io)
  File "/Users/admin/.poetry/lib/poetry/utils/env.py", line 761, in create_venv
    self.build_venv(venv, executable=executable)
  File "/Users/admin/.poetry/lib/poetry/utils/env.py", line 808, in build_venv
    str(path),
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/__init__.py", line 26, in cli_run
    of_session = session_via_cli(args, options, setup_logging)
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/__init__.py", line 42, in session_via_cli
    parser, elements = build_parser(args, options, setup_logging)
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/__init__.py", line 69, in build_parser
    SeederSelector(interpreter, parser),
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/plugin/seeders.py", line 8, in __init__
    possible = self.options('virtualenv.seed')
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/plugin/base.py", line 39, in options
    cls._OPTIONS = cls.entry_points_for(key)
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/plugin/base.py", line 18, in entry_points_for
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/collections.py", line 57, in __init__
    self.__update(*args, **kwds)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/_abcoll.py", line 568, in update
    for key, value in other:
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/virtualenv/run/plugin/base.py", line 18, in <genexpr>
    return OrderedDict((e.name, e.load()) for e in cls.entry_points().get(key, {}))
  File "/Users/admin/.poetry/lib/poetry/_vendor/py2.7/importlib_metadata/__init__.py", line 105, in load
    module = import_module(match.group('module'))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
```

From the error seems like it still using python2.7 for some reason, even after i installed poetry with python3

**Comment by finswimmer** [comment]
Hello @linhnvhicts,

this has been asked multiple times before. Please see this summary thread: https://github.com/python-poetry/poetry/issues/3288

Concerning the error you receive, please have a look at https://github.com/python-poetry/poetry/issues/2972#issuecomment-704800769

fin swimmer

**Comment by linhnvhicts** [comment]
Thank for telling me, didn't notice that question
