### ISSUE TITLE
Launching poetry from no-longer existing subfolder -> cryptic error message

### ISSUE THREAD

**Issue by ikamensh** [python-poetry/poetry#3455]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOS 10.14
- **Poetry version**: Poetry version 1.1.4

- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
```
[tool.poetry]
name = "globalgarden"
version = "0.1.0"
description = "distributed non-differentiable optimization"
authors = ["Ilya Kamen <ikamenshchikov@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.6"
blackopt = "^"
loguru = "^"
#sortedcontainers = "^0"

[tool.poetry.dev-dependencies]
pytest = "^5.3.5"
isort = "^4.3.21"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

## Issue

I was working in a subdirectory of my project, and then unknowingly I have deleted the subdirectory. Running `poetry publish` created a somewhat cryptic `FileNotFound` error with a stack trace. I've spent some time debugging / trying to figure out a problem. 

Output:
```
(globalgarden-NcFPtnbn-py3.9) ~/P/g/s/g/buff (master|✔) $ poetry publish                                                                                                    11:38:23

  FileNotFoundError

  [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/Users/ikkamens/.poetry/lib/poetry/_vendor/py3.9/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/Users/ikkamens/.poetry/lib/poetry/_vendor/py3.9/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/Users/ikkamens/.poetry/lib/poetry/_vendor/py3.9/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/Users/ikkamens/.poetry/lib/poetry/_vendor/py3.9/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/Users/ikkamens/.poetry/lib/poetry/console/commands/publish.py", line 46, in handle
    publisher = Publisher(self.poetry, self.io)
  File "/Users/ikkamens/.poetry/lib/poetry/console/commands/command.py", line 10, in poetry
    return self.application.poetry
  File "/Users/ikkamens/.poetry/lib/poetry/console/application.py", line 69, in poetry
    self._poetry = Factory().create_poetry(Path.cwd())
  File "/Users/ikkamens/.pyenv/versions/3.9.0/lib/python3.9/pathlib.py", line 1125, in cwd
    return cls(os.getcwd())
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/ikkamens/.poetry/bin/poetry", line 19, in <module>
    main()
  File "/Users/ikkamens/.poetry/lib/poetry/console/__init__.py", line 5, in main
    return Application().run()
  File "/Users/ikkamens/.poetry/lib/poetry/_vendor/py3.9/clikit/console_application.py", line 142, in run
    trace.render(io, simple=isinstance(e, CliKitException))
  File "/Users/ikkamens/.poetry/lib/poetry/_vendor/py3.9/clikit/ui/components/exception_trace.py", line 232, in render
    return self._render_exception(io, self._exception)
  File "/Users/ikkamens/.poetry/lib/poetry/_vendor/py3.9/clikit/ui/components/exception_trace.py", line 269, in _render_exception
    self._render_snippet(io, current_frame)
  File "/Users/ikkamens/.poetry/lib/poetry/_vendor/py3.9/clikit/ui/components/exception_trace.py", line 277, in _render_snippet
    self._get_relative_file_path(frame.filename),
  File "/Users/ikkamens/.poetry/lib/poetry/_vendor/py3.9/clikit/ui/components/exception_trace.py", line 405, in _get_relative_file_path
    cwd = os.getcwd()
FileNotFoundError: [Errno 2] No such file or directory
```

For example, git commands fail with descriptive error message:
`fatal: Unable to read current working directory: No such file or directory`. Just one line, no stack trace.

**Comment by sinoroc** [comment]
I am wondering, if this is really worth a bug ticket. What could possibly be done in _poetry_ to improve things here?

**Comment by dimaqq** [comment]
@sinoroc  I guess `poetry` could/should follow same rules to determine the project root as it does when `cwd` exists.

**Comment by sinoroc** [comment]
OK, I am not really following the exact issue. I just want to ask, if maybe this could be reclassified as a "feature request" ticket (UX improvement) instead of a "bug" ticket? Things would have failed anyway, wouldn't they?

**Comment by dimbleby** [comment]
I guess this isn't going to happen and the issue should be closed.

**Comment by neersighted** [comment]
Indeed, this is a very typical edge case on a Unix system and not really worth special casing -- plenty of other commands will break in a similar way when run from a nonsense CWD.
