### ISSUE TITLE
Django 3.1.4 not installed with poetry 1.1.4

### ISSUE THREAD

**Issue by holgerco** [python-poetry/poetry#3461]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:Windows 10
- **Poetry version**:1.1.4

## Issue

i try to install django 3.1.4 with poetry and get this error

```
  • Installing asgiref (3.3.1)
  • Installing pytz (2020.4)
  • Installing sqlparse (0.4.1)
  • Installing django (3.1.4)

  EnvCommandError

  Command "path\pypoetry\Cache\virtualenvs\sumatran-8syAURjl-py3.8\Scripts\pip.exe" install --no-deps file:path/pypoetry/Cache/artifacts/15/24/44/674b16e8d6aa16725e64e97704f4d979f2e143a7c7ae1c
24cd2713eac7/Django-3.1.4-py3-none-any.whl errored with the following return code 2, and output:
  Processing path\pypoetry\cache\artifacts\15\24\44\674b16e8d6aa16725e64e97704f4d979f2e143a7c7ae1c24cd2713eac7\django-3.1.4-py3-none-any.whl
  ERROR: Exception:
  Traceback (most recent call last):
    File "path\pypoetry\Cache\virtualenvs\sumatran-8syAURjl-py3.8\lib\site-packages\pip\_internal\cli\base_command.py", line 216, in _main
      status = self.run(options, args)
    File "path\pypoetry\Cache\virtualenvs\sumatran-8syAURjl-py3.8\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
      return func(self, options, args)
    File "path\pypoetry\Cache\virtualenvs\sumatran-8syAURjl-py3.8\lib\site-packages\pip\_internal\commands\install.py", line 324, in run
      requirement_set = resolver.resolve(
    File "path\pypoetry\Cache\virtualenvs\sumatran-8syAURjl-py3.8\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 183, in resolve
      discovered_reqs.extend(self._resolve_one(requirement_set, req))
    File "pathpypoetry\Cache\virtualenvs\sumatran-8syAURjl-py3.8\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 391, in _resolve_one
      dist = abstract_dist.get_pkg_resources_distribution()
    File "path\pypoetry\Cache\virtualenvs\sumatran-8syAURjl-py3.8\lib\site-packages\pip\_internal\distributions\wheel.py", line 29, in get_pkg_resources_distribution
      with ZipFile(self.req.local_file_path, allowZip64=True) as z:
    File "C:\Python\Python38-32\lib\zipfile.py", line 1269, in __init__
      self._RealGetContents()
    File "C:\Python\Python38-32\lib\zipfile.py", line 1336, in _RealGetContents
      raise BadZipFile("File is not a zip file")
  zipfile.BadZipFile: File is not a zip file


  at ~\.poetry\lib\poetry\utils\env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):


Failed to add packages, reverting the pyproject.toml file to its original content.

```

**Comment by sinoroc** [comment]
Looks like something went wrong during the download of the wheel file. To make sure of it, try to inspect the `...\pypoetry\cache\artifacts\15\24\44\674b16e8d6aa16725e64e97704f4d979f2e143a7c7ae1c24cd2713eac7\django-3.1.4-py3-none-any.whl`. Maybe you could try to unzip it for example.

To fix it, I would recommend deleting that file and retry.

Possible duplicates:

* https://github.com/python-poetry/poetry/issues/2674
* https://github.com/python-poetry/poetry/issues/3326
* https://github.com/python-poetry/poetry/issues/2388
* https://github.com/python-poetry/poetry/issues/1483
* https://github.com/python-poetry/poetry/issues/155

**Comment by holgerco** [comment]
thank you @sinoroc

**Comment by holgerco** [comment]
thank @sinoroc
