### ISSUE TITLE
Poetry says no versions match, but versions do match

### ISSUE THREAD

**Issue by WhyNotHugo** [python-poetry/poetry#3484]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: ArchLInux
- **Poetry version**: 1.0.10
- Using an new `pyproject.toml` for a fresh new project.

## Issue

`poetry add pyside6` complains that no version matches, but the error doesn't make sense:

```
➜ python --version
Python 3.9.0

➜ poetry add -vvv pyside6
Using virtualenv: /home/hugo/.cache/pypoetry/virtualenvs/screenman-YK8rCbov-py3.9
PyPI: 3 packages found for pyside6 *
Using version ^6.0.0 for pyside6

Updating dependencies
Resolving dependencies...
   1: fact: screenman is 0.1.0
   1: derived: screenman
   1: fact: screenman depends on pyside6 (^6.0.0)
   1: selecting screenman (0.1.0)
   1: derived: pyside6 (^6.0.0)
PyPI: 1 packages found for pyside6 >=6.0.0,<7.0.0
   1: fact: pyside6 (6.0.0) requires Python >=3.6, <3.10
   1: derived: not pyside6 (6.0.0)
   1: fact: no versions of pyside6 match >6.0.0,<7.0.0
   1: conflict: no versions of pyside6 match >6.0.0,<7.0.0
   1: ! pyside6 (>6.0.0,<7.0.0) is partially satisfied by not pyside6 (6.0.0)
   1: ! which is caused by "pyside6 (6.0.0) requires Python >=3.6, <3.10"
   1: ! thus: pyside6 is forbidden
   1: ! pyside6 (>=6.0.0,<7.0.0) is satisfied by pyside6 (^6.0.0)
   1: ! which is caused by "screenman depends on pyside6 (^6.0.0)"
   1: ! thus: version solving failed
   1: Version solving took 0.011 seconds.
   1: Tried 1 solutions.

[SolverProblemError]
The current project's Python requirement (^3.9) is not compatible with some of the required packages Python requirement:
  - pyside6 requires Python >=3.6, <3.10

Because no versions of pyside6 match >6.0.0,<7.0.0
 and pyside6 (6.0.0) requires Python >=3.6, <3.10, pyside6 is forbidden.
So, because screenman depends on pyside6 (^6.0.0), version solving failed.

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/usr/lib/python3.9/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/usr/lib/python3.9/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/usr/lib/python3.9/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/usr/lib/python3.9/site-packages/poetry/console/commands/add.py", line 156, in handle
    status = installer.run()
  File "/usr/lib/python3.9/site-packages/poetry/installation/installer.py", line 74, in run
    self._do_install(local_repo)
  File "/usr/lib/python3.9/site-packages/poetry/installation/installer.py", line 161, in _do_install
    ops = solver.solve(use_latest=self._whitelist)
  File "/usr/lib/python3.9/site-packages/poetry/puzzle/solver.py", line 36, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/usr/lib/python3.9/site-packages/poetry/puzzle/solver.py", line 190, in _solve
    raise SolverProblemError(e)
```

Maybe I'm missing something, but this seems to indicate that the dependency requires Python>3.6, <3.10, but fails to match on Python 3.9. This doesn't make sense.

**Comment by sinoroc** [comment]
I can recreate and does not make sense to me either.

**Comment by finswimmer** [comment]
Hello @WhyNotHugo,

> [SolverProblemError]
>The current project's Python requirement (^3.9) is not compatible with some of the required packages Python requirement:
>  - pyside6 requires Python >=3.6, <3.10

please see https://github.com/python-poetry/poetry/issues/1930#issuecomment-653906544 to understand what's going on here and how you can solve it.

fin swimmer
