### ISSUE TITLE
Broken packages lead to errors on any poetry command

### ISSUE THREAD

**Issue by eugenweissbart** [python-poetry/poetry#3486]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- 10.15.7 macOS Catalina 
- 1.1.4 
- https://gist.github.com/eugenweissbart/9470b942f2d171fc71d84b9ffd9b83a8 

## Issue
Somehow I've got a broken `redis` package on last package upgrade. The main issue is, any poetry command now leads to a following stacktrace:

```
➜ poetry remove redisearch
Traceback (most recent call last):
  File "/Users/ebelousov/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
  File "/Users/ebelousov/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/ebelousov/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/Users/ebelousov/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/Users/ebelousov/.poetry/lib/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/Users/ebelousov/.poetry/lib/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/Users/ebelousov/.poetry/lib/poetry/repositories/pypi_repository.py", line 14, in <module>
    from cachy import CacheManager
  File "/Users/ebelousov/.poetry/lib/poetry/_vendor/py3.8/cachy/__init__.py", line 3, in <module>
    from .cache_manager import CacheManager
  File "/Users/ebelousov/.poetry/lib/poetry/_vendor/py3.8/cachy/cache_manager.py", line 8, in <module>
    from .stores import (
  File "/Users/ebelousov/.poetry/lib/poetry/_vendor/py3.8/cachy/stores/__init__.py", line 6, in <module>
    from .redis_store import RedisStore
  File "/Users/ebelousov/.poetry/lib/poetry/_vendor/py3.8/cachy/stores/redis_store.py", line 4, in <module>
    from redis import StrictRedis
  File "/Users/ebelousov/.pyenv/versions/stickersearchbot/lib/python3.8/site-packages/redis/__init__.py", line 1, in <module>
    from redis.client import Redis, StrictRedis
  File "/Users/ebelousov/.pyenv/versions/stickersearchbot/lib/python3.8/site-packages/redis/client.py", line 12, in <module>
    from redis.connection import (ConnectionPool, UnixDomainSocketConnection,
  File "/Users/ebelousov/.pyenv/versions/stickersearchbot/lib/python3.8/site-packages/redis/connection.py", line 194
    import logging
                 ^
TabError: inconsistent use of tabs and spaces in indentation
```

**Comment by finswimmer** [comment]
Closing this because we haven't received more information for a long time.

Feel free to leave a comment if you disagree.
