### ISSUE TITLE
Can't add option with name `n`

### ISSUE THREAD

**Issue by Rhinik** [python-poetry/poetry#3517]
I want to add an option with name `n`
```
{--n|names=* : Some description}
```

But I get this:
```
Traceback (most recent call last):
  File "/Users/an/Desktop/vkquick/env/bin/vq", line 2, in <module>
    from vkquick.__main__ import app
  File "/Users/an/Desktop/vkquick/vkquick/__main__.py", line 23, in <module>
    app.add_commands(New(), DebugRun(), ReleaseRun(), Com())
  File "/Users/an/Desktop/vkquick/env/lib/python3.8/site-packages/cleo/application.py", line 36, in add_commands
    self.add(command)
  File "/Users/an/Desktop/vkquick/env/lib/python3.8/site-packages/cleo/application.py", line 42, in add
    self.add_command(command.config)
  File "/Users/an/Desktop/vkquick/env/lib/python3.8/site-packages/clikit/console_application.py", line 163, in add_command
    command = Command(config, self)
  File "/Users/an/Desktop/vkquick/env/lib/python3.8/site-packages/clikit/api/command/command.py", line 35, in __init__
    self._args_format = config.build_args_format(self.base_format)
  File "/Users/an/Desktop/vkquick/env/lib/python3.8/site-packages/clikit/api/config/command_config.py", line 159, in build_args_format
    builder.add_options(*self.options.values())
  File "/Users/an/Desktop/vkquick/env/lib/python3.8/site-packages/clikit/api/args/format/args_format_builder.py", line 292, in add_options
    self.add_option(option)
  File "/Users/an/Desktop/vkquick/env/lib/python3.8/site-packages/clikit/api/args/format/args_format_builder.py", line 302, in add_option
    raise CannotAddOptionException.already_exists(short_name)
clikit.api.args.exceptions.CannotAddOptionException: An option named "-n" exists already.
```

There __aren't__ any options with name `n` so I think it is a "built-in". Can I override it?

**Comment by Rhinik** [comment]
Oh sorry it is a poetry
