### ISSUE TITLE
Failed to install Poetry on macOS Catalina for Python3 

### ISSUE THREAD

**Issue by kakyoism** [python-poetry/poetry#3528]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.15.7
- **Poetry version**: 0.14
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

I'm trying to install Poetry using the download script `get-poetry.py` with the official Python 3.9.1 downloaded from python.org. But failed with the following errors.

```python
$ python3 get-poetry.py 
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 950, in send
    self.connect()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/http/client.py", line 1424, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/me/Desktop/_dev/get-poetry.py", line 1086, in <module>
    sys.exit(main())
  File "/Users/me/Desktop/_dev/get-poetry.py", line 1060, in main
    urlopen(Installer.REPOSITORY_URL)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1123)>
```

Using the system builtin Python2.7, I got no such errors. But since py27 is deprecated for Poetry. I got no choice but to use Python3.

If I'm the only one with this problem, then it must be my own setup, but what am I missing?

**Comment by sinoroc** [comment]
Where did you get your Python 3 from? There might be something broken with it.

**Comment by kakyoism** [comment]
> Where did you get your Python 3 from? There might be something broken with it.

As I said in my answer "with the official Python 3.9.1 downloaded from python.org"

**Comment by kakyoism** [comment]
I worked around this with `pip3 install --user poetry`, but since the download script is the first choice, and the Poetry doc suggests with the scary red notes that 

> Be aware that it will also install Poetry's dependencies which might cause conflicts with other packages.

I'd really love to get an answer for how to use the recommended script with Python 3.

>

**Comment by sanders41** [comment]
I installed python with pyenv and haven't seen this issue so I wasn't able to test this myself, but according to [this article](https://medium.com/@yen.hoang.1904/resolve-issue-ssl-certificate-verify-failed-when-trying-to-open-an-url-with-python-on-macos-46d868b44e10) you might be able to fix it by:

Navigating to Application/Python 3.9 folder, you will see the command file shipped with Python: Install Certificates.command.

**Comment by kottn** [comment]
I got the same error under the [first-step (windows powershell install)](https://python-poetry.org/docs/#windows-powershell-install-instructions):

```
(Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -
```

- OS: Windows10 Pro build 1909
- Python version: Official Python 3.9.1 https://www.python.org/

Error details:

```
PS C:\Users\me> (Invoke-WebRequest -Uri https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py -UseBasicParsing).Content | python -
Traceback (most recent call last):
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1342, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1010, in _send_output
    self.send(msg)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 950, in send
    self.connect()
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 1417, in connect
    super().connect()
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\http\client.py", line 921, in connect
    self.sock = self._create_connection(
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\socket.py", line 822, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\socket.py", line 953, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1086, in <module>
  File "<stdin>", line 1060, in main
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 517, in open
    response = self._open(req, data)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 494, in _call_chain
    result = func(*args)
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1385, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\me\AppData\Local\Programs\Python\Python39\lib\urllib\request.py", line 1345, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 11001] getaddrinfo failed>


PS C:\Users\me> python --version
Python 3.9.1

```

**Comment by sanders41** [comment]
@kottn I think your issue may be different since your error is not an ssl certificate error. Are you using a proxy? I have seen others mention errors like this when behind a proxy.

**Comment by kottn** [comment]
@sanders41 Thanks a lot. I solved. The problem was Proxy settings as you said.

**Comment by dimbleby** [comment]
get-poetry.py is deprecated, probably no-one will ever make any more fixes to it, this might as well be closed

**Comment by Abdullah204** [comment]
> I installed python with pyenv and haven't seen this issue so I wasn't able to test this myself, but according to [this article](https://medium.com/@yen.hoang.1904/resolve-issue-ssl-certificate-verify-failed-when-trying-to-open-an-url-with-python-on-macos-46d868b44e10) you might be able to fix it by:
> 
> Navigating to Application/Python 3.9 folder, you will see the command file shipped with Python: Install Certificates.command. Run that command

that worked with me ,thanks

**Comment by acebytes** [comment]
For anyone still experiencing issues, I was able to install Poetry using Homebrew:
`brew install poetry`
