### ISSUE TITLE
Poetry fails to install PyQt6 from its wheel, inexplicably choose to download the sdist

### ISSUE THREAD

**Issue by xrogaan** [python-poetry/poetry#3584]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Devuan Beowulf (debian derivative)
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/xrogaan/cae41d48f78dc1727a8194ad52db4aed

## Issue
The PyQt6 installation fails because the sdist build requires Qt6 sources to be available, where as the wheel bundle Qt6. For some unknown reason, poetry doesn't download the wheel where as a direct install with pip does.

I've discussed this issue on PyQt's mailing list, those emails contains context as well as an answer from PyQt's maintainer (Phil Thompson). The helpful messages are as follow:
* https://www.riverbankcomputing.com/pipermail/pyqt/2021-January/043555.html
* https://www.riverbankcomputing.com/pipermail/pyqt/2021-January/043559.html
* https://www.riverbankcomputing.com/pipermail/pyqt/2021-January/043561.html

I believe anybody can reproduce that behavior by using the linked pyproject.toml.

I apologize if there is lack of details in this bug report. I've been exchanging information in several places and I am unsure of how much is required here.

### poetry env info
```
Virtualenv
Python:         3.8.7
Implementation: CPython
Path:           /home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8
Valid:          True

System
Platform: linux
OS:       posix
Python:   /home/xx/.pyenv/versions/3.8.7
```

### `poetry run pip debug --verbose`
[pip_debug.txt](https://github.com/python-poetry/poetry/files/5826654/pip_debug.txt)

### `poetry run pip --version`
pip 20.3.3 from /home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8/lib/python3.8/site-packages/pip (python 3.8)

### Traceback
Here included poetry's error for the sake of completeness:
```
  Command ['/home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8/bin/pip', 'install', '--no-deps', 'file:///home/xx/.cache/pypoetry/artifacts/9f/e5/4f/8c942b1b7e85a4e4f60f423ebcf98c81e6ce31c589eaa9f186c9e878e/PyQt6-6.0.0.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/xx/.cache/pypoetry/artifacts/9f/e5/4f/8c942b1b7e85a41e4f60f423ebcf98c81e6ce31c589eaa9f186c9e878e/PyQt6-6.0.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8/bin/python /home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8/lib/python3.8/site-pacages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpj31x1slb
           cwd: /tmp/pip-req-build-mnpblx1b
      Complete output (26 lines):
      Querying qmake about your Qt installation...
      /usr/bin/qmake -query
      Traceback (most recent call last):
        File "/home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 126, in prepare_metadata_for_buid_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
          main()
        File "/home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 130, in prepare_metadata_for_buid_wheel
          return _get_wheel_metadata_from_wheel(backend, metadata_directory,
        File "/home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 159, in _get_wheel_metadata_fromwheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/tmp/pip-build-env-av61j5d2/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "/tmp/pip-build-env-av61j5d2/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/tmp/pip-build-env-av61j5d2/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 495, in setup
          self.update(tool)
        File "project.py", line 158, in update
      sipbuild.exceptions.UserException
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKiElV-py3.8/bin/python /home/xx/.cache/pypoetry/virtualenvs/test-pyqt6-hVjKElV-py3.8/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py prepare_metadata_for_build_wheel /tmp/tmpj31x1slb Check the logs for full command output.
```

**Comment by sinoroc** [comment]
Wheel file name: `PyQt6-6.0.0-6.0.0-cp36.cp37.cp38.cp39-abi3-manylinux_2_28_x86_64.whl` the version string is present twice. It could be an issue. As far as I know this is not a standard-conform file name for a wheel. Maybe pip has a different parsing logic and is more lenient.

**Comment by altendky** [comment]
I don't recall offhand the details of the file name format, but just to explain the double version...  The 'second version' is the Qt version included in the wheel as opposed to the PyQt6 Python package version.

**Comment by bnavigator** [comment]
The missing `prepare_metadata_for_build_wheel` could indicate that your pip is too old. Did you update it?

**Comment by xrogaan** [comment]
> The missing `prepare_metadata_for_build_wheel` could indicate that your pip is too old. Did you update it?

The answer is in the OP. It's the latest. The failure isn't on `prepare_metadata_for_build_wheel`, it's when poetry chose to download the sdist instead of the wheel.

**Comment by sinoroc** [comment]
> I don't recall offhand the details of the file name format, but just to explain the double version... The 'second version' is the Qt version included in the wheel as opposed to the PyQt6 Python package version.

I found this: `{distribution}-{version}(-{build tag})?-{python tag}-{abi tag}-{platform tag}.whl` at https://www.python.org/dev/peps/pep-0427/#file-name-convention
So the second version string would be the _build-tag_. I see, that would mean the file name is standard-conform. Not sure if _poetry_ understands such a wheel file name or not.

**Comment by xrogaan** [comment]
That trail may be the right one. The list of supported environment known by poetry follow this scheme:
* `<cp38-abi3-manylinux2010_x86_64 @ 140301994449152>`
* `<cp38-abi3-manylinux1_x86_64 @ 140301994196672>`

PyQt6 wheel's filename is: `PyQt6-6.0.0-6.0.0-cp36.cp37.cp38.cp39-abi3-manylinux_2_28_x86_64.whl`. Notice the `_2_28` after manylinux, it isn't present in the list available to poetry. Where as PySide6's filename is `PySide6-6.0.0-6.0.0-cp36.cp37.cp38.cp39-abi3-manylinux1_x86_64.whl`, there `manylinux1` fits.

I don't know what `_2_28` represent, but pip doesn't seem bothered by it.

**Comment by xrogaan** [comment]
Alright, so, `poetry.utils.env.supported_tags` is an alias for `packaging.tags.sys_tags`. But for some reason the list of supported tags are drastically lower than what should be available.  From `manylinux_2_5_x86_64` to `manylinux_2_28_x86_64` are somehow missing.

I am looking at this file: https://github.com/python-poetry/poetry/blob/3f6220dedb6d824e14e0c703485bbf76c32af3db/poetry/utils/env.py

**Comment by xrogaan** [comment]
If poetry is installed through the official installer all dependencies are vendored (`$HOME/.poetry/lib/poetry/_vendor`). The version of `packaging` shipped is 20.4, which doesn't support glibc tags.

See: https://github.com/pypa/packaging/compare/20.4...20.8#diff-e2a5f8198f944bfcd050534d68367fd50e3f9f28afe1bb4b54c72afccd8fc0f6

**Comment by sinoroc** [comment]
In case updating `packaging` solves this, then these PRs should fix it:

* https://github.com/python-poetry/poetry-core/pull/125
* https://github.com/python-poetry/poetry/pull/3530

**Comment by daiyam** [comment]
I'm getting the same issue when
```
• Installing pyqt5 (5.15.2): Failed

  EnvCommandError

  Command ['/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/bin/pip', 'install', '--no-deps', 'file:///Users/baptiste/Library/Caches/pypoetry/artifacts/68/c1/b8/00a192d66f6efe4fcc730dcf859ef8ade4de0569167d58b743b570c4a3/PyQt5-5.15.2.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/baptiste/Library/Caches/pypoetry/artifacts/68/c1/b8/00a192d66f6efe4fcc730dcf859ef8ade4de0569167d58b743b570c4a3/PyQt5-5.15.2.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/bin/python /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/tmpr1_u1zkx
           cwd: /private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-req-build-kxl9tir1
      Complete output (31 lines):
      Traceback (most recent call last):
        File "/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 126, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
          main()
        File "/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in prepare_metadata_for_build_wheel
          return _get_wheel_metadata_from_wheel(backend, metadata_directory,
        File "/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 484, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 230, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      ----------------------------------------
  WARNING: Discarding file:///Users/baptiste/Library/Caches/pypoetry/artifacts/68/c1/b8/00a192d66f6efe4fcc730dcf859ef8ade4de0569167d58b743b570c4a3/PyQt5-5.15.2.tar.gz. Command errored out with exit status 1: /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/bin/python /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/tmpr1_u1zkx Check the logs for full command output.
  ERROR: Command errored out with exit status 1: /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/bin/python /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/tmpr1_u1zkx Check the logs for full command output.
  WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
  You should consider upgrading via the '/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/bin/python -m pip install --upgrade pip' command.
```
with
```
$ poetry -V
Poetry version 1.1.7

$ poetry env info
Virtualenv
Python:         3.9.1
Implementation: CPython
Path:           /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /Users/baptiste/.pyenv/versions/3.9.1
```
