### ISSUE TITLE
jupyter failes with "ModuleNotFoundError: No module named 'pysqlite2'"

### ISSUE THREAD

**Issue by PgLoLo** [python-poetry/poetry#3588]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/PgLoLo/dc2fabc3bfd61cae5b858eee24f92797

## Issue
jupyter notebook failes in the clean python 3.9.1 environment:

```
poetry new test-test
cd test-test/
poetry add --dev jupyter
poetry run jupyter notebook
```
would fail with
```
Traceback (most recent call last):
  File "/home/gosha/.cache/pypoetry/virtualenvs/test-test-NHgy5K2K-py3.9/lib/python3.9/site-packages/notebook/services/sessions/sessionmanager.py", line 9, in <module>
    import sqlite3
  File "/home/gosha/.pyenv/versions/3.9.1/lib/python3.9/sqlite3/__init__.py", line 23, in <module>
    from sqlite3.dbapi2 import *
  File "/home/gosha/.pyenv/versions/3.9.1/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gosha/.cache/pypoetry/virtualenvs/test-test-NHgy5K2K-py3.9/bin/jupyter-notebook", line 5, in <module>
    from notebook.notebookapp import main
  File "/home/gosha/.cache/pypoetry/virtualenvs/test-test-NHgy5K2K-py3.9/lib/python3.9/site-packages/notebook/notebookapp.py", line 86, in <module>
    from .services.sessions.sessionmanager import SessionManager
  File "/home/gosha/.cache/pypoetry/virtualenvs/test-test-NHgy5K2K-py3.9/lib/python3.9/site-packages/notebook/services/sessions/sessionmanager.py", line 12, in <module>
    from pysqlite2 import dbapi2 as sqlite3
ModuleNotFoundError: No module named 'pysqlite2'
```

What could be the cause of the problem?

**Comment by sinoroc** [comment]
Isn't there something broken with your installation of Python? I did not have a close look so I might be a bit off, but it looks like the `sqlite3` module (which is part of Python's standard library and thus should always be available and importable) is broken and not importable.

**Comment by PgLoLo** [comment]
> Isn't there something broken with your installation of Python? I did not have a close look so I might be a bit off, but it looks like the `sqlite3` module (which is part of Python's standard library and thus should always be available and importable) is broken and not importable.
> 
> If true, that would mean that it is not a _poetry_ issue.
> 
> Could you try `poetry run python -c 'import sqlite3'`, or even `python -c 'import sqlite3'`?

Yes, that was exactly the problem, thank you very much! Could not image such a problem could leak through the python installation process in pyenv.
