### ISSUE TITLE
[Solved] TypeError on `version` when installing a package 

### ISSUE THREAD

**Issue by shreyansb** [python-poetry/poetry#3635]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: MacOX Big Sur 11.1
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/shreyansb/4aed665e3ad5d9feaa6e91cffb5edd98
- pip version: 21.0

## Issue
I'm getting the following error while installing `grpcio`:
```
  • Installing grpcio (1.35.0): Failed

  EnvCommandError

  Command ['/Users/shreyans/Library/Caches/pypoetry/virtualenvs/api-CC92AA4r-py3.9/bin/pip', 'install', '--no-deps', 'file:///Users/shreyans/Library/Caches/pypoetry/artifacts/e9/51/ef/4a92d0d17a6a42d453b4eb4f92639086e56b4fbd8246d2e37ec786cefc/grpcio-1.35.0.tar.gz'] errored with the following return code 1, and output:
  Processing /Users/shreyans/Library/Caches/pypoetry/artifacts/e9/51/ef/4a92d0d17a6a42d453b4eb4f92639086e56b4fbd8246d2e37ec786cefc/grpcio-1.35.0.tar.gz
      ERROR: Command errored out with exit status 1:
       command: /Users/shreyans/Library/Caches/pypoetry/virtualenvs/api-CC92AA4r-py3.9/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/hh/7l91p_qs66n6h8rgq80348pc0000gn/T/pip-req-build-zapd7oor/setup.py'"'"'; __file__='"'"'/private/var/folders/hh/7l91p_qs66n6h8rgq80348pc0000gn/T/pip-req-build-zapd7oor/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/hh/7l91p_qs66n6h8rgq80348pc0000gn/T/pip-pip-egg-info-r9ln5m4_
           cwd: /private/var/folders/hh/7l91p_qs66n6h8rgq80348pc0000gn/T/pip-req-build-zapd7oor/
      Complete output (9 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/private/var/folders/hh/7l91p_qs66n6h8rgq80348pc0000gn/T/pip-req-build-zapd7oor/setup.py", line 359, in <module>
          if mac_target and (pkg_resources.parse_version(mac_target) <
        File "/Users/shreyans/Library/Caches/pypoetry/virtualenvs/api-CC92AA4r-py3.9/lib/python3.9/site-packages/pkg_resources/__init__.py", line 113, in parse_version
          return packaging.version.Version(v)
        File "/Users/shreyans/Library/Caches/pypoetry/virtualenvs/api-CC92AA4r-py3.9/lib/python3.9/site-packages/pkg_resources/_vendor/packaging/version.py", line 275, in __init__
          match = self._regex.search(version)
      TypeError: expected string or bytes-like object
      ----------------------------------------
  WARNING: Discarding file:///Users/shreyans/Library/Caches/pypoetry/artifacts/e9/51/ef/4a92d0d17a6a42d453b4eb4f92639086e56b4fbd8246d2e37ec786cefc/grpcio-1.35.0.tar.gz. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
  ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.


  at /usr/local/Cellar/poetry/1.1.4/libexec/lib/python3.9/site-packages/poetry/utils/env.py:1074 in _run
      1070│                 output = subprocess.check_output(
      1071│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1072│                 )
      1073│         except CalledProcessError as e:
    → 1074│             raise EnvCommandError(e, input=input_)
      1075│
      1076│         return decode(output)
      1077│
      1078│     def execute(self, bin, *args, **kwargs):
```

The same package can be installed directly via `pip`:

```
Collecting grpcio
  Using cached grpcio-1.35.0-cp39-cp39-macosx_10_10_x86_64.whl (3.8 MB)
Requirement already satisfied: six>=1.5.2 in /usr/local/lib/python3.9/site-packages (from grpcio) (1.15.0)
Installing collected packages: grpcio
Successfully installed grpcio-1.35.0
```

Unsure what other information to provide, but lmk and I'll add it.
Oh and `-vvv` does not produce any additional output - it looks the same.

This [Dockerfile and requirements.txt (gist)](https://gist.github.com/shreyansb/26f51ab77b407a52b3f91a04eda4e28b) work fine, so the issue is on my machine, and so I wonder what I can do to reset my environment and try this again from a fresh start.

I've tried deleting the `poetry.lock` file, and have tried `poetry env remove` as well. `poetry install` failed in the same way after both of those.

Thank you!

**Comment by patollefsen** [comment]
I have the same issue.
Issuing `poetry config experimental.new-installer false` works as a workaround.

**Comment by shreyansb** [comment]
Omg @patollefsen thank you. That worked.
