### ISSUE TITLE
Recently released poetry-core 1.0.1 breaks things

### ISSUE THREAD

**Issue by bdrosen96** [python-poetry/poetry#3651]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- Ubuntu 16.04: 
- 1.1.4: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

With the poetry core 1.0.1 instead of poetry 1.0.0 we see this:

```
13:15:40  Traceback (most recent call last):
13:15:40    File "/usr/local/bin/poetry", line 5, in <module>
13:15:40      from poetry.console import main
13:15:40    File "/usr/local/lib/python3.8/site-packages/poetry/console/__init__.py", line 1, in <module>
13:15:40      from .application import Application
13:15:40    File "/usr/local/lib/python3.8/site-packages/poetry/console/application.py", line 7, in <module>
13:15:40      from .commands.about import AboutCommand
13:15:40    File "/usr/local/lib/python3.8/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
13:15:40      from .check import CheckCommand
13:15:40    File "/usr/local/lib/python3.8/site-packages/poetry/console/commands/check.py", line 2, in <module>
13:15:40      from poetry.factory import Factory
13:15:40    File "/usr/local/lib/python3.8/site-packages/poetry/factory.py", line 16, in <module>
13:15:40      from .packages.locker import Locker
13:15:40    File "/usr/local/lib/python3.8/site-packages/poetry/packages/__init__.py", line 2, in <module>
13:15:40      from .locker import Locker
13:15:40    File "/usr/local/lib/python3.8/site-packages/poetry/packages/locker.py", line 28, in <module>
13:15:40      from poetry.core.packages.package import Dependency
13:15:40  ImportError: cannot import name 'Dependency' from 'poetry.core.packages.package' (/usr/local/lib/python3.8/site-packages/poetry/core/packages/package.py)
```

**Comment by bdrosen96** [comment]
Looks like it is a duplicate of https://github.com/python-poetry/poetry/issues/3650. I had search issues in poetry-core and it was not there
