### ISSUE TITLE
poetry self update (from 1.1.4 to 1.1.5) fails on Windows 10

### ISSUE THREAD

**Issue by irwand** [python-poetry/poetry#3769]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

NOTE: I checked "I am on latest Poetry version" above, although not really. I was on the last release version, trying to update to the latest Poetry version.

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A. I'm trying to `poetry self update`

## Issue
I was trying to `poetry self update` ; from 1.1.4 to 1.1.5 (latest release at the moment)
Here's the console dump
```
> poetry self update
Updating to 1.1.5
Traceback (most recent call last):
  File "c:\Users\irwand\.poetry\lib\poetry\_vendor\py3.6\clikit\console_application.py", line 131, in run
  File "c:\Users\irwand\.poetry\lib\poetry\_vendor\py3.6\clikit\api\command\command.py", line 120, in handle
  File "c:\Users\irwand\.poetry\lib\poetry\_vendor\py3.6\clikit\api\command\command.py", line 171, in _do_handle
  File "c:\Users\irwand\.poetry\lib\poetry\_vendor\py3.6\cleo\commands\command.py", line 92, in wrap_handle
  File "c:\Users\irwand\.poetry\lib\poetry\console\commands\self\update.py", line 130, in handle
  File "c:\Users\irwand\.poetry\lib\poetry\console\commands\self\update.py", line 142, in update
  File "C:\Users\irwand\.pyenv\pyenv-win\versions\3.6.8\lib\shutil.py", line 500, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "C:\Users\irwand\.pyenv\pyenv-win\versions\3.6.8\lib\shutil.py", line 390, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\irwand\.pyenv\pyenv-win\versions\3.6.8\lib\shutil.py", line 390, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  File "C:\Users\irwand\.pyenv\pyenv-win\versions\3.6.8\lib\shutil.py", line 390, in _rmtree_unsafe
    _rmtree_unsafe(fullname, onerror)
  [Previous line repeated 1 more time]
  File "C:\Users\irwand\.pyenv\pyenv-win\versions\3.6.8\lib\shutil.py", line 395, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "C:\Users\irwand\.pyenv\pyenv-win\versions\3.6.8\lib\shutil.py", line 393, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [WinError 5] Access is denied: 'c:\\Users\\irwand\\.poetry\\lib\\poetry\\_vendor\\py3.6\\msgpack\\_cmsgpack.cp36-win_amd64.pyd'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\irwand\.poetry\bin\poetry", line 19, in <module>
    main()
  File "c:\Users\irwand\.poetry\lib\poetry\console\__init__.py", line 5, in main
  File "c:\Users\irwand\.poetry\lib\poetry\_vendor\py3.6\clikit\console_application.py", line 142, in run
  File "c:\Users\irwand\.poetry\lib\poetry\_vendor\py3.6\clikit\ui\components\exception_trace.py", line 232, in render
  File "c:\Users\irwand\.poetry\lib\poetry\_vendor\py3.6\clikit\ui\components\exception_trace.py", line 251, in _render_exception
ModuleNotFoundError: No module named 'crashtest.inspector'

> poetry self update -vvv
Traceback (most recent call last):
  File "c:\Users\irwand\.poetry\bin\poetry", line 17, in <module>
    from poetry.console import main
ModuleNotFoundError: No module named 'poetry.console'
```

As you can see, once the self update fails, installation is corrupted. :(

**Comment by RCJacH** [comment]
Just to add to this that uninstalling and reinstalling 1.1.5 does not fix this problem, downgrading to 1.1.4, however, does.

**Comment by Benzidrine** [comment]
Same thing with 1.1.12 just to confirm. I'm moving back to venv as this doesn't meet my needs concerning reliability.

**Comment by stuaxo** [comment]
You may have a similar issue with pip, ie if you run `pip install -U pip` on windows, as open files can't be written to there.

On pip you can get round this using python -mpip instead of just "pip", for poetry you can try "python -m poetry"

**Comment by finswimmer** [comment]
Hello @irwand,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer
