### ISSUE TITLE
Poetry 1.1.4 - "PackageInfoError - Unable to determine package info for path..." on ubuntu server

### ISSUE THREAD

**Issue by wotori** [python-poetry/poetry#3795]
I am on the latest Poetry version.
 I have searched the issues of this repo and believe that this is not a duplicate.

OS version and name: Ubuntu 20.04.2 LTS
Poetry version: 1.1.5

```
poetry install
Installing dependencies from lock file
  
  PackageInfoError

  Unable to determine package info for path: /tmp/pypoetry-git-cpppo52_ltkzs
  
  Fallback egg_info generation failed.
  
  Command ['/tmp/tmprjai3lgy/.venv/bin/python', 'setup.py', 'egg_info'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "/tmp/pypoetry-git-cpppo52_ltkzs/setup.py", line 1, in <module>
      from setuptools import setup
    File "/tmp/tmprjai3lgy/.venv/lib/python3.9/site-packages/setuptools/__init__.py", line 18, in <module>
      from setuptools.dist import Distribution
    File "/tmp/tmprjai3lgy/.venv/lib/python3.9/site-packages/_virtualenv.py", line 89, in exec_module
      old(module)
    File "/tmp/tmprjai3lgy/.venv/lib/python3.9/site-packages/setuptools/dist.py", line 34, in <module>
      from setuptools import windows_support
    File "/tmp/tmprjai3lgy/.venv/lib/python3.9/site-packages/setuptools/windows_support.py", line 2, in <module>
      import ctypes
    File "/usr/local/lib/python3.9/ctypes/__init__.py", line 8, in <module>
      from _ctypes import Union, Structure, Array
  ModuleNotFoundError: No module named '_ctypes'

  at venv/lib/python3.9/site-packages/poetry/inspection/info.py:502 in _pep517_metadata
      498│                 try:
      499│                     venv.run("python", "setup.py", "egg_info")
      500│                     return cls.from_metadata(path)
      501│                 except EnvCommandError as fbe:
    → 502│                     raise PackageInfoError(
      503│                         path, "Fallback egg_info generation failed.", fbe
      504│                     )
      505│                 finally:
      506│                     os.chdir(cwd.as_posix())

```

At the main machine I dont have such an issue. What the reason of such pproblem could be?
Thanks!

**Comment by wotori** [comment]
It was an [error](https://stackoverflow.com/questions/27022373/python3-importerror-no-module-named-ctypes-when-using-value-from-module-mul) on system side, not poetry side.
All I had to do is just to install [libffi](https://github.com/libffi/libffi).
```
sudo apt-get install libffi-dev
```
Then i had completely uninstall python and install It from .tgz source file.
