### ISSUE TITLE
poetry does not install current package in editable mode

### ISSUE THREAD

**Issue by charlax** [python-poetry/poetry#3810]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac Os Big Sur 11.2.2
- **Poetry version**: 1.1.5
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/charlax/e5d467487811056770230b8747d1bf32

## Issue

Steps to reproduce:

```bash
$ mkdir editablemode
$ cd editablemode
$ poetry init

This command will guide you through creating your pyproject.toml config.

Package name [editablemode]:
Version [0.1.0]:
Description []:
Author [charlax <redacted>, n to skip]:  n
License []:
Compatible Python versions [^3.9]:

Would you like to define your main dependencies interactively? (yes/no) [yes] no
Would you like to define your development dependencies interactively? (yes/no) [yes] no
Generated file

[tool.poetry]
name = "editablemode"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


Do you confirm generation? (yes/no) [yes] yes

$ poetry install
Creating virtualenv editablemode-iRuPsUl_-py3.9 in /Users/.../Library/Caches/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file

$ poetry run python -c "from importlib.metadata import version; print(version('editablemode'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 551, in version
    return distribution(distribution_name).version
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: editablemode
```

Indeed, the `.pth` file is missing:

```
❯ ls /Users/.../Library/Caches/pypoetry/virtualenvs/editablemode-iRuPsUl_-py3.9/lib/python3.9/site-packages
__pycache__               pip                    setuptools-53.0.0.dist-info
_distutils_hack           pip-21.0.1.dist-info   setuptools-53.0.0.virtualenv
_virtualenv.pth           pip-21.0.1.virtualenv  wheel
_virtualenv.py            pkg_resources          wheel-0.36.2.dist-info
distutils-precedence.pth  setuptools             wheel-0.36.2.virtualenv
```

My config:

```
cache-dir = "/Users/.../Library/Caches/pypoetry"
experimental.new-installer = true
installer.parallel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.path = "{cache-dir}/virtualenvs"
```

What's weird is that I have some older projects, already installed, that are in editable mode...

**Comment by charlax** [comment]
The same happens without the experimental new installer:

```bash
$ POETRY_EXPERIMENTAL_NEW_INSTALLER="" poetry install
Creating virtualenv editablemode-iRuPsUl_-py3.9 in /Users/.../Library/Caches/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file
No dependencies to install or update

$ poetry run python -c "from importlib.metadata import version; print(version('editablemode'))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 551, in version
    return distribution(distribution_name).version
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/local/Cellar/python@3.9/3.9.2_1/Frameworks/Python.framework/Versions/3.9/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: editablemode
```

**Comment by charlax** [comment]
I think I found the issue. There must be a folder with the same name as the package name:

```bash
$ rm -rf `poetry env info -p`
$ rm poetry.lock
$ mkdir editablemode
$ touch editablemode/__init__.py
$ POETRY_EXPERIMENTAL_NEW_INSTALLER="" poetry install
Creating virtualenv editablemode-iRuPsUl_-py3.9 in /Users/ca/Library/Caches/pypoetry/virtualenvs
Updating dependencies
Resolving dependencies... (0.1s)

Writing lock file
No dependencies to install or update


Installing the current project: editablemode (0.1.0)

$ poetry run python -c "from importlib.metadata import version; print(version('editablemode'))"
0.1.0
```

Wondering if this should be documented...

**Comment by david-fortini** [comment]
Did you look at the [docs](https://python-poetry.org/docs/cli/) ?
they recommend the following for your `toml` file, before version 1.1 was this the default behaviour, now you have to make it explicit.
```
[tool.poetry.dependencies]
my-package = {path = "../my/path", develop = true}
```

**Comment by charlax** [comment]
Yes, I did, including the line you're mentioning. There is those other mentions:

https://python-poetry.org/docs/cli/

> By default poetry will install your project's package everytime you run install:

https://python-poetry.org/docs/basic-usage/

> The current project is installed in editable mode by default.

The thing is, this happens only (it seems) if there is a folder with the same name as the package name.

**Comment by abn** [comment]
@charlax from what I can tell, you need to specify the package name if it differs from the canonical form of the project's name in `pyproject.toml`. See [here](https://python-poetry.org/docs/pyproject/#packages) for more information.

```toml
[tool.poetry]
name = "editablemode"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
packages = [
    { include = "noteditable" }
]

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

If you have a src directory layout you would do something like this.

```toml
packages = [
    { include = "noteditable", from = "src" }
]
```

**Comment by charlax** [comment]
Yes, that makes sense. I'd like to make a PR to clarify that in more places in the documentation (for instance, in the sentences that I'm quoting above). Would that be ok?

**Comment by sinoroc** [comment]
@charlax I might be wrong, but I think there are already PRs for this. At least I am pretty sure the lack of clarity of the doc on that topic has already been raised, so it might be worth checking for similar tickets before starting your PR.

**Comment by abn** [comment]
Happy to review documentation improvements. Closing this as this a project configuration error.
