### ISSUE TITLE
bootstrap: remove dependency on system provided pip

### ISSUE THREAD

**Issue by abn** [python-poetry/poetry#3843]
We should do a check for pip, as pip is not always present. If it's not present we have one of two options.

1. Automatically execute `python -m ensurepip`. 
2. Error out, instructing user to install pip and hint at 1, since they may want to use distro specific installation. 

Alternatively, `virtualenv` wheel should be usable without installation I think. That would make a cleaner approach.
1. Download latest wheel.
2. Insert wheel to site.
3. Execute required commands.

_Originally posted by @abn in https://github.com/python-poetry/poetry/pull/3706#r598254393_

**Comment by matangover** [comment]
I also encountered this but I initially couldn't find it in the issue tracker. Here is the error I got, in case it helps someone find this:

```shellsession
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py | python3 -
[...]
Installing Poetry (1.1.6): Creating environment
Traceback (most recent call last):
  File "<stdin>", line 831, in <module>
  File "<stdin>", line 827, in main
  File "<stdin>", line 440, in run
  File "<stdin>", line 462, in install
  File "<stdin>", line 526, in make_env
ModuleNotFoundError: No module named 'virtualenv'
```

Note: This happens by default on Ubuntu where the `python3` package does not come with pip.
