### ISSUE TITLE
Poetry Solver Error with Vanilla Project

### ISSUE THREAD

**Issue by tylermanning** [python-poetry/poetry#3898]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Platform: ubuntu 18.04**: 
- **Poetry version 1.1.5**: 
- **Link of a [Gist](https://gist.github.com/tylermanning/196f0b8e4e19dbd4c401810d662a70ce) with the contents of your pyproject.toml file**: 

## Issue

I installed poetry and tried creating a vanilla project with no special configs. Once i loaded the poetry shell and tried installing dependencies i got the following errors. Even just `poetry show` threw these errors:

```
(test-proj-WTfosmZH-py3.8) [user1@my-machine01 ~/test-proj]$ poetry show -vvv
Using virtualenv: /home/user1/.cache/pypoetry/virtualenvs/test-proj-WTfosmZH-py3.8

  Stack trace:

  6  ~/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py:131 in run
Traceback (most recent call last):
  File "/home/user1/.poetry/lib/poetry/puzzle/solver.py", line 233, in _solve
    result = resolve_version(
  File "/home/user1/.poetry/lib/poetry/mixology/__init__.py", line 7, in resolve_version
    return solver.solve()
  File "/home/user1/.poetry/lib/poetry/mixology/version_solver.py", line 83, in solve
    self._propagate(next)
  File "/home/user1/.poetry/lib/poetry/mixology/version_solver.py", line 123, in _propagate
    root_cause = self._resolve_conflict(incompatibility)
  File "/home/user1/.poetry/lib/poetry/mixology/version_solver.py", line 321, in _resolve_conflict
    raise SolveFailure(incompatibility)
poetry.mixology.failure.SolveFailure: Because test-proj depends on pytest (^5.2) which doesn't match any versions, version solving failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/user1/.poetry/lib/poetry/console/commands/show.py", line 82, in handle
    ops = solver.solve()
  File "/home/user1/.poetry/lib/poetry/puzzle/solver.py", line 65, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/home/user1/.poetry/lib/poetry/puzzle/solver.py", line 241, in _solve
    raise SolverProblemError(e)
poetry.puzzle.exceptions.SolverProblemError: Because test-proj depends on pytest (^5.2) which doesn't match any versions, version solving failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.poetry/bin/poetry", line 17, in <module>
    main()
  File "/home/user1/.poetry/lib/poetry/console/__init__.py", line 5, in main
    return Application().run()
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/console_application.py", line 142, in run
    trace.render(io, simple=isinstance(e, CliKitException))
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/ui/components/exception_trace.py", line 232, in render
    return self._render_exception(io, self._exception)
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/ui/components/exception_trace.py", line 257, in _render_exception
    self._render_trace(io, inspector.frames)
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/ui/components/exception_trace.py", line 381, in _render_trace
    self._render_line(
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/ui/components/exception_trace.py", line 402, in _render_line
    io.write_line("{}{}".format(indent * " ", line))
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/cleo/io/io_mixin.py", line 65, in write_line
    super(IOMixin, self).write_line(string, flags)
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/api/io/io.py", line 66, in write_line
    self._output.write_line(string, flags=flags)
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/api/io/output.py", line 69, in write_line
    self.write(string, flags=flags, new_line=True)
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/api/io/output.py", line 61, in write
    self._stream.write(to_str(formatted))
  File "/home/user1/.poetry/lib/poetry/_vendor/py3.8/clikit/io/output_stream/stream_output_stream.py", line 24, in write
    self._stream.write(string)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2502' in position 27: ordinal not in range(256)
```

**Comment by tylermanning** [comment]
It looks like the last error was due to a string not being utf-8 for some odd reason. I found a work around by doing this:

```
 17     def write(self, string):  # type: (str) -> None
 18         """
 19         Writes a string to the stream.
 20         """
 21         if self.is_closed():
 22             raise io.UnsupportedOperation("Cannot write to a closed input.")
 23         try:
 24             self._stream.write(string)
 25             self._stream.flush()
 26         except UnicodeEncodeError:
 28             self._stream.write(str(string.encode("utf-8")))
 29             self._stream.flush()
```
But I have no idea if this has unintended consequences. At least i can add dependencies now...

**Comment by tylermanning** [comment]
Some updates. The base system was a clean Ubuntu 18.04. I tried uninstalling poetry and reinstalling but i get the same problem each time I try to add dependencies to a project. The base python of the system is Python 3.8.5 located here: /opt/anaconda/latest/bin/python

Steps to reproduce:
1. curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
2. source the thing so poetry can be used immediately
3. create a new project with poetry
4. launch a poetry shell inside it
5. Try `poetry show` or `poetry add [some package]` and the error will be thrown

**Comment by abn** [comment]
@tylermanning do you have this issue if installing poetry using `pipx` or via `pip`?

Can you please try the fix at #PULL_ID.

### Using pipx
```sh
pipx install poetry
```
Additionally, if the problem persists you might want to check the system locale.

**Comment by tylermanning** [comment]
@abn I installed it using `pipx` same issue. This is from a brand new poetry package that was created, with nothing added:

```
(my-proj-3x5DuWQ5-py3.8) [user1@my-machine ~/my-proj]$ poetry show -vvv
Using virtualenv: /home/user1/.cache/pypoetry/virtualenvs/my-proj-3x5DuWQ5-py3.8

  Stack trace:

  6  ~/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/console_application.py:131 in run
Traceback (most recent call last):
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/puzzle/solver.py", line 233, in _solve
    result = resolve_version(
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/mixology/__init__.py", line 7, in resolve_version
    return solver.solve()
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/mixology/version_solver.py", line 83, in solve
    self._propagate(next)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/mixology/version_solver.py", line 123, in _propagate
    root_cause = self._resolve_conflict(incompatibility)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/mixology/version_solver.py", line 321, in _resolve_conflict
    raise SolveFailure(incompatibility)
poetry.mixology.failure.SolveFailure: Because my-proj depends on pytest (^5.2) which doesn't match any versions, version solving failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/command/command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/command/command.py", line 171, in _do_handle
    return getattr(handler, handler_method)(args, io, self)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/cleo/commands/command.py", line 92, in wrap_handle
    return self.handle()
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/console/commands/show.py", line 82, in handle
    ops = solver.solve()
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/puzzle/solver.py", line 65, in solve
    packages, depths = self._solve(use_latest=use_latest)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/puzzle/solver.py", line 241, in _solve
    raise SolverProblemError(e)
poetry.puzzle.exceptions.SolverProblemError: Because my-proj depends on pytest (^5.2) which doesn't match any versions, version solving failed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user1/.local/bin/poetry", line 8, in <module>
    sys.exit(main())
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/poetry/console/__init__.py", line 5, in main
    return Application().run()
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/console_application.py", line 142, in run
    trace.render(io, simple=isinstance(e, CliKitException))
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/ui/components/exception_trace.py", line 232, in render
    return self._render_exception(io, self._exception)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/ui/components/exception_trace.py", line 257, in _render_exception
    self._render_trace(io, inspector.frames)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/ui/components/exception_trace.py", line 381, in _render_trace
    self._render_line(
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/ui/components/exception_trace.py", line 402, in _render_line
    io.write_line("{}{}".format(indent * " ", line))
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/cleo/io/io_mixin.py", line 65, in write_line
    super(IOMixin, self).write_line(string, flags)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/io/io.py", line 66, in write_line
    self._output.write_line(string, flags=flags)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/io/output.py", line 69, in write_line
    self.write(string, flags=flags, new_line=True)
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/api/io/output.py", line 61, in write
    self._stream.write(to_str(formatted))
  File "/home/user1/.local/pipx/venvs/poetry/lib/python3.8/site-packages/clikit/io/output_stream/stream_output_stream.py", line 24, in write
    self._stream.write(string)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u2502' in position 27: ordinal not in range(256)
```

**Comment by abn** [comment]
This sounds like a system locale issue more than a poetry. Can you post the output of `locale`?

Here is a succinct explanation. https://stackoverflow.com/a/57298412

**Comment by tylermanning** [comment]
@abn You're right. The output of `locale` is:
```
LANG=en_US
LANGUAGE=en_US:
LC_CTYPE="en_US"
LC_NUMERIC="en_US"
LC_TIME="en_US"
LC_COLLATE="en_US"
LC_MONETARY="en_US"
LC_MESSAGES="en_US"
LC_PAPER="en_US"
LC_NAME="en_US"
LC_ADDRESS="en_US"
LC_TELEPHONE="en_US"
LC_MEASUREMENT="en_US"
LC_IDENTIFICATION="en_US"
LC_ALL=
```
So i added `export PYTHONUTF8=1` to my `~/.bash_profile` and the UnicodeEncodeError is gone. Hoorary! 
Thanks a lot for your help. I spent like 5h yesterday trying to figure it out. I should have asked sooner.

**Comment by abn** [comment]
Happy to have helped.
