### ISSUE TITLE
Poetry commands got errors

### ISSUE THREAD

**Issue by tjapro** [python-poetry/poetry#4075]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux .... 5.10.17-v7l+ #1414 SMP Fri Apr 30 13:20:47 BST 2021 armv7l GNU/Linux
- **Poetry version**: ----

## Issue
I installed Poetry today via curl and reboot my RaspberryPi 4.
Then I try to run any poetry command, and got this errors:
```
Traceback (most recent call last):
  File "/home/pi/.poetry/bin/poetry", line 17, in <module>
    from poetry.console import main
  File "/home/pi/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/pi/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/home/pi/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/pi/.poetry/lib/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/home/pi/.poetry/lib/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/home/pi/.poetry/lib/poetry/repositories/pypi_repository.py", line 33, in <module>
    from ..inspection.info import PackageInfo
  File "/home/pi/.poetry/lib/poetry/inspection/info.py", line 25, in <module>
    from poetry.utils.env import EnvCommandError
  File "/home/pi/.poetry/lib/poetry/utils/env.py", line 21, in <module>
    import packaging.tags
  File "/home/pi/.poetry/lib/poetry/_vendor/py3.7/poetry/core/_vendor/packaging/tags.py", line 7, in <module>
    import distutils.util
ModuleNotFoundError: No module named 'distutils.util'
```
Any command: --version, shell, new, ....

**Comment by finswimmer** [comment]
Hello @tjapro,

for some reasons this module is not shipped for python on raspberry by default. You have to install it by your own:

```
sudo apt-get install python3-distutils
```

fin swimmer
