### ISSUE TITLE
install-poetry fails with PIP_REQUIRE_VIRTUALENV

### ISSUE THREAD

**Issue by neersighted** [python-poetry/poetry#4089]
Because `install-poetry.py` does not check the exit status of `pip` when bootstrapping the temporary `virtualenv` module, users are confronted with an odd error when they have `$PIP_REQUIRE_VIRTUALENV` set in their environment.

Output looks something like the following:

```
Installing Poetry...
Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/neersighted/.local/share/pypoetry/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.6): Creating environment
Traceback (most recent call last):
  File "<stdin>", line 808, in <module>
  File "<stdin>", line 804, in main
  File "<stdin>", line 417, in run
  File "<stdin>", line 439, in install
  File "<stdin>", line 505, in make_env
AttributeError: module 'virtualenv' has no attribute 'cli_run'
```

This can easily be corrected by invoking the script again with `PIP_REQUIRE_VIRTUALENV=` to 'reset' the environmental variable.

For some background:
Pip provides this opt-in so that users can ensure they don't accidentally clutter or break their system installation of Python. Normally when this feature blocks execution of a command, it is called out to the user like this:

```
ERROR: Could not find an activated virtualenv (required).
```

Because pip is being invoked by `install-poetry.py` without checking exit status or output, this information is lost.

I would suggest explicitly resetting `PIP_REQUIRE_VIRTUALENV` in the installer script unconditionally to ensure that this interaction doesn't cause the failure above.

**Comment by neersighted** [comment]
The installer changes proposed in #4099 greatly simplify the virtualenv-related code and solve half this issue (unexplained errors/discarded information). Now we just have to determine if the installer breaking due to this setting is a bug, or if the user is responsible for unsetting it before running the installer.

Thoughts, @sdispater?

**Comment by neersighted** [comment]
I was wrong about this -- #4099 with actually entirely solve this issue as Poetry will no longer invoke `pip` outside a virtualenv! Nice!
