### ISSUE TITLE
Add optional flag to "poetry install": on failure, nuke virtualenv and retry

### ISSUE THREAD

**Issue by pieter-lautus** [python-poetry/poetry#4149]
Sometimes, there are issues with packages (not with poetry itself), which cause the packages to fail on upgrade from certain older versions.

One example is ansible >= 3.0, which in their infinite wisdom decided that upgrading from ansible < 3.0 should require manual intervention:

```
poetry install
Installing dependencies from lock file

Package operations: 3 installs, 17 updates, 0 removals

  • Installing ansible-core (2.11.1): Failed

  EnvCommandError

  Command ['/home/r2d2/.cache/pypoetry/virtualenvs/lautus-ansible-cM3A0zsx-py3.8/bin/pip', 'install', '--no-deps', 'file:///home/r2d2/.cache/pypoetry/artifacts/3c/29/ef/173bd7aace316994d575c99084871c6308a8e1205a90d5331658a020fc/ansible-core-2.11.1.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/r2d2/.cache/pypoetry/artifacts/3c/29/ef/173bd7aace316994d575c99084871c6308a8e1205a90d5331658a020fc/ansible-core-2.11.1.tar.gz
  Building wheels for collected packages: ansible-core
    Building wheel for ansible-core (setup.py): started
    Building wheel for ansible-core (setup.py): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/r2d2/.cache/pypoetry/virtualenvs/lautus-ansible-cM3A0zsx-py3.8/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-dd8789mc/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-dd8789mc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-mna49npz
         cwd: /tmp/pip-req-build-dd8789mc/
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-dd8789mc/setup.py", line 120, in <module>
        _validate_install_ansible_core()
      File "/tmp/pip-req-build-dd8789mc/setup.py", line 91, in _validate_install_ansible_core
        raise RuntimeError(
    RuntimeError:
    
        ****************************************************************************
    
        Cannot install ansible-core with a pre-existing ansible==2.8.11
        installation.
    
        Installing ansible-core with ansible-2.9 or older, or ansible-base-2.10
        currently installed with pip is known to cause problems. Please uninstall
        ansible and install the new version:
    
            pip uninstall ansible
            pip install ansible-core
    
        If you want to skip the conflict checks and manually resolve any issues
        afterwards, set the ANSIBLE_SKIP_CONFLICT_CHECK environment variable:
    
            ANSIBLE_SKIP_CONFLICT_CHECK=1 pip install ansible-core
    
        ****************************************************************************
    
    ----------------------------------------
    ERROR: Failed building wheel for ansible-core
    Running setup.py clean for ansible-core
    ERROR: Command errored out with exit status 1:
     command: /home/r2d2/.cache/pypoetry/virtualenvs/lautus-ansible-cM3A0zsx-py3.8/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-dd8789mc/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-dd8789mc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
         cwd: /tmp/pip-req-build-dd8789mc
    Complete output (27 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-dd8789mc/setup.py", line 120, in <module>
        _validate_install_ansible_core()
      File "/tmp/pip-req-build-dd8789mc/setup.py", line 91, in _validate_install_ansible_core
        raise RuntimeError(
    RuntimeError:
    
        ****************************************************************************
    
        Cannot install ansible-core with a pre-existing ansible==2.8.11
        installation.
    
        Installing ansible-core with ansible-2.9 or older, or ansible-base-2.10
        currently installed with pip is known to cause problems. Please uninstall
        ansible and install the new version:
    
            pip uninstall ansible
            pip install ansible-core
    
        If you want to skip the conflict checks and manually resolve any issues
        afterwards, set the ANSIBLE_SKIP_CONFLICT_CHECK environment variable:
    
            ANSIBLE_SKIP_CONFLICT_CHECK=1 pip install ansible-core
    
        ****************************************************************************
    
    ----------------------------------------
    ERROR: Failed cleaning build dir for ansible-core
  Failed to build ansible-core
  Installing collected packages: ansible-core
      Running setup.py install for ansible-core: started
      Running setup.py install for ansible-core: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /home/r2d2/.cache/pypoetry/virtualenvs/lautus-ansible-cM3A0zsx-py3.8/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-dd8789mc/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-dd8789mc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jdfv89y5/install-record.txt --single-version-externally-managed --compile --install-headers /home/r2d2/.cache/pypoetry/virtualenvs/lautus-ansible-cM3A0zsx-py3.8/include/site/python3.8/ansible-core
           cwd: /tmp/pip-req-build-dd8789mc/
      Complete output (27 lines):
      Traceback (most recent call last):
        File "<string>", line 1, in <module>
        File "/tmp/pip-req-build-dd8789mc/setup.py", line 120, in <module>
          _validate_install_ansible_core()
        File "/tmp/pip-req-build-dd8789mc/setup.py", line 91, in _validate_install_ansible_core
          raise RuntimeError(
      RuntimeError:
      
          ****************************************************************************
      
          Cannot install ansible-core with a pre-existing ansible==2.8.11
          installation.
      
          Installing ansible-core with ansible-2.9 or older, or ansible-base-2.10
          currently installed with pip is known to cause problems. Please uninstall
          ansible and install the new version:
      
              pip uninstall ansible
              pip install ansible-core
      
          If you want to skip the conflict checks and manually resolve any issues
          afterwards, set the ANSIBLE_SKIP_CONFLICT_CHECK environment variable:
      
              ANSIBLE_SKIP_CONFLICT_CHECK=1 pip install ansible-core
      
          ****************************************************************************
      
      ----------------------------------------
  ERROR: Command errored out with exit status 1: /home/r2d2/.cache/pypoetry/virtualenvs/lautus-ansible-cM3A0zsx-py3.8/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-req-build-dd8789mc/setup.py'"'"'; __file__='"'"'/tmp/pip-req-build-dd8789mc/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-jdfv89y5/install-record.txt --single-version-externally-managed --compile --install-headers /home/r2d2/.cache/pypoetry/virtualenvs/lautus-ansible-cM3A0zsx-py3.8/include/site/python3.8/ansible-core Check the logs for full command output.
  WARNING: You are using pip version 21.0.1; however, version 21.1.2 is available.
  You should consider upgrading via the '/home/r2d2/.cache/pypoetry/virtualenvs/lautus-ansible-cM3A0zsx-py3.8/bin/python -m pip install --upgrade pip' command.
  
```

In principle, though, this situation can occur with any package, either by bug of by design, not just ansible.

It would be useful if "poetry install" had some sort of "--force-something" flag whose semantics are: if any package fails to install, first do the equivalent of "poetry env remove", then retry the install in a clean environment.

**Comment by dimbleby** [comment]
probably time to acknowledge that no-one seems to be interested in doing this - if it's even desirable - and close it out

**Comment by neersighted** [comment]
This very much seems like a niche (mis)feature; this will become even less relevant in the future as we migrate away from pip (and ansible's check doesn't work with Poetry today anyway, as we build in an isolated environment). With that in mind, it seems like this is not solving a real problem most users of Poetry will ever face.
