### ISSUE TITLE
Poetry improperly installs sqlalchemy2 stubs

### ISSUE THREAD

**Issue by kracekumar** [python-poetry/poetry#4177]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  11.2.3, Mac OSX 
- **Poetry version**: 1.1.4
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 
- https://gist.github.com/kracekumar/c441369b51dfb8c22ffea26f065f874e

## Issue

When I run the mypy using `poetry run`, the command doesn't load sqlalchemy plugin.

```bash
$poetry run mypy out/flask_sqlalchemy/model.pyi --config=mypy.ini
Error constructing plugin instance of SQLAlchemyPlugin

Traceback (most recent call last):
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/bin/mypy", line 8, in <module>
    sys.exit(console_entry())
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/mypy/__main__.py", line 11, in console_entry
    main(None, sys.stdout, sys.stderr)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/mypy/main.py", line 98, in main
    res = build.build(sources, options, None, flush_errors, fscache, stdout, stderr)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/mypy/build.py", line 179, in build
    result = _build(
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/mypy/build.py", line 229, in _build
    plugin, snapshot = load_plugins(options, errors, stdout, extra_plugins)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/mypy/build.py", line 475, in load_plugins
    custom_plugins, snapshot = load_plugins_from_config(options, errors, stdout)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/mypy/build.py", line 454, in load_plugins_from_config
    snapshot[module_name] = take_module_snapshot(module)
  File "/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/mypy/build.py", line 494, in take_module_snapshot
    with open(module.__file__, 'rb') as f:
NotADirectoryError: [Errno 20] Not a directory: '/Users/user/Library/Caches/pypoetry/virtualenvs/flask-sqlalchemy-KzL4aHKU-py3.9/lib/python3.9/site-packages/SQLAlchemy-1.4.18-py3.9-macosx-11-x86_64.egg/sqlalchemy/ext/mypy/plugin.py'
...
$poetry run -vvv mypy out/flask_sqlalchemy/model.pyi --config=mypy.ini

  FileNotFoundError

  [Errno 2] No such file or directory

  at /usr/local/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/os.py:607 in _execvpe
       603│         path_list = map(fsencode, path_list)
       604│     for dir in path_list:
       605│         fullname = path.join(dir, file)
       606│         try:
    →  607│             exec_func(fullname, *argrest)
       608│         except (FileNotFoundError, NotADirectoryError) as e:
       609│             last_exc = e
       610│         except OSError as e:
       611│             last_exc = e
```
Whereas I install sqlalchemy2-stubs with pip and run normally I don't see the error.
```bash
$ mypy out/flask_sqlalchemy/model.pyi --config=mypy.ini
out/flask_sqlalchemy/__init__.pyi:37: error: Signature of "get_bind" incompatible with supertype "Session"
out/flask_sqlalchemy/__init__.pyi:117: error: Variable "flask_sqlalchemy.SQLAlchemy.Model" is not valid as a type
out/flask_sqlalchemy/__init__.pyi:117: note: See https://mypy.readthedocs.io/en/stable/common_issues.html#variables-vs-type-aliases
Found 2 errors in 1 file (checked 1 source file)
```

mypy config
```
$cat mypy.ini
[mypy]
plugins = sqlalchemy.ext.mypy.plugin
```
[SQLAlchemy stubs issue from the repo.](https://github.com/sqlalchemy/sqlalchemy2-stubs/issues/118#issuecomment-860230939)
[Docs](https://docs.sqlalchemy.org/en/14/orm/extensions/mypy.html)

**Comment by Jarvis1Tube** [comment]
Hi, @kracekumar! I use sqlalchemy2-stubs in my project too, but I added this dependency explicit way:
```
[tool.poetry.dev-dependencies]
...
sqlalchemy2-stubs = "^0.0.2-alpha.8"
```
So, I tried to do `poetry run mypy specific/path/to/file --config=mypy.ini` and it worked.

**Comment by kracekumar** [comment]
@Jarvis1Tube Thanks. Adding explicit version to dependencies works.
