### ISSUE TITLE
DEPRECATION: A future pip version will change local packages to be built in-place

### ISSUE THREAD

**Issue by AndreasWJ** [python-poetry/poetry#4178]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Windows 10 Home, Version 20H2, 19042.1052**: 
- **1.16**: 
pyproject.toml:
```
[tool.poetry]
name = "neuralnetworks"
version = "1.0"
description = "."
authors = ["."]
[tool.poetry.dependencies]
python = "~=3.8"
requests = "~=2.25.0"
youtubeuploader = {git = "https://github.com/AndreasWJ/YouTubeUploader.git"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0a5"]
build-backend = "poetry.core.masonry.api"

```

## Issue

I added a package youtubeuploader to my pyproject.toml:
`youtubeuploader = {git = "https://github.com/AndreasWJ/YouTubeUploader.git"}`

Now, whenever I run: `poetry install -vvv`, I receive a lengthy error message from which I can't discern any particular reason:
```
Using virtualenv: C:\Users\known\AppData\Local\pypoetry\Cache\virtualenvs\neuralnetworks-1dOnRCsH-py3.8
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 1 install, 0 updates, 0 removals, 35 skipped
  • Installing youtubeuploader (1.0 bd753c7)

  Stack trace:

  9  ~\.poetry\lib\poetry\installation\executor.py:202 in _execute_operation
      200│
      201│             try:
    → 202│                 result = self._do_execute_operation(operation)
      203│             except EnvCommandError as e:
      204│                 if e.e.returncode == -2:

  8  ~\.poetry\lib\poetry\installation\executor.py:276 in _do_execute_operation
      274│             return 0
      275│
    → 276│         result = getattr(self, "_execute_{}".format(method))(operation)
      277│
      278│         if result != 0:

  7  ~\.poetry\lib\poetry\installation\executor.py:411 in _execute_install
      409│
      410│     def _execute_install(self, operation):  # type: (Install) -> None
    → 411│         return self._install(operation)
      412│
      413│     def _execute_update(self, operation):  # type: (Update) -> None

  6  ~\.poetry\lib\poetry\installation\executor.py:430 in _install
      428│
      429│         if package.source_type == "git":
    → 430│             return self._install_git(operation)
      431│
      432│         if package.source_type == "file":

  5  ~\.poetry\lib\poetry\installation\executor.py:580 in _install_git
      578│         package._source_url = str(src_dir)
      579│
    → 580│         return self._install_directory(operation)
      581│
      582│     def _download(self, operation):  # type: (Operation) -> Path

  4  ~\.poetry\lib\poetry\installation\executor.py:549 in _install_directory
      547│         args.append(req)
      548│
    → 549│         return self.run_pip(*args)
      550│
      551│     def _install_git(self, operation):

  3  ~\.poetry\lib\poetry\installation\executor.py:300 in run_pip
      298│     def run_pip(self, *args, **kwargs):  # type: (...) -> int
      299│         try:
    → 300│             self._env.run_pip(*args, **kwargs)
      301│         except EnvCommandError as e:
      302│             output = decode(e.e.output)

  2  ~\.poetry\lib\poetry\utils\env.py:1043 in run_pip
      1041│         pip = self.get_pip_command()
      1042│         cmd = pip + list(args)
    → 1043│         return self._run(cmd, **kwargs)
      1044│
      1045│     def _run(self, cmd, **kwargs):

  1  ~\.poetry\lib\poetry\utils\env.py:1325 in _run
      1323│     def _run(self, cmd, **kwargs):
      1324│         kwargs["env"] = self.get_temp_environ(environ=kwargs.get("env"))
    → 1325│         return super(VirtualEnv, self)._run(cmd, **kwargs)
      1326│
      1327│     def get_temp_environ(

  EnvCommandError

  Command C:\Users\known\AppData\Local\pypoetry\Cache\virtualenvs\neuralnetworks-1dOnRCsH-py3.8\Scripts\pip.exe install --no-deps -U C:\Users\known\AppData\Local\pypoetry\Cache\virtualenvs\neuralnetworks-1dOnRCsH-py3.8\src\youtubeuploader errored with the following return code 1, and output:
  Processing c:\users\known\appdata\local\pypoetry\cache\virtualenvs\neuralnetworks-1donrcsh-py3.8\src\youtubeuploader
    DEPRECATION: A future pip version will change local packages to be built in-place without first copying to a temporary directory. We recommend you use --use-feature=in-tree-build to test your packages with this new behavior before it becomes the default.
     pip 21.3 will remove support for this functionality. You can find discussion regarding this at https://github.com/pypa/pip/issues/7555.
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: 'c:\users\known\appdata\local\pypoetry\cache\virtualenvs\neuralnetworks-1donrcsh-py3.8\scripts\python.exe' 'c:\users\known\appdata\local\pypoetry\cache\virtualenvs\neuralnetworks-1donrcsh-py3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\known\AppData\Local\Temp\tmpjrxzt9jh'
           cwd: C:\Users\known\AppData\Local\Temp\pip-req-build-cu27o5bt
      Complete output (16 lines):
      Traceback (most recent call last):
        File "c:\users\known\appdata\local\pypoetry\cache\virtualenvs\neuralnetworks-1donrcsh-py3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 280, in <module>
          main()
        File "c:\users\known\appdata\local\pypoetry\cache\virtualenvs\neuralnetworks-1donrcsh-py3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "c:\users\known\appdata\local\pypoetry\cache\virtualenvs\neuralnetworks-1donrcsh-py3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 133, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "C:\Users\known\AppData\Local\Temp\pip-build-env-yyoe00bf\overlay\Lib\site-packages\poetry\core\masonry\api.py", line 43, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
        File "C:\Users\known\AppData\Local\Temp\pip-build-env-yyoe00bf\overlay\Lib\site-packages\poetry\core\masonry\builders\wheel.py", line 58, in __init__
          super(WheelBuilder, self).__init__(poetry, executable=executable)
        File "C:\Users\known\AppData\Local\Temp\pip-build-env-yyoe00bf\overlay\Lib\site-packages\poetry\core\masonry\builders\builder.py", line 91, in __init__
          self._module = Module(
        File "C:\Users\known\AppData\Local\Temp\pip-build-env-yyoe00bf\overlay\Lib\site-packages\poetry\core\masonry\utils\module.py", line 67, in __init__
          raise ModuleOrPackageNotFound(
      poetry.core.masonry.utils.module.ModuleOrPackageNotFound: No file/folder found for package youtubeuploader
      ----------------------------------------
  WARNING: Discarding file:///C:/Users/known/AppData/Local/pypoetry/Cache/virtualenvs/neuralnetworks-1dOnRCsH-py3.8/src/youtubeuploader. Command errored out with exit status 1: 'c:\users\known\appdata\local\pypoetry\cache\virtualenvs\neuralnetworks-1donrcsh-py3.8\scripts\python.exe' 'c:\users\known\appdata\local\pypoetry\cache\virtualenvs\neuralnetworks-1donrcsh-py3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\known\AppData\Local\Temp\tmpjrxzt9jh' Check the logs for full command output.
  ERROR: Command errored out with exit status 1: 'c:\users\known\appdata\local\pypoetry\cache\virtualenvs\neuralnetworks-1donrcsh-py3.8\scripts\python.exe' 'c:\users\known\appdata\local\pypoetry\cache\virtualenvs\neuralnetworks-1donrcsh-py3.8\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\known\AppData\Local\Temp\tmpjrxzt9jh' Check the logs for full command output.


  at ~\.poetry\lib\poetry\utils\env.py:1075 in _run
      1071│                 output = subprocess.check_output(
      1072│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1073│                 )
      1074│         except CalledProcessError as e:
    → 1075│             raise EnvCommandError(e, input=input_)
      1076│
      1077│         return decode(output)
      1078│
      1079│     def execute(self, bin, *args, **kwargs):
```

**Comment by J-M0** [comment]
When I try to view your YouTubeUploader repo, I get a 404 error. Is your repo public?
