### ISSUE TITLE
Poetry not install in Python 3.6.10

### ISSUE THREAD

**Issue by hebertjulio** [python-poetry/poetry#4268]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Fedora 34 (Kernel 5.12.13-300.fc34.x86_64)**: 
- **1.1.6**: 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

Whe I typing pip install poetry using Python 3.6.10, I get error below.

```
Command "/home/hebert/.pyenv/versions/3.6.10/bin/python3.6 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-d6q6miao --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=40.6.0 wheel "cffi>=1.12; platform_python_implementation != 'PyPy'" setuptools-rust>=0.11.4" failed with error code -11 in None
Exception information:
Traceback (most recent call last):
  File "/home/hebert/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 143, in main
    status = self.run(options, args)
  File "/home/hebert/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 318, in run
    resolver.resolve(requirement_set)
  File "/home/hebert/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pip/_internal/resolve.py", line 102, in resolve
    self._resolve_one(requirement_set, req)
  File "/home/hebert/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pip/_internal/resolve.py", line 256, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/home/hebert/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pip/_internal/resolve.py", line 209, in _get_abstract_dist_for
    self.require_hashes
  File "/home/hebert/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 298, in prepare_linked_requirement
    abstract_dist.prep_for_dist(finder, self.build_isolation)
  File "/home/hebert/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pip/_internal/operations/prepare.py", line 109, in prep_for_dist
    "Installing build dependencies"
  File "/home/hebert/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pip/_internal/build_env.py", line 122, in install_requirements
    call_subprocess(args, show_stdout=False, spinner=spinner)
  File "/home/hebert/.pyenv/versions/3.6.10/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 705, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/home/hebert/.pyenv/versions/3.6.10/bin/python3.6 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-d6q6miao --no-warn-script-location -v --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools>=40.6.0 wheel "cffi>=1.12; platform_python_implementation != 'PyPy'" setuptools-rust>=0.11.4" failed with error code -11 in None
You are using pip version 18.1, however version 21.1.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

**Comment by finswimmer** [comment]
Hello @hebertjulio,

please be aware that installing poetry with pip is not recommended. Please use the recommended installer script or pipx instead.

Regarding you issue: You are using a very old pip version. Please upgrade as suggested and try again.

Thanks!

fin swimmer

**Comment by hebertjulio** [comment]
Great! Install poetry by installer script work! Thanks :smile:
