### ISSUE TITLE
Issue with my local pyenv/python/poetry versions

### ISSUE THREAD

**Issue by scipe** [python-poetry/poetry#4272]
Hi guys.

I hit the issue on my mac.
Can not run poetry even with reinstall that with different ways (brew or poetry-install script)

Versions:
- macos: 11.2.3
- python: Python 2.7.16
- python3: Python 3.9.6
- poetry: 1.1.7 (brew)

Brew test (same issue when I try to use poetry):

Short report: 
```AttributeError: module 'json' has no attribute 'loads'```

Full report:
```> brew test poetry
==> Testing poetry
==> /usr/local/Cellar/poetry/1.1.7/bin/poetry --version
Traceback (most recent call last):
  File "/usr/local/Cellar/poetry/1.1.7/bin/poetry", line 8, in <module>
    from poetry.console import main
  File "/usr/local/Cellar/poetry/1.1.7/libexec/lib/python3.9/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/local/Cellar/poetry/1.1.7/libexec/lib/python3.9/site-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/usr/local/Cellar/poetry/1.1.7/libexec/lib/python3.9/site-packages/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/usr/local/Cellar/poetry/1.1.7/libexec/lib/python3.9/site-packages/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/usr/local/Cellar/poetry/1.1.7/libexec/lib/python3.9/site-packages/poetry/factory.py", line 9, in <module>
    from poetry.core.factory import Factory as BaseFactory
  File "/usr/local/Cellar/poetry/1.1.7/libexec/vendor/lib/python3.9/site-packages/poetry/core/factory.py", line 13, in <module>
    from .json import validate_object
  File "/usr/local/Cellar/poetry/1.1.7/libexec/vendor/lib/python3.9/site-packages/poetry/core/json/__init__.py", line 7, in <module>
    from jsonschema import Draft7Validator
  File "/usr/local/Cellar/poetry/1.1.7/libexec/vendor/lib/python3.9/site-packages/poetry/core/_vendor/jsonschema/__init__.py", line 22, in <module>
    from jsonschema.validators import (
  File "/usr/local/Cellar/poetry/1.1.7/libexec/vendor/lib/python3.9/site-packages/poetry/core/_vendor/jsonschema/validators.py", line 446, in <module>
    meta_schema=_utils.load_schema("draft3"),
  File "/usr/local/Cellar/poetry/1.1.7/libexec/vendor/lib/python3.9/site-packages/poetry/core/_vendor/jsonschema/_utils.py", line 58, in load_schema
    return json.loads(data)
AttributeError: module 'json' has no attribute 'loads'
Error: poetry: failed
An exception occurred within a child process:
  Minitest::Assertion: Expected: 0
  Actual: 1
```

Any ideas?

**Comment by finswimmer** [comment]
Hello @scipe,

I don't know what your command does, but do you have a json.py within the folder you are running it? If so, rename it or switch to another folder.

fin swimmer

**Comment by scipe** [comment]
@finswimmer you talking about `brew test poetry` it's just run a test case for poetry from brew repo. And it's small check, just `/usr/local/Cellar/poetry/1.1.7/bin/poetry --version` eq to `poetry --version`. 

And no, I don't have anything like json.py in my folders.

**Comment by scipe** [comment]
I still thinking that it's a problem with version of python or smth like that..

**Comment by scipe** [comment]
The issue was python3.9 installed from brew.
Steps for fix:

1. Uninstall poetry with brew
2. Uninstall python3 with brew (with --force, but you should take care about your other apps)
3. Install python 3.9.6 with pyenv
4. Install poetry
