### ISSUE TITLE
[1.1.7] fail to install pyqt5

### ISSUE THREAD

**Issue by daiyam** [python-poetry/poetry#4281]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 10.11
- **Poetry version**: 1.1.7
- **pyproject.toml**: https://raw.githubusercontent.com/ActivityWatch/aw-qt/master/pyproject.toml

## Issue

The installation of `pyqt5` is failing because it can't find its wheel file. I believe that the root cause is the same as #3584.

```
• Installing pyqt5 (5.15.2): Failed

  EnvCommandError

  Command ['/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/bin/pip', 'install', '--no-deps', 'file:///Users/baptiste/Library/Caches/pypoetry/artifacts/68/c1/b8/00a192d66f6efe4fcc730dcf859ef8ade4de0569167d58b743b570c4a3/PyQt5-5.15.2.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/baptiste/Library/Caches/pypoetry/artifacts/68/c1/b8/00a192d66f6efe4fcc730dcf859ef8ade4de0569167d58b743b570c4a3/PyQt5-5.15.2.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'error'
      ERROR: Command errored out with exit status 1:
       command: /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/bin/python /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/tmpr1_u1zkx
           cwd: /private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-req-build-kxl9tir1
      Complete output (31 lines):
      Traceback (most recent call last):
        File "/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 126, in prepare_metadata_for_build_wheel
          hook = backend.prepare_metadata_for_build_wheel
      AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'
      
      During handling of the above exception, another exception occurred:
      
      Traceback (most recent call last):
        File "/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 280, in <module>
          main()
        File "/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 263, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 130, in prepare_metadata_for_build_wheel
          return _get_wheel_metadata_from_wheel(backend, metadata_directory,
        File "/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 159, in _get_wheel_metadata_from_wheel
          whl_basename = backend.build_wheel(metadata_directory, config_settings)
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/sipbuild/api.py", line 51, in build_wheel
          project = AbstractProject.bootstrap('pep517')
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
          project.setup(pyproject, tool, tool_description)
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 484, in setup
          self.apply_user_defaults(tool)
        File "project.py", line 63, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/pyqtbuild/project.py", line 70, in apply_user_defaults
          super().apply_user_defaults(tool)
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/sipbuild/project.py", line 230, in apply_user_defaults
          self.builder.apply_user_defaults(tool)
        File "/private/var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/pip-build-env-xn3bd88q/overlay/lib/python3.9/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
          raise PyProjectOptionException('qmake',
      sipbuild.pyproject.PyProjectOptionException
      ----------------------------------------
  WARNING: Discarding file:///Users/baptiste/Library/Caches/pypoetry/artifacts/68/c1/b8/00a192d66f6efe4fcc730dcf859ef8ade4de0569167d58b743b570c4a3/PyQt5-5.15.2.tar.gz. Command errored out with exit status 1: /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/bin/python /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/tmpr1_u1zkx Check the logs for full command output.
  ERROR: Command errored out with exit status 1: /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/bin/python /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py prepare_metadata_for_build_wheel /var/folders/g_/d89pljs17k30q8nm40rj7fr40000gn/T/tmpr1_u1zkx Check the logs for full command output.
  WARNING: You are using pip version 21.1.2; however, version 21.1.3 is available.
  You should consider upgrading via the '/Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9/bin/python -m pip install --upgrade pip' command.
```
with
```
$ poetry -V
Poetry version 1.1.7

$ poetry env info
Virtualenv
Python:         3.9.1
Implementation: CPython
Path:           /Users/baptiste/Library/Caches/pypoetry/virtualenvs/aw-qt-IZ0syVCP-py3.9
Valid:          True

System
Platform: darwin
OS:       posix
Python:   /Users/baptiste/.pyenv/versions/3.9.1
```

**Comment by daiyam** [comment]
Same error with `Python 3.8.6`

**Comment by xrogaan** [comment]
Something is wrong with the vendored versions of the various libraries poetry has to use. How did you install poetry?

**Comment by daiyam** [comment]
Here the chain I've used to install `poetry`:
- pyenv 1.2.21
- python 3.9.1
- pip 21.1.3
- poetry 1.1.7

**Comment by xrogaan** [comment]
You didn't answered the question: How did you install poetry?

Those packages are useless to this problem, verify the vendored version of packaging.

**Comment by daiyam** [comment]
I've installed with pip.

**Comment by xrogaan** [comment]
Within the environment where poetry is installed, verify that the `packaging` module is at least version 20.9:

```pycon
>>> import packaging
>>> packaging.__version__
'20.9'
```

Try to use the [recommended way to get poetry](https://python-poetry.org/docs/master/#installation). It'll be independent from your python environment and should come with everything needed for it to function. It'll use the `python` interpreter though.

**Comment by dimbleby** [comment]
poetry is simply shelling out to pip here, if the package can't be installed then that's not poetry's fault.  Almost certainly not pip's fault either...

Since this was raised, poetry has started using `--use-pep517` at pip install: so if pyqt5 is packaged correctly and declares its build-time dependencies then this is now fixed.  And if it doesn't, that should be reported to them.

No action on poetry here, this can be closed.

**Comment by alita-moore** [comment]
This happened to me because I didn't have qt5 installed on my system. So I ran `brew install qt5`.
