### ISSUE TITLE
Vendored package `backports` can be masked by virtualenv during import process

### ISSUE THREAD

**Issue by frankier** [python-poetry/poetry#4553]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian GNU/Linux 11 (bullseye)
- **Poetry version**: Poetry 1.1.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/frankier/0b5334d07df07e596bac7ad8dcda2fbb

## Issue

Steps to reproduce

 1. Have a pyproject.toml with backports.csv in (see above gist)
 2. Run `poetry install`
 3. Enter the virtualenv with `poetry shell`
 4. Run `poetry`

We get 

```
Traceback (most recent call last):
  File "/home/frankier/.poetry/bin/poetry", line 35, in <module>
    from poetry.console import main
  File "/home/frankier/.poetry/lib/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/home/frankier/.poetry/lib/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/home/frankier/.poetry/lib/poetry/console/commands/__init__.py", line 4, in <module>
    from .check import CheckCommand
  File "/home/frankier/.poetry/lib/poetry/console/commands/check.py", line 2, in <module>
    from poetry.factory import Factory
  File "/home/frankier/.poetry/lib/poetry/factory.py", line 18, in <module>
    from .repositories.pypi_repository import PyPiRepository
  File "/home/frankier/.poetry/lib/poetry/repositories/pypi_repository.py", line 33, in <module>
    from ..inspection.info import PackageInfo
  File "/home/frankier/.poetry/lib/poetry/inspection/info.py", line 25, in <module>
    from poetry.utils.env import EnvCommandError
  File "/home/frankier/.poetry/lib/poetry/utils/env.py", line 23, in <module>
    import virtualenv
  File "/home/frankier/.poetry/lib/poetry/_vendor/py3.9/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/home/frankier/.poetry/lib/poetry/_vendor/py3.9/virtualenv/run/__init__.py", line 13, in <module>
    from .plugin.activators import ActivationSelector
  File "/home/frankier/.poetry/lib/poetry/_vendor/py3.9/virtualenv/run/plugin/activators.py", line 6, in <module>
    from .base import ComponentBuilder
  File "/home/frankier/.poetry/lib/poetry/_vendor/py3.9/virtualenv/run/plugin/base.py", line 5, in <module>
    from backports.entry_points_selectable import entry_points
ModuleNotFoundError: No module named 'backports.entry_points_selectable'
```

What's the problem? It looks like backports is *already imported before* the following lines in the poetry startup script:

```
sys.path.insert(0, lib)
sys.path.insert(0, current_vendors)
```

This means that the cached module in sys.modules is used, which is from the virtualenv and not from Poetry vendored packages directory.

We can work around it by adding the following to the poetry startup script after the `sys.path.insert`s:

```
def reload_packages(packages):
    import types
    loaded_package_modules = {
        key: value for key, value in sys.modules.items()
        if key in packages and isinstance(value, types.ModuleType)
    }

    for key in loaded_package_modules:
        del sys.modules[key]

    for key in loaded_package_modules:
        newmodule = __import__(key)
        oldmodule = loaded_package_modules[key]
        oldmodule.__dict__.clear()
        oldmodule.__dict__.update(newmodule.__dict__)

reload_packages({"backports"})
```

I haven't created this as a PR since I think this approach is generally considered brittle and I see that I'm likely to get pushback on it. Maybe someone else has a more robust idea? The only other thing I can think of is running exec() on the script again with a modified PYTHONPATH, but this will significantly increase startup time, which is really no good for a command like `poetry`.

**Comment by finswimmer** [comment]
Hello @frankier,

this only happens when poetry was installed with the (now deprecated) `get-install.py` script, where poetry vendors it's own dependencies but runs with currently activated python interpreter. This has changed with now recommended `install-poetry.py` script, where poetry runs within it's own venv. There you don't have this issue anymore.

fin swimmer
