### ISSUE TITLE
Can not install pypy dependencies

### ISSUE THREAD

**Issue by ArtsiomAntropau** [python-poetry/poetry#4828]
Hello, I can not install dependencies using pdm in pypy environment. 

- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have searched the [documentation](https://python-poetry.org/docs/) and believe that my question is not covered.

## Issue

I'm using this docker tag https://hub.docker.com/layers/pypy/library/pypy/3.8/images/sha256-b8fac9a0fae4743e716d06c758d9a93071346b00bd5baf0dedaafe59460ef486
And trying to install dependencies from this pyproject.toml, I can not share some parts like package names and repositories names due to NDA.

```
[project]
name = ""
version = ""
description = ""
authors = []
required-version = "3.8"
dependencies = [
    "plotly~=5.4.0",
    "structlog~=21.3.0",
    "pyodbc==4.0.24",
    "cython==0.29.24",
    "alembic==1.7.3",
    "pandas==1.3.4",
    "voluptuous~=0.12.2",
    "pathlib2==2.3.0",
    "click~=7.1.2",
    "openpyxl~=3.0.9",
    "requests~=2.26.0",
    "selenium==3.141.0",
    "python-pptx~=0.6.21",
    "jsonschema==3.2.0",
    "SQLAlchemy~=1.4.25",
    "PyYAML~=5.4.1",
    "Flask~=2.0.2",
    "Flask-SQLAlchemy==2.5.1",
    "Routes==2.4.1",
    "Pillow~=8.3.2",
    "gunicorn~=20.1.0",
    "psycopg2==2.9.1",
    "sqlalchemy-exasol==1.3.2",
    "sqlparse==0.3.0",
    "mock==3.0.5",
    "can-not-share-this-private-package-1~=3.0.0",
    "can-not-share-this-private-package-2==0.30.115",
    "sentry-sdk",
    "user-agents==2.0",
    "platform-pysdk~=1.12.0",
    "can-not-share-this-private-package-3==1.1.17",
    "can-not-share-this-private-package-4==1.0.7",
    "wand==0.6.7",
    "cryptography~=3.4.8",
    "orjson~=3.6.4",
    "numpy",
]
dynamic = ["classifiers"]
license = {text = "MIT"}

[project.urls]
homepage = ""

[[tool.pdm.source]]
url = "https://can_not_share_this_private_repo_1.com/+simple/"
verify_ssl = true
name = "name1-pypi"

[[tool.pdm.source]]
url = "https://can_not_share_this_private_repo_2.com/simple"
verify_ssl = true
name = "name2-pypi"

[[tool.pdm.source]]
url = "https://can_not_share_this_private_repo_3.com/simple"
verify_ssl = false
name = "name3-pypi"


[tool.pdm.dev-dependencies]
dev = [
    "pre-commit==2.15.0",
    "flake8==3.9.2",
    "pytest~=6.2.5",
    "mock==3.0.5",
    "coverage~=6.0",
    "pytest-clarity==1.0.1",
    "pdbpp==0.9.11",
    "remote-pdb==1.3.0",
    "pylint",
    "bandit~=1.7.0",
]

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
```

And I'm receiving the following error each time, it is the first round of installation

```
          ... [60 more candidate(s)]
  Adding requirement python>=3.6(from plotly 5.4.0)
🔒 Lock failed
Unable to find a resolution that satisfies the following requirements:
  python (from project)
  python>=3.6 (from <Candidate plotly 5.4.0 from unknown>)
Please make sure the package names are correct. If so, you can either loosen the version constraints of these dependencies, or set a narrower `requires-python` range in the pyproject.toml.
Traceback (most recent call last):
  File "/root/.local/bin/pdm", line 8, in <module>
    sys.exit(main())
  File "/root/.local/share/pdm/venv/lib/pypy3.8/site-packages/pdm/core.py", line 200, in main
    return Core().main(args)
  File "/root/.local/share/pdm/venv/lib/pypy3.8/site-packages/pdm/core.py", line 153, in main
    raise cast(Exception, err).with_traceback(traceback)
  File "/root/.local/share/pdm/venv/lib/pypy3.8/site-packages/pdm/core.py", line 148, in main
    f(options.project, options)
  File "/root/.local/share/pdm/venv/lib/pypy3.8/site-packages/pdm/cli/commands/install.py", line 44, in handle
    actions.do_lock(project, strategy="reuse", dry_run=options.dry_run)
  File "/root/.local/share/pdm/venv/lib/pypy3.8/site-packages/pdm/cli/actions.py", line 72, in do_lock
    resolve_max_rounds,
  File "/root/.local/share/pdm/venv/lib/pypy3.8/site-packages/pdm/resolver/core.py", line 31, in resolve
    result = resolver.resolve(requirements, max_rounds)
  File "/root/.local/share/pdm/venv/lib/pypy3.8/site-packages/resolvelib/resolvers.py", line 472, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/root/.local/share/pdm/venv/lib/pypy3.8/site-packages/resolvelib/resolvers.py", line 376, in resolve
    raise ResolutionImpossible(causes)
resolvelib.resolvers.ResolutionImpossible: [RequirementInformation(requirement=PythonRequirement(name='python', marker=None, extras=None, specifier=<PySpecSet >, editable=False), parent=None), RequirementInformation(requirement=PythonRequirement(name='python', marker=None, extras=None, specifier=<PySpecSet >=3.6>, editable=False), parent=<Candidate plotly 5.4.0 from unknown>)]
make: *** [Makefile:13: prod-requirements] Error 1
```

**Comment by neersighted** [comment]
Hi @ArtsiomAntropau, I think you may have taken a left turn by mistake. This repo is for poetry, not for PDM. Find PDM at https://github.com/pdm-project/pdm.

**Comment by ArtsiomAntropau** [comment]
@neersighted omg sorry, you are absolutely right.
