### ISSUE TITLE
pytest 7 test failures

### ISSUE THREAD

**Issue by hroncok** [python-poetry/poetry#4901]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version. (this is 1.1.11, but the difference should not matter)
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.

- **OS version and name**: Fedora Linux 36
- **Poetry version**: 1.1.11

## Issue

Hello, we are test-building all Fedora python packages with pytest 7.0.0rc1 and poetry fails with:

```
=================================== FAILURES ===================================
_________________ test_execute_executes_a_batch_of_operations __________________

config = <poetry.config.config.Config object at 0x7f8dbf39bac0>
pool = <poetry.repositories.pool.Pool object at 0x7f8dbf39bc40>
io = <clikit.io.buffered_io.BufferedIO object at 0x7f8dbf39bcd0>
tmp_dir = '/tmp/poetry_em0nkgl8', mock_file_downloads = None

    def test_execute_executes_a_batch_of_operations(
        config, pool, io, tmp_dir, mock_file_downloads
    ):
        config = Config()
        config.merge({"cache-dir": tmp_dir})
    
        env = MockEnv(path=Path(tmp_dir))
        executor = Executor(env, pool, config, io)
    
        file_package = Package(
            "demo",
            "0.1.0",
            source_type="file",
            source_url=Path(__file__)
            .parent.parent.joinpath(
                "fixtures/distributions/demo-0.1.0-py2.py3-none-any.whl"
            )
            .resolve()
            .as_posix(),
        )
    
        directory_package = Package(
            "simple-project",
            "1.2.3",
            source_type="directory",
            source_url=Path(__file__)
            .parent.parent.joinpath("fixtures/simple_project")
            .resolve()
            .as_posix(),
        )
    
        git_package = Package(
            "demo",
            "0.1.0",
            source_type="git",
            source_reference="master",
            source_url="https://github.com/demo/demo.git",
        )
    
>       assert 0 == executor.execute(
            [
                Install(Package("pytest", "3.5.2")),
                Uninstall(Package("attrs", "17.4.0")),
                Update(Package("requests", "2.18.3"), Package("requests", "2.18.4")),
                Uninstall(Package("clikit", "0.2.3")).skip("Not currently installed"),
                Install(file_package),
                Install(directory_package),
                Install(git_package),
            ]
        )
E       assert 0 == 1
E        +  where 1 = <bound method Executor.execute of <poetry.installation.executor.Executor object at 0x7f8dbf39b610>>([<Install pytest (3.5.2)>, <Uninstall attrs (17.4.0)>, <Update requests (2.18.3) to requests (2.18.4)>, <Uninstall cli...one-any.whl)>, <Install simple-project (1.2.3 /builddir/build/BUILD/poetry-1.1.11/tests/fixtures/simple_project)>, ...])
E        +    where <bound method Executor.execute of <poetry.installation.executor.Executor object at 0x7f8dbf39b610>> = <poetry.installation.executor.Executor object at 0x7f8dbf39b610>.execute

tests/installation/test_executor.py:100: AssertionError
------------------------------ Captured log call -------------------------------
DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): files.pythonhosted.org:443
DEBUG    urllib3.connectionpool:connectionpool.py:452 https://files.pythonhosted.org:443 "GET /packages/ed/96/271c93f75212c06e2a7ec3e2fa8a9c90acee0a4838dc05bf379ea09aae31/pytest-3.5.0-py2.py3-none-any.whl HTTP/1.1" 200 1116
DEBUG    urllib3.connectionpool:connectionpool.py:971 Starting new HTTPS connection (1): files.pythonhosted.org:443
DEBUG    urllib3.connectionpool:connectionpool.py:452 https://files.pythonhosted.org:443 "GET /packages/49/df/50aa1999ab9bde74656c2919d9c0c085fd2b3775fd3eca826012bef76d8c/requests-2.18.4-py2.py3-none-any.whl HTTP/1.1" 200 1116
__________________ test_builder_should_execute_build_scripts ___________________

extended_without_setup_poetry = <poetry.poetry.Poetry object at 0x7f8dbc27c0a0>

    def test_builder_should_execute_build_scripts(extended_without_setup_poetry):
        env = MockEnv(path=Path("/foo"))
        builder = EditableBuilder(extended_without_setup_poetry, env, NullIO())
    
>       builder.build()

tests/masonry/builders/test_editable_builder.py:227: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
poetry/masonry/builders/editable.py:59: in build
    self._add_dist_info(added_files)
poetry/masonry/builders/editable.py:207: in _add_dist_info
    dist_info = self._env.site_packages.mkdir(dist_info_path)
poetry/utils/env.py:271: in mkdir
    return self._path_method_wrapper(path, "mkdir", *args, **kwargs)[0]
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <poetry.utils.env.SitePackages object at 0x7f8dbc27ca00>
path = PosixPath('extended_project-1.2.3.dist-info'), method = 'mkdir'
args = (), kwargs = {}, return_first = True, writable_only = False
candidates = [PosixPath('/usr/lib/python3.10/site-packages/extended_project-1.2.3.dist-info')]
results = []
candidate = PosixPath('/usr/lib/python3.10/site-packages/extended_project-1.2.3.dist-info')

    def _path_method_wrapper(
        self, path, method, *args, **kwargs
    ):  # type: (Path, str, *Any, **Any) -> Union[Tuple[Path, Any], List[Tuple[Path, Any]]]
    
        # TODO: Move to parameters after dropping Python 2.7
        return_first = kwargs.pop("return_first", True)
        writable_only = kwargs.pop("writable_only", False)
    
        candidates = self.make_candidates(path, writable_only=writable_only)
    
        if not candidates:
            raise RuntimeError(
                'Unable to find a suitable destination for "{}" in {}'.format(
                    str(path), paths_csv(self._candidates)
                )
            )
    
        results = []
    
        for candidate in candidates:
            try:
                result = candidate, getattr(candidate, method)(*args, **kwargs)
                if return_first:
                    return result
                else:
                    results.append(result)
            except (IOError, OSError):
                # TODO: Replace with PermissionError
                pass
    
        if results:
            return results
    
>       raise OSError("Unable to access any of {}".format(paths_csv(candidates)))
E       OSError: Unable to access any of "/usr/lib/python3.10/site-packages/extended_project-1.2.3.dist-info"

poetry/utils/env.py:265: OSError
=============================== warnings summary ===============================
../../../../usr/lib/python3.10/site-packages/poetry/core/_vendor/packaging/tags.py:7
  /usr/lib/python3.10/site-packages/poetry/core/_vendor/packaging/tags.py:7: DeprecationWarning: The distutils package is deprecated and slated for removal in Python 3.12. Use setuptools or check PEP 632 for potential alternatives
    import distutils.util

tests/helpers.py:139
  /builddir/build/BUILD/poetry-1.1.11/tests/helpers.py:139: PytestCollectionWarning: cannot collect test class 'TestApplication' because it has a __init__ constructor (from: tests/console/commands/test_init.py)
    class TestApplication(Application):

tests/console/commands/test_export.py::test_export_exports_requirements_txt_uses_lock_file
  /usr/lib64/python3.10/distutils/command/install.py:13: DeprecationWarning: The distutils.sysconfig module is deprecated, use sysconfig instead
    from distutils.sysconfig import get_config_vars

tests/console/commands/test_publish.py: 6 warnings
tests/publishing/test_uploader.py: 6 warnings
  /builddir/build/BUILD/poetry-1.1.11/poetry/publishing/uploader.py:62: DeprecationWarning: Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead
    retry = util.Retry(

tests/console/commands/test_publish.py: 2 warnings
tests/console/commands/test_search.py: 1 warning
tests/installation/test_authenticator.py: 39 warnings
tests/installation/test_chooser.py: 12 warnings
tests/installation/test_executor.py: 2 warnings
tests/publishing/test_uploader.py: 3 warnings
  /usr/lib/python3.10/site-packages/urllib3/connection.py:542: DeprecationWarning: ssl.match_hostname() is deprecated
    match_hostname(cert, asserted_hostname)

tests/console/commands/test_publish.py::test_publish_returns_non_zero_code_for_connection_errors
  /usr/lib/python3.10/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-26 (fill_filekind)
  
  Traceback (most recent call last):
    File "/usr/lib64/python3.10/threading.py", line 1009, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.10/threading.py", line 946, in run
      self._target(*self._args, **self._kwargs)
    File "/usr/lib/python3.10/site-packages/httpretty/core.py", line 1097, in fill_filekind
      status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
    File "/builddir/build/BUILD/poetry-1.1.11/tests/console/commands/test_publish.py", line 35, in request_callback
      raise requests.ConnectionError()
  requests.exceptions.ConnectionError
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/installation/test_authenticator.py::test_authenticator_request_retries_on_exception
  /usr/lib/python3.10/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-79 (fill_filekind)
  
  Traceback (most recent call last):
    File "/usr/lib64/python3.10/threading.py", line 1009, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.10/threading.py", line 946, in run
      self._target(*self._args, **self._kwargs)
    File "/usr/lib/python3.10/site-packages/httpretty/core.py", line 1097, in fill_filekind
      status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
    File "/builddir/build/BUILD/poetry-1.1.11/tests/installation/test_authenticator.py", line 130, in callback
      raise requests.exceptions.ConnectionError("Disconnected")
  requests.exceptions.ConnectionError: Disconnected
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/installation/test_authenticator.py::test_authenticator_request_raises_exception_when_attempts_exhausted
  /usr/lib/python3.10/site-packages/_pytest/threadexception.py:73: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-86 (fill_filekind)
  
  Traceback (most recent call last):
    File "/usr/lib64/python3.10/threading.py", line 1009, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.10/threading.py", line 946, in run
      self._target(*self._args, **self._kwargs)
    File "/usr/lib/python3.10/site-packages/httpretty/core.py", line 1097, in fill_filekind
      status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
    File "/builddir/build/BUILD/poetry-1.1.11/tests/installation/test_authenticator.py", line 148, in callback
      raise requests.exceptions.ConnectionError(str(uuid.uuid4()))
  requests.exceptions.ConnectionError: 729ca528-1544-44ef-bb7f-5fbcd7fe1c83
  
    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
=========================== short test summary info ============================
FAILED tests/installation/test_executor.py::test_execute_executes_a_batch_of_operations
FAILED tests/masonry/builders/test_editable_builder.py::test_builder_should_execute_build_scripts
= 2 failed, 653 passed, 4 skipped, 2 deselected, 77 warnings in 66.89s (0:01:06) =
```

Ourr builders are offline, but this works with pytest 6.2.5.

**Comment by hroncok** [comment]
Thanks. Will check that out when we upgrade.
