### ISSUE TITLE
Some dependencies not installed on Debian bookworm, Python 3.10

### ISSUE THREAD

**Issue by intgr** [python-poetry/poetry#4906]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Debian bookworm (slim Docker image)
- **Poetry version**: 1.1.12
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://github.com/intgr/bug-reports/tree/main/poetry-missing-deps

## Issue

I'm using the `debian:bookworm-slim` base Docker image to install Python 3.10 and Poetry.

For some reason `pip install poetry` isn't enough to get a working Poetry installation, I need to explicitly install `cachecontrol crashtest lockfile` as well. Otherwise the output of `poetry -vvv --version` is:
```
#7 0.685 Traceback (most recent call last):
#7 0.685   File "/usr/bin/poetry", line 5, in <module>
#7 0.685     from poetry.console import main
#7 0.685   File "/usr/lib/python3.10/dist-packages/poetry/console/__init__.py", line 1, in <module>
#7 0.685     from .application import Application
#7 0.685   File "/usr/lib/python3.10/dist-packages/poetry/console/application.py", line 7, in <module>
#7 0.686     from .commands.about import AboutCommand
#7 0.686   File "/usr/lib/python3.10/dist-packages/poetry/console/commands/__init__.py", line 4, in <module>
#7 0.686     from .check import CheckCommand
#7 0.686   File "/usr/lib/python3.10/dist-packages/poetry/console/commands/check.py", line 2, in <module>
#7 0.686     from poetry.factory import Factory
#7 0.686   File "/usr/lib/python3.10/dist-packages/poetry/factory.py", line 18, in <module>
#7 0.686     from .repositories.pypi_repository import PyPiRepository
#7 0.686   File "/usr/lib/python3.10/dist-packages/poetry/repositories/pypi_repository.py", line 11, in <module>
#7 0.686     from cachecontrol import CacheControl
#7 0.686 ModuleNotFoundError: No module named 'cachecontrol'
```

Example Dockerfile:
```dockerfile
FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
        python3.10 libpython3.10-dev python3.10-venv python3-pip && \
    update-alternatives --install /usr/bin/python python /usr/bin/python3.10 0 && \
    update-alternatives --install /usr/bin/python3 python3 /usr/bin/python3.10 0 && \
    rm -rf /var/lib/apt/lists/*

RUN pip install --no-cache-dir poetry
# If I don't install these explicitly, Poetry won't work:
# RUN pip install --no-cache-dir cachecontrol crashtest lockfile

RUN poetry -vvv --version
```

More complete reproducer available at https://github.com/intgr/bug-reports/tree/main/poetry-missing-deps

**Comment by intgr** [comment]
This line from `pip install poetry` seems suspect:
```
#6 2.074 Ignoring cachecontrol: markers 'python_version < "3.6"' don't match your environment
```

<details>
<summary>Full output from pip install</summary>

```
#6 [3/7] RUN pip install --no-cache-dir poetry
#6 sha256:9685adbbe861304efc22fca4b07e385e9a5079ebdeee6a0978cac9234538de87
#6 1.972 Collecting poetry
#6 2.018   Downloading poetry-1.1.12-py2.py3-none-any.whl (175 kB)
#6 2.070 Ignoring importlib-metadata: markers 'python_version < "3.8"' don't match your environment
#6 2.074 Ignoring cachecontrol: markers 'python_version < "3.6"' don't match your environment
#6 2.132 Collecting pkginfo<2.0,>=1.4
#6 2.140   Downloading pkginfo-1.8.2-py2.py3-none-any.whl (26 kB)
#6 2.207 Collecting tomlkit<1.0.0,>=0.7.0
#6 2.215   Downloading tomlkit-0.7.2-py2.py3-none-any.whl (32 kB)
#6 2.274 Collecting pexpect<5.0.0,>=4.7.0
#6 2.291   Downloading pexpect-4.8.0-py2.py3-none-any.whl (59 kB)
#6 2.356 Collecting requests-toolbelt<0.10.0,>=0.9.1
#6 2.366   Downloading requests_toolbelt-0.9.1-py2.py3-none-any.whl (54 kB)
#6 2.405 Collecting cachy<0.4.0,>=0.3.0
#6 2.412   Downloading cachy-0.3.0-py2.py3-none-any.whl (20 kB)
#6 2.448 Collecting html5lib<2.0,>=1.0
#6 2.456   Downloading html5lib-1.1-py2.py3-none-any.whl (112 kB)
#6 2.513 Collecting cleo<0.9.0,>=0.8.1
#6 2.520   Downloading cleo-0.8.1-py2.py3-none-any.whl (21 kB)
#6 2.572 Collecting clikit<0.7.0,>=0.6.2
#6 2.580   Downloading clikit-0.6.2-py2.py3-none-any.whl (91 kB)
#6 2.666 Collecting packaging<21.0,>=20.4
#6 2.678   Downloading packaging-20.9-py2.py3-none-any.whl (40 kB)
#6 2.738 Collecting poetry-core<1.1.0,>=1.0.7
#6 2.746   Downloading poetry_core-1.0.7-py2.py3-none-any.whl (424 kB)
#6 2.905 Collecting requests<3.0,>=2.18
#6 2.912   Downloading requests-2.26.0-py2.py3-none-any.whl (62 kB)
#6 2.987 Collecting shellingham<2.0,>=1.1
#6 2.994   Downloading shellingham-1.4.0-py2.py3-none-any.whl (9.4 kB)
#6 3.222 Collecting virtualenv<21.0.0,>=20.0.26
#6 3.230   Downloading virtualenv-20.10.0-py2.py3-none-any.whl (5.6 MB)
#6 3.730 Collecting pylev<2.0,>=1.3
#6 3.739   Downloading pylev-1.4.0-py2.py3-none-any.whl (6.1 kB)
#6 3.768 Collecting pastel<0.3.0,>=0.2.0
#6 3.779   Downloading pastel-0.2.1-py2.py3-none-any.whl (6.0 kB)
#6 3.844 Collecting six>=1.9
#6 3.852   Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
#6 3.881 Collecting webencodings
#6 3.888   Downloading webencodings-0.5.1-py2.py3-none-any.whl (11 kB)
#6 4.031 Collecting pyparsing>=2.0.2
#6 4.037   Downloading pyparsing-3.0.6-py3-none-any.whl (97 kB)
#6 4.090 Collecting ptyprocess>=0.5
#6 4.097   Downloading ptyprocess-0.7.0-py2.py3-none-any.whl (13 kB)
#6 4.223 Collecting certifi>=2017.4.17
#6 4.230   Downloading certifi-2021.10.8-py2.py3-none-any.whl (149 kB)
#6 4.304 Collecting idna<4,>=2.5
#6 4.313   Downloading idna-3.3-py3-none-any.whl (61 kB)
#6 4.442 Collecting urllib3<1.27,>=1.21.1
#6 4.449   Downloading urllib3-1.26.7-py2.py3-none-any.whl (138 kB)
#6 4.526 Collecting charset-normalizer~=2.0.0
#6 4.535   Downloading charset_normalizer-2.0.9-py3-none-any.whl (39 kB)
#6 4.724 Ignoring importlib-metadata: markers 'python_version < "3.8"' don't match your environment
#6 4.730 Ignoring pathlib2: markers 'python_version < "3.4" and sys_platform != "win32"' don't match your environment
#6 4.733 Ignoring importlib-resources: markers 'python_version < "3.7"' don't match your environment
#6 4.780 Collecting backports.entry-points-selectable>=1.0.4
#6 4.788   Downloading backports.entry_points_selectable-1.1.1-py2.py3-none-any.whl (6.2 kB)
#6 4.844 Collecting platformdirs<3,>=2
#6 4.852   Downloading platformdirs-2.4.0-py3-none-any.whl (14 kB)
#6 4.907 Collecting distlib<1,>=0.3.1
#6 4.916   Downloading distlib-0.3.4-py2.py3-none-any.whl (461 kB)
#6 5.018 Collecting filelock<4,>=3.2
#6 5.026   Downloading filelock-3.4.0-py3-none-any.whl (9.8 kB)
#6 5.051 Ignoring importlib-metadata: markers 'python_version < "3.8"' don't match your environment
#6 5.275 Installing collected packages: urllib3, pylev, pastel, idna, charset-normalizer, certifi, webencodings, six, requests, pyparsing, ptyprocess, platformdirs, filelock, distlib, clikit, backports.entry-points-selectable, virtualenv, tomlkit, shellingham, requests-toolbelt, poetry-core, pkginfo, pexpect, packaging, html5lib, cleo, cachy, poetry
#6 6.833 ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
#6 6.833 backports-entry-points-selectable 1.1.1 requires importlib-metadata; python_version < "3.8", which is not installed.
#6 6.833 virtualenv 20.10.0 requires importlib-metadata>=0.12; python_version < "3.8", which is not installed.
#6 6.833 virtualenv 20.10.0 requires importlib-resources>=1.0; python_version < "3.7", which is not installed.
#6 6.833 virtualenv 20.10.0 requires pathlib2<3,>=2.3.3; python_version < "3.4" and sys_platform != "win32", which is not installed.
#6 6.833 poetry 1.1.12 requires cachecontrol[filecache]<0.13.0,>=0.12.4; python_version < "3.6", which is not installed.
#6 6.833 poetry 1.1.12 requires importlib-metadata<2.0.0,>=1.6.0; python_version < "3.8", which is not installed.
#6 6.833 Successfully installed backports.entry-points-selectable-1.1.1 cachy-0.3.0 certifi-2021.10.8 charset-normalizer-2.0.9 cleo-0.8.1 clikit-0.6.2 distlib-0.3.4 filelock-3.4.0 html5lib-1.1 idna-3.3 packaging-20.9 pastel-0.2.1 pexpect-4.8.0 pkginfo-1.8.2 platformdirs-2.4.0 poetry-1.1.12 poetry-core-1.0.7 ptyprocess-0.7.0 pylev-1.4.0 pyparsing-3.0.6 requests-2.26.0 requests-toolbelt-0.9.1 shellingham-1.4.0 six-1.16.0 tomlkit-0.7.2 urllib3-1.26.7 virtualenv-20.10.0 webencodings-0.5.1
```
</details>
