### ISSUE TITLE
No module pip found

### ISSUE THREAD

**Issue by ierezell** [python-poetry/poetry#5068]
- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:Archlinux 5.16.1
- **Poetry version**: 1.2.0a2

## Issue
When trying to install allennlp I got the follwing stack trace which breaks the rest. 

```bash
 poetry add allennlp allennlp-models                                                                                                                                                                     
Using version ^2.8.0 for allennlp
Using version ^2.8.0 for allennlp-models

Updating dependencies
Resolving dependencies... (11.6s)

Package operations: 7 installs, 0 updates, 0 removals

  • Installing checklist (0.0.11): Failed

  CalledProcessError

  Command '['/mnt/Documents/nlp/packages/coreference/.venv/bin/python', '/home/pedro/.local/share/pypoetry/venv/lib/python3.7/site-packages/virtualenv/seed/wheels/embed/pip-21.0.1-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/mnt/Documents/nlp/packages/coreference/.venv', '--no-deps', 'file:/home/pedro/.cache/pypoetry/artifacts/f8/43/ff/932718aa7bb512da59fb6c3551b3421dba473b7f7681ec65d87d642e33/checklist-0.0.11.tar.gz']' returned non-zero exit status 1.

  at /usr/lib/python3.7/subprocess.py:512 in run
       508│             raise
       509│         retcode = process.poll()
       510│         if check and retcode:
       511│             raise CalledProcessError(retcode, process.args,
    →  512│                                      output=stdout, stderr=stderr)
       513│     return CompletedProcess(process.args, retcode, stdout, stderr)
       514│ 
       515│ 
       516│ def list2cmdline(seq):

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/mnt/Documents/nlp/packages/coreference/.venv/bin/python', '/home/pedro/.local/share/pypoetry/venv/lib/python3.7/site-packages/virtualenv/seed/wheels/embed/pip-21.0.1-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/mnt/Documents/nlp/packages/coreference/.venv', '--no-deps', 'file:/home/pedro/.cache/pypoetry/artifacts/f8/43/ff/932718aa7bb512da59fb6c3551b3421dba473b7f7681ec65d87d642e33/checklist-0.0.11.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/pedro/.cache/pypoetry/artifacts/f8/43/ff/932718aa7bb512da59fb6c3551b3421dba473b7f7681ec65d87d642e33/checklist-0.0.11.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /mnt/Documents/nlp/packages/coreference/.venv/bin/python /tmp/tmpy9qupqns get_requires_for_build_wheel /tmp/tmps80cx5z4
         cwd: /tmp/pip-req-build-3kdh1xhu
    Complete output (47 lines):
    running egg_info
    warning: no files found matching 'CHANGES'
    warning: no files found matching 'requirements.txt'
    warning: no files found matching 'data' under directory '*'
    warning: no previously-included files matching '__pycache__' found under directory '*'
    warning: no previously-included files matching '*.pyc' found under directory '*'
    warning: no previously-included files matching '*.pyo' found under directory '*'
    warning: no previously-included files matching '*.orig' found under directory '*'
    warning: no previously-included files matching 'node_modules' found under directory '*'
    warning: no previously-included files matching '_release_data' found under directory '*'
    warning: no previously-included files matching 'visual_interface' found under directory '*'
    writing manifest file 'checklist.egg-info/SOURCES.txt'
    /mnt/Documents/nlp/packages/coreference/.venv/bin/python: No module named pip
    Traceback (most recent call last):
      File "/tmp/tmpy9qupqns", line 280, in <module>
        main()
      File "/tmp/tmpy9qupqns", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpy9qupqns", line 114, in get_requires_for_build_wheel
        return hook(config_settings)
      File "/tmp/pip-build-env-6gqg9wz5/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 163, in get_requires_for_build_wheel
        config_settings, requirements=['wheel'])
      File "/tmp/pip-build-env-6gqg9wz5/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 143, in _get_build_requires
        self.run_setup()
      File "/tmp/pip-build-env-6gqg9wz5/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 268, in run_setup
        self).run_setup(setup_script=setup_script)
      File "/tmp/pip-build-env-6gqg9wz5/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 158, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 85, in <module>
        zip_safe=False
      File "/tmp/pip-build-env-6gqg9wz5/overlay/lib/python3.7/site-packages/setuptools/__init__.py", line 155, in setup
        return distutils.core.setup(**attrs)
      File "/tmp/pip-build-env-6gqg9wz5/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 148, in setup
        return run_commands(dist)
      File "/tmp/pip-build-env-6gqg9wz5/overlay/lib/python3.7/site-packages/setuptools/_distutils/core.py", line 163, in run_commands
        dist.run_commands()
      File "/tmp/pip-build-env-6gqg9wz5/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 967, in run_commands
        self.run_command(cmd)
      File "/tmp/pip-build-env-6gqg9wz5/overlay/lib/python3.7/site-packages/setuptools/_distutils/dist.py", line 986, in run_command
        cmd_obj.run()
      File "setup.py", line 53, in run
        enable_visual_interface()
      File "setup.py", line 12, in enable_visual_interface
        check_call(f"{sys.executable} -m pip install jupyter", shell=True)
      File "/usr/lib/python3.7/subprocess.py", line 363, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '/mnt/Documents/nlp/packages/coreference/.venv/bin/python -m pip install jupyter' returned non-zero exit status 1.
    ----------------------------------------
  WARNING: Discarding file:///home/pedro/.cache/pypoetry/artifacts/f8/43/ff/932718aa7bb512da59fb6c3551b3421dba473b7f7681ec65d87d642e33/checklist-0.0.11.tar.gz. Command errored out with exit status 1: /mnt/Documents/nlp/packages/coreference/.venv/bin/python /tmp/tmpy9qupqns get_requires_for_build_wheel /tmp/tmps80cx5z4 Check the logs for full command output.
  ERROR: Command errored out with exit status 1: /mnt/Documents/nlp/packages/coreference/.venv/bin/python /tmp/tmpy9qupqns get_requires_for_build_wheel /tmp/tmps80cx5z4 Check the logs for full command output.
  

  at ~/.local/share/pypoetry/venv/lib/python3.7/site-packages/poetry/utils/env.py:1300 in _run
      1296│                 output = subprocess.check_output(
      1297│                     cmd, stderr=subprocess.STDOUT, env=env, **kwargs
      1298│                 )
      1299│         except CalledProcessError as e:
    → 1300│             raise EnvCommandError(e, input=input_)
      1301│ 
      1302│         return decode(output)
      1303│ 
      1304│     def execute(self, bin: str, *args: str, **kwargs: Any) -> Optional[int]:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install file:/home/pedro/.cache/pypoetry/artifacts/f8/43/ff/932718aa7bb512da59fb6c3551b3421dba473b7f7681ec65d87d642e33/checklist-0.0.11.tar.gz

  at ~/.local/share/pypoetry/venv/lib/python3.7/site-packages/poetry/utils/pip.py:60 in pip_install
       56│                     *env.get_pip_command(),
       57│                     *args,
       58│                     env={**os.environ, "PYTHONPATH": str(env.purelib)},
       59│                 )
    →  60│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       61│ 
       62│ 
       63│ def pip_editable_install(directory: Path, environment: Env) -> Union[int, str]:
       64│     return pip_install(

```

However, installing with vanilla pip work perfectly well. 

Thanks in advance, 
Have  a great day.

**Comment by finswimmer** [comment]
Thanks for reporting @Ierezell.

I'm able to reproduce it with current preview release as well with current version in master, but not with poetry 1.1.12.

fin swimmer

**Comment by dimbleby** [comment]
checklist is trying to `pip install jupyter` during its own installation - https://github.com/marcotcr/checklist/blob/9baab717e44e216697f7ef0730ee269db9ef7d5b/setup.py#L11-L12.

This is quite strange from checklist.  If it needs `jupyter` to be installed then surely simply declare that as a dependency.

Reckon this wants taking upstream, if you still care.

**Comment by dimbleby** [comment]
Actually upstream already has an issue https://github.com/marcotcr/checklist/issues/119

**Comment by neersighted** [comment]
Closing as not a Poetry issue.
