### ISSUE TITLE
1.1.13: pytest is failing

### ISSUE THREAD

**Issue by kloczek** [python-poetry/poetry#5184]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Linux x86/64
- **Poetry version**: 1.1.13

## Issue
Looks like in many places is hardcodes python interpreter name. In my case python executable is `bpytho3` and many units is failing on executing `pythoi`
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-poetry-1.1.13-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-poetry-1.1.13-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --ignore tests/repositories/test_installed_repository.py
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/poetry-1.1.13
plugins: mock-3.7.0
collected 654 items

tests/test_factory.py ..............                                                                                                                                 [  2%]
tests/config/test_config.py .......                                                                                                                                  [  3%]
tests/console/commands/test_about.py .                                                                                                                               [  3%]
tests/console/commands/test_add.py ..........................................................                                                                        [ 12%]
tests/console/commands/test_cache.py ..                                                                                                                              [ 12%]
tests/console/commands/test_check.py ..                                                                                                                              [ 12%]
tests/console/commands/test_config.py ..........                                                                                                                     [ 14%]
tests/console/commands/test_export.py F.....                                                                                                                         [ 15%]
tests/console/commands/test_init.py ..................                                                                                                               [ 18%]
tests/console/commands/test_lock.py .                                                                                                                                [ 18%]
tests/console/commands/test_publish.py ..s...                                                                                                                        [ 19%]
tests/console/commands/test_run.py .                                                                                                                                 [ 19%]
tests/console/commands/test_search.py .                                                                                                                              [ 19%]
tests/console/commands/test_show.py ..................                                                                                                               [ 22%]
tests/console/commands/test_version.py .......................                                                                                                       [ 25%]
tests/console/commands/debug/test_resolve.py ...                                                                                                                     [ 26%]
tests/console/commands/env/test_info.py ..                                                                                                                           [ 26%]
tests/console/commands/env/test_list.py FFF                                                                                                                          [ 26%]
tests/console/commands/env/test_remove.py .F                                                                                                                         [ 27%]
tests/console/commands/env/test_use.py FFF                                                                                                                           [ 27%]
tests/console/commands/self/test_update.py ..                                                                                                                        [ 27%]
tests/inspection/test_info.py .........s.........                                                                                                                    [ 30%]
tests/installation/test_authenticator.py .................                                                                                                           [ 33%]
tests/installation/test_chef.py ...                                                                                                                                  [ 33%]
tests/installation/test_chooser.py ............                                                                                                                      [ 35%]
tests/installation/test_executor.py .........                                                                                                                        [ 37%]
tests/installation/test_installer.py ................................s.........                                                                                      [ 43%]
tests/installation/test_installer_old.py ...............................s........                                                                                    [ 49%]
tests/installation/test_pip_installer.py ........                                                                                                                    [ 50%]
tests/masonry/builders/test_editable_builder.py ....                                                                                                                 [ 51%]
tests/mixology/solutions/providers/test_python_requirement_solution_provider.py ..                                                                                   [ 51%]
tests/mixology/solutions/solutions/test_python_requirement_solution.py .                                                                                             [ 51%]
tests/mixology/version_solver/test_backtracking.py ........                                                                                                          [ 53%]
tests/mixology/version_solver/test_basic_graph.py ....                                                                                                               [ 53%]
tests/mixology/version_solver/test_python_constraint.py .                                                                                                            [ 53%]
tests/mixology/version_solver/test_unsolvable.py .....                                                                                                               [ 54%]
tests/mixology/version_solver/test_with_lock.py .....                                                                                                                [ 55%]
tests/packages/test_locker.py ..............                                                                                                                         [ 57%]
tests/publishing/test_publisher.py ........                                                                                                                          [ 58%]
tests/publishing/test_uploader.py ...                                                                                                                                [ 59%]
tests/puzzle/test_provider.py .....................                                                                                                                  [ 62%]
tests/puzzle/test_solver.py ...............................................................................................                                          [ 77%]
tests/repositories/test_legacy_repository.py ......................                                                                                                  [ 80%]
tests/repositories/test_pool.py .......                                                                                                                              [ 81%]
tests/repositories/test_pypi_repository.py ...............                                                                                                           [ 83%]
tests/utils/test_env.py ...F.FFFFFFFFFFF.F.F...FF..FFF.......                                                                                                        [ 89%]
tests/utils/test_env_site.py ..                                                                                                                                      [ 89%]
tests/utils/test_exporter.py ...............................                                                                                                         [ 94%]
tests/utils/test_extras.py .......                                                                                                                                   [ 95%]
tests/utils/test_helpers.py ...                                                                                                                                      [ 96%]
tests/utils/test_password_manager.py ...............                                                                                                                 [ 98%]
tests/utils/test_patterns.py ..                                                                                                                                      [ 98%]
tests/utils/test_setup_reader.py .........                                                                                                                           [100%]

[..]

============================================================================= warnings summary =============================================================================
tests/helpers.py:139
  /home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/tests/helpers.py:139: PytestCollectionWarning: cannot collect test class 'TestApplication' because it has a __init__ constructor (from: tests/console/commands/test_init.py)
    class TestApplication(Application):

tests/console/commands/test_publish.py: 6 warnings
tests/publishing/test_uploader.py: 6 warnings
  /home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/poetry/publishing/uploader.py:62: DeprecationWarning: Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead
    retry = util.Retry(

tests/console/commands/test_publish.py::test_publish_returns_non_zero_code_for_connection_errors
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-26

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/usr/lib/python3.8/site-packages/httpretty/core.py", line 1097, in fill_filekind
      status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
    File "/home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/tests/console/commands/test_publish.py", line 35, in request_callback
      raise requests.ConnectionError()
  requests.exceptions.ConnectionError

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/installation/test_authenticator.py::test_authenticator_request_retries_on_exception
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-79

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/usr/lib/python3.8/site-packages/httpretty/core.py", line 1097, in fill_filekind
      status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
    File "/home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/tests/installation/test_authenticator.py", line 130, in callback
      raise requests.exceptions.ConnectionError("Disconnected")
  requests.exceptions.ConnectionError: Disconnected

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/installation/test_authenticator.py::test_authenticator_request_raises_exception_when_attempts_exhausted
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-86

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/usr/lib/python3.8/site-packages/httpretty/core.py", line 1097, in fill_filekind
      status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
    File "/home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/tests/installation/test_authenticator.py", line 148, in callback
      raise requests.exceptions.ConnectionError(str(uuid.uuid4()))
  requests.exceptions.ConnectionError: 8a79db4a-8d4a-415a-a677-7baf7d9a06ac

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] tests/console/commands/test_publish.py:50: Improved error rendering is not available on Python <3.6
SKIPPED [1] tests/inspection/test_info.py:166: For projects with setup.py using Python < 3.5 fallback to pep517 build
SKIPPED [1] tests/installation/test_installer.py:1443: This is not working at the moment due to limitations in the resolver
SKIPPED [1] tests/installation/test_installer_old.py:1395: This is not working at the moment due to limitations in the resolver
FAILED tests/console/commands/test_export.py::test_export_exports_requirements_txt_file_locks_if_no_lock_file - SystemExit: 2
FAILED tests/console/commands/env/test_list.py::test_none_activated - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/console/commands/env/test_list.py::test_activated - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/console/commands/env/test_list.py::test_in_project_venv - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/console/commands/env/test_remove.py::test_remove_by_name - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/console/commands/env/test_use.py::test_activate_activates_non_existing_virtualenv_no_envs_file - FileNotFoundError: [Errno 2] No such file or directory: 'py...
FAILED tests/console/commands/env/test_use.py::test_get_prefers_explicitly_activated_virtualenvs_over_env_var - FileNotFoundError: [Errno 2] No such file or directory: '...
FAILED tests/console/commands/env/test_use.py::test_get_prefers_explicitly_activated_non_existing_virtualenvs_over_env_var - FileNotFoundError: [Errno 2] No such file or...
FAILED tests/utils/test_env.py::test_env_get_venv_with_venv_folder_present[True] - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_env_get_venv_with_venv_folder_present[None] - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_activate_activates_non_existing_virtualenv_no_envs_file - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_activate_activates_existing_virtualenv_no_envs_file - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_activate_activates_same_virtualenv_with_envs_file - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_activate_activates_different_virtualenv_with_envs_file - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_activate_activates_recreates_for_different_patch - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_activate_does_not_recreate_when_switching_minor - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_deactivate_non_activated_but_existing - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_deactivate_activated - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_get_prefers_explicitly_activated_virtualenvs_over_env_var - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_list - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_remove_by_name - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_remove_keeps_dir_if_not_deleteable - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_create_venv_tries_to_find_a_compatible_python_executable_using_generic_ones_first - FileNotFoundError: [Errno 2] No such file or dir...
FAILED tests/utils/test_env.py::test_create_venv_tries_to_find_a_compatible_python_executable_using_specific_ones - FileNotFoundError: [Errno 2] No such file or director...
FAILED tests/utils/test_env.py::test_create_venv_uses_patch_version_to_detect_compatibility - FileNotFoundError: [Errno 2] No such file or directory: 'python'
FAILED tests/utils/test_env.py::test_create_venv_uses_patch_version_to_detect_compatibility_with_executable - FileNotFoundError: [Errno 2] No such file or directory: 'py...
FAILED tests/utils/test_env.py::test_activate_with_in_project_setting_does_not_fail_if_no_venvs_dir - FileNotFoundError: [Errno 2] No such file or directory: 'python'
==================================================== 27 failed, 623 passed, 4 skipped, 16 warnings in 137.98s (0:02:17) ====================================================
```
If you want full pytet output please let me know (I'm not copying iot here because it has more than 64KB).

**Comment by kloczek** [comment]
After deselecting all above units it as well another issue with `pytest-mock`.
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-poetry-1.1.13-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-poetry-1.1.13-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --deselect tests/console/commands/env/test_list.py::test_activated --deselect tests/console/commands/env/test_list.py::test_in_project_venv --deselect tests/console/commands/env/test_list.py::test_none_activated --deselect tests/console/commands/env/test_remove.py::test_remove_by_name --deselect tests/console/commands/env/test_use.py::test_activate_activates_non_existing_virtualenv_no_envs_file --deselect tests/console/commands/env/test_use.py::test_get_prefers_explicitly_activated_non_existing_virtualenvs_over_env_var --deselect tests/console/commands/env/test_use.py::test_get_prefers_explicitly_activated_virtualenvs_over_env_var --deselect tests/console/commands/test_export.py::test_export_exports_requirements_txt_file_locks_if_no_lock_file --deselect tests/utils/test_env.py::test_activate_activates_different_virtualenv_with_envs_file --deselect tests/utils/test_env.py::test_activate_activates_existing_virtualenv_no_envs_file --deselect tests/utils/test_env.py::test_activate_activates_non_existing_virtualenv_no_envs_file --deselect tests/utils/test_env.py::test_activate_activates_recreates_for_different_patch --deselect tests/utils/test_env.py::test_activate_activates_same_virtualenv_with_envs_file --deselect tests/utils/test_env.py::test_activate_does_not_recreate_when_switching_minor --deselect tests/utils/test_env.py::test_activate_with_in_project_setting_does_not_fail_if_no_venvs_dir --deselect tests/utils/test_env.py::test_create_venv_tries_to_find_a_compatible_python_executable_using_generic_ones_first --deselect tests/utils/test_env.py::test_create_venv_tries_to_find_a_compatible_python_executable_using_specific_ones --deselect tests/utils/test_env.py::test_create_venv_uses_patch_version_to_detect_compatibility --deselect tests/utils/test_env.py::test_create_venv_uses_patch_version_to_detect_compatibility_with_executable --deselect tests/utils/test_env.py::test_deactivate_activated --deselect tests/utils/test_env.py::test_deactivate_non_activated_but_existing --deselect 'tests/utils/test_env.py::test_env_get_venv_with_venv_folder_present[None]' --deselect 'tests/utils/test_env.py::test_env_get_venv_with_venv_folder_present[True]' --deselect tests/utils/test_env.py::test_get_prefers_explicitly_activated_virtualenvs_over_env_var --deselect tests/utils/test_env.py::test_list --deselect tests/utils/test_env.py::test_remove_by_name --deselect tests/utils/test_env.py::test_remove_keeps_dir_if_not_deleteable
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.11.0, pluggy-1.0.0
rootdir: /home/tkloczko/rpmbuild/BUILD/poetry-1.1.13
plugins: mock-3.7.0
collected 654 items / 1 error / 27 deselected / 626 selected

================================================================================== ERRORS ==================================================================================
_____________________________________________________ ERROR collecting tests/repositories/test_installed_repository.py _____________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/tests/repositories/test_installed_repository.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/repositories/test_installed_repository.py:5: in <module>
    from pytest_mock.plugin import MockFixture
E   ImportError: cannot import name 'MockFixture' from 'pytest_mock.plugin' (/usr/lib/python3.8/site-packages/pytest_mock/plugin.py)
============================================================================= warnings summary =============================================================================
tests/helpers.py:139
  /home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/tests/helpers.py:139: PytestCollectionWarning: cannot collect test class 'TestApplication' because it has a __init__ constructor (from: tests/console/commands/test_init.py)
    class TestApplication(Application):

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
ERROR tests/repositories/test_installed_repository.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
================================================================ 27 deselected, 1 warning, 1 error in 2.08s ================================================================
```
I'm using `pytest-mock` 3.7.0.

**Comment by kloczek** [comment]
list of modules installed in build env
```console
Package            Version
------------------ --------------
asciidoc           10.1.1
attrs              21.4.0
build              0.7.0
CacheControl       0.12.10
cachy              0.3.0
cffi               1.15.0
charset-normalizer 2.0.10
cleo               0.8.1
clikit             0.6.2
crashtest          0.3.1
cryptography       36.0.1
distlib            0.3.4
distro             1.6.0
extended-project   1.2.3
filelock           3.4.2
gpg                1.16.0-unknown
html5lib           1.1
httpretty          1.1.4
idna               3.3
importlib-metadata 4.10.1
iniconfig          1.1.1
jeepney            0.7.1
keyring            23.5.0
libcomps           0.1.18
lockfile           0.12.2
meson              0.61.1
mock               4.0.3
msgpack            1.0.3
packaging          21.3
pastel             0.2.1
pep517             0.12.0
pexpect            4.8.0
pip                21.3.1
pkginfo            1.8.2
platformdirs       2.5.0
pluggy             1.0.0
ply                3.11
poetry-core        1.0.7
ptyprocess         0.7.0
py                 1.11.0
pycparser          2.21
PyGObject          3.42.0
pylev              1.4.0
pyparsing          3.0.7
pytest             6.2.5
pytest-mock        3.7.0
python-dateutil    2.8.2
requests           2.27.1
requests-toolbelt  0.9.1
rpm                4.17.0
SecretStorage      3.3.1
shellingham        1.4.0
simple-project     1.2.3
six                1.16.0
toml               0.10.2
tomli              2.0.0
tomlkit            0.8.0
urllib3            1.26.8
virtualenv         20.13.0
webencodings       0.5.1
wheel              0.37.1
zipp               3.7.0
```

**Comment by kloczek** [comment]
Summary list of warnings with deselected all failing units and ignore tests/repositories/test_installed_repository.py
```console
============================================================================= warnings summary =============================================================================
tests/helpers.py:139
  /home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/tests/helpers.py:139: PytestCollectionWarning: cannot collect test class 'TestApplication' because it has a __init__ constructor (from: tests/console/commands/test_init.py)
    class TestApplication(Application):

tests/console/commands/test_publish.py: 6 warnings
tests/publishing/test_uploader.py: 6 warnings
  /home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/poetry/publishing/uploader.py:62: DeprecationWarning: Using 'method_whitelist' with Retry is deprecated and will be removed in v2.0. Use 'allowed_methods' instead
    retry = util.Retry(

tests/console/commands/test_publish.py::test_publish_returns_non_zero_code_for_connection_errors
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-26

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/usr/lib/python3.8/site-packages/httpretty/core.py", line 1097, in fill_filekind
      status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
    File "/home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/tests/console/commands/test_publish.py", line 35, in request_callback
      raise requests.ConnectionError()
  requests.exceptions.ConnectionError

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/installation/test_authenticator.py::test_authenticator_request_retries_on_exception
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-79

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/usr/lib/python3.8/site-packages/httpretty/core.py", line 1097, in fill_filekind
      status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
    File "/home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/tests/installation/test_authenticator.py", line 130, in callback
      raise requests.exceptions.ConnectionError("Disconnected")
  requests.exceptions.ConnectionError: Disconnected

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

tests/installation/test_authenticator.py::test_authenticator_request_raises_exception_when_attempts_exhausted
  /usr/lib/python3.8/site-packages/_pytest/threadexception.py:75: PytestUnhandledThreadExceptionWarning: Exception in thread Thread-86

  Traceback (most recent call last):
    File "/usr/lib64/python3.8/threading.py", line 932, in _bootstrap_inner
      self.run()
    File "/usr/lib64/python3.8/threading.py", line 870, in run
      self._target(*self._args, **self._kwargs)
    File "/usr/lib/python3.8/site-packages/httpretty/core.py", line 1097, in fill_filekind
      status, headers, self.body = self.callable_body(self.request, self.info.full_url(), headers)
    File "/home/tkloczko/rpmbuild/BUILD/poetry-1.1.13/tests/installation/test_authenticator.py", line 148, in callback
      raise requests.exceptions.ConnectionError(str(uuid.uuid4()))
  requests.exceptions.ConnectionError: 946c4a55-95e1-44ac-9ebe-98ca19d7c6ca

    warnings.warn(pytest.PytestUnhandledThreadExceptionWarning(msg))

-- Docs: https://docs.pytest.org/en/stable/warnings.html
========================================================================= short test summary info ==========================================================================
SKIPPED [1] tests/console/commands/test_publish.py:50: Improved error rendering is not available on Python <3.6
SKIPPED [1] tests/inspection/test_info.py:166: For projects with setup.py using Python < 3.5 fallback to pep517 build
SKIPPED [1] tests/installation/test_installer.py:1443: This is not working at the moment due to limitations in the resolver
SKIPPED [1] tests/installation/test_installer_old.py:1395: This is not working at the moment due to limitations in the resolver
================================================== 623 passed, 4 skipped, 27 deselected, 16 warnings in 128.11s (0:02:08) ==================================================
```

**Comment by finswimmer** [comment]
Hello,

you haven't come back to this issue for a long while. So I assume this is solved in the meantime and I can close this ticket.

Feel free to leave a comment if you disagree.

fin swimmer

**Comment by Secrus** [comment]
> Just retested 1.2.0 and I fould that somethinf is wrong with use of `cleo`. I have instlled in build env `cleo` 0.8.` and pytest is failing with ..
> 
> ```
> + PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-poetry-1.2.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-poetry-1.2.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
> + /usr/bin/pytest -ra
> ImportError while loading conftest '/home/tkloczko/rpmbuild/BUILD/poetry-1.2.0/tests/conftest.py'.
> tests/conftest.py:23: in <module>
>     from poetry.factory import Factory
> ../../BUILDROOT/python-poetry-1.2.0-2.fc35.x86_64/usr/lib/python3.8/site-packages/poetry/factory.py:12: in <module>
>     from cleo.io.null_io import NullIO
> E   ModuleNotFoundError: No module named 'cleo.io.null_io'
> ```
> 
> Can you help with some advice? thinking

Poetry 1.2 is using Cleo in pre-release version (since we maintain both repos, we can handle a pre-release). Cleo 1.0 will be released soon and it should fix this error. See #6353
