### ISSUE TITLE
install-poetry.py fails on Python 3.10.3

### ISSUE THREAD

**Issue by mortenlj** [python-poetry/poetry#5487]
- [N/A] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [N/A] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 21.10
- **Poetry version**: N/A
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: N/A

## Issue

When trying to install Poetry on Python 3.10.3 (built from source), a weird exception happens when the subprocess module is imported, which doesn't happen if I start an interpreter and import subprocess.

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/subprocess.py", line 69, in <module>
    import msvcrt
ModuleNotFoundError: No module named 'msvcrt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/usr/local/lib/python3.10/ensurepip/__init__.py", line 4, in <module>
    import subprocess
  File "/usr/local/lib/python3.10/subprocess.py", line 74, in <module>
    import _posixsubprocess
ModuleNotFoundError: No module named '_posixsubprocess'

Traceback:

  File "/tmp/./install-poetry.py", line 879, in main
    return installer.run()
  File "/tmp/./install-poetry.py", line 517, in run
    raise PoetryInstallationError(
```

The problem doesn't happen when running with Python 3.9.11.

**Comment by eyllanesc** [comment]
@mortenlj It seems to be a bug in python(or your build) rather than poetry since msvcrt is a windows package and not a Linux one.

**Comment by mortenlj** [comment]
> It seems to be a bug in python(or your build) rather than poetry since that the `_posixsubprocess` module has not been generated.

When I start the interpreter normally, and do `import subprocess`, everything works as normal. So poetry is doing something that influences the interpreter to fail in this manner.

**Comment by abn** [comment]
@mortenlj sounds like https://stackoverflow.com/questions/66814603/pip-is-not-working-error-no-module-named-msvcrt

**Comment by Secrus** [comment]
@mortenlj did the link help?

**Comment by mortenlj** [comment]
I don't know what has changed, but tried to reproduce now and now it works without having done any changes.
I do find it unlikely that this was caused by a missing symlink (which is still missing btw), because importing subprocess worked when not done by the install-poetry.py script. In any case, this is now solved somehow, so closing the issue.

**Comment by ubotser** [comment]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/runpy.py", line 18[7](https://github.com/ubotser/bot-deploy/actions/runs/3210318164/jobs/5247671338#step:6:8), in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/local/lib/python3.10/runpy.py", line 146, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "/usr/local/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/__w/bot-deploy/bot-deploy/ubotser/ProjectMan/__init__.py", line [8](https://github.com/ubotser/bot-deploy/actions/runs/3210318164/jobs/5247671338#step:6:9)6, in <module>
    Client(
TypeError: Client.__init__() got an unexpected keyword argument 'session_name'
