### ISSUE TITLE
install-poetry.py crashes on Python 3.11 beta 1

### ISSUE THREAD

**Issue by davidfstr** [python-poetry/poetry#5597]
Repro steps:

```
$ wget https://raw.githubusercontent.com/python-poetry/poetry/master/install-poetry.py
$ python3 install-poetry.py 
[...]
Installing Poetry (1.1.13): Creating environment
Traceback (most recent call last):
  File "/Users/davidf/Projects/trycast/install-poetry.py", line 908, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/davidf/Projects/trycast/install-poetry.py", line 876, in main
    return installer.run()
           ^^^^^^^^^^^^^^^
  File "/Users/davidf/Projects/trycast/install-poetry.py", line 507, in run
    self.install(version)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidf/Projects/trycast/install-poetry.py", line 528, in install
    with self.make_env(version) as env:
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "/Users/davidf/Projects/trycast/install-poetry.py", line 600, in make_env
    raise e
    ^^^^^^^
  File "/Users/davidf/Projects/trycast/install-poetry.py", line 586, in make_env
    yield VirtualEnvironment.make(env_path)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/davidf/Projects/trycast/install-poetry.py", line 292, in make
    builder.ensure_directories(target)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/venv/__init__.py", line 119, in ensure_directories
    if os.pathsep in env_dir:
       ^^^^^^^^^^^^^^^^^^^^^
TypeError: argument of type 'PosixPath' is not iterable
```

**Your environment**

* CPython 3.11 beta 1

I'm shepherding a fix to upstream Python 3.11: https://github.com/python/cpython/issues/92675

**Comment by davidfstr** [comment]
The upstream `venv` module has been fixed in CPython, with the fix [backported to CPython 3.11](https://github.com/python/cpython/pull/92961). It should be released in CPython 3.11 beta 2, [estimated for 2022-05-30](https://peps.python.org/pep-0664/).

**Comment by davidfstr** [comment]
I've confirmed that the development version of CPython (with the above-mentioned fix) is able to run install-poetry.py without any additional errors.

**Comment by abn** [comment]
@davidfstr thank you for reporting this and handling it upstream. Much appreciated.
