### ISSUE TITLE
`poetry install` fails with `EnvCommandError` searching for Python `3.9.12` instead of running installed Python `3.9.13`

### ISSUE THREAD

**Issue by ancalita** [python-poetry/poetry#5735]
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:   Microsoft Windows Server 2019 10.0.17763
- **Poetry version**:  1.1.11
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: 

## Issue

A Github Actions CI workflow consistently fails on the job that installs Python 3.9 on Windows 2019 at the `poetry install` command.

These are the environment values:
```
DEFAULT_PYTHON_VERSION: 3.9
POETRY_VERSION: 1.1.11
pythonLocation: C:\hostedtoolcache\windows\Python\3.9.13\x64
```

Full traceback here:

```
poetry install

  EnvCommandError

  Command D:\a\framework-plus\framework-plus\.venv\Scripts\python.exe -W ignore - errored with the following return code 103, and output: 
  No Python at 'C:\hostedtoolcache\windows\Python\3.9.12\x64\python.exe'

  input was : import sys
  
  if hasattr(sys, "real_prefix"):
      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:
      print(sys.prefix)
  

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py:1183 in _run
Traceback (most recent call last):
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py", line 1168, in _run
    output = subprocess.run(
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\_compat.py", line 217, in run
    raise CalledProcessError(
poetry.utils._compat.CalledProcessError: Command 'D:\a\framework-plus\framework-plus\.venv\Scripts\python.exe -W ignore -' returned non-zero exit status 103.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\command\command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\command\command.py", line 163, in _do_handle
    self._dispatcher.dispatch(PRE_HANDLE, event)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\event\event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\event\event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\config\application_config.py", line 119, in set_env
    env = env_manager.create_venv(io)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py", line 659, in create_venv
    env = self.get(reload=True)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py", line 502, in get
    return VirtualEnv(venv)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py", line 1363, in __init__
    self._base = Path(self.run_python_script(GET_BASE_PREFIX).strip())
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py", line 1151, in run_python_script
    return self.run(self._executable, "-W", "ignore", "-", input_=content, **kwargs)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py", line 1140, in run
    return self._run(cmd, **kwargs)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py", line 1441, in _run
    return super(VirtualEnv, self)._run(cmd, **kwargs)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\utils\env.py", line 1183, in _run
    raise EnvCommandError(e, input=input_)
poetry.utils.env.EnvCommandError: Command D:\a\framework-plus\framework-plus\.venv\Scripts\python.exe -W ignore - errored with the following return code 103, and output: 
No Python at 'C:\hostedtoolcache\windows\Python\3.9.12\x64\python.exe'

input was : import sys

if hasattr(sys, "real_prefix"):
    print(sys.real_prefix)
elif hasattr(sys, "base_prefix"):
    print(sys.base_prefix)
else:
    print(sys.prefix)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\runneradmin\AppData\Roaming\Python\Scripts\poetry.exe\__main__.py", line 7, in <module>
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\console\__init__.py", line 5, in main
    return Application().run()
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\console_application.py", line 142, in run
    trace.render(io, simple=isinstance(e, CliKitException))
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\ui\components\exception_trace.py", line 232, in render
    return self._render_exception(io, self._exception)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\ui\components\exception_trace.py", line 269, in _render_exception
    self._render_snippet(io, current_frame)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\ui\components\exception_trace.py", line 289, in _render_snippet
    self._render_line(io, code_line)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\ui\components\exception_trace.py", line 402, in _render_line
    io.write_line("{}{}".format(indent * " ", line))
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\cleo\io\io_mixin.py", line 65, in write_line
    super(IOMixin, self).write_line(string, flags)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\io\io.py", line 66, in write_line
    self._output.write_line(string, flags=flags)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\io\output.py", line 69, in write_line
    self.write(string, flags=flags, new_line=True)
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\api\io\output.py", line 61, in write
    self._stream.write(to_str(formatted))
  File "C:\Users\runneradmin\AppData\Roaming\pypoetry\venv\lib\site-packages\clikit\io\output_stream\stream_output_stream.py", line 24, in write
    self._stream.write(string)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2502' in position 10: character maps to <undefined>
```

**Comment by ancalita** [comment]
@finswimmer Confirming that upgrading to version `1.1.13` fixed the issue, closing this ticket.
