### ISSUE TITLE
Can't add scanpy package

### ISSUE THREAD

**Issue by diklios5768** [python-poetry/poetry#5920]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **Windows10 , Centos7**
- **1.1.13**

## Issue
Just run `poetry add scanpy` and you can see the error. It cannot be installed successfully.

Error infos:
```sh
Using version ^1.9.1 for scanpy

Updating dependencies
Resolving dependencies... (83.2s)

Writing lock file

Package operations: 31 installs, 1 update, 0 removals

  • Installing numpy (1.23.0)
  • Installing joblib (1.1.0)
  • Installing llvmlite (0.34.0): Failed

  EnvCommandError

  Command ['/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/bin/pip', 'install', '--no-deps', '/share2/home/sunhj/.cache/pypoetry/artifacts/9e/1c/c8/439ee74bf8837fa4dae6747de4184a713dd70697520cd1d1500b1141f0/llvmlite-0.34.0.tar.gz'] errored with the following return code 1, and output:
  Processing /share2/home/sunhj/.cache/pypoetry/artifacts/9e/1c/c8/439ee74bf8837fa4dae6747de4184a713dd70697520cd1d1500b1141f0/llvmlite-0.34.0.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Building wheels for collected packages: llvmlite
    Building wheel for llvmlite (setup.py): started
    Building wheel for llvmlite (setup.py): finished with status 'error'
    error: subprocess-exited-with-error

    × python setup.py bdist_wheel did not run successfully.
    │ exit code: 1
    ╰─> [26 lines of output]
        running bdist_wheel
        /share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/bin/python3.10 /tmp/pip-req-build-rjb_h090/ffi/build.py
        LLVM version... Traceback (most recent call last):
          File "/tmp/pip-req-build-rjb_h090/ffi/build.py", line 105, in main_posix
            out = subprocess.check_output([llvm_config, '--version'])
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/subprocess.py", line 420, in check_output
            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/subprocess.py", line 501, in run
            with Popen(*popenargs, **kwargs) as process:
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/subprocess.py", line 969, in __init__
            self._execute_child(args, executable, preexec_fn, close_fds,
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/subprocess.py", line 1845, in _execute_child
            raise child_exception_type(errno_num, err_msg, err_filename)
        FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/tmp/pip-req-build-rjb_h090/ffi/build.py", line 191, in <module>
            main()
          File "/tmp/pip-req-build-rjb_h090/ffi/build.py", line 181, in main
            main_posix('linux', '.so')
          File "/tmp/pip-req-build-rjb_h090/ffi/build.py", line 107, in main_posix
            raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
        RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
        error: command '/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/bin/python3.10' failed with exit code 1
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for llvmlite
    Running setup.py clean for llvmlite
  Failed to build llvmlite
  Installing collected packages: llvmlite
    Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    error: subprocess-exited-with-error

    × Running setup.py install for llvmlite did not run successfully.
    │ exit code: 1
    ╰─> [31 lines of output]
        running install
        /share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        running build
        got version from file /tmp/pip-req-build-rjb_h090/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
        running build_ext
        /share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/bin/python3.10 /tmp/pip-req-build-rjb_h090/ffi/build.py
        LLVM version... Traceback (most recent call last):
          File "/tmp/pip-req-build-rjb_h090/ffi/build.py", line 105, in main_posix
            out = subprocess.check_output([llvm_config, '--version'])
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/subprocess.py", line 420, in check_output
            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/subprocess.py", line 501, in run
            with Popen(*popenargs, **kwargs) as process:
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/subprocess.py", line 969, in __init__
            self._execute_child(args, executable, preexec_fn, close_fds,
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/subprocess.py", line 1845, in _execute_child
            raise child_exception_type(errno_num, err_msg, err_filename)
        FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

        During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "/tmp/pip-req-build-rjb_h090/ffi/build.py", line 191, in <module>
            main()
          File "/tmp/pip-req-build-rjb_h090/ffi/build.py", line 181, in main
            main_posix('linux', '.so')
          File "/tmp/pip-req-build-rjb_h090/ffi/build.py", line 107, in main_posix
            raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
        RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
        error: command '/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/bin/python3.10' failed with exit code 1
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: legacy-install-failure

  × Encountered error while trying to install package.
  ╰─> llvmlite

  note: This is an issue with the package mentioned above, not pip.
  hint: See above for output from the failure.


  at /share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):

  • Updating packaging (20.9 -> 21.3)
  • Installing scipy (1.6.1): Failed

  EnvCommandError

  Command ['/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/bin/pip', 'install', '--no-deps', '/share2/home/sunhj/.cache/pypoetry/artifacts/bc/74/e2/a22451059efb69c32be2d51a7727b1133375122dd7564e8a8e9df4f1cd/scipy-1.6.1.tar.gz'] errored with the following return code 1, and output:
  Processing /share2/home/sunhj/.cache/pypoetry/artifacts/bc/74/e2/a22451059efb69c32be2d51a7727b1133375122dd7564e8a8e9df4f1cd/scipy-1.6.1.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error

    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [139 lines of output]
        setup.py:461: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-irsicazy'), proceeding with generating Cython sources and expanding templates
          warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "
        setup.py:563: DeprecationWarning:

          `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
          of the deprecation of `distutils` itself. It will be removed for
          Python >= 3.12. For older Python versions it will remain present.
          It is recommended to use `setuptools < 60.0` for those Python versions.
          For more details, see:
            https://numpy.org/devdocs/reference/distutils_status_migration.html


          from numpy.distutils.core import setup
        Running from SciPy source directory.
        INFO: lapack_opt_info:
        INFO: lapack_armpl_info:
        INFO: customize UnixCCompiler
        INFO:   libraries armpl_lp64_mp not found in ['/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        INFO:   NOT AVAILABLE
        INFO:
        INFO: lapack_mkl_info:
        INFO:   libraries mkl_rt not found in ['/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        INFO:   NOT AVAILABLE
        INFO:
        INFO: openblas_lapack_info:
        INFO:   libraries openblas not found in ['/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        INFO:   NOT AVAILABLE
        INFO:
        INFO: openblas_clapack_info:
        INFO:   libraries openblas,lapack not found in ['/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        INFO:   NOT AVAILABLE
        INFO:
        INFO: flame_info:
        INFO:   libraries flame not found in ['/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        INFO:   NOT AVAILABLE
        INFO:
        INFO: accelerate_info:
        INFO:   NOT AVAILABLE
        INFO:
        INFO: atlas_3_10_threads_info:
        INFO: Setting PTATLAS=ATLAS
        INFO:   libraries tatlas,tatlas not found in /share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib
        INFO:   libraries tatlas,tatlas not found in /usr/local/lib64
        INFO:   libraries tatlas,tatlas not found in /usr/local/lib
        INFO:   libraries tatlas,tatlas not found in /usr/lib64/sse2
        INFO:   libraries tatlas,tatlas not found in /usr/lib64
        INFO:   libraries tatlas,tatlas not found in /usr/lib/sse2
        INFO:   libraries tatlas,tatlas not found in /usr/lib
        INFO:   libraries tatlas,tatlas not found in /usr/lib/sse2
        INFO:   libraries tatlas,tatlas not found in /usr/lib/
        INFO: <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
        INFO:   NOT AVAILABLE
        INFO:
        INFO: atlas_3_10_info:
        INFO:   libraries satlas,satlas not found in /share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib
        INFO:   libraries satlas,satlas not found in /usr/local/lib64
        INFO:   libraries satlas,satlas not found in /usr/local/lib
        INFO:   libraries satlas,satlas not found in /usr/lib64/sse2
        INFO:   libraries satlas,satlas not found in /usr/lib64
        INFO:   libraries satlas,satlas not found in /usr/lib/sse2
        INFO:   libraries satlas,satlas not found in /usr/lib
        INFO:   libraries satlas,satlas not found in /usr/lib/sse2
        INFO:   libraries satlas,satlas not found in /usr/lib/
        INFO: <class 'numpy.distutils.system_info.atlas_3_10_info'>
        INFO:   NOT AVAILABLE
        INFO:
        INFO: atlas_threads_info:
        INFO: Setting PTATLAS=ATLAS
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib64
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib64/sse2
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib64
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib/sse2
        INFO:   libraries ptf77blas,ptcblas,atlas not found in /usr/lib/
        INFO: <class 'numpy.distutils.system_info.atlas_threads_info'>
        INFO:   NOT AVAILABLE
        INFO:
        INFO: atlas_info:
        INFO:   libraries f77blas,cblas,atlas not found in /share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib
        INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib64
        INFO:   libraries f77blas,cblas,atlas not found in /usr/local/lib
        INFO:   libraries f77blas,cblas,atlas not found in /usr/lib64/sse2
        INFO:   libraries f77blas,cblas,atlas not found in /usr/lib64
        INFO:   libraries f77blas,cblas,atlas not found in /usr/lib/sse2
        INFO:   libraries f77blas,cblas,atlas not found in /usr/lib
        INFO:   libraries f77blas,cblas,atlas not found in /usr/lib/sse2
        INFO:   libraries f77blas,cblas,atlas not found in /usr/lib/
        INFO: <class 'numpy.distutils.system_info.atlas_info'>
        INFO:   NOT AVAILABLE
        INFO:
        INFO: lapack_info:
        INFO:   libraries lapack not found in ['/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib', '/usr/local/lib64', '/usr/local/lib', '/usr/lib64', '/usr/lib', '/usr/lib/']
        INFO:   NOT AVAILABLE
        INFO:
        /tmp/pip-build-env-s872i3d3/overlay/lib/python3.10/site-packages/numpy/distutils/system_info.py:1902: UserWarning:
            Lapack (http://www.netlib.org/lapack/) libraries not found.
            Directories to search for the libraries can be specified in the
            numpy/distutils/site.cfg file (section [lapack]) or by setting
            the LAPACK environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
        INFO: lapack_src_info:
        INFO:   NOT AVAILABLE
        INFO:
        /tmp/pip-build-env-s872i3d3/overlay/lib/python3.10/site-packages/numpy/distutils/system_info.py:1902: UserWarning:
            Lapack (http://www.netlib.org/lapack/) sources not found.
            Directories to search for the sources can be specified in the
            numpy/distutils/site.cfg file (section [lapack_src]) or by setting
            the LAPACK_SRC environment variable.
          return getattr(self, '_calc_info_{}'.format(name))()
        INFO:   NOT AVAILABLE
        INFO:
        Traceback (most recent call last):
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
            main()
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "/tmp/pip-build-env-s872i3d3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 161, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "/tmp/pip-build-env-s872i3d3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 253, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/tmp/pip-build-env-s872i3d3/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 145, in run_setup
            exec(compile(code, __file__, 'exec'), locals())
          File "setup.py", line 588, in <module>
            setup_package()
          File "setup.py", line 584, in setup_package
            setup(**metadata)
          File "/tmp/pip-build-env-s872i3d3/overlay/lib/python3.10/site-packages/numpy/distutils/core.py", line 135, in setup
            config = configuration()
          File "setup.py", line 499, in configuration
            raise NotFoundError(msg)
        numpy.distutils.system_info.NotFoundError: No BLAS/LAPACK libraries found.
        To build Scipy from sources, BLAS & LAPACK libraries need to be installed.
        See site.cfg.example in the Scipy source directory and
        https://docs.scipy.org/doc/scipy/reference/building/index.html for details.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed

  × Encountered error while generating package metadata.
  ╰─> See above for output.

  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.


  at /share2/pub/sunhj/sunhj/Soft/miniconda3/envs/test/lib/python3.10/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│
      1197│         return decode(output)
      1198│
      1199│     def execute(self, bin, *args, **kwargs):

  • Installing threadpoolctl (3.1.0)
  • Installing tomli (2.0.1)
  • Installing typing-extensions (4.2.0)

Failed to add packages, reverting the pyproject.toml file to its original content.
```

**Comment by mkniewallner** [comment]
This doesn't seem to be an issue with Poetry itself.

`scanpy`, or one of its dependencies, requires `llvmlite` up to `0.34.0`, and `scipy` up to `1.6.1`. Both [llvmlite](https://pypi.org/project/llvmlite/0.34.0/#files) and [scipy](https://pypi.org/project/scipy/1.6.1/#files) don't provide wheels for Python 3.10, thus requiring to have some system dependencies installed in order to be installed.

Either check if newer dependencies make it possible to require newer versions of those libraries, since they provide wheels for Python 3.10, or install the required system dependencies according to both libraries' documentation.

**Comment by diklios5768** [comment]
But run `pip install scanpy` or `pipenv install scanpy` can install successfully. Why are they different?
I tried Python 3.9 and `scipy==1.6.1` can install successfully, but `llvmlite==0.34.0` can't install successfully.

Just run `pip install llvmlite` can succeed:
```sh
Collecting llvmlite
  Downloading llvmlite-0.38.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (34.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 34.5/34.5 MB 10.8 MB/s eta 0:00:00
Installing collected packages: llvmlite
Successfully installed llvmlite-0.38.1
```

But `poetry add llvmlite` failed:
```sh
Using version ^0.38.1 for llvmlite

Updating dependencies
Resolving dependencies... (17.0s)

  SolverProblemError

  The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
    - llvmlite requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0

  Because no versions of llvmlite match >0.38.1,<0.39.0
   and llvmlite (0.38.1) requires Python >=3.7,<3.11, llvmlite is forbidden.
  So, because test depends on llvmlite (^0.38.1), version solving failed.

  at /share2/pub/sunhj/sunhj/Soft/miniconda3/envs/py39/lib/python3.9/site-packages/poetry/puzzle/solver.py:241 in _solve
      237│             packages = result.packages
      238│         except OverrideNeeded as e:
      239│             return self.solve_in_compatibility_mode(e.overrides, use_latest=use_latest)
      240│         except SolveFailure as e:
    → 241│             raise SolverProblemError(e)
      242│
      243│         results = dict(
      244│             depth_first_search(
      245│                 PackageNode(self._package, packages), aggregate_package_nodes

  • Check your dependencies Python requirement: The Python requirement can be specified via the `python` or `markers` properties

    For llvmlite, a possible solution would be to set the `python` property to ">=3.10,<3.11"

    https://python-poetry.org/docs/dependency-specification/#python-restricted-dependencies,
    https://python-poetry.org/docs/dependency-specification/#using-environment-markers
```

It should not be different. And it seems to be not related to `llvmlite` or `scipy` verison.

After use `pip install llvmlite` installed successfully ,run `poetry add scanpy`, it still downgrade `llvmlite` to 0.34.0 and failed finally.

**Comment by dimbleby** [comment]
you've pasted a _completely_ different error message this time, relating to an imcompatibility between the python versions that your project says that it supports and the python versions that llvmlite says that it supports.  Please read and act on the message.

**Comment by dimbleby** [comment]
The reason that poetry is refusing to install llvmlite in your most recent log is clearly explained by the error message.  Please read it.

**Comment by rafrafavi** [comment]
The question he's asking is why does it succeed with pip but fail with poetry? I have the same error on a different package and the same question.  The error is clear enough but the only solution I have found is to use an earlier version of Python, which begs the question why does using poetry with module X require using an earlier version of python when a more recent version of Python will work just fine with module X, without poetry?

**Comment by finswimmer** [comment]
@rafrafavi This FAQ should answer your first question: https://python-poetry.org/docs/master/faq/#why-is-poetry-telling-me-that-the-current-projects-python-requirement-is-not-compatible-with-one-or-more-packages-python-requirements

**Comment by diklios5768** [comment]
> The question he's asking is why does it succeed with pip but fail with poetry? I have the same error on a different package and the same question. The error is clear enough, but as someone trying to get their head around poetry, I am also curious as to why it puts itself in this pickle: `setup.py:461: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-irsicazy'), proceeding with generating Cython sources and expanding templates warnings.warn("Unrecognized setuptools command ('{}'), proceeding with "`

Because poetry version solving error. Poetry has bugs, and they just ignore them, telling me it's my fault:
```
 The current project's Python requirement (>=3.10,<4.0) is not compatible with some of the required packages Python requirement:
    - llvmlite requires Python >=3.7,<3.11, so it will not be satisfied for Python >=3.11,<4.0
```
`>=3.10,<4.0`  and `>=3.7,<3.11` , it should be `>=3.10, <3.11` , not `>=3.11,<4.0` poetry remind.

**Comment by diklios5768** [comment]
```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["diklios"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

**Comment by diklios5768** [comment]
I tried in many different PC, windows10 or Centos7.
```
conda create -n test python=3.10
pip install poetry
poetry init
poetry add scanpy
```
Just not work.

**Comment by dimbleby** [comment]
I don't know how to help you more:

- poetry's error message is helpful
- finswimmer has pointed at the faq explaining what is going on
- I have told you exactly what line to change in your pyproject.toml (which is what the faq also says)

**Comment by diklios5768** [comment]
Sorry, maybe it's my fault, but I have no ability to fix this. I can just simply use conda and pip. I use poetry to record my env.
Can you tell me the whole process to install scanpy in python 3.10? Like these commands:
```
conda create -n test python=3.10
conda activate test
pip install scanpy
```
Or need more operations?

**Comment by dimbleby** [comment]
https://github.com/python-poetry/poetry/issues/5920#issuecomment-1178736746

**Comment by diklios5768** [comment]
I'm so stupid.
Finally I found solution in this issue: https://github.com/pdm-project/pdm/issues/1136, and know what the doc excatly express.
> `>=3.10` means everything newer than 3.10, even an alpha release of 3.11 and future versions of python. Its common for some python packages to put an upper bound on what they support.
Ather change `python="^3.10"` to `python = ">=3.10,<3.11"`, it works.
Thank you @dimbleby! I had wasted so much of your time.

**Comment by diklios5768** [comment]
It seems like these issues are same:
https://github.com/python-poetry/poetry/issues/5752
https://github.com/python-poetry/poetry/issues/5798
https://github.com/pdm-project/pdm/issues/1094
https://github.com/pdm-project/pdm/issues/1007
https://github.com/pdm-project/pdm/issues/1146

Search `scipy`, not `scanpy` in issues can find more related one.
