### ISSUE TITLE
Poetry | RuntimeError: No python executable found in shell environment. Tried: ['python3', 'python', 'py.exe -3', 'py.exe -2']

### ISSUE THREAD

**Issue by danielbellhv** [python-poetry/poetry#5930]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 10
- **Poetry version**: 1.1.13
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [gist](https://gist.github.com/danielbellhv/9934acc860f38093474d67afff7be736)

## Issue
```
HDS+dabell@PF2DCSXD MINGW64 ~/Anaconda3
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
Retrieving Poetry metadata

This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

%USERPROFILE%\.poetry\bin

This path will then be added to your `PATH` environment variable by
modifying the `HKEY_CURRENT_USER/Environment/PATH` registry key.

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing version: 1.1.13
  - Downloading poetry-1.1.13-win32.tar.gz (71.14MB)
Traceback (most recent call last):
  File "<stdin>", line 1118, in <module>
  File "<stdin>", line 1114, in main
  File "<stdin>", line 362, in run
  File "<stdin>", line 556, in install
  File "<stdin>", line 704, in make_bin
  File "<stdin>", line 693, in _which_python
RuntimeError: No python executable found in shell environment. Tried: ['python3', 'python', 'py.exe -3', 'py.exe -2']
```

So, I went into `Anaconda3`, duplicated `python.exe`, renaming it `python3.exe`:
```
HDS+dabell@PF2DCSXD MINGW64 ~/Anaconda3
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
bash: python3: command not found
curl: (23) Failure writing output to destination
(base)
HDS+dabell@PF2DCSXD MINGW64 ~/Anaconda3
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
Retrieving Poetry metadata

This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
Latest version already installed.
(base)
HDS+dabell@PF2DCSXD MINGW64 ~
```

```
HDS+dabell@PF2DCSXD MINGW64 ~/Documents/GitHub/lumada-catalog/synthetic-data-gen (daniel_sims)
$ curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python3
Retrieving Poetry metadata

This installer is deprecated. Poetry versions installed using this script will not be able to use 'self update' command to upgrade to 1.2.0a1 or later.
Latest version already installed.
(base)
HDS+dabell@PF2DCSXD MINGW64 ~/Documents/GitHub/lumada-catalog/synthetic-data-gen (daniel_sims)
$ poetry install
bash: poetry: command not found
(base)
```

I then tried Powershell:
```
PS C:\Users\dabell> (Invoke-WebRequest -Uri https://install.python-poetry.org -UseBasicParsing).Content | python3       Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

C:\Users\dabell\AppData\Roaming\Python\Scripts

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.1.13)
Installing Poetry (1.1.13): Creating environment
Installing Poetry (1.1.13): Installing Poetry
Installing Poetry (1.1.13): Creating script
Installing Poetry (1.1.13): Done

Poetry (1.1.13) is installed now. Great!

To get started you need Poetry's bin directory (C:\Users\dabell\AppData\Roaming\Python\Scripts) in your `PATH`
environment variable.

Alternatively, you can call Poetry explicitly with `C:\Users\dabell\AppData\Roaming\Python\Scripts\poetry`.

You can test that everything is set up by executing:

`poetry --version`

PS C:\Users\dabell> poetry --version
poetry : The term 'poetry' is not recognized as the name of a cmdlet, function, script file, or operable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ poetry --version
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (poetry:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

**Comment by dimbleby** [comment]
As the logs say, you are using a deprecated installer.

I've no idea whether the new installer does better - perhaps you'd like to try? - but I wouldn't expect that anyone is going to fix the deprecated installer.

**Comment by danielbellhv** [comment]
@dimbleby What would you suggest I do then?

I'm not aware of installers. As long as I get a recent enough version working; I'm happy

**Comment by dimbleby** [comment]
Did you do this?
```
To get started you need Poetry's bin directory (C:\Users\dabell\AppData\Roaming\Python\Scripts) in your `PATH`
environment variable.

Alternatively, you can call Poetry explicitly with `C:\Users\dabell\AppData\Roaming\Python\Scripts\poetry`.
```

**Comment by danielbellhv** [comment]
Will try now

**Comment by danielbellhv** [comment]
I have `C:\Users\dabell\AppData\Roaming\Python\Scripts\poetry.symlink`. What do I do with it?

**Comment by danielbellhv** [comment]
Lmao fair, Thanks

**Comment by danielbellhv** [comment]
Miniconda3:
```
HDS+dabell@PF2DCSXD MINGW64 ~/Documents/GitHub/lumada-catalog/synthetic-data-gen (daniel_sims)
$ poetry install

  EnvCommandError

  Command C:\Users\dabell\Miniconda3\envs\sdg\python.exe -W ignore - errored with the following return code 1, and output:
  input was : import sys

  if hasattr(sys, "real_prefix"):
      print(sys.real_prefix)
  elif hasattr(sys, "base_prefix"):
      print(sys.base_prefix)
  else:
      print(sys.prefix)


  at ~\Miniconda3\envs\sdg\lib\site-packages\poetry\utils\env.py:1195 in _run
Traceback (most recent call last):
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\utils\env.py", line 1180, in _run
    output = subprocess.run(
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\utils\_compat.py", line 217, in run
    raise CalledProcessError(
poetry.utils._compat.CalledProcessError: Command 'C:\Users\dabell\Miniconda3\envs\sdg\python.exe -W ignore -' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\console_application.py", line 131, in run
    status_code = command.handle(parsed_args, io)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\api\command\command.py", line 120, in handle
    status_code = self._do_handle(args, io)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\api\command\command.py", line 163, in _do_handle
    self._dispatcher.dispatch(PRE_HANDLE, event)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\api\event\event_dispatcher.py", line 22, in dispatch
    self._do_dispatch(listeners, event_name, event)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\api\event\event_dispatcher.py", line 89, in _do_dispatch
    listener(event, event_name, self)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\console\config\application_config.py", line 119, in set_env
    env = env_manager.create_venv(io)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\utils\env.py", line 659, in create_venv
    env = self.get(reload=True)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\utils\env.py", line 531, in get
    return VirtualEnv(prefix, base_prefix)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\utils\env.py", line 1375, in __init__
    self._base = Path(self.run_python_script(GET_BASE_PREFIX).strip())
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\utils\env.py", line 1163, in run_python_script
    return self.run(self._executable, "-W", "ignore", "-", input_=content, **kwargs)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\utils\env.py", line 1152, in run
    return self._run(cmd, **kwargs)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\utils\env.py", line 1453, in _run
    return super(VirtualEnv, self)._run(cmd, **kwargs)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\utils\env.py", line 1195, in _run
    raise EnvCommandError(e, input=input_)
poetry.utils.env.EnvCommandError: Command C:\Users\dabell\Miniconda3\envs\sdg\python.exe -W ignore - errored with the following return code 1, and output:
input was : import sys

if hasattr(sys, "real_prefix"):
    print(sys.real_prefix)
elif hasattr(sys, "base_prefix"):
    print(sys.base_prefix)
else:
    print(sys.prefix)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dabell\Miniconda3\envs\sdg\Scripts\poetry-script.py", line 10, in <module>
    sys.exit(main())
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\poetry\console\__init__.py", line 5, in main
    return Application().run()
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\console_application.py", line 142, in run
    trace.render(io, simple=isinstance(e, CliKitException))
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\ui\components\exception_trace.py", line 232, in render
    return self._render_exception(io, self._exception)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\ui\components\exception_trace.py", line 269, in _render_exception
    self._render_snippet(io, current_frame)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\ui\components\exception_trace.py", line 289, in _render_snippet
    self._render_line(io, code_line)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\ui\components\exception_trace.py", line 402, in _render_line
    io.write_line("{}{}".format(indent * " ", line))
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\cleo\io\io_mixin.py", line 65, in write_line
    super(IOMixin, self).write_line(string, flags)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\api\io\io.py", line 66, in write_line
    self._output.write_line(string, flags=flags)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\api\io\output.py", line 69, in write_line
    self.write(string, flags=flags, new_line=True)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\api\io\output.py", line 61, in write
    self._stream.write(to_str(formatted))
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\site-packages\clikit\io\output_stream\stream_output_stream.py", line 24, in write
    self._stream.write(string)
  File "C:\Users\dabell\Miniconda3\envs\sdg\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2502' in position 28: character maps to <undefined>
(sdg)
HDS+dabell@PF2DCSXD MINGW64 ~/Documents/GitHub/lumada-catalog/synthetic-data-gen (daniel_sims)
$
```

**Comment by neersighted** [comment]
Anaconda is not officially supported by the [virtualenv module on Windows](https://virtualenv.pypa.io/en/latest/installation.html#windows) -- while I have had it work in trivial scenarios, it simply isn't compatible in all the ways expected (e.g. providing the `py.exe` launcher) of a Windows Python distribution. A Windows expert could likely spend time figuring out why and working around it, but for now Poetry depends on standard interfaces to interact with Python on Windows and doesn't do any special-casing needed for Anaconda.

You could open a new issue as a feature request for Anaconda support, and PRs are always welcome if someone wants to start working on a compatibility layer ahead of discussion in an issue.
