### ISSUE TITLE
poetry 1.2.0b2 fails to upgrade local packages

### ISSUE THREAD

**Issue by ruomad** [python-poetry/poetry#5961]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: windows 10 2020H2 19042.1706
- **Poetry version**: 1.2.0b2
- **Python version**: 3.10.5

## Issue
Trying to update or remove a local package fails with the error (see attached log) :
<pre>
  Installing collected packages: savemail
    Attempting uninstall: savemail
      Found existing installation: savemail 1.0.2
  ERROR: Exception:
  Traceback (most recent call last):
    File "C:\Users\USER\AppData\Local\Programs\Python\Poetry\venv\lib\site-packages\virtualenv\seed\wheels\embed\pip-22.0.4-py3-none-any.whl\pip\_internal\cli\base_command.py", line 167, in exc_logging_wrapper
      status = run_func(*args)
    File "C:\Users\USER\AppData\Local\Programs\Python\Poetry\venv\lib\site-packages\virtualenv\seed\wheels\embed\pip-22.0.4-py3-none-any.whl\pip\_internal\cli\req_command.py", line 205, in wrapper
      return func(self, options, args)
    File "C:\Users\USER\AppData\Local\Programs\Python\Poetry\venv\lib\site-packages\virtualenv\seed\wheels\embed\pip-22.0.4-py3-none-any.whl\pip\_internal\commands\install.py", line 405, in run
      installed = install_given_reqs(
    File "C:\Users\USER\AppData\Local\Programs\Python\Poetry\venv\lib\site-packages\virtualenv\seed\wheels\embed\pip-22.0.4-py3-none-any.whl\pip\_internal\req\__init__.py", line 68, in install_given_reqs
      uninstalled_pathset = requirement.uninstall(auto_confirm=True)
    File "C:\Users\USER\AppData\Local\Programs\Python\Poetry\venv\lib\site-packages\virtualenv\seed\wheels\embed\pip-22.0.4-py3-none-any.whl\pip\_internal\req\req_install.py", line 637, in uninstall
      uninstalled_pathset = UninstallPathSet.from_dist(dist)
    File "C:\Users\USER\AppData\Local\Programs\Python\Poetry\venv\lib\site-packages\virtualenv\seed\wheels\embed\pip-22.0.4-py3-none-any.whl\pip\_internal\req\req_uninstall.py", line 522, in from_dist
      for path in uninstallation_paths(dist):
    File "C:\Users\USER\AppData\Local\Programs\Python\Poetry\venv\lib\site-packages\virtualenv\seed\wheels\embed\pip-22.0.4-py3-none-any.whl\pip\_internal\req\req_uninstall.py", line 41, in unique
      for item in fn(*args, **kw):
    File "C:\Users\USER\AppData\Local\Programs\Python\Poetry\venv\lib\site-packages\virtualenv\seed\wheels\embed\pip-22.0.4-py3-none-any.whl\pip\_internal\req\req_uninstall.py", line 81, in uninstallation_paths
      for entry in entries:
    File "C:\Users\USER\AppData\Local\Programs\Python\Poetry\venv\lib\site-packages\virtualenv\seed\wheels\embed\pip-22.0.4-py3-none-any.whl\pip\_internal\metadata\base.py", line 405, in <genexpr>
      return (str(pathlib.Path(row[0])) for row in csv.reader(text.splitlines()))
  IndexError: list index out of range
</pre>

**pyproject.toml**:
<pre>
[tool.poetry]
name = "atest"
version = "0.1.0"
description = ""
authors = ["Bruno Damour <bruno@ruomad.net>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10,<3.11"
savemail = {path = "../savemail"}

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
</pre>

**Comment by dimbleby** [comment]
duplicate #5799
