### ISSUE TITLE
Installation issue: UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)

### ISSUE THREAD

**Issue by michalstefanowski** [python-poetry/poetry#5993]
Reproducible on Ubuntu 20.04 and some docker debian distors:

Run command:
`curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -`

Output:

```
Retrieving Poetry metadata
Traceback (most recent call last):
  File "<stdin>", line 1117, in <module>
  File "<stdin>", line 1113, in main
  File "<stdin>", line 351, in run
  File "<stdin>", line 414, in get_version
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 20: ordinal not in range(128)
```

**Comment by dimbleby** [comment]
duplicate #5989

**Comment by michalstefanowski** [comment]
thanks. Closing issue
