### ISSUE TITLE
poetry shell fails to start due to rapidfuzz missing "MatchingBlock" attribute on ArchLinux with poetry built from git source

### ISSUE THREAD

**Issue by AkechiShiro** [python-poetry/poetry#6078]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Linux hostname 5.15.53-2-lts SMP Sat, 09 Jul 2022 10:30:57 +0000 x86_64 GNU/Linux
- **Poetry version**: 1.2.0b3.r16.gec610a34-1 
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: not relevant

## Issue

So poetry was somewhat working, I started having issue when I ran `peotry shell` about a missing `cleo.terminal` module, I thus installed `python-cleo-git` from the AUR, then after that `poetry shell` told me it's missing `rapidfuzz`, I thus installed `python-rapidfuzz-git` from the AUR again and then hit the following stack trace, I cannot even run `poetry --version` anymore :
```py
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/rapidfuzz/utils.py", line 17, in _fallback_import
    mod = importlib.import_module(module + "_cpp")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rapidfuzz.process_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/rapidfuzz/utils.py", line 17, in _fallback_import
    mod = importlib.import_module(module + "_cpp")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'rapidfuzz.fuzz_cpp'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/poetry", line 5, in <module>
    from poetry.console.application import main
  File "/usr/lib/python3.10/site-packages/poetry/console/application.py", line 12, in <module>
    from cleo.application import Application as BaseApplication
  File "/usr/lib/python3.10/site-packages/cleo/application.py", line 12, in <module>
    from cleo.commands.completions_command import CompletionsCommand
  File "/usr/lib/python3.10/site-packages/cleo/commands/completions_command.py", line 10, in <module>
    from cleo import helpers
  File "/usr/lib/python3.10/site-packages/cleo/helpers.py", line 5, in <module>
    from cleo.io.inputs.argument import Argument
  File "/usr/lib/python3.10/site-packages/cleo/io/inputs/argument.py", line 5, in <module>
    from cleo.exceptions import LogicException
  File "/usr/lib/python3.10/site-packages/cleo/exceptions/__init__.py", line 3, in <module>
    from cleo._utils import find_similar_names
  File "/usr/lib/python3.10/site-packages/cleo/_utils.py", line 8, in <module>
    from rapidfuzz.distance import Levenshtein
  File "/usr/lib/python3.10/site-packages/rapidfuzz/__init__.py", line 8, in <module>
    from rapidfuzz import process, distance, fuzz, string_metric, utils
  File "/usr/lib/python3.10/site-packages/rapidfuzz/process.py", line 7, in <module>
    extract = _fallback_import(_mod, "extract")
  File "/usr/lib/python3.10/site-packages/rapidfuzz/utils.py", line 19, in _fallback_import
    mod = importlib.import_module(module + "_py")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/rapidfuzz/process_py.py", line 5, in <module>
    from rapidfuzz.fuzz import WRatio
  File "/usr/lib/python3.10/site-packages/rapidfuzz/fuzz.py", line 7, in <module>
    ratio = _fallback_import(_mod, "ratio")
  File "/usr/lib/python3.10/site-packages/rapidfuzz/utils.py", line 19, in _fallback_import
    mod = importlib.import_module(module + "_py")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/usr/lib/python3.10/site-packages/rapidfuzz/fuzz_py.py", line 4, in <module>
    from rapidfuzz.distance.Indel_py import (
  File "/usr/lib/python3.10/site-packages/rapidfuzz/distance/__init__.py", line 12, in <module>
    MatchingBlock = _fallback_import(_mod, "MatchingBlock")
  File "/usr/lib/python3.10/site-packages/rapidfuzz/utils.py", line 21, in _fallback_import
    func = getattr(mod, name)
AttributeError: module 'rapidfuzz.distance._initialize_py' has no attribute 'MatchingBlock'

```

**Comment by Secrus** [comment]
This is a problem on your end. Only official installers are those listed on our website. Any package from AUR is a third party to us and is not guaranteed to work. The problem you are experiencing is because of the current Cleo master branch going through changes that were not tested on Poetry yet. I suggest you use the official Poetry installer to solve your issue.

**Comment by AkechiShiro** [comment]
@Secrus the latest method to install, install only 1.14 and does not build the latest version which is required to install Pendulum (as it requires Poetry >=1.2), do you have any way of installing in a recommended way, that would allow Pendulum to be used as well ?

**Comment by Secrus** [comment]
> @Secrus the latest method recommended to install, install only 1.14 and does not build the latest version which is required to install Pendulum (as it requires Poetry >=1.2), do you have any way of installing in a recommended way, that would allow Pendulum to be used as well ?

As in [documentation](https://python-poetry.org/docs/master/#installation) `curl -sSL https://install.python-poetry.org | python3 - --preview`

**Comment by maxbachmann** [comment]
@AkechiShiro @Secrus I am tracking this issue here: https://github.com/maxbachmann/RapidFuzz/issues/247

**Comment by maxbachmann** [comment]
@AkechiShiro I fixed the bug in the python fallback in `v2.4.2`. However your general problem is that the package [`python-rapidfuzz-git`](https://aur.archlinux.org/packages/python-rapidfuzz-git) on AUR is completely outdated and does not support newer versions of the library. You should install [`python-rapidfuzz`](https://aur.archlinux.org/packages/python-rapidfuzz) instead.

**Comment by AkechiShiro** [comment]
@maxbachmann okay thanks, if you have any tips regarding updating the upstream AUR package feel free to tell me I can give it a try

**Comment by pekkarr** [comment]
@AkechiShiro Hi, I'm the maintainer of `python-rapidfuzz` (but not the `-git` version) on AUR. I added a comment about the issues with the `-git` package to the [AUR page](https://aur.archlinux.org/packages/python-rapidfuzz-git#comment-875937) of `python-rapidfuzz-git`.

However, for using `python-cleo-git`, installing the normal `python-rapidfuzz` package is enough. Not having `python-rapidfuzz` as a dependency is currently a bug in `python-cleo-git`.

**Comment by Secrus** [comment]
Gentleusers, I am quite sure that this discussion does not belong here. As I mentioned before, only officially supported ways of installing Poetry can be found on our website. Please discuss 3rd party installers in their appropriate repos/pages.

**Comment by maxbachmann** [comment]
Since this issue still affected at least one user I thought it would make sense to post a solution here as well. However I am happy to move this elsewhere if this is unwanted. I think this issue is now resolved anyways.
