### ISSUE TITLE
Poetry does not add virtual env site-packages to PYTHONPATH so Python cannot resolve packages/modules on Windows

### ISSUE THREAD

**Issue by dlawrences** [python-poetry/poetry#6172]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Windows 21H2 (OS Build 19044.1826)
- **Poetry version**: 1.2.0b3
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/dlawrences/a7c83c33ca88d9358d6a4c23d9ce2e42

## Issue
My environment runs Python via pyenv. More specifically, I have 3.8.10 and 3.9.6 installed via `pyenv` and actively use 3.9.6 in the project I'm facing issues in (also tried with 3.8.10).

```sh
$ poetry debug info

Poetry
Version: 1.2.0b3
Python:  3.9.6

Virtualenv
Python:         3.9.6
Implementation: CPython
Path:           C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9
Executable:     C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\Scripts\python.exe
Valid:          True

System
Platform:   win32
OS:         nt
Python:     3.9.6
Path:       C:\Users\Diaconii\.pyenv\pyenv-win\versions\3.9.6
Executable: C:\Users\Diaconii\.pyenv\pyenv-win\versions\3.9.6\python.exe
```

What happens is `python3`, under poetry venv/shell, doesn't have the path(s) to the virtual env injected into `PYTHONPATH`. More specifically:

```sh
Diaconii@Laurentius-Home-Workstation MINGW64 /e/Work/transform-service (main)
$ source c:/Users/Diaconii/AppData/Local/pypoetry/Cache/virtualenvs/playground-lxpOQ0nG-py3.9/Scripts/activate
(playground-py3.9) 
Diaconii@Laurentius-Home-Workstation MINGW64 /e/Work/transform-service (main)
$ poetry run python3
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path)
['', 'C:\\Users\\Diaconii\\.pyenv\\pyenv-win\\versions\\3.9.6\\python39.zip', 'C:\\Users\\Diaconii\\.pyenv\\pyenv-win\\versions\\3.9.6\\DLLs', 'C:\\Users\\Diaconii\\.pyenv\\pyenv-win\\versions\\3.9.6\\lib', 'C:\\Users\\Diaconii\\.pyenv\\pyenv-win\\versions\\3.9.6', 'C:\\Users\\Diaconii\\.pyenv\\pyenv-win\\versions\\3.9.6\\lib\\site-packages']
```

Whereas `python` does:

```sh
Diaconii@Laurentius-Home-Workstation MINGW64 /e/Work/transform-service (main)
$ poetry run python
Python 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> print(sys.path) 
['', 'C:\\Users\\Diaconii\\.pyenv\\pyenv-win\\versions\\3.9.6\\python39.zip', 'C:\\Users\\Diaconii\\.pyenv\\pyenv-win\\versions\\3.9.6\\DLLs', 'C:\\Users\\Diaconii\\.pyenv\\pyenv-win\\versions\\3.9.6\\lib', 'C:\\Users\\Diaconii\\.pyenv\\pyenv-win\\versions\\3.9.6', 'C:\\Users\\Diaconii\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\playground-lxpOQ0nG-py3.9', 'C:\\Users\\Diaconii\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\playground-lxpOQ0nG-py3.9\\lib\\site-packages', 'E:\\Work\\transform-service']
```

This is frustrating since a script `validate.py` like the following should run just fine in this virtual environment:

```python
#!/usr/bin/env python
import snowflake.connector

# Gets the version
ctx = snowflake.connector.connect(
    user='<some beautiful username>',
    authenticator='externalbrowser',
    account='<some beautiful sfc account>'
    )
cs = ctx.cursor()
try:
    cs.execute("SELECT current_version()")
    one_row = cs.fetchone()
    print(one_row[0])
finally:
    cs.close()
ctx.close()
```

However, it doesn't and the following is apparent since the `PYTHONPATH` doesn't contain the required paths for Python to be able to resolve the module:

```sh
Diaconii@Laurentius-Home-Workstation MINGW64 /e/Work/transform-service (main)
$ poetry run python3 validate.py 
Traceback (most recent call last):
  File "E:\Work\transform-service\validate.py", line 2, in <module>
    import snowflake.connector
ModuleNotFoundError: No module named 'snowflake'
(playground-py3.9)
```

What's frustrating is I cannot run the same via `python` since it leads into another issue (the module above is resolved though):

```sh
Diaconii@Laurentius-Home-Workstation MINGW64 /e/Work/transform-service (main)
$ poetry run python validate.py 
Traceback (most recent call last):
  File "E:\Work\transform-service\validate.py", line 5, in <module>
    ctx = snowflake.connector.connect(
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\__init__.py", line 51, in Connect
    return SnowflakeConnection(**kwargs)
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\connection.py", line 292, in __init__
    self.connect(**kwargs)
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\connection.py", line 542, in connect
    self.__open_connection()
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\connection.py", line 781, in __open_connection
    self._authenticate(auth_instance)
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\connection.py", line 1044, in _authenticate   
    self.__authenticate(self.__preprocess_auth_instance(auth_instance))
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\connection.py", line 1064, in __authenticate  
    auth.authenticate(
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\auth.py", line 257, in authenticate
    ret = self._rest._post_request(
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\network.py", line 704, in _post_request
    ret = self.fetch(
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\network.py", line 794, in fetch
    ret = self._request_exec_wrapper(
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\network.py", line 917, in _request_exec_wrapper
    raise e
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\network.py", line 837, in _request_exec_wrapper
    return_object = self._request_exec(
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\network.py", line 1116, in _request_exec
    raise err
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\network.py", line 1018, in _request_exec
    raw_ret = session.request(
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\vendored\requests\sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\vendored\requests\sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\vendored\requests\adapters.py", line 489, in send
    resp = conn.urlopen(
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\vendored\urllib3\connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\vendored\urllib3\connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\vendored\urllib3\connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\vendored\urllib3\connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\ssl_wrap_socket.py", line 78, in ssl_wrap_socket_with_ocsp
    from .ocsp_asn1crypto import SnowflakeOCSPAsn1Crypto as SFOCSP
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\ocsp_asn1crypto.py", line 47, in <module>
    from snowflake.connector.ocsp_snowflake import SnowflakeOCSP
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\ocsp_snowflake.py", line 71, in <module>
    from .cache import SFDictCache
  File "C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\snowflake\connector\cache.py", line 12, in <module>
    from typing_extensions import NamedTuple, Self
ImportError: cannot import name 'NamedTuple' from 'typing_extensions' (C:\Users\Diaconii\AppData\Local\pypoetry\Cache\virtualenvs\playground-lxpOQ0nG-py3.9\lib\site-packages\typing_extensions.py)
```

The cherry on top is I eventually need to run commands via `poetry run <some script defined under tool.poetry.scripts>`, and I can already tell this is using `python3` and not `python`, thus it doesn't resolve the modules/packages.

I have tried **all of the following options**, to **no** avail:
- create the virtual environment in the project root folder by leveraging the config `virtualenvs.in-project`
- with the virtual environment in the project root folder/at the default path:
  - execute `poetry shell` explicitly before `poetry install`

Experimenting further it, I am getting the sense that poetry on Windows is very sensible to the project actually following the package structure as set forth by `poetry new`. To be specific, the project I'm getting the errors in has roughly the following structure:

```sh
Diaconii@Laurentius-Home-Workstation MINGW64 /e/Work/transform-service (main)
$ tree -L 1
.
├── AzureFunctionHttpTrigger
│   ├── __init__.py
│   └── function.json
├── AzureFunctionQueueTransform
│   ├── __init__.py
│   └── function.json
├── Dockerfile
├── README.md
├── artifacts
├── config.json
├── dbt
│   ├── <multiple folders>
├── dbtvmx
│   ├── LICENSE
│   ├── README.md
│   ├── dist
│   ├── poetry.lock
│   ├── pyproject.toml
│   ├── setup.py
│   └── src
├── docs
│   └── overview.md
├── host.json
├── local_playground.py
├── models
│   ├── __init__.py
│   ├── command_executor.py
│   ├── configuration_validator.py
│   ├── execution_error.py
│   ├── execution_error_list.py
│   ├── parameter_mailer.py
│   └── snowflake_client.py
├── packages.yml
├── playground
│   ├── __init__.py
│   └── runner.py
├── poetry.lock
├── profiles.yml
├── pyproject.toml
├── tests
│   ├── __init__.py
│   ├── support
│   ├── test_command_executor.py
│   ├── test_configuration_validator.py
│   └── test_transform_service.py
├── transform_service.py
└── verumex_client.py
```

I am running out of ideas. I am running this setup flawlessly on my MacOS M1 Pro machine and I need to get it working over Windows as well, preferably without involving WSL2 or anything similar.

Any thoughts?

**Comment by dlawrences** [comment]
Any thoughts on this, guys?

**Comment by clintonroy** [comment]
Please try updating to a released version.

**Comment by neersighted** [comment]
Poetry is not responsible for adding the site-packages path; it merely sets `VIRTUAL_ENV` during `run`. Please try to reproduce on 1.2, and in a container (with steps) if at all possible. I seem to recall trying to reproduce this and failing months ago, and I am unable to reproduce today on Windows 11.

**Comment by dlawrences** [comment]
Thanks for the feedback @clintonroy and @neersighted. I retested this using poetry version 1.2.2 and it seems to not be the case anymore. I think it was something specifically related to the `snowflake-connector-python` package that we were using and the way that it was being imported. There have been a handful of issues historically speaking with respect to it, enlisting a few below:
- https://community.snowflake.com/s/feed/0D53r0000ASF9ncCQD
- https://stackoverflow.com/questions/66201891/no-module-named-snowflake-found
- https://stephenallwright.com/no-module-named-snowflake/

Bumping the package version while also moving to a new poetry version seemed to have done the trick. Cheers, closing.
