### ISSUE TITLE
Resolver picks too old version of `llvmlite` dependency, causing `poetry install` to fail

### ISSUE THREAD

**Issue by nathanpainchaud** [python-poetry/poetry#6265]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: EndeavourOS (Arch-based rolling release up-to-date)
- **Poetry version**: 1.1.15
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [My pyproject.toml](https://gist.github.com/nathanpainchaud/1d07ac4058c47b867253847bb107cd7b)

## Issue

I've seen a few issues reported with the same final result (#5752, #5920, #6079) where `llvmlite` fails to install because a pre-built wheel can't be found and `poetry` tries to build it from source. And I've seen that these issues were closed (appropriately) as not `poetry`'s responsability in the end.

As in #5920, `poetry install` fails while `pip install .` as no problem resolving the `pyproject.toml`. But the underlying issue comes from how `poetry` resolves the dependencies and which versions of the packages it tries to install. `poetry` choses to install `numba==0.51.2`, which limits `llvmlite` to `>=0.34.0.dev0,<0.35`, which do not have pre-built wheels for Python 3.10 (which I'm using).

However, the choice of `numba==0.51.2` is the real problem. It's the minimum version across the other packages, but no dependency as an upper bound on the `numba` version. So that's why `pip` is able to chose `numba==0.56.0`, which depends on `llvmlite<0.40,>=0.39.0dev0`, for which there are pre-built wheels for Python 3.10.

I don't know why `poetry` resolves the dependency differently than `pip`, so I think the bug lies somewhere there and I would be grateful for any help in identifying the root cause of the issue!

As additional information, here are links to:
- [`poetry.lock` file generated by running `poetry install` on the provided `pyprojec.toml`](https://gist.github.com/nathanpainchaud/5c33a323d7246cded7e8a5136b91f682)
- [output of running `pip install .` on the project](https://gist.github.com/nathanpainchaud/341428ed01d5ba71fc8cd4ffd963f0ef)

EDIT: I forgot to include it because the error message regarding `llvmlite` itself is the same as in the linked issues, but here it is nonetheless:
```bash shell
> poetry install -vvv
Using virtualenv: /home/nathan/.cache/pypoetry/virtualenvs/my_package-EOfcrJo4-py3.10
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 146 installs, 0 updates, 0 removals, 1 skipped

  • Removing colorama (0.4.5): Pending...
  • Removing colorama (0.4.5): Skipped for the following reason: Not currently installed
  • Installing locket (1.0.0): Pending...
  • Installing locket (1.0.0): Installing...
  • Installing locket (1.0.0)
  • Installing pyparsing (3.0.9): Pending...
  • Installing pyparsing (3.0.9): Installing...
  • Installing pyparsing (3.0.9)
  • Installing toolz (0.12.0): Pending...
  • Installing toolz (0.12.0): Installing...
  • Installing toolz (0.12.0)
  • Installing certifi (2022.6.15): Pending...
  • Installing certifi (2022.6.15): Installing...
  • Installing certifi (2022.6.15)
  • Installing charset-normalizer (2.1.1): Pending...
  • Installing charset-normalizer (2.1.1): Installing...
  • Installing charset-normalizer (2.1.1)
  • Installing cloudpickle (2.1.0): Pending...
  • Installing cloudpickle (2.1.0): Installing...
  • Installing cloudpickle (2.1.0)
  • Installing fsspec (2022.7.1): Pending...
  • Installing fsspec (2022.7.1): Installing...
  • Installing fsspec (2022.7.1)
  • Installing heapdict (1.0.1): Pending...
  • Installing heapdict (1.0.1): Installing...
  • Installing heapdict (1.0.1)
  • Installing idna (3.3): Pending...
  • Installing idna (3.3): Installing...
  • Installing idna (3.3)
  • Installing markupsafe (2.1.1): Pending...
  • Installing markupsafe (2.1.1): Installing...
  • Installing markupsafe (2.1.1)
  • Installing packaging (21.3): Pending...
  • Installing packaging (21.3): Installing...
  • Installing packaging (21.3)
  • Installing partd (1.3.0): Pending...
  • Installing partd (1.3.0): Installing...
  • Installing partd (1.3.0)
  • Installing pyasn1 (0.4.8): Pending...
  • Installing pyasn1 (0.4.8): Installing...
  • Installing pyasn1 (0.4.8)
  • Installing pyyaml (6.0): Pending...
  • Installing pyyaml (6.0): Installing...
  • Installing pyyaml (6.0)
  • Installing six (1.16.0): Pending...
  • Installing six (1.16.0): Installing...
  • Installing six (1.16.0)
  • Installing urllib3 (1.26.12): Pending...
  • Installing urllib3 (1.26.12): Installing...
  • Installing urllib3 (1.26.12)
  • Installing cachetools (5.2.0): Pending...
  • Installing cachetools (5.2.0): Installing...
  • Installing cachetools (5.2.0)
  • Installing click (8.1.3): Pending...
  • Installing click (8.1.3): Installing...
  • Installing click (8.1.3)
  • Installing dask (2022.8.1): Pending...
  • Installing dask (2022.8.1): Installing...
  • Installing dask (2022.8.1)
  • Installing frozenlist (1.3.1): Pending...
  • Installing frozenlist (1.3.1): Installing...
  • Installing frozenlist (1.3.1)
  • Installing jinja2 (3.1.2): Pending...
  • Installing jinja2 (3.1.2): Installing...
  • Installing jinja2 (3.1.2)
  • Installing msgpack (1.0.4): Pending...
  • Installing msgpack (1.0.4): Installing...
  • Installing msgpack (1.0.4)
  • Installing multidict (6.0.2): Pending...
  • Installing multidict (6.0.2): Installing...
  • Installing multidict (6.0.2)
  • Installing numpy (1.23.2): Pending...
  • Installing numpy (1.23.2): Installing...
  • Installing numpy (1.23.2)
  • Installing oauthlib (3.2.0): Pending...
  • Installing oauthlib (3.2.0): Installing...
  • Installing oauthlib (3.2.0)
  • Installing param (1.12.2): Pending...
  • Installing param (1.12.2): Installing...
  • Installing param (1.12.2)
  • Installing pillow (9.2.0): Pending...
  • Installing pillow (9.2.0): Installing...
  • Installing pillow (9.2.0)
  • Installing psutil (5.9.1): Pending...
  • Installing psutil (5.9.1): Installing...
  • Installing psutil (5.9.1)
  • Installing pyasn1-modules (0.2.8): Pending...
  • Installing pyasn1-modules (0.2.8): Installing...
  • Installing pyasn1-modules (0.2.8)
  • Installing python-dateutil (2.8.2): Pending...
  • Installing python-dateutil (2.8.2): Installing...
  • Installing python-dateutil (2.8.2)
  • Installing pytz (2022.2.1): Pending...
  • Installing pytz (2022.2.1): Installing...
  • Installing pytz (2022.2.1)
  • Installing requests (2.28.1): Pending...
  • Installing requests (2.28.1): Installing...
  • Installing requests (2.28.1)
  • Installing rsa (4.9): Pending...
  • Installing rsa (4.9): Installing...
  • Installing rsa (4.9)
  • Installing sortedcontainers (2.4.0): Pending...
  • Installing sortedcontainers (2.4.0): Installing...
  • Installing sortedcontainers (2.4.0)
  • Installing tblib (1.7.0): Pending...
  • Installing tblib (1.7.0): Installing...
  • Installing tblib (1.7.0)
  • Installing tomli (2.0.1): Pending...
  • Installing tomli (2.0.1): Installing...
  • Installing tomli (2.0.1)
  • Installing tornado (6.1): Pending...
  • Installing tornado (6.1): Installing...
  • Installing tornado (6.1)
  • Installing typing-extensions (4.3.0): Pending...
  • Installing typing-extensions (4.3.0): Installing...
  • Installing typing-extensions (4.3.0)
  • Installing webencodings (0.5.1): Pending...
  • Installing webencodings (0.5.1): Installing...
  • Installing webencodings (0.5.1)
  • Installing zict (2.2.0): Pending...
  • Installing zict (2.2.0): Installing...
  • Installing zict (2.2.0)
  • Installing aiosignal (1.2.0): Pending...
  • Installing aiosignal (1.2.0): Installing...
  • Installing aiosignal (1.2.0)
  • Installing async-timeout (4.0.2): Pending...
  • Installing async-timeout (4.0.2): Installing...
  • Installing async-timeout (4.0.2)
  • Installing attrs (22.1.0): Pending...
  • Installing attrs (22.1.0): Installing...
  • Installing attrs (22.1.0)
  • Installing bleach (5.0.1): Pending...
  • Installing bleach (5.0.1): Installing...
  • Installing bleach (5.0.1)
  • Installing bokeh (2.4.3): Pending...
  • Installing bokeh (2.4.3): Installing...
  • Installing bokeh (2.4.3)
  • Installing cycler (0.11.0): Pending...
  • Installing cycler (0.11.0): Installing...
  • Installing cycler (0.11.0)
  • Installing distributed (2022.8.1): Pending...
  • Installing distributed (2022.8.1): Installing...
  • Installing distributed (2022.8.1)
  • Installing fonttools (4.37.1): Pending...
  • Installing fonttools (4.37.1): Installing...
  • Installing fonttools (4.37.1)
  • Installing google-auth (2.11.0): Pending...
  • Installing google-auth (2.11.0): Installing...
  • Installing google-auth (2.11.0)
  • Installing joblib (1.1.0): Pending...
  • Installing joblib (1.1.0): Installing...
  • Installing joblib (1.1.0)
  • Installing kiwisolver (1.4.4): Pending...
  • Installing kiwisolver (1.4.4): Installing...
  • Installing kiwisolver (1.4.4)
  • Installing llvmlite (0.34.0): Pending...
  • Installing llvmlite (0.34.0): Installing...
  • Installing llvmlite (0.34.0): Failed

  EnvCommandError

  Command ['/home/nathan/.cache/pypoetry/virtualenvs/my_package-EOfcrJo4-py3.10/bin/pip', 'install', '--no-deps', 'file:///home/nathan/.cache/pypoetry/artifacts/9e/1c/c8/439ee74bf8837fa4dae6747de4184a713dd70697520cd1d1500b1141f0/llvmlite-0.34.0.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/nathan/.cache/pypoetry/artifacts/9e/1c/c8/439ee74bf8837fa4dae6747de4184a713dd70697520cd1d1500b1141f0/llvmlite-0.34.0.tar.gz
    Preparing metadata (setup.py): started
    Preparing metadata (setup.py): finished with status 'done'
  Building wheels for collected packages: llvmlite
    Building wheel for llvmlite (setup.py): started
    Building wheel for llvmlite (setup.py): finished with status 'error'
    error: subprocess-exited-with-error
    
    × python setup.py bdist_wheel did not run successfully.
    │ exit code: 1
    ╰─> [26 lines of output]
        running bdist_wheel
        /home/nathan/.cache/pypoetry/virtualenvs/my_package-EOfcrJo4-py3.10/bin/python /tmp/pip-req-build-ucb4pzxh/ffi/build.py
        LLVM version... Traceback (most recent call last):
          File "/tmp/pip-req-build-ucb4pzxh/ffi/build.py", line 105, in main_posix
            out = subprocess.check_output([llvm_config, '--version'])
          File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
          File "/usr/lib/python3.10/subprocess.py", line 501, in run
            with Popen(*popenargs, **kwargs) as process:
          File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
            self._execute_child(args, executable, preexec_fn, close_fds,
          File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
            raise child_exception_type(errno_num, err_msg, err_filename)
        FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/tmp/pip-req-build-ucb4pzxh/ffi/build.py", line 191, in <module>
            main()
          File "/tmp/pip-req-build-ucb4pzxh/ffi/build.py", line 181, in main
            main_posix('linux', '.so')
          File "/tmp/pip-req-build-ucb4pzxh/ffi/build.py", line 107, in main_posix
            raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
        RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
        error: command '/home/nathan/.cache/pypoetry/virtualenvs/my_package-EOfcrJo4-py3.10/bin/python' failed with exit code 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for llvmlite
    Running setup.py clean for llvmlite
  Failed to build llvmlite
  Installing collected packages: llvmlite
    Running setup.py install for llvmlite: started
    Running setup.py install for llvmlite: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Running setup.py install for llvmlite did not run successfully.
    │ exit code: 1
    ╰─> [31 lines of output]
        running install
        /home/nathan/.cache/pypoetry/virtualenvs/my_package-EOfcrJo4-py3.10/lib/python3.10/site-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
          warnings.warn(
        running build
        got version from file /tmp/pip-req-build-ucb4pzxh/llvmlite/_version.py {'version': '0.34.0', 'full': 'c5889c9e98c6b19d5d85ebdd982d64a03931f8e2'}
        running build_ext
        /home/nathan/.cache/pypoetry/virtualenvs/my_package-EOfcrJo4-py3.10/bin/python /tmp/pip-req-build-ucb4pzxh/ffi/build.py
        LLVM version... Traceback (most recent call last):
          File "/tmp/pip-req-build-ucb4pzxh/ffi/build.py", line 105, in main_posix
            out = subprocess.check_output([llvm_config, '--version'])
          File "/usr/lib/python3.10/subprocess.py", line 420, in check_output
            return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
          File "/usr/lib/python3.10/subprocess.py", line 501, in run
            with Popen(*popenargs, **kwargs) as process:
          File "/usr/lib/python3.10/subprocess.py", line 969, in __init__
            self._execute_child(args, executable, preexec_fn, close_fds,
          File "/usr/lib/python3.10/subprocess.py", line 1845, in _execute_child
            raise child_exception_type(errno_num, err_msg, err_filename)
        FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'
        
        During handling of the above exception, another exception occurred:
        
        Traceback (most recent call last):
          File "/tmp/pip-req-build-ucb4pzxh/ffi/build.py", line 191, in <module>
            main()
          File "/tmp/pip-req-build-ucb4pzxh/ffi/build.py", line 181, in main
            main_posix('linux', '.so')
          File "/tmp/pip-req-build-ucb4pzxh/ffi/build.py", line 107, in main_posix
            raise RuntimeError("%s failed executing, please point LLVM_CONFIG "
        RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
        error: command '/home/nathan/.cache/pypoetry/virtualenvs/my_package-EOfcrJo4-py3.10/bin/python' failed with exit code 1
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: legacy-install-failure
  
  × Encountered error while trying to install package.
  ╰─> llvmlite
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for output from the failure.
  

  at ~/opt/poetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1195 in _run
      1191│                 output = subprocess.check_output(
      1192│                     cmd, stderr=subprocess.STDOUT, **kwargs
      1193│                 )
      1194│         except CalledProcessError as e:
    → 1195│             raise EnvCommandError(e, input=input_)
      1196│ 
      1197│         return decode(output)
      1198│ 
      1199│     def execute(self, bin, *args, **kwargs):

  • Installing markdown (3.4.1): Pending...
  • Installing markdown (3.4.1): Installing...
  • Installing markdown (3.4.1)
  • Installing multipledispatch (0.6.0): Pending...
  • Installing multipledispatch (0.6.0): Installing...
  • Installing multipledispatch (0.6.0)
  • Installing pandas (1.4.3): Pending...
  • Installing pandas (1.4.3): Installing...
  • Installing pandas (1.4.3)
  • Installing pyct (0.4.8): Pending...
  • Installing pyct (0.4.8): Installing...
  • Installing pyct (0.4.8)
  • Installing pyviz-comms (2.2.1): Pending...
  • Installing pyviz-comms (2.2.1): Installing...
  • Installing pyviz-comms (2.2.1)
  • Installing requests-oauthlib (1.3.1): Pending...
  • Installing requests-oauthlib (1.3.1): Installing...
  • Installing requests-oauthlib (1.3.1)
  • Installing scipy (1.9.1): Pending...
  • Installing scipy (1.9.1): Installing...
  • Installing scipy (1.9.1)
  • Installing setuptools-scm (6.4.2): Pending...
  • Installing setuptools-scm (6.4.2): Installing...
  • Installing setuptools-scm (6.4.2)
  • Installing threadpoolctl (3.1.0): Pending...
  • Installing threadpoolctl (3.1.0): Installing...
  • Installing threadpoolctl (3.1.0)
  • Installing tqdm (4.64.0): Pending...
  • Installing tqdm (4.64.0): Installing...
  • Installing tqdm (4.64.0)
  • Installing yarl (1.8.1): Pending...
  • Installing yarl (1.8.1): Installing...
  • Installing yarl (1.8.1)
```

**Comment by dimbleby** [comment]
the way to debug if you believe that poetry should be able to choose a higher version of llvmlite in your project is to add a requirement explicitly demanding that higher version.  Then either:

- poetry will tell you what the incompatibility is that prevented it from making that choice in the first place
- poetry will go "yes, fine, let's use the higher version"
  - but in that case I expect something else will be forced to a lower version, it's unlikely that poetry is just picking the lower version of llvmlite for no reason at all

**Comment by nathanpainchaud** [comment]
Well, I just manually edited the `pyproject.toml` to add `numba = "~0.56.0"` in `[tool.poetry.dependencies]`, and `poetry` managed to resolve the dependencies and install without errors this time...

By doing a diff between the `poetry.lock` files generated in both cases, the only packages whose version changed was `numpy`, which was downgraded from 1.23.2 to 1.22.4.

I must admit that I'm not knowledgeable enough to understand where `pip` and `poetry` do things differently to explain the different resolution outcome. At least in my case, it seems that `pip`'s is the most logical one.

Given this, is there a way to ensure consistent behavior between `pip` and `poetry`? This is frustrating because I want to be able to `pip install` my package in more "deployment" oriented settings (so that people using my project don't have to install `poetry` to use it), but still be able to use `poetry install` locally to manage the dev dependencies + editable installation of the project.

**Comment by finswimmer** [comment]
> Given this, is there a way to ensure consistent behavior between pip and poetry?

This is impossible, because Poetry creates a universal lock file, which means it's looking for a solution that is valid for the whole range of python versions that the project is aimed to be compatible to. `pip` only takes the current python version and platform into account.

**Comment by nathanpainchaud** [comment]
Okay, understood that `poetry` and `pip` won't resolve the dependencies the same way. But what then is the recommended approach in situations like mine where the resolved versions chosen by `poetry` fail during the installation, but there are other resolution outcomes that would install effortlessly?

Note that the range of python versions I'm specifying is `~3.10.4`, so it's not like my requirements for the python versions are too broad and the resolution of the dependencies itself is too complex.

**Comment by nathanpainchaud** [comment]
Couldn't there be for example a flag that would prioritize pre-built binaries over, so that in my case it would chose not to try and compile `llvmlite` itself and aim for the resolution for which `llvmlite` offers a pre-built binary?

**Comment by dimbleby** [comment]
the recommendation is to do exactly what you've done: if you care which version of numba is installed, say so in your pyproject.toml

NB
```
$ curl -s https://pypi.org/pypi/numba/json | jq '.info.requires_dist'
[
  "llvmlite (<0.40,>=0.39.0dev0)",
  "numpy (<1.23,>=1.18)",
  "setuptools",
  "importlib-metadata ; python_version < \"3.9\""
]
```
explains why recent numba is not compatible with recent numpy: numba explicitly demands older numpy.

**Comment by nathanpainchaud** [comment]
Thanks for confirming that it's the recommended way, but IMO it's really inelegant. I do NOT care about the `numba` version. But I care to have my recursive dependencies installed as painlessly as possible. And I'm not sure why the resolution mechanism would prioritize a newer version of `numpy` over a pre-built `numba` (since requiring to compile the package locally is a whole other game).

**Comment by dimbleby** [comment]
poetry is not interested in what is pre-built or not during resolution, and I think that is unlikely to change.  

Resolution is already complicated enough, the idea that it should find a valid solution but then say "I should keep looking for a _different_ valid solution in the hope of finding more binary distributions; and also I mustn't annoy all users by being slower" is... well if anyone wants to prove me wrong with an MR, I wish them all the luck in the world.

This case is more or less a coin-flip: poetry might have happened to pick recent numba and less recent numpy without hints, in fact it happened to pick recent numpy and less recent numba.

Don't hold your breath on anything changing here, IMO this can safely be closed today.

**Comment by nathanpainchaud** [comment]
I must admit that's the answer I was afraid to hear :stuck_out_tongue: I'm not a fan of the workaround, but thank you for confirming that's the way to go. Along with the clear position on `poetry`'s dependency resolution, at least it cleary explains the issue now. So I would agree that the discussion regarding this issue is done.
