### ISSUE TITLE
Regression with Poetry version 1.2 when installing nipy

### ISSUE THREAD

**Issue by ghisvail** [python-poetry/poetry#6279]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS 12.5.1
- **Poetry version**: 1.2

## Issue

[Clinica](https://github.com/aramis-lab/clinica/blob/dev/pyproject.toml) uses Poetry to manage the project. With the recent update to version 1.2, CI started to fail to install new environments on Python 3.10 specifically.

I can reproduce the issue with the following setup:

pyproject.toml
```toml
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["John Does <me@john.doe>"]

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
scipy = "^1.7"
nipy = "^0.5"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

commands:
```shell
conda create -n test python=3.10
conda activate test
pip install poetry
poetry install -vvv
```

output:
```txt
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 1 install, 0 updates, 0 removals, 8 skipped

  • Installing mpmath (1.2.1): Pending...
  • Installing mpmath (1.2.1): Skipped for the following reason: Already installed
  • Installing nibabel (4.0.1): Pending...
  • Installing nibabel (4.0.1): Skipped for the following reason: Already installed
  • Installing nipy (0.5.0): Pending...
  • Installing packaging (21.3): Pending...
  • Installing packaging (21.3): Skipped for the following reason: Already installed
  • Installing scipy (1.9.1): Pending...
  • Installing scipy (1.9.1): Skipped for the following reason: Already installed
  • Installing sympy (1.11.1): Pending...
  • Installing sympy (1.11.1): Skipped for the following reason: Already installed
  • Installing pyparsing (3.0.9): Pending...
  • Installing pyparsing (3.0.9): Skipped for the following reason: Already installed
  • Installing setuptools (65.3.0): Pending...
  • Installing setuptools (65.3.0): Skipped for the following reason: Already installed
  • Installing numpy (1.23.2): Pending...
  • Installing numpy (1.23.2): Skipped for the following reason: Already installed
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
Skipping wheel nipy-0.5.0-cp27-cp27m-macosx_10_13_x86_64.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp27-cp27m-manylinux1_i686.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp27-cp27m-manylinux1_x86_64.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp27-cp27mu-manylinux1_i686.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp27-cp27mu-manylinux1_x86_64.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp27-none-win32.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp27-none-win_amd64.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp36-cp36m-macosx_10_13_x86_64.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp36-cp36m-manylinux1_i686.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp36-cp36m-manylinux1_x86_64.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp36-none-win32.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp36-none-win_amd64.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp37-cp37m-macosx_10_13_x86_64.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp37-cp37m-manylinux1_i686.whl as this is not supported by the current environment
Skipping wheel nipy-0.5.0-cp37-cp37m-manylinux1_x86_64.whl as this is not supported by the current environment
  • Installing nipy (0.5.0): Installing...
  • Installing nipy (0.5.0): Failed

  Stack trace:

  2  .venv/lib/python3.10/site-packages/poetry/utils/env.py:1469 in _run
      1467│                 )
      1468│             else:
    → 1469│                 output = subprocess.check_output(
      1470│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1471│                 )

  1  .venv/lib/python3.10/subprocess.py:420 in check_output
       418│         kwargs['input'] = empty
       419│
    →  420│     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
       421│                **kwargs).stdout
       422│

  CalledProcessError

  Command '['/Users/ghislain.vaillant/Projects/test/.venv/bin/python', '/Users/ghislain.vaillant/Projects/test/.venv/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/ghislain.vaillant/Projects/test/.venv', '--no-deps', '/Users/ghislain.vaillant/Library/Caches/pypoetry/artifacts/ac/64/5a/e291ffb88c0fca80e840a9f9dcfc12b391e11c41a5f8fe81bbf4fb9d16/nipy-0.5.0.tar.gz']' returned non-zero exit status 1.

  at .venv/lib/python3.10/subprocess.py:524 in run
       520│             # We don't call process.wait() as .__exit__ does that for us.
       521│             raise
       522│         retcode = process.poll()
       523│         if check and retcode:
    →  524│             raise CalledProcessError(retcode, process.args,
       525│                                      output=stdout, stderr=stderr)
       526│     return CompletedProcess(process.args, retcode, stdout, stderr)
       527│
       528│

The following error occurred when trying to handle this error:


  Stack trace:

  3  .venv/lib/python3.10/site-packages/poetry/utils/pip.py:49 in pip_install
       47│
       48│     try:
    →  49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
       51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e

  2  .venv/lib/python3.10/site-packages/poetry/utils/env.py:1432 in run_pip
      1430│         pip = self.get_pip_command(embedded=True)
      1431│         cmd = pip + list(args)
    → 1432│         return self._run(cmd, **kwargs)
      1433│
      1434│     def run_python_script(self, content: str, **kwargs: Any) -> int | str:

  1  .venv/lib/python3.10/site-packages/poetry/utils/env.py:1722 in _run
      1720│     def _run(self, cmd: list[str], **kwargs: Any) -> int | str:
      1721│         kwargs["env"] = self.get_temp_environ(environ=kwargs.get("env"))
    → 1722│         return super()._run(cmd, **kwargs)
      1723│
      1724│     def get_temp_environ(

  EnvCommandError

  Command ['/Users/ghislain.vaillant/Projects/test/.venv/bin/python', '/Users/ghislain.vaillant/Projects/test/.venv/lib/python3.10/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/Users/ghislain.vaillant/Projects/test/.venv', '--no-deps', '/Users/ghislain.vaillant/Library/Caches/pypoetry/artifacts/ac/64/5a/e291ffb88c0fca80e840a9f9dcfc12b391e11c41a5f8fe81bbf4fb9d16/nipy-0.5.0.tar.gz'] errored with the following return code 1, and output:
  Processing /Users/ghislain.vaillant/Library/Caches/pypoetry/artifacts/ac/64/5a/e291ffb88c0fca80e840a9f9dcfc12b391e11c41a5f8fe81bbf4fb9d16/nipy-0.5.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [19 lines of output]
        Traceback (most recent call last):
          File "/var/folders/m3/r24ql8bj2h9_g1d970f9mr40000w73/T/tmp43e5kzhq_in_process.py", line 363, in <module>
            main()
          File "/var/folders/m3/r24ql8bj2h9_g1d970f9mr40000w73/T/tmp43e5kzhq_in_process.py", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/var/folders/m3/r24ql8bj2h9_g1d970f9mr40000w73/T/tmp43e5kzhq_in_process.py", line 130, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/private/var/folders/m3/r24ql8bj2h9_g1d970f9mr40000w73/T/pip-build-env-mauvzdbn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/private/var/folders/m3/r24ql8bj2h9_g1d970f9mr40000w73/T/pip-build-env-mauvzdbn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
            self.run_setup()
          File "/private/var/folders/m3/r24ql8bj2h9_g1d970f9mr40000w73/T/pip-build-env-mauvzdbn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 482, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/private/var/folders/m3/r24ql8bj2h9_g1d970f9mr40000w73/T/pip-build-env-mauvzdbn/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 16, in <module>
          File "/private/var/folders/m3/r24ql8bj2h9_g1d970f9mr40000w73/T/pip-req-build-a87imunu/setup_helpers.py", line 35, in <module>
            from numpy.distutils.misc_util import appendpath
        ModuleNotFoundError: No module named 'numpy'
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.


  at .venv/lib/python3.10/site-packages/poetry/utils/env.py:1473 in _run
      1469│                 output = subprocess.check_output(
      1470│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1471│                 )
      1472│         except CalledProcessError as e:
    → 1473│             raise EnvCommandError(e, input=input_)
      1474│
      1475│         return decode(output)
      1476│
      1477│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  Stack trace:

  5  .venv/lib/python3.10/site-packages/poetry/installation/executor.py:250 in _execute_operation
      248│
      249│             try:
    → 250│                 result = self._do_execute_operation(operation)
      251│             except EnvCommandError as e:
      252│                 if e.e.returncode == -2:

  4  .venv/lib/python3.10/site-packages/poetry/installation/executor.py:323 in _do_execute_operation
      321│             return 0
      322│
    → 323│         result: int = getattr(self, f"_execute_{method}")(operation)
      324│
      325│         if result != 0:

  3  .venv/lib/python3.10/site-packages/poetry/installation/executor.py:443 in _execute_install
      441│
      442│     def _execute_install(self, operation: Install | Update) -> int:
    → 443│         status_code = self._install(operation)
      444│
      445│         self._save_url_reference(operation)

  2  .venv/lib/python3.10/site-packages/poetry/installation/executor.py:485 in _install
      483│         )
      484│         self._write(operation, message)
    → 485│         return self.pip_install(archive, upgrade=operation.job_type == "update")
      486│
      487│     def _update(self, operation: Install | Update) -> int:

  1  .venv/lib/python3.10/site-packages/poetry/installation/executor.py:120 in pip_install
      118│     ) -> int:
      119│         try:
    → 120│             pip_install(req, self._env, upgrade=upgrade, editable=editable)
      121│         except EnvCommandError as e:
      122│             output = decode(e.e.output)

  PoetryException

  Failed to install /Users/ghislain.vaillant/Library/Caches/pypoetry/artifacts/ac/64/5a/e291ffb88c0fca80e840a9f9dcfc12b391e11c41a5f8fe81bbf4fb9d16/nipy-0.5.0.tar.gz

  at .venv/lib/python3.10/site-packages/poetry/utils/pip.py:51 in pip_install
       47│
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│

  • Installing packaging (21.3): Pending...
  • Installing packaging (21.3): Skipped for the following reason: Already installed
  • Installing scipy (1.9.1): Pending...
  • Installing scipy (1.9.1): Skipped for the following reason: Already installed
  • Installing sympy (1.11.1): Pending...
  • Installing sympy (1.11.1): Skipped for the following reason: Already installed
  • Installing pyparsing (3.0.9): Pending...
  • Installing pyparsing (3.0.9): Skipped for the following reason: Already installed
  • Installing setuptools (65.3.0): Pending...
  • Installing setuptools (65.3.0): Skipped for the following reason: Already installed
  • Installing numpy (1.23.2): Pending...
  • Installing numpy (1.23.2): Skipped for the following reason: Already installed
```

It works fine on the rest of our test matrix, i.e. Python 3.8 and 3.9.

**Comment by finswimmer** [comment]
Hey @ghisvail,

there is no wheel file for `nipy` on python3.10. That's why it must be build from the `sdist` file. The maintainers of the package missed to define build systemt requirements according to [PEP-518](https://peps.python.org/pep-0518/) and so the build failed.

Please contact the maintainers of the package and ask them to fix it. There's nothing Poetry can do here.

fin swimmer

**Comment by ghisvail** [comment]
Sure, but it worked fine in Poetry 1.1.x. What changed in Poetry v1.2 which introduced this regression?

**Comment by ghisvail** [comment]
> There's nothing Poetry can do here.

Well, it sure worked before though. So there is nothing Poetry used to do, that it's not doing now.

**Comment by ghisvail** [comment]
@finswimmer I am sorry but I can't help but feel this issue has been closed in haste.

**Comment by finswimmer** [comment]
> Sure, but it worked fine in Poetry 1.1.x. What changed in Poetry v1.2 which introduced this regression?

You are right, it works in Poetry 1.1.x. I don't know the exact reason for this, but it's definitely a bug there. Poetry 1.2 about complaining a missing build dependency. Also `pip` is doing this if you try to install  `nipy` in a python3.10 environment.

**Comment by dimbleby** [comment]
poetry started adding `--use-pep517` to its pip install comand, I think that'll be the difference

**Comment by ghisvail** [comment]
> I don't know the exact reason for this, but it's definitely a bug there.

Sadly, this "bug" became a feature for some users. I suspect more report like this will follow.

> poetry started adding `--use-pep517` to its pip install comand, I think that'll be the difference

Thank you for providing further context. Could this behaviour be parameterized somehow? We deal with a lot of scientific packages for which transition to PEP-518 will likely take time, if it ever happens.

Besides, I am not sure pinning Poetry to version 1.1.x forever is the right approach to this instead.
