### ISSUE TITLE
CI/CD automatic release installation is broken pipeline

### ISSUE THREAD

**Issue by vit1251** [python-poetry/poetry#6285]
See on my CI/CD service I meet with next error output:

```
poetry install -vvv
Traceback (most recent call last):
  File "/usr/local/bin/poetry", line 5, in <module>
    from poetry.console import main
  File "/usr/local/lib/python3.7/dist-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/usr/local/lib/python3.7/dist-packages/poetry/console/application.py", line 3, in <module>
    from cleo import Application as BaseApplication
ImportError: cannot import name 'Application' from 'cleo' (/var/lib/jenkins/.local/lib/python3.7/site-packages/cleo/__init__.py)
```

Can explain problem with?

**Comment by HarrisonAlmeida** [comment]
I'm also having the same issue, anyone knows how to fix it?

**Comment by neersighted** [comment]
This is a distro packaging issue judging by the install paths. Your distro is not properly packaging cleo 1.0.0a5 most likely -- please open a ticket there.
