### ISSUE TITLE
Installation of 1.2.0 fail on kubuntu 22.04

### ISSUE THREAD

**Issue by Elufimov** [python-poetry/poetry#6289]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Kubuntu 22.04 
- **Poetry version**: 1.2.0

## Issue
Fresh kubuntu install. I can provide any extra info.
```
elufimov in SMRNBL1084RMN in 
✖130 ~ ❯ curl -sSL https://install.python-poetry.org | python3 -
Execution starts at 17:35:28 on 2022-08-31


Retrieving Poetry metadata

# Welcome to Poetry!

This will download and install the latest version of Poetry,
a dependency and package manager for Python.

It will add the `poetry` command to Poetry's bin directory, located at:

/home/elufimov/.local/bin

You can uninstall at any time by executing this script with the --uninstall option,
and these changes will be reverted.

Installing Poetry (1.2.0): An error occurred. Removing partial environment.
Traceback (most recent call last):
  File "<stdin>", line 913, in <module>
  File "<stdin>", line 892, in main
  File "<stdin>", line 528, in run
  File "<stdin>", line 549, in install
  File "/usr/lib/python3.10/contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "<stdin>", line 621, in make_env
  File "<stdin>", line 607, in make_env
  File "<stdin>", line 339, in make
  File "<stdin>", line 362, in pip
  File "<stdin>", line 359, in python
  File "<stdin>", line 345, in run
  File "/usr/lib/python3.10/subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1842, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/elufimov/.local/share/pypoetry/venv/bin/python'               
                                                                                                                                                      

Execution time: 2,686s

```

**Comment by neersighted** [comment]
This is because of a bug in Python packaging on these OS versions. We have documented a workaround, but the proper fix will be in your operating system/OS packaging:

https://github.com/python-poetry/install.python-poetry.org#debianubuntu
