### ISSUE TITLE
After upgrading to poetry 1.2.0, installation of fasttext library fails

### ISSUE THREAD

**Issue by georgeseifada** [python-poetry/poetry#6293]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: macOS Monterey 12.4
- **Poetry version**: 1.2.0

## Issue

Here is a minimal examples:

**pyproject.toml**

```
[tool.poetry]
name = "myproject"
version = "0.3.0"
description = "my service"
authors = ["Bobthebuilder <bob@myemail.com>"]

[tool.poetry.dependencies]
python = "^3.9"
fasttext = "0.9.2"
hanzidentifier = "1.0.2"

[tool.poetry.dev-dependencies]
pytest = "^6.2.5"
poethepoet = "^0.13.1"
requests = "^2.27.1"
python-dotenv = "^0.19.2"
```

If I execute `poetry install` with `poetry==1.2.0` the installation fails with the following error:

```
#10 20.55 
#10 20.55   at /usr/local/lib/python3.9/subprocess.py:528 in run
#10 20.67        524│             # We don't call process.wait() as .__exit__ does that for us.
#10 20.67        525│             raise
#10 20.67        526│         retcode = process.poll()
#10 20.67        527│         if check and retcode:
#10 20.67     →  528│             raise CalledProcessError(retcode, process.args,
#10 20.67        529│                                      output=stdout, stderr=stderr)
#10 20.67        530│     return CompletedProcess(process.args, retcode, stdout, stderr)
#10 20.67        531│ 
#10 20.67        532│ 
#10 20.67 
#10 20.67 The following error occurred when trying to handle this error:
#10 20.67 
#10 20.67 
#10 20.67   EnvCommandError
#10 20.67 
#10 20.67   Command ['/root/.cache/pypoetry/virtualenvs/myproject-9TtSrW0h-py3.9/bin/python', '/usr/local/lib/python3.9/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/root/.cache/pypoetry/virtualenvs/myproject-9TtSrW0h-py3.9', '--no-deps', '/root/.cache/pypoetry/artifacts/ac/a5/ee/54101db87f67a97b9b6b57eb413731373edaa830ae76b984b844257e4a/fasttext-0.9.2.tar.gz'] errored with the following return code 1, and output: 
#10 20.67   Processing /root/.cache/pypoetry/artifacts/ac/a5/ee/54101db87f67a97b9b6b57eb413731373edaa830ae76b984b844257e4a/fasttext-0.9.2.tar.gz
#10 20.67     Installing build dependencies: started
#10 20.67     Installing build dependencies: finished with status 'done'
#10 20.67     Getting requirements to build wheel: started
#10 20.67     Getting requirements to build wheel: finished with status 'error'
#10 20.67     error: subprocess-exited-with-error
#10 20.67     
#10 20.67     × Getting requirements to build wheel did not run successfully.
#10 20.67     │ exit code: 1
#10 20.67     ╰─> [25 lines of output]
#10 20.67         /root/.cache/pypoetry/virtualenvs/myproject-9TtSrW0h-py3.9/bin/python: No module named pip
#10 20.67         Traceback (most recent call last):
#10 20.67           File "<string>", line 38, in __init__
#10 20.67         ModuleNotFoundError: No module named 'pybind11'
#10 20.67         
#10 20.67         During handling of the above exception, another exception occurred:
#10 20.67         
#10 20.67         Traceback (most recent call last):
#10 20.67           File "/tmp/tmp6lhbwq02_in_process.py", line 363, in <module>
#10 20.67             main()
#10 20.67           File "/tmp/tmp6lhbwq02_in_process.py", line 345, in main
#10 20.67             json_out['return_val'] = hook(**hook_input['kwargs'])
#10 20.67           File "/tmp/tmp6lhbwq02_in_process.py", line 130, in get_requires_for_build_wheel
#10 20.67             return hook(config_settings)
#10 20.67           File "/tmp/pip-build-env-z8o11hhy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
#10 20.67             return self._get_build_requires(config_settings, requirements=['wheel'])
#10 20.67           File "/tmp/pip-build-env-z8o11hhy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
#10 20.67             self.run_setup()
#10 20.67           File "/tmp/pip-build-env-z8o11hhy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 482, in run_setup
#10 20.67             super(_BuildMetaLegacyBackend,
#10 20.67           File "/tmp/pip-build-env-z8o11hhy/overlay/lib/python3.9/site-packages/setuptools/build_meta.py", line 335, in run_setup
#10 20.67             exec(code, locals())
#10 20.67           File "<string>", line 72, in <module>
#10 20.67           File "<string>", line 41, in __init__
#10 20.67         RuntimeError: pybind11 install failed.
#10 20.67         [end of output]
#10 20.67     
#10 20.67     note: This error originates from a subprocess, and is likely not a problem with pip.
#10 20.67   error: subprocess-exited-with-error
#10 20.67   
#10 20.67   × Getting requirements to build wheel did not run successfully.
#10 20.67   │ exit code: 1
#10 20.67   ╰─> See above for output.
#10 20.67   
#10 20.67   note: This error originates from a subprocess, and is likely not a problem with pip.
#10 20.67   
#10 20.67 
#10 20.67   at /usr/local/lib/python3.9/site-packages/poetry/utils/env.py:1473 in _run
#10 20.78       1469│                 output = subprocess.check_output(
#10 20.78       1470│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
#10 20.78       1471│                 )
#10 20.78       1472│         except CalledProcessError as e:
#10 20.78     → 1473│             raise EnvCommandError(e, input=input_)
#10 20.78       1474│ 
#10 20.78       1475│         return decode(output)
#10 20.78       1476│ 
#10 20.78       1477│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:
#10 20.78 
#10 20.78 The following error occurred when trying to handle this error:
#10 20.78 
#10 20.78 
#10 20.78   PoetryException
#10 20.78 
#10 20.78   Failed to install /root/.cache/pypoetry/artifacts/ac/a5/ee/54101db87f67a97b9b6b57eb413731373edaa830ae76b984b844257e4a/fasttext-0.9.2.tar.gz
#10 20.78 
#10 20.78   at /usr/local/lib/python3.9/site-packages/poetry/utils/pip.py:51 in pip_install
#10 20.78        47│ 
#10 20.78        48│     try:
#10 20.78        49│         return environment.run_pip(*args)
#10 20.78        50│     except EnvCommandError as e:
#10 20.78     →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
#10 20.78        52│ 
#10 20.78 
------
```

However, on `poetry==1.1.14` the installation works perfectly fine.

Note that in order to reproduce, you will need to install `apt-get update -y && apt-get install build-essential python3-dev -y`

**Comment by dimbleby** [comment]
duplicate #6113, please close

**Comment by georgeseifada** [comment]
Thanks!
