### ISSUE TITLE
PEP 503 compliance in 1.1.0 causes my package to no longer be installed properly

### ISSUE THREAD

**Issue by vancromy** [python-poetry/poetry#6413]

**Comment by neersighted** [comment]
Moved from poetry-core as somehow issues got turned on there by mistake -- we use one tracker for both Poetry and poetry-core.

**Comment by dimbleby** [comment]
Oh, I remember now. This is going to be a duplicate of #6198, in which the discussion concluded that importlib at python 3.10 handled this fine (per my attempt to reproduce), and that poetry wasn't wrong.

**Comment by neersighted** [comment]
Good catch, I also remember that issue now. We're probably going to need some sort of FAQ entry for this.

**Comment by elemakil** [comment]
Hi @neersighted @dimbleby,

sorry for hijacking this issue but I think I have the same issue and I don't understand the solution presented here or in #6198. We are using implicit namespace packages [as per](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages) to place all our python packages within an organisation specific namespace and avoid naming collisions.

As an example consider the following `pyproject.toml` 
```
[tool.poetry]
name = "org.module"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"
packages = [
    { include = "org", from = "src" },
]

[tool.poetry.dependencies]
python = "^3.7"

[build-system]
requires = ["poetry-core>=1.1.0"]
build-backend = "poetry.core.masonry.api"
```

which is accomodated by an empty `Readme.md` and a single source file located in `src/org/module/__init__.py` which contains

```python
import sys

if sys.version_info >= (3, 8):  # pragma: no cover
    import importlib.metadata as importlib_metadata
else:  # pragma: no cover
    import importlib_metadata

def get_version():
    return importlib_metadata.version(__name__)
```

**Reproduction steps**

1. Install poetry 1.1.15
2. Run `poetry install`
3. Run `poetry run python -c 'from org.module import get_version; print(get_version())'`

This produces the (expected) output

```
0.1.0
```

1. Install poetry 1.2.0
2. Run `poetry install`
3. Run `poetry run python -c 'from org.module import get_version; print(get_version())'`

This produces a crash

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/fawilk/Temp/poetry-1.2-issue/src/org/module/__init__.py", line 9, in get_version
    return importlib_metadata.version(__name__)
  File "/home/fawilk/.pyenv/versions/3.9.1/lib/python3.9/importlib/metadata.py", line 551, in version
    return distribution(distribution_name).version
  File "/home/fawilk/.pyenv/versions/3.9.1/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/home/fawilk/.pyenv/versions/3.9.1/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: org.module
```

- I have tried replacing `name = "org.module"` by `name = "org-module"` in the `[tool.poetry]` section of `pyproject.toml` as suggested in #6198, however, this does not resolve the issue. 
- I can confirm that this issue only occurs when using python 3.8.6 or 3.9.1 and vanishes when I use 3.10.5.
- I've executed `poetry build` with both poetry 1.1.15 and 1.2.0 and compared the contents of the generated `.tar.gz` and could not find any difference.

Can you provide instructions how to solve this problem?

**Comment by dimbleby** [comment]
#6198 reported that `name = "org-module"` did resolve this.  

Indeed it seems unlikely that a fresh install of code that doesn't mention the text `org.module` would fall over complaining about `org.module`.  Perhaps you still had something from a previous try interfering when you did this?

Alternatively (warning, untested) perhaps spelling out `org-module` in place of `__name__` while you are stuck at an older importlib would work.

**Comment by elemakil** [comment]
Thanks for the quick reply. I don't think interference from a previous attempt is an issue but of course you never know.

It appears the issue was truly with importlib and I didn't fully think the implications through. Hard-coding `org-module` in place of `__name__` does indeed resolve this. As does using the "backported" [importlib-metadata](https://pypi.org/project/importlib-metadata/) installed from pypi instead of the builtin version. We've been using this for `python < 3.8`, I guess we'll have to add it to version 3.8 and 3.9 as well.

Thanks to @dimbleby for pointing me in the right direction!
