### ISSUE TITLE
  ModuleNotFoundError: No module named 'numpy' when installing package after upgrading to 1.2

### ISSUE THREAD

**Issue by tall-josh** [python-poetry/poetry#6417]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**:  Ubuntu 20.04
- **Poetry version**: 1.2

## Issue
Hey I am trying to `poetry add mmpycocotools` and I get the following error

```
Package operations: 1 install, 1 update, 0 removals

  • Updating setuptools (65.3.0 -> 59.5.0)
  • Installing mmpycocotools (12.0.3): Failed

  CalledProcessError

  Command '['/home/users/josh/.venvs/myenv/bin/python', '/home/users/josh/.local/share/pypoetry/venv/lib/python3.7/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/home/users/josh/.venvs/myenv', '--no-deps', '/home/users/josh/.cache/pypoetry/artifacts/8d/1b/b8/abb84b69e94a9e16e3e2a1ed8725fb71610b92b6a1f5ae807def0da22e/mmpycocotools-12.0.3.tar.gz']' returned non-zero exit status 1.

  at ~/.pyenv/versions/3.7.9/lib/python3.7/subprocess.py:512 in run
       508│             raise
       509│         retcode = process.poll()
       510│         if check and retcode:
       511│             raise CalledProcessError(retcode, process.args,
    →  512│                                      output=stdout, stderr=stderr)
       513│     return CompletedProcess(process.args, retcode, stdout, stderr)
       514│ 
       515│ 
       516│ def list2cmdline(seq):

The following error occurred when trying to handle this error:


  EnvCommandError
  Command ['/home/users/josh/.venvs/myenv/bin/python', '/home/users/josh/.local/share/pypoetry/venv/lib/python3.7/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip', 'install', '--use-pep517', '--disable-pip-version-check', '--prefix', '/home/users/josh/.venvs/myenv', '--no-deps', '/home/users/josh/.cache/pypoetry/artifacts/8d/1b/b8/abb84b69e94a9e16e3e2a1ed8725fb71610b92b6a1f5ae807def0da22e/mmpycocotools-12.0.3.tar.gz'] errored with the following return code 1, and output: 
  Looking in indexes: https://pypi.org/simple, https://josh:****@pypi.silverpond.com.au/simple
  Processing /home/users/josh/.cache/pypoetry/artifacts/8d/1b/b8/abb84b69e94a9e16e3e2a1ed8725fb71610b92b6a1f5ae807def0da22e/mmpycocotools-12.0.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [17 lines of output]
        Traceback (most recent call last):
          File "/tmp/tmpx3tfhljc", line 363, in <module>
            main()
          File "/tmp/tmpx3tfhljc", line 345, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/tmp/tmpx3tfhljc", line 130, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/tmp/pip-build-env-sjtmfa9i/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/tmp/pip-build-env-sjtmfa9i/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
            self.run_setup()
          File "/tmp/pip-build-env-sjtmfa9i/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 483, in run_setup
            self).run_setup(setup_script=setup_script)
          File "/tmp/pip-build-env-sjtmfa9i/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 1, in <module>
        ModuleNotFoundError: No module named 'numpy'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  

  at ~/.local/share/pypoetry/venv/lib/python3.7/site-packages/poetry/utils/env.py:1473 in _run
      1469│                 output = subprocess.check_output(
      1470│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1471│                 )
      1472│         except CalledProcessError as e:
    → 1473│             raise EnvCommandError(e, input=input_)
      1474│ 
      1475│         return decode(output)
      1476│ 
      1477│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /home/users/josh/.cache/pypoetry/artifacts/8d/1b/b8/abb84b69e94a9e16e3e2a1ed8725fb71610b92b6a1f5ae807def0da22e/mmpycocotools-12.0.3.tar.gz
```

Running the offending command manually does (thankfully) reproduce the error, but removing `--use-pep517` results in the package installing.

```
/home/users/josh/.venvs/myenv/bin/python /home/users/josh/.local/share/pypoetry/venv/lib/python3.7/site-packages/virtualenv/seed/wheels/embed/pip-22.2.2-py3-none-any.whl/pip install --use-pep517 --disable-pip-version-check --prefix /home/users/josh/.venvs/myenv --no-deps /home/users/josh/.cache/pypoetry/artifacts/8d/1b/b8/abb84b69e94a9e16e3e2a1ed8725fb71610b92b6a1f5ae807def0da22e/mmpycocotools-12.0.3.tar.gz
```

In the meantime, I'm using `poethepoet` to install `mmpycocotools`

Maybe it's an artefact of an upstream issue but I'm confused why `numpy` cannot be found.

**Comment by neersighted** [comment]
Looks like this is an upstream issue -- `numpy` is not found during the build as in a PEP 517 build environment, only `setup_requires` dependencies are available during the build. There is no declaration of a build-time dependency on `numpy` in the upstream setup.py:

https://github.com/open-mmlab/cocoapi/blob/01f805cd54d7bd7af64c0fbd5fd96d8ca0b9ddc9/pycocotools/setup.py#L1

If wheels were made available (or if you built a wheel and hosted it at a stable URL), Poetry would be able to install this dependency with no issues. However, for a source-based build, a setup.py that declares its dependencies properly is needed.
