### ISSUE TITLE
Poetry 1.2.0 doesn't seem to like shortened git commit hashes

### ISSUE THREAD

**Issue by dasm-tmlt** [python-poetry/poetry#6455]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Mac OS 12.3
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: [https://gist.github.com/dasm-tmlt/28b714320c663ae87df3f262a64916d1]

## Issue
I'm the first person on my team using poetry 1.2.0, and noticed that one of our existing dependencies stopped working (I've verified that it works fine under 1.1.15). The gist above is a minimal example that demonstrates the problem - trying to run `poetry lock` returns `Failed to clone https://github.com/ryan112358/private-pgm.git at 'e9ea5fc', verify ref exists on remote.`, but that commit [definitely exists](https://github.com/ryan112358/private-pgm/commit/e9ea5fc). Replacing the shortened version of the commit hash (`e9ea5fc`) with the full commit hash (`e9ea5fcac62e2c5b92ae97f7afe2648c04432564`) fixes the problem, so there is a workaround, but this does seem like a regression.

Note that debugging this problem was rather difficult because once the first failure has occurred, poetry doesn't attempt to re-download the dependency. Running `poetry lock` a second time will yield a different error:

```
Unable to determine package info for path: /Users/dasm/test/.venv/src/private-pgm

Command ['/var/folders/1g/g0wb8wcn2ys55jkc69z0xs3r0000gn/T/tmp53lmvcsc/.venv/bin/python', '-'] errored with the following return code 1, and output: 
Traceback (most recent call last):
  File "<stdin>", line 13, in <module>
  File "/var/folders/1g/g0wb8wcn2ys55jkc69z0xs3r0000gn/T/tmp53lmvcsc/.venv/lib/python3.7/site-packages/build/__init__.py", line 208, in __init__
    _validate_source_directory(srcdir)
  File "/var/folders/1g/g0wb8wcn2ys55jkc69z0xs3r0000gn/T/tmp53lmvcsc/.venv/lib/python3.7/site-packages/build/__init__.py", line 109, in _validate_source_directory
    raise BuildException(f'Source {srcdir} does not appear to be a Python project: no pyproject.toml or setup.py')
build.BuildException: Source /Users/dasm/test/.venv/src/private-pgm does not appear to be a Python project: no pyproject.toml or setup.py
input was : import build
import build.env
import pep517

source = '/Users/dasm/test/.venv/src/private-pgm'
dest = '/var/folders/1g/g0wb8wcn2ys55jkc69z0xs3r0000gn/T/tmp53lmvcsc/dist'

with build.env.IsolatedEnvBuilder() as env:
    builder = build.ProjectBuilder(
        srcdir=source,
        scripts_dir=env.scripts_dir,
        python_executable=env.executable,
        runner=pep517.quiet_subprocess_runner,
    )
    env.install(builder.build_system_requires)
    env.install(builder.get_requires_for_build('wheel'))
    builder.metadata_path(dest)

No fallback setup.py file was found to generate egg_info.
```

If instead you switch to the full commit hash after a failure with the short hash, `poetry lock` fails silently (there is error output when running with `-vvv`) rather than downloading the right dependency. Only if you remove the mostly empty directory (it contains a single `.git` file) at `.venv/src/private-pgm` does it start working properly.

**Comment by neersighted** [comment]
This is a dulwich issue -- there is currently a PR open to add a callout of this to the release notes, but if shortened hashes are important to your workflow you can work around the lack of them with `poetry config experimental.system-git-client true`.

**Comment by neersighted** [comment]
(the mentioned PR is https://github.com/python-poetry/website/pull/82)

**Comment by dasm-tmlt** [comment]
I see. We've already switched to using longer hashes, so we should be okay.

If this is going to be a limitation of poetry going forward, it would be good to have a better error message (the current one suggesting that the ref might not exist is not that helpful). Additionally, the fact that trying to use a short hash lands you in a broken state where it's difficult to recover was really frustrating, and felt like a larger issue than lack of support for short hashes.

**Comment by neersighted** [comment]
I think the solution is to open a dulwich issue/request and see if this is something they intend to support. If they do, we can consider it a gotcha of Poetry 1.2.0 that future releases (or even an update of deps depending on dulwich semver) will resolve -- if they opt not to support it, we can add it to the docs and validate hash length to provide a useful error message/guards against creating a broken lock file.

**Comment by dasm-tmlt** [comment]
Got it, would you like me to open an issue with dulwich? I suspect I will not do a great job (since I don't know much about how poetry uses dulwich), but I can take a stab.

It's ultimately your call since you'd be doing the work, but I'd recommend doing the work to smooth the experience in the short term even if dulwich intends to fix it long-term. The current experience is not great.

At a minimum, I would recommend changing the documentation [here](https://python-poetry.org/docs/dependency-specification/#git-dependencies) so the examples don't use short hashes, and adding a note saying explicitly that they aren't supported. I would not have thought to check the changelog, but I did look at that documentation page.

**Comment by neersighted** [comment]
Dulwich is quite responsive so if they implement support I don't think we'll need to do much -- but if they don't, we certainly should add some error handling to catch this as part of the next patch release.

Please do open an issue -- feel free to link here and they should have enough context.

**Comment by dasm-tmlt** [comment]
Before I do that, I just want to run one thing by you: it looks like poetry is [already attending to detect short hashes and replace them with full-length ones](https://github.com/python-poetry/poetry/blob/f51a2c7427a046bcb71434e8ff29f6ce137301f7/src/poetry/vcs/git/backend.py#L88). From a cursory inspection, it seems like that should be preventing the problem I'm seeing. Are we sure this is a dulwich problem?

**Comment by neersighted** [comment]
Good call -- I think we might not be hitting that code path through the lock file, so we might need to generalize it and hoist it out, or ask Dulwich to support short hashes natively (if they don't already -- need to do more testing evidently).

**Comment by jelmer** [comment]
Dulwich does support short hashes, but only in its porcelain. The plumbing (which is what poetry uses) works with full hashes.

Poetry appears to have some code to resolve short hashes to long hashes in [src/poetry/vcs/git/backend.py](https://github.com/python-poetry/poetry/blob/master/src/poetry/vcs/git/backend.py#L88)

**Comment by dimbleby** [comment]
For reasons that escape me, this code https://github.com/python-poetry/poetry/blob/dbc2030c8b8a5aa9f7f76e3f94f99aceee574662/src/poetry/vcs/git/backend.py#L201-L205
only finds a handful of top-level references

So when poetry later searches for the short sha among the references that it has - well it's not there.

I'm not sure whether this is poetry using dulwich wrong, or dulwich failing to find the refs it ought to find. I've not found a set of parameters that make dulwich behave differently, but probably I'm missing something.

**Comment by jelmer** [comment]
The current behaviour indeed only finds top level SHAs (the git protocol doesn't provide a way to find other SHAs). As far as I know the only alternative is to download and then search for the short sha in the locally cloned repository.

**Comment by dimbleby** [comment]
The `determine_wants` and `depth` parameters on this API are rather confusing then!

Well anyway I find myself more interested in debugging this than fixing it, I'll leave it to someone who minds about this behaviour to decide what to do with that.

**Comment by jelmer** [comment]
For anybody looking at taking this on, ``dulwich.objectspec.parse_commit`` can resolve arbitrary strings to 40-character hex SHAs. It does require a local (rather than a remote) repository.

**Comment by jelmer** [comment]
> The `determine_wants` and `depth` parameters on this API are rather confusing then!

These are for determining which objects (including ancestry) you want to retrieve. Git doesn't allow you to retrieve any objects that are not actually in the refs (even if you have the full 40-character hex sha, and it's present in the repository).

**Comment by FionaDmello** [comment]
So, the discussion here points to usage of short hashes and we (in #7844) used a full hash to see if it works. This time it throws a different error, as shown below
```
Updating dependencies
Resolving dependencies... (0.0s)

  AssertionError

  

  at /local~/.local/share/pypoetry/venv/lib/python3.8/site-packages/dulwich/pack.py:699 in _object_offset
       695│ 
       696│         Args:
       697│           sha: A *binary* SHA string. (20 characters long)_
       698│         """
    →  699│         assert len(sha) == 20
       700│         idx = ord(sha[:1])
       701│         if idx == 0:
       702│             start = 0
       703│         else:
(dummy-py3.8) j.doe@ias9212:~/dummy$ 
```
We shortened it to 20 chars , and (as expected because of the docstring) it gives the exact same error as above. 

There was a mention of an issue to be opened in Dulwich. Did someone do this, already? Or, could somebody help with a workaround for this issue, if one has been found by now?

**Comment by timos-flwls** [comment]
I am having the same issue, the root of the problem seems to be that it only downloads the top level refs as @jelmer says above.

However if it fails to find to find the full hash Poetry just seems to forget that it might be a short hash? I guess it might also impossible to know whether it's a branch/tag or short hash at that point.

But my problem seems to be that Poetry then initialises a git repository for the dependency using the short hash which is invalid. When instead it problem needs to initialise it at a valid ref (head?) and search the repository history for the short hash at that point.

So the support for short hashes seems to be in a really weird place where you can also use short hashes if it's the latest commit on a branch or pull request? At that point Poetry should just not support short hashes, at least it could provide a sensible error (please do not use short hashes :D )

**Comment by timos-flwls** [comment]
Unfortunately specifying the full commit hash leads to a separate bug, running into the same problem as @FionaDmello.

**Comment by jelmer** [comment]
@FionaDmello @timos-flwls the code you're quoting expects a 20-byte *binary* SHA, not a a 40-byte hex sha shortened to 20 bytes. Can you share the full traceback?

**Comment by jelmer** [comment]
FWIW I started working on a PR last weekend to try to address this issue, but there are a lot of moving parts.

**Comment by F1ashhimself** [comment]
@FionaDmello found that if you delete poetry env (poetry env remove python) then this error will disappear.

**Comment by Skorpyon** [comment]
There is no problem how you define dependency (6-8-20 sha).
I've defined even the tag:
```toml
fastapi-sdk = {git = "git@gitlab.internal:fastapi-sdk.git", tag="2.0.4"}
```
but here:
```python
# dulwich/pack.py
def _object_offset(self, sha: bytes) -> int:
    ...
    print(sha)
    assert len(sha) == 20
```
it printing `b'8bcdbb\n'` that resolved from the tree given by GitHub, so tricking with short-long SHA helps rarely.
How it said above probably Poetry should refactor Dulwich usage.

**Comment by Forden** [comment]
> @FionaDmello found that if you delete poetry env (poetry env remove python) then this error will disappear.

this helped me

**Comment by abn** [comment]
The original issue reported is not longer present. It was partially resolved by #9748 and by dulwich upgrade. You can test by using the latest version of Poetry from `main`.

```sh
pipx install --force --suffix=@git 'poetry @ git+https://github.com/python-poetry/poetry.git'
```

Note `poetry@git` now refers to the vcs version of Poetry installed above.
