### ISSUE TITLE
poetry doesn't add __pycache__ folder during "poetry install"

### ISSUE THREAD

**Issue by RalfKow** [python-poetry/poetry#6503]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

#### Develope environement
- **OS version and name**: Windows 10
- **Poetry version**: Poetry 1.2.0
- **Python**:3.8.10
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: See the pyproject.toml below

#### Remote environement
- **Docker**:???
- **Python**:3.8.13
- **Poetry version**: Poetry 1.2.0

## Issue
If I run the command

1. poetry install
2. poetry run pre-commit run --all-files

```bash
unittest-run.............................................................Failed
- hook id: unittest-run
- exit code: 1

Running tests...
----------------------------------------------------------------------
EEE
======================================================================
ERROR [0.012s]: tests.sample_pipeline.test_feed_selector (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.sample_pipeline.test_feed_selector
Traceback (most recent call last):
  File "c:\..\python308\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "c:\..\python308\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\..\sample-pipeline\tests\sample_pipeline\test_feed_selector.py", line 3, in <module>
    from sample_pipeline import feed_selector
ImportError: cannot import name 'feed_selector' from 'sample_pipeline' (C:\..\sample-pipeline\tests\sample_pipeline\__init__.py)


======================================================================
ERROR [0.001s]: tests.sample_pipeline.test_greeter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.sample_pipeline.test_greeter
Traceback (most recent call last):
  File "c:\..\python308\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "c:\..\python308\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\..\sample-pipeline\tests\sample_pipeline\test_greeter.py", line 3, in <module>
    from sample_pipeline.greeter.greeter import Greeter
ModuleNotFoundError: No module named 'sample_pipeline.greeter'


======================================================================
ERROR [0.000s]: tests.snowpark_utils.test_snowflake_client (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: tests.snowpark_utils.test_snowflake_client
Traceback (most recent call last):
  File "c:\..\python308\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "c:\..\python308\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "C:\..\sample-pipeline\tests\snowpark_utils\test_snowflake_client.py", line 1, in <module>
    from snowpark_utils.snowflake_client import SnowflakeClient
ModuleNotFoundError: No module named 'snowpark_utils.snowflake_client'


----------------------------------------------------------------------
```

On the local machine, the folders get created after multiple times executing "poetry install". If I compare the two environements  the one throwing the exception doesnt have the files
poetry doesn't create the folder __pycache__ in the folder
 .venv/Lib/site-packages/{
pkg_resources/__pycache__,
pkg_resources/vendor/__pycache__,
pkg_resources/vendor/importlib_resources/__pycache__,
 }

## pyproject.toml
```toml
[tool.poetry]
name = "sample-pipeline"
version = "0.0.0" # Version is ignored and set by jenkins. Use pipeline to increase.
description = "Example project for Python"
packages = [
    {include = "sample_pipeline", from = "src"},
    {include = "snowpark_utils", from = "src"},
    {include = "test_cases", from = "tests"}] #TODO: Try to get rid of include local packages
readme = "README.md"

[tool.poetry.dependencies]
python = "3.8.*"
numpy = "^1.22.4"                                   # NumPy is the fundamental package for array computing with Python.
pandas = "1.4.4"                                    # Pandas is a data analysis and manipulation tool.
snowflake-snowpark-python = "0.9.0"                 # The Snowpark library provides intuitive APIs for querying and processing data.

[tool.poetry.dev-dependencies]
black = "^22.3.0"                                   # The uncompromising code formatter.
coverage = {extras = ["toml"], version = "^6.4.1"}  # Code coverage measurement for Python
unittest-xml-reporting = "^3.2.0"                   # unittest-based test runner with Ant/JUnit like XML reporting.
pre-commit = "^2.19.0"                              # A framework for managing and maintaining multi-language pre-commit hooks.
pre-commit-hooks = "^4.2.0"                         # Some out-of-the-box hooks for pre-commit.
pydocstyle = "^6.1.1"                               # Python docstring style checker
pylint = "^2.14.1"                                  # python code static checker
reorder-python-imports = "^3.1.0"                   # Tool for reordering python imports

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pylint.main]
fail-on = "F,E,W"
fail-under = 0.0

[tool.pylint.basic]
good-names = ["i", "j", "k", "n", "s", "d", "ex", "Run", "_", "pk", "x", "y", "df"]

[tool.pylint.format]
max-line-length = 140

[tool.pylint.design]
max-args = 8

[tool.pylint.messages_control]
disable = [
    # pydocstyle takes care of this...
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
    
    # don't hinder me creating small classes!
    "too-few-public-methods",
    
    # reorder-python-imports should know what it's doing
    "wrong-import-order",

    # can't do much about duplicate imports in two files, I'm afraid...
    "duplicate-code",
]

[tool.pylint.miscellaneous]
notes = []  # don't warn about `TODO` and `FIXME` comments

[tool.pylint.reports]
output-format = "parseable:pylintout,text"

[tool.pydocstyle]
match-dir = "[^\\.][^test].*"
convention = "google"

[tool.coverage.run]
command_line = "-m xmlrunner discover --output-file junittest.xml"
```

**Comment by neersighted** [comment]
It's very unclear what this issue is about -- the `__pycache__` folders should be installed by Poetry and pip if present in a wheel, and generated after the first run by Python if they are not installed. Whether or not they are included in a wheel is a bit of a matter of opinion and circumstance.

`__pycache__` is simply an implementation detail of Python and can be [disabled if desired](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONDONTWRITEBYTECODE). There is no real reason to do so as the bytecode representation of Python code provides a minor speedup and has robust invalidation logic for when the source file changes.

It's unclear why you are referencing your test failures under `pre-commit` -- though I suspect that might be your real issue as `pre-commit` runs your code in an isolated environment and will not have access to import your project or its dependencies. 

I am going to close this for now as I believe I have answered your immediate question, and if you are having issues figuring out the best way to operate your test suite when managing deps with Poetry, Discussions or Discord are much more appropriate venues.
