### ISSUE TITLE
Poetry 1.2.0 fails to install LightFM

### ISSUE THREAD

**Issue by daniel-ferguson** [python-poetry/poetry#6527]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Fedora Linux 36, kernel 5.19.8
- **Poetry version**: 1.2.0
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: https://gist.github.com/daniel-ferguson/9bf5becb724d4ec2fb68e524a3a10f11#file-pyproject-toml

## Issue

Trying to upgrade one of our projects from `1.1.4` to `1.2` results in errors during the `poetry install` process, which we can reliably reproduce in both local and CI environments.

I've narrowed the issue down to a change in poetry that affects its ability to install the [lightfm package](https://github.com/lyst/lightfm). Please see the attached gist for both the minimal `pyproject.toml` that reproduces the issue, as well as a `poetry install -vvv` log.

Please let me know if there's anything further I can do to help!

**Comment by daniel-ferguson** [comment]
Hi @dimbleby - thanks for your speedy reply. I wonder if it's something about the way poetry shells out, since after running `poetry shell` in the test project I can install it fine with `pip`.

```
(repro-poetry-lightfm-py3.9) > pip install --use-pep517 lightfm==1.16
Collecting lightfm==1.16
  Using cached lightfm-1.16-cp39-cp39-linux_x86_64.whl
Requirement already satisfied: scipy>=0.17.0 in /home/daniel/.cache/pypoetry/virtualenvs/repro-poetry-lightfm-sAGHHxSF-py3.9/lib/python3.9/site-packages (from lightfm==1.16) (1.6.1)
Requirement already satisfied: scikit-learn in /home/daniel/.cache/pypoetry/virtualenvs/repro-poetry-lightfm-sAGHHxSF-py3.9/lib/python3.9/site-packages (from lightfm==1.16) (1.1.2)
Requirement already satisfied: requests in /home/daniel/.cache/pypoetry/virtualenvs/repro-poetry-lightfm-sAGHHxSF-py3.9/lib/python3.9/site-packages (from lightfm==1.16) (2.28.1)
Requirement already satisfied: numpy in /home/daniel/.cache/pypoetry/virtualenvs/repro-poetry-lightfm-sAGHHxSF-py3.9/lib/python3.9/site-packages (from lightfm==1.16) (1.23.3)
Requirement already satisfied: idna<4,>=2.5 in /home/daniel/.cache/pypoetry/virtualenvs/repro-poetry-lightfm-sAGHHxSF-py3.9/lib/python3.9/site-packages (from requests->lightfm==1.16) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /home/daniel/.cache/pypoetry/virtualenvs/repro-poetry-lightfm-sAGHHxSF-py3.9/lib/python3.9/site-packages (from requests->lightfm==1.16) (1.26.12)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/daniel/.cache/pypoetry/virtualenvs/repro-poetry-lightfm-sAGHHxSF-py3.9/lib/python3.9/site-packages (from requests->lightfm==1.16) (2.1.1)
Requirement already satisfied: certifi>=2017.4.17 in /home/daniel/.cache/pypoetry/virtualenvs/repro-poetry-lightfm-sAGHHxSF-py3.9/lib/python3.9/site-packages (from requests->lightfm==1.16) (2022.9.14)
Requirement already satisfied: threadpoolctl>=2.0.0 in /home/daniel/.cache/pypoetry/virtualenvs/repro-poetry-lightfm-sAGHHxSF-py3.9/lib/python3.9/site-packages (from scikit-learn->lightfm==1.16) (3.1.0)
Requirement already satisfied: joblib>=1.0.0 in /home/daniel/.cache/pypoetry/virtualenvs/repro-poetry-lightfm-sAGHHxSF-py3.9/lib/python3.9/site-packages (from scikit-learn->lightfm==1.16) (1.1.0)
Installing collected packages: lightfm
Successfully installed lightfm-1.16
```

**Comment by dimbleby** [comment]
I see this
```
$ pip install --use-pep517 lightfm==1.16
Collecting lightfm==1.16
  Downloading lightfm-1.16.tar.gz (310 kB)
     |████████████████████████████████| 310 kB 5.4 MB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /home/dch/.virtualenvs/foo/bin/python3 /tmp/tmp5suci12x get_requires_for_build_wheel /tmp/tmpyy5ta2an
       cwd: /tmp/pip-install-50bnvg8i/lightfm
  Complete output (17 lines):
  Traceback (most recent call last):
    File "/tmp/tmp5suci12x", line 280, in <module>
      main()
    File "/tmp/tmp5suci12x", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp5suci12x", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-5izi0fvz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-5izi0fvz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-5izi0fvz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 482, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-5izi0fvz/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 11, in <module>
  AttributeError: 'dict' object has no attribute '__LIGHTFM_SETUP__'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /home/dch/.virtualenvs/foo/bin/python3 /tmp/tmp5suci12x get_requires_for_build_wheel /tmp/tmpyy5ta2an Check the logs for full command output.
```
I guess you are finding abinary wheel but I am at a diffierent python version and am not.  You could likely reproduce the error by adding `--no-binary` to your pip install command.  

Either way, it is certainly lightfm's build that is broken.

https://github.com/python-poetry/poetry/pull/5385 might help in some cases, if that got merged.

I expect that what has changed in poetry is that it now uses `--use-pep517`, which it didn't used to do.

**Comment by daniel-ferguson** [comment]
Ah, ok thanks for your help. I can reproduce with `pip install --use-pep517 lightfm==1.16 --no-binary :all:`

I'll close this issue in favour of the lightfm bug
