### ISSUE TITLE
Error during pre-commit initialization phase: `poetry.core.semver.exceptions.ParseConstraintError: Could not parse version constraint: (>=20.4.3`

### ISSUE THREAD

**Issue by mzebrak** [python-poetry/poetry#6546]
- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) Poetry version.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option).

- **OS version and name**: Ubuntu 20.04
- **Poetry version**: 1.2.1
- **Link of a [Gist](https://gist.github.com/) with the contents of your pyproject.toml file**: `N/A`

## Issue

We run pre-commit check --all-files during our GitLab CI steps.

Yesterday (16 September) everything was working when today (17 September) an error is raised when pre-commit is initializing.
It looks like poetry recently released a new version (1.2.1) but even when locking pip install poetry==1.2.0, this error appears.

Also, it looks like the 20.4.3 corresponds to the virtualenv version, because in the job log I can see:

```
Collecting virtualenv!=20.4.5,!=20.4.6,>=20.4.3
  Downloading virtualenv-20.16.5-py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 91.1 MB/s eta 0:00:00
```
When trying with locked version of `pip install poetry==1.2.0,` the `20.4.3` could not be observed but pre-commit still fails.
```
Collecting virtualenv
  Downloading virtualenv-20.16.5-py3-none-any.whl (8.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.8/8.8 MB 68.6 MB/s eta 0:00:00
```

 It looks like it is related to https://github.com/python-poetry/poetry-core/pull/461/commits/f61f8df5e2e8c67bf154614ff71b3821b02cbb6f
 which was introduced in the `poetry 1.2.1` update which bumps `poetry-core` to `1.2.0` but I still don't understand why I'm getting this error when locking `pip install poetry==1.2.0`. Also, we got `requires = ["poetry-core==1.1.0"]` in the pyproject.toml file.
 
#### Steps to reproduce:

1. `pip install poetry`
2. `poetry install`
3. `source poetry env info --path/bin/activate`
4. `pre-commit run --all-files`

#### Full error message:
```
$ echo -e "${TXT_BLUE}Check all files with pre-commit hooks${TXT_CLEAR}" && pre-commit run --all-files
Check all files with pre-commit hooks
[INFO] Initializing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Initializing environment for https://github.com/python-poetry/poetry.
[INFO] Installing environment for https://github.com/pre-commit/pre-commit-hooks.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
[INFO] Installing environment for https://github.com/python-poetry/poetry.
[INFO] Once installed this environment will be reused.
[INFO] This may take a few minutes...
An unexpected error has occurred: CalledProcessError: command: ('/root/.cache/pre-commit/repo3tk67alr/py_env-python3/bin/python', '-mpip', 'install', '.')
return code: 1
expected return code: 0
stdout:
    Processing /root/.cache/pre-commit/repo3tk67alr
      Installing build dependencies: started
      Installing build dependencies: finished with status 'done'
      Getting requirements to build wheel: started
      Getting requirements to build wheel: finished with status 'done'
      Preparing metadata (pyproject.toml): started
      Preparing metadata (pyproject.toml): finished with status 'error'
    
stderr:
      error: subprocess-exited-with-error
      
      × Preparing metadata (pyproject.toml) did not run successfully.
      │ exit code: 1
      ╰─> [26 lines of output]
          Traceback (most recent call last):
            File "/root/.cache/pre-commit/repo3tk67alr/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
              main()
            File "/root/.cache/pre-commit/repo3tk67alr/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
              json_out['return_val'] = hook(**hook_input['kwargs'])
            File "/root/.cache/pre-commit/repo3tk67alr/py_env-python3/lib/python3.8/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
              return hook(metadata_directory, config_settings)
            File "/tmp/pip-build-env-hrlj9u5v/overlay/lib/python3.8/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
              poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
            File "/tmp/pip-build-env-hrlj9u5v/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 62, in create_poetry
              package = self.configure_package(
            File "/tmp/pip-build-env-hrlj9u5v/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 156, in configure_package
              cls._add_package_group_dependencies(
            File "/tmp/pip-build-env-hrlj9u5v/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 102, in _add_package_group_dependencies
              cls.create_dependency(
            File "/tmp/pip-build-env-hrlj9u5v/overlay/lib/python3.8/site-packages/poetry/core/factory.py", line 366, in create_dependency
              dependency = Dependency(name, constraint, groups=groups)
            File "/tmp/pip-build-env-hrlj9u5v/overlay/lib/python3.8/site-packages/poetry/core/packages/dependency.py", line 66, in __init__
              self.constraint = constraint  # type: ignore[assignment]
            File "/tmp/pip-build-env-hrlj9u5v/overlay/lib/python3.8/site-packages/poetry/core/packages/dependency.py", line 110, in constraint
              self._constraint = parse_constraint(constraint)
            File "/tmp/pip-build-env-hrlj9u5v/overlay/lib/python3.8/site-packages/poetry/core/semver/helpers.py", line 31, in parse_constraint
              constraint_objects.append(parse_single_constraint(constraint))
            File "/tmp/pip-build-env-hrlj9u5v/overlay/lib/python3.8/site-packages/poetry/core/semver/helpers.py", line 147, in parse_single_constraint
              raise ParseConstraintError(f"Could not parse version constraint: {constraint}")
          poetry.core.semver.exceptions.ParseConstraintError: Could not parse version constraint: (>=20.4.3
          [end of output]
      
      note: This error originates from a subprocess, and is likely not a problem with pip.
    error: metadata-generation-failed
    
    × Encountered error while generating package metadata.
    ╰─> See above for output.
    
    note: This is an issue with the package mentioned above, not pip.
    hint: See above for details.
    
Check the log at /root/.cache/pre-commit/pre-commit.log
```

**Comment by dimbleby** [comment]
The poetry 1.2.0 version constraint was bad, and poetry 1.2.1 detects this.

So presumably you still have some 1.2.0 poetry creeping in somewhere, you should update

**Comment by mzebrak** [comment]
Found the source of the error:
`.pre-commit-config.yaml`

```
 14 ⋮ 14 |  - repo: https://github.com/python-poetry/poetry
 15 ⋮  - │    rev: 1.2.0
  + ⋮ 15 │    rev: 1.2.1

```
