### ISSUE TITLE
poetry install gets stuck

### ISSUE THREAD

**Issue by dimaqq** [python-poetry/poetry#6836]
```
> poetry install
Installing dependencies from lock file

Package operations: 104 installs, 0 updates, 0 removals

  • Installing charset-normalizer (2.1.1): Pending...
  • Installing pyparsing (3.0.9): Pending...
  • Installing urllib3 (1.26.12): Pending...

# stuck here, after a few minutes I've decided to kill it

^C^C^CError in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.8/concurrent/futures/thread.py", line 40, in _python_exit
    t.join()
  File "/usr/lib/python3.8/threading.py", line 1011, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.8/threading.py", line 1027, in _wait_for_tstate_lock
    elif lock.acquire(block, timeout):
KeyboardInterrupt
```

are there any magic flags I can use to generate the kind of debug log that would be helpful to the devs?

**Comment by dimaqq** [comment]
I was able to work around that by adding `--no-plugins --no-cache`

Maybe the problem is that I've recently upgraded from `1.1.x` to `1.2.x` ?

Not the best dev exp, but I'm happy to use this software :)
May be worth noting this somewhere or having the new version drop the old cache 🤔

**Comment by dimbleby** [comment]
presumably duplicate #6030 (and many others)

**Comment by dimaqq** [comment]
Sounds like it could be that indeed.
