### ISSUE TITLE
Poetry does not install every package from dependency groups

### ISSUE THREAD

**Issue by lacer93** [python-poetry/poetry#6913]
- **Poetry version**: 1.2.2
- **Python version**: 3.8.13
- **OS version and name**: macOS 12.6
- **pyproject.toml**: https://gist.github.com/lacer93/942be8950a004e18a7e826a6805223c2

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I created a simple `pyproject.toml` file with dependency groups:
```
[tool.poetry]
name = "example"
version = "0.1.0"
description = "Example"
authors = ["example"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.group.abc.dependencies]
fastapi = "^0.65.2"
msgpack = "^1.0.2"

[tool.poetry.group.test]
optional = true

[tool.poetry.group.test.dependencies]
pytest = "*"

[build-system]
requires = ["poetry>=1.0"]
build-backend = "poetry.core.masonry.api"
```
locking created this [lock](https://gist.github.com/lacer93/942be8950a004e18a7e826a6805223c2#file-poetry-lock) file. It seems correct, it contains everything that is needed.

According to the documentation:
> By default, dependencies across all non-optional groups will be installed when executing poetry install.

So my expectation is that if I execute `poetry install --with test` I will have
 - fastapi
 - msgpack
 - pytest

installed and ready to go but that is not the case:
```
❯ poetry install --with test
Installing dependencies from lock file

Package operations: 9 installs, 0 updates, 0 removals

  • Installing typing-extensions (4.4.0)
  • Installing exceptiongroup (1.0.0)
  • Installing iniconfig (1.1.1)
  • Installing pluggy (1.0.0)
  • Installing pydantic (1.10.2)
  • Installing starlette (0.14.2)
  • Installing tomli (2.0.1)
  • Installing fastapi (0.65.3)
  • Installing pytest (7.2.0)
```
`msgpack` is already missing for some reason but `fastapi` is there which is weird because they are in the same dependency group. 

```
❯ poetry run pytest     
Traceback (most recent call last):
  File "/Users/example/Library/Caches/pypoetry/virtualenvs/example-jaXQCetV-py3.8/bin/pytest", line 5, in <module>
    from pytest import console_main
  File "/Users/example/Library/Caches/pypoetry/virtualenvs/example-jaXQCetV-py3.8/lib/python3.8/site-packages/pytest/__init__.py", line 5, in <module>
    from _pytest._code import ExceptionInfo
  File "/Users/example/Library/Caches/pypoetry/virtualenvs/example-jaXQCetV-py3.8/lib/python3.8/site-packages/_pytest/_code/__init__.py", line 2, in <module>
    from .code import Code
  File "/Users/example/Library/Caches/pypoetry/virtualenvs/example-jaXQCetV-py3.8/lib/python3.8/site-packages/_pytest/_code/code.py", line 35, in <module>
    import attr
ModuleNotFoundError: No module named 'attr'
```
`pytest` is there but some of its dependencies are not. `attrs` is a [dependency](https://github.com/pytest-dev/pytest/blob/646a46e5f4b1f1ae5a06dcbc91fcdebfc235a28a/setup.cfg#L47) of `pytest` and it is in the lock file but it is not installed.

```
❯ poetry run pip freeze                                                                                       
exceptiongroup @ file:///Users/example/Library/Caches/pypoetry/artifacts/9d/58/84/dcbd7cff9a9e21313d4d800a57f512933dc4a55721f84ec24a82b75c0a/exceptiongroup-1.0.0-py3-none-any.whl
fastapi @ file:///Users/example/Library/Caches/pypoetry/artifacts/fc/d2/ff/8670678c4b851a14b995e2b81488757b5e167bada2409003c5436f4176/fastapi-0.65.3-py3-none-any.whl
iniconfig @ file:///Users/example/Library/Caches/pypoetry/artifacts/ac/f9/da/e990ffcd9ec361a68676a5916e391286e1ea5d1b8907ae887e141a71f5/iniconfig-1.1.1-py2.py3-none-any.whl
pluggy @ file:///Users/example/Library/Caches/pypoetry/artifacts/38/05/d7/70e2b0d553c780097b692ed658b0f553a28f16028d848a98174b1a2249/pluggy-1.0.0-py2.py3-none-any.whl
pydantic @ file:///Users/example/Library/Caches/pypoetry/artifacts/d9/0a/fa/35afc709433b744e92ebc845172f1b5c5a99bb050eb465d0c69827cd37/pydantic-1.10.2-cp38-cp38-macosx_11_0_arm64.whl
pytest @ file:///Users/example/Library/Caches/pypoetry/artifacts/b8/d4/fa/e11ca7e853aabf27bad9a66d522b5ad2b770643c57b10be217fe9bc86a/pytest-7.2.0-py3-none-any.whl
starlette @ file:///Users/example/Library/Caches/pypoetry/artifacts/24/98/d5/27dc0660a651fef03b9f7a1eb252133d2c136058fc421d1794ac7c8604/starlette-0.14.2-py3-none-any.whl
tomli @ file:///Users/example/Library/Caches/pypoetry/artifacts/36/bd/11/98fa2af866c73d00f2498ade62c7fcf28db8656714b7b7a44e9cb2f855/tomli-2.0.1-py3-none-any.whl
typing_extensions @ file:///Users/example/Library/Caches/pypoetry/artifacts/ee/e8/69/53e1643581fdd5761336e7a2ee82742b171fa57ab9dbed6d15593e5d0b/typing_extensions-4.4.0-py3-none-any.whl
```

**Comment by neersighted** [comment]
I can't reproduce this; everything from your pyproject.toml installs as expected on my machine and in a container. I would try recreating your virtual environment, and running Poetry in debug mode and sharing the log here if you are still having trouble.

```
$ poetry install --with test                                                                                                           
Installing dependencies from lock file

Package operations: 13 installs, 0 updates, 0 removals

  • Installing pyparsing (3.0.9)
  • Installing typing-extensions (4.4.0)
  • Installing attrs (22.1.0)
  • Installing exceptiongroup (1.0.0)
  • Installing iniconfig (1.1.1)
  • Installing packaging (21.3)
  • Installing pluggy (1.0.0)
  • Installing pydantic (1.10.2)
  • Installing starlette (0.14.2)
  • Installing tomli (2.0.1)
  • Installing fastapi (0.65.3)
  • Installing msgpack (1.0.4)
  • Installing pytest (7.2.0)

Installing the current project: testproj (0.1.0)                                                                                                            $ poetry show --tree --with test                                                                         
fastapi 0.65.3 FastAPI framework, high performance, easy to learn, fast to code, ready for production
├── pydantic >=1.6.2,<1.7 || >1.7,<1.7.1 || >1.7.1,<1.7.2 || >1.7.2,<1.7.3 || >1.7.3,<1.8 || >1.8,<1.8.1 || >1.8.1,<2.0.0
│   └── typing-extensions >=4.1.0
└── starlette 0.14.2
msgpack 1.0.4 MessagePack serializer
pytest 7.2.0 pytest: simple powerful testing with Python
├── attrs >=19.2.0
├── colorama *
├── exceptiongroup >=1.0.0rc8
├── iniconfig *
├── packaging *
│   └── pyparsing >=2.0.2,<3.0.5 || >3.0.5
├── pluggy >=0.12,<2.0
└── tomli >=1.0.0
```

**Comment by lacer93** [comment]
Yeah, turns out I am at fault. Earlier I was debugging a forever hanging install command (it was a problem with the HTTP session's cache, clearing it resolved the issue) in PyCharm but it wasn't really working, kept throwing errors around `Env.run_python_script` so I had to mess around and practically hardcode some stuff to avoid calling that function.

This resulted in a messed up `sys.path` which meant that Poetry looked for already installed packages in its own virtualenv instead of the project's and would not install those packages.
