### ISSUE TITLE
Fail to install specific package

### ISSUE THREAD

**Issue by FranzForstmayr** [python-poetry/poetry#7087]
- **Poetry version**: 
- **Python version**: 
- **OS version and name**: 
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Following `pyproject.toml`:
```toml
[tool.poetry]
name = "tmp"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

The installing `pyaedt` from here: https://pypi.org/project/pyaedt/  
```
poetry add pyaedt -vvv
```

Results in following exception (last lines):
```
  • Installing pyaedt (0.6.28)

  Stack trace:

  2  C:\program files\python39\lib\site-packages\poetry\utils\env.py:1472 in _run
      1470│                 )
      1471│             else:
    → 1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )

  1  C:\program files\python39\lib\subprocess.py:424 in check_output
       422│         kwargs['input'] = empty
       423│ 
    →  424│     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
       425│                **kwargs).stdout
       426│

  CalledProcessError

  Command 'C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\tmp-GSJlVcU4-py3.9\Scripts\python.exe -m pip install --use-pep517 --disable-pip-version-check --prefix C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\tmp-GSJlVcU4-py3.9 --no-deps C:\Users\User\AppData\Local\pypoetry\Cache\artifacts\4b\5e\68\28cb2ff4fb2b3c99e8b6d2907b64dae8b7eeb97583e1ffd33f55f1fc1d\pyaedt-0.6.28.tar.gz' returned non-zero exit status 1.

  at C:\program files\python39\lib\subprocess.py:528 in run
       524│             # We don't call process.wait() as .__exit__ does that for us.
       525│             raise
       526│         retcode = process.poll()
       527│         if check and retcode:
    →  528│             raise CalledProcessError(retcode, process.args,
       529│                                      output=stdout, stderr=stderr)
       530│     return CompletedProcess(process.args, retcode, stdout, stderr)
       531│
       532│

The following error occurred when trying to handle this error:


  Stack trace:

  3  C:\program files\python39\lib\site-packages\poetry\utils\pip.py:49 in pip_install
       47│
       48│     try:
    →  49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
       51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e

  2  C:\program files\python39\lib\site-packages\poetry\utils\env.py:1435 in run_pip
      1433│         pip = self.get_pip_command()
      1434│         cmd = pip + list(args)
    → 1435│         return self._run(cmd, **kwargs)
      1436│
      1437│     def run_python_script(self, content: str, **kwargs: Any) -> int | str:

  1  C:\program files\python39\lib\site-packages\poetry\utils\env.py:1712 in _run
      1710│     def _run(self, cmd: list[str], **kwargs: Any) -> int | str:
      1711│         kwargs["env"] = self.get_temp_environ(environ=kwargs.get("env"))
    → 1712│         return super()._run(cmd, **kwargs)
      1713│
      1714│     def get_temp_environ(

  EnvCommandError

  Command C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\tmp-GSJlVcU4-py3.9\Scripts\python.exe -m pip install --use-pep517 --disable-pip-version-check --prefix C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\tmp-GSJlVcU4-py3.9 --no-deps C:\Users\User\AppData\Local\pypoetry\Cache\artifacts\4b\5e\68\28cb2ff4fb2b3c99e8b6d2907b64dae8b7eeb97583e1ffd33f55f1fc1d\pyaedt-0.6.28.tar.gz errored with the following return code 1, and output:
  Processing c:\users\User\appdata\local\pypoetry\cache\artifacts\4b\5e\68\28cb2ff4fb2b3c99e8b6d2907b64dae8b7eeb97583e1ffd33f55f1fc1d\pyaedt-0.6.28.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error

    Getting requirements to build wheel did not run successfully.
    exit code: 1

    [17 lines of output]
    Traceback (most recent call last):
      File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\tmp-GSJlVcU4-py3.9\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
        main()
      File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\tmp-GSJlVcU4-py3.9\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "C:\Users\User\AppData\Local\pypoetry\Cache\virtualenvs\tmp-GSJlVcU4-py3.9\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
        return hook(config_settings)
      File "C:\Users\User\AppData\Local\Temp\pip-build-env-6e83ctyr\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
        return self._get_build_requires(config_settings, requirements=['wheel'])
      File "C:\Users\User\AppData\Local\Temp\pip-build-env-6e83ctyr\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
        self.run_setup()
      File "C:\Users\User\AppData\Local\Temp\pip-build-env-6e83ctyr\overlay\Lib\site-packages\setuptools\build_meta.py", line 483, in run_setup
        super(_BuildMetaLegacyBackend,
      File "C:\Users\User\AppData\Local\Temp\pip-build-env-6e83ctyr\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
        exec(code, locals())
      File "<string>", line 5, in <module>
    ModuleNotFoundError: No module named 'pip'
    [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  See above for output.

  note: This error originates from a subprocess, and is likely not a problem with pip.


  at C:\program files\python39\lib\site-packages\poetry\utils\env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│
      1478│         return decode(output)
      1479│
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  Stack trace:

  5  C:\program files\python39\lib\site-packages\poetry\installation\executor.py:261 in _execute_operation
      259│ 
      260│             try:
    → 261│                 result = self._do_execute_operation(operation)
      262│             except EnvCommandError as e:
      263│                 if e.e.returncode == -2:

  4  C:\program files\python39\lib\site-packages\poetry\installation\executor.py:334 in _do_execute_operation
      332│             return 0
      333│
    → 334│         result: int = getattr(self, f"_execute_{method}")(operation)
      335│
      336│         if result != 0:

  3  C:\program files\python39\lib\site-packages\poetry\installation\executor.py:454 in _execute_install
      452│ 
      453│     def _execute_install(self, operation: Install | Update) -> int:
    → 454│         status_code = self._install(operation)
      455│
      456│         self._save_url_reference(operation)

  2  C:\program files\python39\lib\site-packages\poetry\installation\executor.py:496 in _install
      494│         )
      495│         self._write(operation, message)
    → 496│         return self.pip_install(archive, upgrade=operation.job_type == "update")
      497│
      498│     def _update(self, operation: Install | Update) -> int:

  1  C:\program files\python39\lib\site-packages\poetry\installation\executor.py:123 in pip_install
      121│     ) -> int:
      122│         try:
    → 123│             pip_install(req, self._env, upgrade=upgrade, editable=editable)
      124│         except EnvCommandError as e:
      125│             output = decode(e.e.output)

  PoetryException

  Failed to install C:/Users/User/AppData/Local/pypoetry/Cache/artifacts/4b/5e/68/28cb2ff4fb2b3c99e8b6d2907b64dae8b7eeb97583e1ffd33f55f1fc1d/pyaedt-0.6.28.tar.gz

  at C:\program files\python39\lib\site-packages\poetry\utils\pip.py:51 in pip_install
       47│
       48│     try:
       49│         return environment.run_pip(*args)
       50│     except EnvCommandError as e:
    →  51│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       52│

```

Installing with pip works fine.

**Comment by dimbleby** [comment]
Not a poetry bug, as you can verify by:
```
pip install --use-pep517 --no-binary pyaedt pyaedt
```
you should raise this at pyaedt

**Comment by dimbleby** [comment]
Please feel free to submit a docs MR if you think that would have helped you

**Comment by FranzForstmayr** [comment]
Is there at least a way to specify such a package in `pyproject.toml`

**Comment by dimbleby** [comment]
no, poetry always uses pep517 install, your only route to fixing this is at pyaedt

**Comment by Secrus** [comment]
pyaedt even have issue about it: https://github.com/pyansys/pyaedt/issues/1646
