### ISSUE TITLE
`poetry install` in 3.5 env - "AttributeError: 'PosixPath' object has no attribute 'endswith'"

### ISSUE THREAD

**Issue by alorence** [python-poetry/poetry#7124]
- **Poetry version**: 1.2.2
- **Python version**: System python : 3.10.8, env version: 3.5.10
- **OS version and name**: Linux (Manjaro)
- **pyproject.toml**: https://github.com/alorence/django-modern-rpc/blob/better-dependencies-management/pyproject.toml

- [ x ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ x ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ x ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ x ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
I am managing a FOSS project with Python 3.5 and 3.6 support. I know that Poetry runs only on Python 3.7+, but I assume I can use it with my python system (3.10) while working in an environment:
```bash
❯ python -V
Python 3.10.8
❯ pyenv local   
system
3.11
3.5
❯ poetry env use 3.5
Creating virtualenv django-modern-rpc-4Wp8Q-da-py3.5 in /home/alorence/.cache/pypoetry/virtualenvs
Using virtualenv: /home/alorence/.cache/pypoetry/virtualenvs/django-modern-rpc-4Wp8Q-da-py3.5
❯ poetry run python -V
Python 3.5.10
```

Now, I try to install the dependencies inside the 3.5 environment:

```bash
❯ poetry install -vvv
Loading configuration file /home/alorence/.config/pypoetry/config.toml
Using virtualenv: /home/alorence/.cache/pypoetry/virtualenvs/django-modern-rpc-4Wp8Q-da-py3.5
Project environment contains an empty path in sys_path, ignoring.
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 33 installs, 0 updates, 0 removals, 1 skipped

  • Installing zipp (1.2.0): Pending...
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/zipp/1.2.0/json HTTP/1.1" 304 0
  • Installing zipp (1.2.0): Failed

  Stack trace:

  1  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/utils/env.py:1459 in _run
      1457│ 
      1458│             if input_:
    → 1459│                 output = subprocess.run(
      1460│                     command,
      1461│                     stdout=subprocess.PIPE,

  CalledProcessError

  Command '['/home/alorence/.cache/pypoetry/virtualenvs/django-modern-rpc-4Wp8Q-da-py3.5/bin/python', '-W', 'ignore', '-']' returned non-zero exit status 1.

  at /usr/lib/python3.10/subprocess.py:526 in run
       522│             # We don't call process.wait() as .__exit__ does that for us.
       523│             raise
       524│         retcode = process.poll()
       525│         if check and retcode:
    →  526│             raise CalledProcessError(retcode, process.args,
       527│                                      output=stdout, stderr=stderr)
       528│     return CompletedProcess(process.args, retcode, stdout, stderr)
       529│ 
       530│ 

The following error occurred when trying to handle this error:


  Stack trace:

  12  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/executor.py:261 in _execute_operation
       259│ 
       260│             try:
     → 261│                 result = self._do_execute_operation(operation)
       262│             except EnvCommandError as e:
       263│                 if e.e.returncode == -2:

  11  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/executor.py:334 in _do_execute_operation
       332│             return 0
       333│ 
     → 334│         result: int = getattr(self, f"_execute_{method}")(operation)
       335│ 
       336│         if result != 0:

  10  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/executor.py:454 in _execute_install
       452│ 
       453│     def _execute_install(self, operation: Install | Update) -> int:
     → 454│         status_code = self._install(operation)
       455│ 
       456│         self._save_url_reference(operation)

   9  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/executor.py:488 in _install
       486│             archive = self._download_link(operation, Link(package.source_url))
       487│         else:
     → 488│             archive = self._download(operation)
       489│ 
       490│         operation_message = self.get_operation_message(operation)

   8  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/executor.py:633 in _download
       631│ 
       632│     def _download(self, operation: Install | Update) -> Path:
     → 633│         link = self._chooser.choose_for(operation.package)
       634│ 
       635│         if link.yanked:

   7  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/chooser.py:88 in choose_for
        86│                     continue
        87│ 
     →  88│                 if not Wheel(link.filename).is_supported_by_environment(self._env):
        89│                     logger.debug(
        90│                         "Skipping wheel %s as this is not supported by the current"

   6  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/installation/chooser.py:56 in is_supported_by_environment
        54│ 
        55│     def is_supported_by_environment(self, env: Env) -> bool:
     →  56│         return bool(set(env.supported_tags).intersection(self.tags))
        57│ 
        58│ 

   5  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/utils/env.py:1370 in supported_tags
       1368│     def supported_tags(self) -> list[Tag]:
       1369│         if self._supported_tags is None:
     → 1370│             self._supported_tags = self.get_supported_tags()
       1371│ 
       1372│         return self._supported_tags

   4  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/utils/env.py:1674 in get_supported_tags
       1672│ 
       1673│     def get_supported_tags(self) -> list[Tag]:
     → 1674│         output = self.run_python_script(GET_SYS_TAGS)
       1675│         assert isinstance(output, str)
       1676│ 

   3  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/utils/env.py:1438 in run_python_script
       1436│ 
       1437│     def run_python_script(self, content: str, **kwargs: Any) -> int | str:
     → 1438│         return self.run(self._executable, "-W", "ignore", "-", input_=content, **kwargs)
       1439│ 
       1440│     def _run(self, cmd: list[str], **kwargs: Any) -> int | str:

   2  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/utils/env.py:1430 in run
       1428│     def run(self, bin: str, *args: str, **kwargs: Any) -> str | int:
       1429│         cmd = self.get_command_from_bin(bin) + list(args)
     → 1430│         return self._run(cmd, **kwargs)
       1431│ 
       1432│     def run_pip(self, *args: str, **kwargs: Any) -> int | str:

   1  ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/utils/env.py:1712 in _run
       1710│     def _run(self, cmd: list[str], **kwargs: Any) -> int | str:
       1711│         kwargs["env"] = self.get_temp_environ(environ=kwargs.get("env"))
     → 1712│         return super()._run(cmd, **kwargs)
       1713│ 
       1714│     def get_temp_environ(

  EnvCommandError

  Command ['/home/alorence/.cache/pypoetry/virtualenvs/django-modern-rpc-4Wp8Q-da-py3.5/bin/python', '-W', 'ignore', '-'] errored with the following return code 1, and output: 
  Traceback (most recent call last):
    File "<stdin>", line 9, in <module>
    File "<frozen importlib._bootstrap_external>", line 581, in spec_from_file_location
  AttributeError: 'PosixPath' object has no attribute 'endswith'
  input was : 
  import importlib.util
  import json
  import sys
  
  from pathlib import Path
  
  spec = importlib.util.spec_from_file_location(
      "packaging", Path(r"/home/alorence/.local/pipx/venvs/poetry/lib/python3.10/site-packages/packaging/__init__.py")
  )
  packaging = importlib.util.module_from_spec(spec)
  sys.modules[spec.name] = packaging
  
  spec = importlib.util.spec_from_file_location(
      "packaging.tags", Path(r"/home/alorence/.local/pipx/venvs/poetry/lib/python3.10/site-packages/packaging/tags.py")
  )
  packaging_tags = importlib.util.module_from_spec(spec)
  spec.loader.exec_module(packaging_tags)
  
  print(
      json.dumps([(t.interpreter, t.abi, t.platform) for t in packaging_tags.sys_tags()])
  )
  

  at ~/.local/pipx/venvs/poetry/lib/python3.10/site-packages/poetry/utils/env.py:1476 in _run
      1472│                 output = subprocess.check_output(
      1473│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1474│                 )
      1475│         except CalledProcessError as e:
    → 1476│             raise EnvCommandError(e, input=input_)
      1477│ 
      1478│         return decode(output)
      1479│ 
      1480│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:
```

I think the relevant part is

> AttributeError: 'PosixPath' object has no attribute 'endswith'

coming from https://github.com/python-poetry/poetry/blob/d02c71cf0262b4741852a9ca0333db1021ac4b9f/src/poetry/utils/env.py#L71-L73

Giving a `Path` instance to `importlib.util.spec_from_file_location` may be problematic in Python 3.5 environment, [as explained in the documentation](https://docs.python.org/3/library/importlib.html#importlib.util.spec_from_file_location):

> New in version 3.4.
> 
> Changed in version 3.6: Accepts a [path-like object](https://docs.python.org/3/glossary.html#term-path-like-object).

**Comment by dimbleby** [comment]
did you try the obvious fix, and does it work?  want to submit a pull request?

**Comment by alorence** [comment]
The obvious fix works well
```python
spec = importlib.util.spec_from_file_location(
    "packaging", str(Path(r"{packaging.__file__}"))
)
# [...]
spec = importlib.util.spec_from_file_location(
    "packaging.tags", str(Path(r"{packaging.tags.__file__}"))
)
```

But the command `poetry install` fails later on another Python 3.5 specific syntax error, in `packaging` module.
Since I used pipx to setup poetry, I can easily check which `packaging` version is installed in poetry's environment (system wide)

```bash
❯ pipx runpip poetry show packaging
Name: packaging
Version: 21.3
Summary: Core utilities for Python packages
Home-page: https://github.com/pypa/packaging
Author: Donald Stufft and individual contributors
Author-email: donald@stufft.io
License: BSD-2-Clause or Apache-2.0
Location: /home/alorence/.local/pipx/venvs/poetry/lib/python3.10/site-packages
Requires: pyparsing
Required-by: poetry
```

According to Pypi's relase notes, [packaging requires python 3.6 starting with 21.0]((https://pypi.org/project/packaging/21.0/).
But [packaging 20.9 run well with python 3.5](https://pypi.org/project/packaging/20.9/).

I tried manually downgrade packaging in poetry's virtualenv
```bash
❯ pipx runpip poetry install "packaging==20.9"
```

Then, re-try running the problematic command:
```bash
❯ poetry install
Installing dependencies from lock file

Package operations: 33 installs, 0 updates, 0 removals

  • Installing zipp (1.2.0)
  • Installing importlib-metadata (2.1.3)
  • Installing pyparsing (2.4.7)
  • Installing six (1.16.0)
  • Installing attrs (22.1.0)
  • Installing iniconfig (1.1.1)
  • Installing packaging (20.9)
  • Installing pathlib2 (2.3.7.post1)
  • Installing pluggy (0.13.1)
  • Installing py (1.11.0)
  • Installing pyrsistent (0.17.3)
  • Installing toml (0.10.2)
  • Installing apply-defaults (0.1.6)
  • Installing certifi (2021.10.8)
  • Installing chardet (4.0.0)
  • Installing click (7.1.2)
  • Installing coverage (5.5)
  • Installing idna (2.10)
  • Installing jsonschema (3.2.0)
  • Installing pytest (6.1.2)
  • Installing pytz (2022.6)
  • Installing sqlparse (0.4.3)
  • Installing termcolor (1.1.0)
  • Installing urllib3 (1.26.9)
  • Installing django (2.2.28)
  • Installing docutils (0.17.1)
  • Installing jsonrpcclient (3.3.6)
  • Installing markdown (3.2.2)
  • Installing pytest-cov (2.12.1)
  • Installing pytest-django (4.5.2)
  • Installing pytest-pythonpath (0.7.4)
  • Installing pytest-sugar (0.9.6)
  • Installing requests (2.25.1)

Installing the current project: django-modern-rpc (1.0.0a4)
```

And it works ! So, I'm ok to submit a pull request, but to fix the issue, we have to update code in `env.py` and ensure packaging < 21 is installed in all case. Would you agree with that?

**Comment by dimbleby** [comment]
Probably other will want to chip in - but guess that it won't be OK to hold poetry to an old version of packaging for the benefit of python 3.5.  

The fact that it is broken, per this issue, suggests that the number of people using poetry to manage a python 3.5 project is extremely small - perhaps as low as one.  I'd guess that the project will prefer to drop that python 3.5 support than to commit to being stuck with old packaging.

**Comment by alorence** [comment]
Since I started using poetry's group feature in my project, and all the CI/CD have been updated accordingly with poetry 1.2.*, this will be difficult to handle. But I perfectly understand that maintaining support for Python 3.5 is painful. But I think the poetry's doc should be updated to indicate py35 environments are not supported anymore.

I can open a PR to update docs' `managing-environments.md` with the folloiwing message:

```
{{% note %}}
Since version 1.2, Poetry no longer supports managing environments for Python under 3.6.
{{% /note %}}
```

But I saw another message in CLI indicating a wrond information

```
Python 3.5 will no longer be supported in the next feature release of Poetry (1.2).
You should consider updating your Python version to a supported one.

Note that you will still be able to manage Python 3.5 projects by using the env command.
See https://python-poetry.org/docs/managing-environments/ for more information.
```

See https://github.com/alorence/django-modern-rpc/actions/runs/3578173444/jobs/6018026523 in Install dependencies

But I don't know where this message is printed. I didn't find it in poetry's code. Do you know where it come from ?

**Comment by dimbleby** [comment]
> in the next feature release of Poetry (1.2)

presumably that message comes from the 1.1 codebase, so there's no need to worry about updating that.

Neither dropping support for 3.5 projects or committing to that support is a decision that I can take - I'd wait for someone to show up who does have such authority before submitting any more MRs.

(of course if you have any ideas about how to achieve what that code is trying to achieve without being stuck at old versions of packaging, that would be great...)

**Comment by alorence** [comment]
> Neither dropping support for 3.5 projects nor committing to that support is a decision that I can take - I'd wait for someone to show up who does have such authority before submitting any MRs.

I understand. Maybe this issue should remain open at least until a decision is made to either
- officially drop the support of managing python 3.5 projects
or
- find a way to repair this feature

The official poetry 1.2 announce on the blog mentionned only the end of python 2.7 projects support : https://python-poetry.org/blog/announcing-poetry-1.2.0/#dropping-support-for-managing-python-27-projects
