### ISSUE TITLE
Unhelpful "tuple index out of range" error on empty project

### ISSUE THREAD

**Issue by brandon-leapyear** [python-poetry/poetry#7185]
- **Poetry version**: 
- **Python version**: 
- **OS version and name**: 
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Repro: running `docker build .` with this Dockerfile shows an unhelpful "tuple index out of range" error:
```dockerfile
FROM python:3.11

RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH=/root/.local/bin:$PATH
RUN poetry --version
RUN poetry init
RUN poetry install
```
Seems to happen when `packages` is not specified in `pyproject.toml` and poetry tries to automatically add an `Include` that has a glob pattern `.`, which is an invalid glob:
```python
>>> list(Path("/").glob("."))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/pathlib.py", line 1139, in glob
    selector = _make_selector(tuple(pattern_parts), self._flavour)
  File "/usr/local/lib/python3.8/pathlib.py", line 463, in _make_selector
    pat = pattern_parts[0]
IndexError: tuple index out of range
```

**Comment by brandon-leapyear** [comment]
ah seems to only happen when running in the root directory `/` and without a name specified (as is the case with `poetry init`). So perhaps not high priority.

Also, there's another error when using `poetry init --dependency=click` in the root directory:
```
  Unable to parse fact: fact:  depends on click (^8.1.3)

  at ~/.local/share/pypoetry/venv/lib/python3.11/site-packages/poetry/puzzle/provider.py:840 in debug
       836│         if message.startswith("fact:"):
       837│             if "depends on" in message:
       838│                 m = re.match(r"fact: (.+?) depends on (.+?) \((.+?)\)", message)
       839│                 if m is None:
    →  840│                     raise ValueError(f"Unable to parse fact: {message}")
       841│                 m2 = re.match(r"(.+?) \((.+?)\)", m.group(1))
       842│                 if m2:
       843│                     name = m2.group(1)
       844│                     version = f" ({m2.group(2)})"
```

**Comment by silverwind** [comment]
Another way to reproduce is to run `poetry` on this `pyproject.toml`:

```toml
[tool.poetry]
name = ""
version = "0.0.0"
description = ""
authors = []

[tool.poetry.dependencies]
python = "^3.8"

**Comment by dimbleby** [comment]
presumably can be fixed by adding a pattern to the schema, preventing empty strings - at https://github.com/python-poetry/poetry-core/blob/0749c5531d778a07788dfdc163716523fd479d9e/src/poetry/core/json/schemas/poetry-schema.json#L13
