### ISSUE TITLE
Poetry>1.1 don't work after installation via pip

### ISSUE THREAD

**Issue by voronind** [python-poetry/poetry#7332]
Ubuntu 20.04.
Python 3.8

Install Poerty using pip
```console
$ pip3 install --user  poetry

Collecting poetry
  Using cached poetry-1.3.1-py3-none-any.whl (218 kB)
Requirement already satisfied: dulwich<0.21.0,>=0.20.46 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (0.20.50)
Requirement already satisfied: html5lib<2.0,>=1.0 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (1.1)
Requirement already satisfied: poetry-core==1.4.0 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (1.4.0)
Requirement already satisfied: crashtest<0.5.0,>=0.4.1 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (0.4.1)
Requirement already satisfied: keyring<24.0.0,>=23.9.0 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (23.13.1)
Requirement already satisfied: requests-toolbelt<0.11.0,>=0.9.1 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (0.9.1)
Requirement already satisfied: cachecontrol[filecache]<0.13.0,>=0.12.9 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (0.12.10)
Requirement already satisfied: poetry-plugin-export<2.0.0,>=1.2.0 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (1.2.0)
Requirement already satisfied: lockfile<0.13.0,>=0.12.2 in /usr/lib/python3/dist-packages (from poetry) (0.12.2)
Requirement already satisfied: pexpect<5.0.0,>=4.7.0 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (4.8.0)
Requirement already satisfied: importlib-metadata<5.0,>=4.4 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (4.13.0)
Requirement already satisfied: requests<3.0,>=2.18 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (2.28.1)
Requirement already satisfied: platformdirs<3.0.0,>=2.5.2 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (2.6.2)
Requirement already satisfied: trove-classifiers>=2022.5.19 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (2022.12.22)
Requirement already satisfied: tomli<3.0.0,>=2.0.1 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (2.0.1)
Requirement already satisfied: cleo<3.0.0,>=2.0.0 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (2.0.1)
Requirement already satisfied: virtualenv!=20.4.5,!=20.4.6,<21.0.0,>=20.4.3 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (20.17.1)
Requirement already satisfied: filelock<4.0.0,>=3.8.0 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (3.9.0)
Requirement already satisfied: pkginfo<2.0,>=1.5 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (1.5.0.1)
Requirement already satisfied: packaging>=20.4 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (20.4)
Requirement already satisfied: shellingham<2.0,>=1.5 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (1.5.0.post1)
Requirement already satisfied: urllib3<2.0.0,>=1.26.0 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (1.26.13)
Requirement already satisfied: tomlkit!=0.11.2,!=0.11.3,<1.0.0,>=0.11.1 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (0.11.6)
Requirement already satisfied: jsonschema<5.0.0,>=4.10.0 in /home/voronin/.local/lib/python3.8/site-packages (from poetry) (4.17.3)
Requirement already satisfied: msgpack>=0.5.2 in /home/voronin/.local/lib/python3.8/site-packages (from cachecontrol[filecache]<0.13.0,>=0.12.9->poetry) (1.0.1)
Requirement already satisfied: rapidfuzz<3.0.0,>=2.2.0 in /home/voronin/.local/lib/python3.8/site-packages (from cleo<3.0.0,>=2.0.0->poetry) (2.13.7)
Requirement already satisfied: six>=1.9 in /usr/lib/python3/dist-packages (from html5lib<2.0,>=1.0->poetry) (1.14.0)
Requirement already satisfied: webencodings in /home/voronin/.local/lib/python3.8/site-packages (from html5lib<2.0,>=1.0->poetry) (0.5.1)
Requirement already satisfied: zipp>=0.5 in /home/voronin/.local/lib/python3.8/site-packages (from importlib-metadata<5.0,>=4.4->poetry) (3.10.0)
Requirement already satisfied: importlib-resources>=1.4.0 in /home/voronin/.local/lib/python3.8/site-packages (from jsonschema<5.0.0,>=4.10.0->poetry) (5.10.0)
Requirement already satisfied: attrs>=17.4.0 in /usr/lib/python3/dist-packages (from jsonschema<5.0.0,>=4.10.0->poetry) (19.3.0)
Requirement already satisfied: pkgutil-resolve-name>=1.3.10 in /home/voronin/.local/lib/python3.8/site-packages (from jsonschema<5.0.0,>=4.10.0->poetry) (1.3.10)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /usr/lib/python3/dist-packages (from jsonschema<5.0.0,>=4.10.0->poetry) (0.15.5)
Requirement already satisfied: jeepney>=0.4.2 in /home/voronin/.local/lib/python3.8/site-packages (from keyring<24.0.0,>=23.9.0->poetry) (0.8.0)
Requirement already satisfied: jaraco.classes in /home/voronin/.local/lib/python3.8/site-packages (from keyring<24.0.0,>=23.9.0->poetry) (3.2.3)
Requirement already satisfied: SecretStorage>=3.2 in /home/voronin/.local/lib/python3.8/site-packages (from keyring<24.0.0,>=23.9.0->poetry) (3.3.3)
Requirement already satisfied: pyparsing>=2.0.2 in /home/voronin/.local/lib/python3.8/site-packages (from packaging>=20.4->poetry) (2.4.7)
Requirement already satisfied: ptyprocess>=0.5 in /home/voronin/.local/lib/python3.8/site-packages (from pexpect<5.0.0,>=4.7.0->poetry) (0.6.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests<3.0,>=2.18->poetry) (2019.11.28)
Requirement already satisfied: charset-normalizer<3,>=2 in /home/voronin/.local/lib/python3.8/site-packages (from requests<3.0,>=2.18->poetry) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests<3.0,>=2.18->poetry) (2.8)
Requirement already satisfied: cryptography>=2.0 in /usr/lib/python3/dist-packages (from SecretStorage>=3.2->keyring<24.0.0,>=23.9.0->poetry) (2.8)
Requirement already satisfied: distlib<1,>=0.3.6 in /home/voronin/.local/lib/python3.8/site-packages (from virtualenv!=20.4.5,!=20.4.6,<21.0.0,>=20.4.3->poetry) (0.3.6)
Requirement already satisfied: more-itertools in /usr/lib/python3/dist-packages (from jaraco.classes->keyring<24.0.0,>=23.9.0->poetry) (4.2.0)
Installing collected packages: poetry
Successfully installed poetry-1.3.1
WARNING: You are using pip version 20.3.3; however, version 22.3.1 is available.
You should consider upgrading via the '/usr/bin/python3 -m pip install --upgrade pip' command.
```

Run Poetry
```console
$ poetry --version

Traceback (most recent call last):
  File "/home/voronin/.local/lib/python3.8/site-packages/cleo/application.py", line 327, in run
    exit_code = self._run(io)
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/console/application.py", line 188, in _run
    self._load_plugins(io)
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/console/application.py", line 355, in _load_plugins
    manager.load_plugins()
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/plugins/plugin_manager.py", line 38, in load_plugins
    self._load_plugin_entry_point(ep)
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/plugins/plugin_manager.py", line 76, in _load_plugin_entry_point
    plugin = ep.load()  # type: ignore[no-untyped-call]
  File "/home/voronin/.local/lib/python3.8/site-packages/importlib_metadata/__init__.py", line 207, in load
    module = import_module(match.group('module'))
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry_plugin_export/plugins.py", line 7, in <module>
    from poetry_plugin_export.command import ExportCommand
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry_plugin_export/command.py", line 7, in <module>
    from poetry.console.commands.group_command import GroupCommand
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/console/commands/group_command.py", line 6, in <module>
    from poetry.core.packages.dependency_group import MAIN_GROUP
ModuleNotFoundError: No module named 'poetry.core.packages.dependency_group'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/voronin/.local/bin/poetry", line 8, in <module>
    sys.exit(main())
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/console/application.py", line 406, in main
    exit_code: int = Application().run()
  File "/home/voronin/.local/lib/python3.8/site-packages/cleo/application.py", line 338, in run
    self.render_error(e, io)
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/console/application.py", line 180, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/console/application.py", line 395, in _get_solution_provider_repository
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (  # noqa: E501
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/mixology/__init__.py", line 5, in <module>
    from poetry.mixology.version_solver import VersionSolver
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/mixology/version_solver.py", line 10, in <module>
    from poetry.mixology.failure import SolveFailure
  File "/home/voronin/.local/lib/python3.8/site-packages/poetry/mixology/failure.py", line 5, in <module>
    from poetry.core.constraints.version import parse_constraint
ModuleNotFoundError: No module named 'poetry.core.constraints'
```

**Comment by voronind** [comment]
Works well if `pip install --user poetry==1.1.15

**Comment by dimbleby** [comment]
duplicate #7157
