### ISSUE TITLE
"No module named pip" when `add`ing cyipopt

### ISSUE THREAD

**Issue by ForceBru** [python-poetry/poetry#7368]
- **Poetry version**: 1.3.2
- **Python version**: 3.10.6
- **OS version and name**: macOS 10.15.7
- **pyproject.toml**:

```
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [ ] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
   - Technically, it's a duplicate of #1004, but __solutions posted there don't work for me__.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I'm simply trying to install [cyipopt](https://github.com/mechmotum/cyipopt):

```
$ poetry shell # dropped into zsh
(test-py3.10) forcebru test % poetry add cyipopt -vvv
Using virtualenv: /Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
Creating new session for pypi.org
Source (PyPI): 2 packages found for cyipopt *
Using version ^1.2.0 for cyipopt

Updating dependencies
Resolving dependencies...
   1: fact: test is 0.1.0
   1: derived: test
   1: fact: test depends on cyipopt (^1.2.0)
   1: selecting test (0.1.0)
   1: derived: cyipopt (>=1.2.0,<2.0.0)
Source (PyPI): 1 packages found for cyipopt >=1.2.0,<2.0.0
   1: fact: cyipopt (1.2.0) depends on cython (>=0.26)
   1: fact: cyipopt (1.2.0) depends on numpy (>=1.15)
   1: fact: cyipopt (1.2.0) depends on setuptools (>=39.0)
   1: selecting cyipopt (1.2.0)
   1: derived: setuptools (>=39.0)
   1: derived: numpy (>=1.15)
   1: derived: cython (>=0.26)
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/setuptools/ HTTP/1.1" 304 0
[filelock] Attempting to acquire lock 4352661280 on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/0/4/1/8/c/0418c83b80f7f7bfaec2738bfbbee53d2c1562196c0781702f6eddc8.lock
[filelock] Lock 4352661280 acquired on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/0/4/1/8/c/0418c83b80f7f7bfaec2738bfbbee53d2c1562196c0781702f6eddc8.lock
[filelock] Attempting to release lock 4352661280 on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/0/4/1/8/c/0418c83b80f7f7bfaec2738bfbbee53d2c1562196c0781702f6eddc8.lock
[filelock] Lock 4352661280 released on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/0/4/1/8/c/0418c83b80f7f7bfaec2738bfbbee53d2c1562196c0781702f6eddc8.lock
Source (PyPI): 202 packages found for setuptools >=39.0
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/numpy/ HTTP/1.1" 304 0
[filelock] Attempting to acquire lock 4363897008 on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/c/c/1/3/3/cc133da5701a066bc3777b2575e0daa601596f19871db4608ca98b97.lock
[filelock] Lock 4363897008 acquired on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/c/c/1/3/3/cc133da5701a066bc3777b2575e0daa601596f19871db4608ca98b97.lock
[filelock] Attempting to release lock 4363897008 on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/c/c/1/3/3/cc133da5701a066bc3777b2575e0daa601596f19871db4608ca98b97.lock
[filelock] Lock 4363897008 released on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/c/c/1/3/3/cc133da5701a066bc3777b2575e0daa601596f19871db4608ca98b97.lock
Source (PyPI): 54 packages found for numpy >=1.15
[urllib3.connectionpool] https://pypi.org:443 "GET /simple/cython/ HTTP/1.1" 304 0
[filelock] Attempting to acquire lock 4366647936 on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/a/2/6/7/f/a267f54c19667a20e6416d2dc2a1df4a525eed802f0f2b538b654da1.lock
[filelock] Lock 4366647936 acquired on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/a/2/6/7/f/a267f54c19667a20e6416d2dc2a1df4a525eed802f0f2b538b654da1.lock
[filelock] Attempting to release lock 4366647936 on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/a/2/6/7/f/a267f54c19667a20e6416d2dc2a1df4a525eed802f0f2b538b654da1.lock
[filelock] Lock 4366647936 released on /Users/forcebru/Library/Caches/pypoetry/cache/repositories/PyPI/_http/a/2/6/7/f/a267f54c19667a20e6416d2dc2a1df4a525eed802f0f2b538b654da1.lock
Source (PyPI): 45 packages found for cython >=0.26
   1: selecting cython (0.29.33)
   1: selecting numpy (1.24.1)
   1: selecting setuptools (66.0.0)
   1: Version solving took 4.191 seconds.
   1: Tried 1 solutions.

Writing lock file

Finding the necessary packages for the current system
Source (poetry-repo): 1 packages found for cyipopt >=1.2.0,<2.0.0
Source (poetry-repo): 1 packages found for setuptools >=39.0
Source (poetry-repo): 1 packages found for numpy >=1.15
Source (poetry-repo): 1 packages found for cython >=0.26

Package operations: 1 install, 0 updates, 0 removals, 3 skipped

  • Installing cyipopt (1.2.0): Pending...
  • Installing cyipopt (1.2.0): Installing...
  • Installing cyipopt (1.2.0): Failed

  Stack trace:

  2  ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1536 in _run
      1534│                 )
      1535│             else:
    → 1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )

  1  ~/mambaforge/lib/python3.10/subprocess.py:420 in check_output
       418│         kwargs['input'] = empty
       419│ 
    →  420│     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
       421│                **kwargs).stdout
       422│ 

  CalledProcessError

  Command '['/Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10', '--no-deps', '/Users/forcebru/Library/Caches/pypoetry/artifacts/a5/a8/9e/80306f8dda7dc4682a86897b5dfdc4d1c4444d5055260091388599b8ec/cyipopt-1.2.0.tar.gz']' returned non-zero exit status 1.

  at ~/mambaforge/lib/python3.10/subprocess.py:524 in run
       520│             # We don't call process.wait() as .__exit__ does that for us.
       521│             raise
       522│         retcode = process.poll()
       523│         if check and retcode:
    →  524│             raise CalledProcessError(retcode, process.args,
       525│                                      output=stdout, stderr=stderr)
       526│     return CompletedProcess(process.args, retcode, stdout, stderr)
       527│ 
       528│ 

The following error occurred when trying to handle this error:


  Stack trace:

  3  ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/pip.py:56 in pip_install
       54│ 
       55│     try:
    →  56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
       58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e

  2  ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1497 in run_pip
      1495│         pip = self.get_pip_command()
      1496│         cmd = pip + list(args)
    → 1497│         return self._run(cmd, **kwargs)
      1498│ 
      1499│     def run_python_script(self, content: str, **kwargs: Any) -> int | str:

  1  ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1776 in _run
      1774│     def _run(self, cmd: list[str], **kwargs: Any) -> int | str:
      1775│         kwargs["env"] = self.get_temp_environ(environ=kwargs.get("env"))
    → 1776│         return super()._run(cmd, **kwargs)
      1777│ 
      1778│     def get_temp_environ(

  EnvCommandError

  Command ['/Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10', '--no-deps', '/Users/forcebru/Library/Caches/pypoetry/artifacts/a5/a8/9e/80306f8dda7dc4682a86897b5dfdc4d1c4444d5055260091388599b8ec/cyipopt-1.2.0.tar.gz'] errored with the following return code 1, and output: 
  Processing /Users/forcebru/Library/Caches/pypoetry/artifacts/a5/a8/9e/80306f8dda7dc4682a86897b5dfdc4d1c4444d5055260091388599b8ec/cyipopt-1.2.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'error'
    error: subprocess-exited-with-error
    
    × Getting requirements to build wheel did not run successfully.
    │ exit code: 1
    ╰─> [43 lines of output]
        /private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
          warnings.warn(
        /Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/bin/python: No module named pip
        Traceback (most recent call last):
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
            subprocess.check_call(cmd)
          File "/Users/forcebru/mambaforge/lib/python3.10/subprocess.py", line 369, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['/Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/tmp7dmcveqx', '--quiet', 'numpy>=1.15']' returned non-zero exit status 1.
        
        The above exception was the direct cause of the following exception:
        
        Traceback (most recent call last):
          File "/Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
            main()
          File "/Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
            return hook(config_settings)
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
            return self._get_build_requires(config_settings, requirements=['wheel'])
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
            self.run_setup()
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 26, in <module>
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
            resolved_dists = pkg_resources.working_set.resolve(
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 815, in resolve
            dist = self._resolve_dist(
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 851, in _resolve_dist
            dist = best[req.key] = env.best_match(
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1123, in best_match
            return self.obtain(req, installer)
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1135, in obtain
            return installer(requirement)
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
            return fetch_build_egg(self, req)
          File "/private/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/pip-build-env-ii3hxfut/overlay/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
            raise DistutilsError(str(e)) from e
        distutils.errors.DistutilsError: Command '['/Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/bin/python', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/var/folders/ys/3h0gnqns4b98zb66_vl_m35m0000gn/T/tmp7dmcveqx', '--quiet', 'numpy>=1.15']' returned non-zero exit status 1.
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│ 
      1542│         return decode(output)
      1543│ 
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  Stack trace:

  5  ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/executor.py:263 in _execute_operation
      261│ 
      262│             try:
    → 263│                 result = self._do_execute_operation(operation)
      264│             except EnvCommandError as e:
      265│                 if e.e.returncode == -2:

  4  ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/executor.py:334 in _do_execute_operation
      332│             return 0
      333│ 
    → 334│         result: int = getattr(self, f"_execute_{method}")(operation)
      335│ 
      336│         if result != 0:

  3  ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/executor.py:454 in _execute_install
      452│ 
      453│     def _execute_install(self, operation: Install | Update) -> int:
    → 454│         status_code = self._install(operation)
      455│ 
      456│         self._save_url_reference(operation)

  2  ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/executor.py:496 in _install
      494│         )
      495│         self._write(operation, message)
    → 496│         return self.pip_install(archive, upgrade=operation.job_type == "update")
      497│ 
      498│     def _update(self, operation: Install | Update) -> int:

  1  ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/executor.py:125 in pip_install
      123│     ) -> int:
      124│         try:
    → 125│             pip_install(req, self._env, upgrade=upgrade, editable=editable)
      126│         except EnvCommandError as e:
      127│             output = decode(e.e.output)

  PoetryException

  Failed to install /Users/forcebru/Library/Caches/pypoetry/artifacts/a5/a8/9e/80306f8dda7dc4682a86897b5dfdc4d1c4444d5055260091388599b8ec/cyipopt-1.2.0.tar.gz

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/pip.py:58 in pip_install
       54│ 
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│ 

  • Installing cython (0.29.33): Pending...
  • Installing cython (0.29.33): Skipped for the following reason: Already installed
  • Installing setuptools (66.0.0): Pending...
  • Installing setuptools (66.0.0): Skipped for the following reason: Already installed
  • Installing numpy (1.24.1): Pending...
  • Installing numpy (1.24.1): Skipped for the following reason: Already installed
(test-py3.10) forcebru test %
```

Among other things, this says:

    /Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/bin/python: No module named pip

However, it's not true:

```
(test-py3.10) forcebru test % /Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/bin/python -m pip --version
pip 22.3.1 from /Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/lib/python3.10/site-packages/pip (python 3.10)
(test-py3.10) forcebru test %
```

--------

Is this a problem with the cyipopt package? I can install other packages without issues. I can install cyipopt "manually" in the same virtual environment using the supposedly missing `pip`:

```
(test-py3.10) forcebru test % /Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/bin/python -m pip install cyipopt
Collecting cyipopt
  Downloading cyipopt-1.2.0.tar.gz (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.4/46.4 kB 271.0 kB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: cython>=0.26 in /Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/lib/python3.10/site-packages (from cyipopt) (0.29.33)
Requirement already satisfied: numpy>=1.15 in /Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/lib/python3.10/site-packages (from cyipopt) (1.24.1)
Requirement already satisfied: setuptools>=39.0 in /Users/forcebru/Library/Caches/pypoetry/virtualenvs/test-cZeh_li5-py3.10/lib/python3.10/site-packages (from cyipopt) (66.0.0)
Building wheels for collected packages: cyipopt
  Building wheel for cyipopt (setup.py) ... done
  Created wheel for cyipopt: filename=cyipopt-1.2.0-cp310-cp310-macosx_10_9_x86_64.whl size=124510 sha256=361271a7e43d054e0bec92be2fba6583506557da1ecc2c284cafa81399b21460
  Stored in directory: /Users/forcebru/Library/Caches/pip/wheels/b6/c0/ef/b548bbaab05bc456720930fa4cc28a20ca9ce9c50cea99907e
Successfully built cyipopt
Installing collected packages: cyipopt
Successfully installed cyipopt-1.2.0
(test-py3.10) forcebru test % 
```

Then Poetry detects it and I can technically go about my day, but is this how it's supposed to work? I don't think so: I ended up using `pip`, thus doing Poetry's job myself.

**Comment by dimbleby** [comment]
`pip install --use-pep517 cyipopt` gives the same result.  You should take this to cyiopt.

**Comment by ForceBru** [comment]
@dimbleby, is it possible to make Poetry run pip _without_ `--use-pip517` for a particular package?

**Comment by dimbleby** [comment]
no
