### ISSUE TITLE
Poetry raises exceptions with Python 3.10.x 

### ISSUE THREAD

**Issue by dongchirua** [python-poetry/poetry#7397]
- **Poetry version**: 1.1.7
- **Python version**:  3.10.9
- **OS version and name**: MacOS 13.1, M1 chip
- **Conda version**: 22.11.1

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.

## Issue
I have install poetry from conda. After installation, regardless of which option I used (`poetry -V`, `poetry shell`, etc.), poetry keeps raising an exception. For example,

```
Traceback (most recent call last):
  File "/Users/bryan/miniconda3/bin/poetry", line 7, in <module>
    from poetry.console import main
  File "/Users/bryan/miniconda3/lib/python3.10/site-packages/poetry/console/__init__.py", line 1, in <module>
    from .application import Application
  File "/Users/bryan/miniconda3/lib/python3.10/site-packages/poetry/console/application.py", line 7, in <module>
    from .commands.about import AboutCommand
  File "/Users/bryan/miniconda3/lib/python3.10/site-packages/poetry/console/commands/__init__.py", line 2, in <module>
    from .add import AddCommand
  File "/Users/bryan/miniconda3/lib/python3.10/site-packages/poetry/console/commands/add.py", line 8, in <module>
    from .init import InitCommand
  File "/Users/bryan/miniconda3/lib/python3.10/site-packages/poetry/console/commands/init.py", line 16, in <module>
    from poetry.core.pyproject import PyProjectException
ImportError: cannot import name 'PyProjectException' from 'poetry.core.pyproject' (/Users/bryan/miniconda3/lib/python3.10/site-packages/poetry/core/pyproject/__init__.py)
```

**Comment by neersighted** [comment]
You're on a very old version of Poetry, and more importantly, it looks like you have a slightly broken installation with a mismatched poetry-core. Please update Poetry and try to reproduce there; you should have no issues on recent versions.
