### ISSUE TITLE
not able to add onnx subdependency as part of the install

### ISSUE THREAD

**Issue by felixgao** [python-poetry/poetry#7446]
- **Poetry version**: 1.3.2
- **Python version**: 
- Poetry
Version: 1.3.2
Python:  3.10.9

Virtualenv
Python:         3.10.9
Implementation: CPython
Path:           /Users/ggao/github/ged/libs/ocr/.venv
Executable:     /Users/ggao/github/ged/libs/ocr/.venv/bin/python
Valid:          True

System
Platform:   darwin
OS:         posix
Python:     3.10.9
Path:       /Users/ggao/.pyenv/versions/3.10.9
Executable: /Users/ggao/.pyenv/versions/3.10.9/bin/python3.10

- **OS version and name**:  macOS 13.2
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I am trying to add a new dependency to my pyproject.toml but it fails with the current version of poetry/python.  I was able to install with pip but 
```
> poetry add paddlepaddle
....
Package operations: 4 installs, 1 update, 0 removals

  • Updating onnx (1.13.0 -> 1.12.0): Failed
  CalledProcessError

  Command '['/Users/ggao/github/ged/libs/ocr/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/ggao/github/ged/libs/ocr/.venv', '--upgrade', '--no-deps', '/Users/ggao/Library/Caches/pypoetry/artifacts/8d/90/16/bdef24060239697e9cbc170a44e400ed5bf86285722386bf9b548ab102/onnx-1.12.0.tar.gz']' returned non-zero exit status 1.
  at  ~/.pyenv/versions/3.10.9/lib/python3.10/subprocess.py:526 in run
       522│             # We don't call process.wait() as .__exit__ does that for us.
       523│             raise
       524│         retcode = process.poll()
       525│         if check and retcode:
    →  526│             raise CalledProcessError(retcode, process.args,
       527│                                      output=stdout, stderr=stderr)
       528│     return CompletedProcess(process.args, retcode, stdout, stderr)
       529│
       530│

  CalledProcessError

 Command '['/Users/ggao/github/ged/libs/ocr/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/ggao/github/ged/libs/ocr/.venv', '--upgrade', '--no-deps', '/Users/ggao/Library/Caches/pypoetry/artifacts/8d/90/16/bdef24060239697e9cbc170a44e400ed5bf86285722386bf9b548ab102/onnx-1.12.0.tar.gz']' returned non-zero exit status 1.

  at ~/.pyenv/versions/3.9.13/lib/python3.9/subprocess.py:528 in run
       524│             # We don't call process.wait() as .__exit__ does that for us.
       525│             raise
       526│         retcode = process.poll()
       527│         if check and retcode:
    →  528│             raise CalledProcessError(retcode, process.args,
       529│                                      output=stdout, stderr=stderr)
       530│     return CompletedProcess(process.args, retcode, stdout, stderr)
       531│
       532│

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/Users/ggao/github/ged/libs/ocr/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/Users/ggao/github/ged/libs/ocr/.venv', '--upgrade', '--no-deps', '/Users/ggao/Library/Caches/pypoetry/artifacts/8d/90/16/bdef24060239697e9cbc170a44e400ed5bf86285722386bf9b548ab102/onnx-1.12.0.tar.gz'] errored with the following return code 1, and output:
  Processing /Users/ggao/Library/Caches/pypoetry/artifacts/8d/90/16/bdef24060239697e9cbc170a44e400ed5bf86285722386bf9b548ab102/onnx-1.12.0.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Installing backend dependencies: started
    Installing backend dependencies: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'done'
  Building wheels for collected packages: onnx
    Building wheel for onnx (pyproject.toml): started
    Building wheel for onnx (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error

    × Building wheel for onnx (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [86 lines of output]
        fatal: not a git repository (or any of the parent directories): .git
        running bdist_wheel
        running build
        running build_py
        running create_version
        running cmake_build
        Using cmake args: ['/opt/homebrew/bin/cmake', '-DPYTHON_INCLUDE_DIR=/Users/ggao/.pyenv/versions/3.10.9/include/python3.10', '-DPYTHON_EXECUTABLE=/Users/ggao/github/ged/libs/ocr/.venv/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-darwin.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-req-build-m9v608gd']
        -- The C compiler identification is AppleClang 14.0.0.14000029
        -- The CXX compiler identification is AppleClang 14.0.0.14000029
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc - skipped
        -- Detecting C compile features
        -- Detecting C compile features - done
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ - skipped
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        -- Found PythonInterp: /Users/ggao/github/ged/libs/ocr/.venv/bin/python (found version "3.10.9")
        -- Found PythonLibs: /opt/homebrew/Frameworks/Python.framework/Versions/3.11/lib/libpython3.11.dylib (found version "3.10.9")
        Generated: /private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-req-build-m9v608gd/.setuptools-cmake-build/onnx/onnx-ml.proto
        CMake Error at CMakeLists.txt:299 (message):
          Protobuf compiler not found
        Call Stack (most recent call first):
          CMakeLists.txt:330 (relative_protobuf_generate_cpp)


        -- Configuring incomplete, errors occurred!
        See also "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-req-build-m9v608gd/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
        See also "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-req-build-m9v608gd/.setuptools-cmake-build/CMakeFiles/CMakeError.log".
        Traceback (most recent call last):
          File "/Users/ggao/github/ged/libs/ocr/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
            main()
          File "/Users/ggao/github/ged/libs/ocr/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/Users/ggao/github/ged/libs/ocr/.venv/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 249, in build_wheel
            return _build_backend().build_wheel(wheel_directory, config_settings,
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 413, in build_wheel
            return self._build_with_temp_dir(['bdist_wheel'], '.whl',
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 398, in _build_with_temp_dir
            self.run_setup()
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 484, in run_setup
            super(_BuildMetaLegacyBackend,
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
            exec(code, locals())
          File "<string>", line 332, in <module>
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/__init__.py", line 108, in setup
            return distutils.core.setup(**attrs)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
            super().run_command(command)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/wheel/bdist_wheel.py", line 325, in run
            self.run_command("build")
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
            super().run_command(command)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/command/build.py", line 132, in run
            self.run_command(cmd_name)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
            super().run_command(command)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "<string>", line 223, in run
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 318, in run_command
            self.distribution.run_command(command)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/dist.py", line 1213, in run_command
            super().run_command(command)
          File "/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-build-env-2brlsgot/overlay/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "<string>", line 209, in run
          File "/Users/ggao/.pyenv/versions/3.10.9/lib/python3.10/subprocess.py", line 369, in check_call
            raise CalledProcessError(retcode, cmd)
        subprocess.CalledProcessError: Command '['/opt/homebrew/bin/cmake', '-DPYTHON_INCLUDE_DIR=/Users/ggao/.pyenv/versions/3.10.9/include/python3.10', '-DPYTHON_EXECUTABLE=/Users/ggao/github/ged/libs/ocr/.venv/bin/python', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cpython-310-darwin.so', '-DCMAKE_BUILD_TYPE=Release', '-DONNX_ML=1', '/private/var/folders/sh/yv_yy1f55t352j55wrvwzwsc0000gq/T/pip-req-build-m9v608gd']' returned non-zero exit status 1.
        [end of output]

    note: This error originates from a subprocess, and is likely not a problem with pip.
    ERROR: Failed building wheel for onnx
  Failed to build onnx
  ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects


  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│
      1542│         return decode(output)
      1543│
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /Users/ggao/Library/Caches/pypoetry/artifacts/8d/90/16/bdef24060239697e9cbc170a44e400ed5bf86285722386bf9b548ab102/onnx-1.12.0.tar.gz

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/utils/pip.py:58 in pip_install
       54│
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│
```

the dependency seems to be able to add fine with pip

```
❯ poetry run pip install paddlepaddle
Collecting paddlepaddle
  Using cached paddlepaddle-2.4.1-cp310-cp310-macosx_11_0_arm64.whl (46.9 MB)
Requirement already satisfied: Pillow in /Users/ggao/intuit/github/ged/GED_MONOREPO/libs/ocr/.venv/lib/python3.10/site-packages (from paddlepaddle) (9.4.0)
Collecting opt-einsum==3.3.0
  Using cached opt_einsum-3.3.0-py3-none-any.whl (65 kB)
Requirement already satisfied: protobuf<=3.20.0,>=3.1.0 in /Users/ggao/intuit/github/ged/GED_MONOREPO/libs/ocr/.venv/lib/python3.10/site-packages (from paddlepaddle) (3.19.6)
Requirement already satisfied: six in /Users/ggao/intuit/github/ged/GED_MONOREPO/libs/ocr/.venv/lib/python3.10/site-packages (from paddlepaddle) (1.16.0)
Collecting astor
  Using cached astor-0.8.1-py2.py3-none-any.whl (27 kB)
Requirement already satisfied: numpy>=1.13 in /Users/ggao/intuit/github/ged/GED_MONOREPO/libs/ocr/.venv/lib/python3.10/site-packages (from paddlepaddle) (1.24.1)
Collecting paddle-bfloat==0.1.7
  Using cached paddle_bfloat-0.1.7-cp310-cp310-macosx_11_0_arm64.whl (41 kB)
Requirement already satisfied: requests>=2.20.0 in /Users/ggao/intuit/github/ged/GED_MONOREPO/libs/ocr/.venv/lib/python3.10/site-packages (from paddlepaddle) (2.28.2)
Requirement already satisfied: decorator in /Users/ggao/intuit/github/ged/GED_MONOREPO/libs/ocr/.venv/lib/python3.10/site-packages (from paddlepaddle) (5.1.1)
Requirement already satisfied: idna<4,>=2.5 in /Users/ggao/intuit/github/ged/GED_MONOREPO/libs/ocr/.venv/lib/python3.10/site-packages (from requests>=2.20.0->paddlepaddle) (3.4)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /Users/ggao/intuit/github/ged/GED_MONOREPO/libs/ocr/.venv/lib/python3.10/site-packages (from requests>=2.20.0->paddlepaddle) (1.26.14)
Requirement already satisfied: charset-normalizer<4,>=2 in /Users/ggao/intuit/github/ged/GED_MONOREPO/libs/ocr/.venv/lib/python3.10/site-packages (from requests>=2.20.0->paddlepaddle) (3.0.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/ggao/intuit/github/ged/GED_MONOREPO/libs/ocr/.venv/lib/python3.10/site-packages (from requests>=2.20.0->paddlepaddle) (2022.12.7)
Installing collected packages: paddle-bfloat, opt-einsum, astor, paddlepaddle
Successfully installed astor-0.8.1 opt-einsum-3.3.0 paddle-bfloat-0.1.7 paddlepaddle-2.4.1
```

**Comment by dimbleby** [comment]
Such things are nearly always because the package in question is not correctly set up for PEP517 builds

You can verify with something like:
```
pip install --no-cache --use-pep517 --no-binary onnx onnx
```
which I expect to fail in the same way (without poetry being involved)

**Comment by dimbleby** [comment]
not a poetry bug, should be closed
