### ISSUE TITLE
NoSuchOptionException when running `poetry env remove --all`

### ISSUE THREAD

**Issue by iharsuvorau** [python-poetry/poetry#7457]
- **Poetry version**: 1.3.2
- **Python version**: Python 3.9.16 (main, Dec  7 2022, 10:06:04), [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
- **OS version and name**: macOS 13.2 Ventura (ARM64)
- **pyproject.toml**: Not relevant. The issue is in CLI

On `poetry env remove --all` I get NoSuchOptionException. According to https://python-poetry.org/docs/managing-environments/#deleting-the-environments, there is such an option.

```
simod on  master [$?] is 📦 v3.2.0 via ☕ v1.8.0 via 🐍 v3.9.16 
❯ poetry env list        
simod-oF6EjPXs-py3.9

simod on  master [$?] is 📦 v3.2.0 via ☕ v1.8.0 via 🐍 v3.9.16 
❯ poetry env remove --all

  Stack trace:

  11  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/console_application.py:123 in run
      io = io_factory(

  10  ~/.poetry/lib/poetry/console/config/application_config.py:221 in create_io
      resolved_command = application.resolve_command(args)

   9  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/console_application.py:110 in resolve_command
      return self._config.command_resolver.resolve(args, self)

   8  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/resolver/default_resolver.py:34 in resolve
      return self.create_resolved_command(result)

   7  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/resolver/default_resolver.py:166 in create_resolved_command
      if not result.is_parsable():

   6  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/resolver/resolve_result.py:43 in is_parsable
      self._parse()

   5  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/resolver/resolve_result.py:49 in _parse
      self._parsed_args = self._command.parse(self._raw_args)

   4  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/api/command/command.py:113 in parse
      return self._config.args_parser.parse(args, self._args_format, lenient)

   3  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/args/default_args_parser.py:53 in parse
      self._parse(args, _fmt, lenient)

   2  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/args/default_args_parser.py:101 in _parse
      self._parse_long_option(token, tokens, fmt, lenient)

   1  ~/.poetry/lib/poetry/_vendor/py3.9/clikit/args/default_args_parser.py:247 in _parse_long_option
      self._add_long_option(name, None, tokens, fmt, lenient)

  NoSuchOptionException

  The "--all" option does not exist.

  at ~/.poetry/lib/poetry/_vendor/py3.9/clikit/args/default_args_parser.py:300 in _add_long_option
      296│     def _add_long_option(
      297│         self, name, value, tokens, fmt, lenient
      298│     ):  # type: (str, Optional[str], List[str], ArgsFormat, bool) -> None
      299│         if not fmt.has_option(name):
    → 300│             raise NoSuchOptionException(name)
      301│ 
      302│         option = fmt.get_option(name)
      303│ 
      304│         if value is False:

```

**Comment by finswimmer** [comment]
What's the output of `poetry --version` and `poetry env remove  --help`?

**Comment by dimbleby** [comment]
presence of clikit in the call stack shows that it's not a recent poetry

**Comment by iharsuvorau** [comment]
It now looks a bit weird.

```
❯ poetry --version         
Poetry version 1.1.13
```

```
❯ poetry env remove  --help
USAGE
  poetry env remove <python>

ARGUMENTS
  <python>               The python executable to remove the virtualenv for.

GLOBAL OPTIONS
  -h (--help)            Display this help message
  -q (--quiet)           Do not output any message
  -v (--verbose)         Increase the verbosity of messages: "-v" for normal output, "-vv" for more verbose output and "-vvv" for debug
  -V (--version)         Display this application version
  --ansi                 Force ANSI output
  --no-ansi              Disable ANSI output
  -n (--no-interaction)  Do not ask any interactive question
```

Upgrading `poetry` finishes successfully:
```
❯ pip install -U poetry       
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
Requirement already satisfied: poetry in /opt/homebrew/lib/python3.9/site-packages (1.3.2)
Requirement already satisfied: crashtest<0.5.0,>=0.4.1 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (0.4.1)
Requirement already satisfied: tomlkit!=0.11.2,!=0.11.3,<1.0.0,>=0.11.1 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (0.11.6)
Requirement already satisfied: dulwich<0.21.0,>=0.20.46 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (0.20.50)
Requirement already satisfied: packaging>=20.4 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (22.0)
Requirement already satisfied: shellingham<2.0,>=1.5 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (1.5.0.post1)
Requirement already satisfied: html5lib<2.0,>=1.0 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (1.1)
Requirement already satisfied: urllib3<2.0.0,>=1.26.0 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (1.26.12)
Requirement already satisfied: importlib-metadata<5.0,>=4.4 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (4.12.0)
Requirement already satisfied: filelock<4.0.0,>=3.8.0 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (3.9.0)
Requirement already satisfied: platformdirs<3.0.0,>=2.5.2 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (2.6.2)
Requirement already satisfied: poetry-plugin-export<2.0.0,>=1.2.0 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (1.3.0)
Requirement already satisfied: trove-classifiers>=2022.5.19 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (2023.1.20)
Requirement already satisfied: requests<3.0,>=2.18 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (2.28.2)
Requirement already satisfied: poetry-core==1.4.0 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (1.4.0)
Requirement already satisfied: pexpect<5.0.0,>=4.7.0 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (4.8.0)
Requirement already satisfied: requests-toolbelt<0.11.0,>=0.9.1 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (0.9.1)
Requirement already satisfied: lockfile<0.13.0,>=0.12.2 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (0.12.2)
Requirement already satisfied: pkginfo<2.0,>=1.5 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (1.9.6)
Requirement already satisfied: tomli<3.0.0,>=2.0.1 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (2.0.1)
Requirement already satisfied: cachecontrol[filecache]<0.13.0,>=0.12.9 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (0.12.11)
Requirement already satisfied: cleo<3.0.0,>=2.0.0 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (2.0.1)
Requirement already satisfied: keyring<24.0.0,>=23.9.0 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (23.13.1)
Requirement already satisfied: virtualenv!=20.4.5,!=20.4.6,<21.0.0,>=20.4.3 in /Users/ihar/Library/Python/3.9/lib/python/site-packages (from poetry) (20.13.3)
Requirement already satisfied: jsonschema<5.0.0,>=4.10.0 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (4.16.0)
Requirement already satisfied: xattr<0.11.0,>=0.10.0 in /opt/homebrew/lib/python3.9/site-packages (from poetry) (0.10.1)
Requirement already satisfied: msgpack>=0.5.2 in /opt/homebrew/lib/python3.9/site-packages (from cachecontrol[filecache]<0.13.0,>=0.12.9->poetry) (1.0.4)
Requirement already satisfied: rapidfuzz<3.0.0,>=2.2.0 in /opt/homebrew/lib/python3.9/site-packages (from cleo<3.0.0,>=2.0.0->poetry) (2.13.7)
Requirement already satisfied: six>=1.9 in /opt/homebrew/lib/python3.9/site-packages (from html5lib<2.0,>=1.0->poetry) (1.16.0)
Requirement already satisfied: webencodings in /opt/homebrew/lib/python3.9/site-packages (from html5lib<2.0,>=1.0->poetry) (0.5.1)
Requirement already satisfied: zipp>=0.5 in /opt/homebrew/lib/python3.9/site-packages (from importlib-metadata<5.0,>=4.4->poetry) (3.8.1)
Requirement already satisfied: pyrsistent!=0.17.0,!=0.17.1,!=0.17.2,>=0.14.0 in /opt/homebrew/lib/python3.9/site-packages (from jsonschema<5.0.0,>=4.10.0->poetry) (0.18.1)
Requirement already satisfied: attrs>=17.4.0 in /opt/homebrew/lib/python3.9/site-packages (from jsonschema<5.0.0,>=4.10.0->poetry) (21.4.0)
Requirement already satisfied: jaraco.classes in /opt/homebrew/lib/python3.9/site-packages (from keyring<24.0.0,>=23.9.0->poetry) (3.2.3)
Requirement already satisfied: ptyprocess>=0.5 in /opt/homebrew/lib/python3.9/site-packages (from pexpect<5.0.0,>=4.7.0->poetry) (0.7.0)
Requirement already satisfied: certifi>=2017.4.17 in /opt/homebrew/lib/python3.9/site-packages (from requests<3.0,>=2.18->poetry) (2022.9.14)
Requirement already satisfied: idna<4,>=2.5 in /opt/homebrew/lib/python3.9/site-packages (from requests<3.0,>=2.18->poetry) (3.4)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/homebrew/lib/python3.9/site-packages (from requests<3.0,>=2.18->poetry) (2.1.1)
Requirement already satisfied: distlib<1,>=0.3.1 in /Users/ihar/Library/Python/3.9/lib/python/site-packages (from virtualenv!=20.4.5,!=20.4.6,<21.0.0,>=20.4.3->poetry) (0.3.4)
Requirement already satisfied: cffi>=1.0 in /opt/homebrew/lib/python3.9/site-packages (from xattr<0.11.0,>=0.10.0->poetry) (1.15.1)
Requirement already satisfied: pycparser in /opt/homebrew/lib/python3.9/site-packages (from cffi>=1.0->xattr<0.11.0,>=0.10.0->poetry) (2.21)
Requirement already satisfied: more-itertools in /opt/homebrew/lib/python3.9/site-packages (from jaraco.classes->keyring<24.0.0,>=23.9.0->poetry) (9.0.0)
DEPRECATION: Configuring installation scheme with distutils config files is deprecated and will no longer work in the near future. If you are using a Homebrew or Linuxbrew Python, please see discussion at https://github.com/Homebrew/homebrew-core/issues/76621
```

However, after the upgrade the version printed by `poetry --version` is still the old one. But `pip` points to the newest version:
```
❯ poetry --version         
Poetry version 1.1.13
```

```
❯ pip list | grep poetry
poetry                     1.3.2
poetry-core                1.4.0
poetry-plugin-export       1.3.0
```

But, if I upgrade poetry with pip and open a new shell, then I see the newest poetry version for some time.
```
❯ poetry --version     
Poetry (version 1.3.2)
```

However, if I start working with poetry. For example, I wanted to update the package with `poetry update pix_utils`. After the operation, when I run `poetry --version`, I get the old version again. Here's the full shell input/output, so you can see what I typed and got in response:

```
simod on  small-refactors:refs/pull/96/head [$!?] is 📦 v3.2.0 via ☕ v1.8.0 via 🐍 v3.9.16 (simod-oF6EjPXs-py3.9) 
❯ poetry --version     
Poetry (version 1.3.2)

simod on  small-refactors:refs/pull/96/head [$!?] is 📦 v3.2.0 via ☕ v1.8.0 via 🐍 v3.9.16 (simod-oF6EjPXs-py3.9) 
❯ poetry env remove --all
Deleted virtualenv: /Users/ihar/Projects/PIX/simod/.venv
Deleted virtualenv: /Users/ihar/Library/Caches/pypoetry/virtualenvs/simod-oF6EjPXs-py3.9

simod on  small-refactors:refs/pull/96/head [$!?] is 📦 v3.2.0 via ☕ v1.8.0 via 🐍 v3.9.16 (simod-oF6EjPXs-py3.9) 
❯ CVXOPT_SUITESPARSE_SRC_DIR=/Users/ihar/Projects/PIX/simod/external_tools/SuiteSparse CVXOPT_BUILD_GLPK=1 CVXOPT_GLPK_LIB_DIR=/opt/homebrew/Cellar/glpk/5.0/lib CVXOPT_GLPK_INC_DIR=/opt/homebrew/Cellar/glpk/5.0/include poetry install
Creating virtualenv simod-oF6EjPXs-py3.9 in /Users/ihar/Library/Caches/pypoetry/virtualenvs
Installing dependencies from lock file

Package operations: 80 installs, 0 updates, 0 removals

  • Installing idna (3.4)
  • Installing numpy (1.24.1)
  • Installing packaging (23.0)
  • Installing six (1.16.0)
  • Installing sniffio (1.3.0)
  • Installing tomli (2.0.1)
  • Installing typing-extensions (4.4.0)
  • Installing anyio (3.6.2)
  • Installing attrs (22.2.0)
  • Installing contourpy (1.0.7)
  • Installing cycler (0.11.0)
  • Installing exceptiongroup (1.1.0)
  • Installing fonttools (4.38.0)
  • Installing iniconfig (2.0.0)
  • Installing kiwisolver (1.4.4)
  • Installing pillow (9.4.0)
  • Installing pluggy (1.0.0)
  • Installing pyparsing (3.0.9)
  • Installing python-dateutil (2.8.2)
  • Installing pytz (2022.7.1)
  • Installing setuptools-scm (7.1.0)
  • Installing sortedcontainers (2.4.0)
  • Installing cloudpickle (2.2.1)
  • Installing coverage (7.1.0)
  • Installing cvxopt (1.3.0): Installing...
  • Installing deprecation (2.1.0)
  • Installing distlib (0.3.6)
  • Installing docutils (0.19)
  • Installing filelock (3.9.0)
  • Installing deprecation (2.1.0)
  • Installing distlib (0.3.6)
  • Installing docutils (0.19)
  • Installing filelock (3.9.0)
  • Installing cvxopt (1.3.0)
  • Installing deprecation (2.1.0)
  • Installing distlib (0.3.6)
  • Installing docutils (0.19)
  • Installing filelock (3.9.0)
  • Installing future (0.18.3)
  • Installing graphviz (0.20.1)
  • Installing intervaltree (3.1.0)
  • Installing lxml (4.9.2)
  • Installing matplotlib (3.6.3)
  • Installing networkx (2.8.8)
  • Installing pandas (1.5.3)
  • Installing platformdirs (2.6.2)
  • Installing py4j (0.10.9.7)
  • Installing pydantic (1.10.4)
  • Installing pydotplus (2.0.2)
  • Installing pytest (7.2.1)
  • Installing scipy (1.9.3)
  • Installing starlette (0.22.0)
  • Installing stringdist (1.0.9)
  • Installing tqdm (4.64.1)
  • Installing certifi (2022.12.7)
  • Installing cfgv (3.3.1)
  • Installing charset-normalizer (3.0.1): Installing...
  • Installing charset-normalizer (3.0.1)
  • Installing click (8.1.3)
  • Installing dtw (1.4.0)
  • Installing fastapi (0.89.1)
  • Installing h11 (0.14.0)
  • Installing hyperopt (0.2.7)
  • Installing identify (2.5.15)
  • Installing jellyfish (0.9.0)
  • Installing nodeenv (1.7.0)
  • Installing pm4py (2.3.4)
  • Installing pytest-cov (3.0.0)
  • Installing pytzdata (2020.1)
  • Installing pyyaml (6.0)
  • Installing simpy (4.0.1)
  • Installing sqlalchemy (1.4.46)
  • Installing statistics (1.0.3.5)
  • Installing urllib3 (1.26.14)
  • Installing virtualenv (20.17.1)
  • Installing diffresbp-simulator (0.1.0 db0e1f0)
  • Installing estimate-start-times (1.7.0 1dca546)
  • Installing fastapi-utils (0.2.1)
  • Installing invoke (1.7.3)
  • Installing log-similarity-metrics (0.8.0 a86603f)
  • Installing pendulum (2.1.2)
  • Installing extraneous-activity-delays (1.3.2 20ca322)
  • Installing pix-utils (0.4.0 f252cab)
  • Installing pm4py-wrapper (1.3.0 6e3ef05)
  • Installing pre-commit (2.21.0)
  • Installing python-dotenv (0.21.1)
  • Installing python-multipart (0.0.5)
  • Installing requests (2.28.2)
  • Installing uvicorn (0.20.0)
  • Installing xmltodict (0.13.0)

Installing the current project: simod (3.2.0)

simod on  small-refactors:refs/pull/96/head [$!?] is 📦 v3.2.0 via ☕ v1.8.0 via 🐍 v3.9.16 (simod-oF6EjPXs-py3.9) took 55s 
❯ simod --help                                            
Traceback (most recent call last):
  File "/opt/homebrew/bin/simod", line 5, in <module>
    from simod.cli import main
  File "/Users/ihar/Projects/PIX/simod/src/simod/cli.py", line 6, in <module>
    from simod.event_log.event_log import EventLog
  File "/Users/ihar/Projects/PIX/simod/src/simod/event_log/event_log.py", line 4, in <module>
    from pix_utils.log_split.log_split import split_log_training_validation_trace_wise as split_log
ModuleNotFoundError: No module named 'pix_utils.log_split'

simod on  small-refactors:refs/pull/96/head [$!?] is 📦 v3.2.0 via ☕ v1.8.0 via 🐍 v3.9.16 (simod-oF6EjPXs-py3.9) 
❯ poetry add pix_utils   
The following packages are already present in the pyproject.toml and will be skipped:

  • pix_utils

If you want to update it to the latest compatible version, you can use `poetry update package`.
If you prefer to upgrade it to the latest available version, you can use `poetry add package@latest`.

Nothing to add.

simod on  small-refactors:refs/pull/96/head [$!?] is 📦 v3.2.0 via ☕ v1.8.0 via 🐍 v3.9.16 (simod-oF6EjPXs-py3.9) 
❯ poetry add pix_utils@0.4.0

  ValueError

  Could not find a matching version of package pix_utils

  at ~/.poetry/lib/poetry/console/commands/init.py:367 in _find_best_version_for_package
      363│         )
      364│ 
      365│         if not package:
      366│             # TODO: find similar
    → 367│             raise ValueError(
      368│                 "Could not find a matching version of package {}".format(name)
      369│             )
      370│ 
      371│         return package.pretty_name, selector.find_recommended_require_version(package)

simod on  small-refactors:refs/pull/96/head [$!?] is 📦 v3.2.0 via ☕ v1.8.0 via 🐍 v3.9.16 (simod-oF6EjPXs-py3.9) 
❯ poetry update pix_utils   
Updating dependencies
Resolving dependencies... (97.3s)

No dependencies to install or update

simod on  small-refactors:refs/pull/96/head [$!?] is 📦 v3.2.0 via ☕ v1.8.0 via 🐍 v3.9.16 (simod-oF6EjPXs-py3.9) took 1m39s 
❯ poetry --version       
Poetry version 1.1.13
```

All the commands above were typed in the same shell session. In the beginning the version was 1.3.2, at the end, it's 1.1.13. Could it be something with the caching?

**Comment by finswimmer** [comment]
Hey,

I guess you have multiple installations of Poetry, installed in different ways (pip, old get-poetry.py script, official installer). Find all those installations (`which -a poetry` might be useful), remove them and install Poetry with the recommended installer.

fin swimmer

**Comment by iharsuvorau** [comment]
> Hey,
> 
> I guess you have multiple installations of Poetry, installed in different ways (pip, old get-poetry.py script, official installer). Find all those installations (`which -a poetry` might be useful), remove them and install Poetry with the recommended installer.
> 
> fin swimmer

Hey, thanks! No confusion with the versions now. I had 2 installations: in `~/.poetry/bin` and `/opt/homebrew/bin`. Removed the former with `rm -rf ~/.poetry`. Everything is good so far. 🙇
