### ISSUE TITLE
I have a package, I created it with poetry, I wanted to install it as editable package by using pip, I got error

### ISSUE THREAD

**Issue by yingshaoxo** [python-poetry/poetry#7741]
Here is the error:
```
❯ python3 -m pip install -e .
Obtaining file:///Users/yingshaoxo/CS/auto_everything
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Preparing editable metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/opt/homebrew/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 181, in prepare_metadata_for_build_editable
          return hook(metadata_directory, config_settings)
        File "/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
          poetry = Factory().create_poetry(Path(".").resolve(), with_dev=False)
        File "/opt/homebrew/Cellar/python@3.10/3.10.10/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/poetry/core/factory.py", line 43, in create_poetry
          raise RuntimeError("The Poetry configuration is invalid:\n" + message)
      RuntimeError: The Poetry configuration is invalid:
        - Additional properties are not allowed ('group' was unexpected)
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

Here is the package pyproject.toml content:
```
[tool.poetry]
name = "auto-everything"
version = "3.19"
description = "do automate things on Linux"
authors = ["yingshaoxo <yingshaoxo@gmail.com>"]
license = "GPLv3"
readme = "README.md"
packages = [{include = "auto_everything"}]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.dependencies]
python = "^3.10"
psutil = "5.9.4"
fire = "0.5.0"

[tool.poetry.group.all]
optional = true

[tool.poetry.group.all.dependencies]
pytest = "^7.2.0"
ipykernel = "^6.19.2"
librosa = "^0.9.2"
moviepy = "^1.0.3"
vosk = "^0.3.44"
pydub = "^0.25.1"
py-dateutil = "^2.2"
opencv-python = "^4.7.0.68"
pyautogui = "^0.9.53"
python-telegram-bot = "^20.2"
#torch = "^2.0.0" #{url = "https://download.pytorch.org/whl/cpu/torch-1.13.0-cp310-none-macosx_11_0_arm64.whl"}
#torch = {url = "https://download.pytorch.org/whl/cpu/torch-1.13.0%2Bcpu-cp310-cp310-linux_x86_64.whl"}
#torch = {version = "^2.0.0+cpu", source = "pytorch-cpu"}
#torchaudio = "^0.13.0" 
#speechbrain = "^0.5.13"
#o365 = "^2.0.23"
#paddlepaddle = "^2.4.1"

[tool.poetry.scripts]
hi = "auto_everything._command_line_interface:_hi" # You can call 'hi' in everywhere from your terminal after you install this package
auto_everything = "auto_everything._command_line_interface:main"
```

___

** I think poetry as npm + package.json in javascript, pip as npm + install --globally **

**Comment by dimbleby** [comment]
you are picking up an old version of `poetry-core` from somewhere.  Try being explicit that you require a more recent version in the build-system requirements.
