### ISSUE TITLE
Metadata preparation failure using poetry add git+url

### ISSUE THREAD

**Issue by jademackay** [python-poetry/poetry#7831]
- **Poetry version**: Poetry (version 1.3.0)
- **Python version**: Python 3.10.10 
- **OS version and name**: NixOS (and MacOS 13.3)
- **pyproject.toml**: https://github.com/jademackay/poetry-add-issue/blob/main/pyproject.toml
-
- [ ] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
-  [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Metadata preparation failure using poetry add git+url. I am unable to install my poetry package using either
```
poetry init -i --name example
poetry add git+https://github.com/jademackay/poetry-add-issue.git
```
Nor by directly editing the `pyproject.toml` in this way
```
[tool.poetry.dependencies]
python = "^3.10"
poetry-add-issue = {git = "git@github.com:jademackay/poetry-add-issue.git", branch = "main"}
```
followed by `poetry install`.

I encounter an error relating to metadata preparation, excerpt:
```
  EnvCommandError

  Command ['/home/jade/.cache/pypoetry/virtualenvs/example-iNd1DgyF-py3.10/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/home/jade/.cache/pypoetry/virtualenvs/example-iNd1DgyF-py3.10', '--upgrade', '--no-deps', '/home/jade/.cache/pypoetry/virtualenvs/example-iNd1DgyF-py3.10/src/poetry-add-issue'] errored with the following return code 1, and output:
  Processing /home/jade/.cache/pypoetry/virtualenvs/example-iNd1DgyF-py3.10/src/poetry-add-issue
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error

    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
```

However, I can add the package from a local pre-built wheel:
```
mkdir /tmp
cd /tmp
git clone https://github.com/jademackay/poetry-add-issue.git
cd poetry-add-issue
poetry build
```
Back in our project edit pyproject.toml to include
```
[tool.poetry.dependencies]
python = "^3.10"
poetry-add-issue = {path = "/tmp/poetry-add-issue/dist/poetry_add_issue-0.1.0-py3-none-any.whl"}
```
then
```
poetry install
```
success!
```
poetry run yo
# yo! # as desired.
```

All this is described in the MWE here https://github.com/jademackay/poetry-add-issue.

Thanks in advance for your thoughts!

**Comment by dimbleby** [comment]
the modern solver in poetry 1.4 does not use this code branch at all, so I expect there to be little interest in digging into this.  Please use the latest poetry.

**Comment by jademackay** [comment]
Thanks @dimbleby . I have updated everything to poetry version 1.4.2 and, alas, am still experiencing the same issue. That is, installation from local `whl` file succeeds but installation from git, a la, `poetry-add-issue = {git = "git@github.com:jademackay/poetry-add-issue.git", branch = "main"}` fails. A fuller log below:

```
...
  • Installing scikit-learn (1.2.2)
  • Installing poetry-add-issue (0.1.0 2246184): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel

  Traceback (most recent call last):
    File "/nix/store/y0nvjq0s3f9b8dxrk6yazm17gfj93jl3-python3.10-pyproject-hooks-1.0.0/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/nix/store/y0nvjq0s3f9b8dxrk6yazm17gfj93jl3-python3.10-pyproject-hooks-1.0.0/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/nix/store/y0nvjq0s3f9b8dxrk6yazm17gfj93jl3-python3.10-pyproject-hooks-1.0.0/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
    File "/tmp/nix-shell.17lu13/tmpa62fexa5/.venv/lib/python3.10/site-packages/hatchling/build.py", line 56, in build_wheel
      return os.path.basename(next(builder.build(wheel_directory, ['standard'])))
    File "/tmp/nix-shell.17lu13/tmpa62fexa5/.venv/lib/python3.10/site-packages/hatchling/builders/plugin/interface.py", line 93, in build
      self.metadata.validate_fields()
    File "/tmp/nix-shell.17lu13/tmpa62fexa5/.venv/lib/python3.10/site-packages/hatchling/metadata/core.py", line 243, in validate_fields
      _ = self.version
    File "/tmp/nix-shell.17lu13/tmpa62fexa5/.venv/lib/python3.10/site-packages/hatchling/metadata/core.py", line 128, in version
      self._version = self._get_version()
    File "/tmp/nix-shell.17lu13/tmpa62fexa5/.venv/lib/python3.10/site-packages/hatchling/metadata/core.py", line 222, in _get_version
      core_metadata = self.core
    File "/tmp/nix-shell.17lu13/tmpa62fexa5/.venv/lib/python3.10/site-packages/hatchling/metadata/core.py", line 161, in core
      metadata = CoreMetadata(self.root, self.core_raw_metadata, self.hatch.metadata, self.context)
    File "/tmp/nix-shell.17lu13/tmpa62fexa5/.venv/lib/python3.10/site-packages/hatchling/metadata/core.py", line 79, in core_raw_metadata
      raise ValueError(message)
  ValueError: Missing `project` metadata table in configuration


  at /nix/store/rpw39qmar9wwpg5swh02gjwdlv3k7b0s-python3.10-poetry-1.4.2/lib/python3.10/site-packages/poetry/installation/chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

**Comment by jademackay** [comment]
Thanks @dimbleby , you are right. It's been a while since I have engaged with the Python eco-system and I appreciate the time you have given me on this.
