### ISSUE TITLE
Can't install Poetry on Debian

### ISSUE THREAD

**Issue by infiniityr** [python-poetry/poetry#7864]
- **Poetry version**: None
- **Python version**: 3.9
- **OS version and name**: Debian 11
- **pyproject.toml**: None

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I can't install poetry on Debian.
- OS : Debian 11
- Python version : 3.9
- Command executed : `curl -sSL https://install.python-poetry.org | python3 -`
- Output
```console
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/airflow/virtualenv.pyz/__main__.py", line 169, in <module>
  File "/home/airflow/virtualenv.pyz/__main__.py", line 165, in run
  File "/home/airflow/virtualenv.pyz/virtualenv/__main__.py", line 18, in run
  File "/home/airflow/virtualenv.pyz/virtualenv/run/__init__.py", line 30, in cli_run
  File "/home/airflow/virtualenv.pyz/virtualenv/run/__init__.py", line 48, in session_via_cli
  File "/home/airflow/virtualenv.pyz/virtualenv/run/__init__.py", line 74, in build_parser
  File "/home/airflow/virtualenv.pyz/virtualenv/run/plugin/creators.py", line 15, in __init__
  File "/home/airflow/virtualenv.pyz/virtualenv/run/plugin/creators.py", line 22, in for_interpreter
  File "/home/airflow/virtualenv.pyz/virtualenv/run/plugin/base.py", line 46, in options
  File "/home/airflow/virtualenv.pyz/virtualenv/run/plugin/base.py", line 25, in entry_points_for
  File "/home/airflow/virtualenv.pyz/virtualenv/run/plugin/base.py", line 25, in <genexpr>
  File "/usr/lib/python3.9/importlib/metadata.py", line 79, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'virtualenv.create.via_global_ref.builtin.cpython.mac_os' has no attribute 'CPython2macOsFramework'
```

Since the exception is in `Virutalenv`, I opened an issue on their repo : https://github.com/pypa/virtualenv/issues/2565

**Comment by dimbleby** [comment]
Something screwy about your python environment I expect.  Certainly lots of people install poetry on debian 11 successfully.

Seems very unlikely that this is an issue which can be solved from this repository.  

If you want to make this a poetry problem you will need do a bit more work to establish that it actually is a poetry problem, else please close.

**Comment by infiniityr** [comment]
It is not a poetry issue but a virtualenv issue
It can be bypassed by installing poetry from the sourcing instead of using the installer.

**Comment by jandd** [comment]
I just had the same issue on a system upgraded from Debian 10 to Debian 11.

`apt install python3-venv`

fixed the issue.
