### ISSUE TITLE
ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' 

### ISSUE THREAD

**Issue by jrjsmrtn** [python-poetry/poetry#7880]
- **Poetry version**: 1.4.2
- **Python version**: 3.9.2
- **OS version and name**: Debian GNU/LInux 11 (Bullseye)
- **pyproject.toml**: https://gist.github.com/jrjsmrtn/f0c5a9622236bfdaea6da9714f5f01bb

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

```
Loading configuration file /home/foo/.config/pypoetry/config.toml
Using virtualenv: /home/foo/.cache/pypoetry/virtualenvs/bar-G_ikZTXW-py3.9
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 100 installs, 1 update, 0 removals

  • Installing pycparser (2.21)
No suitable keyring backend found
No suitable keyring backends were found
Keyring is not available, credentials will be stored and retrieved from configuration files as plaintext.
Creating new session for pypi.org
  • Installing cffi (1.15.1)
Skipping wheel cffi-1.15.1-cp27-cp27m-macosx_10_9_x86_64.whl as this is not supported by the current environment
[...]
Skipping wheel cffi-1.15.1-cp39-cp39-win_amd64.whl as this is not supported by the current environment
  • Installing certifi (2022.12.7)
  • Installing charset-normalizer (3.1.0)
Skipping wheel charset_normalizer-3.1.0-cp310-cp310-macosx_10_9_universal2.whl as this is not supported by the current environment
[...]
Skipping wheel charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_ppc64le.manylinux2014_ppc64le.whl as this is not supported by the current environment
  • Installing idna (3.4)
Skipping wheel charset_normalizer-3.1.0-cp310-cp310-manylinux_2_17_s390x.manylinux2014_s390x.whl as this is not supported by the current environment
  • Installing jeepney (0.8.0)
Skipping wheel cryptography-40.0.2-cp36-abi3-manylinux_2_28_aarch64.whl as this is not supported by the current environment
[...]
Skipping wheel charset_normalizer-3.1.0-cp310-cp310-musllinux_1_1_ppc64le.whl as this is not supported by the current environment
  • Installing more-itertools (9.1.0)
Skipping wheel cryptography-40.0.2-pp38-pypy38_pp73-manylinux_2_28_aarch64.whl as this is not supported by the current environment
[...]
Skipping wheel charset_normalizer-3.1.0-cp310-cp310-musllinux_1_1_s390x.whl as this is not supported by the current environment
  • Installing tomli (2.0.1)
Skipping wheel cryptography-40.0.2-pp38-pypy38_pp73-win_amd64.whl as this is not supported by the current environment
  • Installing urllib3 (1.26.15)
[...]
Skipping wheel charset_normalizer-3.1.0-cp311-cp311-macosx_11_0_arm64.whl as this is not supported by the current environment
  • Installing zipp (3.15.0)
Skipping wheel charset_normalizer-3.1.0-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
[...]
Skipping wheel charset_normalizer-3.1.0-cp39-cp39-win_amd64.whl as this is not supported by the current environment
  • Installing attrs (23.1.0)
  • Installing crashtest (0.4.1)
  • Installing filelock (3.12.0)
  • Installing importlib-metadata (6.6.0)
  • Installing distlib (0.3.6)
  • Installing lockfile (0.12.2)
  • Installing jaraco-classes (3.2.3)
  • Installing markupsafe (2.1.2)
Skipping wheel MarkupSafe-2.1.2-cp310-cp310-macosx_10_9_universal2.whl as this is not supported by the current environment
[...]
Skipping wheel MarkupSafe-2.1.2-cp39-cp39-musllinux_1_1_i686.whl as this is not supported by the current environment
  • Installing msgpack (1.0.5)
Skipping wheel MarkupSafe-2.1.2-cp39-cp39-musllinux_1_1_x86_64.whl as this is not supported by the current environment
[...]
Skipping wheel msgpack-1.0.5-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
  • Installing packaging (23.1)
Skipping wheel msgpack-1.0.5-cp311-cp311-manylinux_2_17_x86_64.manylinux2014_x86_64.whl as this is not supported by the current environment
  • Installing platformdirs (2.6.2)
Skipping wheel msgpack-1.0.5-cp311-cp311-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl as this is not supported by the current environment
[...]
Skipping wheel msgpack-1.0.5-cp36-cp36m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl as this is not supported by the current environment
  • Installing poetry-core (1.5.2)
  • Installing ptyprocess (0.7.0)
Skipping wheel msgpack-1.0.5-cp36-cp36m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl as this is not supported by the current environment
[...]
Skipping wheel msgpack-1.0.5-cp39-cp39-win_amd64.whl as this is not supported by the current environment
  • Installing pyproject-hooks (1.0.0)
  • Installing pyrsistent (0.19.3)
Skipping wheel pyrsistent-0.19.3-cp310-cp310-macosx_10_9_universal2.whl as this is not supported by the current environment
[...]
Skipping wheel pyrsistent-0.19.3-cp39-cp39-win_amd64.whl as this is not supported by the current environment
  • Installing pytz (2023.3)
  • Installing rapidfuzz (2.15.1)
Skipping wheel rapidfuzz-2.15.1-cp310-cp310-macosx_10_9_universal2.whl as this is not supported by the current environment
[...]
Skipping wheel rapidfuzz-2.15.1-cp311-cp311-musllinux_1_1_ppc64le.whl as this is not supported by the current environment
  • Installing requests (2.30.0)
Skipping wheel rapidfuzz-2.15.1-cp311-cp311-musllinux_1_1_s390x.whl as this is not supported by the current environment
[...]
Skipping wheel rapidfuzz-2.15.1-pp38-pypy38_pp73-manylinux_2_17_i686.manylinux2014_i686.whl as this is not supported by the current environment
  • Installing secretstorage (3.3.3)
Skipping wheel rapidfuzz-2.15.1-pp38-pypy38_pp73-manylinux_2_17_x86_64.manylinux2014_x86_64.whl as this is not supported by the current environment
[...]
Skipping wheel rapidfuzz-2.15.1-pp39-pypy39_pp73-win_amd64.whl as this is not supported by the current environment
  • Installing six (1.16.0)
  • Installing webencodings (0.5.1)
  • Installing build (0.10.0)
  • Installing cachecontrol (0.12.11)
  • Installing cleo (2.0.1)
  • Installing click (8.1.3)
  • Installing dulwich (0.21.5)
Skipping wheel dulwich-0.21.5-cp310-cp310-macosx_10_9_universal2.whl as this is not supported by the current environment
[...]
Skipping wheel dulwich-0.21.5-cp37-cp37m-win32.whl as this is not supported by the current environment
  • Installing greenlet (2.0.2)
  • Installing html5lib (1.1)
  • Installing installer (0.7.0)
Skipping wheel dulwich-0.21.5-cp37-cp37m-win_amd64.whl as this is not supported by the current environment
[...]
Skipping wheel greenlet-2.0.2-cp39-cp39-win_amd64.whl as this is not supported by the current environment
  • Installing itsdangerous (2.1.2)
  • Installing jinja2 (3.1.2)
  • Installing jsonschema (4.17.3)
  • Installing keyring (23.13.1)
  • Installing numpy (1.24.3)
Skipping wheel numpy-1.24.3-cp310-cp310-macosx_10_9_x86_64.whl as this is not supported by the current environment
[...]
Skipping wheel numpy-1.24.3-pp38-pypy38_pp73-win_amd64.whl as this is not supported by the current environment
  • Installing pexpect (4.8.0)
  • Installing pkginfo (1.9.6)
  • Installing poetry-plugin-export (1.3.1)
  • Installing requests-toolbelt (0.10.1)
  • Updating setuptools (67.6.1 -> 67.7.2)
  • Installing shellingham (1.5.0.post1)
  • Installing tomlkit (0.11.8)
  • Installing trove-classifiers (2023.5.2)
  • Installing types-markupsafe (1.1.10)

  Stack trace:

  2  ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/utils/env.py:1543 in _run
      1541│                 return subprocess.call(cmd, stderr=stderr, env=env, **kwargs)
      1542│             else:
    → 1543│                 output = subprocess.check_output(cmd, stderr=stderr, env=env, **kwargs)
      1544│         except CalledProcessError as e:
      1545│             raise EnvCommandError(e, input=input_)

  1  /usr/lib/python3.9/subprocess.py:424 in check_output
       422│         kwargs['input'] = empty
       423│
    →  424│     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
       425│                **kwargs).stdout
       426│

  CalledProcessError

  Command '['/home/foo/.cache/pypoetry/virtualenvs/bar-G_ikZTXW-py3.9/bin/python', '-m', 'pip', 'uninstall', 'setuptools', '-y']' returned non-zero exit status 1.

  at /usr/lib/python3.9/subprocess.py:528 in run
       524│             # We don't call process.wait() as .__exit__ does that for us.
       525│             raise
       526│         retcode = process.poll()
       527│         if check and retcode:
    →  528│             raise CalledProcessError(retcode, process.args,
       529│                                      output=stdout, stderr=stderr)
       530│     return CompletedProcess(process.args, retcode, stdout, stderr)
       531│
       532│

The following error occurred when trying to handle this error:


  Stack trace:

  9  ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/executor.py:280 in _execute_operation
      278│
      279│             try:
    → 280│                 result = self._do_execute_operation(operation)
      281│             except EnvCommandError as e:
      282│                 if e.e.returncode == -2:

  8  ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/executor.py:382 in _do_execute_operation
      380│             return 0
      381│
    → 382│         result: int = getattr(self, f"_execute_{method}")(operation)
      383│
      384│         if result != 0:

  7  ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/executor.py:509 in _execute_update
      507│
      508│     def _execute_update(self, operation: Install | Update) -> int:
    → 509│         status_code = self._update(operation)
      510│
      511│         self._save_url_reference(operation)

  6  ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/executor.py:568 in _update
      566│
      567│     def _update(self, operation: Install | Update) -> int:
    → 568│         return self._install(operation)
      569│
      570│     def _remove(self, package: Package) -> int:

  5  ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/executor.py:558 in _install
      556│                 # the new package can't be installed
      557│                 assert isinstance(operation, Update)
    → 558│                 self._remove(operation.initial_package)
      559│
      560│             self._wheel_installer.install(archive)
      
  4  ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/executor.py:578 in _remove
      576│
      577│         try:
    → 578│             return self.run_pip("uninstall", package.name, "-y")
      579│         except CalledProcessError as e:
      580│             if "not installed" in str(e):

  3  ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/installation/executor.py:405 in run_pip
      403│     def run_pip(self, *args: Any, **kwargs: Any) -> int:
      404│         try:
    → 405│             self._env.run_pip(*args, **kwargs)
      406│         except EnvCommandError as e:
      407│             output = decode(e.e.output)

  2  ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/utils/env.py:1505 in run_pip
      1503│         pip = self.get_pip_command()
      1504│         cmd = pip + list(args)
    → 1505│         return self._run(cmd, **kwargs)
      1506│
      1507│     def run_python_script(self, content: str, **kwargs: Any) -> int | str:

  1  ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/utils/env.py:1781 in _run
      1779│     def _run(self, cmd: list[str], **kwargs: Any) -> int | str:
      1780│         kwargs["env"] = self.get_temp_environ(environ=kwargs.get("env"))
    → 1781│         return super()._run(cmd, **kwargs)
      1782│
      1783│     def get_temp_environ(

  EnvCommandError

  Command ['/home/foo/.cache/pypoetry/virtualenvs/bar-G_ikZTXW-py3.9/bin/python', '-m', 'pip', 'uninstall', 'setuptools', '-y'] errored with the following return code 1

  Output:
  Could not import runpy module
  Traceback (most recent call last):
    File "/usr/lib/python3.9/runpy.py", line 14, in <module>
      import importlib.machinery # importlib first so we can test #15386 via -m
    File "/usr/lib/python3.9/importlib/__init__.py", line 57, in <module>
      import types
    File "/home/foo/Projects/baz-project/baz-package/baz/types.py", line 3, in <module>
      from typing import Any
    File "/usr/lib/python3.9/typing.py", line 23, in <module>
      import contextlib
    File "/usr/lib/python3.9/contextlib.py", line 6, in <module>
      from functools import wraps
    File "/usr/lib/python3.9/functools.py", line 22, in <module>
      from types import GenericAlias
  ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/home/foo/Projects/baz-project/baz-package/baz/types.py)


  at ~/.local/pipx/venvs/poetry/lib/python3.9/site-packages/poetry/utils/env.py:1545 in _run
      1541│                 return subprocess.call(cmd, stderr=stderr, env=env, **kwargs)
      1542│             else:
      1543│                 output = subprocess.check_output(cmd, stderr=stderr, env=env, **kwargs)
      1544│         except CalledProcessError as e:
    → 1545│             raise EnvCommandError(e, input=input_)
      1546│
      1547│         return decode(output)
      1548│
      1549│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

  • Installing typing-extensions (4.5.0)
  • Installing tzlocal (2.0.0)
  • Installing virtualenv (20.16.5)
  • Installing werkzeug (2.3.3)
```

## Issue

I have a `baz/types.py` module in my package, containing typing definitions:
```
baz-package
├── dev-requirements.txt
├── baz
│   ├── cli.py
│   ├── config.py
│   ├── constants.py
│   ├── exceptions.py
│   ├── filters.py
│   ├── __init__.py
│   ├── logging.py
│   ├── reports
│   │   └── ...
│   ├── static
│   │   └── ...
│   ├── templates
│   │   └── ...
│   ├── **types.py**
│   └── utils.py
├── poetry.lock
├── baz.service
├── pyproject.gist.toml
├── README.md
├── requirements.txt
└── tests
```

This seems to cause circular imports with setuptools when executing:

```sh
$ poetry shell
$ poetry install
```

> ImportError: cannot import name 'GenericAlias' from partially initialized module 'types' (most likely due to a circular import) (/home/foo/Projects/baz-project/baz-package/baz/types.py)`

I renamed that module and its imports, then the install worked successfully.

Thus, is the `types.py` module name forbidden/not recommended ? :-)

**Comment by dimbleby** [comment]
this doesn't look as though it's anything much to do with poetry: you can see that poetry is simply shelling out to `pip` at this point and that's what's failing.
