### ISSUE TITLE
PermissionError when installing on Windows only

### ISSUE THREAD

**Issue by l0b0** [python-poetry/poetry#8047]
- **Poetry version**: 1.5.0 and 1.5.1
- **Python version**: 3.8, 3.9, 3.10, and 3.11
- **OS version and name**: Windows 2022
- **pyproject.toml**: [Gist](https://gist.github.com/l0b0/b4a4f2a801d84f53ba1f4606761a5bef)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

See [relevant PR](https://github.com/linz/emergency-management-tools/pull/207) and [example build failure](https://github.com/linz/emergency-management-tools/actions/runs/5128270356/jobs/9224788900).

 `poetry -vvv install --only=main --no-root` output:

```text
Using virtualenv: C:\Miniconda\envs\test
Installing dependencies from lock file

Finding the necessary packages for the current system

Package operations: 99 installs, 17 updates, 0 removals, 2 skipped

  � Updating attrs (23.1.0 /home/conda/feedstock_root/build_artifacts/attrs_1683424013410/work -> 22.2.0)
  � Updating platformdirs (3.5.1 /home/conda/feedstock_root/build_artifacts/platformdirs_1683850015520/work -> 3.2.0)
  � Updating pyrsistent (0.19.3 D:/bld/pyrsistent_1672681663470/work -> 0.19.3)
  � Installing pywin32 (306)
  � Updating six (1.16.0 /home/conda/feedstock_root/build_artifacts/six_1620240208055/work -> 1.16.0)
  � Installing traitlets (5.9.0)
[keyring.backend] Loading KWallet
[keyring.backend] Loading KWallet
[keyring.backend] Loading KWallet
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading SecretService
[keyring.backend] Loading SecretService
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading Windows
[keyring.backend] Loading Windows
[keyring.backend] Loading Windows
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading KWallet
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading chainer
[keyring.backend] Loading chainer
[keyring.backend] Loading chainer
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading libsecret
[keyring.backend] Loading libsecret
[keyring.backend] Loading libsecret
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
[keyring.backend] Loading macOS
[keyring.backend] Loading macOS
[keyring.backend] Loading macOS
[keyring.backend] Loading macOS
[keyring.backend] Loading macOS
Creating new session for pypi.org
[urllib3.connectionpool] Starting new HTTPS connection (1): pypi.org:443
[urllib3.connectionpool] Starting new HTTPS connection (2): pypi.org:443
[urllib3.connectionpool] Starting new HTTPS connection (3): pypi.org:443
[urllib3.connectionpool] Starting new HTTPS connection (4): pypi.org:443
[urllib3.connectionpool] Starting new HTTPS connection (5): pypi.org:443
[urllib3.connectionpool] Starting new HTTPS connection (6): pypi.org:443
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/six/1.16.0/json HTTP/1.1" 200 1539
[filelock] Attempting to acquire lock 1601254265456 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\0\a\3\d\2\0a3d25d87fafdf016ee0ce5af0b8840c4088c048fdaea00685df55b3.lock
[filelock] Lock 1601254265456 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\0\a\3\d\2\0a3d25d87fafdf016ee0ce5af0b8840c4088c048fdaea00685df55b3.lock
[filelock] Attempting to release lock 1601254265456 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\0\a\3\d\2\0a3d25d87fafdf016ee0ce5af0b8840c4088c048fdaea00685df55b3.lock
[filelock] Lock 1601254265456 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\0\a\3\d\2\0a3d25d87fafdf016ee0ce5af0b8840c4088c048fdaea00685df55b3.lock
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/platformdirs/3.2.0/json HTTP/1.1" 200 3586
[filelock] Attempting to acquire lock 1601254265600 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\2\3\3\4\1\23341d5184bc0e9a7dd4b6c5486944b6678117c7ad094ed7e082663c.lock
[filelock] Lock 1601254265600 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\2\3\3\4\1\23341d5184bc0e9a7dd4b6c5486944b6678117c7ad094ed7e082663c.lock
[filelock] Attempting to release lock 1601254265600 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\2\3\3\4\1\23341d5184bc0e9a7dd4b6c5486944b6678117c7ad094ed7e082663c.lock
[filelock] Lock 1601254265600 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\2\3\3\4\1\23341d5184bc0e9a7dd4b6c5486944b6678117c7ad094ed7e082663c.lock
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/attrs/22.2.0/json HTTP/1.1" 200 5285
[filelock] Attempting to acquire lock 1601254265696 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\8\1\4\e\a\814ea79aaf2958d364068f0b91b82e0077d4fc0d0cf856a8ec28e467.lock
[filelock] Lock 1601254265696 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\8\1\4\e\a\814ea79aaf2958d364068f0b91b82e0077d4fc0d0cf856a8ec28e467.lock
[filelock] Attempting to release lock 1601254265696 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\8\1\4\e\a\814ea79aaf2958d364068f0b91b82e0077d4fc0d0cf856a8ec28e467.lock
[filelock] Lock 1601254265696 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\8\1\4\e\a\814ea79aaf2958d364068f0b91b82e0077d4fc0d0cf856a8ec28e467.lock
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/traitlets/5.9.0/json HTTP/1.1" 200 4857
[filelock] Attempting to acquire lock 1601254266032 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\e\7\f\4\7\e7f47bbc2826d45b243d63e7c0f373907232391f8247af5a4616e788.lock
[filelock] Lock 1601254266032 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\e\7\f\4\7\e7f47bbc2826d45b243d63e7c0f373907232391f8247af5a4616e788.lock
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/pywin32/306/json HTTP/1.1" 200 5499
[filelock] Attempting to acquire lock 1601254267088 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\f\1\8\6\6\f1866113136faae9b3ce77b5b4ef046277c4e83c34177e9b325b77d3.lock
[filelock] Lock 1601254267088 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\f\1\8\6\6\f1866113136faae9b3ce77b5b4ef046277c4e83c34177e9b325b77d3.lock
[filelock] Attempting to release lock 1601254267088 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\f\1\8\6\6\f1866113136faae9b3ce77b5b4ef046277c4e83c34177e9b325b77d3.lock
[filelock] Lock 1601254267088 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\f\1\8\6\6\f1866113136faae9b3ce77b5b4ef046277c4e83c34177e9b325b77d3.lock
[filelock] Attempting to release lock 1601254266032 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\e\7\f\4\7\e7f47bbc2826d45b243d63e7c0f373907232391f8247af5a4616e788.lock
[filelock] Lock 1601254266032 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\e\7\f\4\7\e7f47bbc2826d45b243d63e7c0f373907232391f8247af5a4616e788.lock
[urllib3.connectionpool] https://pypi.org:443 "GET /pypi/pyrsistent/0.19.3/json HTTP/1.1" 200 14289
[filelock] Attempting to acquire lock 1601254270016 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\8\6\4\b\4\864b4eb7fe9df7fae1220d2144a54fb8e83c7d6b16b7e0f074a513e0.lock
[filelock] Lock 1601254270016 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\8\6\4\b\4\864b4eb7fe9df7fae1220d2144a54fb8e83c7d6b16b7e0f074a513e0.lock
[filelock] Attempting to release lock 1601254270016 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\8\6\4\b\4\864b4eb7fe9df7fae1220d2144a54fb8e83c7d6b16b7e0f074a513e0.lock
[filelock] Lock 1601254270016 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\PyPI\_http\8\6\4\b\4\864b4eb7fe9df7fae1220d2144a54fb8e83c7d6b16b7e0f074a513e0.lock
Creating new session for files.pythonhosted.org
[urllib3.connectionpool] Starting new HTTPS connection (1): files.pythonhosted.org:443
Skipping wheel pywin32-306-cp310-cp310-win32.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp311-cp311-win32.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp311-cp311-win_amd64.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp311-cp311-win_arm64.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp312-cp312-win32.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp312-cp312-win_amd64.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp312-cp312-win_arm64.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp37-cp37m-win32.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp37-cp37m-win_amd64.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp38-cp38-win32.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp38-cp38-win_amd64.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp39-cp39-win32.whl as this is not supported by the current environment
Skipping wheel pywin32-306-cp39-cp39-win_amd64.whl as this is not supported by the current environment
[urllib3.connectionpool] Starting new HTTPS connection (2): files.pythonhosted.org:443
[urllib3.connectionpool] Starting new HTTPS connection (3): files.pythonhosted.org:443
[urllib3.connectionpool] https://files.pythonhosted.org:443 "GET /packages/fb/6e/6f83bf616d2becdf333a1640f1d463fef3150e2e926b7010cb0f81c95e88/attrs-22.2.0-py3-none-any.whl HTTP/1.1" 200 60018
[filelock] Attempting to acquire lock 1601254264304 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\c\e\f\9\1\cef9102a0c1f42977f786c811243e289f80ce484ee957137931aedd9.lock
[filelock] Lock 1601254264304 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\c\e\f\9\1\cef9102a0c1f42977f786c811243e289f80ce484ee957137931aedd9.lock
[filelock] Attempting to release lock 1601254264304 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\c\e\f\9\1\cef9102a0c1f42977f786c811243e289f80ce484ee957137931aedd9.lock
[filelock] Lock 1601254264304 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\c\e\f\9\1\cef9102a0c1f42977f786c811243e289f80ce484ee957137931aedd9.lock
[urllib3.connectionpool] Starting new HTTPS connection (4): files.pythonhosted.org:443
[urllib3.connectionpool] https://files.pythonhosted.org:443 "GET /packages/77/75/c28e9ef7abec2b7e9ff35aea3e0be6c1aceaf7873c26c95ae1f0d594de71/traitlets-5.9.0-py3-none-any.whl HTTP/1.1" 200 117376
[urllib3.connectionpool] https://files.pythonhosted.org:443 "GET /packages/d3/d6/891894edec688e72c2e308b3243fad98b4066e1839fd2fe78f04129a9d31/pywin32-306-cp310-cp310-win_amd64.whl HTTP/1.1" 200 9226392
[filelock] Attempting to acquire lock 1601254267088 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\e\6\d\9\b\e6d9b1283b6dc6eab2db2ea8f2f5de1215358b4c1003d5c3b4182b3b.lock
[filelock] Lock 1601254267088 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\e\6\d\9\b\e6d9b1283b6dc6eab2db2ea8f2f5de1215358b4c1003d5c3b4182b3b.lock
[filelock] Attempting to release lock 1601254267088 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\e\6\d\9\b\e6d9b1283b6dc6eab2db2ea8f2f5de1215358b4c1003d5c3b4182b3b.lock
[filelock] Lock 1601254267088 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\e\6\d\9\b\e6d9b1283b6dc6eab2db2ea8f2f5de1215358b4c1003d5c3b4182b3b.lock
[urllib3.connectionpool] https://files.pythonhosted.org:443 "GET /packages/d9/5a/e7c31adbe875f2abbb91bd84cf2dc52d792b5a01506781dbcf25c91daf11/six-1.16.0-py2.py3-none-any.whl HTTP/1.1" 200 11053
[filelock] Attempting to acquire lock 1601254266176 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\3\f\4\9\c\3f49c19c42525485da2c265d82244e942d3619ff5626136ee23992d0.lock
[filelock] Lock 1601254266176 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\3\f\4\9\c\3f49c19c42525485da2c265d82244e942d3619ff5626136ee23992d0.lock
[filelock] Attempting to release lock 1601254266176 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\3\f\4\9\c\3f49c19c42525485da2c265d82244e942d3619ff5626136ee23992d0.lock
[filelock] Lock 1601254266176 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\3\f\4\9\c\3f49c19c42525485da2c265d82244e942d3619ff5626136ee23992d0.lock
[urllib3.connectionpool] https://files.pythonhosted.org:443 "GET /packages/b2/f3/4fb5fae710fc9f22a42cd90dc0547da18ec83e2e139294ab94f04c449cf5/platformdirs-3.2.0-py3-none-any.whl HTTP/1.1" 200 14863
[filelock] Attempting to acquire lock 1601254266752 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\e\0\b\8\0\e0b803b48b6f96ad38f88f0a549220eafd482a8c15102bc20f8d3b9b.lock
[filelock] Lock 1601254266752 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\e\0\b\8\0\e0b803b48b6f96ad38f88f0a549220eafd482a8c15102bc20f8d3b9b.lock
[filelock] Attempting to release lock 1601254266752 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\e\0\b\8\0\e0b803b48b6f96ad38f88f0a549220eafd482a8c15102bc20f8d3b9b.lock
[filelock] Lock 1601254266752 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\e\0\b\8\0\e0b803b48b6f96ad38f88f0a549220eafd482a8c15102bc20f8d3b9b.lock
[filelock] Attempting to acquire lock 1601254266752 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\b\6\4\f\4\b64f4d51ab2c732a0f9ec26600eed01ce0e5837b13f47d3b41930ecc.lock
[filelock] Lock 1601254266752 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\b\6\4\f\4\b64f4d51ab2c732a0f9ec26600eed01ce0e5837b13f47d3b41930ecc.lock
[filelock] Attempting to release lock 1601254266752 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\b\6\4\f\4\b64f4d51ab2c732a0f9ec26600eed01ce0e5837b13f47d3b41930ecc.lock
[filelock] Lock 1601254266752 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\b\6\4\f\4\b64f4d51ab2c732a0f9ec26600eed01ce0e5837b13f47d3b41930ecc.lock
Skipping wheel pyrsistent-0.19.3-cp310-cp310-macosx_10_9_universal2.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp310-cp310-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp310-cp310-win32.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp311-cp311-macosx_10_9_universal2.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp311-cp311-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp311-cp311-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp311-cp311-win32.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp311-cp311-win_amd64.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp37-cp37m-macosx_10_9_x86_64.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp37-cp37m-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp37-cp37m-win32.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp37-cp37m-win_amd64.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp38-cp38-macosx_10_9_universal2.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp38-cp38-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp38-cp38-win32.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp38-cp38-win_amd64.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp39-cp39-macosx_10_9_universal2.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp39-cp39-manylinux_2_5_i686.manylinux1_i686.manylinux_2_17_i686.manylinux2014_i686.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp39-cp39-win32.whl as this is not supported by the current environment
Skipping wheel pyrsistent-0.19.3-cp39-cp39-win_amd64.whl as this is not supported by the current environment
[urllib3.connectionpool] https://files.pythonhosted.org:443 "GET /packages/87/72/e5b2347f136d14f09c8260a2e3a528be94e536d97e6635cc9f22cff2d88c/pyrsistent-0.19.3-cp310-cp310-win_amd64.whl HTTP/1.1" 200 62716
[filelock] Attempting to acquire lock 1601254270592 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\7\9\b\7\9\79b7957fae9e096d8b9b525cb3dac889dfe4e5b398de4f9432ae4021.lock
[filelock] Lock 1601254270592 acquired on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\7\9\b\7\9\79b7957fae9e096d8b9b525cb3dac889dfe4e5b398de4f9432ae4021.lock
[filelock] Attempting to release lock 1601254270592 on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\7\9\b\7\9\79b7957fae9e096d8b9b525cb3dac889dfe4e5b398de4f9432ae4021.lock
[filelock] Lock 1601254270592 released on C:\Users\runneradmin\AppData\Local\pypoetry\Cache\cache\repositories\_default_cache\_http\7\9\b\7\9\79b7957fae9e096d8b9b525cb3dac889dfe4e5b398de4f9432ae4021.lock

  Stack trace:

  2  C:\Miniconda\envs\test\lib\site-packages\poetry\utils\env.py:1523 in _run
      1521|                 output = ""
      1522|             else:
    > 1523|                 output = subprocess.check_output(cmd, stderr=stderr, env=env, **kwargs)
      1524|         except CalledProcessError as e:
      1525|             raise EnvCommandError(e, input=input_)

  1  C:\Miniconda\envs\test\lib\subprocess.py:421 in check_output
       419|         kwargs['input'] = empty
       420| 
    >  421|     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
       422|                **kwargs).stdout
       423| 

  CalledProcessError

  Command '['C:\\Miniconda\\envs\\test\\python.exe', '-m', 'pip', 'uninstall', 'pyrsistent', '-y']' returned non-zero exit status 2.

  at C:\Miniconda\envs\test\lib\subprocess.py:526 in run
       522|             # We don't call process.wait() as .__exit__ does that for us.
       523|             raise
       524|         retcode = process.poll()
       525|         if check and retcode:
    >  526|             raise CalledProcessError(retcode, process.args,
       527|                                      output=stdout, stderr=stderr)
       528|     return CompletedProcess(process.args, retcode, stdout, stderr)
       529| 
       530| 

The following error occurred when trying to handle this error:


  Stack trace:

  9  C:\Miniconda\envs\test\lib\site-packages\poetry\installation\executor.py:286 in _execute_operation
      284| 
      285|             try:
    > 286|                 result = self._do_execute_operation(operation)
      287|             except EnvCommandError as e:
      288|                 if e.e.returncode == -2:

  8  C:\Miniconda\envs\test\lib\site-packages\poetry\installation\executor.py:388 in _do_execute_operation
      386|             return 0
      387| 
    > 388|         result: int = getattr(self, f"_execute_{method}")(operation)
      389| 
      390|         if result != 0:

  7  C:\Miniconda\envs\test\lib\site-packages\poetry\installation\executor.py:515 in _execute_update
      513| 
      514|     def _execute_update(self, operation: Install | Update) -> int:
    > 515|         status_code = self._update(operation)
      516| 
      517|         self._save_url_reference(operation)

  6  C:\Miniconda\envs\test\lib\site-packages\poetry\installation\executor.py:574 in _update
      572| 
      573|     def _update(self, operation: Install | Update) -> int:
    > 574|         return self._install(operation)
      575| 
      576|     def _remove(self, package: Package) -> int:

  5  C:\Miniconda\envs\test\lib\site-packages\poetry\installation\executor.py:564 in _install
      562|                 # the new package can't be installed
      563|                 assert isinstance(operation, Update)
    > 564|                 self._remove(operation.initial_package)
      565| 
      566|             self._wheel_installer.install(archive)

  4  C:\Miniconda\envs\test\lib\site-packages\poetry\installation\executor.py:584 in _remove
      582| 
      583|         try:
    > 584|             return self.run_pip("uninstall", package.name, "-y")
      585|         except CalledProcessError as e:
      586|             if "not installed" in str(e):

  3  C:\Miniconda\envs\test\lib\site-packages\poetry\installation\executor.py:411 in run_pip
      409|     def run_pip(self, *args: Any, **kwargs: Any) -> int:
      410|         try:
    > 411|             self._env.run_pip(*args, **kwargs)
      412|         except EnvCommandError as e:
      413|             output = decode(e.e.output)

  2  C:\Miniconda\envs\test\lib\site-packages\poetry\utils\env.py:1484 in run_pip
      1482|         pip = self.get_pip_command()
      1483|         cmd = pip + list(args)
    > 1484|         return self._run(cmd, **kwargs)
      1485| 
      1486|     def run_python_script(self, content: str, **kwargs: Any) -> str:

  1  C:\Miniconda\envs\test\lib\site-packages\poetry\utils\env.py:1731 in _run
      1729|     def _run(self, cmd: list[str], **kwargs: Any) -> str:
      1730|         kwargs["env"] = self.get_temp_environ(environ=kwargs.get("env"))
    > 1731|         return super()._run(cmd, **kwargs)
      1732| 
      1733|     def get_temp_environ(

  EnvCommandError

  Command ['C:\\Miniconda\\envs\\test\\python.exe', '-m', 'pip', 'uninstall', 'pyrsistent', '-y'] errored with the following return code 2
  
  Output:
  Found existing installation: pyrsistent 0.19.3

  Uninstalling pyrsistent-0.19.3:

    Successfully uninstalled pyrsistent-0.19.3

  ERROR: Exception:

  Traceback (most recent call last):

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_internal\cli\base_command.py", line 169, in exc_logging_wrapper

      status = run_func(*args)

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_internal\commands\uninstall.py", line 110, in run

      uninstall_pathset.commit()

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_internal\req\req_uninstall.py", line 432, in commit

      self._moved_paths.commit()

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_internal\req\req_uninstall.py", line 278, in commit

      save_dir.cleanup()

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_internal\utils\temp_dir.py", line 173, in cleanup

      rmtree(self._path)

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 291, in wrapped_f

      return self(f, *args, **kw)

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 381, in __call__

      do = self.iter(retry_state=retry_state)

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 327, in iter

      raise retry_exc.reraise()

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 160, in reraise

      raise self.last_attempt.result()

    File "C:\Miniconda\envs\test\lib\concurrent\futures\_base.py", line 451, in result

      return self.__get_result()

    File "C:\Miniconda\envs\test\lib\concurrent\futures\_base.py", line 403, in __get_result

      raise self._exception

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_vendor\tenacity\__init__.py", line 384, in __call__

      result = fn(*args, **kwargs)

    File "C:\Miniconda\envs\test\lib\site-packages\pip\_internal\utils\misc.py", line 130, in rmtree

      shutil.rmtree(dir, ignore_errors=ignore_errors, onerror=rmtree_errorhandler)

    File "C:\Miniconda\envs\test\lib\shutil.py", line 750, in rmtree

      return _rmtree_unsafe(path, onerror)

    File "C:\Miniconda\envs\test\lib\shutil.py", line 620, in _rmtree_unsafe

      onerror(os.unlink, fullname, sys.exc_info())

    File "C:\Miniconda\envs\test\lib\shutil.py", line 618, in _rmtree_unsafe

      os.unlink(fullname)

  PermissionError: [WinError 5] Access is denied: 'C:\\Users\\runneradmin\\AppData\\Local\\Temp\\pip-uninstall-4zdp64ma\\pvectorc.cp310-win_amd64.pyd'

  

  at C:\Miniconda\envs\test\lib\site-packages\poetry\utils\env.py:1525 in _run
      1521|                 output = ""
      1522|             else:
      1523|                 output = subprocess.check_output(cmd, stderr=stderr, env=env, **kwargs)
      1524|         except CalledProcessError as e:
    > 1525|             raise EnvCommandError(e, input=input_)
      1526| 
      1527|         return decode(output)
      1528| 
      1529|     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:
```

**Comment by dimbleby** [comment]
as you can see,this is happening from a `pip` subprocess.  I dont expect there is anything poetry can do about that.

There are many relevant issues on the pip tracker, https://github.com/pypa/pip/pull/11394, looks live.
