### ISSUE TITLE
Poetry install fails with ModuleNotFoundError: No module named 'lockfile'

### ISSUE THREAD

**Issue by 4ekin** [python-poetry/poetry#8064]
- **Poetry version**: 1.3.0
- **Python version**: 3.10
- **OS version and name**: docker image python:3.10-slim-buster

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
At friday 02 June my docker build was in excellent state, but today I have errors during `poetry install` execution

Docker file:
```Docker
FROM python:3.10-slim-buster as python-base

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    # pip
    PIP_NO_CACHE_DIR=off \
    PIP_DISABLE_PIP_VERSION_CHECK=on \
    PIP_DEFAULT_TIMEOUT=100 \
    # poetry
    POETRY_VERSION=1.3.0 \
    POETRY_HOME="/opt/poetry" \
    POETRY_VIRTUALENVS_IN_PROJECT=true \
    POETRY_NO_INTERACTION=1 \
    PYSETUP_PATH="/opt/pysetup" \
    VENV_PATH="/opt/pysetup/.venv"

ENV PATH="$POETRY_HOME/bin:$VENV_PATH/bin:$PATH"

RUN apt-get update \
    && apt-get install -y libpq-dev netcat

FROM python-base as builder-base
RUN apt-get install -y curl build-essential gcc libkeyutils1

RUN curl -sSL https://install.python-poetry.org | python3 -

WORKDIR $PYSETUP_PATH
COPY poetry.lock pyproject.toml ./

RUN poetry install -vvv --only main --no-root
```

Exception:
```
Step 11/28 : RUN poetry install -vvv --only main --no-root
 ---> Running in de2a58ffc74f
Traceback (most recent call last):
  File "/opt/poetry/venv/lib/python3.10/site-packages/cleo/application.py", line 327, in run
    exit_code = self._run(io)
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/console/application.py", line 188, in _run
    self._load_plugins(io)
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/console/application.py", line 355, in _load_plugins
    manager.load_plugins()
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/plugins/plugin_manager.py", line 38, in load_plugins
    self._load_plugin_entry_point(ep)
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/plugins/plugin_manager.py", line 76, in _load_plugin_entry_point
    plugin = ep.load()  # type: ignore[no-untyped-call]
  File "/usr/local/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/usr/local/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry_plugin_export/plugins.py", line 7, in <module>
    from poetry_plugin_export.command import ExportCommand
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry_plugin_export/command.py", line 10, in <module>
    from poetry_plugin_export.exporter import Exporter
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry_plugin_export/exporter.py", line 11, in <module>
    from poetry.repositories.http_repository import HTTPRepository
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/repositories/http_repository.py", line 26, in <module>
    from poetry.utils.authenticator import Authenticator
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/utils/authenticator.py", line 15, in <module>
    import lockfile
ModuleNotFoundError: No module named 'lockfile'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/poetry/bin/poetry", line 8, in <module>
    sys.exit(main())
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/console/application.py", line 406, in main
    exit_code: int = Application().run()
  File "/opt/poetry/venv/lib/python3.10/site-packages/cleo/application.py", line 338, in run
    self.render_error(e, io)
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/console/application.py", line 180, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/console/application.py", line 395, in _get_solution_provider_repository
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (  # noqa: E501
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/mixology/solutions/providers/__init__.py", line 3, in <module>
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/mixology/solutions/providers/python_requirement_solution_provider.py", line 9, in <module>
    from poetry.puzzle.exceptions import SolverProblemError
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/puzzle/__init__.py", line 3, in <module>
    from poetry.puzzle.solver import Solver
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/puzzle/solver.py", line 19, in <module>
    from poetry.puzzle.provider import Indicator
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/puzzle/provider.py", line 37, in <module>
    from poetry.vcs.git import Git
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/vcs/git/__init__.py", line 3, in <module>
    from poetry.vcs.git.backend import Git
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/vcs/git/backend.py", line 21, in <module>
    from poetry.utils.authenticator import get_default_authenticator
  File "/opt/poetry/venv/lib/python3.10/site-packages/poetry/utils/authenticator.py", line 15, in <module>
    import lockfile
ModuleNotFoundError: No module named 'lockfile'
The command '/bin/sh -c poetry install -vvv --only main --no-root' returned a non-zero code: 1
```

I think that issue in this commit https://github.com/python-poetry/poetry/commit/fca3d5d04fb01bbb3c77e810094a99732b7d024c

**Comment by 4ekin** [comment]
Well, I've replaced 1.3.0 to 1.5.0, and it fixed my problem

Can I close issue?

**Comment by finswimmer** [comment]
> Can I close issue?

If you cannot reproduce the issue with the current version of Poetry, please do so :+1:

**Comment by ehellmann-nydig** [comment]
How is this ok? I haven't upgraded and it's not trivial for me to upgrade. This is a breaking change to a stable version

**Comment by mishamsk** [comment]
> How is this ok? I haven't upgraded and it's not trivial for me to upgrade. This is a breaking change to a stable version

same here. We are on 1.2.2

What's weird, it does work on my Mac, but fails in CI on multiple runners. Any fixes?

**Comment by dimbleby** [comment]
the actual cause is the release of cachecontrol 0.12.13 which dropped its dependency on lockfile and therefore revealed that poetry had forgotten to declare its own explicit dependency

this was fixed six months ago.  your fix is to use a more recent poetry.

**Comment by ehellmann-nydig** [comment]
oh, so a temporary fix would be to explicitly add a dependency on lockfile, then? For those who don't have the luxury of upgrading, of course.

**Comment by mishamsk** [comment]
@dimbleby not sure about the OP, but in my case we were going through poetry upgrades to 1.2 then 1.3, when it started breaking things for us, so we stuck with 1.2.2 at the time. Which was 6+ months ago. We apparently left 1.3.0 in pre-commit. It did work ok up until yesterday, and this is not about us changing any dependencies, I do not think we’ve let a fresh `cachecontrol` somewhere, since this issue popped up in pre-commit, which just installs poetry in a separate env.

Although, it is obviously much less of a pain to try and update poetry just for the pre-commit. But updating poetry for the project itself is definitely not a simple exercise as I’ve learned the hard way when we tried to go up to then-most-recent 1.3 version

**Comment by dimbleby** [comment]
fresh cachecontrol is certainly what is causing these symptoms, it sounds as though your installs are less reproducible than you think they are.  How much of a problem that is for you, is up to you.

**Comment by mishamsk** [comment]
@dimbleby yeah, totally agree about reproducibility. Will look into that, thanks
