### ISSUE TITLE
Poetry install randomly started failing today, no dependency changes

### ISSUE THREAD

**Issue by mattotodd** [python-poetry/poetry#8207]
- **Poetry version**: 1.5.1
- **Python version**: 3.11
- **OS version and name**: macOS12 and on CI build cimg/python:3.9
- **pyproject.toml**: [https://gist.github.com/mattotodd/e8e2c53888904dd8de2e76dbc7a54a42](https://gist.github.com/mattotodd/e8e2c53888904dd8de2e76dbc7a54a42)

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Build started failing this morning when trying to install. There were no dependency changes.  
Fails in our CI build and also fails trying to install locally too.  

```
  • Installing pyyaml (6.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  running egg_info
  writing lib/PyYAML.egg-info/PKG-INFO
  writing dependency_links to lib/PyYAML.egg-info/dependency_links.txt
  writing top-level names to lib/PyYAML.egg-info/top_level.txt
  Traceback (most recent call last):
    File "/Users/mattotodd/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/Users/mattotodd/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/mattotodd/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
             ^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
      self.run_setup()
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/build_meta.py", line 338, in run_setup
      exec(code, locals())
    File "<string>", line 288, in <module>
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/__init__.py", line 107, in setup
      return distutils.core.setup(**attrs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
             ^^^^^^^^^^^^^^^^^^
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
      self.run_command(cmd)
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/dist.py", line 1234, in run_command
      super().run_command(command)
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
      cmd_obj.run()
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 314, in run
      self.find_sources()
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 322, in find_sources
      mm.run()
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 551, in run
      self.add_defaults()
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/command/egg_info.py", line 589, in add_defaults
      sdist.add_defaults(self)
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/command/sdist.py", line 104, in add_defaults
      super().add_defaults()
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 251, in add_defaults
      self._add_defaults_ext()
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/_distutils/command/sdist.py", line 336, in _add_defaults_ext
      self.filelist.extend(build_ext.get_source_files())
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "<string>", line 204, in get_source_files
    File "/var/folders/cg/gk_xvzfn6jn7v6bzpvydqc040000gn/T/tmpfu0z0wqo/.venv/lib/python3.11/site-packages/setuptools/_distutils/cmd.py", line 107, in __getattr__
      raise AttributeError(attr)
  AttributeError: cython_sources
  

  at ~/Library/Application Support/pypoetry/venv/lib/python3.10/site-packages/poetry/installation/chef.py:147 in _prepare
      143│ 
      144│                 error = ChefBuildError("\n\n".join(message_parts))
      145│ 
      146│             if error is not None:
    → 147│                 raise error from None
      148│ 
      149│             return path
      150│ 
      151│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with PyYAML (6.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "pyyaml (==6.0)"'
```

**Comment by dimbleby** [comment]
not a poetry bug, much as the error message says: you can reproduce this with pip as:
```
pip wheel --use-pep517 "pyyaml (==6.0)" --no-binary pyyaml
```
please close

**Comment by Secrus** [comment]
Update your `pyyaml` to 6.0.1, 6.0 is broken after Cython 3.0 was released.
