### ISSUE TITLE
Preparing metadata: assert isinstance(config, Table)

### ISSUE THREAD

**Issue by pbienst** [python-poetry/poetry#8601]
- **Poetry version**: auto-installed from pip
- **Python version**: python 3.8.10
- **OS version and name**: ubuntu 20.04.6 LTS
- **pyproject.toml**: https://github.com/mnemosyne-proj/mnemosyne/blob/master/pyproject.toml

- [X] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [X] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [X] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [X] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I created a source distribution for upload to pypi, to be installed using poetry. However, myself and other users on other systems get errors like these:

```
sudo pip3 install -i https://test.pypi.org/simple/ mnemosyne==2.10.1a0
Looking in indexes: https://test.pypi.org/simple/
Collecting mnemosyne==2.10.1a0
 Using cached https://test-files.pythonhosted.org/packages/fb/4d/d17f2eaead745b10676d4b5795ff3ac8948b685a4b5d61440213ab95af65/mnemosyne-2.10.1a0.tar.gz (898 kB)
 Installing build dependencies ... done
 Getting requirements to build wheel ... done
 Preparing metadata (pyproject.toml) ... error
 error: subprocess-exited-with-error

 × Preparing metadata (pyproject.toml) did not run successfully.
 │ exit code: 1
 ╰─> [14 lines of output]
     Traceback (most recent call last):
       File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
         main()
       File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
         json_out['return_val'] = hook(**hook_input['kwargs'])
       File "/usr/lib/python3.10/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
         return hook(metadata_directory, config_settings)
       File "/tmp/pip-build-env-us2xkg24/overlay/lib/python3.10/site-packages/poetry/core/masonry/api.py", line 40, in prepare_metadata_for_build_wheel
         poetry = Factory().create_poetry(Path(".").resolve(), with_groups=False)
       File "/tmp/pip-build-env-us2xkg24/overlay/lib/python3.10/site-packages/poetry/core/factory.py", line 46, in create_poetry
         local_config = PyProjectTOML(path=poetry_file).poetry_config
       File "/tmp/pip-build-env-us2xkg24/overlay/lib/python3.10/site-packages/poetry/core/pyproject/toml.py", line 74, in poetry_config
         assert isinstance(config, Table)
```

It's very difficult to debug this for me since the /tmp/pip-build directories seem to get deleted after install. Also, I looked at the most recent toml.py file on your repo, and that assert statement is no longer there. So, it seems like the poetry version pulled in by pip is perhaps outdated?

**Comment by dimbleby** [comment]
presumably test-pypi has only old versions of poetry-core available.  Too bad I guess.

**Comment by Secrus** [comment]
You are pulling `poetry-core` from test-pypi, we don't upload new versions there.
