### ISSUE TITLE
Regression: Poetry 1.7 hangs instead of asking to unlock keyring

### ISSUE THREAD

**Issue by ilyagr** [python-poetry/poetry#8623]
- **Poetry version**: 1.7.0
- **Python version**:  3.11.6
- **OS version and name**: Debian trixie (testing) running in a Chrome OS Linux container
- **pyproject.toml**: https://gist.github.com/ilyagr/1bebabebc93e6662d139009d19ed8c1b/edit (includes poetry.lock and detailed command-line output as well).

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a recommended method.
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

This is a follow-up to https://github.com/python-poetry/poetry/pull/1917 and https://github.com/python-poetry/poetry/pull/8227. I also mentioned this briefly in
https://github.com/python-poetry/poetry/issues/1917#issuecomment-1793322478

The bug happens when I run either `poetry install` or `poetry lock`.

- **Poetry 1.6.1 behavior**: a Gnome (gnome-keyring or seahorse, I'm unsure) window opens and asks to unlock a keyring. If I click cancel (refuse to unlock the keyring), poetry fails with an exception as described in #8227.

- **Current Poetry 1.7 behavior**: no Gnome window opens, poetry just freezes for a while.
 
  With Poetry 1.7, I also tried rebooting. After a reboot, a Gnome window does appear. After clicking cancel (refuse to unlock the keyring), it reappears. After clicking cancel ~10 more times, it stops reappearing and hangs again.

`rm -r ~/.cache/pypoetry` as suggested in https://github.com/python-poetry/poetry/issues/1917#issuecomment-1770241003 did not help, with or without reinstalling `poetry` (via `pipx`, in my case)

## Expected behavior

poetry does not try to unlock the keyring unless it is performing an operation that can't succeed without access to the keyring (e.g., already failed without access to the keyring).

Alternatively, a somewhat inferior option would be to have some way to tell poetry not to try unlocking any keyrings that is easier to discover than the workaround below. Additionally, there would be a user-friendly message suggesting that option whenever unlocking the keyrings doesn't work.

## Workaround

The workaround of `export PYTHON_KEYRING_BACKEND=keyring.backends.fail.Keyring` from https://github.com/python-poetry/poetry/issues/1917#issuecomment-1235998997 still works.

**Update:** https://github.com/python-poetry/poetry/issues/8623#issuecomment-2306101200 suggests that `poetry config keyring.enabled false` is a more permanent workaround.

## Command-line output

See https://gist.github.com/ilyagr/1bebabebc93e6662d139009d19ed8c1b for details.

The end of it is often the following printed to `stderr`:

```
[keyring.backend] Loading SecretService
[keyring.backend] Loading Windows
[keyring.backend] Loading chainer
[keyring.backend] Loading libsecret
[keyring.backend] Loading macOS
```

At this point, it hangs forever.

**Comment by n00bsys0p** [comment]
Confirming I'm getting exactly the same behaviour on an Ubuntu dev container with no X server. Both the following workarounds worked for me, but aren't ideal:

* `export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring`
* `pyenv shell system` followed by `python3 -m keyring --disable`

**Comment by bipindr123** [comment]
thank you for the workaround, it worked

**Comment by FloHu** [comment]
I have the exact same issue on Ubuntu 20.04.6 LTS and poetry version 1.7.1.

**Comment by kangqiwang** [comment]
Thanks @n00bsys0p

use Ubuntu 20, got same issue. it works


Cheers

**Comment by gmagannaDevelop** [comment]
I am running `Poetry v1.7.1 / Poetry-Core v1.8.1` on Debian 12 (bookworm) x86_64. I mainly use my computer in text mode and I confirm that poetry hangs when performing an install. 

When adding `-vvv`, it is effectively stuck in unlocking a keyring.

**Comment by kangqiwang** [comment]
> I am running `Poetry v1.7.1 / Poetry-Core v1.8.1` on Debian 12 (bookworm) x86_64. I mainly use my computer in text mode and I confirm that poetry hangs when performing an install.
> 
> When adding `-vvv`, it is effectively stuck in unlocking a keyring.

have you try ? it works for me
```
export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring
```

**Comment by ahollmann** [comment]
Same issue on Debian 12.

**Comment by Popkornium18** [comment]
If you're fine with running a prerelease version of poetry you could use [this setting](https://python-poetry.org/docs/master/configuration/#keyringenabled) to disable the keyring completely.

**Comment by namoshizun** [comment]
The workaround works. I wonder what is the root cause and whether there will be future Poetry versions addressing this issue 🤔

**Comment by damtharvey** [comment]
I ran into this today on Ubuntu 22.04. I think poetry might be trying to get the keyring through a GUI, which a lot of us don't have installed.

**Comment by alanwilter** [comment]
It should warn rather than spinning forever.

**Comment by n00bsys0p** [comment]
I found [this](https://python-poetry.org/docs/configuration#keyringenabled) Poetry setting, which seems likely to be the official way of disabling the keyring, but I haven't had a chance to try it yet.

**Comment by damtharvey** [comment]
Nice! Seems like it works. To clarify, you can change it with
`poetry config keyring.enabled false`

**Comment by alanwilter** [comment]
Good to know. The default should be `False`, just my 2 cents.

**Comment by agrajagco** [comment]
oh my, yes this is key, i was trying to troubleshoot a server based install and wondering if a keyring prompt was being expected to pop up where this was hanging (debian12).  Thanks for the poetry config example to disable this @damtharvey and @n00bsys0p

**Comment by ryanovas** [comment]
Just experienced this myself. Updating poetry and setting the config option to false seems to have worked for me, but there really should be some kind of warning or something instead of hanging forever unless you know to check the extra extra verbose logs...

**Comment by Popkornium18** [comment]
> some kind of warning or something instead of hanging forever unless you know to check the extra extra verbose logs...

I think that's fine. When an `ssh` command hangs the user is also expected to check the verbose output to see what is wrong. IMO the assumption that there is a working keyring is fine. Most users probably do not care about the keyring at all, so printing `checking keyring` for everyone would just add noise to the output for most people. Trying to detect a hanging keyring call from within `poetry` seems overkill to me.

Making the keyring opt-in would solve this issue, but also leave most people less secure since most people will not enable it. I would probably prefer to leave it opt-out. This is a rare issue that is rather easy to analyze and the fix is trivial (setting `keyring.enabled false`).

**Comment by StefanDenn3r** [comment]
I am new to poetry and was facing the exact same issue. It took me quite some time to figure out what is going wrong because I didn't know how long I was supposed to wait or how long checking the keyring would take. The verbose logs therefore only helped for checking where I might be stuck but not that I was actually stuck. 

Workaround fixed it.

**Comment by matt-forallepsilon** [comment]
+1

**Comment by ilyagr** [comment]
Looking at bugs like https://github.com/jaraco/keyring/issues/496, it might help if somebody ran `keyring --list-backends` and tried to debug what causes the issue to happen. Can it be reproduced with the "Command-line utility" described in https://pypi.org/project/keyring/? If so, it's likely a problem in the library.

I no longer have a computer on which this problem occurs, so I cannot do it unless I find a config where it happens.

**Comment by jeanlego** [comment]
ssh'd on a headless server got the same issue

> it might help if somebody ran keyring --list-backends 
hope this helps
```
❯ keyring --list-backends
keyring.backends.fail.Keyring (priority: 0)
keyring.backends.libsecret.Keyring (priority: 4.8)
keyring.backends.chainer.ChainerBackend (priority: 10)
keyring.backends.SecretService.Keyring (priority: 5)
```

**Comment by Youjin1985** [comment]
Still an issue on Ubuntu 22.04 and poetry 1.8.3. Please fix, I spend a lot of time to found this thread.

**Comment by 4ydan** [comment]
I encountered this problem on the latest raspian too.

**Comment by Popkornium18** [comment]
Poetry can't fix a broken keyring setup. Either fix the keyring or disable the use of the keyring in the poetry config.

**Comment by alanwilter** [comment]
@Popkornium18 The point is that `poetry` doesn’t provide any hints about where the issue might be, which can leave people feeling lost. In reality, the issue is often quite simple — once you know where to look. Many users aren’t familiar with `keyring` or even aware of what it is.

As discussed before, what if `poetry` could check for `keyring` and give a warning message?

**Comment by Popkornium18** [comment]
Poetry does provide hints in verbose modes. It states that it is trying to access the keyring and then it hangs.

The keyring access is part of a library that poetry uses. There is no simple way to test if an available keyring is broken. If it is broken the call to the library code just simply hangs an never returns to the poetry code that might try to handle it.

**Comment by henryk** [comment]
Just ran into it again (my last time was ~6 months ago) on a fresh raspberry pi.

Is there a way to limit the keyring initialization to just cases where poetry actually, you know, *needs* keyring access? To me it seems like a 5% case. In my 20 or so projects with poetry (most of them professionally) I have had to access a private repo exactly once. And even then we were using restricted deploy tokens which don't need a secrets manager.

**Comment by codethief** [comment]
@henryk 

> Is there a way to limit the keyring initialization to just cases where poetry actually, you know, needs keyring access?

Not that I know of but there is https://github.com/python-poetry/poetry/issues/8761 at least!

**Comment by andrewpollock** [comment]
We've just freshly migrated to Poetry from Pipenv and this isn't a very delightful first user experience...

**Comment by andrewpollock** [comment]
@ilyagr would you mind editing the workaround statement to mention `poetry config keyring.enabled false`? That seems like the more correct and durable workaround.

**Comment by rod7760** [comment]
Why would `keyring.enabled true` be a sane default? Improve security practices?

**Comment by radoering** [comment]
> Why would `keyring.enabled true` be a sane default? Improve security practices?

Two reasons:

1. Before the setting was introduced, keyring support had always been enabled. Thus, making `true` the default did not result in a behavior change.
2. Security by default.

Considering how many users have issues with keyring, maybe, we should consider changing the default to false in Poetry 2.0? Although, disabling a security setting by default feels bad...

**Comment by andrewpollock** [comment]
> Considering how many users have issues with keyring, maybe, we should consider changing the default to false in Poetry 2.0? Although, disabling a security setting by default feels bad...

In terms of UX, even emitting a line alerting the user to this potential for an indefinite hang (and the solution) would go a long way. Even better if the conditions are detectable, and the warning is contingent on them? Then you could explore conditionally falling back to a false setting

**Comment by codethief** [comment]
Adding to what @andrewpollock said, one could also add a prompt before "unlock keyring", warning the user and allowing them to choose between unlocking the keyring and skipping it. Though, I would argue the very first thing to do would be fixing https://github.com/python-poetry/poetry/issues/8761 as this might already solve a good 80% of all issues.

**Comment by alanwilter** [comment]
I got another similar problem: somehow, in hindsight, my `ssh-agent` was down and `poetry update` was taking forever. With `poetry update -vvv` I could see that I had a prompt asking for my `passphrase`!
I really wish `poetry` could do better in these cases.

**Comment by acochrane** [comment]
I also experience this issue with brand new poetry install with
`curl -sSL https://install.python-poetry.org | python3 -`

**Comment by ivhacks** [comment]
I believe I'm experiencing this also. Fresh venvs and poetry install via pipx. Originally I was trying to work from an existing `poetry.lock` file, and I got this traceback when I cancelled it (for those Googling this):
```
Exception ignored in: <module 'threading' from '/usr/lib/python3.12/threading.py'>
Traceback (most recent call last):
  File "/usr/lib/python3.12/threading.py", line 1592, in _shutdown
    atexit_call()
  File "/usr/lib/python3.12/concurrent/futures/thread.py", line 31, in _python_exit
    t.join()
  File "/usr/lib/python3.12/threading.py", line 1147, in join
    self._wait_for_tstate_lock()
  File "/usr/lib/python3.12/threading.py", line 1167, in _wait_for_tstate_lock
    if lock.acquire(block, timeout):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 ```
 I deleted `poetry.lock` and then it hung on Resolving dependencies.
 
Since I was logged in via SSH, I used the low-tech workaround of running down to the basement and doing it directly on the machine I was SSHed into.

**Comment by alexanderswerdlow** [comment]
Also experiencing this....a little unexpected given the promise of "dependency management made easy." Perhaps a simple fix could be to print a warning [regardless of mode] the first time the keyring is accessed after install?

**Comment by anirbanbasu** [comment]
> Confirming I'm getting exactly the same behaviour on an Ubuntu dev container with no X server. Both the following workarounds worked for me, but aren't ideal. I do have private repositories in my pyproject.toml, and have configured & tested working access via Github PAT stored in ~/.git-credentials.
> 
> * `export PYTHON_KEYRING_BACKEND=keyring.backends.null.Keyring`
> * `pyenv shell system` followed by `python3 -m keyring --disable`

This workaround worked well for me until I noticed that `git commit` gets stuck because it cannot obtain the commit signing password correctly. How can I undo `python3 -m keyring --disable`?

> Also experiencing this....a little unexpected given the promise of "dependency management made easy."
It has been over a year and there seems to be no solution to this. I just switched to `poetry` and this isn't a pleasant start.

**Comment by wolfgang000** [comment]
+1, I just encounter this same issue, please atleast add a warning or a error message.

**Comment by abn** [comment]
It's not an easy fix unfortunately, the issue usually is `secretstorage` dbus requests hanging and the requests happen in a second level dependency.

I am working on a fix to improve the status quo and present the potential error early on the application start. 

Would be good to have some testing volunteers to ensure the fix/mitigation works.

**Comment by abn** [comment]
Folks who have environments where you can reproduce this issue still with `2.0.1`, can you please try the fix at #10062? This should significantly improve status quo. Note that the fix might not yet work for folks who have a dbus-session, keyring available and a system prompter is not available.

### Using pipx
```sh
pipx install --suffix=@10062 'poetry @ git+https://github.com/python-poetry/poetry.git@refs/pull/10062/head'
```

### Using a container (podman | docker)
```sh
podman run --rm -i --entrypoint bash docker.io/python:latest <<EOF
set -xe
python -m pip install --disable-pip-version-check --root-user-action ignore -q git+https://github.com/python-poetry/poetry.git@refs/pull/10062/head
poetry new foobar
pushd foobar
poetry add -v pycowsay httpx
EOF
```
