### ISSUE TITLE
cannot install tensorflow-gpu to environment with pytorch CUDA version installed

### ISSUE THREAD

**Issue by FelipeDiaz98** [python-poetry/poetry#8695]
I have a currently working environment in which I somehow managed to install Pytorch with CUDA, as it is a little bit of a nightmare, for it I had to especify the download wheel and try like 4 times until installation was succesfull. Afterwards I have had no issues other than any further installation taking literally hours. Now I am trying to install tensorflow on the same environment using 'poetry add --group dev tensorflow="^2.8.0"', which tries to install tensorflow 2.12.0. But when doing so I keep getting very criptic errors that I can either not understand or don't seem to make much sense: either it seems poetry is trying to install tensorflow from the pytorch wheel, although it shouldn't as I never asked for it in the toml, or something about the python version which apparently needs to be higher than 3.7, but I am using 3.9 and my toml file asks for > 3.9.

Thanks in advance for the help, and please let me know if there's any important information I might have not provided.

Poetry version: 1.4.2
CUDA: 11.8
os: windows 10

toml file:
```
[tool.poetry]
name = "---"
version = "0.1.0"
description = ""
authors = ["-- <--@-->"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"

[tool.poetry.group.dev.dependencies]
torch = { version = "^2.0.0", source = "torch" }
torchvision = { version = "^0.15.1", source = "torch" }
torchaudio = { version = "^2.0.1", source = "torch" }
opencv-python = "^4.7.0"
fastai = "^2.7.12"
jupyter = "^1.0.0"
pytorch-lightning = "^2.0.3"
fs = "^2.4.16"
torchsummary = "^1.4.4"

[[tool.poetry.source]]
name = "torch"
url = "https://download.pytorch.org/whl/cu118"
default = false
secondary = true

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

error:
```
(drucksensor-py3.9) PS C:\Users\z004r7aj\drucksensor> poetry add --group dev tensorflow-gpu="^2.8.0"
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/

Updating dependencies
Resolving dependencies...
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Source (torch): Authorization error accessing https://download.pytorch.org/whl/cu118/tensorflow-gpu/
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping

Writing lock file

Package operations: 1 install, 0 updates, 0 removals

  • Installing tensorflow-gpu (2.12.0)
<c1>Source (torch):</c1> Authorization error accessing https://download.pytorch.org/whl/cu118/wheel/
<c1>Source (torch):</c1> Authorization error accessing https://download.pytorch.org/whl/cu118/setuptools/

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel

  Traceback (most recent call last):
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 35, in __init__
      parsed = _parse_requirement(requirement_string)
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 64, in parse_requirement
      return _parse_requirement(Tokenizer(source, rules=DEFAULT_RULES))
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 82, in _parse_requirement
      url, specifier, marker = _parse_requirement_details(tokenizer)
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 126, in _parse_requirement_details
      marker = _parse_requirement_marker(
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\_vendor\packaging\_parser.py", line 147, in _parse_requirement_marker
      tokenizer.raise_syntax_error(
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\_vendor\packaging\_tokenizer.py", line 165, in raise_syntax_error
      raise ParserSyntaxError(
  setuptools.extern.packaging._tokenizer.ParserSyntaxError: Expected end or semicolon (after name and no valid version specifier)
      python_version>"3.7"
                    ^

  The above exception was the direct cause of the following exception:

  Traceback (most recent call last):
    File "C:\Users\z004r7aj\AppData\Roaming\pypoetry\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\z004r7aj\AppData\Roaming\pypoetry\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\z004r7aj\AppData\Roaming\pypoetry\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
      self.run_setup()
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\build_meta.py", line 507, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
      exec(code, locals())
    File "<string>", line 40, in <module>
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\__init__.py", line 102, in setup
      _install_setup_requires(attrs)
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\__init__.py", line 73, in _install_setup_requires
      dist.parse_config_files(ignore_option_errors=True)
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\_virtualenv.py", line 21, in parse_config_files
      result = old_parse_config_files(self, *args, **kwargs)
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\dist.py", line 655, in parse_config_files
      self._finalize_requires()
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\dist.py", line 390, in _finalize_requires
      self._normalize_requires()
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\dist.py", line 405, in _normalize_requires
      self.install_requires = list(map(str, _reqs.parse(install_requires)))
    File "C:\Users\z004r7aj\AppData\Local\Temp\tmpcpozkqsf\.venv\lib\site-packages\setuptools\_vendor\packaging\requirements.py", line 37, in __init__
      raise InvalidRequirement(str(e)) from e
  setuptools.extern.packaging.requirements.InvalidRequirement: Expected end or semicolon (after name and no valid version specifier)
      python_version>"3.7"
                    ^


  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\chef.py:152 in _prepare
      148│
      149│                 error = ChefBuildError("\n\n".join(message_parts))
      150│
      151│             if error is not None:
    → 152│                 raise error from None
      153│
      154│             return path
      155│
      156│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with tensorflow-gpu (2.12.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "tensorflow-gpu (==2.12.0)"'.
```

Now, I also tried commenting out the pytorch installation wheel, for which I get the following:
```
(drucksensor-py3.9) PS C:\Users\z004r7aj\drucksensor> poetry add --group dev tensorflow-gpu="^2.8.0"

Updating dependencies
Resolving dependencies...
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping
Invalid requirement (python_version>"3.7") found in tensorflow-gpu-2.12.0 dependencies, skipping

Repository "torch" does not exist.
```

I also tried adding tensorflow-gpu into the toml file (with and without the torch wheel) and use 'poetry install', of course this made no difference. Should I just give up and create a different env and hope it does work out this time?

Thanks again 🙌

**Comment by dimbleby** [comment]
please read the error message, this is a problem with the tensorflow distribution and not a poetry bug

```
Note: This error originates from the build backend, and is likely not a problem with poetry but with tensorflow-gpu (2.12.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "tensorflow-gpu (==2.12.0)"'.
```

**Comment by FelipeDiaz98** [comment]
> please read the error message, this is a problem with the tensorflow-gpu distribution and not a poetry bug
> 
> ```
> Note: This error originates from the build backend, and is likely not a problem with poetry but with tensorflow-gpu (2.12.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --use-pep517 "tensorflow-gpu (==2.12.0)"'.
> ```

Okay, then I guess you are telling me that this
```
• Installing tensorflow-gpu (2.12.0)
<c1>Source (torch):</c1> Authorization error accessing https://download.pytorch.org/whl/cu118/wheel/
<c1>Source (torch):</c1> Authorization error accessing https://download.pytorch.org/whl/cu118/setuptools/
```
is the expected behaviour of the installation and poetry should indeed be trying to install tensorflow from the pytorch wheel? I would really appreaciate if you could provide me with a possible solution, even if it's not a bug it's still not working and I clearly need a solution which I don't posses. Or then where should I ask the question if it's not supposed to go here. Also I really don't think it's a problem with tensorflow as running the suggested pip command also doesn't work.

**Comment by dimbleby** [comment]
the suggested pip command doesn't work _because_ it's a problem with tensorflow-gpu: therefore neither pip nor poetry can install it.

if you want to know how to install tensorflow you should read tensorflow's documentation and use their support forums, that's not something that poetry can be responsible for

**Comment by FelipeDiaz98** [comment]
> the suggested pip command doesn't work _because_ it's a problem with tensorflow-gpu: therefore neither pip nor poetry can install it.
> 
> if you want to know how to install tensorflow you should read tensorflow's documentation and use their support forums, that's not something that poetry can be responsible for

thank you, I indeed looked up on tensorflow's forums and apparently there is a missing wheel in windows for one of the dependencies when installing tensorflow >2.11.X
