### ISSUE TITLE
ImportError: cannot import name 'get_embed_wheel' from 'virtualenv.seed.wheels.embed' (unknown location)

### ISSUE THREAD

**Issue by exister** [python-poetry/poetry#8716]
- **Poetry version**: 1.7.1
- **Python version**: 3.12
- **OS version and name**: OSX 13.6.1

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
Any poetry command fails with this traceback
```
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 283, in configure_env
    from poetry.console.commands.self.self_command import SelfCommand
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/commands/self/self_command.py", line 13, in <module>
    from poetry.utils.env import EnvManager
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/utils/env/__init__.py", line 9, in <module>
    from poetry.utils.env.base_env import Env
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/utils/env/base_env.py", line 15, in <module>
    from virtualenv.seed.wheels.embed import get_embed_wheel
ImportError: cannot import name 'get_embed_wheel' from 'virtualenv.seed.wheels.embed' (unknown location)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/poetry", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 411, in main
    exit_code: int = Application().run()
                     ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/cleo/application.py", line 338, in run
    self.render_error(e, io)
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 180, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 400, in _get_solution_provider_repository
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/mixology/solutions/providers/__init__.py", line 3, in <module>
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/mixology/solutions/providers/python_requirement_solution_provider.py", line 9, in <module>
    from poetry.puzzle.exceptions import SolverProblemError
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/puzzle/__init__.py", line 3, in <module>
    from poetry.puzzle.solver import Solver
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/puzzle/solver.py", line 16, in <module>
    from poetry.puzzle.provider import Indicator
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/puzzle/provider.py", line 27, in <module>
    from poetry.packages.direct_origin import DirectOrigin
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/packages/direct_origin.py", line 10, in <module>
    from poetry.inspection.info import PackageInfo
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/inspection/info.py", line 24, in <module>
    from poetry.utils.env import EnvCommandError
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/utils/env/__init__.py", line 9, in <module>
    from poetry.utils.env.base_env import Env
  File "/usr/local/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/utils/env/base_env.py", line 15, in <module>
    from virtualenv.seed.wheels.embed import get_embed_wheel
ImportError: cannot import name 'get_embed_wheel' from 'virtualenv.seed.wheels.embed' (unknown location)

```

**Comment by dimbleby** [comment]
since that code [certainly exists](https://github.com/pypa/virtualenv/blob/1fe291a38de49b107420367004727f17a535ae77/src/virtualenv/seed/wheels/embed/__init__.py#L43) - I suppose that you are wrong when you ticked the box saying that you installed using a recommended method.

please uninstall, and reinstall following the docs

**Comment by Secrus** [comment]
The paths in your stacktrace show that you used `brew` to install Poetry. The Poetry's Homebrew formula is not maintained by the Poetry team. You should report this issue to Homebrew.
