### ISSUE TITLE
future pacakge is not being installed

### ISSUE THREAD

**Issue by smrrazavian** [python-poetry/poetry#8768]
#### Environment Details
- **Poetry Version**: 1.7.1
- **Python Version**: 3.8.1.8
- **Operating System**: Fedora 39
- **pyproject.toml**: [GitHub - pyproject.toml](https://github.com/smrrazavian/comment-classification/blob/master/pyproject.toml)

#### Issue Checklist
- [ ] I am using the [latest stable Poetry version](https://github.com/python-poetry/poetry/releases/latest).
- [ ] This issue is not a duplicate of any [existing issues](https://github.com/python-poetry/poetry/issues).
- [ ] I have gone through the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/).
- [ ] I ran the command in debug mode (`-vvv`) and have provided the output below.

#### Issue Description
**Problem:**
While installing the `future` package (version 0.18.3) using Poetry, an error occurs during the package installation process.

**Steps to Reproduce:**
1. Run `poetry lock -n && poetry export --without-hashes > requirements.txt`.
2. Execute `poetry install -n`.

**Error Output:**
```bash
• Installing future (0.18.3): Failed

  CalledProcessError

  Command '['/data/projects/comment-classification/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/data/projects/comment-classification/.venv', '--no-deps', '/home/smrrazavian/.cache/pypoetry/artifacts/80/9e/43/6239285a143ee79885e7db7225cc5b41e5e619b4f23a226c414485f644/future-0.18.3.tar.gz']' returned non-zero exit status 1.

  at ~/.pyenv/versions/3.8.18/lib/python3.8/subprocess.py:516 in run
       512│             # We don't call process.wait() as .__exit__ does that for us.
       513│             raise
       514│         retcode = process.poll()
       515│         if check and retcode:
    →  516│             raise CalledProcessError(retcode, process.args,
       517│                                      output=stdout, stderr=stderr)
       518│     return CompletedProcess(process.args, retcode, stdout, stderr)
       519│ 
       520│ 

The following error occurred when trying to handle this error:


  EnvCommandError

  Command ['/data/projects/comment-classification/.venv/bin/python', '-m', 'pip', 'install', '--use-pep517', '--disable-pip-version-check', '--isolated', '--no-input', '--prefix', '/data/projects/comment-classification/.venv', '--no-deps', '/home/smrrazavian/.cache/pypoetry/artifacts/80/9e/43/6239285a143ee79885e7db7225cc5b41e5e619b4f23a226c414485f644/future-0.18.3.tar.gz'] errored with the following return code 1, and output: 
  Processing /home/smrrazavian/.cache/pypoetry/artifacts/80/9e/43/6239285a143ee79885e7db7225cc5b41e5e619b4f23a226c414485f644/future-0.18.3.tar.gz
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
    Preparing metadata (pyproject.toml): started
    Preparing metadata (pyproject.toml): finished with status 'error'
    error: subprocess-exited-with-error
    
    × Preparing metadata (pyproject.toml) did not run successfully.
    │ exit code: 1
    ╰─> [66 lines of output]
        running dist_info
        creating /tmp/pip-modern-metadata-bvfy1sbp/future.egg-info
        writing /tmp/pip-modern-metadata-bvfy1sbp/future.egg-info/PKG-INFO
        writing dependency_links to /tmp/pip-modern-metadata-bvfy1sbp/future.egg-info/dependency_links.txt
        writing entry points to /tmp/pip-modern-metadata-bvfy1sbp/future.egg-info/entry_points.txt
        writing top-level names to /tmp/pip-modern-metadata-bvfy1sbp/future.egg-info/top_level.txt
        writing manifest file '/tmp/pip-modern-metadata-bvfy1sbp/future.egg-info/SOURCES.txt'
        reading manifest file '/tmp/pip-modern-metadata-bvfy1sbp/future.egg-info/SOURCES.txt'
        reading manifest template 'MANIFEST.in'
        warning: no files found matching '*.au' under directory 'tests'
        warning: no files found matching '*.gif' under directory 'tests'
        warning: no files found matching '*.txt' under directory 'tests'
        adding license file 'LICENSE.txt'
        writing manifest file '/tmp/pip-modern-metadata-bvfy1sbp/future.egg-info/SOURCES.txt'
        creating '/tmp/pip-modern-metadata-bvfy1sbp/future-0.18.3.dist-info'
        Traceback (most recent call last):
          File "/data/projects/comment-classification/.venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
            main()
          File "/data/projects/comment-classification/.venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
            json_out['return_val'] = hook(**hook_input['kwargs'])
          File "/data/projects/comment-classification/.venv/lib/python3.8/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
            return hook(metadata_directory, config_settings)
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 366, in prepare_metadata_for_build_wheel
            self.run_setup()
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 480, in run_setup
            super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 311, in run_setup
            exec(code, locals())
          File "<string>", line 159, in <module>
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 103, in setup
            return distutils.core.setup(**attrs)
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 185, in setup
            return run_commands(dist)
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
            dist.run_commands()
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
            self.run_command(cmd)
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 963, in run_command
            super().run_command(command)
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
            cmd_obj.run()
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/command/dist_info.py", line 96, in run
            bdist_wheel = self.get_finalized_command('bdist_wheel')
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/_distutils/cmd.py", line 304, in get_finalized_command
            cmd_obj = self.distribution.get_command_obj(command, create)
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/_distutils/dist.py", line 860, in get_command_obj
            klass = self.get_command_class(command)
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/dist.py", line 710, in get_command_class
            self.cmdclass[command] = cmdclass = ep.load()
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/setuptools/_vendor/importlib_metadata/__init__.py", line 208, in load
            module = import_module(match.group('module'))
          File "/home/smrrazavian/.pyenv/versions/3.8.18/lib/python3.8/importlib/__init__.py", line 127, in import_module
            return _bootstrap._gcd_import(name[level:], package, level)
          File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
          File "<frozen importlib._bootstrap>", line 991, in _find_and_load
          File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
          File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
          File "<frozen importlib._bootstrap_external>", line 843, in exec_module
          File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 27, in <module>
            from .macosx_libfile import calculate_macosx_platform_tag
          File "/tmp/pip-build-env-_3wpdifk/overlay/lib/python3.8/site-packages/wheel/macosx_libfile.py", line 43, in <module>
            import ctypes
          File "/home/smrrazavian/.pyenv/versions/3.8.18/lib/python3.8/ctypes/__init__.py", line 7, in <module>
            from _ctypes import Union, Structure, Array
        ModuleNotFoundError: No module named '_ctypes'
        [end of output]
    
    note: This error originates from a subprocess, and is likely not a problem with pip.
  error: metadata-generation-failed
  
  × Encountered error while generating package metadata.
  ╰─> See above for output.
  
  note: This is an issue with the package mentioned above, not pip.
  hint: See above for details.
  

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/utils/env.py:1540 in _run
      1536│                 output = subprocess.check_output(
      1537│                     command, stderr=subprocess.STDOUT, env=env, **kwargs
      1538│                 )
      1539│         except CalledProcessError as e:
    → 1540│             raise EnvCommandError(e, input=input_)
      1541│ 
      1542│         return decode(output)
      1543│ 
      1544│     def execute(self, bin: str, *args: str, **kwargs: Any) -> int:

The following error occurred when trying to handle this error:


  PoetryException

  Failed to install /home/smrrazavian/.cache/pypoetry/artifacts/80/9e/43/6239285a143ee79885e7db7225cc5b41e5e619b4f23a226c414485f644/future-0.18.3.tar.gz

  at ~/.local/share/pypoetry/venv/lib/python3.8/site-packages/poetry/utils/pip.py:58 in pip_install
       54│ 
       55│     try:
       56│         return environment.run_pip(*args)
       57│     except EnvCommandError as e:
    →  58│         raise PoetryException(f"Failed to install {path.as_posix()}") from e
       59│ 
```

**Comment by dimbleby** [comment]
You have configured poetry to use the old pip-based installer, recommend not doing that.

But anyway: please read the error message.  This is not a poetry bug (or a pip bug).  You either do not have the needed dependencies installed to build the `future` package from source, or `future` is mis-packaged.

Please close.
