### ISSUE TITLE
future (0.18.3) not supporting PEP 517 builds.

### ISSUE THREAD

**Issue by sonnguyen129** [python-poetry/poetry#8787]
- **Poetry version**: 1.7.1
- **Python version**: 3.10.7
- **OS version and name**: Windows 10
- **pyproject.toml**: 

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [ ] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

Here is my log

```
• Installing future (0.18.3): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  Traceback (most recent call last):
    File "C:\Users\Zbook G3\AppData\Roaming\pypoetry\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\Zbook G3\AppData\Roaming\pypoetry\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "C:\Users\Zbook G3\AppData\Roaming\pypoetry\venv\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
      return hook(config_settings)
    File "C:\Users\ZBOOKG~1\AppData\Local\Temp\tmp61yquc4k\.venv\lib\site-packages\setuptools\build_meta.py", line 325, in get_requires_for_build_wheel
      return self._get_build_requires(config_settings, requirements=['wheel'])
    File "C:\Users\ZBOOKG~1\AppData\Local\Temp\tmp61yquc4k\.venv\lib\site-packages\setuptools\build_meta.py", line 295, in _get_build_requires
      self.run_setup()
    File "C:\Users\ZBOOKG~1\AppData\Local\Temp\tmp61yquc4k\.venv\lib\site-packages\setuptools\build_meta.py", line 480, in run_setup
      super(_BuildMetaLegacyBackend, self).run_setup(setup_script=setup_script)
    File "C:\Users\ZBOOKG~1\AppData\Local\Temp\tmp61yquc4k\.venv\lib\site-packages\setuptools\build_meta.py", line 311, in run_setup
      exec(code, locals())
    File "<string>", line 86, in <module>
  ModuleNotFoundError: No module named 'src.future'
  

  at ~\AppData\Roaming\pypoetry\venv\lib\site-packages\poetry\installation\chef.py:164 in _prepare
      160│
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│
      163│             if error is not None:
    → 164│                 raise error from None
      165│
      166│             return path
      167│
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with future (0.18.3) not supporting PEP 517 builds. You can verify th
is by running 'pip wheel --no-cache-dir --use-pep517 "future (==0.18.3)"'.
```
I also try "pip wheel --no-cache-dir --use-pep517 "future (==0.18.3)" but everything is OK

**Comment by dimbleby** [comment]
this is a future bug, not a poetry bug.  And it already is tracked on their issue tracker.  Please close.
