### ISSUE TITLE
build-system.requires ignored for tool.poetry.build.script

### ISSUE THREAD

**Issue by cavedon** [python-poetry/poetry#8807]
- **Poetry version**: 1.7.1
- **Python version**: 3.10.12
- **OS version and name**: Ubuntu 22.04
- **pyproject.toml**: [pyproject.toml](https://gist.github.com/cavedon/a1b03ecf26d20187958095f7a61116f2#file-pyproject-toml)
- **build.py**: [build.py](https://gist.github.com/cavedon/a1b03ecf26d20187958095f7a61116f2#file-build-py)

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

In my [pyproject.toml](https://gist.github.com/cavedon/a1b03ecf26d20187958095f7a61116f2#file-pyproject-toml) I have 

```
[tool.poetry.build]
script = "build.py"
generate-setup-file = false

[build-system]
requires = ["poetry-core", "protoc-exe"]
build-backend = "poetry.core.masonry.api"
```

and my [build.py](https://gist.github.com/cavedon/a1b03ecf26d20187958095f7a61116f2#file-build-py) invokes the `protoc` command, which is provided by the `protoc-exe` module, listed in `[build-system]`.

This works fine with `poetry install --sync`:
```
 % poetry install --sync
Installing dependencies from lock file

Preparing build environment with build-system requirements poetry-core, protoc-exe
Installing the current project: mypoetrytest (0.1.0)
```

But it fails with `poetry build`:
```
 % poetry build     
Preparing build environment with build-system requirements poetry-core, protoc-exe
Building mypoetrytest (0.1.0)
Traceback (most recent call last):
  File "/home/cavedon/mypoetrytest/build.py", line 27, in <module>
    build()
  File "/home/cavedon/mypoetrytest/build.py", line 17, in build
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'

Command '['/tmp/tmp0g_4j74h/.venv/bin/python', 'build.py']' returned non-zero exit status 1.
```
([full output with `-vvv`](https://gist.github.com/cavedon/a1b03ecf26d20187958095f7a61116f2#file-poetry-build-vvv))

In the case of `poetry build`, the command `protoc` is in the `bin` directory of the virtualenv, but the `bin` directory is not added to the PATH environment variable.

Setting `generate-setup-file = true` does not help.

**Comment by dimbleby** [comment]
duplicate #8749 please close

(even better there is a suggested fix in there, so as well as closing this duplicate please feel free to submit a merge request)

**Comment by dimbleby** [comment]
you should not use `poetry run` in your build script; or anyway definitely not without declaring `poetry` as a build requirement.

just call `protoc` directly - that is what is being installed in the isolated build environment.

please close

**Comment by cavedon** [comment]
> you should not use `poetry run` in your build script; or anyway definitely not without declaring `poetry` as a build requirement.
> 
> just call `protoc` directly - that is what is being installed in the isolated build environment.

Ah, I am sorry, I did not realize I still had `poetry run` in my `build.py`. That was a left-over from my debugging. I have removed it, re-run the tests, and update the description of this issue.

> duplicate #8749 please close

Thanks for pointing for that issue. Indeed it seems to be caused by the fact that the `bin` directory of the virtualenv is not in the PATH when `build.py` is executed. Let me do some tests and confirm it is indeed exactly the same issue and if so I will close as duplicate.

**Comment by cavedon** [comment]
I do _not_ think this is a duplicate of #8749:
- I tried to patch as suggested in https://github.com/python-poetry/poetry/issues/8749#issuecomment-1841516573, but it does help.
```
index 3edb225c..47ecdc51 100644
--- a/src/poetry/inspection/info.py
+++ b/src/poetry/inspection/info.py
@@ -44,9 +44,8 @@ source = '{source}'
 dest = '{dest}'
 
 with build.env.DefaultIsolatedEnv() as env:
-    builder = build.ProjectBuilder(
-        source_dir=source,
-        python_executable=env.python_executable,
+    builder = build.ProjectBuilder.from_isolated_env(
+        env, source,
         runner=pyproject_hooks.quiet_subprocess_runner,
     )
     env.install(builder.build_system_requires)
```
- `PEP517_META_BUILD` is not the path of my failure. The issue seems to be in [poetry-core](https://github.com/python-poetry/poetry-core/blob/main/src/poetry/core/masonry/builders/wheel.py#L261), in my case.

**Comment by dimbleby** [comment]
I deleted the comment referencing #8749, I also don't think this is a duplicate.  Sorry for confusion.

You should set `generate-setup-file = true` if you want to use the isolated environment during build.

**Comment by cavedon** [comment]
Setting `generate-setup-file = true` fails in a similar way:
```
 % poetry build
Preparing build environment with build-system requirements poetry-core, protoc-exe, setuptools
Building mypoetrytest (0.1.0)
A setup.py file already exists. Using it.
Traceback (most recent call last):
  File "/home/cavedon/mypoetrytest/setup.py", line 25, in <module>
    build(setup_kwargs)
  File "/home/cavedon/mypoetrytest/build.py", line 17, in build
    subprocess.check_call(
  File "/usr/lib/python3.10/subprocess.py", line 364, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib/python3.10/subprocess.py", line 345, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'protoc'

Command '['/tmp/tmpokfeqd7d/.venv/bin/python', '/home/cavedon/mypoetrytest/setup.py', 'build', '-b', '/home/cavedon/mypoetrytest/build', '--build-purelib', '/home/cavedon/mypoetrytest/build/lib', '--build-platlib', '/home/cavedon/mypoetrytest/build/lib.linux-x86_64-cpython-310']' returned non-zero exit status 1.
```

However this patch solves the issue:
```
diff --git a/src/poetry/utils/env/__init__.py b/src/poetry/utils/env/__init__.py
index ed22bb37..a4211591 100644
--- a/src/poetry/utils/env/__init__.py
+++ b/src/poetry/utils/env/__init__.py
@@ -1,6 +1,7 @@
 from __future__ import annotations
 
 from contextlib import contextmanager
+import os
 from pathlib import Path
 from typing import TYPE_CHECKING
 
@@ -97,7 +98,12 @@ def build_environment(
                 assert io is not None
                 io.write_error_line("")
 
-            yield venv
+            orig_environ = os.environ
+            os.environ = venv.get_temp_environ(environ=os.environ)
+            try:
+                yield venv
+            finally:
+                os.environ = orig_environ
     else:
         yield env
 ```

**Comment by dimbleby** [comment]
I do not reproduce:
```
$ poetry build
Preparing build environment with build-system requirements poetry-core, protoc-exe
Building mypoetrytest (0.1.0)
fatal: not a git repository (or any of the parent directories): .git
fatal: not a git repository (or any of the parent directories): .git
Traceback (most recent call last):
  File "/home/dch/foo/setup.py", line 2, in <module>
    from setuptools import setup
ModuleNotFoundError: No module named 'setuptools'

Command '['/tmp/tmp6ijhbpq3/.venv/bin/python', '/home/dch/foo/setup.py', 'build', '-b', '/home/dch/foo/build', '--build-purelib', '/home/dch/foo/build/lib', '--build-platlib', '/home/dch/foo/build/lib.linux-x86_64-cpython-310']' returned non-zero exit status 1.
```
which I guess is expected while setuptools is not declared as a build requirement

when I add it the error becomes `Could not make proto path relative: protobuf/myproto.proto: No such file or directory
`, which is to say everything is working as expected

**Comment by dimbleby** [comment]
I don't know what the right fix is but I'm pretty sure that it's not going to be what you suggest - updating `os.environ` looks horrid

**Comment by dimbleby** [comment]
another approach would just not to try and do this via build requirements - there's at least a case that installing executables isn't really what build requirements are for

eg if you were trying to use the compiler from your build script, you wouldn't expect to be able to list `gcc` in the python project's build requirements.

you could just tell people that having `protoc` in their path is a requirement to install your package.

**Comment by cavedon** [comment]
> another approach would just not to try and do this via build requirements - there's at least a case that installing executables isn't really what build requirements are for

I think it would be a reasonable expectation that if I need package X to build my module, I can add it to the build-requirements. 
And indeed that's the case when building via `poetry install`.
The difference in behavior is also confusing.

> eg if you were trying to use the compiler from your build script, you wouldn't expect to be able to list `gcc` in the python project's build requirements.

It would not be a horrible idea, I think

> you could just tell people that having `protoc` in their path is a requirement to install your package.

This adds friction. I am building a pure python module that needs some processing to be built. The tool to do the processing is available as pypi package. Why not allowing users to specify that in the build-requirements instead of having to write it somewhere the user needs read and execute manually?

**Comment by abn** [comment]
Relates to https://github.com/python-poetry/poetry-core/pull/319

**Comment by wtdcode** [comment]
Having the same issue. What's the current status?

**Comment by abn** [comment]
This was resolved by #10059. You can try the latest version on the `main` branch.

```sh
podman run --rm -i --entrypoint bash docker.io/python:latest <<EOF
set -xe
python -m pip install --disable-pip-version-check --root-user-action ignore -q 'git+https://github.com/python-poetry/poetry.git@main'
poetry new foobar
pushd foobar

cat > pyproject.toml <<TOML
[project]
name = "foobar"
version = "0.1.0"
description = ""
authors = [
    {name = "Some One",email = "some.one@somewhere.com"}
]
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
]

[tool.poetry.build]
script = "build.py"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0", "protoc-exe", "PySide6-Essentials"]
build-backend = "poetry.core.masonry.api"
TOML

cat > build.py <<BUILDPY
import subprocess

subprocess.check_call(["protoc", "--help"])


def main():
    print("Running pyside6-uic --help...")
    subprocess.run(
        ["pyside6-uic", "--help"],
        check=True,  # Raise exception on failure
        capture_output=True,
    )
    print("Running protoc --help ...")
    subprocess.run(
        ["protoc", "--help"],
        check=True,  # Raise exception on failure
        capture_output=True,
    )


if __name__ == "__main__":
    main()
BUILDPY

poetry build -f wheel
EOF
```

```console
+ python -m pip install --disable-pip-version-check --root-user-action ignore -q git+https://github.com/python-poetry/poetry.git@main
+ poetry new foobar
Created package foobar in foobar
+ pushd foobar
/foobar /
+ cat
+ cat
+ poetry build -f wheel
Creating virtualenv foobar-lWDpn5M1-py3.13 in /root/.cache/pypoetry/virtualenvs
Building foobar (0.1.0)
Building wheel
```
