### ISSUE TITLE
`ModuleNotFoundError: No module named 'platformdirs'` after `brew install poetry`

### ISSUE THREAD

**Issue by kraktus** [python-poetry/poetry#8853]
Hey, thanks for the good work

- **Poetry version**: v1.7.1
- **Python version**:  py3.12 
- **OS version and name**:macOS 14.1.2

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, ~~installed using a [recommended method](https://python-poetry.org/docs/#installation).~~ Apparently brew is not listed as recommended, surprising as it's the de-facto package manager for macOS
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [x] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue
```shell
$ poetry --version -vvv
Traceback (most recent call last):
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/cleo/application.py", line 327, in run
    exit_code = self._run(io)
                ^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 188, in _run
    self._load_plugins(io)
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 354, in _load_plugins
    manager.load_plugins()
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/plugins/plugin_manager.py", line 38, in load_plugins
    self._load_plugin_entry_point(ep)
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/plugins/plugin_manager.py", line 76, in _load_plugin_entry_point
    plugin = ep.load()  # type: ignore[no-untyped-call]
             ^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.12/3.12.1/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 994, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry_plugin_export/plugins.py", line 7, in <module>
    from poetry_plugin_export.command import ExportCommand
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry_plugin_export/command.py", line 12, in <module>
    from poetry_plugin_export.exporter import Exporter
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry_plugin_export/exporter.py", line 11, in <module>
    from poetry.repositories.http_repository import HTTPRepository
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/repositories/__init__.py", line 4, in <module>
    from poetry.repositories.repository_pool import RepositoryPool
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/repositories/repository_pool.py", line 11, in <module>
    from poetry.config.config import Config
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/config/config.py", line 18, in <module>
    from poetry.locations import CONFIG_DIR
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/locations.py", line 9, in <module>
    from platformdirs import user_cache_path
ModuleNotFoundError: No module named 'platformdirs'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/homebrew/bin/poetry", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 411, in main
    exit_code: int = Application().run()
                     ^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/cleo/application.py", line 338, in run
    self.render_error(e, io)
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 180, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/console/application.py", line 400, in _get_solution_provider_repository
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/mixology/solutions/providers/__init__.py", line 3, in <module>
    from poetry.mixology.solutions.providers.python_requirement_solution_provider import (
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/mixology/solutions/providers/python_requirement_solution_provider.py", line 9, in <module>
    from poetry.puzzle.exceptions import SolverProblemError
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/puzzle/__init__.py", line 3, in <module>
    from poetry.puzzle.solver import Solver
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/puzzle/solver.py", line 16, in <module>
    from poetry.puzzle.provider import Indicator
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/puzzle/provider.py", line 27, in <module>
    from poetry.packages.direct_origin import DirectOrigin
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/packages/direct_origin.py", line 10, in <module>
    from poetry.inspection.info import PackageInfo
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/inspection/info.py", line 24, in <module>
    from poetry.utils.env import EnvCommandError
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/utils/env/__init__.py", line 9, in <module>
    from poetry.utils.env.base_env import Env
  File "/opt/homebrew/Cellar/poetry/1.7.1/libexec/lib/python3.12/site-packages/poetry/utils/env/base_env.py", line 15, in <module>
    from virtualenv.seed.wheels.embed import get_embed_wheel
  File "/opt/homebrew/lib/python3.12/site-packages/virtualenv/__init__.py", line 3, in <module>
    from .run import cli_run, session_via_cli
  File "/opt/homebrew/lib/python3.12/site-packages/virtualenv/run/__init__.py", line 7, in <module>
    from virtualenv.app_data import make_app_data
  File "/opt/homebrew/lib/python3.12/site-packages/virtualenv/app_data/__init__.py", line 8, in <module>
    from platformdirs import user_data_dir
ModuleNotFoundError: No module named 'platformdirs'
```

Similar to https://github.com/python-poetry/poetry/issues/4493 but I'm not installing `poetry` in the env it's managing

For now I don't know if it's a `poetry` or `brew` issue. I uninstalled and re-installed, without luck.

**Comment by dimbleby** [comment]
homebrew packaging of poetry does not happen from this repository, please take your bug report to homebrew

please close

**Comment by kraktus** [comment]
Yeah I think the issue is on the brew side. Will reopen in case it's not

**Comment by rkhan-cfs** [comment]
I don't know where this issue is reported on the brew side but I managed to solve it by installing platformdirs directly with brew:

`brew install python-platformdirs`

Note that after this I also had to symlink the installation to my python directory

**Comment by kraktus** [comment]
Seems like a case of https://xkcd.com/979/, since I managed to fix it but not explain.

I had `python-platformdirs` installed already but symlinked to python 3.11. I had to uninstall it then re-install and finally symlink it
