### ISSUE TITLE
numpy: Error importing numpy: you should not try to import numpy from its source directory; please exit the numpy source tree, and relaunch your python interpreter from there.

### ISSUE THREAD

**Issue by devfinwiz** [python-poetry/poetry#8870]
- **Poetry version**:  1.7.1
- **Python version**:  3.10.11
- **OS version and name**:  Windows 11
- **pyproject.toml**: 

```
[tool.poetry]
name = "finmaestro"
version = "0.1.0"
description = "A FastApi for the mighty Fin-Maestro by Dev_Finwiz."
authors = ["devfinwiz <devjuneja43@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.108.0"
uvicorn = "^0.25.0"
pydantic = "^2.5.3"
requests = "^2.31.0"
numpy = "^1.26.3"
pandas = "^2.1.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

```

- [x] I am on the [latest](https://github.com/python-poetry/poetry/releases/latest) stable Poetry version, installed using a [recommended method](https://python-poetry.org/docs/#installation).
- [x] I have searched the [issues](https://github.com/python-poetry/poetry/issues) of this repo and believe that this is not a duplicate.
- [x] I have consulted the [FAQ](https://python-poetry.org/docs/faq/) and [blog](https://python-poetry.org/blog/) for any relevant entries or release notes.
- [ ] If an exception occurs when executing a command, I executed it again in debug mode (`-vvv` option) and have included the output below.

## Issue

I am using pandas in my python code. However I added pandas and numpy to my project using poetry add command. But when I run the script I get this long error: 

```
Process SpawnProcess-1:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 314, in _bootstrap
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\multiprocessing\process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\finmaestro-ZQx55jaC-py3.10\lib\site-packages\uvicorn\_subprocess.py", line 76, in subprocess_started
    target(sockets=sockets)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\finmaestro-ZQx55jaC-py3.10\lib\site-packages\uvicorn\server.py", line 61, in run      
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\finmaestro-ZQx55jaC-py3.10\lib\site-packages\uvicorn\server.py", line 68, in serve    
    config.load()
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\finmaestro-ZQx55jaC-py3.10\lib\site-packages\uvicorn\config.py", line 467, in load    
    self.loaded_app = import_from_string(self.app)
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\finmaestro-ZQx55jaC-py3.10\lib\site-packages\uvicorn\importer.py", line 21, in import_from_string
    module = importlib.import_module(module_str)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.3056.0_x64__qbz5n2kfra8p0\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\Dev.Juneja\Downloads\fin-maestro.py\main.py", line 5, in <module>
    from modules.data_toolkit.nse.nifty_indices import router as nse_router
  File "C:\Users\Dev.Juneja\Downloads\fin-maestro.py\modules\data_toolkit\nse\nifty_indices.py", line 4, in <module>
    import pandas as pd
  File "C:\Users\Dev.Juneja\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\Local\pypoetry\Cache\virtualenvs\finmaestro-ZQx55jaC-py3.10\lib\site-packages\pandas\__init__.py", line 29, in <module>
    raise ImportError(
ImportError: Unable to import required dependencies:
numpy: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
```

Note: This only happens with poetry and is not an issue of numpy.

**Comment by dimbleby** [comment]
lots of us use numpy and pandas etc via poetry without problem.

It is hard to guess what you have done to get into this state, but you should assume that it is almost certainly not a poetry bug.

**Comment by devfinwiz** [comment]
Again,
When I replicated the same thing on Python 3.9, it worked just fine. Idk why this random stuff keeps happening when I use python 3.10.... 
Closing the issue.

**Comment by devfinwiz** [comment]
https://github.com/numpy/numpy/issues/24965#issuecomment-1871270034

Someone else was stuck with the same thing :)...

**Comment by Phobia-Cosmos** [comment]
> [numpy/numpy#24965 (comment)](https://github.com/numpy/numpy/issues/24965#issuecomment-1871270034)
> 
> Someone else was stuck with the same thing :)...

I don't think the problem is fully resolved from the post.I run in jupyter lab and suddenly run into the error when i restart one kernel, confused.

**Comment by kylefoley76** [comment]
I also have this problem

**Comment by dimbleby** [comment]
you're in the wrong place, there is no reason to think that this has anything to do with poetry.

eg the original report over in numpy was from a pip installation

**Comment by devfinwiz** [comment]
I faced this issue because my system(not personal laptop) lacked some necessary permissions maybe. I did not face this issue when I switched to my personal setup...
