### ISSUE TITLE
Poetry incompatible with dotenv

### ISSUE THREAD

**Issue by rjurney** [python-poetry/poetry#9142]
Poetry doesn't work with `dotenv`:

```bash
Using version ^0.0.5 for dotenv

Updating dependencies
Resolving dependencies... (0.2s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing dotenv (0.0.5): Preparing...
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/__init__.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/archive_util.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/depends.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/dist.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/extension.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/package_index.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/sandbox.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/__init__.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/alias.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/bdist_egg.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/bdist_rpm.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/build_ext.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/build_py.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/develop.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/easy_install.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/egg_info.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/install.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/install_egg_info.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/install_lib.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/install_scripts.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/register.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/rotate.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/saveopts.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/sdist.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/setopt.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/test.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/upload.py over existing file
Installing /var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/command/upload_docs.py over existing   - Installing dotenv (0.0.5): Failed

  ChefBuildError

  Backend 'setuptools.build_meta:__legacy__' is not available.
  
  Traceback (most recent call last):
    File "/Users/r0j07qf/Library/Application Support/pipx/venvs/poetry/lib/python3.12/site-packages/pyproject_hooks/_in_process/_in_process.py", line 77, in _build_backend
      obj = import_module(mod_path)
    File "/opt/miniconda3/envs/api/lib/python3.10/importlib/__init__.py", line 126, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
    File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
    File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 883, in exec_module
    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
    File "/var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/__init__.py", line 2, in <module>
      from setuptools.extension import Extension, Library
    File "/var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/extension.py", line 5, in <module>
      from setuptools.dist import _get_unpatched
    File "/var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/_virtualenv.py", line 91, in exec_module
      old(module)
    File "/var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/dist.py", line 10, in <module>
      from setuptools.compat import numeric_types, basestring
  ImportError: cannot import name 'numeric_types' from 'setuptools.compat' (/var/folders/n2/hl7k7_390zbdm8c7f4sydzhr0000gq/T/tmp0gg74fl6/.venv/lib/python3.10/site-packages/setuptools/compat/__init__.py)
  

  at ~/Library/Application Support/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with dotenv (0.0.5) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "dotenv (==0.0.5)"'.
```

_Originally posted by @github-actions[bot] in https://github.com/python-poetry/poetry/issues/8444#issuecomment-1970314171_

**Comment by dimbleby** [comment]
> Poetry incompatible with dotenv

Correct.  But as the error mesage says: this is a `dotenv` problem, not a `poetry` problem.

Since the last release of that project was in 2015 I expect it is not what you wanted in the first place.  Maybe `python-dotenv`?

Please close.

**Comment by rjurney** [comment]
Whoops, I needed python-dotenv.
