### ISSUE TITLE
pip breaks when installing dependencies in non-package mode

### ISSUE THREAD

**Issue by ar-qun** [python-poetry/poetry#9316]
### Description

If `pyproject.toml`
```toml
[tool.poetry]
package-mode = false
```
Then `pip install .` fails with:

```python
  error: subprocess-exited-with-error
  
  × Preparing metadata (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [14 lines of output]
      Traceback (most recent call last):
        File "/home/user/project/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/home/user/project/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user/project/venv/lib/python3.9/site-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 149, in prepare_metadata_for_build_wheel
          return hook(metadata_directory, config_settings)
        File "/tmp/pip-build-env-oe6wt9ed/overlay/lib/python3.9/site-packages/poetry/core/masonry/api.py", line 43, in prepare_metadata_for_build_wheel
          builder = WheelBuilder(poetry)
        File "/tmp/pip-build-env-oe6wt9ed/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/wheel.py", line 62, in __init__
          super().__init__(poetry, executable=executable)
        File "/tmp/pip-build-env-oe6wt9ed/overlay/lib/python3.9/site-packages/poetry/core/masonry/builders/builder.py", line 45, in __init__
          raise RuntimeError(
      RuntimeError: Building a package is not possible in non-package mode.
      [end of output]

```

### Workarounds

Install the package even if not needed.

### Poetry Installation Method

pip

### Operating System

Ubuntu (WSL2)

### Poetry Version

1.8.2

### Poetry Configuration

```bash session
cache-dir = "/home/user/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/user/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = true
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
N/A running pip
```

**Comment by Secrus** [comment]
You can't install the current project with `pip` if it's non-package mode. Use `poetry install`.
