### ISSUE TITLE
`ModuleNotFoundError: No module named 'package'` when running a script declared in `pyproject.toml`

### ISSUE THREAD

**Issue by HenestrosaDev** [python-poetry/poetry#9514]
### Description

My project structure is as follows (it can also be seen [here](https://github.com/HenestrosaDev/indentation-converter)):

```
/
│    scripts.py
│    pyproject.toml
│
├───src
│        └───indentation_converter 
│                       __init__.py
│                       indentation_converter.py
│
└───tests
              test_indentation_converter.py
```

I have the following script in the `pyproject.toml` file:

```toml
[tool.poetry.scripts]
test = "scripts:test"
```

`scripts.py`:

```python
import subprocess


def test():
    subprocess.run(["python", "-m", "unittest", "discover", "tests"])
```

I run `poetry install` and then `poetry run test`, but I get the following error:

```
(venv) PS D:\Mio\Proyectos\Python\indentation-converter> poetry run test                             
E
======================================================================
ERROR: test_indentation_converter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_indentation_converter
Traceback (most recent call last):
  File "C:\Users\Gunze\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Gunze\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "D:\Mio\Proyectos\Python\indentation-converter\tests\test_indentation_converter.py", line 4, in <module>
    from indentation_converter import (
ModuleNotFoundError: No module named 'indentation_converter'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

However, when I run `poetry run python -m unittest discover tests`, all tests pass successfully. What is wrong with the script?

### Workarounds

I'm not aware of this

### Poetry Installation Method

pip

### Operating System

Windows 11

### Poetry Version

1.8.3

### Poetry Configuration

```bash session
cache-dir = "C:\\Users\\Gunze\\AppData\\Local\\pypoetry\\Cache"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
repositories.testpypi.url = "https://test.pypi.org/legacy/"
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\Gunze\AppData\Local\pypoetry\Cache\virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
(venv) PS D:\Mio\Proyectos\Python\indentation-converter> poetry -vvv run test
Loading configuration file C:\Users\Gunze\AppData\Roaming\pypoetry\config.toml
Loading configuration file C:\Users\Gunze\AppData\Roaming\pypoetry\auth.toml
Using virtualenv: D:\Mio\Proyectos\Python\indentation-converter\venv
E
======================================================================
ERROR: test_indentation_converter (unittest.loader._FailedTest)
----------------------------------------------------------------------
ImportError: Failed to import test module: test_indentation_converter
Traceback (most recent call last):
  File "C:\Users\Gunze\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "C:\Users\Gunze\AppData\Local\Programs\Python\Python310\lib\unittest\loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "D:\Mio\Proyectos\Python\indentation-converter\tests\test_indentation_converter.py", line 4, in <module>
    from indentation_converter import (
ModuleNotFoundError: No module named 'indentation_converter'


----------------------------------------------------------------------
Ran 1 test in 0.000s

FAILED (errors=1)
```

**Comment by HenestrosaDev** [comment]
I fixed this by installing `pytest` as a dev package instead of using the `unittest` package.
