### ISSUE TITLE
error on dependency propagation

### ISSUE THREAD

**Issue by iBuitron** [python-poetry/poetry#9610]
### Issue Kind

Unclear documentation

### Existing Link

https://python-poetry.org/docs/managing-dependencies/

### Description

Hi!

Context:

I have several packages:

quickbio_books
quickbio
quickbio_frontend (base on Dash from plotly)
------------------------------

quickbio uses quickbio_books

``` 
# quickbio project.toml

[tool.poetry.dependencies]
# others libs

[tool.poetry.group.dev.dependencies]
data-management-tools = {path = "../../data_management_tools", develop = true}
quickbio-books = {path = "../quickBio-books", develop = true}

```

quickbio_fronted uses quickbio

```
[tool.poetry.dependencies]
# others libs

[tool.poetry.group.dev.dependencies]
quickbio = {path = "../quickBio", extras = ["dev"], develop = true}
data-management-tools = {path = "../../data_management_tools", extras = ["dev"], develop = true}
ft-utils = {path = "../ft_utils", extras = ["dev"], develop = true}
auth = {path = "../auth", extras = ["dev"], develop = true}

```
When i run quickbio_frontend it gives to me the error:

```
Traceback (most recent call last):
  File "/home/reveur/python/environmental/quickBio-frontend/quickbio_frontend/app.py", line 14, in <module>
    from quickbio_frontend.src.pages.shell_props import appshell_props
  File "/home/reveur/python/environmental/quickBio-frontend/quickbio_frontend/src/pages/shell_props.py", line 4, in <module>
    from .diversity._shell_props import shell_props as diversity_shell_props
  File "/home/reveur/python/environmental/quickBio-frontend/quickbio_frontend/src/pages/diversity/__init__.py", line 1, in <module>
    from quickbio.names.process import AllowAnalysis
  File "/home/reveur/python/environmental/quickBio/quickbio/__init__.py", line 10, in <module>
    from .process.search.country_book.country_book import CountryBook
  File "/home/reveur/python/environmental/quickBio/quickbio/process/search/country_book/country_book.py", line 6, in <module>
    import quickbio_books as qbio_books
ModuleNotFoundError: No module named 'quickbio_books'
```

According to my understanding,
if I already have quickbio_book installed in quickbio, and if I already have quickbio installed in quickbio_frontend, isn't quickbio_book supposed to be available in quickbio_frontend already?

Note: I'm working on everything locally at the moment (dev mode)

Am I doing something wrong? Any solution to avoid having to install quickbio_books in quickbio_frontend?

all are installed as packages (poetry install) 

I have used "extra dev" which is supposed to fix it as I understand it but it doesn't.

**Comment by Secrus** [comment]
Groups are not extras. Groups are dev dependencies releated only to the project they are declared in.

**Comment by iBuitron** [comment]
> Groups are not extras. Groups are dev dependencies releated only to the project they are declared in.

How poetry handles dependency propagation as I mentioned above:

if quickbio has quickbio_books installed.
if quickbio_frontend has quickbio installed

when running quickbio_frontend it should have quickbio_books installed (from quickbio)

how is this handled?
I emphasize this because other libraries from quickbio_books do not generate errors, only quickbio_books and this is because it is installed from dev mode (--editable)

any solution?

**Comment by iBuitron** [comment]
i fix that with

on quickbio_frontend

poetry add --editable ../quicbio --group dev (where is my quickbio_books)
