### ISSUE TITLE
Poetry is not handling rpath for pip installed object files 

### ISSUE THREAD

**Issue by scrufulufugus** [python-poetry/poetry#9635]
### Description

When installing `torch` in a poetry env it pulls in pypy packages that provide runtime shared libraries. This seems to work fine in a `venv` but running from within poetry's virtualenv throws an exception. E.g.

```sh
$ poetry add torch numpy
$ poetry shell
$ python -c "import torch"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cache/pypoetry/virtualenvs/test-7x-8T2db-py3.12/lib64/python3.12/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory

$ find /home/user/.cache/pypoetry/virtualenvs/test-7x-8T2db-py3.12/ -name "libcudnn.so.9"
/home/user/.cache/pypoetry/virtualenvs/test-7x-8T2db-py3.12/lib/python3.12/site-packages/nvidia/cudnn/lib/libcudnn.so.9
```

### Workarounds

venv has no problems handling pip installed object files:

```sh
$ python3.12 -m venv venv
$ . venv/bin/activate
$ pip install numpy==2.0.1 torch==2.4.0
$ python -c "import torch" # No error
```

### Poetry Installation Method

pipx

### Operating System

RHEL 9.4 (Plow)

### Poetry Version

Poetry (version 1.8.3)

### Poetry Configuration

```bash session
cache-dir = "/home/user/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/user/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "test"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
numpy = "^2.0.1"
torch = "^2.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

```bash session
$ poetry -vvv run python -c "import torch" # Or poetry shell -> python -c "import torch"
Loading configuration file /home/user/.config/pypoetry/config.toml
The currently activated Python version 3.9.18 is not supported by the project (^3.12).
Trying to find and use a compatible version.
Trying python3
Trying python3.12
Using python3.12 (3.12.1)
Virtualenv test-7x-8T2db-py3.12 already exists.
Using virtualenv: /home/user/.cache/pypoetry/virtualenvs/test-7x-8T2db-py3.12
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/user/.cache/pypoetry/virtualenvs/test-7x-8T2db-py3.12/lib64/python3.12/site-packages/torch/__init__.py", line 290, in <module>
    from torch._C import *  # noqa: F403
    ^^^^^^^^^^^^^^^^^^^^^^
ImportError: libcudnn.so.9: cannot open shared object file: No such file or directory

$ find /home/user/.cache/pypoetry/virtualenvs/test-7x-8T2db-py3.12/ -name "libcudnn.so.9"
/home/user/.cache/pypoetry/virtualenvs/test-7x-8T2db-py3.12/lib/python3.12/site-packages/nvidia/cudnn/lib/libcudnn.so.9
```

**Comment by dimbleby** [comment]
does not reproduce

**Comment by scrufulufugus** [comment]
Strange, the syscall is failing:

```sh
$ strace -e trace=openat python -c "import torch"
...
openat(AT_FDCWD, "/home/user/.cache/pypoetry/virtualenvs/test-7x-8T2db-py3.12/lib64/python3.12/site-packages/torch/lib/libcudnn.so.9", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/user/.cache/pypoetry/virtualenvs/test-7x-8T2db-py3.12/lib64/python3.12/site-packages/torch/libcudnn.so.9", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/home/user/.cache/pypoetry/virtualenvs/test-7x-8T2db-py3.12/lib64/python3.12/site-packages/torch/lib/libcudnn.so.9", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
...
```

Guess it must be something on my side. Will close.
