### ISSUE TITLE
PEP 517 build error

### ISSUE THREAD

**Issue by msto** [python-poetry/poetry#9706]
### Description

Hi,

I am encountering the PEP 517 build error for a package which does support PEP 517 builds.

Poetry error:

```console
  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^
    File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 74, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen os>", line 679, in __getitem__
  KeyError: 'PEP517_BUILD_BACKEND'
  

  at /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with datrie (0.8.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "datrie (==0.8.2)"'.
```

I have verified that `datrie` **does** support PEP 517 builds.

```console
$ pip wheel --no-cache-dir --use-pep517 "datrie (==0.8.2)"
Collecting datrie==0.8.2
  Downloading datrie-0.8.2.tar.gz (63 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: datrie
  Building wheel for datrie (pyproject.toml) ... done
  Created wheel for datrie: filename=datrie-0.8.2-cp311-cp311-macosx_10_13_x86_64.whl size=151478 sha256=493f599481c214541f98
b3f8c915c8def786d9b521cab14206c5651503b77e0e
  Stored in directory: /private/tmp/pip-ephem-wheel-cache-qf9spymy/wheels/8b/20/f4/aeacf0184f20e22473a01257c56c74cc976e1cd838
a01de6d5
Successfully built datrie
```

I am only encountering this error in GitHub Actions and cannot replicate locally. 

I'd appreciate any help resolving - thanks!

### Workarounds

Not that I am aware of.

### Poetry Installation Method

pipx

### Operating System

ubuntu-latest

### Poetry Version

Poetry (version 1.8.2)

### Poetry Configuration

```bash session
cache-dir = "/home/runner/.cache/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = false
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /home/runner/.cache/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
Stack trace:

  8  /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/poetry/installation/executor.py:281 in _execute_operation
      279│ 
      280│             try:
    → 281│                 result = self._do_execute_operation(operation)
      282│             except EnvCommandError as e:
      283│                 if e.e.returncode == -2:

  7  /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/poetry/installation/executor.py:391 in _do_execute_operation
      389│             return 0
      390│ 
    → 391│         result: int = getattr(self, f"_execute_{method}")(operation)
      392│ 
      393│         if result != 0:

  6  /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/poetry/installation/executor.py:516 in _execute_install
      514│ 
      515│     def _execute_install(self, operation: Install | Update) -> int:
    → 516│         status_code = self._install(operation)
      517│ 
      518│         self._save_url_reference(operation)

  5  /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/poetry/installation/executor.py:554 in _install
      552│             archive = self._download_link(operation, Link(package.source_url))
      553│         else:
    → 554│             archive = self._download(operation)
      555│ 
      556│         operation_message = self.get_operation_message(operation)

  4  /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/poetry/installation/executor.py:746 in _download
      744│             self._yanked_warnings.append(message)
      745│ 
    → 746│         return self._download_link(operation, link)
      747│ 
      748│     def _download_link(self, operation: Install | Update, link: Link) -> Path:

  3  /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/poetry/installation/executor.py:781 in _download_link
      779│             self._write(operation, message)
      780│ 
    → 781│             archive = self._chef.prepare(archive, output_dir=original_archive.parent)
      782│ 
      783│         # Use the original archive to provide the correct hash.

  2  /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/poetry/installation/chef.py:123 in prepare
      121│             return self._prepare(archive, destination=destination, editable=editable)
      122│ 
    → 123│         return self._prepare_sdist(archive, destination=output_dir)
      124│ 
      125│     def _prepare(

  1  /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/poetry/installation/chef.py:194 in _prepare_sdist
      192│             destination.mkdir(parents=True, exist_ok=True)
      193│ 
    → 194│             return self._prepare(
      195│                 sdist_dir,
      196│                 destination,

  ChefBuildError

  Backend subprocess exited when trying to invoke build_wheel
  
  Traceback (most recent call last):
    File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
      main()
    File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 335, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
      return _build_backend().build_wheel(wheel_directory, config_settings,
             ^^^^^^^^^^^^^^^^
    File "/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/pyproject_hooks/_in_process/_in_process.py", line 74, in _build_backend
      ep = os.environ['PEP517_BUILD_BACKEND']
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^
    File "<frozen os>", line 679, in __getitem__
  KeyError: 'PEP517_BUILD_BACKEND'
  

  at /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with datrie (0.8.2) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "datrie (==0.8.2)"'.

Installing /opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/LICENSE over existing file
```

**Comment by msto** [comment]
Note the complete install log exceeded the GitHub character limit and is attached here

[poetry_install.log](https://github.com/user-attachments/files/17111695/poetry_install.log)
