### ISSUE TITLE
When I run `poetry install`, I get an error saying `FileNotFoundError: [Errno 2] No such file or directory: 'project dir\.venv\\Lib\\site-packages\\pkg_resources\\tests\\data\\my-test-package_unpacked-egg\\my_test_package-1.0-py3.7.egg\\EGG-INFO\\dependency_links.txt'`

### ISSUE THREAD

**Issue by nikhil12322** [python-poetry/poetry#9797]
### Description

When I run `poetry install` when the virtual environment isn't created, I get the following error message: `FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nikhil\\Projects\\Coding Projects\\Python Projects\\Packages\\Types\\Poetry Plugins\\poetry_plugin_multiple_in_project_venvs\\.venv\\Lib\\site-packages\\pkg_resources\\tests\\data\\my-test-package_unpacked-egg\\my_test_package-1.0-py3.7.egg\\EGG-INFO\\dependency_links.txt'`

The virtual environment is still created, just without the dependencies and the activation files. The second time I run `poetry install`, it is successful, and all the dependencies get installed. However, the activation files still aren't created.

Also, this isn't a duplicate of #6841 because Poetry isn't trying to access `python` but a file called `dependency_links.txt`.

### Workarounds

I don't think there are any workarounds.

### Poetry Installation Method

pipx

### Operating System

Windows 11

### Poetry Version

1.8.4

### Poetry Configuration

```bash session
cache-dir = "C:\\Users\\nikhil\\AppData\\Local\\pypoetry\\Cache"  # C:\Users\nikhil\NonRegisteredPrograms\poetry\Cache
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = true
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}\\virtualenvs"  # C:\Users\nikhil\NonRegisteredPrograms\poetry\virtualenvs
virtualenvs.prefer-active-python = true
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Python Sysconfig

```bash session
Platform: "win-amd64"
Python version: "3.11"
Current installation scheme: "nt"

Paths:
        data = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9"
        include = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Include"
        platinclude = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Include"
        platlib = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages"
        platstdlib = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Lib"
        purelib = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Lib\site-packages"
        scripts = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Scripts"
        stdlib = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Lib"

Variables:
        BINDIR = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9"
        BINLIBDEST = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Lib"
        EXE = ".exe"
        EXT_SUFFIX = ".cp311-win_amd64.pyd"
        INCLUDEPY = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Include"
        LIBDEST = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Lib"
        TZPATH = ""
        VERSION = "311"
        VPATH = "..\.."
        abiflags = ""
        base = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9"
        exec_prefix = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9"
        installed_base = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9"
        installed_platbase = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9"
        platbase = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9"
        platlibdir = "DLLs"
        prefix = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9"
        projectbase = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9"
        py_version = "3.11.9"
        py_version_nodot = "311"
        py_version_nodot_plat = "311"
        py_version_short = "3.11"
        srcdir = "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9"
        userbase = "C:\Users\nikhil\AppData\Roaming\Python"
```

### Example pyproject.toml

```TOML
[tool.poetry]
name = "poetry-plugin-multiple-in-project-venvs"
version = "0.1.0"
description = "Multiple in-project Poetry virtual environments!"
authors = ["Nikhil Narayan <167934187+nikhil12322@users.noreply.github.com>"]
license = "GNU General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
poetry = "^1.8.3"

[tool.poetry.plugins."poetry.plugin"]
multiple_in_project_venvs = "poetry_plugin_multiple_in_project_venvs:MultipleInProjectVenvsPlugin"

[tool.semantic_release]
version_toml = [
    "pyproject.toml:tool.poetry.version",
]
branch = "main"
changelog_file = "CHANGELOG.md"
build_command = "pip install poetry && poetry build"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
```

### Poetry Runtime Logs

```bash session
Loading configuration file C:\Users\nikhil\NonRegisteredPrograms\poetry\config.toml
Trying to detect current active python executable as specified in the config.
Found: C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\python.exe
Creating virtualenv poetry-plugin-multiple-in-project-venvs in C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv
[virtualenv] find interpreter for spec PythonSpec(path=C:/Users/nikhil/.pyenv/pyenv-win/versions/3.11.9/python.exe)
[virtualenv] filesystem is not case-sensitive
[filelock:filelock] Attempting to acquire lock 2281704835984 on C:\Users\nikhil\AppData\Local\pypa\virtualenv\py_info\1\7b32c4fd4bae350f9237f691c3493639ded6833d8540b0182e69392a3147a659.lock
[filelock:filelock] Lock 2281704835984 acquired on C:\Users\nikhil\AppData\Local\pypa\virtualenv\py_info\1\7b32c4fd4bae350f9237f691c3493639ded6833d8540b0182e69392a3147a659.lock
[virtualenv] got python info of %s from (WindowsPath('C:/Users/nikhil/.pyenv/pyenv-win/versions/3.11.9/python.exe'), WindowsPath('C:/Users/nikhil/AppData/Local/pypa/virtualenv/py_info/1/7b32c4fd4bae350f9237f691c3493639ded6833d8540b0182e69392a3147a659.json'))
[filelock:filelock] Attempting to release lock 2281704835984 on C:\Users\nikhil\AppData\Local\pypa\virtualenv\py_info\1\7b32c4fd4bae350f9237f691c3493639ded6833d8540b0182e69392a3147a659.lock
[filelock:filelock] Lock 2281704835984 released on C:\Users\nikhil\AppData\Local\pypa\virtualenv\py_info\1\7b32c4fd4bae350f9237f691c3493639ded6833d8540b0182e69392a3147a659.lock
[virtualenv] proposed PythonInfo(spec=CPython3.11.9.final.0-64, exe=C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\python.exe, platform=win32, version='3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252)
[virtualenv] accepted PythonInfo(spec=CPython3.11.9.final.0-64, exe=C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\python.exe, platform=win32, version='3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]', encoding_fs_io=utf-8-cp1252)
[virtualenv] symlink on filesystem does not work
[virtualenv] create virtual environment via CPython3Windows(dest=C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv, clear=False, no_vcs_ignore=False, global=False)
[virtualenv] create folder C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Lib\site-packages
[virtualenv] create folder C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Scripts
[virtualenv] write C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\pyvenv.cfg
[virtualenv]    home = C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9
[virtualenv]    implementation = CPython
[virtualenv]    version_info = 3.11.9.final.0
[virtualenv]    virtualenv = 20.26.6
[virtualenv]    include-system-site-packages = false
[virtualenv]    base-prefix = C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9
[virtualenv]    base-exec-prefix = C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9
[virtualenv]    base-executable = C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\python.exe
[virtualenv] copy C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Lib\venv\scripts\nt\python.exe to C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Scripts\python.exe
[virtualenv] copy C:\Users\nikhil\.pyenv\pyenv-win\versions\3.11.9\Lib\venv\scripts\nt\pythonw.exe to C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Scripts\pythonw.exe
[virtualenv] create virtualenv import hook file C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Lib\site-packages\_virtualenv.pth
[virtualenv] create C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Lib\site-packages\_virtualenv.py
[virtualenv] ============================== target debug ==============================
[virtualenv] debug via 'C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Scripts\python.exe' 'C:\Users\nikhil\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\create\debug.py'
[virtualenv] {
[virtualenv]   "sys": {
[virtualenv]     "executable": "C:\\Users\\nikhil\\Projects\\Coding Projects\\Python Projects\\Packages\\Types\\Poetry Plugins\\poetry_plugin_multiple_in_project_venvs\\.venv\\Scripts\\python.exe",
[virtualenv]     "_base_executable": "C:\\Users\\nikhil\\.pyenv\\pyenv-win\\versions\\3.11.9\\python.exe",
[virtualenv]     "prefix": "C:\\Users\\nikhil\\Projects\\Coding Projects\\Python Projects\\Packages\\Types\\Poetry Plugins\\poetry_plugin_multiple_in_project_venvs\\.venv",
[virtualenv]     "base_prefix": "C:\\Users\\nikhil\\.pyenv\\pyenv-win\\versions\\3.11.9",
[virtualenv]     "real_prefix": null,
[virtualenv]     "exec_prefix": "C:\\Users\\nikhil\\Projects\\Coding Projects\\Python Projects\\Packages\\Types\\Poetry Plugins\\poetry_plugin_multiple_in_project_venvs\\.venv",
[virtualenv]     "base_exec_prefix": "C:\\Users\\nikhil\\.pyenv\\pyenv-win\\versions\\3.11.9",
[virtualenv]     "path": [
[virtualenv]       "C:\\Users\\nikhil\\.pyenv\\pyenv-win\\versions\\3.11.9\\python311.zip",
[virtualenv]       "C:\\Users\\nikhil\\.pyenv\\pyenv-win\\versions\\3.11.9\\DLLs",
[virtualenv]       "C:\\Users\\nikhil\\.pyenv\\pyenv-win\\versions\\3.11.9\\Lib",
[virtualenv]       "C:\\Users\\nikhil\\.pyenv\\pyenv-win\\versions\\3.11.9",
[virtualenv]       "C:\\Users\\nikhil\\Projects\\Coding Projects\\Python Projects\\Packages\\Types\\Poetry Plugins\\poetry_plugin_multiple_in_project_venvs\\.venv",
[virtualenv]       "C:\\Users\\nikhil\\Projects\\Coding Projects\\Python Projects\\Packages\\Types\\Poetry Plugins\\poetry_plugin_multiple_in_project_venvs\\.venv\\Lib\\site-packages"
[virtualenv]     ],
[virtualenv]     "meta_path": [
[virtualenv]       "<class '_virtualenv._Finder'>",
[virtualenv]       "<class '_frozen_importlib.BuiltinImporter'>",
[virtualenv]       "<class '_frozen_importlib.FrozenImporter'>",
[virtualenv]       "<class '_frozen_importlib_external.PathFinder'>"
[virtualenv]     ],
[virtualenv]     "fs_encoding": "utf-8",
[virtualenv]     "io_encoding": "cp1252"
[virtualenv]   },
[virtualenv]   "version": "3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]",
[virtualenv]   "makefile_filename": "C:\\Users\\nikhil\\.pyenv\\pyenv-win\\versions\\3.11.9\\Lib\\config\\Makefile",
[virtualenv]   "os": "<module 'os' (frozen)>",
[virtualenv]   "site": "<module 'site' (frozen)>",
[virtualenv]   "datetime": "<module 'datetime' from 'C:\\\\Users\\\\nikhil\\\\.pyenv\\\\pyenv-win\\\\versions\\\\3.11.9\\\\Lib\\\\datetime.py'>",
[virtualenv]   "math": "<module 'math' (built-in)>",
[virtualenv]   "json": "<module 'json' from 'C:\\\\Users\\\\nikhil\\\\.pyenv\\\\pyenv-win\\\\versions\\\\3.11.9\\\\Lib\\\\json\\\\__init__.py'>"
[virtualenv] }
[virtualenv] add seed packages via FromAppData(download=False, pip=bundle, setuptools=bundle, via=copy, app_data_dir=C:\Users\nikhil\AppData\Local\pypa\virtualenv)
[virtualenv] got embed update of distribution %s from ('setuptools', WindowsPath('C:/Users/nikhil/AppData/Local/pypa/virtualenv/wheel/3.11/embed/3/setuptools.json'))
[virtualenv] got embed update of distribution %s from ('pip', WindowsPath('C:/Users/nikhil/AppData/Local/pypa/virtualenv/wheel/3.11/embed/3/pip.json'))
[virtualenv] install setuptools from wheel C:\Users\nikhil\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\seed\wheels\embed\setuptools-75.1.0-py3-none-any.whl via CopyPipInstall
[virtualenv] install pip from wheel C:\Users\nikhil\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\seed\wheels\embed\pip-24.2-py3-none-any.whl via CopyPipInstall
[filelock:filelock] Attempting to acquire lock 2281686538512 on C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\setuptools-75.1.0-py3-none-any.lock
[filelock:filelock] Attempting to acquire lock 2281686538656 on C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\pip-24.2-py3-none-any.lock
[filelock:filelock] Lock 2281686538512 acquired on C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\setuptools-75.1.0-py3-none-any.lock
[filelock:filelock] Lock 2281686538656 acquired on C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\pip-24.2-py3-none-any.lock
[filelock:filelock] Attempting to release lock 2281686538512 on C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\setuptools-75.1.0-py3-none-any.lock
[filelock:filelock] Attempting to release lock 2281686538656 on C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\pip-24.2-py3-none-any.lock
[filelock:filelock] Lock 2281686538512 released on C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\setuptools-75.1.0-py3-none-any.lock
[filelock:filelock] Lock 2281686538656 released on C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\pip-24.2-py3-none-any.lock
[virtualenv] copy directory C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\pip-24.2-py3-none-any\pip to C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Lib\site-packages\pip
[virtualenv] copy C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\setuptools-75.1.0-py3-none-any\distutils-precedence.pth to C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Lib\site-packages\distutils-precedence.pth
[virtualenv] copy directory C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\setuptools-75.1.0-py3-none-any\pkg_resources to C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Lib\site-packages\pkg_resources
[virtualenv] copy directory C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\pip-24.2-py3-none-any\pip-24.2.dist-info to C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Lib\site-packages\pip-24.2.dist-info
[virtualenv] copy C:\Users\nikhil\AppData\Local\pypa\virtualenv\wheel\3.11\image\1\CopyPipInstall\pip-24.2-py3-none-any\pip-24.2.virtualenv to C:\Users\nikhil\Projects\Coding Projects\Python Projects\Packages\Types\Poetry Plugins\poetry_plugin_multiple_in_project_venvs\.venv\Lib\site-packages\pip-24.2.virtualenv
[virtualenv] generated console scripts pip.exe pip3.exe pip-3.11.exe pip3.11.exe

  Stack trace:

  13  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:327 in run
       325│ 
       326│             try:
     → 327│                 exit_code = self._run(io)
       328│             except BrokenPipeError:
       329│                 # If we are piped to another process, it may close early and send a

  12  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\poetry\console\application.py:190 in _run
       188│         self._load_plugins(io)
       189│
     → 190│         exit_code: int = super()._run(io)
       191│         return exit_code
       192│

  11  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:431 in _run
       429│             io.input.interactive(interactive)
       430│
     → 431│         exit_code = self._run_command(command, io)
       432│         self._running_command = None
       433│

  10  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:473 in _run_command
       471│ 
       472│         if error is not None:
     → 473│             raise error
       474│
       475│         return terminate_event.exit_code

   9  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\cleo\application.py:454 in _run_command
       452│
       453│         try:
     → 454│             self._event_dispatcher.dispatch(command_event, COMMAND)
       455│
       456│             if command_event.command_should_run():

   8  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\cleo\events\event_dispatcher.py:26 in dispatch
        24│ 
        25│         if listeners:
     →  26│             self._do_dispatch(listeners, event_name, event)
        27│
        28│         return event

   7  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\cleo\events\event_dispatcher.py:85 in _do_dispatch
        83│                 break
        84│
     →  85│             listener(event, event_name, self)
        86│
        87│     def _sort_listeners(self, event_name: str) -> None:

   6  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\poetry\console\application.py:299 in configure_env
       297│ 
       298│         env_manager = EnvManager(poetry, io=io)
     → 299│         env = env_manager.create_venv()
       300│
       301│         if env.is_venv() and io.is_verbose():

   5  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\poetry\utils\env\env_manager.py:592 in create_venv
       590│ 
       591│         if create_venv:
     → 592│             self.build_venv(
       593│                 venv,
       594│                 executable=executable,

   4  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\poetry\utils\env\env_manager.py:678 in build_venv
       676│         args.append(str(path))
       677│
     → 678│         cli_result = virtualenv.cli_run(args, setup_logging=False)
       679│
       680│         # Exclude the venv folder from from macOS Time Machine backups

   3  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\run\__init__.py:33 in cli_run
        31│     of_session = session_via_cli(args, options, setup_logging, env)
        32│     with of_session:
     →  33│         of_session.run()
        34│     return of_session
        35│

   2  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\run\session.py:45 in run
        43│     def run(self):
        44│         self._create()
     →  45│         self._seed()
        46│         self._activate()
        47│         self.creator.pyenv_cfg.write()

   1  ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\run\session.py:58 in _seed
        56│         if self.seeder is not None and self.seeder.enabled:
        57│             logging.info("add seed packages via %s", self.seeder)
     →  58│             self.seeder.run(self.creator)
        59│
        60│     def _activate(self):

  RuntimeError

  failed to build image setuptools because:
  Traceback (most recent call last):
    File "C:\Users\nikhil\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py", line 57, in _install
      installer.install(creator.interpreter.version_info)
    File "C:\Users\nikhil\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\base.py", line 37, in install
      self._sync(filename, into)
    File "C:\Users\nikhil\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\seed\embed\via_app_data\pip_install\copy.py", line 13, in _sync
      copy(src, dst)
    File "C:\Users\nikhil\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\util\path\_sync.py", line 41, in copy
      method(str(src), str(dest))
    File "C:\Users\nikhil\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\util\path\_sync.py", line 52, in copytree
      shutil.copy(src_f, dest_f)
    File "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.12.4\Lib\shutil.py", line 435, in copy
      copyfile(src, dst, follow_symlinks=follow_symlinks)
    File "C:\Users\nikhil\.pyenv\pyenv-win\versions\3.12.4\Lib\shutil.py", line 262, in copyfile
      with open(dst, 'wb') as fdst:
           ^^^^^^^^^^^^^^^
  FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\nikhil\\Projects\\Coding Projects\\Python Projects\\Packages\\Types\\Poetry Plugins\\poetry_plugin_multiple_in_project_venvs\\.venv\\Lib\\site-packages\\pkg_resources\\tests\\data\\my-test-package_unpacked-egg\\my_test_package-1.0-py3.7.egg\\EGG-INFO\\dependency_links.txt'
  

  at ~\NonRegisteredPrograms\Programs\pipx\venvs\poetry\Lib\site-packages\virtualenv\seed\embed\via_app_data\via_app_data.py:71 in run
       67│                 messages = [f"failed to build image {', '.join(exceptions.keys())} because:"]
       68│                 for value in exceptions.values():
       69│                     exc_type, exc_value, exc_traceback = value
       70│                     messages.append("".join(traceback.format_exception(exc_type, exc_value, exc_traceback)))
    →  71│                 raise RuntimeError("\n".join(messages))
       72│
       73│     @contextmanager
       74│     def _get_seed_wheels(self, creator):  # noqa: C901
       75│         name_to_whl, lock, fail = {}, Lock(), {}
```

**Comment by dimbleby** [comment]
Looks like a virtualenv error, you should report it to that project 

Eg similar https://github.com/pypa/virtualenv/issues/2361

**Comment by nikhil12322** [comment]
Well, if I create the virtualenv using `py -m virtualenv .venv`, the command is successful, and all the activation files get created.

**Comment by dimbleby** [comment]
That seems irrelevant?

Again: this looks like a virtualenv problem, where I suggest that the issue is too-long windows paths.

**Comment by nikhil12322** [comment]
Also, it's only a problem with this project.

**Comment by dimbleby** [comment]
I don't know another way to say it so let's go one more time: this error is coming from virtualenv and is likely because Windows does not like your overlong paths.

Take iyour report to virtualenv, or move the project to somewhere with a shorter path, or configure windows to allow long paths.

There is nothing that can be done from this repository to help you.

**Comment by nikhil12322** [comment]
I moved the project from `Types\Poetry Plugins` to `Poetry Plugins`, and it worked. Before, the length of the path was 264, which is greater than 260. Now, the length is 258, which is less than 260.
