### ISSUE TITLE
Poetry not user-friendly behaviour – raises exceptions on wrong commands

### ISSUE THREAD

**Issue by solesensei** [python-poetry/poetry#9920]
### Description

Poetry is not very user-friendly. It constantly throws exceptions with tracebacks when you give it wrong commands.

Example:
`poetry cache clear` <-- (this command is not correct, and I need to use `poetry cache clear my-cache`)

Expected output
```
Some message that my command was not correct.
Show the closest command matching, or suggest `poetry cache clear --help` to show help
```

<details><summary>What I really getting in output</summary>
<p>

```
Traceback (most recent call last):
  File "/Users/sole/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 316, in run
    exit_code = self._run(io)
                ^^^^^^^^^^^^^
  File "/Users/sole/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 190, in _run
    exit_code: int = super()._run(io)
                     ^^^^^^^^^^^^^^^^
  File "/Users/sole/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 420, in _run
    exit_code = self._run_command(command, io)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/sole/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 462, in _run_command
    raise error
  File "/Users/sole/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 446, in _run_command
    exit_code = command.run(io)
                ^^^^^^^^^^^^^^^
  File "/Users/sole/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/commands/base_command.py", line 115, in run
    io.input.validate()
  File "/Users/sole/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/io/inputs/input.py", line 110, in validate
    raise CleoMissingArgumentsError(
cleo.exceptions.CleoMissingArgumentsError: Not enough arguments (missing: "cache")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sole/.local/bin/poetry", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/sole/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 411, in main
    exit_code: int = Application().run()
                     ^^^^^^^^^^^^^^^^^^^
  File "/Users/sole/.local/pipx/venvs/poetry/lib/python3.12/site-packages/cleo/application.py", line 327, in run
    self.render_error(e, io)
  File "/Users/sole/.local/pipx/venvs/poetry/lib/python3.12/site-packages/poetry/console/application.py", line 180, in render_error
    self.set_solution_provider_repository(self._get_solution_provider_repository())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Application' object has no attribute 'set_solution_provider_repository'. Did you mean: '_get_solution_provider_repository'?
```

</p>
</details> 

### Workarounds

None

### Poetry Installation Method

pipx

### Operating System

MacOS Sonoma 14.6.1

### Poetry Version

1.8.3

### Poetry Configuration

```bash session
cache-dir = "/Users/sole/Library/Caches/pypoetry"
experimental.system-git-client = false
installer.max-workers = null
installer.modern-installation = true
installer.no-binary = null
installer.parallel = true
keyring.enabled = true
solver.lazy-wheel = true
virtualenvs.create = true
virtualenvs.in-project = null
virtualenvs.options.always-copy = false
virtualenvs.options.no-pip = false
virtualenvs.options.no-setuptools = false
virtualenvs.options.system-site-packages = false
virtualenvs.path = "{cache-dir}/virtualenvs"  # /Users/sole/Library/Caches/pypoetry/virtualenvs
virtualenvs.prefer-active-python = false
virtualenvs.prompt = "{project_name}-py{python_version}"
warnings.export = true
```

### Poetry Runtime Logs

```bash session
The same as above
```

**Comment by solesensei** [comment]
I reinstalled poetry from scratch with pipx. But still getting the same error.

**Comment by Secrus** [comment]
This is not a CLI issue. Looks like you are getting a yanked version of our CLI package. Try `pipx inject poetry cleo==2.1.0`, which should fix this issue.

**Comment by Secrus** [comment]
Ref: #9856
